### ISSUE TITLE
IE11 navigator.getGamepads

### ISSUE THREAD

**Issue by thscott** [BabylonJS/Babylon.js#10007]
navigator.getGamepads is undefined in IE11, which stops the engine from working.

Setting that to just return an empty array then leads to issues with wheel events, with the error "Unable to find input 7 for device Mouse in slot 0" issued on every scroll event. This means wheel events aren't working at all for IE11.

I briefly looked at the code but couldn't see anything obvious as to why that is happening.

I am however unsure as to why getGamepads is called so often.
It's called in [DeviceInputSystem._updateDevice](https://github.com/BabylonJS/Babylon.js/blob/7dd5871388045383609111fd79fde70a22a2826f/src/DeviceInput/deviceInputSystem.ts#L569)
which has the comment that the function updates devices every frame.

This however isn't the case. The function is called from [DeviceInputSystem.pollInput](https://github.com/BabylonJS/Babylon.js/blob/7dd5871388045383609111fd79fde70a22a2826f/src/DeviceInput/deviceInputSystem.ts#L134), which in turn is called from [InputManager](https://github.com/BabylonJS/Babylon.js/blob/7dd5871388045383609111fd79fde70a22a2826f/src/Inputs/scene.inputManager.ts#L804), up to 11 times, per input change!! (And looking at [this](https://github.com/BabylonJS/Babylon.js/blob/7dd5871388045383609111fd79fde70a22a2826f/src/DeviceInput/deviceInputSystem.ts#L355), it might be multiple times for some inputs). Just moving the mouse over the scene for one of my projects leads to getGamepads being called more than 100 times per frame, for a scene which has no intention of handling gamepad inputs at all.

Surely checking gamepad state should happen once per frame (as the comment implies), and just loop over all connected gamepads (which are stored, so no need to even call getGamepads), instead of checking (multiple times) if every single input event (all of which from what I can see are pointer or keyboard events) is from a gamepad.

I'm curious what the rationale behind using the device input system (pr [here](https://github.com/BabylonJS/Babylon.js/pull/9789)) is, seeing as for the general use case of mouse and keyboard events on the web, it seems to add a lot of convolution and indirection.

**Comment by deltakosh** [comment]
Hello! please use the forum for discussion and question as stated in the issue template

**Comment by deltakosh** [comment]
Missing forum link: https://forum.babylonjs.com/t/ie11-navigator-getgamepads-babylonjs-no-longer-working-in-ie11/18901/10

**Comment by PolygonalSun** [comment]
Fixes for getGamepads call and mouse wheel issues in PR: https://github.com/BabylonJS/Babylon.js/pull/10013
