### ISSUE TITLE
Webxr not working on oculus rift s (BUT, the ones from the official webxr website works)

### ISSUE THREAD

**Issue by gdefraiteur** [BabylonJS/Babylon.js#10016]
Hello, this morning i tried randomly to use webxr on my oculus rift s,

it work from those examples:

https://immersive-web.github.io/webxr-samples/

but from the ones on babylon, it doesnt, its loading infinitely.

**Comment by deltakosh** [comment]
Do you mind using the forum for question as stated in the Issue template?

cc @RaananW FYI
