### ISSUE TITLE
npm install fails on master

### ISSUE THREAD

**Issue by chase-moskal** [BabylonJS/Babylon.js#10024]
:wave: hello folks!

on latest `master` commit df124c8b187c93430af32180f7ab8659e2c1d711

`npm install` seems to be failing

```
chase@ragnarok-vm:/work/Babylon.js$ npm i
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: babylonjs@5.0.0-alpha.12
npm ERR! Found: typescript@4.2.3
npm ERR! node_modules/typescript
npm ERR!   dev typescript@"^4.2.2" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer typescript@"^2.7 || ^3" from awesome-typescript-loader@5.2.1
npm ERR! node_modules/awesome-typescript-loader
npm ERR!   dev awesome-typescript-loader@"^5.2.1" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/chase/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/chase/.npm/_logs/2021-03-07T00_53_14_263Z-debug.log
```

is this some kind of mistake on my end? i had assumed that after a fresh checkout of master, `npm install` should succeed? i had opened a [related thread on the babylon forums](https://forum.babylonjs.com/t/babylon-master-fails-npm-install/18923), but maybe this is now the appropriate place to file this issue

i'm getting back into game dev, and i'm hoping to start contributing directly to babylonjs! i'm super excited by WebXR!

thanks fellas

**Comment by chase-moskal** [comment]
on debian,
```
chase@ragnarok-vm:/work/Babylon.js$ node -v
v15.10.0
chase@ragnarok-vm:/work/Babylon.js$ npm -v
7.6.0
```

**Comment by sebavan** [comment]
@chase-moskal , did you follow this guide ? https://doc.babylonjs.com/divingDeeper/developWithBjs/howToStart

cause I am not able to repro from the tools/gulp folder. (Please note, we never manually run the scripts in the main folder)

**Comment by sebavan** [comment]
Closing for now, will reopen following up the discussion on the forum if it is proven to be a bug.

**Comment by chase-moskal** [comment]
@sebavan — i was confused by the root `package.json` which i thought was used to install dependencies — instead, babylon is setup in a very unconventional way — but now i have a better understanding

i want to ask: **what is the purpose of the root-level `package.json`?**

considering it does not work to install dependencies, it seems confusing. it lists a large number of devDependencies, but these are not installable? this setup is very unfamiliar to me and hard to understand

being an expert web dev, i had ignored that guide after a quick skim, seeing such basic advice as how to fork, clone, etc — but now i see babylon has very subtle unconventional installation procedures — this is a situation i would be interested to help address and discuss further in my proposal #10025

let's keep this issue closed, thanks
