### ISSUE TITLE
Proposal to modernize and simplify babylon distribution and development

### ISSUE THREAD

**Issue by chase-moskal** [BabylonJS/Babylon.js#10025]
@deltakosh, @sebavan, @RaananW, and many others,

👋 hello friends!  

babylon is an immense, powerful, and irreplaceable framework for the web. the sheer magnitude of the amazing work you all do here is awe-inspiring! thank you for your dedication and contributions!

i have some small ideas, and some big ideas. most importantly for my project, i want babylon to be browser-standards-compliant, which is super easy, all we need to do is add `.js` extensions to all the imports. but i have more radical ideas i'd be willing to work on, and i've been experimenting, so i want to know how far you're willing to go in an effort to modernize and reduce complexity

here is my proposal, perhaps for `babylon@6`, as prototyped in my branch:  
&nbsp; &nbsp; https://github.com/chase-moskal/Babylon.js/tree/modern  
&nbsp; &nbsp; *(note, this branch is not for merging, just demonstrating the ideas)*

## 🏎️ super-fast minimalistic typescript build
- in my branch, you will see i've converted all of babylon's `core` and also `gui` into a single build, that only takes seconds to run
    - it's all built with one simple standard run of `tsc`
    - run an efficient watch routine over all of babylon with `tsc -w`
    - npm scripts `build` and `watch` to do the above
    - with your approval and support, i'd like to continue an effort like this with *all* of babylon's typescript code, so that all of babylon's source is unified under one tree, with one simple build, emitting a single tree of clean es modules, ripe for the taking

## 🔌 standard browser compatibility for es module imports
- simply by adding `.js` extensions to every import, i've made babylon in my branch browser-standards-compliant. and it's backwards-compatible with bundlers
    - even if you disagree with *everything else* in my proposal, i'm certain we'll all agree on this one point: that we should add .js extensions to support native browser standards today (which strictly require the extensions)
    - this part of the proposal could be done in a minor semver bump, as it is backwards compatible
    - it's the minimum i need for babylon to work in my project. but if you like, we can go further!
- this way, people can load babylon natively in the browser, without requiring any build step or bundlers!
    ```html
    <script type="module">
      import {Scene} from "https://unpkg.com/babylonjs/x/core/Scene.js"
        // babylon doesn't currently support this,
        // but this proposal fixes that :)
    </script>
    ```
- browser [import maps](https://github.com/WICG/import-maps) (available today via polyfill [es-module-shims](https://github.com/guybedford/es-module-shims)) will make dependency management easy for users, natively in the browser, even without any special tooling like npm or package.json, allowing direct use of bare-specifiers in plain modules
    - so, it's already common to use bare-specifiers instead of full url's:
        ```js
        import {Scene} from "babylonjs/x/core/Scene.js"
        ```
    - my branch already supports all of this, and is fully backwards compatible with familiar npm workflows involving bundlers
    - this was actually the main motivation for this whole proposal: i was unable currently to load babylon in my modern project, and i don't want to downgrade my project (instead, i want to get involved and contribute!)

## 📦 simplify how babylon is shipped on npm
- consolidate *all* of babylon source code into one npm package
    - nowadays, this is actually efficient,
        - because modern bundlers all support treeshaking,
        - and even native browser esm loads each module selectively
    - so the *total* size of the npm package no longer matters :)
        - we can reduce all the complexity involved with managing multiple packages and their relationships
- there are some improvements we can consider for how babylon is shipped in the npm package:
    - we should ship both the typescript source code with source maps, in addition to the emitted javascript modules
        - this way with source maps, end-users will have a better debugging experience in general
    - we should stop shipping any `index` files
        - because index files destroy tree-shaking and selective loading, people will accidentally load much more than they really need. index files seem handy and convenient, but because they are so easily misused, they can be toxic
        - vscode's autocomplete is really great at finding the right modules to directly import from
    - we should stop shipping any bundles
        - bundles are great, but only for applications, not for libraries!
        - the problem with shipping bundles in libraries, is basically that when another library depends on those bundles, it causes end-users to load multiple redundant copies of entire bundles!
            - if person A releases a cool game entity as an npm package, and they depend on a bundle of `babylon@5.1`, then person B who is using `babylon@5.2` who imports the cool game entity, will end up loading TWO whole babylon bundles!
        - the modern approach is that all bundling and optimizations like minifications are the responsibility of each application -- otherwise people end up bundling multiple bundles and similar problems
            - the original use-case for shipping bundles, used to be for convenient developer experimentation in-browser,
            - however, now with modern native esm support, browsers can now properly import individual modules, which is the new best-practice for easy developer experimentation :)
- the ideal goal, is that babylon becomes a pure, lean, and simple collection of fantastic es modules
    - browser-ready
    - bundler-ready (rollup-ready, webpack-ready)
    - optimization-ready
    - happy developers 🌈

## 🛠️ simplify babylon's build in general
- we should be able to reduce the complexity of the build quite a lot, down to a small collection of standard one-liner npm scripts
    - like my branch's [package.json scripts](https://github.com/chase-moskal/Babylon.js/blob/modern/package.json)
- devs will already be familiar with such a simple setup
- of course, we can't just replace the whole gulp-based build at once -- surely we want to keep large parts of it doing important custom work -- but i'm thinking there are surely significant parts we could simplify and optimize down to these standard familiar one-liner npm scripts that everyone can understand, particularly the typescript build and watch routines

## 🎷 some opinionated quirks in my branch
- instead of a `/dist/` directory, i use the shorter name `/x/`, because it looks better in imports  
    eg
    ```js
    import {Scene} from "babylonjs/x/Scene.js"
    ```
    instead of
    ```js
    import {Scene} from "babylonjs/dist/Scene.js"
    ```
    - similarly i use the shorter `/s/` instead of `/src/`
    - we need the distinction between `s` and `x` so end-users have access to both, and they get a great debugging experience via source maps (unless you want js emitted side-by-side with the ts, which is doable)
    - it's just a fun idea -- totally understandable if you folks still prefer `src` and `dist` -- i just find that when you're directly importing things, the shorter file path is slightly nicer :)
- temporarily, i threw everything into `/_archive/`, from which i had extracted and converted the code from `core` and `gui` thusfar
- if this proposal was approved, i think my actual approach would be to create a script that can automatically recreate the migration over the whole codebase, so that way, we can seamlessly integrate any work from ongoing divergent branches based from the existing babylon `master` branch (so we don't have to freeze any development)

## implementation of this proposal and backwards compatibility
- i understand babylon may not want to make any breaking changes under any circumstances, even with a major semver bump
- i think it *might* be possible to incorporate all or most of this proposal in a net-additive way: perhaps separating a "modern" build routine, from a "legacy" one that CI/CD can worry about :)

## thank you for reading my proposal!

please tell me what aspects you like, and also what you might find worrisome or challenging. i'm eager to answer any questions, and have a discussion. if you like this proposal and approve of it, i'd love to continue this work, and coordinate on how we can seamlessly make it a reality for a future version of babylon

please comment with your thoughts, and feel free to add me on discord at `Chase Moskal#7898` if you'd like to chat in realtime

&nbsp; &nbsp; 🍻 chase

**Comment by sebavan** [comment]
I love the detailed proposal, so let us have a quick chat before we provide a longer answer in the thread :-)

**Comment by deltakosh** [comment]
I did not check your proposal as I trust @RaananW  and @sebavan  to review it but i can already tell you that we will NOT allow any user disruption. I could be ok to change dev experience (like requiring npm install or anything along these lines) but no code breaking change

**Comment by RaananW** [comment]
Hey @chase-moskal,

First - thank you SO MUCH for this proposal. It always amazes me to see how awesome the babylon community is.

We have been discussing build and packaging subjects for quite some time now. Our main goal when discussing these topics is to advance the framework forward, while still maintaining our current userbase, without forcing any change on them. And this is where backwards compatibility comes into play. 

I had a few issues with always keeping backwards compatibility, but had been proven time and time again how important it is. If we suddenly say - "look people, starting babylon 6 you HAVE to change your codebase to fit what we think is the right way to go" we might gain a few new users, but will lose a lot that will be forced to make major changes (in some cases to production code).  Heck, we still support IE11!... So much fun 😉 

But!! We do want to move forward. We just do it a bit differently.  I liked this sentence of yours:

> * even if you disagree with _everything else_ in my proposal, i'm certain we'll all agree on this one point: that we should add .js extensions to support native browser standards today (which strictly require the extensions)

We don't disagree with everything you say. On the contrary - we totally get it as developers using the framework. Whatever can be done without breaking anything for existing users - let's do it. This is the first example. Want to add .js to the imports? That would be great! and if you want to do that yourself and submit a PR, even better. The only condition is that the codebase will not change. It should be added in build-time (or package-time? :-)) only. As I don't see any breaking change to push this to our current es6 packages (`@babylonjs/*`) this is a very welcomed change. We will need to make sure that projects that already relay on these packages are still compiling, but as most are using some form of a bundler to get it to work, i believe there won't be any issue. 

On the subject of fully es6-ing babylon, this is where it gets complicated. We liked most of your suggestions regarding build time (and were planning on tackling most of them after shipping babylon 5), as long as back-compat is kept.  We don't mind adding another npm package, containing the entire sourcecode of the project, compiled to native es6, without bundles (and with the right dependency-tree). We thought it can be called `@babylonjs/modules`, but naming is the last problem here 😄 . This must be done, however, during build time, without changing the current structure. If you are willing to offer a PR that does that, we will be thrilled to review it and merge it if it all works out.  If not (which is perfectly understandable), we will probably tackle it at the end of this year. If you want to discuss exact details, let's switch to the forum and have a conversation about it. 

Once again, thank you so much for taking the time to do that. It's a great feedback that is important to the future of the framework.
