### ISSUE TITLE
navigationPlugin.getNavmeshData

### ISSUE THREAD

**Issue by unicomp21** [BabylonJS/Babylon.js#10032]
We need an awaitable version which runs on a web worker thread.  This would also allow for multiple navmesh bakes to run concurrently.

**Comment by CedricGuillemet** [comment]
@unicomp21 A version using worker thread is available thanks to this PR : https://github.com/BabylonJS/Babylon.js/pull/10656
Let me know if it fits your need.

**Comment by unicomp21** [comment]
perfect, thanks @CedricGuillemet !!!
