### ISSUE TITLE
[GE] [Alpha 1C] Create Theming for Properties Panel

### ISSUE THREAD

**Issue by msDestiny14** [BabylonJS/Babylon.js#10075]
- [x] Creating second style in code
- [x] Responsive design. Percentage vs pixels
- [x] Include all current properties
- [x] Includes new UI layout
- [ ] Includes hoverstate tooltip
- [x] Button controls become text button or image button

![gui3](https://user-images.githubusercontent.com/67929198/111705931-af742700-87fe-11eb-8f89-030ad4d49707.JPG)

**Comment by akapure** [comment]
hi good to know about the UI tool, do we need to update the BJS editor for this or it will be in the online viewer
