### ISSUE TITLE
Simultaneous button presses not working properly

### ISSUE THREAD

**Issue by PolygonalSun** [BabylonJS/Babylon.js#10087]
In the PG below, there are two cubes and when a mouse button is pressed, a corresponding cube will rotate.  Both should rotate at the same time when the left and right are pressed but in 5.0, only one will rotate at a time.

**Repro**
https://playground.babylonjs.com/#T4MJ6I#5

In 5.0, only one cube will rotate.
In 4.2, both cubes will move when the left and right mouse buttons are pressed

Forum post for reference: https://forum.babylonjs.com/t/detect-simultaneously-pressed-mousebuttons/6278

**Comment by sebavan** [comment]
Closed by https://github.com/BabylonJS/Babylon.js/pull/10098
