### ISSUE TITLE
Motion Blur fixes

### ISSUE THREAD

**Issue by thomlucc** [BabylonJS/Babylon.js#10109]
Implement 2 fixes on the Motion blur: 1) for Sprite and 2) for Instances + instanced bones. Fix in prepass PBR + standard and in the Gbuffer

**Comment by thomlucc** [comment]
For you @CraigFeldspar :-)

**Comment by julien-moreau** [comment]
I would love to help!
Is it limited to prepass? Or is geometry buffer renderer should support it as well? The problem will still be visible using the geometry buffer renderer if not fixed

**Comment by thomlucc** [comment]
Thanks @julien-moreau! @CraigFeldspar is on it (and I believe this includes the geometry buffer renderer)

**Comment by CraigFeldspar** [comment]
hi @julien-moreau , to allow the default clear color (0, 0, 0, 0) to be a neutral value for velocity, I was considering removing the mapping (-1, 1) => (0, 1) that we are performing on velocity values, since the velocity texture is already a FLOAT or HALF_FLOAT. Do you happen to think about any problem that may arise with that breaking change ?

**Comment by julien-moreau** [comment]
Hey @CraigFeldspar that would be awesome to allow the clear color and remove the known limitation.
Anyway, I can't really answer now as I have to test it. This was added to ensure more precision in velocity values to avoid artifacts especially when the velocity has a small value.

I'm testing right now :)

**Comment by julien-moreau** [comment]
@CraigFeldspar I can see some artifacts, including in large scenes. Filtering using the alpha value of the velocity buffer may do the trick, what do you think? like:

```glsl
...
vec4 velocityColor = texture2D(velocitySampler, vUV);

 vec2 velocityxy = (velocityColor.rg * 2.0 - 1.0) * velocityColor.a;

vec2 velocity = vec2(pow(velocityxy.r, 3.0), pow(velocityxy.g, 3.0));
velocity *= motionScale * motionStrength;

...
````

**Comment by CraigFeldspar** [comment]
actually @julien-moreau this is a really good solution, since we already use alpha channel to discriminate prepass-compatible pixels
Thanks a lot !

**Comment by thomlucc** [comment]
Fixed with https://github.com/BabylonJS/Babylon.js/pull/10180
