### ISSUE TITLE
Add camera lens shift

### ISSUE THREAD

**Issue by Drigax** [BabylonJS/Babylon.js#10119]
See: https://forum.babylonjs.com/t/add-vertical-shift-to-3ds-max-exporter-babylon-cameras/17480/6?u=drigax

This feature is very useful for Archviz in 3dsMax, where this will allow the user to visually move the horizon, via vertically moving the projection plane. The end goal is to preserve a 2 point perspective of the scene:

https://knowledge.autodesk.com/support/3ds-max/learn-explore/caas/CloudHelp/cloudhelp/2017/ENU/3DSMax/files/GUID-AB01F474-A1BD-4575-916A-988AC964CE4F-htm.html

In order to support this we may need to implment:

- [ ] Transposing the view projection plane
- [ ] view projection plane tilt
- [ ] Tilt correction in order to preserve view projection normal perpendicularity with world up.

**Comment by thomlucc** [comment]
#10530
