### ISSUE TITLE
Incorrect bounds for glTF models with normalized positions

### ISSUE THREAD

**Issue by donmccurdy** [BabylonJS/Babylon.js#10112]
**Repro**

Attached, a version of `WaterBottle.glb` quantized by my (WIP) quantization implementation in https://github.com/donmccurdy/glTF-Transform/pull/59. The model has a number of validation issues that I'm still working on, but it should be able to render in the BabylonJS sandbox now, and doesn't.

[WaterBottleQuantized.zip](https://github.com/BabylonJS/Babylon.js/files/6238605/WaterBottleQuantized.zip)

If you load the model in the sandbox, and then adjust the camera settings...

- Adjust default camera near/far to 0.001-100
- Adjust default camera radius min/max to 0.05-10

... the water bottle appears correctly. Before those adjustments, the screen is empty.

**Screenshot:**

![Screen Shot 2021-03-31 at 11 13 38 AM](https://user-images.githubusercontent.com/1848368/113191242-26072080-9212-11eb-8a48-5a85e7d1d4c2.png)

**Desktop (please complete the following information):**

All.

**Smartphone (please complete the following information):**

All.

**Additional context**

Referring to the code here...

https://github.com/BabylonJS/Babylon.js/blob/5e85e8789e5ecab377aa873624b7c32a5af94a55/loaders/src/glTF/2.0/glTFLoader.ts#L905-L914

... it looks like Babylon.js (as well as three.js, actually) is using the POSITION attribute's `.min` and `.max` property to infer bounds of a mesh primitive, without a more costly traversal of the vertex data. However, the glTF specification states:

> Exporters and loaders must treat these values as having the same data type as accessor's componentType, i.e., use integers (JSON number without fractional part) for integer types and use floating-point decimals for 5126 (FLOAT).

In other words, a normalized accessor will contain normalized integer values in its min/max, and the implementation needs to convert that to floating-point decimals to use as mesh bounds. This becomes an issue for models using `KHR_materials_quantization`, which may choose to use normalized 8-bit or 16-bit integer storage.

**Comment by bghgary** [comment]
@Popov72 Do you mind looking at this? I think this is related to the code you added for using min/max values from glTF.

**Comment by Popov72** [comment]
Going to have a look.
