### ISSUE TITLE
Feature: TAA (Temporal anti-aliasing)

### ISSUE THREAD

**Issue by Zundrium** [BabylonJS/Babylon.js#10120]
This version of AA remains to give the smoothest result (especially when moving) by far in my opinion, so I was wondering, is this a Post-process effect that we can add?

Three.js has it's own implementation here: https://threejs.org/examples/webgl_postprocessing_taa.html.
It also has been talked about before on the HTML5gamedevs forum: https://www.html5gamedevs.com/topic/28727-subpixel-rendering/ where someone was able to implement it with BabylonJS in a commercial product.

What I can see from the Three.js example is that it uses features from SSAA, and I've read it's pretty much one of the more complicated AA techniques out there. So I'm wondering, has this been thought of before but that it's not something easy to add?

**Comment by deltakosh** [comment]
Hey, as mentioned in the github issue template, please go to the forum first to discuss about features.
We are only capturing validated requests here

**Comment by Zundrium** [comment]
@deltakosh My bad, I will most certainly do that. I do think that `You must provide a link to the forum post where the initial discussion happened` feels a bit optional to me, something like along the lines of `We only accept feature requests that are discussed on the BabylonJS forum` might help more for bad readers like me :)

**Comment by deltakosh** [comment]
Well "You must provide a link" seems like you must :D

**Comment by deltakosh** [comment]
That being said let me use your wording now :)
