### ISSUE TITLE
Add Grayscale Depth Map support for Dome

### ISSUE THREAD

**Issue by jaider** [BabylonJS/Babylon.js#10129]
I am trying to add a depth map to a Panoramic 360 view (PG #WP9WDU)
I see in ThreeJS achieving this effect using 2 images (one 360 photo and grayscale depth map), similar to the code of BabylonJS - Height Map.
ThreeJS Example: https://threejs.org/examples/?q=panorama#webxr_vr_panorama_depth

**Discussion**
https://forum.babylonjs.com/t/add-depth-map-support-for-dome/19491

FYI @RaananW

**Comment by RaananW** [comment]
I believe this can be closed.

This playground - https://playground.babylonjs.com/#WP9WDU#31 - shows how to achieve this without changing the photodome class. Adding the parameters required for a displacement map will pollute the configuration object.
