### ISSUE TITLE
Slider control breaks/disappears when passing in a step value greater than 1

### ISSUE THREAD

**Issue by rickfromwork** [BabylonJS/Babylon.js#10146]
The Slider control supports passing in a step value, such that dragging the slider increments it by <step> at a time. This works as expected for values under or equal to 1, but fails on values greater than 1. For greater values, the slider disappears as soon as it receives a pointer down (it is clicked).

Looking at the code, it is hitting a divide-by-zero error in baseSlider.ts's _updateValueFromPointer call,specifically at
`const mult = (1 / this._step) | 0;`
`this.value = this._step ? ((value * mult) | 0) / mult : value;`
It seems like Javascript does not handle decimal values when performing _bitwise_ operations, so the _bitwise OR_ on the first line resolves to 0. Then the next line divides by that value.

Why are bitwise operations being used? Why is **mult** ever being set to 0, given the next line divides by it?

**Repro**
- Bug repro on https://www.babylonjs-playground.com/#NGS9AU#343
- Expected result: Step should increase by 2 at a time
- Current result: Slider disappears (the editor shows the sphere's scaling is NaN)

**Comment by msDestiny14** [comment]
Thank you. Going to look into it now! :)

**Comment by thomlucc** [comment]
Closing as fixed!
