### ISSUE TITLE
Most 3D Controls aren’t pickable by WebXR ControllerPointerSelection

### ISSUE THREAD

**Issue by rickfromwork** [BabylonJS/Babylon.js#10179]
Test scene here: https://www.babylonjs-playground.com/#9K3MRA#384
Reference forum post: https://forum.babylonjs.com/t/most-3d-controls-arent-pickable-by-webxr-controllerpointerselection/19845

After entering VR, you can see that the ray cast by the controller passes right through the holographic button. This is because the button’s meshes are created on the scene’s utility layer, which WebXRControllerPointerSelection doesn’t check during its ray-casting phase. This in turn means that instead of the ray stopping on the surface and rendering a cursor, it passes right through without rendering a cursor.

Note: You can still interact with the button using the ray + motion controller trigger button, you just need to guess as to if the ray is hitting the button.

I feel either controllers shouldn’t interact with 3D controls (though this doesn’t make much sense to me), or the utility layer meshes should be included with the main scene’s meshes for the pick (this seems to already be the case for 2D interactions?).

Note 2: The meshes created in the scene when preparing a MeshButton3D are the only 3D control that WebXRControllerPointerSelection can pick, as the mesh is created on the main scene. This creates a visual inconsistency between the behaviour of different 3D controls.

**Comment by CraigFeldspar** [comment]
@RaananW @deltakosh If it's okay I will have a look into it, since this is something i will need very shortly  😄

**Comment by deltakosh** [comment]
Sure!

**Comment by RaananW** [comment]
I'm actually checking this soon because of the near interaction PR that needs that.
If you do want to look into that, objects in utility layers are not part of the piecing mechanism of the scene and are therefore excluded from direct interactions. I believe this is the issue, but was about to check that on Friday.

**Comment by CraigFeldspar** [comment]
@RaananW I've made a proposal in #10363 to fix that
