### ISSUE TITLE
PrePassRenderer fails to rebuild

### ISSUE THREAD

**Issue by Popov72** [BabylonJS/Babylon.js#10172]
The `PrePassRendererSceneComponent.rebuild` method is implemented like this:
```typescript
/**
 * Rebuilds the elements related to this component in case of
 * context lost for instance.
 */
public rebuild(): void {
    // Release textures first
    this.scene.disablePrePassRenderer();

    // Re-enable
    this.scene.enablePrePassRenderer();
}
```
However, on this PG: https://playground.babylonjs.com/#PIZ1GK#172

if you try to execute `scene.disablePrePassRenderer(); this.scene.enablePrePassRenderer();` in the console, the SSR does not work anymore.

**Comment by deltakosh** [comment]
@CraigFeldspar any update?

**Comment by CraigFeldspar** [comment]
@deltakosh as seen offline with @Popov72, nothing bad yet, but impacts WebGPU. Will check what's wrong as soon as I'm done with #10109

**Comment by CraigFeldspar** [comment]
prepass works well, but SSR doesn't seem to get any valid texture output, probably it is still feeding on the disposed ones. I'm looking a bit deeper to see if it is a problem we should take care of inside the prepass, or on the postprocess level.
![Capture](https://user-images.githubusercontent.com/3762615/115240017-a0470880-a11f-11eb-9214-b9908b2c414d.JPG)

**Comment by CraigFeldspar** [comment]
got it, SSR stores `prePassRenderer` as a variable on its creation, meaning it doesn't update when we rebuild the prepass renderer, I'll open a PR
