### ISSUE TITLE
Order-independent transparency (OIT)

### ISSUE THREAD

**Issue by Vinc3r** [BabylonJS/Babylon.js#10187]
As discussed on the forum [#1](https://forum.babylonjs.com/t/order-independent-transparency/14262), [#2](https://forum.babylonjs.com/t/transparent-material-clipping-or-how-is-this-called/7353/6), [order-independent transparency](https://en.wikipedia.org/wiki/Order-independent_transparency) could be a nice feature to add, helping people to handle some alpha issues.

Here a webGL implementation example: [WebGL 2 Example: Weighted, Blended Order-independent Transparency](https://tsherif.github.io/webgl2examples/oit.html), and some usecases [about why it is useful](https://docs.aws.amazon.com/lumberyard/latest/userguide/graphics-rendering-order-independent-transparency.html).

**Comment by marcusdiy** [comment]
Yes, I've been struggling with semitransparent objects too for a couple of days

**Comment by marcusdiy** [comment]
Oh wow, are you really working on it? 🤗 Would be a killer feature as very few, if any, framework seems to support this feature for now. I'm constrained to solid using solid shapes on transparent intersections. But with this we can be even more creative! Kudos!

**Comment by deltakosh** [comment]
In the mean time we can still enable facet sort:https://doc.babylonjs.com/divingDeeper/mesh/facetData#facet-depth-sort
