### ISSUE TITLE
Error when reading DepthTexture of RenderTargetTexture

### ISSUE THREAD

**Issue by GoodLuckIce** [BabylonJS/Babylon.js#10197]
https://www.babylonjs-playground.com/#TV5FSK

[.WebGL-00004DFC00141C00] GL_INVALID_OPERATION: Mismatch between texture format and sampler type (signed/unsigned/float/shadow).

**Comment by sebavan** [comment]
Please discuss issues on the forum : forum.babylonjs.com first.

In your case you are creating a comparison sampler or shadow sampler but use it as a depth sampler:
https://www.babylonjs-playground.com/#TV5FSK#2

**Comment by GoodLuckIce** [comment]
thank you very much.
But I actually want to get the correct depth value, but the obtained depth value is equal

https://www.babylonjs-playground.com/#TV5FSK#3

I need to use depth to determine the final result of the two rendering results, but the value of depth is equal, which is an error.

**Comment by GoodLuckIce** [comment]
@sebavan  I really hope to get your help, I think it may be a bug in the rendering engine
