### ISSUE TITLE
Can't get the depth value correctly

### ISSUE THREAD

**Issue by GoodLuckIce** [BabylonJS/Babylon.js#10198]
https://www.babylonjs-playground.com/#TV5FSK#3

I need to use depth to determine the final result of the two rendering results, but the value of depth is equal, which is an error.

**Comment by sebavan** [comment]
As discussed on the previous issue, the forum shoud be the start of the discussion for this.

**Comment by GoodLuckIce** [comment]
> As discussed on the previous issue, the forum shoud be the start of the discussion for this.

@sebavan  I think this is a bug in the rendering engine
