### ISSUE TITLE
Error when reading DepthTexture of RenderTargetTexture

### ISSUE THREAD

**Issue by GoodLuckIce** [BabylonJS/Babylon.js#10205]
https://forum.babylonjs.com/t/error-when-reading-depthtexture-of-rendertargettexture/20021

https://www.babylonjs-playground.com/#TV5FSK#11

I have the same error in edge chrome firefox browser

**Comment by sebavan** [comment]
Fixed by https://github.com/BabylonJS/Babylon.js/pull/10206
