### ISSUE TITLE
how to load a .ply format mesh ?

### ISSUE THREAD

**Issue by Rainy-Bear** [BabylonJS/Babylon.js#10217]
We only accept feature requests that are discussed on the BabylonJS forum

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Discussion**
You must provide a link to the forum post where the initial discussion happened

**Comment by mochsner** [comment]
Currently no plans to support .ply according to https://forum.babylonjs.com/t/how-to-add-pointcloud-file-ply-to-babylon-js/9173
