### ISSUE TITLE
ApplyDelta not working

### ISSUE THREAD

**Issue by alinaiim** [BabylonJS/Babylon.js#10226]
**Repro**
- Bug repro on [playground](https://playground.babylonjs.com/#XZ4FC4#3):
- Expected result: The metallic should be 0.6 and clear coat should be enabled
- Current result: The metallic is 0.9 and the clear coat is not enabled

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome

**Additional context**
The getDelta function is registering all the changes right 
The ApplyDelta function is not applying changes to the model

**Comment by Popov72** [comment]
Actually it does work for metallic: the delta records what happens between the call to `track` and `getDelta`. As you don't change the metallic value between those two calls, no changes are recorded so the metallic value is not updated (from the value it currently has) when you apply the delta file.

It seems the apply delta procedure does not work only for sub-objects.
