### ISSUE TITLE
IWebXRHandTrackingOptions onHandJointMeshGenerated should take an abstract mesh constructor so that instanced meshes are supported

### ISSUE THREAD

**Issue by chrisfromwork** [BabylonJS/Babylon.js#10247]
Synced with @RaananW over teams. Right now IWebXRHandTrackingOptions uses some different mesh constructors that could be converted to support abstract meshes so that they also support instanced meshes

**Comment by bghgary** [comment]
Can this be closed?

**Comment by RaananW** [comment]
Yes we can! 😎
