### ISSUE TITLE
When using SceneLoader.LoadAssetContainerAsync does not correctly load GLTFs with PBR Transmission

### ISSUE THREAD

**Issue by vBitreel** [BabylonJS/Babylon.js#10246]
**Repro**
- Bug repro on [playground](https://playground.babylonjs.com/#WGZLGJ#2849):
- Expected result: Same as here https://playground.babylonjs.com/#WGZLGJ#2848
- Current result: Glass spheres appear opaque.

**Screenshots**
Current result:
![image](https://user-images.githubusercontent.com/69317776/115764046-ff658100-a39c-11eb-9131-be42462fc35f.png)
Expected result:
![image](https://user-images.githubusercontent.com/69317776/115764196-30de4c80-a39d-11eb-9e37-ec9772471f2b.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version Version 89.0.4389.128 (Official Build) (64-bit)

**Additional context**
https://forum.babylonjs.com/t/transmissive-materials-sometimes-using-env-map-instead-of-actual-translucency/20203/3

**Comment by bghgary** [comment]
The conclusion we made in the forum is not exactly right. Transmission helper should work correctly in this case. I'm not totally sure what happened, but this bug no longer repros. My guess is that one of the transmission helper fixes from @Popov72 fixed this one also.
