### ISSUE TITLE
Create Screenshot is broken

### ISSUE THREAD

**Issue by CedricGuillemet** [BabylonJS/Babylon.js#10241]
Simple PG to take screenshot. Work with 4.2, not for 5.0 (only background is visible in capture)

https://playground.babylonjs.com/#0H83E8

[EDIT] @Popov72 made it work with `onEndFrameObservable` https://www.babylonjs-playground.com/#JKA0QS#2 But the behavior is different with previous version.

**Comment by Popov72** [comment]
The PG does not always work for me, even in 4.2: we should wait for all resources to be ready before taking a screenshot.

This PG is always working for me, in 4.2 and 5.0:

https://playground.babylonjs.com/#0H83E8#1

**Comment by Popov72** [comment]
@CedricGuillemet I think we can close this issue as it is not an issue in Babylon but in the PG instead?

**Comment by CedricGuillemet** [comment]
@Popov72 Sounds good. Closing.
