### ISSUE TITLE
Reflection probe as a transform node

### ISSUE THREAD

**Issue by m-dastagir** [BabylonJS/Babylon.js#10268]
We only accept feature requests that are discussed on the BabylonJS forum

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Discussion**
You must provide a link to the forum post where the initial discussion happened
I would like a feature where we can view reflection probe in the inspector window as a transform node. Such that the reflection probe can be moved/scaled. Kindly provide this feature. It is very much helpful.

**Comment by m-dastagir** [comment]
Hi, yes it was recently discussed here:
https://forum.babylonjs.com/t/reflection-probe-not-showing-up-in-inspector-window/20389

**Comment by deltakosh** [comment]
Sorry but you simply opened an issue with the template content :)
