### ISSUE TITLE
Database : IOfflineProvider - .manifest URL creation

### ISSUE THREAD

**Issue by gabrielheming** [BabylonJS/Babylon.js#10278]
I have created the thread below on the forum concerning the .manifest URL creation.

https://forum.babylonjs.com/t/database-iofflineprovider-manifest-url-creation/18455

As I said in the post, the situations are pretty forward. However, I got a bit delayed while I was trying to cope with the URL object and IE 11 situation. Because we could use one of the below approaches:

- Find a polyfil package;
- Create its polyfill (it seems to be the case for Promise for instance);
- Use regular expressions instead of URL.

I just didn't know how to proceed.

**Comment by deltakosh** [comment]
Here is a better idea: if URL object do not exist stay with the current behavior

We are slowly moving out of ie11 support so that should be fine

**Comment by RaananW** [comment]
> We are slowly moving out of ie11 support so that should be fine

This kind of sentence will NEVER stop making me extremely happy. 



> if URL object do not exist stay with the current behavior

Perfect, i'll take care of that

**Comment by gabrielheming** [comment]
So, if I do not need to care about IE11, the proposal on the thread is enough. In that case, I can send the PR as is.
