### ISSUE TITLE
Exclude meshes from SSAO2 pipeline

### ISSUE THREAD

**Issue by Queatz** [BabylonJS/Babylon.js#10275]
**Is your feature request related to a problem? Please describe.**
SSAO renders on the yellow skybox, making the sky black:
![ảnh](https://user-images.githubusercontent.com/540620/116502479-33e3ac00-a879-11eb-98a5-377d125e2340.png)

**Describe the solution you'd like**
It should be easy to exclude skybox from SSAO
There should be a way to exclude meshes or materials, i.e. `ssao2Pipeline.excludeMeshes = [ skyboxMesh ]`

**Discussion**
https://www.html5gamedevs.com/topic/34132-how-i-can-exclude-skybox-from-ssao/

**Comment by deltakosh** [comment]
Hello do you mind checking on the "new" forum first: forum.babylonjs.com?

Thanks a lot

**Comment by Queatz** [comment]
@deltakosh Only thing I can find is [this](https://forum.babylonjs.com/t/adding-contrast-to-loaded-models-without-affecting-the-skybox-texture/17549/15) and looks like they also could not find a good solution

**Comment by deltakosh** [comment]
Sorry I meant: please discuss that topic on the new forum (Create an thread) so we can see how we can help

**Comment by Queatz** [comment]
Okay cool will do
