### ISSUE TITLE
Physics imposters are not created correctly for negatively scaled meshes.

### ISSUE THREAD

**Issue by wilcoschoneveld** [BabylonJS/Babylon.js#10283]
**Repro**
- Bug repro: https://playground.babylonjs.com/#TWVYMQ#7
- Expected result: BoxImposter should match the cube mesh
- Current result: BoxImposter is incorrect

**Screenshots**
![image](https://user-images.githubusercontent.com/3064588/116719792-c43a0200-a9db-11eb-8c21-3d2895dfc849.png)

**Additional context**
I stumbled upon this issue when trying to create imposters for imported gltf scenes created with Blender. See playground [here](https://playground.babylonjs.com/#TWVYMQ#5). I see two use cases for which solving this problem would help;

1. When a user wants to create an imposter for a purposely flipped mesh, such that it has a desired orientation
2. When a user wants to create an imposter for an imported mesh from a different coordinate system

A workaround exists by baking the scaling into the mesh, like so: https://playground.babylonjs.com/#TWVYMQ#6

**Comment by wilcoschoneveld** [comment]
I created a PR to address this issue which solves this problem as follows:

1. When calculating `getObjectExtendSize` it uses an `Math.abs`-like method to ensure any negative scaling is negated.
2. When calculating `getObjectCenter` it uses an `Math.sign`-like method to position the center correctly

I was not confident with step 2 and I'm not sure how to go about setting up a bunch of validated tests for this

Thanks!

**Comment by CedricGuillemet** [comment]
Let me take a look.

**Comment by sebavan** [comment]
@CedricGuillemet  any news on this one ?

**Comment by CedricGuillemet** [comment]
@sebavan nop, still on my todo list ...

**Comment by CedricGuillemet** [comment]
I'm working on it today!
