### ISSUE TITLE
On complex models, Sharing EdgesRenderer on Instances fails (also at random progress)

### ISSUE THREAD

**Issue by Ninili** [BabylonJS/Babylon.js#10289]
**Use Github issues ONLY for validated bugs. PLEASE DISCUSS THEM ON THE FORUM FIRST!**

We have a really active forum to help answering questions (https://forum.babylonjs.com/)

# Bugs

- Bug repro on [playground](https://playground.babylonjs.com):
https://playground.babylonjs.com/#303G1F#2
- Expected result:
Not getting the error "Uncaught TypeError: Cannot set property '0' of undefined" when rendering
- Current result:
Getting the error "Uncaught TypeError: Cannot set property '0' of undefined" when rendering

Please be aware that "edgeing" (not loading) this model can take some seconds as it's quite complex.

In the playground I have also a simple model (just boxes and their instances) and there it works fine.
It has to be some special kind of mesh or configuration that triggers this error!
I thought it was something wrong in my code, but I could reproduce this here in a playground. Would be great to have a solution for it, right now, I have to calculate the edges for EVERY instance separately which takes about double the time.

Thank you for looking into this :-)

**Comment by deltakosh** [comment]
> Use Github issues ONLY for validated bugs. PLEASE DISCUSS THEM ON THE FORUM FIRST!
We have a really active forum to help answering questions (https://forum.babylonjs.com/)

I thought it would be clear enough :) Closing for now as this first need to be discussed on the forum
