### ISSUE TITLE
Exclude materials from ES6 bundle

### ISSUE THREAD

**Issue by Kesshi** [BabylonJS/Babylon.js#10327]
Some parts of BabylonJs directly import and use different materials. Even if the application does not use them they still end up in the bundle. This should be avoided if possible. 

Forum discussion: https://forum.babylonjs.com/t/how-to-get-rid-of-standardmaterial-in-es6-bundle/20573

Known places:
- [x] src/Rendering/geometryBufferRenderer.ts  (PBRMaterial, StandardMaterial)
- [x] serializers/src/glTF/2.0/glTFExporter.ts  (MultiMaterial, StandardMaterial)
- [x] serializers/src/glTF/2.0/glTFMaterialExporter.ts  (StandardMaterial, PBRBaseMaterial, PBRBaseSimpleMaterial, PBRMaterial, PBRMetallicRoughnessMaterial, PBRSpecularGlossinessMaterial)

**Comment by RaananW** [comment]
I might make this issue a little bigger (or, well, way bigger). This is the abstracted version of the description:
1) Eliminate direct Constants as much as possible. Move all to constants to an importable file, while referencing them where they are currently at. This will eliminate the need to import a class for a single value.
2) Eliminate the use of instanceOf as much as possible, especially if the class is loaded just for the comparison
3) Go over imports of widely used classes, make sure it is at a minimum.

**Comment by deltakosh** [comment]
@RaananW I will create a new issue for your ideas so we can close this one
