### ISSUE TITLE
NME bug

### ISSUE THREAD

**Issue by unicomp21** [BabylonJS/Babylon.js#10321]
The derivative block doesn't seem to be working.  Repro can be seen here:
https://nodematerial-editor.babylonjs.com/#ND6Z9D

**Comment by unicomp21** [comment]
8:8:33: Shader compilation error: VERTEX SHADER ERROR: 0:69: 'dFdx' : no matching overloaded function found ERROR: 0:69: '=' : dimension mismatch ERROR: 0:69: '=' : cannot convert from 'const mediump float' to 'highp 3-component vector of float' ERROR: 0:70: 'dFdy' : no matching overloaded function found ERROR: 0:70: '=' : dimension mismatch ERROR: 0:70: '=' : cannot convert from 'const mediump float' to 'highp 3-component vector of float'

**Comment by deltakosh** [comment]
why did you totally ignore our template?
anyway....

**Comment by unicomp21** [comment]
@deltakosh apologies, was in a hurry this morning.  thought repro would be sufficient.

**Comment by Popov72** [comment]
After this fix (#10326) is applied, you will have to set the target of the `Transform` block to **Fragment** so that the derivatives are evaluated in the fragment shader.

**Comment by unicomp21** [comment]
Thanks!
