### ISSUE TITLE
PrePassRenderer sometimes does not render geometry with alpha blending

### ISSUE THREAD

**Issue by CraigFeldspar** [BabylonJS/Babylon.js#10337]
**Repro**
- Bug repro on [playground](https://playground.babylonjs.com/#PIZ1GK#255):
- Expected result: Correct SSR reflections
- Current result: Not correct reflections

**Screenshots**

**Additional context**
Geometry of the reflective plane is not rendered at all in PrePassRenderer when it has an alpha value < 1.

**Comment by thomlucc** [comment]
Closing as it will be taken care of with #13003
