### ISSUE TITLE
Importing inspector into es6 bundle overrides validate setting on SceneLoader

### ISSUE THREAD

**Issue by br-matt** [BabylonJS/Babylon.js#10343]
**Repro**
packages:
```
    "@babylonjs/core": "5.0.0-alpha.20",
    "@babylonjs/inspector": "5.0.0-alpha.20",
    "@babylonjs/loaders": "5.0.0-alpha.20",
```
    
add `import "@babylonjs/inspector"` into your bundle 

use the following code snip

```
SceneLoader.OnPluginActivatedObservable.add(function (loader) {
    loader.validate = false;
    loader._validate = () => {
        console.log("loader validate is: ", loader.validate)
    }
})
```

Loader validate will be true when inspector is present in the bundle.

--------

We have url parameters we use on dev builds to control bringing the inspector up or not. For now setting _validate on the loader to an empty function gets around the problem.

**Comment by bghgary** [comment]
For reference: https://forum.babylonjs.com/t/script-tag-for-meshopt-decoder-is-getting-added-for-every-glb/20595

I think the inspector should not be turning validation on automatically. I have ideas on some of the glTF options being handled in the inspector, but haven't found time to implement.

**Comment by deltakosh** [comment]
What I can do is turn it off by default, and enable it in the PG and the sandbox

THoughts?

**Comment by bghgary** [comment]
Yes, that was how it worked originally at some point. I don't remember why it doesn't work this way now.

**Comment by deltakosh** [comment]
Will work on that this week!

**Comment by deltakosh** [comment]
Ok done. Only Sandbox will enable it :) Undefined elsewhere

**Comment by bghgary** [comment]
@deltakosh Can we close this?

**Comment by deltakosh** [comment]
Sure we can!
