### ISSUE TITLE
Add tabbed editing to the Playground

### ISSUE THREAD

**Issue by Popov72** [BabylonJS/Babylon.js#10361]
What about having tabs in the Playground to edit the source code?

Something like that (warning: bad coder art, it's only to have a visualization of the things):
![image](https://user-images.githubusercontent.com/4152247/118154347-39172e00-b417-11eb-9146-bfd111523243.png)

The only change in the source code would be to have a separator to indicate when a tab starts:
```javascript 
// TABSEPARATOR title="Main"
var createScene = function() {
    ...
};
// TABSEPARATOR title="Terrain Generator"
class TerrainGenerator {
    ...
}
// TABSEPARATOR title="Erosion"
class Erosion {
    ...
}
// TABSEPARATOR title="Terrain shader"
BABYLON.ShadersStore["terrainPixelShader"] = `...`;
```    

So that would be fully compatible with the existing playground and we would still be able to edit the source code as a whole, without tabs (we could add an option "Use tabbed editing" to switch/unswitch to/from this new mode).
 
We should be able to add/remove and move tabs (as the order of the tabs is the order in which the code is concatened before running/saving it).
 
That would help working with bigger PGs.

One thing I'm unsure is how to make it work with intellisense: we should have intellisense in a tab for objects in other tabs. So Monaco should be aware of the code in the other tabs when editing the current one.

**Comment by sebavan** [comment]
Closed in favor of #10551 might be reopen depending on the final design.
