### ISSUE TITLE
Babylon running at 100% CPU (even with simple rendering)

### ISSUE THREAD

**Issue by LanderZander** [BabylonJS/Babylon.js#10377]
I have personally [along with other users] been experiencing egregiously high CPU rates while running even modest Babylon renders. 

For example, I loaded up the Babylon Playground: https://www.babylonjs-playground.com/debug.html#PPC2HF
I checked my CPU usage as my fans started firing off, and saw that it was 100%. An Inspect-Element Performance Monitor showed insane levels: http://prntscr.com/130opj1

I created a profile while checking Performance, as well, in case it helps isolate the issue: https://drive.google.com/file/d/1ASzFTwK6rnf3Q6kIl-6qBcPESwfOe2lH/view

Finally, I have a GP63 MSi Leopard 8RD laptop, so I am running an Intel(r) UHD Graphics 630, along with an NVIDIA GeForce GTX 1050 Ti, and all drivers are updated. A buddy of mine with an older Lenovo laptop is getting similar values, too.

I have been trying to adjust settings to figure this out, but to no avail. Ultimately, I am making this report, as nothing else I [or cohorts] does can seem to impact this.

My device specifications:
MSI: Intel(r) Core(TM) i7-8750H CPU @ 2.20GHz 2.20 GHz, 16.0Gb Ram
64-bit operating system, x64-based processor
Windows 10 Home
2004

Any assistance, or fixes for this particular issue, would be greatly appreciated!
~LanderZ

**Comment by EricEisaman** [comment]
@LanderZander Which browser and version are you using?

**Comment by LanderZander** [comment]
Many apologies; I forgot such an obvious point!

Both of us experiencing this issue are using Google Chrome: Version 90.0.4430.212 (Official Build) (64-bit)

**Comment by deltakosh** [comment]
Hey we ask people to discuss questions and everything not already validated on the forum (forum.babylonjs.com) as mentioned in the GitHub issue template.

Kindly closing for now(please simply post it on the forum)
