### ISSUE TITLE
[Viewer] WebXR support

### ISSUE THREAD

**Issue by talanc** [BabylonJS/Babylon.js#10389]
Is native WebXR support for the viewer on the roadmap?

By default it uses WebVR, which no longer works on the latest browsers.
You can use WebXR via the Babylon WebVR using the useXr option, like so:
<babylon model="..." **vr.vr-options.use-xr="true"**></babylon>

**Comment by deltakosh** [comment]
Hey please use the forum for questions ;)

**Comment by deltakosh** [comment]
forum.babylonjs.com
