### ISSUE TITLE
Render SVG on GPU

### ISSUE THREAD

**Issue by awesome-developer-20** [BabylonJS/Babylon.js#10417]
Since earcut is already a dependency of babylon.js, could you implement vector bezier path triangulation to render svg like three.js does. Also, can you then add svg parser that parses svg and covers that in path to be rendered.

Links:
1. [Three.js feature issue](https://github.com/mrdoob/three.js/issues/5959)
2. [Three.js vector path trangulation code](https://github.com/mrdoob/three.js/tree/dev/src/extras)
3. [Three.js svg parser code](https://github.com/mrdoob/three.js/blob/dev/examples/jsm/loaders/SVGLoader.js)
4. [Three.js SVG Example](https://threejs.org/examples/#webgl_loader_svg)
5. [Three.js SVG Example Code](https://github.com/mrdoob/three.js/blob/master/examples/webgl_loader_svg.html)

**Comment by deltakosh** [comment]
Please use the forum as stated in the issue template
