### ISSUE TITLE
Multiple objects leaks when loading assets with scene loader

### ISSUE THREAD

**Issue by bghgary** [BabylonJS/Babylon.js#10433]
**Repro**
1. Open https://playground.babylonjs.com/#WV6GBY in Chromium-based browser.
  (It's easier to repro with localDev to avoid playground specific issues)
2. Open the development console.
3. Type `queryObjects(Promise)`

Current result:
![image](https://user-images.githubusercontent.com/19158740/120033261-35a3ab00-bfb0-11eb-9806-9021460713a9.png)
(Note that some pending ones are leaks from the calling `queryObjects` itself)

Expected result:
* No TypedArray, AssetContainer, or any other objects from scene loader should be leaked via leaked Promises

See forum for more context: https://forum.babylonjs.com/t/i-discovered-the-worst-and-most-insidious-memory-leak-in-babylonjs-history/21170

**Comment by bghgary** [comment]
#10434 fixes the AssetContainer one. If we remove the onDisposeObservables in loadAssetContainerAsync, it fixes the leak, but I can't explain why.

https://github.com/BabylonJS/Babylon.js/blob/master/loaders/src/glTF/glTFFileLoader.ts#L612-L621
https://github.com/BabylonJS/Babylon.js/blob/master/loaders/src/glTF/glTFFileLoader.ts#L626-L634

**Comment by bghgary** [comment]
Also note that the GLTFFileLoader is also being leaked:

![image](https://user-images.githubusercontent.com/19158740/120033926-2113e280-bfb1-11eb-9586-5d17dbbbe33e.png)

One of them is from the inspector which can be ignored.

**Comment by Popov72** [comment]
Removing the enclosing `return Promise.resolve().then(() => {` ... `});` will get rid of the `Array`, `VertexBuffer` and `TypeArray` leaks.

I don't think it is needed, simply returning `this._loader.importMeshAsync(...)` should be enough.

**Comment by Popov72** [comment]
I did some testing, it seems that using a function that is declared inside the `promise.then` or even simply inside the function in which we use `promise.then` is enough to leak the promise.

In the example above, `material.onDisposeObservable.addOnce(() => void(0))` is enough to leak. `material.onDisposeObservable.addOnce(function() {})` also leaks.

Even declaring `const myFunc = function() {};` inside `loadAssetContainerAsync` but before `return Promise.resolve().then(() => {` will leak if we do `material.onDisposeObservable.addOnce(myFunc)`.

Only if `myFunc` is declared outside `loadAssetContainerAsync` (as a method of `glTFFileLoader` for eg) the promise does not leak.

**Comment by bghgary** [comment]
> I don't think it is needed, simply returning this._loader.importMeshAsync(...) should do the job.

We have to wrap it for the exceptions. Otherwise, the exceptions will be synchronous.

**Comment by Popov72** [comment]
Ah too bad...

**Comment by bghgary** [comment]
@deltakosh and I are working on this already.
