### ISSUE TITLE
Add 4D simplex noise

### ISSUE THREAD

**Issue by unicomp21** [BabylonJS/Babylon.js#10446]
We only accept feature requests that are discussed on the BabylonJS forum

**Is your feature request related to a problem? Please describe.**
Being able to index simplex noise by x,y,z,time opens up new kinds of effects.

**Describe the solution you'd like**
Add 4D simplex noise.  See towards the end of forum discussion.

**Discussion**
https://forum.babylonjs.com/t/worley-noise-in-nme/21278/8

**Comment by unicomp21** [comment]
If possible, we also need matching typescript versions of NME simplex and worley noise functions for things like detecting camera collisions with a boundary in a scalar noise field, using the cpu.

**Comment by deltakosh** [comment]
I'm flagging as help wanted as I do not plan to work on it but happy to merge it if someone volunteers to work on it

**Comment by stegu** [comment]
Hoping to be able to supply it. :) Journal article in the works, need to publish, or at least have the paper accepted, before release. The downside of being a university researcher. The time I am allowed to pursue my own ideas at work needs to end up in a publication now and then.

**Comment by deltakosh** [comment]
We do now have Voronoi, cloud and Worley3D in. Should be enough to cover the need.
Please feel free to reopen if I'm wrong
