### ISSUE TITLE
Leverage compute pressure

### ISSUE THREAD

**Issue by deltakosh** [BabylonJS/Babylon.js#10464]
Source: https://web.dev/compute-pressure/

The overall idea would be to expose these values in the inspector and to also uses them as targets for the SceneOptimizer

We should surface them in the API for the users to be able to simply consume them as well

I would also add a new tool in the inspector: the perf monitor. A graph displaying bars during the last x seconds (sliding window) of things like:
- cpu load
- gpu frame time
- fps
- etc...
These options can be turned on/off in the inspector

A bit like that:
![image](https://user-images.githubusercontent.com/1306056/121087047-cb052300-c798-11eb-9895-3a62afdc67d9.png)

but inside the inspector

**Comment by deltakosh** [comment]
I think we could expose that info through 2 ways:
- a direct request..like engine.computePressure property
- an observable approach like: onComputePressureChanged (and we use internally 4 thresholds: 0.25, 0.50, 0.75 and 0.9)
Thoughts?

**Comment by sebavan** [comment]
Yup I kind of like it and it should be doable to add it into native to in this way @bghgary  ?

**Comment by sebavan** [comment]
Also it does not seem there is a direct query available so we might need a granular array of default values to convert an get callbacks often :-)

**Comment by bghgary** [comment]
> Yup I kind of like it and it should be doable to add it into native to in this way @bghgary ?

Doesn't seem hard. Should be doable.
