### ISSUE TITLE
New frustum culling strategy

### ISSUE THREAD

**Issue by RaananW** [BabylonJS/Babylon.js#10462]
Under very specific conditions, the current frustum strategy we are using can return false positives. A simple example:

https://playground.babylonjs.com/#E56SFZ#4

The lines of the near square are green when a specific mesh is in frustum and red when it is not. You will notice that the lines are green, though you can't see the object. move the view up and right and you will see the object in hand.
This test also depends on the size of your screen, so you might need to change the camera's rotation to experience it.

This is not a bug. We are experiencing false-positives in that case, which will set certain meshes active, even though they are not. This will not prevent rendering.

There are further checks that can be done in order to eliminate those false positives, but they might be CPU intensive and only make sense in certain experiences. 
An interesting read - https://www.researchgate.net/publication/2803988_Optimized_View_Frustum_Culling_Algorithms_for_Bounding_Boxes

**Comment by deltakosh** [comment]
Closing due to no traction
