### ISSUE TITLE
Slider3D does not slide 1-1 with pointer when scaled

### ISSUE THREAD

**Issue by rickfromwork** [BabylonJS/Babylon.js#10486]
If a slider3D is scaled in the X direction (along the length of the slider), grabbing and dragging the slider moves it either faster or slower than the cursor, depending on if the slider was scaled up or down, respectively.

An example of a scaled down, normal, and scaled up slider:
https://www.babylonjs-playground.com/#IFDI9M#1

**Comment by RaananW** [comment]
After a little research - 
The `PointerDragBehavior` is not taking parents scaling into account when setting the delta and position on the plane. This PR set the scaling to the node of slider3d, which is the parent of both the button and the slider.

**Comment by RaananW** [comment]
Any update on this one?

**Comment by sebavan** [comment]
@rickfromwork is it still an issue ?
