### ISSUE TITLE
Add a way to remove instantied entries created from assetContainer.instantiateModelsToScene

### ISSUE THREAD

**Issue by bghgary** [BabylonJS/Babylon.js#10488]
See https://forum.babylonjs.com/t/when-importing-a-mesh-from-a-glb-file-its-geometry-is-null/21479/6

After calling `assetContainer.instantiateModelsToScene`, it would be useful to have some function that removed all the created entries.

**Comment by thomlucc** [comment]
Closing as no demand. Feel free to re-open.
