### ISSUE TITLE
Consider offering a simplified hand tracking mesh

### ISSUE THREAD

**Issue by rgerd** [BabylonJS/Babylon.js#10482]
We currently use a [default hand mesh](https://assets.babylonjs.com/meshes/HandMeshes/r_hand_rhs.glb) that contains 5400 vertices (10800 for both hands). The [hands now officially provided by WebXR](https://github.com/immersive-web/webxr-input-profiles/tree/main/packages/assets/profiles/generic-hand) are 1300 each (2600 for both hands, although they make use of indices to bring the triangle count to a higher value than our default hand mesh). 

On HoloLens, we are quite constrained in rendering power, and so we need to be sparing about how much geometry we render to the scene, especially for things like hands.

We might want to consider either using the WebXR hand meshes, reducing our default hand mesh, or offering a reduced hand mesh as an option.

**Comment by RaananW** [comment]
@PatrickRyanMS has optimized our mesh and it has now less vertices than the webxr hands - https://github.com/BabylonJS/Assets/pull/42

**Comment by RaananW** [comment]
Closing for now. Please reopen if needed.

We can offer a configuration option to load the webxr hand meshes, but I honestly don't see a reason to do that. Might be something we can offer in the documentation (how to use the custom hand meshes to load different meshes).
