### ISSUE TITLE
Consider allowing customization of default hand mesh colors

### ISSUE THREAD

**Issue by rgerd** [BabylonJS/Babylon.js#10480]
We currently have the colors for the default hand tracking mesh hard-coded:
https://github.com/BabylonJS/Babylon.js/blob/7bed709f6a7ca9fed85859029ee57a713f9fd9fb/src/XR/features/WebXRHandTracking.ts#L434-L439

It would be nice to allow customization of these colors through `IWebXRHandTrackingOptions`.

**Comment by RaananW** [comment]
Sure! Makes a lot of sense. this can be a part of the configuration.
Seeing you are working on revamping the hands, do you want to add that as well?
