### ISSUE TITLE
Objects in XR are ~10x larger than in the playground

### ISSUE THREAD

**Issue by rickfromwork** [BabylonJS/Babylon.js#10490]
Finally making an issue on this. I've noticed for a while that when you load a playground scene in XR (whether in-browser or via a standalone app with BabylonNative), the objects are much larger than they looked in the playground. This was just an annoyance for a long time, but I just realized that because of this, some things that are scaled to look normal in 2D scenarios look incredibly out of place in XR.
I noticed this when I tried scaling a mesh with a boundingBox gizmo attached to it, and realized the gizmo meshes are a fixed size. I can understand why you'd want that in theory, but because of the scaling difference, each part of the bounding box in AR/VR is about the size of my head. Since I usually want to manipulate objects smaller than my head, this poses a problem.

I see two possible ways around this:
- Go through every class in Babylon, and update it to both be aware of whether it's in XR mode _and_ give it different scaling properties when it is in XR mode, or
- Cause a breaking change for existing apps by scaling content in XR to the same size as content in 2D playground apps

**Comment by RaananW** [comment]
> the objects are much larger than they looked in the playground.

When you say "the objects" do you mean all meshes? or UI elements?


> * Cause a breaking change for existing apps by scaling content in XR to the same size as content in 2D playground apps

I think we first need to understand what the issue is, actually. If it is just camera perspectives (which i doubt) it should stay this way. If it is incorrectly scalling a utility layer scene or an advanced dynamic texture (my assumption?)) we should fix that.

**Comment by rickfromwork** [comment]
All meshes appear to be ~10x larger. It could be that I'm making some invalid assumptions about visual scaling, though. 

If I use this playground scene, the contents look fairly small in the 2D window, but on loading the scene in the Windows Mixed Reality Portal, I am far away from the scene, and on going closer I see that even just the buttons are _very_ big.
https://www.babylonjs-playground.com/#KEPE5P#7

For reference, here is a snippet showing the default size of the HolographicButton in VR (taken from the linked playground scene), with a 1:1 model of a motion controller in front of it:
![image](https://user-images.githubusercontent.com/70608380/121673612-ebb5cd00-ca65-11eb-9aaf-f6ec7b102aea.png)


Writing it out in this way, I'm starting to wonder if the default measurements are in meters - so a 1x1x1 cube is actually a meter cubed. That might explain the sizing, but if that's the case I think meshes that cannot be resized, like the bounding box constraints, should be smaller in XR.

**Comment by rickfromwork** [comment]
Here's a video of me launching the playground scene into VR as well, which might better show the scale seen.
https://user-images.githubusercontent.com/70608380/121674187-94642c80-ca66-11eb-8e12-321e31d18923.mp4

**Comment by RaananW** [comment]
This is the expected behavior. The camera initializes 20 units (meters in XR case) away from the button, so they seem to be very small. If you see the position of the button, you will see that it is located at y = 2, which means it is positioned higher than the user (unless you are taller than 2m :-)).

**Comment by rickfromwork** [comment]
> This is the expected behavior. The camera initializes 20 units (meters in XR case) away from the button, so they seem to be very small. If you see the position of the button, you will see that it is located at y = 2, which means it is positioned higher than the user (unless you are taller than 2m :-)).

I see. The scaling of the bounding box gizmo's meshes should probably be updated to not be so large, then. I've been told that setting the fixedDragMeshScreenSize property can fix the sizing, maybe the logic it handles should be enabled somehow when in XR mode as well?

**Comment by RaananW** [comment]
> I see. The scaling of the bounding box gizmo's meshes should probably be updated to not be so large, then. I've been told that setting the fixedDragMeshScreenSize property can fix the sizing, maybe the logic it handles should be enabled somehow when in XR mode as well?

Sure, that madness sense to me. So the drag mesh is always fixed size relative to the screen size. XR has a different screen resolution so we just need to be sure that the scaling works correctly.

Are you thinking of turning it on per default for XR experiences?

**Comment by rickfromwork** [comment]
> Sure, that madness sense to me. So the drag mesh is always fixed size relative to the screen size. XR has a different screen resolution so we just need to be sure that the scaling works correctly.
> 
> Are you thinking of turning it on per default for XR experiences?

Yeah, either turning it on as a default or, based on what you said, adjusting the scale relative to screen size when in XR to accommodate the different sizing

**Comment by RaananW** [comment]
> Yeah, either turning it on as a default or, based on what you said, adjusting the scale relative to screen size when in XR to accommodate the different sizing

It should be an option of all UI elements - keep perspective based on distance from the camera (or screen size). This seems to be the reasoning behind `fixedDragMeshScreenSize`. I wouldn't want to set it true per default though. We can discuss this offline when you have the time

**Comment by rickfromwork** [comment]
I took an approach similar to option 1, where I provided an alternate scaling for all 3D controls that can be toggled by a single call to the GUI3DManager:
#11333

All that's left to do is to update the documentation to mention this.

**Comment by rickfromwork** [comment]
Docs updated with https://github.com/BabylonJS/Documentation/pull/409
