### ISSUE TITLE
Scene Files not loading when the URL has query strings and checking manifest is ignored

### ISSUE THREAD

**Issue by gabrielheming** [BabylonJS/Babylon.js#10503]
This is quite an unique scenario and requires a few settings to happen.

**Long story short** 

I am loading files to the scene that are private on Azure Blob Storage. To allow the access, we are granting access using [Shared Access Signature](https://docs.microsoft.com/en-us/azure/storage/common/storage-sas-overview). The URL will be create to something similar as:
```
https://site.blob.core.windows.net/file.obj?sv=2019-12-12&st=2021-06-14T14:46:19Z&se=2021-06-14T20:46:19Z&sr=b&sp=r&sig=123`
```

This creates an overhead using the `.manifest` file because of the security and, our files have immutable links (it's a relation between file + user ip address). So, to avoid the overhead, I have [enabled the option to ignore the `.manifest`](https://github.com/BabylonJS/Babylon.js/issues/5508).

However, when loading the file, the timestamp that is added to the URL is being improperly concatenated, see below

Expected:
```
https://site.blob.core.windows.net/file.obj?sv=2019-12-12&st=2021-06-14T14:46:19Z&se=2021-06-14T20:46:19Z&sr=b&sp=r&sig=123&1613477087021
```

Result (duplicating the **?**)
```
https://site.blob.core.windows.net/file.obj?sv=2019-12-12&st=2021-06-14T14:46:19Z&se=2021-06-14T20:46:19Z&sr=b&sp=r&sig=123?1613477087021
```

There's the below playground that represent the URL creation (even though, it doesn't affect the usage because the query string isn't a signature to permit or not the access).
https://playground.babylonjs.com/#6N3FD4#2

Solution:
https://playground.babylonjs.com/#6N3FD4#3

**Comment by deltakosh** [comment]
Good catch! thanks a lot for the PR

**Comment by thomlucc** [comment]
Merged
