### ISSUE TITLE
Playground loading animation doesn't disappear on scene load if tab is not active

### ISSUE THREAD

**Issue by darraghjburke** [BabylonJS/Babylon.js#10523]
**Repro**
- Bug repro on [playground](https://playground.babylonjs.com/#9F0CBV). While the scene is loading, switch tabs repeatedly.
- Expected result: When you return to the original tab after the scene has finished loading, the loading screen should be gone.
- Current result: The screen is still dim and the loading animation still appears over the scene, at least sometimes.

**Screenshots**
![Loading screen](https://user-images.githubusercontent.com/1342157/122606541-518df000-d036-11eb-9034-55c43b87863e.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Edge
 - Version: 91.0.864.41 

**Additional context**
This may be caused by onDisplayWaitRingObservable not being correctly fired if the tab is not active, but I have not confirmed if this is the case.

**Comment by RaananW** [comment]
I believe you it's there, but I can't seem to be able to reproduce this. What's the best moment to switch tabs in order to reproduce this?





> This may be caused by onDisplayWaitRingObservable not being correctly fired if the tab is not active, but I have not confirmed if this is the case.

I initially thought it is something similar, but it seems from your image that the animation has already started. so it already triggered the fade out animation. I need to investigate, but i'll have to reproduce this first.

**Comment by darraghjburke** [comment]
Yeah, I am also having difficulty repro'ing it now. I know that at least one another person was able to repro the issue, but it seems to only happen in very specific circumstances. I will let you know if I can figure out a consistent way to trigger the bug

**Comment by sebavan** [comment]
Let me close it for house keeping and reopen once we figure the full repro
