### ISSUE TITLE
NearMenu gets too close to the user

### ISSUE THREAD

**Issue by rickfromwork** [BabylonJS/Babylon.js#10526]
Since the nearMenu's distances are based on the scaling of its backplate, which is shrunk down on creation, the menu appears much closer than is likely intended, and closer than is physically comfortable. 

On its own, the follow behaviour stays between 2 meters and 30 centimeters (~1 foot) away from the user. This is appropriate, as if it gets any closer, it becomes hard to physically focus on the object without going cross-eyed.

The nearMenu however sets its default distance to 0.072 with one button added, up to 0.136, with the minimum distance being 50% of that and the maximum distance being 150% of that, or ~20 cm away.

This is far too close for comfort in VR/AR, and in a browser scene, the menu comes close enough to clip out of the camera's view.

Test scene here:
https://www.babylonjs-playground.com/#HXXKWA#3

**Comment by CraigFeldspar** [comment]
Hi @rickfromwork , last PR #10485 should have fixed that (here https://github.com/CraigFeldspar/Babylon.js/blob/d18217577e73b58558cf3bf28b094c999a3bef4d/gui/src/3D/controls/nearMenu.ts#L93).
I am now using a fixed world offset between 30 and 60 centimeters.
Do you still get the issue ?

**Comment by rickfromwork** [comment]
Looks like I wasn't using your changes yet. With them it definitely behaves better, though the menu still clips past the camera's near render cutoff when viewing the scene in a browser for me. 

Since the issue was opened primarily around AR/VR usage, I'll mark it as resolved (though tbd if we want it at a viewable distance when previewing scenes in a browser).
