### ISSUE TITLE
glTF Transmission does not properly handle changes to scene lighting intensity

### ISSUE THREAD

**Issue by MiiBond** [BabylonJS/Babylon.js#10536]
When a glTF with the transmission material extension is loaded, the opaque scene is rendered to a texture **with lighting included**. However, when this texture is used in transmissive materials, the scene intensity is multiplied into the result (essentially doubling the intensity effect).
Here's a Playground that demonstrates how dark transmission gets when the scene intensity is turned down.
https://playground.babylonjs.com/#WGZLGJ#3157

The scene intensity should only be multiplied into the transmission result when the source texture doesn't already include this intensity multiplier.

**Comment by sebavan** [comment]
ohhhhhhh I see what you mean... and I concur let s see if our friend @Popov72 might think about a nice fix ?

**Comment by Popov72** [comment]
#10537 should fix it.
