### ISSUE TITLE
Using WebXR with a second canvas does not work 

### ISSUE THREAD

**Issue by darkverse** [BabylonJS/Babylon.js#10560]
Specifying a canvas to use for the WebXR session, via outputCanvasOptions.canvasElement, results in a failure to render to the XR headset. 

This issue was identified as the underlying issue in two threads on the forum:
https://forum.babylonjs.com/t/webxr-render-canvas-and-streaming/20893 and
https://forum.babylonjs.com/t/strange-performance-with-webxr-ammojs-and-scene-animate/21675

Both of these threads started out investigating slightly different aspects and other factors were first thought to be an issue (such as Ammo) but the underlying issue, common to both, is that the WebXR session is somehow still dependant on the canvas that the engine was created with, regardless of the setting in outputCanvasOptions.

- Expected result: WebXR should only use the canvas specified in th eoptions and leave the engine's canvas untouched.
- Current result: Specifying an alternate canvas via the options breaks the rendering to the headset, ie it is still rendered to the engine's canvas

**Headset**
 - OS: tested on a Lenovo Mirage running android (daydream)
 - Browser: Chrome
 - Version: 84

**Additional context**
The frame buffers ARE correctly setup and it does seem to pass the canvas thru but somewhere in the render process it reverts to the renderTarget that the engine was created with/ In this sense, WebXR is ONLY working if the canvas used to setup the render buffers is the canvas that was used to create the engine.

I have setup a standalone project, outside of the playground, that can be used to reproduce this. This test has extra stuff in it as I  was isolating the issue but I have left them in in case it helps further testing. The test in its current state creates a physics playground and then attempts to start an XR session based on the value of canvasToUse, which can be changed on lines 58,59 to use either the canvas the engine was created with or an alternate canvas. Using the alternate canvas does not work, using the engine's canvas does. Other factors, such as streaming or physics engine mentioned in the threads was a red herring. Simply using a different canvas breaks WebXR. 
(Note: In my main project, as I am streaming the engine's canvas, I can see that the WebXR render IS going to the engine's canvas rather than using the frame buffers to render to the headset like it should be)

[test.zip](https://github.com/BabylonJS/Babylon.js/files/6705386/test.zip)

**Comment by RaananW** [comment]
Updating here - I have a working prototype for XR+canvas rendering using the activeCameras array (i.e. an arc rotate and XR camera together):

![image](https://user-images.githubusercontent.com/1381702/127377558-9294f990-9677-4bbf-b6ac-c5c2b0b5d4a2.png)

It requires a few changes (one of them is #10762). I'll close it when merging the needed changes and will probably introduce "spectator mode" in the experience helper.

**Comment by RaananW** [comment]
I want to add - it is currently not possible to change the rendering context (i.e. the gl object) in our engine, so a custom canvas will not work as expected. The current solution is to use the same canvas to render XR and the desktop spectator camera.
