### ISSUE TITLE
A mesh with a non-default rotation and non-uniform scaling will distort any children that get added

### ISSUE THREAD

**Issue by rickfromwork** [BabylonJS/Babylon.js#10579]
https://www.babylonjs-playground.com/#BEMR0P#2

The playground above shows the simplest repro, of a mesh being parented to a transformNode that has been scaled and rotated.
If there is no rotation, or the scaling is uniform, there is no distortion.

Expected: No distortion even with non-uniform scaling
Actual: Distortion present along multiple axis

**Comment by Popov72** [comment]
It seems there's no simple solution to this problem.

From what I understand, we would need to either support shears in addition to translation/rotation/scaling or only use matrices and never decompose them into translation/rotation/scaling.

See for eg:
* https://github.com/mrdoob/three.js/issues/3845
* https://github.com/mrdoob/three.js/issues/15079
* https://github.com/armory3d/armory/issues/2211

**Comment by sebavan** [comment]
I agree with this, @deltakosh any thoughts ?

**Comment by deltakosh** [comment]
I'm fine. We simply need to document it

**Comment by sebavan** [comment]
I ll update the doc thanks a lot. In the meantime @rickfromwork, maybe relying on mesh.parent = instead of setParent might do the trick in your case ?
