### ISSUE TITLE
[XR] Introduce support for WebXR Layer API

### ISSUE THREAD

**Issue by RaananW** [BabylonJS/Babylon.js#10588]
Following the specs - https://www.w3.org/TR/webxrlayers-1/
Explainer - https://github.com/immersive-web/layers/blob/main/explainer.md

WebXR layers should be introduced as an XR feature.

Still TBD:

* What would be the fallback to systems not supporting this? A [polyfill](https://github.com/immersive-web/webxr-layers-polyfill) but that depends on the dev integrating it. 
* Should we introduce a new WebXRVideoTexture (to support video layers) or can we adjust the video texture accordingly? 
* Will (or should) it be a single feature or a few features using the same underlying API?
* Are there any changes required to the rendering pipeline? Any changes required to the engine itself?

**Comment by gabrieljbaker** [comment]
Great to see an issue for this @RaananW !

**Comment by RaananW** [comment]
The work is currently in progress, hope to have a testable version soon

**Comment by thomlucc** [comment]
Thanks @rgerd !
