### ISSUE TITLE
Add support for fullscreen UI in XR

### ISSUE THREAD

**Issue by RaananW** [BabylonJS/Babylon.js#10592]

**Comment by RaananW** [comment]
This will be supported once the webxr layer's projection layer will be implemented (related issue - #10588). Our current fullscreen shader implementation (using the layer shader) doesn't support webxr.

**Comment by ThomasMeetKai** [comment]
Looks like the projection layer was implemented last year, is this possible now?

**Comment by RaananW** [comment]
This will require a different layer to work as we expect it to work. Still on the TODO list, sorry for the delay.
