### ISSUE TITLE
Enhance ObjFileLoader so it can load simple point clouds

### ISSUE THREAD

**Issue by lovettchris** [BabylonJS/Babylon.js#10605]
**Is your feature request related to a problem? Please describe.**
I want to visualize point clouds, the tool that generates them generates a simple .obj file format that has no materials like this [https://raw.githubusercontent.com/lovettchris/GlbFileTest/master/sparse_shed.obj](https://raw.githubusercontent.com/lovettchris/GlbFileTest/master/sparse_shed.obj).

When I tried loading this file using ObjFileLoader I got a mesh back but the mesh returned no data from getVerticesData(VertexBuffer.PositionKind).

**Describe the solution you'd like**
Allow the ObjFileLoader to return a mesh in this case.  Even better if you turn it into a mesh using PointsCloudSystem like this [PointCloudSystem demo](https://www.babylonjs-playground.com/#0631GB#4) to it renders the vertex colors like this:

![image](https://user-images.githubusercontent.com/18707114/124051744-f06d0180-d9d1-11eb-9952-8083cda9ed7a.png)

**Discussion**

[6:30 PM] David Catuhe
    This should work honestly
Wanna create an issue for me on the repo so I can add support for it? (Please also share your obj file?

**Comment by deltakosh** [comment]
Alright! It is now fixed. We are supporting OBJ with ONLY vertice list (no indices, no material, like nothing ;))

After the current commit will be merge this code:
```
    // This creates a basic Babylon Scene object (non-mesh)
    var scene = new BABYLON.Scene(engine);

    var camera = new BABYLON.ArcRotateCamera("Camera", 0, 0.8, 100, new BABYLON.Vector3.Zero(), scene);

    BABYLON.OBJFileLoader.IMPORT_VERTEX_COLORS = true;

    var baseUrl = "https://raw.githubusercontent.com/lovettchris/GlbFileTest/master/"
    BABYLON.SceneLoader.ImportMesh("", baseUrl, "sparse_shed.obj", this.scene, () => {
        scene.createDefaultCameraOrLight(true, true, true);
    });

    return scene;
```

Will render like this:
![image](https://user-images.githubusercontent.com/1306056/124062006-cffa7280-d9e4-11eb-9c15-b54a80898e39.png)

**Comment by deltakosh** [comment]
The system will automatically a point cloud based material if there is no indices (or it will update the associated material if the mesh has a material)

**Comment by lovettchris** [comment]
Wow David, you rock!
