### ISSUE TITLE
Does_babylon.gui.image, url or path input works?

### ISSUE THREAD

**Issue by xwaeaewcrhomesysplug** [BabylonJS/Babylon.js#10626]
I checked https://forum.babylonjs.com/search?q=image%20button
Found,https://forum.babylonjs.com/t/button-image-examples-not-working/16281
states that it worked in the past..however it does not seems to work now.

i used a few references

//https://playground.babylonjs.com/#XCPP9Y#3
//https://doc.babylonjs.com/divingDeeper/gui/gui
however none of it seems to work.
What I need is just a image that acts like a button.
Which you probably will ask did the example in docs worked.sadly no.
in fact,i do not think the example even work.I copied the code and change the string to point to my image.
it sadly does not seems to work.

you may use https://playground.babylonjs.com/#XCPP9Y#3 and replace the var button contructor with the image link to test.
you may also try comment out the button.background and button.color
eg,"textures/grass.png" to "https://avatars.discourse-cdn.com/v4/letter/j/e68b1a/240.png"

Expected result,a picture that acts like a button.
current result,a transparent button that works

**Comment by xwaeaewcrhomesysplug** [comment]
![debugweg2](https://user-images.githubusercontent.com/67897598/124384805-f898aa00-dd0d-11eb-8b53-7a435fa110a1.PNG)
![debugweg](https://user-images.githubusercontent.com/67897598/124384810-fa626d80-dd0d-11eb-932f-501008abec81.PNG)
 
eg

**Comment by sebavan** [comment]
As the template is mentionning it would be great to start the discussion in the babylon forum as we tend to keep github for validated issues.

In your case it seems to be a cors issue for your picture 
![image](https://user-images.githubusercontent.com/16655165/124499465-55ec3400-ddbe-11eb-891b-7da5c8b62a19.png)
