### ISSUE TITLE
GlowLayer not working if BoundingBoxRenderer not loaded

### ISSUE THREAD

**Issue by s0xDk** [BabylonJS/Babylon.js#10643]
`EffectLayer` calls `scene.getBoundingBoxRenderer()` that is defined by `boundingBoxRenderer.js` -- when it's not loaded, you get an error:

`Uncaught TypeError: this._scene.getBoundingBoxRenderer is not a function`

That file not loading if you use specific imports like this:

```import { Engine } from "@babylonjs/core/Engines/engine";
import { Scene } from "@babylonjs/core/scene";
import { ArcRotateCamera } from "@babylonjs/core/Cameras/arcRotateCamera";
import { Mesh } from "@babylonjs/core/Meshes/mesh";
import { GlowLayer } from "@babylonjs/core/Layers/glowLayer";
```

But if you add this line everything becomes fine again:

`import { BoundingBoxRenderer } from '@babylonjs/core/Rendering/boundingBoxRenderer';`

**Comment by sebavan** [comment]
Can you check what version you are using ? 

This should have been fixed 7 months ago so it should be all good in latest preview.

Closing for now, will reopen if not working in latest.

**Comment by s0xDk** [comment]
I'm using 4.2.0. Didn't tried 5.0.0, sorry :)

**Comment by sebavan** [comment]
perfect I let you try it and let me know :-)
