### ISSUE TITLE
NME: Add camera parameters input block

### ISSUE THREAD

**Issue by PatrickRyanMS** [BabylonJS/Babylon.js#10796]
A new input block that holds a vec4 for needed camera parameters. The outputs on the block should be four floats as follows:

- x: projection matrix flag (1.0 if regular and -1.0 if the projection matrix is flipped, to denote WebGL vs WebGPU)
- y: camera.minZ
- z: camera.maxZ
- w: 1 / camera.maxZ

**Comment by deltakosh** [comment]
Pinging @PirateJC to kindly ask him to update the nme documentation page ;)

**Comment by deltakosh** [comment]
nevermind I did it actually ;D
