### ISSUE TITLE
Rendering performance issues on macOS Safari

### ISSUE THREAD

**Issue by hdeppert** [BabylonJS/Babylon.js#10813]
I checked the Babylon 4.2 performance on a MacbookPro 2019 with Safari 14.1.2 (latest), macOS 11.5 , Radeon Pro 555X graphics and a 6-core i7 cpu. Safari shows a GPU utilization of 100% in the activity console, Babylon reports 55-60 FPS, but actual FPS are around 3-7 FPS.

It shows a significant performance drop compared to Windows/PC or Android or iOS devices. Even Chrome on macOS shows good performance (GPU utilization 40-46%).

I am directly writing here instead of the forums, because I checked the issue several times and can reproduce it regularly.

A related issue might be: https://github.com/BabylonJS/Babylon.js/issues/3542 , maybe a regression since 3.*?

In particular:
- Babylon shows a FPS of 55-60 all the time.
- SceneOptimizer is used
- When using native rendering resolution (retina display), the actual performance is like 3-7 FPS .
- When using a second display with lower resolution, the performance is okay (can be 50-60 FPS)
- When using a lower resolution on the retina display (playing with hardware scaling) the performance is okay (40+) , but very depending on the complexity of the model, often stuttering while rotating the camera
- Chrome on macOS runs with good speed, same on Windows, Android, iOS devices

Update:
- Babylon initiated in WebGL1 mode on Safari 14, while Babylon initiated Chrome in WebGL2 mode
- Babylon on iOS Safari (and some Android browsers) also use WebGL1, but with good performance compared to desktop Safari
- If the window size is decreased (smaller) the performance goes up, if increased the performance goes down. But I can only see this on Safari/macOS/WebGL1 -> Chrome/macOS/WebGL2 has good performance all the time

Expected behavior:
- Similar performance for WebGL1 and WebGL2 on same browser (Safari/macOS)

**Comment by sebavan** [comment]
Would be great to move the discussion to the forum first https://forum.babylonjs.com/ as explained in the issue template: 

![image](https://user-images.githubusercontent.com/16655165/128369696-eb1aefed-80c0-4f64-bb06-daa9e0be9500.png)

Let s discuss and repro the issue there before reopening with more context.
