### ISSUE TITLE
Rotation on ArcRotateCamera continues when button is released if another button is still active

### ISSUE THREAD

**Issue by PolygonalSun** [BabylonJS/Babylon.js#10856]
Forum post discussing this: https://forum.babylonjs.com/t/camera-rotation-is-stuck-because-of-pointerinput-fakemove/22171/5

We have a really active forum to help answering questions (https://forum.babylonjs.com/)

With cameras like the ArcRotateCamera, when a mouse button is pressed during a rotate-drag event, if the original button is release with this new button pressed, the rotation will still occur.

Fix for this will require implementing the following behavior:
The initial button press will initiate the behavior (rotate, pan, etc.) and any other buttons will be ignored.

**Comment by sebavan** [comment]
@PolygonalSun, Any ETA on this one ?

**Comment by PolygonalSun** [comment]
> @PolygonalSun, Any ETA on this one ?

Not yet.  I figured out that the reason it isn't working was because Safari is using different values for the PointerEvent's button (eg. 0 for both left click and no button clicked).  I'm working on a different approach that will work for Safari and Every other browser.
