### ISSUE TITLE
Particle system wrong serialization

### ISSUE THREAD

**Issue by hzx829** [BabylonJS/Babylon.js#10882]
**Repro**
- Expected result: [original particle system](https://playground.babylonjs.com/#GXTHL9#9)
- Current result: [after serialization](https://playground.babylonjs.com/#GXTHL9#10)
- Current result: [clone particle system](https://playground.babylonjs.com/debug.html#GXTHL9#12)
- Press *space bar* to start

**Desktop (please complete the following information):**
 - OS: Window10
 - Browser chrome
 - Version 92.0.4515.107

**Comment by Popov72** [comment]
Fixed by #10883
