### ISSUE TITLE
Support npm v7 in our build process

### ISSUE THREAD

**Issue by RaananW** [BabylonJS/Babylon.js#10888]
NPM v7.x introduced back-compat issue that prevents us from building the framework correctly (i.e. running `npm run build` in Tools\Gulp)

This is related to an error conserning the working directory in which npm link is executed.

The error displayed is: `npm ERR! Tracker "idealTree:inflate:" already exists`

**Comment by RaananW** [comment]
This will be solved with the planned new build system.

**Comment by leon** [comment]
@RaananW out of curiosity, what build system are you going to use?

**Comment by RaananW** [comment]
> @RaananW out of curiosity, what build system are you going to use?

I have been experimenting with lerna, rush, npm and yarn workspaces along with typescript project references.

I will continue the work after feature freeze (around january probably), but at the moment I am mainly using lerna as an orchestrator and building most public facing libraries using rollup. 

Still a work in progress though! Lerna has some downsides (mainly the current version which has a few small kinks that are not being solved), so I am not sure I will continue down this path. both workspaces implementations can partly help with structure, but proper orchestration is still not there. When I free the time and continue working on that I will push my branch and publish the updated structure to get feedback

**Comment by leon** [comment]
I have been using https://nx.dev/ as our monorepo at work for the last 2 years.
It works great with typescript, and has support for a lot of the stuff I think we would need in the babylonjs repo.

It handles building, caching, testing, even has support for cypres e2e testing.

It is also good at packaging different sections of your code into reusable libs that can be published as separate things to npm.

could be worth checking out.

I can help if you need guidance :)
