### ISSUE TITLE
glTF: Normals cannot be loaded from the same accessor as positions

### ISSUE THREAD

**Issue by lexaknyazev** [BabylonJS/Babylon.js#10948]
The two meshes in the attached file use the same data both for normals and positions. The first mesh loads normals through the separate accessor while the second mesh reuses the accessor used for `POSITION`. Only the first mesh is rendered correctly.

/cc @bghgary 

[position-normal.glb.zip](https://github.com/BabylonJS/Babylon.js/files/7073339/position-normal.glb.zip)

**Comment by Popov72** [comment]
Thanks for the report, this PR should fix the problem: #10949
