### ISSUE TITLE
If we set at least a value of 1 for the rounded corner of a rectangle, we can't see the selection frame anymore

### ISSUE THREAD

**Issue by msDestiny14** [BabylonJS/Babylon.js#10953]
Bound box should likely be drawn on top of all the GUI, or use the original sizing.

Related issue from the GUI editor repo:
https://github.com/BabylonJS/ThePirateCove/issues/53

**Comment by sebavan** [comment]
@msDestiny14 should it be closed by @Popov72 PR yesteday ?

**Comment by deltakosh** [comment]
That was fixed yes I suppose

**Comment by msDestiny14** [comment]
Yep! https://github.com/BabylonJS/Babylon.js/pull/10968
