### ISSUE TITLE
WebXR motion controller pointer selection stops when manipulating objects

### ISSUE THREAD

**Issue by rickfromwork** [BabylonJS/Babylon.js#10978]
Looks like the near interaction feature thinks there's a near interaction occurring, despite the controller being nowhere near the target mesh.

**Comment by RaananW** [comment]
Is that related? https://github.com/BabylonJS/Babylon.js/pull/10981

**Comment by rickfromwork** [comment]
> Is that related? #10981

Yep, forgot to link that, thanks
