### ISSUE TITLE
My environment is angular8，the SceneLoader.ImportMeshAsync have not any response.

### ISSUE THREAD

**Issue by jinxiu3939** [BabylonJS/Babylon.js#10971]
My enviroement is angular8， and the babylonjs is ok ,and it can create sphere and run ok.
But when I use the SceneLoader.ImportMeshAsync to import  mesh of localhost, it is not work. I debug the progress is finished， however, the promise have not any response.
so, I test the code in javascript environment, and it is work. 
Is it the problem of angular? Or, the npm package has bug? Who can help me?

And the code is on below:

`  ngOnInit() {
    var canvas: any = document.getElementById("renderCanvas");
    var engine: Engine = new Engine(canvas, true);

    var scene: Scene = createScene(engine, canvas); 
    var camera: ArcRotateCamera = createCamera(scene, canvas); 
    var building = createBuilding(scene); // the buiding is sphere
    
    SceneLoader.ImportMeshAsync(null, "./assets/mesh/", "2f.gltf", scene, (progress) => {console.log(progress)}).then((result) => {
      console.log('hello');
    }, (error) => {
      console.log('world');
      console.log(error);
    });

    engine.runRenderLoop(() => {
        scene.render();
    });
  }`

**Screenshots**
![debug](https://user-images.githubusercontent.com/29724523/131635484-03fee461-0bb0-4bb0-a575-22a1f0e404ff.png)

**Comment by sebavan** [comment]
Please use the forum (https://forum.babylonjs.com/) for starting discussions and investigations as specified in the github issue template.

If you provide a repro in the playground there, we ll be able to address it in no time and create back a corresponding github issue if the bug is on our side.

Closing for now, until we investigate further.

**Comment by jinxiu3939** [comment]
O, I find the problem. On the line 143259 of node_modules/babylonjs/babylon.max.js. The if condition is false. I modify as below:

`
// if (request.readyState === (XMLHttpRequest.DONE || 4)) {
if (request.readyState === XMLHttpRequest.DONE || request.readyState === 4) { // [debug]
`
