### ISSUE TITLE
[NME] Adding a Voronoi block for 2D noise

### ISSUE THREAD

**Issue by PatrickRyanMS** [BabylonJS/Babylon.js#11006]
We have a Worley block for 3D noise, but it would be great to have a 2D Voronoi block for things like texture manipulation without the calculations for the extra dimension in the noise. 

**Inputs**
- UVs (vector2)
- Point Offset (float)
- Cell Density (float)

**Output**
- Noise (float)
- Cells data (float)

**Comment by deltakosh** [comment]
Closing for now as the WorleyNoise can output 2d and 1d values now
