### ISSUE TITLE
OffscreenCanvas Textures Inverted

### ISSUE THREAD

**Issue by nmrugg** [BabylonJS/Babylon.js#11059]
When running Babylon.js in a web worker using an OffscreenCanvas, it does not correctly invert images when loading textures.

**Repro**
- Bug repro on [playground NMPB99](https://playground.babylonjs.com/#NMPB99#5):
- Expected result: The meshes should look the same.
- Current result: The image textures are inverted.

**Screenshots**
![offscreen-canvas-bug](https://user-images.githubusercontent.com/387105/133109358-02596b5d-2648-47e8-91b1-fd17ecc3a7bd.png)

**Desktop**
 - OS: Linux
 - Browser: Chromium
 - Version: 91

**Additional context**
I was able to work around this issue by supplying `invertY` to [LoadImage()](https://github.com/BabylonJS/Babylon.js/blob/c843dcbc3875e9eee184152a10b857f7af9f4993/src/Misc/fileTools.ts#L142) and adding `imageOrientation: invertY ? "flipY" : "none"` to [createImageBitmap()](https://github.com/BabylonJS/Babylon.js/blob/c843dcbc3875e9eee184152a10b857f7af9f4993/src/Misc/fileTools.ts#L167). But, I'm not certain that is the best way to handle this issue.

**Comment by deltakosh** [comment]
cc @Popov72 to have a look
**Did you start a thread on the forum as mentioned on the template?**

**Comment by nmrugg** [comment]
> **Did you start a thread on the forum as mentioned on the template?**

No, I didn't sorry. I miss read that. I can open a thread there.

**Comment by sebavan** [comment]
https://forum.babylonjs.com/t/offscreencanvas-textures-are-inverted/23798

Closing for now and might reopen in a bit :-)
