### ISSUE TITLE
GLTFFileLoader.loadFile does not call onError callback for .GLB files with less than 20 characters

### ISSUE THREAD

**Issue by baswelsh** [BabylonJS/Babylon.js#11052]
**Summary**
For corrupt GLB files with less than 20 bytes, `GLTFFileLoader.loadFile` throws an unhandled exception instead of calling the `onError` callback (see screenshots below).

Validated bug: https://forum.babylonjs.com/t/gltffileloader-loadfile-does-not-call-onerror-callback-for-files-with-less-than-20-characters/22669

**Repro**
- Bug repro on [sandbox](https://sandbox.babylonjs.com/).  Please note that this same issue exists in other, customer implementations with `@babylonjs/loaders` but the generic babylon sandbox is an easy repro.
- Expected result:
Upload a .GLB file with >= 20 characters.  Example contents:
```json
{
	"hello": "123abc"
}
```
In this scenario, the generic error message is displayed and the sandbox state is reset.
- Current result:
Upload a .GLB file with < 20 characters.  Example contents:
```json
{
	"hello": "123"
}
```
In this scenario, no error message is displayed and the sandbox stalls in the loading state.

**Screenshots**
When uploading a .GLB file with >= 20 characters.
<img width="1046" alt="image" src="https://user-images.githubusercontent.com/74797106/132963023-8d59edb8-bd9a-4752-8d76-19f2e112bd71.png">

When uploading a .GLB with < 20 characters and waiting a sufficient amount of time.
<img width="1110" alt="image" src="https://user-images.githubusercontent.com/74797106/132962983-e257d75f-3034-44c0-83b9-6bbb33be6ca6.png">

Browser console
<img width="1435" alt="image" src="https://user-images.githubusercontent.com/74797106/132962989-013f2e2a-3ede-4114-ae4e-5cdf82a2efba.png">

**Desktop:**
 - OS: Windows, Mac
 - Browser: Chrome, Safari, Firefox
 - Version: Latest

**Additional context**
I was able to track the issue down to the construction of the Unt8Array in the following codeblock (starting on line 538). Fundamentally the issue is an out-of-bounds error resulting from the combination of byteOffset and byteLength being greater than the file length (in this case, 19).

`loaders/src/glTF/glTFFileLoader.ts`
```javascript
  return this._loadFile(scene, fileOrUrl, (data) => {
      const arrayBuffer = data as ArrayBuffer;
      this._unpackBinaryAsync(new DataReader({
          readAsync: (byteOffset, byteLength) => Promise.resolve(new Uint8Array(arrayBuffer, byteOffset, byteLength)),
          byteLength: arrayBuffer.byteLength
      })).then((loaderData) => {
          onSuccess(loaderData);
      }, onError);
  }, true, onError);
```

While most of the time this won’t be an issue, given the architecture of the loaders, it is nearly impossible to catch the error from the surface of the library so when a <= 19 character file is submitted, a crash is currently unpreventable.

**Comment by deltakosh** [comment]
We want that people discuss issues and bugs first on the forum (as stated in the template)
That being said you did a pretty thorough investigations so I'll keep the issue open and validated :)

**Comment by baswelsh** [comment]
Thanks @deltakosh. Please see the link at the top of my post. That'll take you to the forum post where @bghgary validated the bug.

**Comment by deltakosh** [comment]
I'm dumb :D

**Comment by bghgary** [comment]
@baswelsh Do you have a repro file (i.e. glb file that is less than 20 bytes) that you can attach here?
