### ISSUE TITLE
Get clicked point on the model - React Babylon JS

### ISSUE THREAD

**Issue by SurajMK94** [BabylonJS/Babylon.js#11111]
Hi team,

How can i get the vector3 coordinate of the mouse clicked point on the 3D model in React Babylon JS code?

Thanks and Regards,
Suraj M K

**Comment by sebavan** [comment]
Please use our forum for questions: https://forum.babylonjs.com/

Github is only (as the template mentions) for validated bug and feature requests.

It really depends what you are trying to do with it:
https://doc.babylonjs.com/divingDeeper/mesh/interactions/picking_collisions
https://doc.babylonjs.com/divingDeeper/mesh/decals

Both of the examples are highlighting picking.
