### ISSUE TITLE
Input Text field for the UI - React Babylon JS

### ISSUE THREAD

**Issue by SurajMK94** [BabylonJS/Babylon.js#11110]
Hi team,

Is there a way to click a UI element and type the text using keyboard and save it?

Thanks and Regards,
Suraj M K

**Comment by sebavan** [comment]
Please use our forum for questions: https://forum.babylonjs.com/

Github is only (as the template mentions) for validated bug and feature requests.

Also it is hard to tell what you are trying to achieve from the question :-( the Babylon JS gui text input has a property text containing the text at any time so you can surely access it from react as well as the observable to detect text changes.
