### ISSUE TITLE
Map panning is not working(panningAxis == 1,0,1)  properly on ArcRotateCamera

### ISSUE THREAD

**Issue by youmumzgit** [BabylonJS/Babylon.js#11157]
ArcRotateCamera map panning(panningAxis == 1,0,1) is not working properly on v5.0
PG:https://playground.babylonjs.com/#SRZRWV#623
I've checked the code it seems these lines of code are missing on BABYLONJS v5.0
`//Eliminate y if map panning is enabled (panningAxis == 1,0,1)
if (!this.panningAxis.y) {
    this._transformedDirection.y = 0;
}`

**Comment by sebavan** [comment]
As the template is mentioning, please start any discussion on the https://forum.babylonjs.com/ Github is only used for validated issues and feature requests.

Once opened there, @PolygonalSun will be able to have a look to validate if it is an issue.
