### ISSUE TITLE
[NME] New node for Fractal Brownian Motion Clouds

### ISSUE THREAD

**Issue by PatrickRyanMS** [BabylonJS/Babylon.js#11161]
Another noise node that would be great for NME, especially the procedural texture mode, would be Fractal Brownian Motion for a cloud noise. Something along this line would be ideal: [https://thebookofshaders.com/13/](https://thebookofshaders.com/13/). The other parts of this article that are interesting are turbulence, ridge, and warp which may be awesome extensions as additional nodes or as flags on a single node depending on cost and feasibility. [Here is a quick and dirty version with our current nodes](https://nme.babylonjs.com/#KZNY32), but I feel like there's a more optimized way to do it straight in code as a new node. 

![image](https://user-images.githubusercontent.com/31326855/134723008-283e2c64-0b50-4a40-a7b6-7733424d30a4.png)

**Comment by deltakosh** [comment]
Also @PirateJC: One additional node to document ;)

**Comment by deltakosh** [comment]
No problem! I changed it to a 2 inputs system
