### ISSUE TITLE
Morph target animation freezes when played for the first time

### ISSUE THREAD

**Issue by starrabb1t** [BabylonJS/Babylon.js#11199]
**Repro**
Need any GLTF file exported from Blender with morph target animation
- Expected result:
animation plays smoothly 
- Current result:
animation freezes when played for the first time, then plays smoothly

**Desktop (please complete the following information):**
 - OS: does not depend
 - Browser [e.g. chrome, safari] does not depend
 - Version [e.g. 22] does not depend

**Smartphone (please complete the following information):**
 - Device: any device, does not depend

**Additional context**
Is there any workarounds? Can I play the animation secretly from the user firstly? Buffering somehow?

**Comment by deltakosh** [comment]
Hello as mentioned in the template (that we crafted with love) please start a forum thread first on forum.babylonjs.com

**Comment by starrabb1t** [comment]
Soultion
https://forum.babylonjs.com/t/morph-target-animation-freezes-when-played-for-the-first-time/24248
