### ISSUE TITLE
Assigning a ShadowDepthWrapper to a Material throws in 5.0

### ISSUE THREAD

**Issue by darraghjburke** [BabylonJS/Babylon.js#11205]
**Repro**
https://playground.babylonjs.com/#NES8QN
- Expected result:
![image](https://user-images.githubusercontent.com/1342157/135676729-d62265b9-253e-4a16-9c19-ddb15e192599.png)

- Current result:
![image](https://user-images.githubusercontent.com/1342157/135676754-111f736e-9696-437c-9207-3c2a13346e2c.png)

**Desktop (please complete the following information):**
 - OS: Windows, MacOS
 - Browser: Edge

**Smartphone (please complete the following information):**
 - Device: iPhone 6
 - OS: ios15
 - Browser Safari
 - Version 15

**Additional context**
This line:
```javascript
plane.material.shadowDepthWrapper = new BABYLON.ShadowDepthWrapper(plane.material);
```
Throws an exception, preventing the scene from loading.

**Comment by Popov72** [comment]
Fixed by #11206
