### ISSUE TITLE
Structured textBlock GUI control

### ISSUE THREAD

**Issue by msDestiny14** [BabylonJS/Babylon.js#11309]
Create an API/Control to allow users to have multiple text styles within a textBlock. For example **bolding** a word mid sentence.

https://forum.babylonjs.com/t/multiple-colors-styles-in-one-textblock/24680/18

**Comment by msDestiny14** [comment]
https://github.com/BabylonJS/Babylon.js/pull/11383

**Comment by deltakosh** [comment]
This is not a markdown control unfortunately

**Comment by msDestiny14** [comment]
What would be good rewording for the title?

**Comment by deltakosh** [comment]
It is a structured text block but unfortunately the grammar used to describe the text is not MD based

**Comment by jstroh** [comment]
Please

**Comment by thomlucc** [comment]
https://forum.babylonjs.com/t/structured-textblock-gui-control/52149
