### ISSUE TITLE
[NME] New node for height to normal 

### ISSUE THREAD

**Issue by PatrickRyanMS** [BabylonJS/Babylon.js#11319]
With our expanded noise node offerings, we are in need of a node to generate tangent space normals from a height map for procedural textures. The node would have a float input for the height map and potentially an input for the strength of the normal like we have on the perturbNormal node. The output would be a Vector3. 

![image](https://user-images.githubusercontent.com/31326855/138181592-f4b14cd2-d305-4f58-91c9-1ab88bffa990.png)

**Comment by deltakosh** [comment]
@PatrickRyanMS: to be able to do it I cannot take a float as I need to sample surrounding pixels to get the slope. So the entry point would be a texture

Will that still be ok?

**Comment by PatrickRyanMS** [comment]
@deltakosh, yes... sorry... I didn't mean a float value, I meant a single channel texture and mistyped. I expected the input would be a texture to compute the slope, but I also expected that input to be a single channel and not an RGB image.

**Comment by deltakosh** [comment]
Well..I may had a good (or bad?) idea... PR to come
