### ISSUE TITLE
Significant memory overhead and retention when doing mergeMeshes

### ISSUE THREAD

**Issue by ryantrem** [BabylonJS/Babylon.js#11375]
When calling `mergeMeshes`, a lot of memory is consumed and retained. After talking with @sebavan and @bghgary it seems much of this is unnecessary and can be fixed. Either of them can probably add more detail as needed.

**Comment by deltakosh** [comment]
Do we have any news here or is it ok to close it?

**Comment by sebavan** [comment]
I keep it until we can find a trick for merge mesh

**Comment by deltakosh** [comment]
But do we have a repro?

**Comment by sebavan** [comment]
the default merge mesh from @ryantrem (can not be shared publicly) I ll address it next week

**Comment by sebavan** [comment]
closing this for now as the gain are not worth it, will reopen if starts to be an issue again.
