### ISSUE TITLE
Pass multiple textures to shader

### ISSUE THREAD

**Issue by therepo90** [BabylonJS/Babylon.js#11390]
Im trying to pass multiple textures to postprocess shader channels :

postProcess.onApply = (effect) => {
  effect.setTexture('iChannel0', iChannel0); 
    effect.setTexture('iChannel1', iChannel1);
}

and then in fragment shader:

uniform sampler2D textureSampler;
uniform sampler2D iChannel0;
uniform sampler2D iChannel1;

And its not working. But when i use 'textureSampler' channel it works. What is going on?

**Comment by deltakosh** [comment]
Hey as stated in the issue template please use forum for question (forum.babylonjs.com)
