### ISSUE TITLE
Skinned mesh needs a way to update its bounding box for frustumClipping to work as intended

### ISSUE THREAD

**Issue by PatrickRyanMS** [BabylonJS/Babylon.js#11424]
It is possible to animate a skinned mesh in such a way as to move far enough away from the rest pose for the camera's frustumClipping to remove the mesh from the scene. This is happening if the skeleton and mesh are in different hierarchies (common practice for game assets) and the root bone is animated away from the origin and the camera follows the mesh. The bind pose for the mesh will leave the bounding box at the origin and if the camera can no longer see the origin, the skinned mesh will be culled. 

For this we don't need to update a deformed mesh, but just a way to move the simple bounding box with the skeleton so that the camera does not cull it. A work around would be to place the mesh and skeleton in the same hierarchy and animate the parent of the root bone to ensure that the bounding box stays with the skeleton, but I think there is an argument to be made for a method to do this in engine especially when animations are shared between files and extra hierarchy could be problematic. 

Need to make a repro for this issue

**Comment by sebavan** [comment]
@PatrickRyanMS, let us know when you ll have a repro for this one so that we can address it ASAP
