### ISSUE TITLE
Reload an exported glTF model, its vertex winding and node transform are incorrect.

### ISSUE THREAD

**Issue by daoshengmu** [BabylonJS/Babylon.js#11431]
**Repro**
- Bug repro on [https://playground.babylonjs.com/#CZQA3A](https://playground.babylonjs.com/#CZQA3A):

vs
```

var delayCreateScene = function () {
    
    var scene = new BABYLON.Scene(engine);
    let fanDescendants;
    BABYLON.SceneLoader.ImportMesh(
        null,
        "/Playground/scenes/",
        "fileName.glb",
        scene,
        function (meshes) {          
            scene.createDefaultCameraOrLight(true, true, true);
            scene.createDefaultEnvironment();  
            console.log(meshes[0].position);
            fan = meshes[0];
            fan.position.x = 20;
            fanDescendants = fan.getDescendants(false);  
            console.log(fanDescendants);
    });
    
    return scene;
};
```
- Expected result:

The glTF model which is exported from glTFExported should match to the original glTF model.

- Current result:

The glTF model after exporting will have wrong vertex winding and the attached node transform is wrong.

**Screenshots**
The screenshot after loading from glTFLoader
<img width="571" alt="Screen Shot 2021-11-10 at 11 52 30 PM" src="https://user-images.githubusercontent.com/1263177/141260168-c50f3c20-3aff-42bd-ab88-b8b80966a5e3.png">

The screenshot after loading from an exported glTF model
<img width="530" alt="Screen Shot 2021-11-10 at 11 53 51 PM" src="https://user-images.githubusercontent.com/1263177/141260192-03d3efd4-cd7e-46f8-9de4-964e2aa5dd7d.png">

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Mac OS
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] Version 95.0.4638.69

**Additional context**
Per my investigation, I notice BabylonJS uses left-handed coordinate system and glTF model is right-handed system, so we transform its root node at [glTFLoader.ts](https://github.com/BabylonJS/Babylon.js/blob/8403b1ea3f4ea9265de5d0f7ccbcc75023db300c/loaders/src/glTF/2.0/glTFLoader.ts#L470). However, in glTFExporter, we didn't invert the transform correctly. We are supposed to transform back from left to right handed system when exporting. After adding `glTFNode.scale = [1, 1, 1];` at [glTFExporter.ts](https://github.com/BabylonJS/Babylon.js/blob/8403b1ea3f4ea9265de5d0f7ccbcc75023db300c/serializers/src/glTF/2.0/glTFExporter.ts#L1740), the vertex winding issue is resolved at least. I need to dig into more about how to correct the root transform when applying attached nodes.

**Comment by deltakosh** [comment]
Adding @bghgary 

(Please also note that we state really clearly in the template that we expect you to have a discussion on the forum first)

**Comment by bghgary** [comment]
Yup, looks like a bug. You can workaround it by setting the scene to right handed for now.

https://playground.babylonjs.com/#CZQA3A#1
