### ISSUE TITLE
New parameter to change particle pivot

### ISSUE THREAD

**Issue by PatrickRyanMS** [BabylonJS/Babylon.js#11451]
Our particle system assumes a center pivot on particles for scaling and size. It would benefit the user to be able to change the position of the pivot so that particles scale from a position other than the center. For example, you may want an effect on the ground that scales in Y and being able to place the pivot on all particles at the bottom means you can scale your particles up from the ground.

This would need a conditional in shader compilation so that we are not doing a per-particle, per frame calculation to set pivot. This means the pivot would be a constant per particle system, which I believe is a fair trade off for the flexibility to move the pivot for customizing the particle system.

**Comment by thomlucc** [comment]
Duplicate
