### ISSUE TITLE
Change mime type of .wasm files served from the preview CDN

### ISSUE THREAD

**Issue by Popov72** [BabylonJS/Babylon.js#11454]
To avoid warnings in the browser console log, we should serve .wasm files as `application/wasm` instead of `application/octet-stream`.

**Comment by RaananW** [comment]
This was done and already working:
![image](https://user-images.githubusercontent.com/1381702/141770509-000c824c-8db5-4feb-a765-db1ceba0a672.png)

**Comment by Popov72** [comment]
It seems it's not a global setting of the server:
![image](https://user-images.githubusercontent.com/4152247/141772580-afd36da6-f71e-438f-9a20-1602b0e54d2c.png)

![image](https://user-images.githubusercontent.com/4152247/141772677-a5fc5003-4d4f-4b1a-91da-7f0d939c3591.png)

**Comment by RaananW** [comment]
It might take some time to propagate, but this is the result I am getting:

![image](https://user-images.githubusercontent.com/1381702/141784731-d7e9579a-c688-4f31-ab12-98d462545ade.png)

Can you try clearing your disk cache and see if it works?

**Comment by Popov72** [comment]
Yes, a cache clear did it!
