### ISSUE TITLE
Engine.prototype.version (Inherited from ThinEngine) returns undefined

### ISSUE THREAD

**Issue by dr-vortex** [BabylonJS/Babylon.js#11488]
**Repro**
- Bug repro on playground: Not available, please read the second paragraph of [the forum post](https://forum.babylonjs.com/t/typeerror-cannot-set-property-version-of-object-object-which-only-has-a-getter/25397)
- Expected result: Unknown, most likely returning the Babylon version
- Current result: Empty but can't be set to a custom value

**Desktop**
 - OS: ChromeOS 94
 - Browser: Chrome 94
 - Version: Babylon 5.0 alpha 61

**Additional context**
*From [the form post](https://forum.babylonjs.com/t/typeerror-cannot-set-property-version-of-object-object-which-only-has-a-getter/25397):*
I'm currently developing a space game called [Annihilation](https://annihilation.drvortex.dev) using Babylon.js and recently decided to start working on updating to Babylon 5.0. I'm now getting an error with Babylon 5 (alpha 61) where I can't set `Engine.prototype.version` without Babylon throwing a TypeError (title). Renaming the property works fine, though I would prefer to keep the current property name. How can I fix this?

The game has other libraries and dependencies that make creating a playground for it very difficult. Please use [this](https://annihilation.drvortex.dev/versions/infdev/temp) link to access the game, and F12/Devtools to view the source code and such.

**Comment by deltakosh** [comment]
@sebavan  / @RaananW can you folks have a look?

**Comment by deltakosh** [comment]
Ok sorry I did not read the forum.
Quoting @RaananW: 
![image](https://user-images.githubusercontent.com/1306056/142479313-0663cf08-a555-4866-8c74-55ecc46957f2.png)
