### ISSUE TITLE
Babylon GUI's HolographicSlate doesn't support linked nodes

### ISSUE THREAD

**Issue by rickfromwork** [BabylonJS/Babylon.js#11524]
https://www.babylonjs-playground.com/#Q1R5XX#1

The documentation here (https://doc.babylonjs.com/divingDeeper/gui/gui3D#controls) seems to imply that controls can be 'linked' to objects in the scene, and in fact this can be seen to be true for almost every 3D control. But if a HolographicSlate is linked to an object, either by calling linkToTransformNode() or setting node.parent, then the slate position's z-axis will perpetually increase over time, sending the slate off into the distance. Additionally, if the slate is scaled in any way, it will travel off either diagonally up-left (for a larger slate) or down-right (for a smaller slate).

I think it might have something to do with the fact that the slate uses a custom pivot point, but I'm not familiar enough with pivots, parenting, or the original implementation of the slate to look further.

**Comment by CraigFeldspar** [comment]
some pointers for whomever may take this issue : the pivot point is set to the center, whereas the slate's origin is the topleft corner. This is done so the slate's handles (to resize and rotate) are just changing the pivot point and not the position

**Comment by RaananW** [comment]
Narrowed it down to the follow behavior's `_updateLeashing` function, which sets the parent to null and back again on each frame.

This seems to be an issue with computeWorldMatrix, when the mesh has a pivot and scaling (and not directly with the follow behavior / holographic slate):

https://playground.babylonjs.com/#2J03YY#1

@CraigFeldspar - A general question regarding the follow behavior - is there a reason this function is running even when the follow behavior is not turned on?

**Comment by CraigFeldspar** [comment]
@RaananW I can't remember precisely, but `_updateLeashing` should be only used for an activated followBehavior

**Comment by RaananW** [comment]
> @RaananW I can't remember precisely, but `_updateLeashing` should be only used for an activated followBehavior. Maybe this is a bug ?

I've fixed it in the linked pull request. It now only runs when the feature is enabled. Thanks for confirming!
