### ISSUE TITLE
Userighthandedsystem + button text bug

### ISSUE THREAD

**Issue by msDestiny14** [BabylonJS/Babylon.js#11543]
When using scene.useRightHandedSystem = true; Appears that the text was flipped correctly but button isn't flipped.
Or should the text not flip at all? 

https://forum.babylonjs.com/t/userighthandedsystem-button-text-bug/25547

**Comment by carolhmj** [comment]
IMO the text shouldn't flip, the user shouldn't have to worry about handedness when they just want to render buttons. @msDestiny14 @deltakosh what do you think?

**Comment by deltakosh** [comment]
> IMO the text shouldn't flip
yes

**Comment by sebavan** [comment]
Totally onboard, it feels like a bug.
