### ISSUE TITLE
Loaded .basis textures don't actually have LINEAR_LINEAR_MIPLINEAR sampling initially

### ISSUE THREAD

**Issue by darraghjburke** [BabylonJS/Babylon.js#11549]
Issue stemming from forum: https://forum.babylonjs.com/t/no-mipmap-for-basis-universal-texture/25403/7

This .basis texture loads with a sampling mode of LINEAR_LINEAR_MIPLINEAR. However, if run updateSamplingMode(LINEAR_LINEAR_MIPLINEAR), the texture breaks. This can only be fixed by setting it to some sampling mode without a _MIP option. You can play around with the different sampling modes in the inspector to see which ones work.

There really might be two issues here:
- ~~why does the texture break under any sampling mode with a _MIP option?~~ Edit: according to forum thread, this is because the texture was not built with the -mipmaps flag on. This makes sense. However, the following issue is still here:
- why does the texture not have that sampling mode set initially, even though the texture object thinks it does?

**Repro**
- Bug repro on [playground](https://playground.babylonjs.com/#E4VDDW#10):
- Expected result: the texture should not break when you set the sampling mode to LINEAR_LINEAR_MIPLINEAR, as that should be the sampling mode already (check console for evidence)
- Current result: the object becomes black.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Edge (repros in FF as well)
 - Version 96.0.1054.34

**Comment by sebavan** [comment]
@darraghjburke are you working on the fix ? to be sure who to assign it to ?

**Comment by darraghjburke** [comment]
> @darraghjburke are you working on the fix ? to be sure who to assign it to ?

I am investigating with @bghgary, I'll assign it to myself for now, I am not sure I will be able to implement the fix though

**Comment by Popov72** [comment]
I can have a look if you want?

**Comment by sebavan** [comment]
Would be great !!!

**Comment by Popov72** [comment]
Fix in #11561
