### ISSUE TITLE
[XR] Camera get higher when re-entry

### ISSUE THREAD

**Issue by shang-huang** [BabylonJS/Babylon.js#11603]
**Repro**
- Bug repro on [https://playground.babylonjs.com/#B123IQ](https://playground.babylonjs.com/#B123IQ):
- Expected result: 1.6
- Current result: when re-enter WebXR the Y of camera keep add 1.6, like 3.2, 4.8 ...

**Desktop:**
 - OS: [e.g. macOS]
 - Browser [chrome w/ WebXR Simulator]
 - Version [96]

**Smartphone:**
 - Device: [Oculus Quest]
 - Browser [Oculus Browser]
 - Version [16.2]

**Comment by deltakosh** [comment]
Please use the forum first as stated in the issue template
