### ISSUE TITLE
[Snippet Server] Check caching settings on the snippet server

### ISSUE THREAD

**Issue by RaananW** [BabylonJS/Babylon.js#11614]
Let's check if we can cache requests locally (using the response headers), as snippets are guaranteed to be immutable.

See https://forum.babylonjs.com/t/gui-parsefromsnippetasync-xhr-request-appears-to-bypass-browser-cache/25905

**Comment by RaananW** [comment]
This will require setting a CDN profile to the snippet service.

@deltakosh - the snippet server is still hosted on the old subscription. Do we want to move it to the new subscription?

**Comment by deltakosh** [comment]
yes please :D

**Comment by RaananW** [comment]
Snippet moved, caching and CDN was enabled

**Comment by deltakosh** [comment]
You rock!
