### ISSUE TITLE
Parent node for all created WebXR nodes

### ISSUE THREAD

**Issue by darkverse** [BabylonJS/Babylon.js#11672]
# Feature request

- as discussed on the forum here: https://forum.babylonjs.com/t/webxr-keepassets-and-assetcontainers
- WebXR currently creates nodes, such as controllers at the root level, when trying to use in conjunction with KeepAssets and scene switching/AssetContainers it would be easier to maintain, and would be overall neater anyway, if all WebXR created nodes/objects were parented to a WebXR_root TransformNode (say).

**Comment by thomlucc** [comment]
https://forum.babylonjs.com/t/parent-node-for-all-created-webxr-nodes/52148
