### ISSUE TITLE
Incorrect camera collisions when scene is right handed

### ISSUE THREAD

**Issue by carolhmj** [BabylonJS/Babylon.js#11688]
Forum discussion: https://forum.babylonjs.com/t/problem-when-checkcollisions-and-userighthandedsystem-are-used-together/26248

**Repro**
- Bug repro on [playground](https://playground.babylonjs.com): https://www.babylonjs-playground.com/#I6J7UZ#47
- Expected result: Player should be able to walk on the ground
- Current result: Player clips through the mesh

**Additional context**
Doesn't seem to happen when using a plane ground or even a ground created from a height map: https://playground.babylonjs.com/#LQ4LI1#131

**Comment by carolhmj** [comment]
Digging into this, it happens because, when we load a GLTF in a RHS scene, we don't add the transforms that would convert it to LHS in the root. So the triangle ends up with the wrong orientation on the collider. I'm thinking about the best way to solve this. Maybe add a flag on the AbstractMesh, set it to true when loading this specific case (GLTF mesh on RHS scene), and when checking collisions, if the flag is true, we then apply the RHS -> LHS transformation?

**Comment by Popov72** [comment]
Maybe you can use `mesh.overrideMaterialSideOrientation` because the glTF loader is doing this:

```javascript
babylonMesh.overrideMaterialSideOrientation = this._babylonScene.useRightHandedSystem ? Material.CounterClockWiseSideOrientation : Material.ClockWiseSideOrientation;
```

The glTF loader is the only subsystem that is writing this property (it is `null` by default), so if it is equal to `Material.CounterClockWiseSideOrientation` you know you are currently handling a mesh loaded from glTF in a rhs.

**Comment by sebavan** [comment]
@carolhmj Any updates on this one ?

**Comment by carolhmj** [comment]
Working on it! I fixed the model colliding with the ground plane, however, in the forum example I was still getting weird collisions on the hills and walls, so I wanted to dig into it a little more before opening a PR.
