### ISSUE TITLE
When a value required for a property needs to be in Radians docs should specify that

### ISSUE THREAD

**Issue by Michael-Z-Freeman** [BabylonJS/Babylon.js#11700]
Hi,

Discussed here - https://forum.babylonjs.com/t/cannot-get-poster-image-to-show-for-videotexture/26352/9

For example (I'm sure there are others as well) ...

https://doc.babylonjs.com/typedoc/classes/babylon.videotexture#wang 

which states ...

"_wAng: number_".

I assumed the value was in degrees not radians.

The docs could say something like "_wAng: number (Radians)_".

Cheers

**Comment by sebavan** [comment]
fixed in the next nightly in a couple hours
