### ISSUE TITLE
Types still use `WebGLObject`

### ISSUE THREAD

**Issue by lgarron** [BabylonJS/Babylon.js#11701]
TypeScript hasn't had `WebGLObject` defined for quite a while now, but the latest `@babylonjs/core` published types still seem t use it:

https://unpkg.com/browse/@babylonjs/core@4.2.0/Engines/engine.d.ts

This causes issues for project that checks TypeScript correctness across dependencies. :-(

**Comment by sebavan** [comment]
This is all good on our latest preview, This is a following a change in the ts types that we fixed since.

**Comment by lgarron** [comment]
> This is all good on our latest preview, This is a following a change in the ts types that we fixed since.

Ah, okay, so e.g. `5.0.0-alpha.65` ?

https://unpkg.com/browse/@babylonjs/core@5.0.0-alpha.65/Engines/engine.d.ts
