### ISSUE TITLE
[GUI] TextBlock controls are clipped even when the parent's clipChildren and clipContent values are false

### ISSUE THREAD

**Issue by darraghjburke** [BabylonJS/Babylon.js#11733]
**Repro**
- Bug repro on [playground](https://playground.babylonjs.com/#AIRL47)
- Expected result: The full text should display, no matter how long the width is.
- Current result: The text is clipped to 100px. As you can see, the white rectangle does still display at full width, but not the text.

**Screenshots**
![image](https://user-images.githubusercontent.com/1342157/148455168-e73b204b-57a6-41f2-a136-5b0d91c43b29.png)

**Desktop):**
 - OS: Windows
 - Browser Edge
 - Version 96

**Comment by darraghjburke** [comment]
Actually, this might be expected. The text width is "100%", which makes it the width of the container. So it's actually clipping itself. If you explicitly set the width to 300px, it no longer clips. This is a bit confusing, but I guess it's not a bug.

**Comment by darraghjburke** [comment]
If I set resizeToFit to true, it no longer clips: https://playground.babylonjs.com/#AIRL47#1. I'm going to take the bug label off, but we may still want to make this less confusing.

**Comment by deltakosh** [comment]
> we may still want to make this less confusing

How?

**Comment by darraghjburke** [comment]
At least for the GUI editor (where I first noticed this), we could put resizeToFit on by default. I think this is the behavior that users would expect from a WYSIWYG tool; if I type more text, the size of my text block should grow, unless I explicitly set it to a fixed size.

We can't do this for GUI since it would break back compat.

**Comment by deltakosh** [comment]
Works for me!

**Comment by darraghjburke** [comment]
Issue moved to [BabylonJS/ThePirateCove #147](https://github.com/BabylonJS/ThePirateCove/issues/147) via [**ZenHub**](https://www.zenhub.com/)
