### ISSUE TITLE
Browser freezes when loading model

### ISSUE THREAD

**Issue by carolhmj** [BabylonJS/Babylon.js#11747]
Related forum issue: https://forum.babylonjs.com/t/problem-when-checkcollisions-and-userighthandedsystem-are-used-together/
This behavior doesn't happen on 4.2.

**Repro**
- Bug repro on [playground](https://playground.babylonjs.com): https://www.babylonjs-playground.com/#I6J7UZ#49

**Comment by RaananW** [comment]
A very quick test running a profiler:

![image](https://user-images.githubusercontent.com/1381702/148823476-73c32183-cc0c-40d2-8b22-0025e338a867.png)

It seems like the main issue is `texImage2D`, which is (theoretically?) out of our control. The entire process took ca. 24 seconds (on my device).

However, testing the same demo with 4.2.1 takes 5 seconds on average (!!!) and doesn't block the main UI thread:

![image](https://user-images.githubusercontent.com/1381702/148823923-3f0f5510-8afe-4b32-88b8-929e1564e0e3.png)

@bghgary - did something change in the way we are parsing images?

**Comment by deltakosh** [comment]
cc @Popov72 as this could also be related to WebGPU changes we did in the root engine

**Comment by deltakosh** [comment]
ok it is related to SRGB buffer support

**Comment by deltakosh** [comment]
@RaananW will fix it tomorrow
