### ISSUE TITLE
Externally changing webXR headset blocks entry into webXR

### ISSUE THREAD

**Issue by rickfromwork** [BabylonJS/Babylon.js#11740]
When using the Mixed Reality Portal with Microsoft HMDs, it is possible to enable simulation mode where a headset is simulated. This can be used for more rapid testing, since a physical HMD takes time to take on/off.

But if a webXR playground is launched and webXR is entered when using a simulated headset, then trying to use a real one afterwards will not work. The user will press the button to enter XR, the icon will flash the word "Exit", and will return to the in-browser scene. No error message appears in the console.

The only way to get it to work with the new headset is to completely restart the browser, or change browsers. The same applies in the other direction (trying a physical headset first prevents a simulated headset from ever working on that browser instance). The original HMD will also work fine if it is switched back to.

From this, it _seems_ like it tries to enter XR, but detects a different headset than what was used originally, so it cleanly exits back to the browser.

**Comment by RaananW** [comment]
This seems to be a limitation within the browser. We don't detect any of the headsets, but let the browser decide which headset is going to be used. The same goes to changing the OpenXR runtime. Let's say you have an oculus rift and set it to be the default OpenXR runtime - when entering XR you will use the rift from now on. but if you change the runtime to the MR portal while the browser is still running, it will not switch devices. Not until you restart the browser. 
I'll investigate a bit to see if it is possible to "reload" without actually reloading the browser, but I have a bad feeling the answer would be "you have to restart"
