### ISSUE TITLE
Playground content created via document.createNode() does not clear on loading a different playground

### ISSUE THREAD

**Issue by rickfromwork** [BabylonJS/Babylon.js#11755]
Step 1: Load the following playground:
https://playground.babylonjs.com/#2ARI2W#152

Step 2: Change the playground iteration (#152 in the URL) to a different value (or remove it), and navigate to the new URL

Expected: All content created within the playground editor is cleared and replaced with content from the new playground
Actual: "document"-based calls are not reverted, leaving them present in all future playgrounds until page is properly refreshed (since modifying the playground iteration doesn't refresh the page)

**Comment by deltakosh** [comment]
It is up to the user to clear that when the engine is disposed (or at least the scene with scene.onDispose handler).

How do you propose to track what the user created? We can probably tag our elements I guess

**Comment by deltakosh** [comment]
Ideally we expect the users to open a chat on the forum first so we can have all our community to contribute to the discussion.

**Comment by RaananW** [comment]
will be very hard to track the entire DOM. We could hard-refresh all DOM elements? Add some state change to the parent and redraw everything. Just a thought?

**Comment by deltakosh** [comment]
Honestly I'm more incline to do nothing :)

**Comment by RaananW** [comment]
> Honestly I'm more incline to do nothing :)

This is probably the cleanest solution :-)
