### ISSUE TITLE
Yoyo loop mode for animations

### ISSUE THREAD

**Issue by BlakeOne** [BabylonJS/Babylon.js#11785]
Please add a new animation loop mode that reverses the direction of the animation when it reaches the end instead of restarting the animation from the beginning.

Ideally this yoyo/mirror looping would be as easy to use as the normal looping, by simply specifying a different constant for the loop mode: e.g. by simply passing Animation.ANIMATIONLOOPMODE_YOYO instead of _CYCLE.

Forum discussion: https://forum.babylonjs.com/t/yoyo-mirror-looping/26687/6

**Comment by deltakosh** [comment]
PG to test: https://playground.babylonjs.com/#FFDIXK
