### ISSUE TITLE
load glb file error

### ISSUE THREAD

**Issue by peterpanBest** [BabylonJS/Babylon.js#11802]
i use Babylon.js v4.2.1

`
      SceneLoader.ImportMeshAsync(null, '/assets/models/gltf/', 'car.glb', SCENE, (res) => {
        console.log(res)
      })
`
but some error in devtool 

`
Unable to find a plugin to load .glb files. Trying to use .babylon default plugin. To load from a specific filetype
`
what should i do ? Thanks !

**Comment by carolhmj** [comment]
Please discuss on our forum first (https://forum.babylonjs.com/c/bugs/8) before opening an issue here.
