### ISSUE TITLE
[NME] Add alpha and alphaMode to NME parameters panel

### ISSUE THREAD

**Issue by PatrickRyanMS** [BabylonJS/Babylon.js#11805]
We currently write out the alpha factor and alphaMode for a node material if those parameters are set in the inspector and then the node material is saved to a file or snippet through NME. It would be preferable to be able to set these right in NME through the general parameters when no node is selected. Seems like they would fit between Snippet and Inputs:

![image](https://user-images.githubusercontent.com/31326855/150247204-dd860ec2-f09e-4a63-9473-9ec9c8698b32.png)

There is one bit of complexity here which is that I found some opacity parameters on the PBRMetallicRoughness node. This seems like a strange place for them as you may want to set some of these without using the PBR node. Not sure if relocating them from this node to more general parameters would be problematic.  

![image](https://user-images.githubusercontent.com/31326855/150247459-eb03946a-ce7c-47d3-b4e3-93a51e5bd676.png)

**Comment by deltakosh** [comment]
I'm not sure to follow. All these properties are only available on pbrMetallicRoughness block

Can you elaborate more on why you want to move them?

**Comment by deltakosh** [comment]
Well after looking more into we should not move these properties are they are intrinsic to the pbrMetallicRoughness 

I will add the alpha and alphaMode to general NME properties
