### ISSUE TITLE
KTX decoder appears to leak memory each time it is used

### ISSUE THREAD

**Issue by bghgary** [BabylonJS/Babylon.js#11839]
There are two forum issues that are possibly the same issue:
https://forum.babylonjs.com/t/how-to-release-ressources-for-ktx2-textures/25176
https://forum.babylonjs.com/t/opacitytexture-not-working-on-ios-15-devices/25102

The former is more directly indicating there is a leak. The original issue for second link is already fixed, but the scenario will crash when loading lots of KTX textures which I suspect may be because of the memory leak. I've already spent some time looking into the memory leak, but haven't figured out the root cause yet.

See the forum issues for a repro.

**Comment by deltakosh** [comment]
cc @Popov72 just in case he is bored ;)
