### ISSUE TITLE
Add support for non-multiview rendering with texture-array composition layers

### ISSUE THREAD

**Issue by rgerd** [BabylonJS/Babylon.js#11848]
This issue comes from https://github.com/BabylonJS/Babylon.js/pull/11828

We currently can't explicitly associate a `RenderTargetTexture` with a layer index in an underlying texture of type `TEXTURE_2D_ARRAY`. This is necessary to be able to render to specific eyes in composition layers initialized with `textureType = 'texture-array'`. Perhaps we could subclass `RenderTargetTexture` with a type that calls `engine.bindFramebuffer` with the layer associated with it--in the case of composition layers this would be the `subImageIndex` in the `XRWebGLSubImage` returned from `XRWebGLBinding.getSubImage`.

**Comment by thomlucc** [comment]
@RaananW - can you assign the correct milestone?

**Comment by thomlucc** [comment]
https://forum.babylonjs.com/t/add-support-for-non-multiview-rendering-with-texture-array-composition-layers/52146
