### ISSUE TITLE
Near Menu cannot be dragged when in immersive mode

### ISSUE THREAD

**Issue by RaananW** [BabylonJS/Babylon.js#11875]
See https://forum.babylonjs.com/t/near-menu-dragging-does-not-work-in-oculus-quest-2/27152

https://playground.babylonjs.com/#8RLLVP#1

@CraigFeldspar - do you have an idea what might be the cause here?

**Comment by RaananW** [comment]
I'll test it on both hololens and oculus and see what the state in both.

**Comment by RaananW** [comment]
It only works with the near interaction plugin and not with the pointer selection. @CraigFeldspar - is there any specific code in the near interaction that enables that?

**Comment by CraigFeldspar** [comment]
Sorry for the delay

In the near menu, as in several 3D controls, there is a `this._defaultBehavior` that encapsulated a `sixDofDragBehavior`. This is the part that should handle the pointer drag.
See https://github.com/BabylonJS/Babylon.js/blob/83145ae189d61577252935667f71701cf5ebfca3/gui/src/3D/controls/nearMenu.ts#L120

**Comment by RaananW** [comment]
This has been resolved and is working correctly now.
