### ISSUE TITLE
[GE] [NME] [WebGL1] 'round' : no matching overloaded function found 

### ISSUE THREAD

**Issue by RaggarDK** [BabylonJS/Babylon.js#11878]
For those of us unfortunate enough to still be stuck with WebGL1, round is not a function, and results in the GUI Editor not working, as well as the Round node in the Node Material Editor producing an error. 
I'm not sure what the best approach would be, other than perhaps adding to the helperFunctions, as it is included in shaders generated by both
float round(float a){
    return floor(a + 0.5);
}
vec2 round(vec2 a){
    return vec2(floor(a.x + 0.5),floor(a.y + 0.5));
}
etc.

**Comment by deltakosh** [comment]
Hello please use the forum to start discussion about issues (as stated in the issue template)

cc @DarraghBurkeMS
