### ISSUE TITLE
AssetContainer addAllToScene and removeAllFromScene should also handle particle systems

### ISSUE THREAD

**Issue by darkverse** [BabylonJS/Babylon.js#11897]
# Feature request

- Link to [forum](https://forum.babylonjs.com/) discussion about the feature:
https://forum.babylonjs.com/t/webxr-keepassets-and-assetcontainers/24705/7

- Feature description
Add and remove particle systems in line with other asset types in the AssetContainer addAllToScene and removeAllFromScene methods.

**Comment by deltakosh** [comment]
Good one!
