### ISSUE TITLE
Export to GLB Nodes have Incorrect Rotation

### ISSUE THREAD

**Issue by ecoinomist** [BabylonJS/Babylon.js#11905]
As discussed over the [forum](https://forum.babylonjs.com/t/exported-gltf-scene-does-not-have-material-color-in-blender/27235/9?u=ecoin).

**Repro**
- Bug repro on [playground](https://playground.babylonjs.com/#YIU90M#672):
- Expected result: Nodes/Meshes to have correct rotation, with Babylon's positive z axis match Blender's positive y axis direction
- Current result: Nodes/Meshes are incorrectly rotated by Math.PI, with Babylon's positive z axis matching Blender's negative y axis direction.

**Screenshots**
Blender
<img width="333" alt="Screen Shot 2022-02-03 at 3 31 03 AM" src="https://user-images.githubusercontent.com/13236298/152260979-c7462035-a5de-4049-9a09-ae3b617fd1f0.png">
Babylon
<img width="654" alt="Screen Shot 2022-02-03 at 3 29 33 AM" src="https://user-images.githubusercontent.com/13236298/152261004-d7b502b2-a30f-4eeb-b5da-d8a491d04290.png">

**Desktop:**
 - OS: macOS Big Sur 11.4
 - Browser Chrome
 - Version 97.0.4692.99

**Steps to reproduce:**
1. in [PG]((https://playground.babylonjs.com/#YIU90M#670)), open Inspector and click Scene Export → Export to GLB
2. Open Blender (v2.8+) New project, Import → glTF 2.0

**Comment by deltakosh** [comment]
Up @CedricGuillemet

**Comment by CedricGuillemet** [comment]
As said in the forum thread, I don't see any issue with Babylon js .glb export, in RH or LH when testing with BJS importer or Three importer. To me, it's an issue with Blender. Do you confirm @bghgary ?
