### ISSUE TITLE
Incorrect collision response

### ISSUE THREAD

**Issue by ottoville** [BabylonJS/Babylon.js#11916]
**Repro**
Playground with slope and "car" that is represented as 1x1x1 collider. Ellipsoid is defined on line 51
https://playground.babylonjs.com/#4HUQQ#1812

Press "arrow up" to try to reach the box on the hill. The car will slide down when reached the box and arrow key is released, impossible on stay where the box is.

Same playground with "motorcycle", represented as {0.2, 1, 0,2} collider, meaning that its much taller than wide.
https://playground.babylonjs.com/#4HUQQ#1813

Press "arrow up" to try to reach the box on the hill. The motorcycle will **not** slide down when reached the box and arrow key is released, it has good grip.

**Expected results:**
Both car and motorcycle behaves same, collider size does not impact on sliding distance.

**Actual result:**
Collider shape is impacting on gravity pull.

**Additional context**

The sliding distance is calculated using dot product of collision angles. **Maybe** these angles are different in ellipsoid space where collision is calculated, they are subject to ellipsoid ratio, resulting bad values using in calculation.
![image](https://user-images.githubusercontent.com/2173773/152512307-f6f5c515-c2b1-42b3-b2bb-eb1f5a443a44.png)

**Comment by CedricGuillemet** [comment]
The shape of the collider changes the point of collision. For a thin shape, the collision point will be lower and closer to the ground. Depending on this collision point, the velocity will change as well. Shape impacts the gravity application. It's part of the algorithm and its sliding. There is notion of friction or allowed slope.
This collision process exists for cameras (like a camera following a character in a TPS). For more controls on the physics, using a physics engine seems more appropriate to me.
