### ISSUE TITLE
Address comment for shadow generator

### ISSUE THREAD

**Issue by bghgary** [BabylonJS/Babylon.js#11935]
See https://github.com/BabylonJS/Babylon.js/pull/11919#discussion_r801101168

@Popov72 
> I think the condition should be `if (effectiveMesh !== renderingMesh && !isInstance) {` to be iso with the previous code.
> 
> Indeed, in the case where hardware instance rendering is not supported, `Mesh._processRendering` was calling the callback with `isInstance==true` and `effectiveMeshOverride==undefined` with the old code. In that case, we executed the `else` branch, so we should also do it with the new code.
> 
> Also, I think there's a bug in the old code, I think `effectiveMesh.transferToEffect(world);` should be `effectiveMesh.transferToEffect(isInstance ? worldOverride : world);` so that we use the world matrix passed to the function (which is the world matrix of the instance) when hardware instance rendering is not supported...
> 
> The relevant bit of code from `_processRendering` is:
> ```typescript
> var world = instance.getWorldMatrix();
> if (onBeforeDraw) {
>     onBeforeDraw(true, world, effectiveMaterial);
> }
> ```

**Comment by Popov72** [comment]
Some more explanations:

https://github.com/BabylonJS/Babylon.js/pull/11919#discussion_r801344513
