### ISSUE TITLE
Export PNG from serializers without losing color information due to premultiplied alpha

### ISSUE THREAD

**Issue by bghgary** [BabylonJS/Babylon.js#11967]
See https://forum.babylonjs.com/t/exported-gltf-scene-does-not-have-material-color-in-blender/27235/27 for context.

The gist of the problem is that color information with non-1 alpha doesn't export properly because the code currently uses canvas to get the PNG and the canvas premultiplies alpha.

I found a way to use offscreen canvas, image bitmap, transferFromImageBitmap, and convertToBlob that appears to keep the color information intact. It also doesn't translate from and to base64 which should mean it will be faster.

https://jsfiddle.net/k63b2vL7/

Question: Does this work on all relevant browsers?

**Comment by ecoinomist** [comment]
I'm getting empty white screen on Chrome, MacOS , for jsfiddle link. 
https://caniuse.com/createimagebitmap - apparently it's not widely supported yet.

**Comment by bghgary** [comment]
Oops, no, it's because I forgot to save the final version, lol.

Link updated.

**Comment by ecoinomist** [comment]
Updated link worked in chrome. Downloaded correct Image. Safari and Firefox didn't download anything, but that's because the jsfiddle itself is not properly configured in this browsers.

Updated fiddle to show image, instead of downloading it:
https://jsfiddle.net/rgtj3n9L/
