### ISSUE TITLE
Babylon MeshBuilder meshes exported to glTF have incorrect UV orientation 

### ISSUE THREAD

**Issue by PatrickRyanMS** [BabylonJS/Babylon.js#11963]
When we export a scene with the glTF exporter in the inspector and that scene contains meshes made with `MeshBuilder`, no adjustment is made to the UVs of the mesh before exporting. When we import a glTF file, we assume the UV space conforms without the need to invert the texture so we import any texture contained in the glTF with `Texture.invertY` set to false. `MeshBuilder` meshes require textures to have `Texture.invertY` set to true to render correctly as the `MeshBuilder` UV space is inverted from glTF. 

This means on export to glTF through our inspector tool, we need to invert the UVs on the `MeshBuilder` meshes to match with what glTF expects because when we load it back in, the glTF loader will set embedded textures to have `Texture.invertY` set to false and textures on meshes that were originally `MeshBuilder` meshes will render inverted.

In the image below, the plane was a `MeshBuilder` mesh that was exported to glTF. You can see that on load, the texture has `Texture.invertY` set to false, but the render on the mesh does not match the image in the inspector.

One more caveat. There is a PR https://github.com/BabylonJS/Babylon.js/pull/11962 going in to create a flag that will invert `MeshBuilder` UV space to match glTF when meshes are created if enabled. This will allow users to pass textures back and forth between glTF meshes and `MeshBuilder` meshes without needing to manage `Texture.invertY` as they are passed. If that flag is enabled, we do not want to invert `MeshBuilder` UV space when exporting to glTF because it will already match glTF UV space.

Screenshot:
![image](https://user-images.githubusercontent.com/31326855/153512918-1c19803e-f754-44f4-9f4c-5a257eac26f0.png)

Repro:
https://playground.babylonjs.com/#KZDXTB#22

**Comment by deltakosh** [comment]
Flagged as 6.0 as this will require a lot of exploration to define how we know which convention was used

**Comment by deltakosh** [comment]
Oh I see.. We assume that invertY is always for bjs mode... Yeah that can work :)

Flagging back to 5.0

**Comment by PatrickRyanMS** [comment]
We are inverting the texture on export rather than UV space for Babylon.MeshBuilder objects. This means that the behavior of the repro above is correct and the onus will be on the user to correctly flip textures assigned to any Babylon meshes round tripping through glTF as there is no texture orientation convention that we can point to in the glTF spec.
