### ISSUE TITLE
Rendering issue on instances at different distances

### ISSUE THREAD

**Issue by Exolun** [BabylonJS/Babylon.js#11981]
**Repro**
- Bug repro on [playground](https://playground.babylonjs.com/#BW61N4#1):
- Expected result: All 3 smiley face cubes should look the same
- Current result:  The one that's slightly closer renders differently - looks more transparent than the other two.

**Screenshots**
The leftmost is the original, middle is the first instance - second one is the second / closer instance displaying the rendering issue.  Note that only the planes in front of the head cube are instanced.
![image](https://user-images.githubusercontent.com/6227906/154331147-47cb9b3d-36f5-45e4-b516-4b5bdc574f9e.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Version: 98.0.4758.82

**Comment by deltakosh** [comment]
Unfortunately this is not a bug. To get transparency correctly we need to order the meshes from back to front. When you are using instances, we cannot sort them anymore as they are rendered with one draw call and thus will only depend on where the source for the instances is.

To "fix" your issue you will have to NOT use instances but clones

**Comment by deltakosh** [comment]
One thing you can do is to set the alphaIndex of the source faceMesh: https://playground.babylonjs.com/#BW61N4#2

That way you can at least guarantee that faces are always rendered after the cubes

**Comment by Exolun** [comment]
Ahh thanks David!  Using alphaIndex should work as a solution for now.

**Comment by Popov72** [comment]
Note that you now have `Mesh.INSTANCEDMESH_SORT_TRANSPARENT` that lets you handle this case: just set it to `true`.

**Comment by deltakosh** [comment]
Oh man! I completely forgot about this one! Thanks a lot @Popov72 
This is even better!
