### ISSUE TITLE
[GUI] HolographicSlate manipulation handles don't scale with slate

### ISSUE THREAD

**Issue by rickfromwork** [BabylonJS/Babylon.js#11980]
Slate handles are far too small when the slate is default-scaled. They are appropriately sized when GUI3DManager.UseRealisticScaling is true, though.

Default scaling:
<img width="810" alt="image" src="https://user-images.githubusercontent.com/70608380/154152873-49faf01e-b674-4b83-8e57-9f5f13acdf56.png">

GUI3DManager.UseRealisticScaling:
<img width="244" alt="image" src="https://user-images.githubusercontent.com/70608380/154153102-2b3333ad-0c7b-4d64-bde6-d57d67148429.png">

**Comment by RaananW** [comment]
@rickfromwork - will you be able to fix that? Is the solution for this issue to use realistic scaling?

**Comment by rickfromwork** [comment]
Fixed with #12028
