### ISSUE TITLE
Image for validation test "GLTF ext MSFT_LOD" not ok

### ISSUE THREAD

**Issue by Popov72** [BabylonJS/Babylon.js#12015]
This validation test ("GLTF ext MSFT_LOD") does not fail because there's not enough differences for the error to kick in, but we can clearly see in the picture that the current rendering does not match the test picture:

![image](https://user-images.githubusercontent.com/4152247/155004342-2ee76c2c-49e5-4800-a807-53fe46e9935c.png)

Maybe the current rendering is ok and the test picture should be updated, or maybe the rendering is wrong. I don't know so I let you guys see what's going on.

**Comment by sebavan** [comment]
@bghgary changed the MSFT_LOD recently so I guess it is an image issue ?

**Comment by sebavan** [comment]
@Popov72, thanks a ton for reporting it !!!

**Comment by bghgary** [comment]
I removed the MSFT_lod as rendering LOD support because it wasn't complete and caused some issues. This test is trying to test that. I will remove the test.

**Comment by bghgary** [comment]
PR in question: https://github.com/BabylonJS/Babylon.js/pull/11840
