### ISSUE TITLE
Sandbox issue

### ISSUE THREAD

**Issue by roy-baker** [BabylonJS/Babylon.js#12029]
I have some users that are receiving this error message when the Sandbox tries to view the GLB export from the 3ds Max babylon.js exporter. It happens with all browsers:

"We're working to restore all services as soon as possible. Please check back soon.

00FkVYgAAAACTI1RSPLJBT4wl0ZkA1QDnRVdSMzBFREdFMDUxMQBFZGdl"

I am assuming it's a setting somewhere on their Windows 10 machines.

**Comment by deltakosh** [comment]
Hey please use our forum to ask question as state in the Github issue template:)

forum.babylonjs.com

Thanks!

**Comment by roy-baker** [comment]
Hi David. Thanks, I wasn’t sure if there was a Q/A section for issues like the one I posted. Thanks for the clarity. You can delete it.

Roy Baker
Visualization Design Manager
Global R&D
millerknoll.com<https://www.millerknoll.com/>
Office +1 616 283 2286
[MillerKnoll]
