### ISSUE TITLE
WebGPU broke in safari 

### ISSUE THREAD

**Issue by hanzooo** [BabylonJS/Babylon.js#12033]
**Repro**
- Bug repro on [playground](https://playground.babylonjs.com): the WebGPU demo in safari can not show.
- Expected result: show the demo.
- Current result: it broke in safari with some error.

**Screenshots**
<img width="853" alt="image" src="https://user-images.githubusercontent.com/16368939/155316716-b44efbbe-999c-4840-b4b5-d1594705a6f3.png">

**Desktop (please complete the following information):**
 - OS: macOS Big Sur 11.4
 - Browser: safari 14.1.1 (16611.2.7.1.4) 
 - Version: Babylon.js 5.0.0-beta.11

**Additional context**

**Comment by sebavan** [comment]
Also please note WebGPU only works fine in latest Chrome Canary at the moment.
