### ISSUE TITLE
XR Modal Window

### ISSUE THREAD

**Issue by rickfromwork** [BabylonJS/Babylon.js#12071]
Introduce a modal dialog window control that can prompt the user for an interaction while inside an XR experience. 

Discussed here:
https://forum.babylonjs.com/t/webxr-friendly-pop-up-dialog-box/27944

Example running off of a HolographicSlate here:
https://playground.babylonjs.com/#R2GI49

While the example uses a HolographicSlate, when made into an actual control it shouldn't be a child of the slate class, since no title bar or resizability is needed.

**Comment by thomlucc** [comment]
Hi @rickfromwork, do you think you'll have some time to do it (we can also move this to Future releases). Thanks!

**Comment by thomlucc** [comment]
Closing for now. Feel free to re-open if needed.
