### ISSUE TITLE
Potential memory leak - Arc Rotate camera after attachControl

### ISSUE THREAD

**Issue by RaananW** [BabylonJS/Babylon.js#12086]
The ArcRotateCamerta stays in memory after disposing (and gc-ing) the scene and the engine, but only when attaching the camera.

The following code disposes all objects correctly:

```javascript
            const camera = new BABYLON.ArcRotateCamera("camera1", 0, 0, 0, new BABYLON.Vector3(0, 5, -10), window.scene);
            camera.setTarget(BABYLON.Vector3.Zero());
```

The following keeps the camera in memory:

```javascript
            const camera = new BABYLON.ArcRotateCamera("camera1", 0, 0, 0, new BABYLON.Vector3(0, 5, -10), window.scene);
            camera.setTarget(BABYLON.Vector3.Zero());
            camera.attachControl(true);
```

In this case it is hard to know what references the camera outside of the scene context.

**Comment by deltakosh** [comment]
waouh..this one will be a bit more tricky then :)

**Comment by RaananW** [comment]
I will see how we can simplify finding this out. One way would probably be to list the objects that were added using Object.prototype. Theoretically it should be an empty list, but because sometimes we have static objects (on the BABYLON namespace) it might be an acceptable increase. I'll see how we can improve on that.

**Comment by deltakosh** [comment]
Found it!

**Comment by RaananW** [comment]
can't wait to see what caused that...
