### ISSUE TITLE
Use Custom NME Material for shadow map shaders

### ISSUE THREAD

**Issue by sebavan** [BabylonJS/Babylon.js#12150]
Currently the shadow map setup in the shadow generator is all relying on an embedded OR custom shader. 

It would be great to be able to rely on a custom NME Material in place of the custom shader.

**Comment by Popov72** [comment]
What about the `ShadowDepthWrapper` class (https://doc.babylonjs.com/divingDeeper/lights/shadows#per-material-shadow-depth-map-shader)?

It also works for node materials.

**Comment by sebavan** [comment]
Ohhhhh right but in NME how would you go about creating a fully custom material to generate the shadow map and set it globally like the custom shader ? I can not find a sample with a custom nme material I could reuse on any other materials like a PBR or standard where I would use a plugin to sample the shadow map with another technic ?

**Comment by Popov72** [comment]
Indeed, using a node material to generate a shadow map is not possible, but I would think that wrapping a node material with `ShadowDepthWrapper` to generate the shadow map should cover most of the needs.

Have you a test case where being able to use a node material to directly generate the shadow map could be useful?

**Comment by sebavan** [comment]
Nope, unfortunately no test case so far, the request came from a partner willing to create their shadow map for NME based materials with NME as well, but I was not able to figure out if already possible or not :-( 

PS: shadowDepthWrapper would work if available on NME with NME

**Comment by Popov72** [comment]
Not sure I understood your last statement.

But you can simply do `nodeMaterial.shadowDepthWrapper = new BABYLON.ShadowDepthWrapper(nodeMaterial, scene)` to use the node material to render into the shadow map.

**Comment by Popov72** [comment]
Note that you can use another node material as the shadow depth wrapper, you are not compelled to use the same node material:

`nodeMaterial.shadowDepthWrapper = new BABYLON.ShadowDepthWrapper(otherNodeMaterial, scene)`

**Comment by deltakosh** [comment]
The problem is getting access to Shadow generator speciial data (like bias, etc...). So this can be summarized as:
- Create a shadowGenerator mode
- Add a specific new block in that mode: ShadowGeneratorData
- Add a documentation for it
