### ISSUE TITLE
shaderName in customShaderNameResolve ignores the shader's name?

### ISSUE THREAD

**Issue by AndrewRayCode** [BabylonJS/Babylon.js#12154]
On this line, shaderName is hard coded to "pbr":

https://github.com/BabylonJS/Babylon.js/blob/master/src/Materials/PBR/pbrBaseMaterial.ts#L1328

Which is then passed to `customShaderNameResolve`:

https://github.com/BabylonJS/Babylon.js/blob/master/src/Materials/PBR/pbrBaseMaterial.ts#L1386

This hard codes a shader's name to "pbr" and ignores the name the user chose when constructing the material.

I'm trying to create a PBRMaterial, scrape the raw GLSL produced by Babylon, hand it off to a compiler to manipulate it, then put it back into the shader, preserving PBRMaterial uniforms/lighting info. In order to do that, someone on the forum pointed me to `customShaderNameResolve` and `options.processFinalCode` inside the callback. To be honest, the lifecycle for this method is unclear as to what it's supposed to do, or what is supposed to be returned. I noticed that `shaderName` passed to the callback is hard coded which confused me when debugging the callback behavior.

**Comment by sebavan** [comment]
See discussion on the forum. As the template mentioned we keep Github for validated issues: https://forum.babylonjs.com/t/how-to-access-raw-shader-information/27240/16
