### ISSUE TITLE
Allow conditional texture fetch in NME

### ISSUE THREAD

**Issue by sebavan** [BabylonJS/Babylon.js#12151]
The current conditional blocks are great for values, but dealing with texture samplers, conditionally using one sampler amongst several would result in several fetches before conditionally picking the result.

The idea would be to add a special block or optim on the current one, to only fetch from the required texture. This could leverage texture source blocks or introduce the support for array of texture in NME.

**Comment by thomlucc** [comment]
Closing as no request. Feel free to re-open
