### ISSUE TITLE
Unicode/emoji characters in Playground are lost upon Save

### ISSUE THREAD

**Issue by ryantrem** [BabylonJS/Babylon.js#12174]
https://forum.babylonjs.com/t/unicode-emoji-in-playground/28458/2

Unicode/emoji characters in the code of the Playground are lost when the Playground is saved. Not sure if it is the same issue, but it also seems not possible to type emoji characters into the Playground (though you can paste them).

**Repro**
- Bug repro on [playground](https://playground.babylonjs.com): N/A (the bug is present as soon as you save the Playground)
- Expected result: Unicode/emoji characters can be saved with the Playground.
- Current result: Unicode/emoji characters after a Save show up as `??`. If they are used in something like a glb URI, then the URI is broken and the model wont' load.

**Screenshots**
![BJS-Playground-Emoji](https://user-images.githubusercontent.com/5084643/158645667-c0a03431-7acb-47ff-9bb6-6ac5fdc259f0.gif)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Edge
 - Version: 99.0.1150.39

**Comment by deltakosh** [comment]
ok this will require us to block the PG database for an hour or so

I'll try to do it during the night here (PST)

**Comment by deltakosh** [comment]
Flagging this to future as for now our SQLServer instance does not let us updating the column from 'text' to 'ntext'. A process of copying data to a new table is possible but was proven too slow (I let it ran for more than 2 hours) while blocking the PG and NME  to save and load snippets
