### ISSUE TITLE
[Event leak] UpdateProfilesList  in particleTextureBlock

### ISSUE THREAD

**Issue by RaananW** [BabylonJS/Babylon.js#12182]
If disposed before the request has ended, the `loadend` event is not being removed when using this function.

See:

https://dev.azure.com/babylonjs/ContinousIntegration/_build/results?buildId=18896&view=logs&j=cfa20e98-6997-523c-4233-f0a7302c929f&t=e990613a-5b65-57a5-9f28-c08f539cef73&l=23

**Comment by deltakosh** [comment]
This one is not a leak (per se). The WebXRMotionControllerManager has a static function (UpdateProfilesList) which is not attached to any scene or engine. The request will clean itself upon resolve (or failure) 

I think we should update that test to ignore this occurence.

**Comment by RaananW** [comment]
Test updated.
