### ISSUE TITLE
Allow arc rotate auto rotation to rotate to a certain alpha value

### ISSUE THREAD

**Issue by RaananW** [BabylonJS/Babylon.js#12204]
Add an optional target alpha value to the auto rotate behavior. The behavior will stop when reaching this beta value.

**Comment by TheCrowd** [comment]
@RaananW  could you clarify this issue with more details and can I work on this issue?

**Comment by RaananW** [comment]
@TheCrowd - Of course! Thank you :-)

The arc rotate camera has an auto-rotate behavior. the auto rotate behavior rotates constantly until stopped (for example by a mouse input like a click or a drag).

This feature should allow setting a target alpha that will act as a goal for the auto-rotate behavior. the auto-rotate will stop rotating when reaching this alpha value.

(Note that I originally wrote beta, which actually needed to be alpha. corrected all over).

**Comment by TheCrowd** [comment]
@RaananW Not sure if I understand this correctly, so the goal is achieved, further input won't trigger any rotate behavior?

**Comment by RaananW** [comment]
no - if you drag and change the alpha, the alpha should be animated back to the predefined alpha. It's quite straightforward - if alpha is not the predefined alpha (within an epsilon), run the auto-rotate algorithm. If it's === defined alpha, don't rotate until user input was provided.

**Comment by TheCrowd** [comment]
@RaananW  Thanks for explaining, I will have a try

**Comment by TheCrowd** [comment]
@RaananW  please have a look at this [PR](https://github.com/BabylonJS/Babylon.js/pull/12429)

**Comment by carolhmj** [comment]
Closed by https://github.com/BabylonJS/Babylon.js/pull/12429
