### ISSUE TITLE
Make sure to log shader compilation error better in validation tests

### ISSUE THREAD

**Issue by RaananW** [BabylonJS/Babylon.js#12244]
If a shader compilation occurs it currently shows the full log but halts and doesn't report the error.

Make sure shader compilation errors are reported and (if possible) add a comment with the failed playground for the dev/reviewer to use.

See https://dev.azure.com/babylonjs/ContinousIntegration/_build/results?buildId=19143&view=logs&j=71a83ec6-a99b-56a2-aed7-297b94c4e57e&t=d751f905-fa52-5e6b-98c6-70fa16fc81f1

**Comment by RaananW** [comment]
Moving to playwright - #12977 - will allow us to get the console output without any issues on both firefox and chromium. THis issue is suspended until migration to playwright is done

**Comment by thomlucc** [comment]
Closing as no request. Feel free to re-open if needed
