### ISSUE TITLE
KTX Textures get lost on GLB Export

### ISSUE THREAD

**Issue by HoferMarkus** [BabylonJS/Babylon.js#12257]
As confirmed from @bghgary in this [forum entry](https://forum.babylonjs.com/t/ktx-textures-get-lost-on-glb-export/28605/6) KTX textures are currently not handled by the GLB exporter.

As a result, the textures of the exported model remain black.
![image](https://user-images.githubusercontent.com/60605717/160061899-2e5587f0-5186-4848-844f-18ac6e5ff205.png)

However the export seems to work if the same textures are provided in an uncompressed format as well (eg: png)
See [playground example](https://playground.babylonjs.com/#PEFFA8#8).

**Repro**
- Bug repro on [playground](https://playground.babylonjs.com/#PEFFA8#19):
- Expected result: Exported GLB is shown correctly with the original textures
- Current result: Exported GLB is all black

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 99.0.4844.82
 ... but this doesn't matter, it happens on any device

**Comment by pandaGaume** [comment]
What it seem so far is that texture file are well exported as png but the original pixel are not extracted from the source.
i guess the problem is located somewhere arround

```
    private _getPixelsFromTexture(babylonTexture: BaseTexture): Promise<Nullable<Uint8Array | Float32Array>> {
        const pixels =
            babylonTexture.textureType === Constants.TEXTURETYPE_UNSIGNED_INT
                ? (babylonTexture.readPixels() as Promise<Uint8Array>)
                : (babylonTexture.readPixels() as Promise<Float32Array>);
        return pixels;
    }
```
which is return an empty buffer (0 filled).
I will investigate.

**Comment by sergeystoma** [comment]
One of the issues is that Babylon tries to read pixels from a compressed texture, but it is not supported in the hardware so it fails. As an alternative, you can render a quad using that compressed texture into a buffer, and read that buffer instead.

For our GLB export, I monkey-patched Babylon's `_readTexturePixelsSync` method with something like this: https://gist.github.com/sergeystoma/1b9bf7fce6e58ef8ae0f6a99a1c5a49f Not the prettiest, but it works 😁

**Comment by bghgary** [comment]
You can also look at this which is what the texture inspector does to read the texture:
https://github.com/BabylonJS/Babylon.js/blob/master/packages/dev/inspector/src/textureHelper.ts

**Comment by bghgary** [comment]
Related: https://forum.babylonjs.com/t/bug-when-exporting-and-importing-back-to-babylon/33482

**Comment by thomlucc** [comment]
https://forum.babylonjs.com/t/add-support-ktx-textures-in-glb-exporter/52144

**Comment by Jeggery** [comment]
> You can also look at this which is what the texture inspector does to read the texture: https://github.com/BabylonJS/Babylon.js/blob/master/packages/dev/inspector/src/textureHelper.ts

In other words, if KTX texture is converted to png when exporting glb, simply call    GetTextureDataAsync ?

**Comment by Popov72** [comment]
It won't work, you will only get the transcoded data for your GPU, you won't get the full original KTX data.

**Comment by Jeggery** [comment]
> It won't work, you will only get the transcoded data for your GPU, you won't get the full original KTX data.

Okay, is the saved data after GPU transcoding PNG images? If the data is not lost, it is also acceptable
