### ISSUE TITLE
HDRFiltering class options don't work

### ISSUE THREAD

**Issue by MiikaH** [BabylonJS/Babylon.js#12258]
While looking at the source code I noticed that HDRFiltering() class options implementation has a bug that effectively breaks both options:

https://github.com/BabylonJS/Babylon.js/blob/dc6059e986b99fda20fac7b10691485744e84b87/packages/dev/core/src/Materials/Textures/Filtering/hdrFiltering.ts#L62

As you can see in the code above, `quality` option is actually set from `hdrScale` option if present. Therefore:

- `quality` option itself doesn't do anything
- Using `hdrScale` breaks whole filtering as it replaces quality with too low sample count

**Comment by sebavan** [comment]
I am on it

**Comment by sebavan** [comment]
Thanks a lot for reporting it btw :-)
