### ISSUE TITLE
Babylon.js 5.0.0-rc.12 fails with React Scripts and Webpack

### ISSUE THREAD

**Issue by mrlika** [BabylonJS/Babylon.js#12278]
This [commit](https://github.com/BabylonJS/Babylon.js/commit/ab2ede8d43b0c4891c9a5f21408fe62e67e6e5a7) added `"type": "module"` to `@babylonjs/*/package.json` files and they are not building any more with our rather standard `React Scripts` application with the following error:

```
Module not found: Error: Can't resolve './abstractScene' in '/home/runner/work/service-kepler-worker/service-kepler-worker/app/node_modules/@babylonjs/core'
Did you mean 'abstractScene.js'?
BREAKING CHANGE: The request './abstractScene' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains `"type": "module"`).
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.
```

The reason is how `Webpack` treats `"type": "module"`: https://webpack.js.org/configuration/module/#resolvefullyspecified

Removing `"type": "module"` from `@babylonjs/*/package.json` files directly in `node_modules` folder fixed the issue for me.

**Comment by RaananW** [comment]
We are usually discussing those kinds of issues in our forum, and not in github (as per the issue template you read when creating this issue :-)).

This won't be a long discussion (again - forum would be better for an open discussion). type: "module" was already available in earlier versions (and was removed temporarily between rc.5 and rc.11). I am checking now if something else changed in package.json.

**Comment by RaananW** [comment]
This is because of a different issue. I will release rc.13 with a fix very soon.

**Comment by RaananW** [comment]
rc.13 was released.
