### ISSUE TITLE
Use NPM and tsc get error " Cannot find name 'MouseWheelEvent' ".

### ISSUE THREAD

**Issue by tidus2020** [BabylonJS/Babylon.js#12293]
I just use npm i babylonjs, and run the tsc build , but get this error in the  node_modules/babylonjs/babylon.module.d.ts

**Comment by sebavan** [comment]
It looks like might not be using an up to date version of typescript.

You should come come discuss it on the forum https://forum.babylonjs.com/ as we keep github for validated issue only.
