### ISSUE TITLE
Make sure our tools have basic accessibility tags

### ISSUE THREAD

**Issue by RaananW** [BabylonJS/Babylon.js#12294]
We should run a pass at our tools and the code generating our templates and make sure we have the required accessibility tags added (like alt tags to images, labels for form elements etc')

This is a future task and is set as a reminder for a future release.

- [ ] Sandbox
- [ ] Playground

**Comment by RaananW** [comment]
@carolhmj - I assigned you, let's talk about it when you have the time.

**Comment by thomlucc** [comment]
https://forum.babylonjs.com/t/make-sure-our-tools-have-basic-accessibility-tags/52749
