### ISSUE TITLE
[NME] ctrl + drag around nodes in a frame will only select the frame

### ISSUE THREAD

**Issue by PatrickRyanMS** [BabylonJS/Babylon.js#12317]
**Repro**
- Bug repro on [NME snippet](https://nme.babylonjs.com/#WBESAX):
- hold ctrl + left click + drag a marquee around nodes within frame. Make sure to start marquee within frame and try to select all nodes
- Expected result: We would not select frame on this marquee selection, but only the nodes. We should be able to select only nodes or only frames with ctrl + click or marquee select, and we should give preference to nodes instead of frames. So if the selection mixes both nodes and frames, only the nodes should be selected. Right now we have the reverse and only one frame at a time may be selected. There are use cases for wanting to move frames together so the user should be able to multi-select frames, but only if the user only selects/marquees frames with no nodes in the mix.
- Current result: the marquee will start selecting nodes in most cases, but the selection will switch to the frame and deselect any nodes that were selected and select no more nodes. 

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Edge
 - Version:  99.0.1150.46

**Additional context**

**Comment by carolhmj** [comment]
Closed by https://github.com/BabylonJS/Babylon.js/pull/12327
