### ISSUE TITLE
Push previous versions to our CDN

### ISSUE THREAD

**Issue by RaananW** [BabylonJS/Babylon.js#12335]
The cdn should serve "latest" and previous versions with the following schema:

https://cdn.babylonjs.com/packageName/version/packageName[.min].js

Where package name can be one of the following:

core, loaders, materials, serializers, post-processes, procedural-textures, inspector, gui-editor, node-editor, viewer

Version is the npm version, including "preview" and "latest"

Preview CDN should stay the same

**Comment by dshumakerUT** [comment]
Is this to allow for easier rollbacks?  I have not deployed to production in seven months on a site that uses babylon cdn  (so I know nothing has changed on our end) and now I'm getting this error in the console

```
Uncaught TypeError: Cannot read properties of undefined (reading 'RegisteredTypes')
    at Module.t.exports (babylon.gui.min.js:16:38735)
    at r (babylon.gui.min.js:1:508)
    at Module.<anonymous> (babylon.gui.min.js:16:264807)
    at Module.t.exports (babylon.gui.min.js:16:268227)
    at r (babylon.gui.min.js:1:508)
    at t.exports (babylon.gui.min.js:1:1307)
    at Object.<anonymous> (babylon.gui.min.js:1:400)
    at Object.<anonymous> (main.js:16:268198)
    at r (bootstrap:19:22)
    at Object.<anonymous> (SectionBoxFactory.ts:2:1)
```

The first thing I'lll do is look into how to roll back to an older version???  Thank you for any suggestions.

I'm using it like this

 ```
 <script crossorigin src="https://unpkg.com/react@16/umd/react.development.js"></script>
  <script crossorigin src="https://unpkg.com/react-dom@16/umd/react-dom.development.js"></script>
  <script crossorigin src=" https://cdn.babylonjs.com/babylon.js"></script>
  <script crossorigin src="https://cdn.babylonjs.com/gui/babylon.gui.min.js"></script>
 
```

**Comment by RaananW** [comment]
This shouldn't happen (and is not related to this issue). I will be happy to help you with that (and investigate with you. Let's continue the conversation in our forum, as we use github mainly to track issues.

**Comment by RaananW** [comment]
Future versions will now be pushed to the cdn under `/v${VersionNumber}`. past versions will soon be uploaded.

**Comment by thomlucc** [comment]
Closing as 4.2 and above are covered
