### ISSUE TITLE
32 bit Ktx2 textures are flipped vertically on ios

### ISSUE THREAD

**Issue by Chargeuk** [BabylonJS/Babylon.js#12349]
This is a bug report requested by @bghgary on the babylon.js Bugs forum here: https://forum.babylonjs.com/t/ktx2-flipped-vertically-on-ios/29079

ktx2 textures created from a 32 bit png are flipped in the vertical axis when rendered on iOS compared to other platforms.

**Repro**
- Bug repro on [playground](https://playground.babylonjs.com/#Q9VZS9#814):
- Expected result: iOS renders the polygon with the green part of the texture at the top and the red part at the bottom
- Current result: iOS renders the polygon with the red part of the texture at the top and the green part at the bottom

**Smartphone (please complete the following information):**
 - Device: iPhones & iPads
 - OS: iOS 15.3.1 (although probably other iOS devices too)
 - Browser: iOS Safari

**Additional context**
Texture files used in the playground to reproduce the issue are available from the first post of the bug forum thread: https://forum.babylonjs.com/t/ktx2-flipped-vertically-on-ios/29079

**Comment by sebavan** [comment]
I can not repro on ios 15.4.1 I wonder if this could be part of a Safari bug fix. @bghgary could you confirm ?

**Comment by bghgary** [comment]
I can repro with iOS 15.2.1.

**Comment by sebavan** [comment]
I wonder if you should try to upgrade ? or if we could double check which version @CedricGuillemet is having ?

**Comment by bghgary** [comment]
That will be helpful. We can try to see if it's an OS issue.

**Comment by CedricGuillemet** [comment]
ios 15.3.1 here and I can repro

**Comment by bghgary** [comment]
I've tracked this down a bit. The problem is actually decoding to raw RGBA. Somehow, if we end up on this path, then the texture is flipped.

Repro with this PG that turns off all the compressed formats which will use the RGBA path: https://playground.babylonjs.com/#Q9VZS9#827

**Comment by bghgary** [comment]
It doesn't work before 15.4 because 15.4 reintroduced compressed formats that KTX can target. Before that, it was going down the RGBA path.

**Comment by Popov72** [comment]
The problem is the `invertY` parameter of the `Texture` constructor, which is `true` by default: when using a compressed texture it can't be honored because compressed textures can't be Y inverted, but when falling back to a regular RGBA texture it can be honored. I guess the decompression code should always force `invertY=false`?

**Comment by Popov72** [comment]
So, I think `internalTexture.invertY = false;` should be added around:

https://github.com/BabylonJS/Babylon.js/blob/master/packages/dev/core/src/Misc/khronosTextureContainer2.ts#L253-L255

**Comment by bghgary** [comment]
Yeah, I've been looking at invertY, but haven't figured out exactly what is happening yet.
