### ISSUE TITLE
_internalMeshDataInfo not being cleared during skeleton change

### ISSUE THREAD

**Issue by mrlooi** [BabylonJS/Babylon.js#12364]
Forum link: https://forum.babylonjs.com/t/computebonesusingshaders-on-off-on-is-causing-a-major-bug/29162/14

**Repro**
- Bug repro on [playground](https://playground.babylonjs.com/#SYQW69#1030):

@deltakosh

**Comment by mrlooi** [comment]
From Blake 
"I think in the Mesh class’s computeBonesUsingShaders setter function, when it’s set to false the cache should be reset too. That way after turning it on and then off again, you could afterwards change the vertex positions and normals, and then turn it on and off again and it would reset to your new values. Otherwise they’ll be overwritten without resetting the cache so that the new values can be cached and reset to…"

**Comment by BlakeOne** [comment]
Sorry, I meant to say when setting it to true the setter should reset the cache (not when setting to false).

**Comment by deltakosh** [comment]
@BlakeOne interested to do the PR?

**Comment by goarblt** [comment]
https://www.evil.com
