### ISSUE TITLE
Precision issues when using large values 

### ISSUE THREAD

**Issue by bghgary** [BabylonJS/Babylon.js#12379]
See thread: https://github.com/petrbroz/forge-convert-utils/issues/47

**Repro**
- Bug repro on with model in sandbox: https://github.com/petrbroz/forge-convert-utils/files/8245413/Test_View_ifc_and_glb.zip
- Expected result: See comment: https://github.com/petrbroz/forge-convert-utils/issues/47#issuecomment-1066829730
- Current result: See comment: https://github.com/petrbroz/forge-convert-utils/issues/47#issuecomment-1066829730

**Screenshots**
See comment: https://github.com/petrbroz/forge-convert-utils/issues/47#issuecomment-1066829730

**Comment by deltakosh** [comment]
Replied directly: https://github.com/petrbroz/forge-convert-utils/issues/47#issuecomment-1096957348
