### ISSUE TITLE
Update to glTF-Validator 2.0.0-dev.3.10

### ISSUE THREAD

**Issue by bghgary** [BabylonJS/Babylon.js#12380]
See https://github.com/KhronosGroup/glTF-Validator/pull/179.

EDIT: https://github.com/KhronosGroup/glTF-Validator/releases/tag/2.0.0-dev.3.7

**Comment by bghgary** [comment]
Currently, I do this by hand. I wonder if we can incorporate this into the build system somehow?

**Comment by bghgary** [comment]
I just do the following against the npm package:
```
browserify index.js -o gltf_validator.js
```
where index.js is:
```
GLTFValidator = require('gltf-validator');
```

**Comment by RaananW** [comment]
@bghgary - of course, it seems like something we can do as part of the build process. Should this run on every publish?

**Comment by bghgary** [comment]
It doesn't change that often, so I think no, but it also doesn't take long, so it will fine if we do it every time. What's a good place to do this?

**Comment by bghgary** [comment]
https://github.com/KhronosGroup/glTF-Validator/pull/220

**Comment by thomlucc** [comment]
https://forum.babylonjs.com/t/update-to-gltf-validator-2-0-0-dev-3-10/52750
