### ISSUE TITLE
Spatial sound not working on iOS 14.3, chrome or safari

### ISSUE THREAD

**Issue by kangshiyin** [BabylonJS/Babylon.js#12381]
Spatial sound not working on iOS 14.3, chrome or safari. `attachToMesh`, `spatialSound: true` or any setup enabling spatial sound does not work on iOS, while same code works on chrome@windows PC, chrome@macbook pro and firefox@android. 

Disabling spatial sound makes the project work, but that's not what I want.

Not sure who to blame, babylon.js, web audio api, or apple....

Is there a fix?

Thanks!!

**Use Github issues ONLY for validated bugs. PLEASE DISCUSS THEM ON THE FORUM FIRST!**

A forum discussion started 2 years ago, but seems none has discovered its connection to spatial sound before.
https://forum.babylonjs.com/t/sound-issues-on-ios/8067

**Repro**
- Bug repro on [playground](https://playground.babylonjs.com):
Unchanged demo code from Babylon.js document:
https://playground.babylonjs.com/#EDVU95

- Expected result:
Works on MacOS Chrome, PC, Android phone with firefox browser

- Current result:
iPhone 11 pro, iOS 14.3, neither Safari or Chrome works.

**Smartphone (please complete the following information):**
 iPhone 11 Pro
 
 iOS 14.3
 
 safari or chrome

**Comment by kangshiyin** [comment]
No problem on an Android phone with firefox.

**Comment by kangshiyin** [comment]
A spatial sound demo with web audio api works on iPhone, suggesting that the bug is in Babylon? Not sure if these two demos are referring to the same underlying code. 

https://webaudioapi.com/samples/spatialized/

**Comment by kangshiyin** [comment]
Another spatial sound demo with web audio api.
The music plays on iPhone, but the position of the boombox can not be moved with unknown reason. 

doc:
https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API/Web_audio_spatialization_basics

live demo:
https://mdn.github.io/webaudio-examples/spacialization/

**Comment by kangshiyin** [comment]
Repro this bug on MacBook Pro 2013 MacOS Mojave 10.14.3 Safari 12.0.3 with the demo code in the babylon document.

https://playground.babylonjs.com/#EDVU95

also reproducible on Safari 12 macOS Mojave simulator at https://www.lambdatest.com/

Commenting out line 35 make it work.
```
    // music.attachToMesh(box);
```

**Comment by sebavan** [comment]
This seems to be all good on https://playground.babylonjs.com/#EDVU95#39 (I moved the effect to the extreme) Can you confirm it is good for you ?

Tested chrome and safari Macos 12.3.1 and on iphone 13 ios 15.4.1

**Comment by kangshiyin** [comment]
Thanks, I found that my safari was too old to support `PannerNode` in web audio api , required by babylon spatial audio.
https://developer.mozilla.org/en-US/docs/Web/API/PannerNode#browser_compatibility
Tried newer versions and they are all good.
