### ISSUE TITLE
Animation is not playing in Babylonjs Version 5.2.0.

### ISSUE THREAD

**Issue by neildeora** [BabylonJS/Babylon.js#12398]
Animation is not working when rigging(Clone) animation from one glb model to another glb model in babylonjs latest version 5.2.0, Where as it is working in older versions (<4.0)

here is the playground Url
https://playground.babylonjs.com/#XJTDLU#111

When we switch to v5.2.0 animation will not work where as in the v4.2.0 it will work please help me with this issue
![image](https://user-images.githubusercontent.com/100671221/163392192-a4fcdad9-7e0c-4946-ab3d-092e64e9eeae.png)

**Comment by deltakosh** [comment]
Please use forum.babylonjs.com for questions (this is stated in the issue template...)
