### ISSUE TITLE
DebugLayer : Accessors onNodeSelectedObservable

### ISSUE THREAD

**Issue by dad72** [BabylonJS/Babylon.js#12394]
Hello,

Would it be possible to have an observable when we select a node in the inspector? Like onNodeSelectedObservable().
I would have liked when we select a node, that the camera moves in front of the selected object of the scene.
Or else maybe integrate this directly into the inspector next to the little eye would be even better I guess.

Thanks in advance.

**Discussion**
[[feature request] DebugLayer : Accessors onNodeSelectedObservable](https://forum.babylonjs.com/t/feature-request-debuglayer-accessors-onnodeselectedobservable/29329?u=dad72)

**Comment by deltakosh** [comment]
Done!

observable name is `onSelectionChangedObservable`

**Comment by dad72** [comment]
Thank you. It works.
