### ISSUE TITLE
Why doesn't babylonjs use (Rendering Relative to Eye) to solve the loss of precision?

### ISSUE THREAD

**Issue by GoodLuckIce** [BabylonJS/Babylon.js#12412]
https://forum.babylonjs.com/t/why-doesnt-babylonjs-use-rendering-relative-to-eye-to-solve-the-loss-of-precision/29532?u=luck_good

Why doesn't babylonjs use (Rendering Relative to Eye) to solve the loss of precision?

**Comment by deltakosh** [comment]
Please do not use Github for questions as stated in the issue template
