### ISSUE TITLE
*DOCS* IndexDB cacheing docs imply the feature is limited to 93MB - its not

### ISSUE THREAD

**Issue by ptallettms** [BabylonJS/Babylon.js#12438]
The docs here https://doc.babylonjs.com/divingDeeper/scene/optimizeCached

state at the bottom:

> One of the scenes is configured to only cache the texture. It’s the “[The Car](https://www.babylonjs.com/demos/thecar/)” scene. It’s because the JSON file, TheCar.babylon, is more than 93 MB. IE11 and Chrome can’t store a big file like that into their DB, so decision was made to avoid trying to cache it.

implying models larger than 93MB can't be cached on chrome using this feature. Searching the web to find Chrome limits led me to believe this was true.

That info is either wrong or just really out of date. This works fine with a 250MB GLB.

I am reporting this because it led me to implement my own (inferior) caching when I could just have used this great BABYLON feature.

**Comment by RaananW** [comment]
We accept PRs :-) the documentation repository is `https://github.com/BabylonJS/Documentation`. you can also create an issue there.
