### ISSUE TITLE
KHR_materials_iridescence incompatible with KHR_texture_transform

### ISSUE THREAD

**Issue by zeux** [BabylonJS/Babylon.js#12431]
Using Babylon.JS sandbox, you can try to open two .glb files that use KHR_materials_iridescence (https://github.com/KhronosGroup/glTF/pull/2027). They are ~identical except that one is using KHR_mesh_quantization + KHR_texture_transform, and one isn't:

[ir.zip](https://github.com/BabylonJS/Babylon.js/files/8548676/ir.zip)

Opening ir_noq.glb in sandbox correctly generates the expected screenshot:

![image](https://user-images.githubusercontent.com/1106629/164947245-77761691-4d55-47b7-a404-244536fb8d74.png)

Opening ir_q.glb in sandbox fails with the following shader compilation error:

```
logger.ts:140 BJS - [14:57:03]: Offending line [337] in vertex code: vIridescenceThicknessUV=vec2(iridescenceThicknessMatrix*vec4(uvUpdated,1.0,0.0));
logger.ts:140 BJS - [14:57:03]: Error: VERTEX SHADER ERROR: 0:337: 'vIridescenceThicknessUV' : undeclared identifier
```

Both files were generated by gltfpack using the IridescenceSuzanne model from glTF-Sample-Models as an input (with https://github.com/zeux/meshoptimizer/pull/423).

**Comment by sebavan** [comment]
Thanks for reporting, will fix it asap
