### ISSUE TITLE
[Snippet Server] document the snippet server's API so others can implement a local copy

### ISSUE THREAD

**Issue by RaananW** [BabylonJS/Babylon.js#12449]
Our snippet server is not open source so we can't share its code. What we can do is offer a full API documentation so that others will be able to implement their own snippet server and use it locally, for example when running their own version of the playground.

Optionally - create a reference project that shows a simple snippet server (local-storage-based) that can be served locally.

**Comment by Sumantsahu9888** [comment]
We should offer a very simple getting-started template for an npm-ready project that can be initialized using npm init.

**Comment by RaananW** [comment]
@carolhmj - can we close this? want to add a few links here for future reference?

**Comment by carolhmj** [comment]
Yep we can I hadn't seen the docs PR was merged! For future reference here's the page link on the docs, linking to a reference implementation! https://doc.babylonjs.com/toolsAndResources/tools/playground/yourOwnSnippetServer
