### ISSUE TITLE
Creating depth/stencil texture does not support MSAA in WebGL.

### ISSUE THREAD

**Issue by Popov72** [BabylonJS/Babylon.js#12444]
Try this PG: https://playground.babylonjs.com/#A56TVT#1

Look at the console log: there are some errors because the depth/stencil texture is not created as a MSAA texture.

Note that it is failing only in WebGL, it's ok in WebGPU.

**Comment by sebavan** [comment]
I am pretty sure it has never been supported in our webgl support. Trying to look into what it would take to do so. Do you see it as a regression ? or I would move the issue to a feature request instead ?

**Comment by Popov72** [comment]
I think it can be moved in feature request indeed as it was never supported in WebGL (I looked at the file history of `engine.renderTarget.ts` to be sure it was not a regression I could have introduced!).

**Comment by sebavan** [comment]
Just wondering when do you need this feature by ?

**Comment by Popov72** [comment]
It's not very important, I'm simply not enabling MSAA in my (upcoming) demo.

**Comment by sebavan** [comment]
Not supported by webgl
