### ISSUE TITLE
Does babylonjs repo have a Copyright or NOTICE.md file?

### ISSUE THREAD

**Issue by eherozhao** [BabylonJS/Babylon.js#12447]
We only accept feature requests that are discussed on the BabylonJS forum

**Is your feature request related to a problem? Please describe.**
Under Apache 2.0 license, https://infra.apache.org/licensing-howto.html Notice.md is another required file except License.md.

**Describe the solution you'd like**
Pushed the NOTICE file with the copyright permission.

**Comment by RaananW** [comment]
That's a good question (that should be asked in the forum). The quick answer is - we do not bundle anything that needs to be in the NOTICE file. The only dependencies we bundle as part of our distribution is React (MIT), React DOM (MIT), and tslib (bsd no atrib), which don't require any changes to the notice file. So, the short answer is - i'll add a notice file, but it will have two lines in it:

```markdown
Babylon.js
Copyright 2022 The Babylon.js team
```

If you want to continue the conversation, I will be happy to continue in the forum (as suggested by the first line in the issue you submitted 😉)
