### ISSUE TITLE
animation - goToFrame is not worked at first

### ISSUE THREAD

**Issue by slash9494** [BabylonJS/Babylon.js#12451]
**Use Github issues ONLY for validated bugs. PLEASE DISCUSS THEM ON THE FORUM FIRST!**

We have a really active forum to help answering questions (https://forum.babylonjs.com/)

## I posted about it on forum and let me share link
https://forum.babylonjs.com/t/issue-animation-gotoframe/29493/5

**Repro**
- Bug repro on [playground](https://playground.babylonjs.com):
https://sandbox.babylonjs.com/?assetUrl=https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Models/master/2.0/AnimatedMorphSphere/glTF/AnimatedMorphSphere.gltf
- Expected result: 
- Current result:

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by CedricGuillemet** [comment]
Fixed with https://github.com/BabylonJS/Babylon.js/pull/12465 . closing.
