### ISSUE TITLE
Uncaught (in promise) TypeError: scene.stopAllAnimations is not a function

### ISSUE THREAD

**Issue by alamboley** [BabylonJS/Babylon.js#12457]
Seems closed to https://github.com/BabylonJS/Babylon.js/issues/6206. Calling `this._scene.stopAllAnimations();` using es6 modules bring this error.

**Comment by RaananW** [comment]
You need to check the tree shaking documentation on our docs. You are missing an import (`/Animations/animatable`).

If you want to discuss this further please use the forum.

**Comment by RaananW** [comment]
`import "@babylonjs/core/Animations/animatable";`

Let's keep discussions in the forum in the future :-)
