### ISSUE TITLE
Add boolean to fire PointerMove events on 3D GUI elements every frame

### ISSUE THREAD

**Issue by darraghjburke** [BabylonJS/Babylon.js#12471]
We have a boolean for 2D GUIs which causes a PointerMove event to be triggered every frame. The value in this is that if the camera rotates such that the GUI control under the pointer changes, the GUI will correctly respond to that. (For example, a button that changes color when its under the pointer will now correctly change color even if no pointer event is fired from the hardware pointer device.)

We should add this flag to 3D GUI as well. Here is a playground showing how this can be implemented: https://playground.babylonjs.com/#HJZBRG#245

Notice how the buttons will highlight and unhighlight as the pointer travels over them if you rotate the camera with the arrow keys, even when you're not moving your mouse. We should turn this into a part of the API rather than just a hacky workaround.

**Comment by thomlucc** [comment]
Closing as no request/reaction for it. Feel free to re-open if needed
