### ISSUE TITLE
Sprite add metadata field

### ISSUE THREAD

**Issue by Jeggery** [BabylonJS/Babylon.js#12492]
It is recommended that sprite add metadata to keep consistent with mesh, so that users can customize data to write logic

**Comment by deltakosh** [comment]
Hello, please use the forum as it is clearly stated in the issue template

**Comment by Sumantsahu9888** [comment]
Add a setting on controls that will generate a tooltip on hover.

**Comment by Sumantsahu9888** [comment]
We should offer a very simple getting-started template for an npm-ready
project that can be initialized using npm init.

**Comment by Jeggery** [comment]
> metadata

In fact, the official sprite should add the metadata field. I don't know why the official didn't add it

**Comment by deltakosh** [comment]
> In fact, the official sprite should add the metadata field

It is ok to do a PR if you want to add one ;)
