### ISSUE TITLE
NME Generate code has error on ColorMergerBlock

### ISSUE THREAD

**Issue by jixiangcn** [BabylonJS/Babylon.js#12491]
**Repro**
- Current result:
...
// ColorMergerBlock
var ColorMerger = new BABYLON.ColorMergerBlock("ColorMerger");
ColorMerger.visibleInInspector = false;
ColorMerger.visibleOnFrame = false;
ColorMerger.target = 4;
ColorMerger.rSwizzle = r};
ColorMerger.gSwizzle = g};
ColorMerger.bSwizzle = b};
ColorMerger.aSwizzle = a};
...

**Comment by deltakosh** [comment]
Thanks I will fix it asap!
