### ISSUE TITLE
Make invertY flag more consistent across different texture loading scenarios

### ISSUE THREAD

**Issue by bghgary** [BabylonJS/Babylon.js#12545]
Babylon.js supports loading uncompressed images (e.g., from a PNG or JPG) and compressed images (e.g., from a DDS, Basis, KTX1, KTX2).

For uncompressed images, WebGL can store the pixels inverted on the GPU using [this code](https://github.com/BabylonJS/Babylon.js/blob/6283aefd505d994bd6262335dfd2076a615f8e29/packages/dev/core/src/Engines/thinEngine.ts#L4319).

```javascript
this._gl.pixelStorei(this._gl.UNPACK_FLIP_Y_WEBGL, value ? 1 : 0);
```

This [pixelStorei](https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/pixelStorei) function only affects `texImage2D` and thus has no effect on compressed images.

When creating a `Texture` object, there is a flag [`invertY`](https://github.com/BabylonJS/Babylon.js/blob/master/packages/dev/core/src/Materials/Textures/texture.ts#L372) that determines whether the code above is executed or not.

Currently, some of the texture loaders (e.g., Basis and KTX1) will try to respect this `invertY` by setting an `_invertVScale` property which will eventually [update the `texture.vScale` and `texture.vOffset` properties](https://github.com/BabylonJS/Babylon.js/blob/master/packages/dev/core/src/Materials/Textures/texture.ts#L433-L436).

```javascript
if (this._texture._invertVScale) {
    this.vScale *= -1;
    this.vOffset += 1;
}
```

This is a bad for a couple of reasons:
1. Using texture transform to flip the texture doesn't work for postprocesses.
2. We are mucking with properties that could have been set by the user. If the user of the `vScale` or `vOffset` property is going to compute something using them (e.g., animate them), they will be different once the texture is loaded.

Both DDS and KTX2 loaders do not respect this `invertY` flag and will load images with different orientation depending on if the resulting data is compressed or not compressed.

The proposal is to make this more consistent.
1. Any image that is loaded, whether compressed or not, should load with the same orientation and should match the orientation of loading an uncompressed image (e.g., png or jpg).
2. The `invertY` flag should be ignored when attempting to load a compressed texture. This includes loading a KTX1 texture using the [texture selector](https://github.com/BabylonJS/Babylon.js/blob/master/packages/dev/core/src/Engines/Extensions/engine.textureSelector.ts) or loading a compressed texture directly with DDS, Basis, KTX1, or KTX2. Doing this will ensure compressed textures work consistently across different features since there is no way to update the pixel storage for compressed textures.

Whoever does this work should make sure WebGPU works as well and add tests to ensure textures are consistent when loaded using various loaders with and without compression.

**Comment by ryantrem** [comment]
For more background, see these forum posts:
- https://forum.babylonjs.com/t/ktx2-flipped-vertically-on-ios/29079
- https://forum.babylonjs.com/t/ktx2-texture-flipped-vertically-on-ios/49091

**Comment by ryantrem** [comment]
And here is a Playground (mostly the same as one mentioned in one of the posts above) with a simple example loading a ktx2: https://playground.babylonjs.com/#Q9VZS9#1964

**Comment by thomlucc** [comment]
https://forum.babylonjs.com/t/make-inverty-flag-more-consistent-across-different-texture-loading-scenarios/52751
