### ISSUE TITLE
NME custom Attributes

### ISSUE THREAD

**Issue by sebavan** [BabylonJS/Babylon.js#12549]
It would be great to have the possibility to use custom attributes through the NME editor.

It is currently possible by code in the NodeMaterial input block but not through the editor.

https://forum.babylonjs.com/t/how-to-make-nme-material-for-thin-instances-with-color-attribute/30469/6?u=sebavan

**Comment by carolhmj** [comment]
@sebavan @PatrickRyanMS for this, would changing the Attribute line on the NME from Options to a Text Input suffice? 
![image](https://user-images.githubusercontent.com/6002144/171061407-c1a7e59e-09e7-4a8b-a132-b692eb759906.png)

**Comment by sebavan** [comment]
Almost :-) It would also require a new mode being Custom Attribute and only in this mode having a text input.

**Comment by PatrickRyanMS** [comment]
How would the custom attribute get used in NME? And how do we preview it? For shaders that deal with things like vertex color, we need to load in a preview model with vertex color. But how are we handling custom attributes?

**Comment by carolhmj** [comment]
I think we don't need to preview custom attributes, as we won't know what they are beforehand.

**Comment by philharlow** [comment]
In case this helps anyone, I found a workaround for my situation using:
```
const selectedBlock = nodeMaterial.getBlockByName("selected");
if (selectedBlock instanceof BABYLON.InputBlock) {
  selectedBlock.setAsAttribute("selected");
  nodeMaterial.build();
}
```

**Comment by carolhmj** [comment]
> Especially if it's a parameter for something like a thin instance where the meshes rendered in the preview window are not thin instances.

You have a good point on this, maybe we should at least add an option on the drop down to render a few instances/thin instances so the user could preview shaders that vary per instance 🤔

**Comment by deltakosh** [comment]
Closing for now as there is a way to do it by code and doing it in NME does not provide additional benefit
