### ISSUE TITLE
Problems loading .obj with groups.

### ISSUE THREAD

**Issue by prominentdetail** [BabylonJS/Babylon.js#12542]
I have a user reporting a problem with their ability to import .obj file to babylon.js
https://steamcommunity.com/app/1244040/discussions/0/3280321332558564130/

I believe this is a bug in babylon.js

If you check the obj specifications: http://paulbourke.net/dataformats/obj/

> usemtl material_name
> 
>     Specifies the material name for the element following it. Once a
>     material is assigned, it cannot be turned off; it can only be
>     changed.

So my understanding is that it shouldn't have to respecify the material to use for each group if it is already specified.

Here are test files to confirm the bug:
[babylonGroups.zip](https://github.com/BabylonJS/Babylon.js/files/8717034/babylonGroups.zip)

If you drag the files into the babylon.js sandbox, you can see that one of the groups does not have the material set:
https://sandbox.babylonjs.com/

In comparison, other programs load everything just fine because they can parse the data correctly.

**Comment by deltakosh** [comment]
Hello! as mentioned in the GIthub issue template please open the discussion in the forum first :)

**Comment by sebavan** [comment]
On it :-)
