### ISSUE TITLE
IDE performance problems when importing Babylon

### ISSUE THREAD

**Issue by lostfictions** [BabylonJS/Babylon.js#12568]
Hi there, I'm evaluating Babylon for use in a project, but after importing it (via `import { Scene } from "babylonjs";`) I started noticing performance issues in my IDE, VS Code. Autocomplete, go-to-definition and peek definition got noticeably sluggish, even after a restart. 

I often use VS Code's peek and go-to-definition functionality to get more context on the code I'm working with and learn more about API type relationships. Unfortunately, peeking definitions on Babylon classes doesn't work very well: for example, trying to peek Babylon's `Mesh` class surfaces seven different definitions (after a noticeable delay):

![Screenshot from 2022-05-24 03-27-54](https://user-images.githubusercontent.com/567041/169981324-766a67de-4ebd-46c9-b377-feb0cf5d4c0b.png)

What's more, peeking Babylon defs causes VS Code to emit a warning every time:

![Screenshot from 2022-05-24 03-27-23](https://user-images.githubusercontent.com/567041/169981680-bb98a8a0-243e-4042-b292-9b4bf24f853a.png)

It didn't take long to discover the culprit -- the typings file weighs in at a whopping 200,000 lines:

![Screenshot from 2022-05-24 03-27-41](https://user-images.githubusercontent.com/567041/169980890-01189e3e-698a-48c6-897d-4bd50f54c7d2.png)

This seems pretty wild to me -- TypeScript's own `lib.dom.d.ts`, which comprises type definitions for the vast majority of browser APIs and includes full JSDoc documentation for them, comes in at _less than one-tenth that size_ -- it seems unlikely that Babylon is larger than that, even if the declarations were somehow accidentally duplicated several times within the .d.ts file.

Is it possible that something broke with Babylon's build process? I see from #10025 that Babylon currently has an idiosyncratic build system that prevents modern optimizations like tree-shaking, but this definition file size seems obviously wrong -- and the issues it causes extend beyond optimization, making it more difficult to learn Babylon or write code that uses it.  Babylon also augments or redefines many globals (`CanvasRenderingContext2D` was the first I noticed), causing tooling to slow down for them too.

BabylonJS version: 5.7.0

**Comment by deltakosh** [comment]
Hello as stated in the issue template, please use the forum for questions: forum.babylonjs.com

Issue template for the record:
<img width="1065" alt="image" src="https://user-images.githubusercontent.com/1306056/170072593-73660025-383a-4c81-8dad-d142725fef02.png">
