### ISSUE TITLE
Audio Engine V2

### ISSUE THREAD

**Issue by thomlucc** [BabylonJS/Babylon.js#12576]
Same as IndexedDB, we need to modernize and solidify our WebAudio support

The [Audio Engine](https://doc.babylonjs.com/divingDeeper/audio/playingSoundsMusic) is due for a refresh. 

- [ ] Tech investigation, in particular:
- Clean code
- Add support for async / promises
- Allow the user to control the graph
- [ ] [More milestones to be defined with tech investigation]

### Design Goals
- [ ] Competitive analysis
  - Compare audio capabilities from other industry solutions (Unity, Unreal, Playcanvas)
  - Revisit Audio Editor design from FHL (Jason Syltebo)
  - Create user flows for audio use in Babylon
 - [ ] User Interface
   - Determine where UI of audio lives (inspector only, VSM, new interface)
   - Determine what new components may be needed for UI beyond shared components
   - Design for UI as needed

**Comment by RaananW** [comment]
This should include #11590.

Closing the other issue.

**Comment by dad72** [comment]
Hi,

I was wondering, if I can suggest an idea for the Audio engine v2, to add the possibility of recording live sound spatialized when speaking into a microphone.

Basically, I would like to create a voice chat with spatial sound. But currently the engine just allows you to play audio files, not to save them.

Hope you find this might be a good idea.

Here is an example of a chat with spatial sounds in video of what I would like to achieve with the new generation Audio engine (which Babylon should absolutely have) It would be great to have this for Babylon in a way to be able to create games like MMO, Metaverse... 

https://f.hubspotusercontent40.net/hubfs/5066246/2021%20Website/Videos/SpatialAudioDemo-Spatialized.mp4

**Comment by dad72** [comment]
Hi,

I was wondering where the progress of the audio engine V2 was ? 
If there was any idea of ​​when this might be available/planned ?

Thanks

**Comment by docEdub** [comment]
> Hi,
> 
> I was wondering where the progress of the audio engine V2 was ? If there was any idea of ​​when this might be available/planned ?
> 
> Thanks

We're hoping to have the Audio Engine V2 core ready for the next major release, Spring 2024.

**Comment by dad72** [comment]
OK thank you for the information.

**Comment by FrameBuffer4096** [comment]
> > Hi,
> > I was wondering where the progress of the audio engine V2 was ? If there was any idea of ​​when this might be available/planned ?
> > Thanks
> 
> We're hoping to have the Audio Engine V2 core ready for the next major release, Spring 2024.

This is great news!  Will there be a PR for this soon to test drive?

**Comment by RaananW** [comment]
This update will probably not be included in 7.0, but I will wait for @docEdub to be sure.

**Comment by dad72** [comment]
I proposed this for my part for the V2 of the Audio engine ;
https://github.com/BabylonJS/Babylon.js/issues/12576#issuecomment-1212470389

This new audio engine has been moved several times. Will it be for version 8 or is it abandoned?

**Comment by docEdub** [comment]
> Will it be for version 8 or is it abandoned?

It is not abandoned. I am hoping to spend more time on it after the 7.0 release.

**Comment by bghgary** [comment]
@docEdub Do you want to keep this issue?

**Comment by docEdub** [comment]
> @docEdub Do you want to keep this issue?

Closing this for now. I will reopen or make a new ticket when work starts on the new audio engine.
