### ISSUE TITLE
ground heightmap impostor broken since BJS 5.5.6

### ISSUE THREAD

**Issue by emprove** [BabylonJS/Babylon.js#12578]
When assign heightmap physics impostor to GroundMesh mesh doesnt render at all.
Look at the PG from official docs: https://playground.babylonjs.com/#EXL6K#9
Docs link: https://doc.babylonjs.com/divingDeeper/physics/advancedPhysicsFeatures#the-heightmap
If comment line 42 or change impostor from HeightmapImpostor to MeshImpostor it works as expected. You can change PG bjs to 4.2.1 to see how it should be.

**Comment by deltakosh** [comment]
Help me understand why this github template is unclear?
![image](https://user-images.githubusercontent.com/1306056/170290642-69d2b29a-37d3-404e-8aa1-8545682e4c6b.png)

**Comment by RaananW** [comment]
This does seem like an issue with the heightmap impostor.

Temporarily you can fix it like this - https://playground.babylonjs.com/#EXL6K#33.

@deltakosh - I am keeping this issue open to track. @emprove - if you want to further discuss this issue please use the forum.

**Comment by joergplewe** [comment]
I ran into this issue when porting my flightsim to BJS5 (amongst others). Took me a while to find out the terrain is dropping away.

To fix, is it better to use the `ground.position.y/z = 0` hack or to use `MeshImposter` instead?

Are there plans to fix it?

This playground isolates the effect: https://playground.babylonjs.com/#D3LQD#18

**Comment by deltakosh** [comment]
cc @CedricGuillemet @CedricGuillemetMS

**Comment by CedricGuillemet** [comment]
I'm taking a look.
