### ISSUE TITLE
Accessibility - Alpha

### ISSUE THREAD

**Issue by carolhmj** [BabylonJS/Babylon.js#12581]
- [ ] Investigation
  - Meet up with accessibility researchers, designers and advocates
- [ ] Iterate on the Accessibility Tree concept (https://github.com/BabylonJS/Babylon.js/pull/12074)
- [ ] Ensure the viewer is accessible by default
- [ ] More milestones to be added with investigation

### Design Goals
- [ ] User flows
  - Identify assistive technologies we need to plan for with accessibility team
  - Create several user scenarios to determine needs of feature solutions
- [ ] UI design in Inspector/GUI Editor as needed

**Comment by thomlucc** [comment]
closing as it is not tracked within a project
