### ISSUE TITLE
NME v4

### ISSUE THREAD

**Issue by carolhmj** [BabylonJS/Babylon.js#12582]
- [ ] New features
- https://github.com/BabylonJS/Babylon.js/issues/12151
- https://github.com/BabylonJS/Babylon.js/issues/12150
- https://github.com/BabylonJS/Babylon.js/issues/12148
- https://github.com/BabylonJS/Babylon.js/issues/11818 (related to VSM?)
- https://github.com/BabylonJS/Babylon.js/issues/11319

**Comment by ihc523** [comment]
Based on Babylon.js and CocosCreator, I made a node preview feature. This has been posted at http://store.cocos.com/app/en/detail/3369.
![20220627115638](https://user-images.githubusercontent.com/8569362/175858466-07b1dd71-40fc-438d-bda7-b9b8b038ff70.png)

**Comment by deltakosh** [comment]
Closing this one as we actually have the other active
