### ISSUE TITLE
glXF and behaviors

### ISSUE THREAD

**Issue by RaananW** [BabylonJS/Babylon.js#12599]
- [ ] Implement loader (loaders package)
  - Reuse the glTF loader architecture to implement the glEF loader
  - Define a base loader to be used by both loaders
  - Implement both glEFFileLoader and glEFLoader in version 2.0
  - Define the glEF interfaces 
- [ ] Tech investigation
  - Research usage of ActionManager and how it can be extended
  - Can we reuse Babylon core components, or is it impossible without implementing further modules
  - How abstract can we generate the modules so that they will be usable in packages like VSM?
- [ ] Implement requires components (core package) - Might change after investigation
  - Actions
  - Triggers
  - Behaviors
- [ ] Implement the behaviors extension
  - Implement a new extension for behaviors
  - make the connection between the loader and the core components

**Comment by thomlucc** [comment]
This part is done. Waiting for more glTF specs
