### ISSUE TITLE
2D Gui render depth problem with utilityLayerScene

### ISSUE THREAD

**Issue by ratyes** [BabylonJS/Babylon.js#12606]
**Repro**
- Bug repro on: https://playground.babylonjs.com/#NF8GEE
- Expected result: You expect that render canvas 2D is on top of the utilitylayerscene.
- Current result: utilylayerscene is rendering on top

**Screenshots**
![image](https://user-images.githubusercontent.com/24574835/171045529-613db85f-9c78-4db5-9c5a-58962416fb12.png)

**Desktop (please complete the following information):**
 - OS: [windows]
 - Browser[chrome]
 - Version [5.8.0]

**Additional context**
The utilitylayerscene looks like it works for the 3D models but not for GUI items.

**Comment by sebavan** [comment]
This is actually working as expected despite looking like a bug.

The 2d gui is rendered as a layer right after the scene with blend mode and without depth test thus not impacting depth and 
rendered before any utility layers.

The 3d gui would then be rendered after but on top of it.

I would advise to take the issue to the forum as the template mentions https://forum.babylonjs.com/ so we can find the best fit solution to your needs.
