### ISSUE TITLE
Support for minification property mangling

### ISSUE THREAD

**Issue by bghgary** [BabylonJS/Babylon.js#12615]
Is it possible to turn on property mangling in minification? For my project, turning on property mangling reduces the bundle from 1.43MB to 1MB, but it doesn't run.

For example, for the terser plugin to webpack:
```
      new TerserPlugin({
        terserOptions: {
          mangle: {
            properties: true,
          },
        },
      }),
```

This isn't on by default because it can cause things to break, but maybe we can do it in a way that doesn't break?

https://stackoverflow.com/questions/58835084/webpackterserplugin-mangle-ignores-properties-and-class-names-poor-quality-o

**Comment by RaananW** [comment]
We cannot mangle public properties. We are providing a public API that should never be mangled. What we can do is agree to mangle private properties, which are marked in babylon with `_` at the beginning of the function. This, however, will also mangle public hidden properties (!).

Private/hidden mangling:

```javascript
mangle: {
    properties: {
        regex: /^_/,
    },
},
```

My personal opinion - yes, we should mangle private properties. From initial tests ca. 10% on the package size is reduced when mangling private properties. However (!) this requires changes to the build process, as if an internal package is using a public hidden function, the build might fail or provide incorrect access to those mangled properties.

**Comment by thomlucc** [comment]
https://forum.babylonjs.com/t/support-for-minification-property-mangling/52752
