### ISSUE TITLE
Scene.multiPickWithRay Typescript Defines are incorrect

### ISSUE THREAD

**Issue by GimpMaster** [BabylonJS/Babylon.js#12614]
In the documentation for Scene.multiPickWithRay it says the following:

Predicate function used to determine eligible meshes. Can be set to null.

However the typescript interface shows:

`multiPickWithRay(ray: Ray, predicate: (mesh: AbstractMesh) => boolean, trianglePredicate?: TrianglePickingPredicate): Nullable<PickingInfo>`

requiring that a predicate is passed. I was able to // @ts-ignore this but that feels dirt.

**Screenshots**

![image](https://user-images.githubusercontent.com/7818200/171215674-ccb79a78-0fb2-4e04-80fc-dcdf2ec83150.png)

**Comment by deltakosh** [comment]
cc @RaananW

**Comment by wmurphyrd** [comment]
Changelog says this was released in 5.9.0, but I still have the issue with `scene.multiPickWithRay` in 5.14.1.

Looks like this signature in scene.ts may also need to be updated https://github.com/BabylonJS/Babylon.js/blob/master/packages/dev/core/src/scene.ts#L4952

cc @RaananW

**Comment by RaananW** [comment]
> Changelog says this was released in 5.9.0, but I still have the issue with `scene.multiPickWithRay` in 5.14.1.
> 
> Looks like this signature in scene.ts may also need to be updated https://github.com/BabylonJS/Babylon.js/blob/master/packages/dev/core/src/scene.ts#L4952
> 
> cc @RaananW

Good catch. https://github.com/BabylonJS/Babylon.js/pull/12873
