### ISSUE TITLE
onPointerUp observable on GUI controls only fires when pointer leaves the canvas

### ISSUE THREAD

**Issue by darraghjburke** [BabylonJS/Babylon.js#12627]
Repro: https://playground.babylonjs.com/#XCPP9Y#13

onPointerUp does not fire until the pointer leaves the canvas. The _processObservables function in the control is never called with type === PointerEventTypes.POINTERUP, so the only way it can currently be fired is by _forceUp when the pointer leaves the scene entirely.

This bug has existed since at least 4.2. I have not been able to identify a fix yet. @RaananW and @carolhmj - can one of you take a look?

**Comment by carolhmj** [comment]
Another repro: https://playground.babylonjs.com/#W6RBBW#1
