### ISSUE TITLE
Potential OIT optimization

### ISSUE THREAD

**Issue by lexaknyazev** [BabylonJS/Babylon.js#12631]
Consider using [OES_draw_buffers_indexed](https://www.khronos.org/registry/webgl/extensions/OES_draw_buffers_indexed/) extension on supported platforms to reduce the number of render passes.

**Comment by sebavan** [comment]
Sounds like a pretty cool extension indeed :-)

@CraigFeldspar do you think it would be simple to add ? (assuming support in the engine)

@Popov72 do you know if the same is available in WebGPU ?

**Comment by Popov72** [comment]
Yes in WebGPU you can have these settings per color target:

https://github.com/BabylonJS/Babylon.js/blob/master/packages/dev/core/src/LibDeclarations/webgpu.d.ts#L519-L528

**Comment by Popov72** [comment]
See #13003 which would require the support of the same extension.
