### ISSUE TITLE
Automatically change hardware scaling based on browser zoom level

### ISSUE THREAD

**Issue by PatrickRyanMS** [BabylonJS/Babylon.js#12711]
When the user sets the browser zoom to anything other than 100%, especially when larger than 100%, we can see artifacts in the render due to the canvas thinking it's a different size than it actually is. Zooming in causes the canvas to render at a lower resolution and shows pixelation of all elements. Any ADT will scale with the zoom level, but still renders at the lower resolution of the canvas. Here is a repro:

1. Open any sandbox/PG... this one will do [Interaction Hint | Babylon.js Playground (babylonjs.com)](https://playground.babylonjs.com/#XYV59H)
2. Use the browser zoom to zoom in (ctrl+ to zoom in ctrl- to zoom out)
3. Notice that the canvas is losing resolution as you zoom in and while the ADT is also scaling with the zoom level, it is also losing resolution

If we can [detect the zoom level of the browser](https://www.geeksforgeeks.org/how-to-detect-page-zoom-level-in-all-modern-browsers-using-javascript/) can we dynamically adjust hardware scaling on the scene so that the resolution of the canvas does not change even if the zoom level does?

**Comment by deltakosh** [comment]
I think the resize is not trigger during the zoom change. Or is it?

**Comment by RaananW** [comment]
Checked, it does.

**Comment by RaananW** [comment]
Zoom in and out here - https://playground.babylonjs.com/#7FBWRV , quality will stay the same.

**Comment by RaananW** [comment]
I think the only thing we don't have and might be missing is a way to adjust this flag during a session. I don't see a reason why we don't expose the adjust ratio flag and let devs change it when needed (i.e. - why is it only in the constructor).

**Comment by PatrickRyanMS** [comment]
@RaananW and I chatted and we think we need to add an additional parameter in the engine constructor for the maximum hardware scaling factor. We have a parameter for the minimum hardware scaling factor already with `limitDeviceRatio` but adding a parameter for a maximum hardware scaling factor will prevent perf issues on retina displays when zooming out. Otherwise enabling `adaptToDeviceRatio` in the constructor should prevent the pixelation issues when zooming in.
