### ISSUE TITLE
[NME] Warning for protected block names pops while still typing 

### ISSUE THREAD

**Issue by PatrickRyanMS** [BabylonJS/Babylon.js#12715]
When naming a block, we have a warning pop-up that informs the user that a block they have just named conflicts with protected block names in node material. However, this warning is popping up while the user is typing the name rather than when the user changes focus from the input field. 

For example, if I am typing "normalTex" for the name of the block, the warning will pop when I type the "l" in "normal" and not input the "l". It seems that we should allow the user to finish typing and when they change focus by pressing "enter" or manually changing focus, we should then pop the warning and revert the name back to the block default rather than hijacking the field while typing.

Repro steps:
1. open https://nme.babylonjs.com/
2. click on the color4 block
3. change name to "normalTex"
4. note that you cannot type the full name without getting a popup that removes the "l" from the name even if focus on the input field is not lost.

**Comment by deltakosh** [comment]
can you take care of this one @carolhmj please?

**Comment by deltakosh** [comment]
I'll do it actually :D
