### ISSUE TITLE
[NME] Regression: Vertex target icons missing from block headers

### ISSUE THREAD

**Issue by PatrickRyanMS** [BabylonJS/Babylon.js#12722]
We used to have icons in the header bar of all blocks that were targeted to Vertex and no icon for any block targeted to Neutral or Fragment to help debug targeting issues in NME. These have disappeared in v 5.14.0 but I am unsure of exactly which version they disappeared in.

**Comment by deltakosh** [comment]
I do not think we ever get that :) I did not develop it for sure

we use to have a warning when a neutral block as moved to vertex and I think it is still here right?
