### ISSUE TITLE
Realise a project to show Automatic testing in BabylonJS

### ISSUE THREAD

**Issue by bvaisman-GitHub** [BabylonJS/Babylon.js#12772]
We only accept feature requests that are discussed on the BabylonJS forum

**Is your feature request related to a problem? Please describe.**
I could be great to show the BabylonJS users how to deploy automatic unit tests in a project

**Discussion**
https://forum.babylonjs.com/t/automatic-testing/774/11

**Comment by RaananW** [comment]
To clarify the feature requested here - 

We have not discussed unit testing, as unit testing is local in your project and has nothing to do directly with babylon.
What we can offer in a future release (and probably in an external package) is a way to run validation tests in an external project, similar to the way we run validation tests in our project. It will be a package including peer dependencies on jest, puppeteer and jest-screenshot (among others)

**Comment by bvaisman-GitHub** [comment]
Sorry... I used the "unit testing" expression incorrectly.

In my opinion, what babylonJS users need is a tutorial and a script to know
how they can run validation tests on their own projects.





[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
21/07/22
16:15:00

Le jeu. 21 juil. 2022 à 15:11, Raanan Weber ***@***.***> a
écrit :

**Comment by RaananW** [comment]
I have added validation tests automation in the es6 template - https://github.com/RaananW/babylonjs-webpack-es6#running-validation-tests
