### ISSUE TITLE
Why "Tools.SetReferrerPolicyBehavior" is not a function

### ISSUE THREAD

**Issue by FireLustre** [BabylonJS/Babylon.js#12770]
this is my test code
```
var image = new Image("target", "./ui/missileLockIcon.svg");
image.width = 0.2;
image.height = "40px";
advancedTexture.addControl(image);
```
and i run it in chrome. page is wrong.
<img width="717" alt="image" src="https://user-images.githubusercontent.com/16452711/179919640-6dc82216-65f5-47a1-936a-2fe9ccfde0c1.png">

<img width="788" alt="image" src="https://user-images.githubusercontent.com/16452711/179919746-8f7f0369-a672-43b7-ae94-77306afad2a7.png">

**Comment by carolhmj** [comment]
Please use the forum: https://forum.babylonjs.com/ to validate the issue first.
