### ISSUE TITLE
[babylon-loaders ESM] Can't use SceneLoader without global BABYLON (window.BABYLON)

### ISSUE THREAD

**Issue by runtothedoor** [BabylonJS/Babylon.js#12790]
**Repro**
```typescript
import {
  Color3,
  Color4,
  Engine,
  HemisphericLight,
  Material,
  MeshBuilder,
  MirrorTexture,
  PBRSpecularGlossinessMaterial,
  Scene,
  SceneLoader,
  StandardMaterial,
  UniversalCamera,
  Vector3,
} from "@babylonjs/core";

import 'babylonjs-loaders';

. . .

const scene = new Scene(engine);
   
const camera = new UniversalCamera("camera", new Vector3(0, 5, -10), scene);
camera.setTarget(Vector3.Zero());

// Using already imported SceneLoader doesn't work
(window as any).BABYLON.SceneLoader.Append("", __MyGltf__, scene, function () { 
    scene.meshes[0].position.set(0, 0,0)
});

// Replacing  import "@babylonjs/loaders/glTF"  by import  "@babylonjs/loaders/glTF" and use already imported SceneLoader doesn't show anything
// SceneLoader.Append("", __MyGltf__, scene, function () { 
//     scene.meshes[0].position.set(0, 0,0)
// });
```

**legacy-glTF2.ts** 
https://github.com/BabylonJS/Babylon.js/blob/eabbf0131755fecc4f9f782e3038063e4a0b55eb/packages/lts/loaders/src/legacy/legacy-glTF2.ts#L10

**Comment by sebavan** [comment]
cc @RaananW

**Comment by RaananW** [comment]
You are mixing es6 and umd packaged. please try using @babylonjs/loaders instead of babylonjs-loaders
If you want to discuss this further, we will be happy to do so on the forum. Thanks :-)

**Comment by runtothedoor** [comment]
> You are mixing es6 and umd packaged. please try using @babylonjs/loaders instead of babylonjs-loaders If you want to discuss this further, we will be happy to do so on the forum. Thanks :-)

I don't know if there is a specific reason or it could be some bundler configuration but as I commented, @babylonjs/loaders doesn't work, no error but nothing appears...

![image](https://user-images.githubusercontent.com/28831375/180842995-978994b2-c9cf-4dd6-a4e7-ccb9a254874b.png)

**Comment by RaananW** [comment]
We are using our forum as a place for discussion and I will be happy to see a reproduction of your project to help you debug this. I tested my template-project and it works as expected, so it is probably a configuration issue on your side. 
Waiting at the forum to help further. Thanks :-)

**Comment by runtothedoor** [comment]
> We are using our forum as a place for discussion and I will be happy to see a reproduction of your project to help you debug this. I tested my template-project and it works as expected, so it is probably a configuration issue on your side. Waiting at the forum to help further. Thanks :-)

My post was hidden because of the spam filter but I'll wait and resolve it there then, thank you Raanan

**Comment by runtothedoor** [comment]
Well, the solution I found was register GLTF manually since import wasn't doing it for me

  
```
SceneLoader.RegisterPlugin(new GLTFFileLoader()); 
```
