### ISSUE TITLE
physics & load model

### ISSUE THREAD

**Issue by furan495** [BabylonJS/Babylon.js#12813]
**Use Github issues ONLY for bugs validated on the forum first!**

We have a really active forum to help answering questions (https://forum.babylonjs.com/)

**Repro**
- Bug repro on [playground](https://playground.babylonjs.com): https://playground.babylonjs.com/#SSW9KL
- Expected result: maze falls on the ground
- Current result: The maze doesn't fall on the ground, it's some distance from the ground; additionally only loading models will have this problem.

**Screenshots**
<img width="772" alt="image" src="https://user-images.githubusercontent.com/87800349/182081687-abce170d-f10c-4328-83c0-0503fc9c669e.png">

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] mac m1
 - Browser [e.g. chrome, safari] chrome
 - Version [e.g. 22] 5.17.1

**Smartphone (please complete the following information):**

**Additional context**
Loaded local models, random loading of a model will have this problem.

**Comment by RaananW** [comment]
![image](https://user-images.githubusercontent.com/1381702/182151221-4ef4433c-5322-4c3d-8bec-dfea57f196d5.png)

Also - your reproduction references a model on localhost, so it is impossible to test that. I am clasing ths issue and will be happy to discuss this on the forum. If it is a bug we will reopen this one. 

CC @CedricGuillemet
