### ISSUE TITLE
scene has no effectlayer, error!

### ISSUE THREAD

**Issue by Happy0Ending** [BabylonJS/Babylon.js#12812]
my English is poor,bug it's easy to understand.
scene has no effectlayer,scene.effectlayers is undefined, scene.getGlowLayerByName will make a  error.
because  getGlowLayerByName  use "this.effectlayers .length" .  it should be ""this.effectlayers? .length".

**Comment by deltakosh** [comment]
Please use forum: forum.babylonjs.com
