### ISSUE TITLE
[XR] Trigger and Squeeze buttons are swapped when using WebXR Emulator

### ISSUE THREAD

**Issue by yuripourre** [BabylonJS/Babylon.js#12826]
**Repro** 
- Bug repro on playground: https://playground.babylonjs.com/#28EKWI#37
- Expected result: Trigger and Squeeze buttons, should scale the proper boxes
- Current result: Trigger Button scales the squeeze box and Squeeze Button scales the trigger box.

**Screenshots**
![Screenshot from 2022-08-02 18-46-46](https://user-images.githubusercontent.com/1824878/182506449-7c5bd789-26ab-4480-814d-6267e3918c05.png)

**Desktop (please complete the following information):**
 - OS: Fedora 34
 - Browser: Chromium
 - Version 100.0.4896.127

**Additional context**
Babylon.js version `5.17.0`

**Comment by RaananW** [comment]
This is an issue with the emulator and not with babylon.js. the emulator is sadly not being developed anymore, and we have no real way of knowing we are in an emulated environment (and we are very happy about it).

**Comment by yuripourre** [comment]
@RaananW thanks for your answer. I will investigate it further, I've being using this emulator to create libGDX+webXR apps without any issues.

I definitely want to know what's going on.
