### ISSUE TITLE
add option to recenter the camera in WebXR

### ISSUE THREAD

**Issue by hgouveia** [BabylonJS/Babylon.js#12875]
I would like to have the option to recenter the headset to the new user's position like others platform does like SteamVR,
my only guess will be to move the Entire scene to the user's position, but I dont see a way to do that

for example in a game like beat saber you have a fixed point in the scenario,  then if you  change your position to have a better spot in your IRL room, then you will be offcenter of the game scenario, in that case you will want to recenter the VR, to set that new position as the origin point of the scenario

**Describe the solution you'd like**
I would to have an option where i can trigger this,  for example `xr.recenter();`

**Discussion**
https://forum.babylonjs.com/t/is-it-possible-to-recenter-the-camera-in-webxr/32996

**Comment by thomlucc** [comment]
https://forum.babylonjs.com/t/add-option-to-recenter-the-camera-in-webxr/52143
