### ISSUE TITLE
Tools.LoadScript shouldn't return without calling onError / Infinite loading on ImportMeshAsync

### ISSUE THREAD

**Issue by wmurphyrd** [BabylonJS/Babylon.js#12882]
This line in LoadScript returns without calling either onSuccess or onError if no window object is found, this leads to the parent promise never resolving and being stuck forever in a loading state. Please call onError here before returning

https://github.com/BabylonJS/Babylon.js/blob/master/packages/dev/core/src/Misc/tools.ts#L420

Steps to repro: in WebWorker (i.e. location with no window object) try calling `SceneLoader.ImportMeshAsync` with a model that uses EXT_meshopt_compression

The ImportMeshAsync promise will never resolve

**Comment by deltakosh** [comment]
Wanna do a PR to fix it?

**Comment by wmurphyrd** [comment]
@deltakosh would you be open to an alternative that actually did load the script in a worker context via `self.importScrsipts`?

**Comment by deltakosh** [comment]
sure thing!
