### ISSUE TITLE
babylonjs-viewer not working in Vite

### ISSUE THREAD

**Issue by asdjgfr** [BabylonJS/Babylon.js#12889]
**Screenshots**
![image](https://user-images.githubusercontent.com/23442840/185938597-8938c298-de31-4372-9e72-aee4585c33bf.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser  Microsoft Edge
 - Version  104.0.1293.63

**Additional context**
1. Using vite [vanilla template](https://vitejs.dev/guide/#trying-vite-online)

2. Install with npm
``` shell
npm install --save babylonjs-viewer
```
3. Using import:
``` javascript
import * as a from "babylonjs-viewer"
```

 **There is no problem with CDN.**

**Comment by deltakosh** [comment]
Please use the forum first  as mentioned clearly in the issue template

Thanks a lot!
