### ISSUE TITLE
Adding support for "combining" animation groups

### ISSUE THREAD

**Issue by feuersteiner** [BabylonJS/Babylon.js#12895]
**Problem**
Currently, we cannot export an animation group that has multiple animation groups in it.
Usecase: you have a "walk" animation group embedded in a GLTF, and you create a "translate" animation along the X axis (to give the illusion of walking), and now you want to export all of them into one final GLTF file. 

**Solution**
A utility function that:
- takes multiple animation groups
- each animation group has a start frame and end frame
- compiles all into one final animation group

[**Forum Discussion**](https://forum.babylonjs.com/t/can-we-combine-animation-groups-into-one/33107/5)

**Comment by RaananW** [comment]
(temp assigning @deltakosh, let's discuss this internally)

**Comment by RaananW** [comment]
> thanks @RaananW, as stated on the forum, would love to contribute here.

These kinds of statements make us extremely happy :-)

**Comment by deltakosh** [comment]
I can't agree more :D
