### ISSUE TITLE
Texture UV animation performance

### ISSUE THREAD

**Issue by thomlucc** [BabylonJS/Babylon.js#12987]
See Forum thread: https://forum.babylonjs.com/t/texture-uv-animation-is-very-slow/33902

Texture animation (via uOffset, vOffset, etc.) is very slow since it causes the materials to be flagged as dirty. Setting scene.blockMaterialDirtyMechanism to true will make the speed much faster, but disabling this globally has potentially undesirable side effects for the rest of the scene. And assigning blockMaterialDirtyMechanism to true just before the updates and then reverting to false afterwards is not viable since this causes all materials to be flagged as dirty.

Is there some way to allow fast UV updates without having to force blockMaterialDirtyMechanism to be true globally for the entire duration of the scene? Technically I think the private field _blockMaterialDirtyMechanism could be manually updated, but this is not a stable solution.

Demo (change the mode parameter): https://playground.babylonjs.com/#27Y5SJ

**Comment by deltakosh** [comment]
Closing as there is no direct resolution other than the one from @Popov72 
Users can directly update the texture matrix and that way they can skip the entire update process. They are a lot of corner cases but at least in that case it works well
