### ISSUE TITLE
5 GB repo

### ISSUE THREAD

**Issue by psnet** [BabylonJS/Babylon.js#12981]
Hi

Guys, it is a joke or you don't want somebody to clone your repo? :) 

![t](https://user-images.githubusercontent.com/1023918/189992080-2b320685-7f82-4090-9aa2-6bec1ce74a1f.png)

After unpack entire repo is more than 5 GB, where `.git` folder is 4.5+ GB.

It is a bit large, is not it?

**Comment by deltakosh** [comment]
As mentioned in our template please discuss on the forum :)

(We are aware of that and we are working on it @RaananW )
