### ISSUE TITLE
Add Logarithmic Depth Support on ParticleSystem

### ISSUE THREAD

**Issue by Atsutakemura** [BabylonJS/Babylon.js#13005]
Hello everyone,

**Problem**
I have a small space game project and wanted to give it some diversity like different space ship sizes and the opportunity to zoom deep into planet surface. Also different space system types (i.e. asteroid fields, gas nebulas, suns). To solve z-fighting srzerbetto brought me to the solution to use Logarithmic Depth on materials. I was able to implement it to the project, thanks to Evgeni_Popov even to ShaderMaterial. But there is still z-fighting left on all of the particle systems like nebulas (PG: https://playground.babylonjs.com/#L3JUGF%2316) or on the space ship jets (drive particles).

**Requested Solution**
I would like a Logarithmic Depth Support on ParticleSystem to be added.

**Link to Forum Discussion:**
https://forum.babylonjs.com/t/z-fighting-on-multiple-objects/34067/13

Thanks in Regards,
Takemura

**Comment by deltakosh** [comment]
Makes sense! Tagging myself and @Popov72 to see who can do it first

**Comment by deltakosh** [comment]
Working on it right now :)
