### ISSUE TITLE
BABYLON.NormalMaterial is not a constructor

### ISSUE THREAD

**Issue by robomentor** [BabylonJS/Babylon.js#13025]
Babylon.js v5.25.0

yarn add -S @babylonjs/core

```
const scene_axis_view_cube: any = BABYLON.MeshBuilder.CreateBox("scene_axis_view_cube", {}, scene_axis_view);
scene_axis_view_cube.material = new BABYLON.NormalMaterial("scene_axis_view_cube", scene_axis_view);
```

ERROR：
BABYLON.NormalMaterial is not a constructor

**Comment by sebavan** [comment]
you need to install the @babylonjs/materials package 

Please use our forum for questions. As the template mention we keep github for validated issues and feature request.
