### ISSUE TITLE
models exported from meshlab are not rendered correctly

### ISSUE THREAD

**Issue by yantaozhao** [BabylonJS/Babylon.js#13030]
I have a model (having obj+mtl+png) exported from meshlab.
the model is not rendered consistently with meshlab.

**Repro**
- Expected result: models (having obj+mtl+png) rendered consistently with meshlab
- Current result: the rendered result of babylon.js from [sandbox](https://sandbox.babylonjs.com) seems flipped horizontally.

**Screenshots**

meshlab:

![image](https://user-images.githubusercontent.com/9587405/192488733-d467a350-97fc-4570-bf61-bb2eebbab9d3.png)

babylon.js sandbox:

![image](https://user-images.githubusercontent.com/9587405/192489063-ba512074-c98e-46c3-8167-d4d0023b545b.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10, meshlab2022.02
 - Browser [e.g. chrome, safari] google chrome 105.0.5195.127
 - Version [e.g. 22] babylon.js sandbox online

**Comment by RaananW** [comment]
Was that discussed on the forum at any point?

**Comment by deltakosh** [comment]
Closing as discussion in the forum is mandatory as mentioned clearly in the template
