### ISSUE TITLE
Add flexbox behavior and responsive units (rem, em) to GUI

### ISSUE THREAD

**Issue by wavetro** [BabylonJS/Babylon.js#13059]
## This is a feature request.

**- Link to [forum](https://forum.babylonjs.com/) discussion about the feature:** 
https://forum.babylonjs.com/t/gui-responsive-css-units-and-mobile-breakpoints/34400

**- Feature description:**
Currently, the GUI system lets you create user interfaces using `px` and `%` units aligned on a grid with custom values for columns and heights. However, these tools aren't enough to ensure a consistent experience across different screen resolutions and device pixel densities. CSS has units that adjust based on these differing browser defaults (rem, em) and also a modern layout system (flexbox) to ensure nice-looking UIs for websites on any screen size. I think Babylon.js should implement these concepts into the GUI system, so that Babylon users can create more responsive and attractive menus and interfaces for their applications. See the forum post above for more context.

**- Additional links that could help implementing the feature:**
https://css-tricks.com/snippets/css/a-guide-to-flexbox/
https://www.sitepoint.com/understanding-and-using-rem-units-in-css/

**Comment by thomlucc** [comment]
https://forum.babylonjs.com/t/add-flexbox-behavior-and-responsive-units-rem-em-to-gui/52141
