### ISSUE TITLE
Tracking algorithm in WebXRImageTracking

### ISSUE THREAD

**Issue by TinaLiuArcher** [BabylonJS/Babylon.js#13073]
Hi,

Wondering what the algorithm used in [WebXRImageTracking](https://github.com/BabylonJS/Babylon.js/blob/a578406f39b34a26c983d0006e2c22fef69501da/packages/dev/core/src/XR/features/WebXRImageTracking.ts). For example, how to detect or register an image, how to get the perspective/distance?

**Comment by sebavan** [comment]
@TinaLiuArcher  was this discussed on the forum ?

cc @RaananW

**Comment by RaananW** [comment]
WebXRImageTracking is using WebXR's native Marker Tracking feature (https://immersive-web.github.io/marker-tracking/). It depends on the underlying system. The algoruthm was not implemented by us.
