### ISSUE TITLE
sh: build-tools: command not found

### ISSUE THREAD

**Issue by LiemLin** [BabylonJS/Babylon.js#13093]
https://github.com/BabylonJS/Babylon.js/blob/1d74e28f5de7388ea06316594edeaf52c61290f1/package.json#L67

The operating system is macOS 11.5
When execute command npm run build:dev , throw error sh: build-tools: command not found

**Comment by sebavan** [comment]
cc @RaananW

**Comment by sebavan** [comment]
This works on linux and seems to be ok on my Mac can you create a post in the https://forum.babylonjs.com/ so we discuss it there before opening an issue as the template mentions

**Comment by RaananW** [comment]
Was that discussed in the forum?

In general - the build tools are built during npm install. if npm install was successful you should have build-tools as a binary.
There might be a mac os issue here, which I will be happy to discuss in our forum with you.
