### ISSUE TITLE
Add uv transforms to thininstances

### ISSUE THREAD

**Issue by unicomp21** [BabylonJS/Babylon.js#13103]
Add uv transforms to thininstances.

**Comment by deltakosh** [comment]
Please reference the forum post

**Comment by unicomp21** [comment]
https://forum.babylonjs.com/t/thin-instances-uv-attribute-weird-result/34061/14?u=unicomp21

**Comment by unicomp21** [comment]
I think it could be edge ... until it's not.  The potential here for a non-repeating (thanks to variation in texture), volume filling primitive, is pretty significant.

**Comment by sebavan** [comment]
By edge case I mean not everybody will use it and thus I d prefer it to be on demand to not increase the size of the code in most of the experiences.

**Comment by unicomp21** [comment]
How much of a size increase will there be?

**Comment by sebavan** [comment]
not sure but we could say the same for any small features resulting in overall big additions :-)

I am not saying we should not add the feature, but I d rather keep it as a material plugin that people need to import in order to benefit from it instead of embedding it in the material.

**Comment by thomlucc** [comment]
https://forum.babylonjs.com/t/add-uv-transforms-to-thininstances/52140
