### ISSUE TITLE
Ktx2 texture displayed black on android phone

### ISSUE THREAD

**Issue by tippula8** [BabylonJS/Babylon.js#13117]
ktx2 texture is displayed black on android phone (Android 11, chrome browser), but everything is displayed fine on desktop (windows 10).
https://www.babylonjs-playground.com/#WP9WDU#137

**Comment by RaananW** [comment]
We discuss these issues on the forum first, before opening an issue on github (as the template clearly stated). Thanks, waiting for you on the forum. cc @bghgary

**Comment by bghgary** [comment]
Forum issue here: https://forum.babylonjs.com/t/ktx2-texture-displayed-black-on-android-phone/34773/3

**Comment by bghgary** [comment]
Console error:
> [.WebGL-0x200345b00]GL ERROR :GL_INVALID_VALUE : glCompressedTexImage2D: dimensions out of range

**Comment by bghgary** [comment]
The texture is too big for mobile. Chrome for Android simply rejects textures that are this big.
