### ISSUE TITLE
PickingInfo.getNormal direction is reversed when not using vertex normals for GLTF 

### ISSUE THREAD

**Issue by jardle** [BabylonJS/Babylon.js#13115]
[Forum post](https://forum.babylonjs.com/t/pickinginfo-getnormal-direction-is-reversed-when-not-using-vertex-normals-for-gltf/34634/1)

**Repro**
- Bug repro on [playground](https://playground.babylonjs.com/#WGZLGJ%236535):
- Expected result: Calling PickingInfo.getNormal with useVerticesNormals=false should return a vector in roughly the positive x direction:
```
{
    "_isDirty": true,
    "_x": 0.964271446769104,
    "_y": 0.23283821473925717,
    "_z": 0.1263603684026554
}
```
- Current result:  Direction is reversed:
```
{
    "_isDirty": true,
    "_x": -0.964271446769104,
    "_y": -0.23283821473925717,
    "_z": -0.1263603684026554
}
```

**Additional context**
[Code Ref](https://github.com/BabylonJS/Babylon.js/blob/master/packages/dev/core/src/Collisions/pickingInfo.ts#L98-L107)

comment from @bghgary from the forum post: 
> Yes, this looks like a winding order issue. It’s not specific to glTF though. This code needs to take the winding order into account, and it doesn’t.

**Comment by bghgary** [comment]
I'm not sure what the right fix is for this. Getting the winding order from an abstract mesh is possible with some refactoring, but I'm not sure this is correct. What if someone picks a back face? Should the normal be pointing towards the pick ray or towards the front face? I kind of think it should be always towards the pick ray?

**Comment by Popov72** [comment]
> What if someone picks a back face? Should the normal be pointing towards the pick ray or towards the front face? I kind of think it should be always towards the pick ray?

In my opinion, the normal we return is the normal of the geometry at the picking point. So for a back face it should point backward (the same direction as the normal of the triangle). It's up to the user to reverse the normal if they need it to point toward the origin of the picking ray.

**Comment by sebavan** [comment]
Maybe a parameter on the pick function could be introduced for convenience ?
