### ISSUE TITLE
Allow users to set no height/height in percentage on Stack Panel Control and its children in GUI Editor

### ISSUE THREAD

**Issue by carolhmj** [BabylonJS/Babylon.js#13140]
Related forum discussion: https://forum.babylonjs.com/t/gui-editor-bug-cannot-enter-percentage-value-with-toolbox-button/33225/7

In code, it's possible to set a Stack Panel container to have no height, which allows it to adapt to its children's height. It is also possible to add children with sizing in percentage. This is not possible in the Editor right now.

**Comment by thomlucc** [comment]
https://forum.babylonjs.com/t/allow-users-to-set-no-height-height-in-percentage-on-stack-panel-control-and-its-children-in-gui-editor/52139
