### ISSUE TITLE
Support relative paths for custom set paths for KhronosTextureContainer2

### ISSUE THREAD

**Issue by Steffen-T** [BabylonJS/Babylon.js#13158]
Can't use relative paths for [KhronosTextureContainer2.URLConfig](https://doc.babylonjs.com/typedoc/classes/BABYLON.KhronosTextureContainer2#URLConfig). Only absolute paths work.
[Forum discussion](https://forum.babylonjs.com/t/how-to-make-ktx2decoder-on-local-request-it-takes-too-long/34760/4) suggests a simple `Tools.GetAbsoluteUrl` is missing.
Perhaps this is also needed for [MeshoptCompression.Configuration](https://doc.babylonjs.com/typedoc/classes/BABYLON.MeshoptCompression).

**Desktop**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 106.0.5249.119

**Comment by bghgary** [comment]
MeshoptCompression already supports relative urls: https://github.com/bghgary/Babylon.js/blob/c599fb01de51ab3eba031c8d1d3c609351e8aa23/packages/dev/core/src/Meshes/Compression/meshoptCompression.ts#L81
