### ISSUE TITLE
 Populate 2D texture array from image asset

### ISSUE THREAD

**Issue by axeljaeger** [BabylonJS/Babylon.js#13174]
We only accept feature requests that are discussed on the BabylonJS forum

**Is your feature request related to a problem? Please describe.**
WebGL supports TextureArrays. This is an indexable array of textures, widely used as a replacement for a texture atlas. In contrast to using one texture and use parts of it by using UV-coordinates, texture arrays allow:
- Using texture repetition by using UV-coordinates > 1.
- Indexing them directly, e.g. for drawing them with thin instances and using the instance id as index

Babylon JS added support for texture arrays using the RawTextureArray2D class. However, it only accepts a raw buffer to populate the content. This makes it hard to use for day to day usecases such as loading a texture array from an image file or using a canvas to prepare 2D content. 

**Describe the solution you'd like**
A simple way of populating a texture array from both a loaded Image and a canvas. In my current application, I have both usecases. 

**Discussion**
https://forum.babylonjs.com/t/populate-2d-texture-array-from-image-asset/35140/1

**Comment by pandaGaume** [comment]
FYI, this is what i've done in [this demo](https://forum.babylonjs.com/t/texture-3d-sub-image-updating/47389). The only missing part is the same support for WebGPU. Note: the playground is break since V7.0, but this is only declarativ, the code is still valid and used into other demo such [this mapping](https://avegalaxar.com/babylon/3DMap.html) one.

**Comment by thomlucc** [comment]
Check status of feature request here: https://forum.babylonjs.com/t/populate-2d-texture-array-from-image-asset/35140

**Comment by axeljaeger** [comment]
Did you implement it?
