### ISSUE TITLE
LayerMask doesn't seem to work for cameras in XR

### ISSUE THREAD

**Issue by kryzodoze** [BabylonJS/Babylon.js#13185]
**Repro**
- Bug repro on [playground](https://playground.babylonjs.com): https://playground.babylonjs.com/#9K3MRA#1028
- Expected result: Sphere is visible in XR
- Current result: Sphere is not visible in XR

**Desktop (please complete the following information):**
 - Browser [e.g. chrome, safari]: Chrome
 - Version [e.g. 22]: Version 106.0

**Additional context**
I tried digging through the source code - and it may be that scene's activeCamera isn't set to the XR camera when entering XR mode. If you change the XR camera's layerMask to 0, it should render nothing, but it still renders the default. So it must not be looking at layerMask at all.

**Comment by sebavan** [comment]
The layer mask does not look like being propagated properly to the rig cameras it contains.

Here is a workaround until we push a proper fix https://playground.babylonjs.com/#9K3MRA#1031

Thanks for reporting.
