### ISSUE TITLE
[Sandbox] Can't switch camera if cameras have the same name

### ISSUE THREAD

**Issue by hybridherbst** [BabylonJS/Babylon.js#13203]
**Repro**
- Open https://sandbox.babylonjs.com/
- Drop this file: [MultipleViews.zip](https://github.com/BabylonJS/Babylon.js/files/9943792/MultipleViews.zip)
- Use the camera dropdown to switch between views
- Expected: can see what each camera sees
- Actual: seems views are searched by name, thus can only select one view
Compare to https://github.khronos.org/glTF-Sample-Viewer-Release/

**Screenshots**
![image](https://user-images.githubusercontent.com/2693840/200120157-edd2f6c6-4a6e-4bf6-9bf5-f64337c72029.png)

**Comment by sebavan** [comment]
This should be available tomorrow after our daily publish :-)

**Comment by sebavan** [comment]
Thanks @carolhmj
