### ISSUE TITLE
Are there plans to add support for cesium（3dtiles）？Or improve the size of the babylon format？

### ISSUE THREAD

**Issue by dalidaliW** [BabylonJS/Babylon.js#13230]
Are there plans to add support for cesium（3dtiles) 
The babylong format is 5-10 times the size of the glb file compressed with gltf pipeline?

**Comment by sebavan** [comment]
As the template mention github is only used for validated feature requests or bugs. Could you move the discussion to our forum : https://forum.babylonjs.com/ ?
