### ISSUE TITLE
 NME Gradient node, change Hex value on Color Panle does Not change the color.

### ISSUE THREAD

**Issue by jixiangcn** [BabylonJS/Babylon.js#13296]
![0` 1B3U4FII3(F`@PK ~B Y](https://user-images.githubusercontent.com/5512838/204428243-20e9bbf7-65f8-4f29-abe2-35dc208081cb.png)

After I have changed some numbers of the Hex value or pasted a value into it the color was not changed.

_Originally posted by @jixiangcn in https://github.com/BabylonJS/Babylon.js/issues/13292#issuecomment-1329959479_

**Comment by sebavan** [comment]
As posted on the previous issue and in the template:
![image](https://user-images.githubusercontent.com/16655165/204599824-68db26d8-9c06-4be5-aab2-e140b597e30d.png)

Can we move the conversation on our forum https://forum.babylonjs.com/ until we can all repro ?
