### ISSUE TITLE
Texture3D Bug, with texture2D 

### ISSUE THREAD

**Issue by kevinnroan** [BabylonJS/Babylon.js#13313]
Hi,
I got an error below when I use the sampler3D in the shader.
“GL_INVALID_OPERATION: Two textures of different types use the same sampler location.”
I attached the test scene with the shader code. It looks like that the texture3D cannot be used with texture2D sampler.

Working version ( but texture3D didn’t used )
https://playground.babylonjs.com/#BF96W8#4

Bug version ( but texture3D didn’t used )
https://playground.babylonjs.com/#BF96W8#5

Thanks

**Comment by sebavan** [comment]
It only works in the first case as the sampler is removed by angle (cause it is not in use).

You should try to bind some texture into the textures to prevent them to default to the same location creating the error.

Please, move the conversation to our forum : https://forum.babylonjs.com/ as we keep github for validated issues (as mentioned in the issue template.)
