### ISSUE TITLE
Rotation gizmo does not work at all

### ISSUE THREAD

**Issue by PatrickRyanMS** [BabylonJS/Babylon.js#13315]
In both the playground and the sandbox there is an issue with the rotation gizmo. When enabled, the gizmo axis highlights on click as normal, but will not rotate a selected transform. Mouse movement does not move the gizmo either. Both the gizmo and selected transform appear locked to a user, even when there is no animation locking out the gizmo. 

Repro:

- open any playground or open the sandbox and drop a gltf in the scene. 
- select any transform in the scene
- click on the rotation gizmo to activate it
- click on any axis of the gizmo and move the mouse to try to rotate the transform
- note that no amount of movement will rotation the gizmo and that each axis is selectable in sequence, so the gizmo is recognizing the mouse down action and moving the the correct state. It seems to be ignoring the mouse move action however.

**Comment by CedricGuillemet** [comment]
Rotation is fine with mesh created by MeshBuild but it's clearly blocked for any mesh in a .gltf...debugging now.
