### ISSUE TITLE
Light information block output names rendering incorrectly

### ISSUE THREAD

**Issue by PatrickRyanMS** [BabylonJS/Babylon.js#13329]
Output names on the `LightInformationBlock` are colliding with the sockets and rendering outside the block. This is visible in NME by dragging the Light Information block onto the workspace.

![image](https://user-images.githubusercontent.com/31326855/206314860-911c30cf-5523-4750-8949-033995a6bdb5.png)

**Comment by Popov72** [comment]
We can only fix this problem by increasing the width of the block, but then all the blocks won't have the same size...

![image](https://user-images.githubusercontent.com/4152247/206317194-b59f0e23-50da-4e9d-b5ae-e508499dcf3a.png)

![image](https://user-images.githubusercontent.com/4152247/206317252-4a640b2d-fb85-4f95-8367-4df9015b3dfc.png)

**Comment by sebavan** [comment]
@PatrickRyanMS I think we said it is a go to display the light info block larger for now ?
 
@carolhmj I tried to have a look but not sure how to pass the info easily. Do you want to have a look ?

**Comment by Popov72** [comment]
I think I have something working. Doing the PR now...

**Comment by PatrickRyanMS** [comment]
@sebavan, yes the larger block for light information was the solve for the time being
