### ISSUE TITLE
 [NME] Matrix blocks for determinant, decompose, and transpose

### ISSUE THREAD

**Issue by kzhsw** [BabylonJS/Babylon.js#13354]
**Describe the solution you'd like**
Add build-in blocks for determinant, decompose, and transpose matrix operations.
Update the [docs](https://doc.babylonjs.com/features/featuresDeepDive/materials/node_material/availableNodeBlocks#reciprocal) for existing blocks accepting matrix inputs.

**Discussion**
[How to do matrix math in NodeMaterial](https://forum.babylonjs.com/t/how-to-do-matrix-math-in-nodematerial/36572)

**Comment by sebavan** [comment]
I added determinant and transpose but I won t add decompose for now as the code is pretty heavy and for perf reason in shaders, it is probably better to push towards other ways by not have the node :-)

I will add it later only if fully mandatory.
