### ISSUE TITLE
`instanceof` will return false if element is created from a different window object than the global one

### ISSUE THREAD

**Issue by nerocui** [BabylonJS/Babylon.js#13391]
We are running into an issue where the videotexture we upload ended up drawn upside down on the canvas. After investigation, we found that the cause is this line failing.

https://github.com/BabylonJS/Babylon.js/blob/ff920e81b6b2f24d90aa64fb32f319a0727edf64/packages/dev/core/src/Materials/Textures/htmlElementTexture.ts#L101

I wonder if babylonjs has the ability to pass in the window/host object? In our case, since the element is created from a window object from another window, the global HTMLVideoElement actually refers to the one in the global window object. This causes `this._isVideo = element instanceof HTMLVideoElement;` to fail. I was able to verify this by

1. Checking the element in dev tool where `instanceof` does return false on the global HTMLVideoElement
2. Try calling `instanceof host.HTMLVideoElement` instead and it returns true
3. Patch the videotexture's `_isVideo` to be `instanceof host.HTMLVideoElement` and the code worked as expected.

This also means other `instanceof` can fail too in similar cases.

**Comment by sebavan** [comment]
I will add in the option a flag to allow forcing the fact that the element is a video instead. the window trick is a bit too specific :-) Is that ok with you ?

**Comment by nerocui** [comment]
Hi @sebavan, I think the flag option works for my case. I do see that there are a few other places that also has `instanceof`. I wonder if it'd make sense to find a way to mitigate all of them or at least mention this possible failure in public documentation.

**Comment by sebavan** [comment]
Can you check if engine.getHostWindow() returns the correct window in your case ??? I guess we could use this instead.

**Comment by nerocui** [comment]
@sebavan I think it works. Checked with creating elements with the returned host and global document. `instanceof` does behave differently. 
![image](https://user-images.githubusercontent.com/10738280/210425987-77617795-7d6e-4288-bb97-178e9b402096.png)

**Comment by sebavan** [comment]
Just to be sure, you can confirm _host on your first line is identical to your host window which is where the element comes from ?

If yes I think I can fix it internally with this approach :-)

**Comment by nerocui** [comment]
Yes I was able to verify they are the same. Both host has the same document, and `instanceof` works 
![image](https://user-images.githubusercontent.com/10738280/210447292-1b6b70b9-3b16-441e-aa85-a0e13da13b32.png)

**Comment by sebavan** [comment]
Perfect I will try to PR on Friday for a workaround in Babylon.

**Comment by nerocui** [comment]
Thank you @sebavan! Will it be a patch version or V6 like the milestone suggested?
