### ISSUE TITLE
Boxes Rendering Capacity

### ISSUE THREAD

**Issue by Jiew23** [BabylonJS/Babylon.js#13416]
Hi there, 

I was trying to render a scene with a very large number of boxes at specific locations and with different sizes.  However, when we tested it ro render 400k boxes, the browser starts to behave weirdly (it rendered the scene for less than one second and turned to all black). Rendering 500k boxes would start to cause timeout issue. 

I had a browse for the optimisation and found this (https://doc.babylonjs.com/features/featuresDeepDive/scene/optimizeOctrees), I tried to increase the number of spheres to be rendered on the demo code and found the timeout issue persists.

Could you please advise if there is any way to optimise the code to render more objects (e.g. 20 million of the boxes in a scene)?

Thank you so much.

**Comment by sebavan** [comment]
I guess you d be better off relying on thin instances https://doc.babylonjs.com/features/featuresDeepDive/mesh/copies/thinInstances but even though, 20 millions is a lot.

We keep github for validate issues only, I would advise to continue the discussion on the babylon forum
