### ISSUE TITLE
Allow loading WebAssembly scripts when in node environment

### ISSUE THREAD

**Issue by RaananW** [BabylonJS/Babylon.js#13422]
When running Babylon.js in Node.js it is not enough to load the wasm, as it is required to use Node.js' WebAssembly runtime to parse the file (https://nodejs.dev/en/learn/nodejs-with-webassembly/).
We will need to find a clean way to introduce file loading in different environments.

See discussion here - https://forum.babylonjs.com/t/importasyncmesh-on-server-side-without-scene/34151/39

**Comment by RaananW** [comment]
An acceptable solution for node:

https://forum.babylonjs.com/t/running-nullengine-in-node-js-to-leverage-the-havok-physics-engine/41424/7

**Comment by thomlucc** [comment]
https://forum.babylonjs.com/t/allow-loading-webassembly-scripts-when-in-node-environment/52754
