### ISSUE TITLE
From version 5.42 using same image url multiple times doesn't work

### ISSUE THREAD

**Issue by stefanak-michal** [BabylonJS/Babylon.js#13445]
**Problem**

When you use same image url multiple times, it is visible only once. This bug is from version **5.42**. In version 5.41 works as expected.

**Repro**
- No playground ..I don't know how to upload a picture there (if it's even possible)
- Expected result: See 3 same images next to each other
- Current result: Only one image visible

[babylonjs_test.zip](https://github.com/BabylonJS/Babylon.js/files/10444463/babylonjs_test.zip)

**Screenshots**

![image](https://user-images.githubusercontent.com/5502917/213141896-de241ff4-2ac8-43a5-9f83-01aa77c5df16.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Brave
 - Version v1.47.171

**Additional context**

**Comment by carolhmj** [comment]
Hello! There's a forum report for the same issue https://forum.babylonjs.com/t/gui-editor-bug-parse-from-snippet-with-external-image-from-dropbox-svg/37411, it will be closed by #13440

**Comment by RaananW** [comment]
Closed with https://github.com/BabylonJS/Babylon.js/pull/13440
