### ISSUE TITLE
[Sandbox] Can't switch animations if they share the same name

### ISSUE THREAD

**Issue by hybridherbst** [BabylonJS/Babylon.js#13441]
Related: 
- https://github.com/BabylonJS/Babylon.js/issues/13203

Same issue happens for animations – if animations share a name, only the first one is ever selected in the sandbox.

Also related: 
- https://github.com/google/model-viewer/issues/3224

**Repro**
- Bug repro on [playground](https://playground.babylonjs.com):
[Donkey (1).zip](https://github.com/BabylonJS/Babylon.js/files/10435957/Donkey.1.zip)

- Expected result: can switch between animations (one is the donkey, the other the violin)
- Current result: can't switch animations (it's always the donkey animation that plays)

**Screenshots**
These are different animations:
![image](https://user-images.githubusercontent.com/2693840/212923956-eb05daf3-149f-4f80-b8f9-fd92665fffd4.png)

**Comment by sebavan** [comment]
Thanks a lot for reporting !!!

@carolhmj would be great if you could check as you fixed the previous one IIRC ?

**Comment by carolhmj** [comment]
PR up! I love the lil donkey dancin 😃

**Comment by hybridherbst** [comment]
Haha, thanks, that was quick! The donkey has an elephant brother that'll be an open source asset, can share it here once ready :)
