### ISSUE TITLE
Camera controls in Web Worker?

### ISSUE THREAD

**Issue by joshbrew** [BabylonJS/Babylon.js#13458]
Hi all, I'm currently implementing a web worker renderer for babylonjs. I am able to get the scene on screen just fine but am not able to proxy the camera controls using a method I had working in ThreeJS. I was wondering if anyone had any working examples? If not I'll just add manual controls but I'd rather not have to configure anything but a proxy for the thread to receive events from the element.

For ThreeJS, I used this example to get working controls on a worker using the baked in settings: https://threejs.org/manual/?q=web#en/offscreencanvas  

What would I need to do to differently to get the FreeCamera in Babylon to be responsive on a Web Worker? Any examples I can just borrow from?

Thanks, cheers!

**Comment by sebavan** [comment]
You will have to manually redirect your inputs to the worker.

As we keep github for validated issues only as the template mentioned I would advice to start back to conversation on the forum as I am sure other users might share their implementation: https://forum.babylonjs.com/
