### ISSUE TITLE
CSP errors

### ISSUE THREAD

**Issue by kadinuguru** [BabylonJS/Babylon.js#13461]
Fix for this bug https://github.com/BabylonJS/Babylon.js/issues/9863 is throwing CSP errors. Reverting to old code fixes CSP errors

**Comment by sebavan** [comment]
We github for validating bugs only as the issue template mentions.

Please head over to our forum https://forum.babylonjs.com/ with a repro so we can have a look

**Comment by sebavan** [comment]
cc @carolhmj FYI
