### ISSUE TITLE
Ammo.btMultiSphereShape - How can this work?

### ISSUE THREAD

**Issue by arcman7** [BabylonJS/Babylon.js#13473]
https://github.com/BabylonJS/Babylon.js/blob/42678d6e27dbd834824c431f9dd9ddf311bfc561/packages/dev/core/src/Physics/v1/Plugins/ammoJSPlugin.ts#L1042

If you palce a debugger right at this point in the code and step into the ammo.js function call you'll arrive at a function that looks like this:
```
        function sD(a, c, d) {
            zC();
            a && "object" === typeof a && (a = a.Fz);
            "object" == typeof c && (c = DC(c));
            d && "object" === typeof d && (d = d.Fz);
            this.Fz = Cl(a, c, d);
            h(sD)[this.Fz] = this
        }
```

As soon as the second line gets evaluated, a has been assigned the value `undefined`. So how can passing an array of Ammo.btVector3's ever have any effect?

**Comment by sebavan** [comment]
@arcman7 can you move the conversation to the forum ? https://forum.babylonjs.com/

We keep github as the template mentions only for validated issues.

cc @CedricGuillemet
