### ISSUE TITLE
Foreset WebGPU sample doesn't work due to Wgsl spec change

### ISSUE THREAD

**Issue by shaoboyan** [BabylonJS/Babylon.js#13564]
In babylonjs webgpu sample,  the wgsl shader below
```
==============
// Example WGSL shader code:

var<private> position : vec3<f32>;

struct main_out {
  @builtin(position) gl_Position : vec4<f32>,
}

@vertex
fn main() -> main_out {
  position = vec3<f32>(0.0f);
  return main_out(vec4<f32>(0.5f));
}
```
is not correct anymore due to the new Wgsl spec changes(https://github.com/gpuweb/gpuweb/pull/3859). Now the module-scope variable `position` will shadow the built-in value name.

The suggested fix for this is rename the `var<private> position: vec3<f32>` to others.

**Comment by shaoboyan** [comment]
Hey, is there any progress on this issue?

**Comment by Popov72** [comment]
Not yet, it should happen in the next few weeks.

**Comment by ben-clayton** [comment]
Hi folks,

I work on Tint (Chrome's WGSL compiler) and was part of the WGSL working group discussions which resulted in this scoping rule change. I'm sorry for the breakage.

The working group have decided that _almost_ all identifiers should have consistent symbol resolution (including the `@builtin` enumerators). The outcome of this change is that symbol resolution of `position` in `@builtin(position)` will first resolve to any module-scope declaration (`var`, `fn`, `alias` or `type`) of that name. If no module-scope declaration with that name is found, then symbol resolution will then consult the core language types, builtins and enumerators - hence why your shaders with a `var<private> position` declaration cause the `@builtin(position)` attribute to now error.

The reasons for this change:
* Consistency: Arguments to an attribute, like `@builtin` are now all expressions. Expressions can now resolve to variables, types, functions, and core enumerators like the `builtin` enumerator. There's far less special casing in the grammar, and diagnostics should be easier to follow.
* The ability to now shadow almost anything in WGSL allows future versions of the language to introduce new symbols into without the possibility of breaking existing shaders. For example, if WGSL added an `i64` type in a later version, existing shaders that already declared a `i64` type, function, or variable would continue to compile as before - the user declaration will simply shadow the core type.
* It allows future versions of WGSL to alias more than just types. Example:  `alias my_storage_fmt = rgba8unorm; var diffuse = texture_storage_2d<my_storage_fmt, read>;` (not a V1 feature)

The working group are discussing ways to access for a user to explicitly specify a core language symbol, when that symbol has been redeclared at module scope. One proposal is to add a special `wgsl` namespace, in which case `@builtin(wgsl.position)` would allow you to keep the `position` module-scope `var` declaration. Unfortunately, we're still debating the syntax of this feature, and it will not be available in WGSL V1.

We are putting the final cosmetic touches on WGSL V1, and Chrome is hoping to launch WebGPU in the coming months. It is extremely unlikely that we'll change the scoping rules at this stage.

The only suggestion I have for you is to rename your `position` variable.

Many thanks,
Ben

**Comment by sebavan** [comment]
Thanks a lot for the message @ben-clayton !!!

**Comment by Popov72** [comment]
Thanks for the explanations @ben-clayton.

**Comment by shaoboyan** [comment]
Verified this issue has been fixed. Thanks for your efforts!

**Comment by cx20** [comment]
Does this mean that the issue has been resolved by updating TintWASM?
https://preview.babylonjs.com/twgsl/twgsl.js
https://preview.babylonjs.com/twgsl/twgsl.wasm

**Comment by shaoboyan** [comment]
@cx20  I'm not quite sure about how babylonjs fixing it. But I assume the fix should be a rename for internal variable `position`

**Comment by cx20** [comment]
@shaoboyan

I'm experimenting with `TintWASM` in my [test repository](https://github.com/cx20/webgpu-test).
When I updated `TintWASM` in that repository, I noticed that the conversion result from `GLSL` to `WSGL` changed.
Therefore, I think that it was improved by fixing `TintWASM`.

https://rawcdn.githack.com/cx20/webgpu-test/b46a5c425e23ee4b2ca0a7e2254ebaa13165072c/examples/webgpu_glsl/triangle/index.html

> var<private> position : vec3<f32>;

https://rawcdn.githack.com/cx20/webgpu-test/1ee709fbd96828be2b54c214e84ac150b3996b4e/examples/webgpu_glsl/triangle/index.html

> var<private> position_1 : vec3<f32>;

**Comment by Popov72** [comment]
This is not yet fixed in production.

I have a local PR in progress that fixes it, but it's not deployed yet. So, this PG is not working: https://playground.babylonjs.com/#6GFJNR#168

After the PR merge, this PG will work: https://playground.babylonjs.com/#6GFJNR#178

We had to change our syntax. Basically, all vertex/fragment inputs/outputs should be prefixed with `vertexInputs.` / `vertexOutputs.` / `fragmentInputs.` / `fragmentOutputs.`. The documentation will be updated accordingly.
