### ISSUE TITLE
prePassRenderer indexes into undefined postProcessSourceForThisPass

### ISSUE THREAD

**Issue by hkozachkov** [BabylonJS/Babylon.js#13583]
Under certain conditions, line 425 of prePassRenderer.ts indexes into `this._postProcessesSourceForThisPass` while that is undefined.

I believe that line 425 ( `const firstPP = this._postProcessesSourceForThisPass[0];` )should be replaced with `const firstPP = this._getFirstPostProcess(this._postProcessesSourceForThisPass);` or something similar, to check that this._postProcessSourceForThisPass is defined before indexing into it.

However, the rendering logic is too complex for me to check if that would lead to the expected behavior (as opposed to masking or creating a deeper issue), which is why this is not a pull request.

FYI, this issue emerged when I enabled Order Independent Transparency in a project that already uses multiple render groups, as well as using multiple render targets.

**Comment by sebavan** [comment]
cc @Popov72 

As mentioned in the issue template, we are only using Github for validated issue.

Could you share back on the forum https://forum.babylonjs.com/ ? with a repro case.
