### ISSUE TITLE
Ray bending

### ISSUE THREAD

**Issue by FluorescentHallucinogen** [BabylonJS/Babylon.js#13591]
**Current behavior:**

The ray is always a straight line.

**Expected behavior:**

The ray bend while wobbling or selecting and pulling, like a lasso. See the Mixed Reality Toolkit (MRTK) behavior:

https://user-images.githubusercontent.com/7892779/222911161-75cc2798-7ab0-4766-a61a-347a4fd5a1e9.mp4

**Discussion**

Discussed with @RaananW in Twitter DM.

**Comment by FluorescentHallucinogen** [comment]
Can this be easily achieved by just using `BABYLON.Curve3.CreateQuadraticBezier(origin, control, destination, nb_of_points)`? 🤔

**Comment by thomlucc** [comment]
https://forum.babylonjs.com/t/change-behavior-of-ray-bending/52136
