### ISSUE TITLE
 Memory leak of Crowd navigation

### ISSUE THREAD

**Issue by desertby** [BabylonJS/Babylon.js#13595]
when i use [reacastJSPlugin](https://doc.babylonjs.com/features/featuresDeepDive/crowdNavigation/crowdAgents) of BABYLON, it costs a large memory footprint. And after applying to the mobile device, my phone can not open the page.
So I check the [playground demo](https://playground.babylonjs.com/#X5XCVT#240), and below is the memory footprint case. It is about 930KB.
![image](https://user-images.githubusercontent.com/47724795/223122985-4ac16002-da1c-4766-b308-a21e6af9e406.png)
The one with recast initialized https://playground.babylonjs.com/#X5XCVT#645 is:
![image](https://user-images.githubusercontent.com/47724795/223122839-d14d0a9e-5f16-49a5-b90f-945c547b1192.png)

**Comment by sebavan** [comment]
Closed yesterday by updating the recast build https://github.com/BabylonJS/Babylon.js/pull/13609
