### ISSUE TITLE
HoloLens 2 style bounding box gizmo

### ISSUE THREAD

**Issue by FluorescentHallucinogen** [BabylonJS/Babylon.js#13590]
**Current behavior:**

Currently, the Babylon.js bounding box gizmo uses the legacy HoloLens 1 style from Mixed Reality Toolkit (MRTK) 1.x.

Playground: https://playground.babylonjs.com/#8GY6J8#211

**Expected behavior:**

The Babylon.js bounding box gizmo supports the new HoloLens 2 style from Mixed Reality Toolkit (MRTK) 2.x and above.

The new design is less distracting for users due to less visual noise.

![mixed-reality-toolkit-bounding-box](https://user-images.githubusercontent.com/7892779/222907253-015ec47a-ea98-4fed-a83c-d4e4bc1c594b.png)

https://user-images.githubusercontent.com/7892779/222908213-778bd933-c246-4ec0-ba64-b8cc5da5b0c3.mp4

**Discussion**

Discussed with @RaananW in Twitter DM.

**Comment by FluorescentHallucinogen** [comment]
Just found that `HolographicSlate` gizmo has design very similar to expected.

![holographic-slate-gizmo](https://user-images.githubusercontent.com/7892779/222978731-653e07c5-5e47-4d8c-bb31-669bbd2f048a.png)

Playground: https://playground.babylonjs.com/#43YQHC#2

**Comment by thomlucc** [comment]
https://forum.babylonjs.com/t/hololens-2-style-bounding-box-gizmo/52138
