### ISSUE TITLE
[Sandbox] Sample ktx file mis-displayed

### ISSUE THREAD

**Issue by mcclure** [BabylonJS/Babylon.js#13619]
**Repro**
- Download ibl.ktx from https://github.com/bjornbytes/lovr-docs/tree/v0.16.0/examples/Lighting/PBR_Materials
- Expected: Should look something like 
![weird hexagon](https://files.mastodon.social/media_attachments/files/110/000/359/086/683/031/original/63c9a623ec3a8c89.png)
- Current result: Interpreted as a file with RGB channels all black, alpha channel all white
![image](https://user-images.githubusercontent.com/277318/224411360-048dd536-fae3-45c8-bd6e-549081879cdd.png)

This file is the output of the Google Filament "cmgen" tool on a panoramic photo of a building.

**Alternate expected behavior**: After some experimentation I suspect the reason this is happening is because the file is rg11b10f [GL_R11F_G11F_B10F] and many viewers do not support this. However, **if a ktx file is entered the sandbox cannot process, it should display an error message rather than an incorrect result**.

**Desktop (please complete the following information):**
 - Windows 10 Build 19045
 - Chrome 110.0.5481.178 (Official Build) (64-bit) 
 - Video card: Geforce RTX 3070 Ti, Directx 12 runtime

**Additional context**
I am not a babylonJS user, I was just recommended your sandbox as a good way of viewing files such as KTX. The instructions say to only file here if you have posted on the forum first but I do not have a forum account and so due to the simplicity of the bug I did not do this. Sorry.

**Comment by sebavan** [comment]
Thanks for reporting @mcclure

**Comment by Popov72** [comment]
https://github.com/BabylonJS/Babylon.js/pull/13620

The PR will help bring up the error:

![image](https://user-images.githubusercontent.com/4152247/224487217-7704c3c5-4230-44b3-9b02-fa0cf0e97212.png)

Note that there's also an error message which is generated in the console of the browser.

**Comment by mcclure** [comment]
Can confirm, sandbox with PR works as expected (correctly reports failure)

I notice this issue has been closed although there is an outstanding identified defect (rg11b10f textures not supported). You could consider filing a separate issue to track that. But I will leave it up to the proper users of this project to decide whether to do that…
