### ISSUE TITLE
Visualization of (.vtu), (.case, .geo, .00001, ...) files with babylon.js

### ISSUE THREAD

**Issue by DieuMerciKIMPOLO** [BabylonJS/Babylon.js#13644]
I’m really new to 3D visualization, please bear with me.
We have data from scientific simulations that we intend to visualize in a web application.

The rendering of the simulations is in two types:

the first is a file with a .vtu extension(result.vtu)
The second a set of files:
RESULTS.case
results.currentnb.00001
results.dissip.00001
results.efforts.00001
results.fouriernb.00001
results.geo
results.input_thermal_flux.00001
results.localtime.00001
results.pressure.00001
results.scalar1.00001
results.tempc.00001
results.total_pressure.00001
results.turbener.00001
results.turbvisc.00001
results.velocity.00001
results.wall_temperature.00001
results.yplus.00001
Is it possible to use BABYLON.js as a viewer for these kinds of files. I’m also a taker if there’s an example.

Thank you

**Comment by carolhmj** [comment]
This has already been answered in the forum: https://forum.babylonjs.com/t/visualization-of-vtu-case-geo-00001-files-with-babylon-js/39052, please don't open issues without checking there first.
