### ISSUE TITLE
Support Web Workers to accelerate 2D canvas rendering

### ISSUE THREAD

**Issue by carolhmj** [BabylonJS/Babylon.js#13647]
In some cases, like using Dynamic Texture and/or GUI, we depend on rendering to a 2D context, which can be pretty slow sometimes. We'd like to support usage of Offscreen Canvas and Web Workers to speed this up. This can be done in many levels, like first only supporting in Dynamic Texture for the user to leverage the WW themselves (see example in https://github.com/carolhmj/Babylon.js/blob/offscreenCanvasExperiments/packages/tools/devHost/src/createScene.ts), evolving to optionally render all of the GUI automatically in a WW, if available.

**Comment by jstroh** [comment]
You are my hero.

**Comment by gabrieljbaker** [comment]
Yeah this is epic

**Comment by thomlucc** [comment]
https://forum.babylonjs.com/t/support-web-workers-to-accelerate-2d-canvas-rendering/52755
