### ISSUE TITLE
legacy.js import from cdn fails

### ISSUE THREAD

**Issue by makc** [BabylonJS/Babylon.js#13690]
I am trying [this](https://jsfiddle.net/xn1ohdjs/) in ff/win, and it all goes well for awhile until this happens:

![image](https://user-images.githubusercontent.com/242577/229266785-543ff1e6-f498-47d7-a53c-4e63a130e91f.png)

this `//` causes the url to 404, I think?

For chromium the situation is different, but it won't load any way:

![image](https://user-images.githubusercontent.com/242577/229267031-133fed39-74ef-451e-bb57-671f1a9a892d.png)

To quote SO,
> I believe this is the bug affecting you: https://bugs.chromium.org/p/chromium/issues/detail?id=108055
> There's been discussion about it from 2011-2016, and is ongoing. Basically Chrome can't handle a very large number of requests in a short period of time.

So when you say [here](https://github.com/BabylonJS/Babylon.js/blob/master/readme-es6.md) that people could import BabylonJS entirely using:
```js
import * as BABYLON from "@babylonjs/core/Legacy/legacy";
```
perhaps mention that it only works at compile time with a bundler 😅

**Comment by sebavan** [comment]
I ll update the doc ASAP thanks a lot. 

cc @RaananW to double check when he ll be back from vacation.

**Comment by RaananW** [comment]
I will be happy to mention the browser error, but we as a framework expect it to work :-)
