### ISSUE TITLE
Make the prepass renderer work with node materials

### ISSUE THREAD

**Issue by Popov72** [BabylonJS/Babylon.js#13718]
The prepass renderer only works with the standard and PBR materials.

It would be nice to make node materials work with the prepass renderer, as node materials are used more and more often, and some effects do require materials to support the prepass renderer to work (like SSR, SSAO, ...).

**Comment by CraigFeldspar** [comment]
Can I take this one ? I need it for my own ;)

**Comment by Popov72** [comment]
Of course :)
