### ISSUE TITLE
Havok Plugin Documentation and Instantiation

### ISSUE THREAD

**Issue by sebavan** [BabylonJS/Babylon.js#13765]
I am regrouping the issue for both Core and the Documentation here:

- The Physics Doc does not mention anything about the initialization of HavokPhysics and how to pass it in the plugin.
  - It should detail the 4 cases UMD from CDN, UMD from npm, ES6 and Playground to make it clear to the users 
 
- At the code level, is there any way to reduce the friction to use it in UMD and UMD from CDN ?

FYI: https://forum.babylonjs.com/t/havok-new-plugin-physics-hk-is-not-defined/40049/10

**Comment by deltakosh** [comment]
I really would like to avoid that trick in the user code if possible (the HK object creation). Or at least wrap it into a clean API

**Comment by RaananW** [comment]
https://doc.babylonjs.com/features/featuresDeepDive/physics/havokPlugin

**Comment by arpu** [comment]
"WebAssembly version of the engine. It is available, free to use, under the MIT license"

how can we build our own wasm version?

**Comment by RaananW** [comment]
> "WebAssembly version of the engine. It is available, free to use, under the MIT license"
> 
> how can we build our own wasm version? 

You can't. It's not open source, but free to use.
