### ISSUE TITLE
[Physics] raycast filtering

### ISSUE THREAD

**Issue by CedricGuillemet** [BabylonJS/Babylon.js#13795]
Follow up on https://forum.babylonjs.com/t/let-us-set-filter-masks-for-havokplugin-prototype-raycast/40403

**Comment by FreakTheMighty** [comment]
@CedricGuillemet would this help with back-face culling? For example, could I filter hits for triangles point away from camera?

**Comment by CedricGuillemet** [comment]
@FreakTheMighty No, it's higher level. Filtering per body/shape. Internal representation of a mesh in the physics engine may even not use triangles.

**Comment by FreakTheMighty** [comment]
@CedricGuillemet is it worth creating a issue for this feature request? I suppose the question is, does Havok have any underlying mechanism for getting the hit triangle when using `PhysicsShapeMesh`? I see this [related discussion](https://forum.unity.com/threads/raycasthit-backface-culling.1064876/) in a Unity forum.

**Comment by CedricGuillemet** [comment]
It's possible to filter the meshes that can be used with a filter id and a filter mask. And also in the result, it's possible to have the triangle index.

**Comment by FreakTheMighty** [comment]
I think that triangle index would do what I need. Is that something that's currently exposed?

**Comment by CedricGuillemet** [comment]
Yes, it's exposed by havok but not by raycastresult interface

**Comment by carolhmj** [comment]
PR is open now!
