### ISSUE TITLE
Maybe bug about DumpTools

### ISSUE THREAD

**Issue by Tobepeter** [BabylonJS/Babylon.js#13819]
https://github.com/BabylonJS/Babylon.js/blob/e883bb339451cf7c9aaaaf7fb1618a3a4dff00c6/packages/dev/core/src/Misc/dumpTools.ts#LL141C1-L142C1

 data2[n] = v < 0 ? 0 : v > 1 ? 1 : Math.round(v * 255);
 
v > 1 ? 1 : xxx
maybe change to 

v> 1 ? 255: xxx?

**Comment by carolhmj** [comment]
Hello! As it's stated on our template, please validate issues on the forum first https://forum.babylonjs.com/ before opening on Github.
