### ISSUE TITLE
Abount UNPACK_ALIGNMENT

### ISSUE THREAD

**Issue by Tobepeter** [BabylonJS/Babylon.js#13820]
https://github.com/BabylonJS/Babylon.js/blob/e883bb339451cf7c9aaaaf7fb1618a3a4dff00c6/packages/dev/core/src/Engines/Extensions/engine.rawTexture.ts#L321

 if (texture.width % 4 !== 0) {
        this._gl.pixelStorei(this._gl.UNPACK_ALIGNMENT, 1);
    }

webgl is a statemachine

maybe we need to revert to 4 after changing this parameter？

**Comment by carolhmj** [comment]
Hello! As it's stated on our template, please validate issues on the forum first https://forum.babylonjs.com/ before opening on Github.
