### ISSUE TITLE
Scene Animation Memory Leak Bug

### ISSUE THREAD

**Issue by Tobepeter** [BabylonJS/Babylon.js#13821]
https://github.com/BabylonJS/Babylon.js/blob/9063dde470e2583b2c6f55f3a12692926597997d/packages/dev/core/src/Animations/animatable.ts#L876

the for loop is not stable
because the for loop item `Animatable` will also change the array length as well

this will make the array not clear to zero at all
and I have test that the array will be larger by changes animations（memory leakage）

**Comment by carolhmj** [comment]
Hello! As it's stated on our template, please validate issues on the forum first https://forum.babylonjs.com/ before opening on Github.
