### ISSUE TITLE
webgpu rendermode  :   model.renderOutline = true;    

### ISSUE THREAD

**Issue by idclosed** [BabylonJS/Babylon.js#13828]
In the webgpu model: mesh. renderOutline=true; A white screen will appear

code:
```
const pickResult = this.scene.pick(this.scene.pointerX, this.scene.pointerY);
    if (pickResult.hit) {
      const model = pickResult.pickedMesh;
      // 显示模型的边框
      model.renderOutline = true;
```

<details><summary>log</summary>
Color target has no corresponding fragment stage output but writeMask (ColorWriteMask::(Red|Green|Blue|Alpha)) is not zero.
 - While validating targets[1].
 - While validating fragment state.
 - While calling [Device].CreateRenderPipeline([RenderPipelineDescriptor "RenderPipeline_rgba16float_depth24plus-stencil8_samples1"]).

logger.ts:103 BJS - [17:27:27]: WebGPU uncaptured error (1): [object GPUValidationError] - Color target has no corresponding fragment stage output but writeMask (ColorWriteMask::(Red|Green|Blue|Alpha)) is not zero.
 - While validating targets[1].
 - While validating fragment state.
 - While calling [Device].CreateRenderPipeline([RenderPipelineDescriptor "RenderPipeline_rgba16float_depth24plus-stencil8_samples1"]).

_LogEnabled @ logger.ts:103
(anonymous) @ webgpuEngine.ts:630
250[Invalid RenderPipeline "RenderPipeline_rgba16float_depth24plus-stencil8_samples1"] is invalid.
 - While encoding [RenderPassEncoder].SetPipeline([Invalid RenderPipeline "RenderPipeline_rgba16float_depth24plus-stencil8_samples1"]).

logger.ts:103 BJS - [17:27:27]: WebGPU uncaptured error (2): [object GPUValidationError] - [Invalid RenderPipeline "RenderPipeline_rgba16float_depth24plus-stencil8_samples1"] is invalid.
 - While encoding [RenderPassEncoder].SetPipeline([Invalid RenderPipeline "RenderPipeline_rgba16float_depth24plus-stencil8_samples1"]).

_LogEnabled @ logger.ts:103
(anonymous) @ webgpuEngine.ts:630
249[Invalid CommandBuffer] is invalid.
    at ValidateObject (..\..\third_party\dawn\src\dawn\native\Device.cpp:671)
    at ValidateSubmit (..\..\third_party\dawn\src\dawn\native\Queue.cpp:442)

logger.ts:103 BJS - [17:27:27]: WebGPU uncaptured error (3): [object GPUValidationError] - [Invalid CommandBuffer] is invalid.
    at ValidateObject (..\..\third_party\dawn\src\dawn\native\Device.cpp:671)
    at ValidateSubmit (..\..\third_party\dawn\src\dawn\native\Queue.cpp:442)

_LogEnabled @ logger.ts:103
(anonymous) @ webgpuEngine.ts:630
logger.ts:103 BJS - [17:27:27]: WebGPU uncaptured error (4): [object GPUValidationError] - [Invalid RenderPipeline "RenderPipeline_rgba16float_depth24plus-stencil8_samples1"] is invalid.
 - While encoding [RenderPassEncoder].SetPipeline([Invalid RenderPipeline "RenderPipeline_rgba16float_depth24plus-stencil8_samples1"]).

_LogEnabled @ logger.ts:103
(anonymous) @ webgpuEngine.ts:630
logger.ts:103 BJS - [17:27:27]: WebGPU uncaptured error (5): [object GPUValidationError] - [Invalid CommandBuffer] is invalid.
    at ValidateObject (..\..\third_party\dawn\src\dawn\native\Device.cpp:671)
    at ValidateSubmit (..\..\third_party\dawn\src\dawn\native\Queue.cpp:442)

_LogEnabled @ logger.ts:103
(anonymous) @ webgpuEngine.ts:630
logger.ts:103 BJS - [17:27:27]: WebGPU uncaptured error (6): [object GPUValidationError] - [Invalid RenderPipeline "RenderPipeline_rgba16float_depth24plus-stencil8_samples1"] is invalid.
 - While encoding [RenderPassEncoder].SetPipeline([Invalid RenderPipeline "RenderPipeline_rgba16float_depth24plus-stencil8_samples1"]).

_LogEnabled @ logger.ts:103
(anonymous) @ webgpuEngine.ts:630
logger.ts:103 BJS - [17:27:27]: WebGPU uncaptured error (7): [object GPUValidationError] - [Invalid CommandBuffer] is invalid.
    at ValidateObject (..\..\third_party\dawn\src\dawn\native\Device.cpp:671)
    at ValidateSubmit (..\..\third_party\dawn\src\dawn\native\Queue.cpp:442)

_LogEnabled @ logger.ts:103
(anonymous) @ webgpuEngine.ts:630
logger.ts:103 BJS - [17:27:27]: WebGPU uncaptured error (8): [object GPUValidationError] - [Invalid RenderPipeline "RenderPipeline_rgba16float_depth24plus-stencil8_samples1"] is invalid.
 - While encoding [RenderPassEncoder].SetPipeline([Invalid RenderPipeline "RenderPipeline_rgba16float_depth24plus-stencil8_samples1"]).

_LogEnabled @ logger.ts:103
(anonymous) @ webgpuEngine.ts:630
logger.ts:103 BJS - [17:27:27]: WebGPU uncaptured error (9): [object GPUValidationError] - [Invalid CommandBuffer] is invalid.
    at ValidateObject (..\..\third_party\dawn\src\dawn\native\Device.cpp:671)
    at ValidateSubmit (..\..\third_party\dawn\src\dawn\native\Queue.cpp:442)

_LogEnabled @ logger.ts:103
(anonymous) @ webgpuEngine.ts:630
logger.ts:103 BJS - [17:27:27]: WebGPU uncaptured error (10): [object GPUValidationError] - [Invalid RenderPipeline "RenderPipeline_rgba16float_depth24plus-stencil8_samples1"] is invalid.
 - While encoding [RenderPassEncoder].SetPipeline([Invalid RenderPipeline "RenderPipeline_rgba16float_depth24plus-stencil8_samples1"]).

_LogEnabled @ logger.ts:103
(anonymous) @ webgpuEngine.ts:630
logger.ts:103 BJS - [17:27:27]: WebGPU uncaptured error (11): [object GPUValidationError] - [Invalid CommandBuffer] is invalid.
    at ValidateObject (..\..\third_party\dawn\src\dawn\native\Device.cpp:671)
    at ValidateSubmit (..\..\third_party\dawn\src\dawn\native\Queue.cpp:442)

_LogEnabled @ logger.ts:103
(anonymous) @ webgpuEngine.ts:630
logger.ts:103 BJS - [17:27:27]: WebGPU uncaptured error (12): [object GPUValidationError] - [Invalid RenderPipeline "RenderPipeline_rgba16float_depth24plus-stencil8_samples1"] is invalid.
 - While encoding [RenderPassEncoder].SetPipeline([Invalid RenderPipeline "RenderPipeline_rgba16float_depth24plus-stencil8_samples1"]).

_LogEnabled @ logger.ts:103
(anonymous) @ webgpuEngine.ts:630
logger.ts:103 BJS - [17:27:27]: WebGPU uncaptured error (13): [object GPUValidationError] - [Invalid CommandBuffer] is invalid.
    at ValidateObject (..\..\third_party\dawn\src\dawn\native\Device.cpp:671)
    at ValidateSubmit (..\..\third_party\dawn\src\dawn\native\Queue.cpp:442)

_LogEnabled @ logger.ts:103
(anonymous) @ webgpuEngine.ts:630
logger.ts:103 BJS - [17:27:27]: WebGPU uncaptured error (14): [object GPUValidationError] - [Invalid RenderPipeline "RenderPipeline_rgba16float_depth24plus-stencil8_samples1"] is invalid.
 - While encoding [RenderPassEncoder].SetPipeline([Invalid RenderPipeline "RenderPipeline_rgba16float_depth24plus-stencil8_samples1"]).

_LogEnabled @ logger.ts:103
(anonymous) @ webgpuEngine.ts:630
logger.ts:103 BJS - [17:27:27]: WebGPU uncaptured error (15): [object GPUValidationError] - [Invalid CommandBuffer] is invalid.
    at ValidateObject (..\..\third_party\dawn\src\dawn\native\Device.cpp:671)
    at ValidateSubmit (..\..\third_party\dawn\src\dawn\native\Queue.cpp:442)

_LogEnabled @ logger.ts:103
(anonymous) @ webgpuEngine.ts:630
logger.ts:103 BJS - [17:27:27]: WebGPU uncaptured error (16): [object GPUValidationError] - [Invalid RenderPipeline "RenderPipeline_rgba16float_depth24plus-stencil8_samples1"] is invalid.
 - While encoding [RenderPassEncoder].SetPipeline([Invalid RenderPipeline "RenderPipeline_rgba16float_depth24plus-stencil8_samples1"]).

_LogEnabled @ logger.ts:103
(anonymous) @ webgpuEngine.ts:630
logger.ts:103 BJS - [17:27:27]: WebGPU uncaptured error (17): [object GPUValidationError] - [Invalid CommandBuffer] is invalid.
    at ValidateObject (..\..\third_party\dawn\src\dawn\native\Device.cpp:671)
    at ValidateSubmit (..\..\third_party\dawn\src\dawn\native\Queue.cpp:442)

_LogEnabled @ logger.ts:103
(anonymous) @ webgpuEngine.ts:630
logger.ts:103 BJS - [17:27:27]: WebGPU uncaptured error (18): [object GPUValidationError] - [Invalid RenderPipeline "RenderPipeline_rgba16float_depth24plus-stencil8_samples1"] is invalid.
 - While encoding [RenderPassEncoder].SetPipeline([Invalid RenderPipeline "RenderPipeline_rgba16float_depth24plus-stencil8_samples1"]).

_LogEnabled @ logger.ts:103
(anonymous) @ webgpuEngine.ts:630
logger.ts:103 BJS - [17:27:27]: WebGPU uncaptured error (19): [object GPUValidationError] - [Invalid CommandBuffer] is invalid.
    at ValidateObject (..\..\third_party\dawn\src\dawn\native\Device.cpp:671)
    at ValidateSubmit (..\..\third_party\dawn\src\dawn\native\Queue.cpp:442)

_LogEnabled @ logger.ts:103
(anonymous) @ webgpuEngine.ts:630
logger.ts:103 BJS - [17:27:28]: WebGPU uncaptured error (20): [object GPUValidationError] - [Invalid RenderPipeline "RenderPipeline_rgba16float_depth24plus-stencil8_samples1"] is invalid.
 - While encoding [RenderPassEncoder].SetPipeline([Invalid RenderPipeline "RenderPipeline_rgba16float_depth24plus-stencil8_samples1"]).
</details>

**Comment by Popov72** [comment]
As stated in the template, please use the forum instead: https://forum.babylonjs.com/

Also, provide a reproduction in the [Playground](https://playground.babylonjs.com/), as this PG does work in WebGPU:

https://playground.babylonjs.com/#YMNE9E#1
