### ISSUE TITLE
Not able to run a project in tor-browser: "0Operation is not supported"

### ISSUE THREAD

**Issue by Andrey5045** [BabylonJS/Babylon.js#13858]
If a project (any project, including the playground) is run via tor-browser (all the features for Javascript are on) then it gives an error: 
"0Operation is not supported"
So, a babylon project cannot be hosted on an onion site.

**Comment by Popov72** [comment]
As indicated in the template, please use the forum first to discuss the issue.

[...] I can see you already did it: https://forum.babylonjs.com/t/hosting-babylon-js-project-on-onion-site/40758

Please be patient before you get an answer, as it is still the weekend and your question is quite specific, I'm not sure there are many people in the community who know about onion sites...

**Comment by Andrey5045** [comment]
The issue has not been resolved; still exists, gotta re-open it.

**Comment by Popov72** [comment]
Yes, it will be discussed on the forum.
