### ISSUE TITLE
[Physics] Parenting and transform hierarchy

### ISSUE THREAD

**Issue by CedricGuillemet** [BabylonJS/Babylon.js#13862]
Parenting and physics is a bit difficult because of local/world space changes. In V1, parenting was not allowed and a warning was displayed. I believe we can do better with V2. 
At the price of more CPU costly sync, it's possible to handle parenting.
Regressions are easy to do, so better be rigorous.

Related forum thread: https://forum.babylonjs.com/t/havoc-problems-with-parented-meshes/40584/5

Resolution/testing should be part of documentation (what parenting + precondition => effect) so users can decide how they want to parent and control their meshes.

Test/dev PG:
https://playground.babylonjs.com/#R9DTZ0
There are commented lines (parent with physics, LH/RH hand scene,...). Every variation should be working (RH + physicalized parent + disable pre-step for example)

Also expectation is physics match the rendering. But also, if prestep is enabled, then moving a parent should also move the physics.

Also, update documentation for a page specificly for that purpose.
Physics with thin instances should stay the same. Hence, without parent or a warning is logged.

**Comment by carolhmj** [comment]
https://playground.babylonjs.com/#9VHNB0 Another parenting check case we can use, this one doesn't load from a GLTF to allow checking the two cases (root parent with and without the GLTF transforms) manually
