### ISSUE TITLE
Add double click and long press for GUI Controls

### ISSUE THREAD

**Issue by carolhmj** [BabylonJS/Babylon.js#13861]
Related forum issue: https://forum.babylonjs.com/t/add-doubleclick-and-longpress-for-a-gui-button/40729

We support these as trigger actions for meshes: https://doc.babylonjs.com/features/featuresDeepDive/events/actions#triggers, so we should extend this support. We need to discuss how to do that, through ActionManager too or through some other mechanism.

**Comment by thomlucc** [comment]
No traction. Feel free to re-open
