### ISSUE TITLE
[Screen Reader Support] Allow user to select which GUI Controls will be rendered in the Twin Tree

### ISSUE THREAD

**Issue by carolhmj** [BabylonJS/Babylon.js#13865]
Related forum issue: https://forum.babylonjs.com/t/accessibility-package-confusion-in-the-docs/40752/8

Currently, when a twin tree is rendered, all of the GUI Controls on the Scene are reflected by default. We should add a method so the user can select which controls they want to be rendered (possibly an option in IAccessibilityTag)?

**Comment by gabrieljbaker** [comment]
This would be great @carolhmj ! To have the option to go from a fresh slate and only add the tag to the items I want in the twin tree would be perfect.
