### ISSUE TITLE
webp Animation

### ISSUE THREAD

**Issue by N3GIS** [BabylonJS/Babylon.js#13879]
Webp is a very good texture format, not only small data, but also supports animation, but babylon .js does not support Webp format animation in many places, such as: 
1. The display of Webp animation is not supported in the material;
2. Webp animation is also not supported in UI.
I hope to support Webp animation, with animation, you can make a lot of beautiful effects

**Comment by carolhmj** [comment]
As stated in our template please discuss the feature first in our feature request section :) https://forum.babylonjs.com/c/features/11
