### ISSUE TITLE
Add a helper function to copy a texture to another one

### ISSUE THREAD

**Issue by Popov72** [BabylonJS/Babylon.js#13959]
We currently have [BABYLON.CopyTextureToTexture](https://doc.babylonjs.com/typedoc/classes/BABYLON.CopyTextureToTexture) which can only copy a whole texture to another one.

We should add a function that can copy a smaller texture to some (x,y) offset in the target texture.

**Comment by dCOMMICS** [comment]
Heyy may I help with that.

**Comment by Popov72** [comment]
Of course, contributions are always welcome!

Instead of creating a new function, I think `CopyTextureToTexture` can be extended with the new functionality (maybe as a static function)?

Note that the code should use existing APIs in WebGL / WebGPU to do the job (like `texSubImage2D`), and not perform a render pass (as `CopyTextureToTexture` does currently, but that's because we support a conversion function during the copy, as well as copying to a depth texture).

**Comment by thomlucc** [comment]
https://forum.babylonjs.com/t/add-a-helper-function-to-copy-a-texture-to-another-one/52135
