### ISSUE TITLE
Input manager :  PointerEvent pick with boundingBox

### ISSUE THREAD

**Issue by Perpleex** [BabylonJS/Babylon.js#13967]
Add a way to change the initiator that creates the pickingInfo in pointerEvent to use the boundingbox for picking mesh.
Or, more generally, a way of exposing all picking methods such as sprite multipick etc...
And avoid recreating a new picking with the pointer's coordinates.

(https://forum.babylonjs.com/t/pick-with-bounding-box/41605/2)

**Comment by deltakosh** [comment]
Just introduced new properties:
- scene.pointerDownFastCheck
- scene.pointerUpFastCheck
- scene.pointerMoveFastCheck
