### ISSUE TITLE
The example playground from docs doesn't compline in TS

### ISSUE THREAD

**Issue by ChromeGG** [BabylonJS/Babylon.js#14003]
**Use Github issues ONLY for bugs validated on the forum first!**

We have a really active forum to help answering questions (https://forum.babylonjs.com/)

**Repro**
- Bug repro on [playground](https://playground.babylonjs.com/#2KRNG9%231)
- Expected result: I can run the demo
- Current result: `ERROR: Property 'diffuseColor' does not exist on type 'Material'.`

**Screenshots**
![CleanShot 2023-06-25 at 09 16 14](https://github.com/BabylonJS/Babylon.js/assets/39050595/3843d700-4759-4a11-86c6-aa5ffba02e95)

**Desktop (please complete the following information):**
 - OS: N/A
 - Browser  N/A
 - Version N/A

**Smartphone (please complete the following information):**
 - Device: N/A
 - OS: N/A
 - Browser N/A
 - VersionN/A

**Additional context**
It works for JS. So I guess it's just some typing error

**Comment by Popov72** [comment]
It's expect, `Mesh.material` is of type `Material`, which does not have a `diffuseColor` property.

You should do `groundMaterial.diffuseColor = BABYLON.Color3.Red();` instead.

**Comment by ChromeGG** [comment]
This is the example: https://playground.babylonjs.com/#2KRNG9%231 written in JS.
Hmm... I thought we should be able to switch from JS to TS w/o errors errors like some field doesn't exist. If TS is raising an errors but JS implementation is fine, then it could be an indicator of not adjusted types.
