### ISSUE TITLE
 babylon webXR  AR ground tracking not working in some devices

### ISSUE THREAD

**Issue by jackodiamond** [BabylonJS/Babylon.js#14010]

**Comment by jackodiamond** [comment]
![notWorking](https://github.com/BabylonJS/Babylon.js/assets/14167033/673224e0-6f97-4f61-a615-384860bbec97)
![correctlyWorking](https://github.com/BabylonJS/Babylon.js/assets/14167033/24eca175-5dd4-4a59-a89e-e3c60e0e4d1f)

**Comment by RaananW** [comment]
Regarding tracking - there is little we can do if tracking is not working well on the underlying system, as we don't run the tracking ourselves. If you can explain what is now working with the tracking I might be able to provide a better answer.

Regarding the white screen - this demo requires the plane detection feature, which seems to have been removed in some browsers. When setting a feature as required (as in this demo) and the feature is not compatible with the browser, the `enableFeature` function will throw an exception. Would be great to know which mobile browser doesn't support Plane detection (i can assume the webxr incubation flag is not enabled?)

As we usually say - we would love to discuss this in our forum. We don't use github as a discussion grounds (the teams decision). Would be great if you can come and talk to me on the forum if my answer is not enough.
