### ISSUE TITLE
Decal map: Add an option to apply it before or after the detail map

### ISSUE THREAD

**Issue by Popov72** [BabylonJS/Babylon.js#14024]
See the discussion here:

https://forum.babylonjs.com/t/how-to-render-decal-map-on-top-of-detail-map-or-control-the-render-order-on-a-material-and-its-various-map-properties/42165/6

**Comment by torchesburn** [comment]
any idea how long this would take to implement? Is there any way i could immediately experiment? @Popov72

**Comment by Popov72** [comment]
Implemented in #14025
