### ISSUE TITLE
[Tooling] Support undo/redo

### ISSUE THREAD

**Issue by carolhmj** [BabylonJS/Babylon.js#14042]
This would improve user experience on NME, GUI Editor, etc... And a generic solution can be used in future tools.

**Comment by carolhmj** [comment]
Some forum requests for this: 
https://forum.babylonjs.com/t/add-shortcuts-to-undo-and-redo-in-the-gui-editor/42326
https://forum.babylonjs.com/t/nme-improvements/35266
https://forum.babylonjs.com/t/gui-editor-improvements-suggestion-feedback-parts-1-to-6/32704

**Comment by Pryme8** [comment]
I have a generic script for "Commands" that you could wrap all the existing functionality in pretty easy.

https://github.com/Pryme8/Doomish/blob/main/src/Editor/Commands/Command.ts

Not sure if this would do it for you, but it has worked in every project that I have made that needs undo redo.

You can see how its used by the editor here:
https://github.com/Pryme8/Doomish/blob/main/src/Editor/Editor.ts#L295

and then a simple example command would be like this:
https://github.com/Pryme8/Doomish/blob/main/src/Editor/Commands/Common/DeleteRoomCommand.ts

If you are interested let me know, if not no worries!

**Comment by borismoyosa** [comment]
Hi, I'm curious if there are any updates on this feature? It would really improve the ux of the editor :)

**Comment by RaananW** [comment]
This is still on our agenda. It is simply not that trivial with our current architecture. If we want to deliver something, we want to deliver it the best we can.
We have no timeline on this, sadly.

**Comment by borismoyosa** [comment]
I understand, thanks for the reply!

**Comment by Jeggery** [comment]
> https://github.com/Pryme8/Doomish/blob/main/src/Editor/Commands/Command.ts

The link you provided cannot be opened, I would like to refer to it

**Comment by dennemark** [comment]
Since NME etc. are mainly based on JSON it might be very simple to use immer and Json patches?
 [Immer can generate changes and inverseChanges](https://immerjs.github.io/immer/patches)

Immer however produces immutable data structures. And every change on the json would need to be wrapped by immer then. But it is pretty convenient.

**Comment by Jeggery** [comment]
Are you making progress

**Comment by workhardx2025-ship-it** [comment]
Are you making progress

**Comment by Popov72** [comment]
All our node based tools now support undo/redo (CTRL+Z / CTRL+Y).

**Comment by repulsio** [comment]
@Popov72 Sorry for the ping, though I'm a bit confused, since Ctrl + Z (or CMD + Z on Mac) is not working on the GUI Editor: https://gui.babylonjs.com/

All it does is activate the "Zoom" cursor..

**Comment by Popov72** [comment]
The GUI editor may not support undo/redo indeed... cc @deltakosh who will know for sure.
