### ISSUE TITLE
glTF Export Instanced Meshes as Nodes Pointing to the Same Mesh

### ISSUE THREAD

**Issue by FrameBuffer4096** [BabylonJS/Babylon.js#14056]
**Overview:**
When importing .glTF files, Babylon.js creates instanced meshes when two nodes point to the same mesh however, the opposite does not happen in the exporter which may result in reduced performance of scenes loaded into Babylon.js and subsequently exported due to the exported file no longer having nodes pointing to the same mesh.

**Solution Sought:**
I would like to see Babylon.js .glTF export instanced meshes as nodes pointing to the same mesh.

**Discussion:**
[Forum Reference](https://forum.babylonjs.com/t/how-to-get-instances-exported-when-instantiating-hierarchy-from-assetcontainer/41007/5?u=arraybuffer)

**Comment by gabrieljbaker** [comment]
this would be awesome!

**Comment by zylkowski** [comment]
Any progress on this? All thin instances I try to export to .glb become just empty nodes.

**Comment by sebavan** [comment]
cc @bghgary

**Comment by Jeggery** [comment]
Are you making progress?

**Comment by bghgary** [comment]
I have a local branch that overhauls the code to make this happen, but this won't be done for a while as it's a large change.
