### ISSUE TITLE
No Shader found using GridMaterial

### ISSUE THREAD

**Issue by dengbupapapa** [BabylonJS/Babylon.js#14082]
**version**
    "@babylonjs/core": "^6.13.0",
    "@babylonjs/materials": "^6.13.0",
    "babylonjs": "^6.13.0",
    "babylonjs-loaders": "^6.13.0",
**code**
```js
import * as BABYLON from "babylonjs";
import { GridMaterial } from "@babylonjs/materials";
  let size = 10; 
  let grid = BABYLON.MeshBuilder.CreateGround(
    "grid",
    { height: size, width: size },
    mainScene
  );
  let groundMaterial = new GridMaterial("groundMaterial", mainScene);
  grid.material = groundMaterial;
```
**error info**
![image](https://github.com/BabylonJS/Babylon.js/assets/24804406/d87d0017-8756-4fb4-a627-1e92059b3c55)
**PS**
@babylonjs/materials All materials under @babylonjs/materials will report this error, Or am I using something wrong? :(

**Comment by sebavan** [comment]
As indicated in the template, please first report the problem to [forum](https://playground.babylonjs.com/) for discussion.

cc @RaananW to double check but you should never mix usage of @babylonjs/... our es lib and babylonjs our umd distrib.

**Comment by dengbupapapa** [comment]
> As indicated in the template, please first report the problem to [forum](https://playground.babylonjs.com/) for discussion.
> 
> cc @RaananW to double check but you should never mix usage of @babylonjs/... our es lib and babylonjs our umd distrib.

Thank you very much for your reply. after replacing @babylonjs/materials with babylonjs-materials, it works properly.
