### ISSUE TITLE
Add support for .cube LUTs

### ISSUE THREAD

**Issue by AlexDaniel** [BabylonJS/Babylon.js#14090]
Previous forum discussion: https://forum.babylonjs.com/t/support-for-cube-luts/32630/2

Right now [colorGradingTexture](https://github.com/BabylonJS/Babylon.js/blob/679f2fa1f533c5b8d18d1342d854ccdc334c4cb5/packages/dev/core/src/Materials/Textures/colorGradingTexture.ts) only supports .3dl file.

The problem is very simple: a lot of tools (e.g. Davinci Resolve) can only export `.cube` files. It'd be nice to have first class support for that format to avoid extra conversion. Also, after hours of searching, I found no open-source utility to convert between the two formats, so I'm not sure that such conversion is even available.

An example .cube loader can be found in the amazing postprocessing library: https://github.com/pmndrs/postprocessing/blob/main/src/loaders/LUTCubeLoader.js

**Comment by AlexDaniel** [comment]
Still something I need 😇

**Comment by sebavan** [comment]
Would you want to contribute a loader for it ?

**Comment by AlexDaniel** [comment]
Not right now, but if nobody else does it in like two months or so, then I will.

**Comment by AlexDaniel** [comment]
14 days? Seriously?

**Comment by sebavan** [comment]
Agree it is too short, I ll change it tonight.

**Comment by thomlucc** [comment]
https://forum.babylonjs.com/t/add-support-for-cube-luts/52134

**Comment by gradus0** [comment]
Does anyone know how to apply the cube file format to a video? Just overlay a filter on the <video src=""> tag? I really need an example.
