### ISSUE TITLE
Node material editor is not rendering the connections properly

### ISSUE THREAD

**Issue by AlexDaniel** [BabylonJS/Babylon.js#14100]
![Peek 2023-07-31 13-08](https://github.com/BabylonJS/Babylon.js/assets/5507503/ec50132e-0320-4052-8362-12a1dbbac1c9)

If you look closely, the connections are rendered correctly within the frame container, but somehow it is not resized correctly:

![image](https://github.com/BabylonJS/Babylon.js/assets/5507503/4cfd4871-6645-486b-840b-f36bbfb3360f)

- BabylonJS 6.14.0
- Browser Firefox, Chromium

**Additional context**
It used to work previously, I don't know why it just stopped. Could be because I updated BabylonJS, or maybe it has to do with something else.

**Quick hack:**
By setting:
```css
width: 6000px;
height: 6000px;
```
On the `<svg>` element, I'm able to see all connections of my material.

**Comment by carolhmj** [comment]
Hello! We usually ask first to validate the issue on our forum first: https://forum.babylonjs.com/c/bugs/8
I haven't been able to reproduce this with a newly created Node Material, are you using any specific material? Are you running from nme.babylon.com, or on a local project?

**Comment by AlexDaniel** [comment]
Not reproducable on nme.babylon.com. Running locally with vite. Happens with any material.

**Comment by carolhmj** [comment]
Can you share a repro of your project?

**Comment by AlexDaniel** [comment]
@carolhmj OK, I think I figured it out. So here's what's happening in my case.

I'm using [Quasar](https://quasar.dev/). It turns out that it comes with some default CSS that works around some browser quirks. Specifically, there is an explicit overflow property set for svgs:

https://github.com/quasarframework/quasar/blob/b82b12846dd67e425d4c159e6b51100d703550ed/ui/src/css/normalize.sass#L57
```sass
/*
 * Hide the overflow in IE.
 */

svg:not(:root)
  overflow: hidden
```

It seems that the NME is expecting the opposite.  So, to fix the rendering, I can simply add this to my CSS:
```css
svg:not(:root) {
  overflow: visible !important;
}
```

Now, while it's easy to say that it's an issue in Quasar and not in BabylonJS, I'm not 100% confident about that, because pretty much everything else is working correctly except for node connections. Maybe it makes sense to change the NME layout a bit, so that the SVG is actually taking the size of the viewport?

**Comment by AlexDaniel** [comment]
Actually, I take it back 😇 See this: https://github.com/necolas/normalize.css/issues/718

I think Quasar needs to update its normalize styles a bit. I'll create a ticket for that.
