### ISSUE TITLE
hasAlpha for alpha video (.webm) does not work in WebGPU

### ISSUE THREAD

**Issue by ghtea** [BabylonJS/Babylon.js#14113]
in WebGL2, transparent area of video (.webm) becomes transparent by `videoTexture.hasAlpha=true;` 

**but in WebGPU, it does not work (transparent area become black) and it's has also big lag**

**Repro**
access the playground and set WEBGPU
- Bug repro on [playground](https://playground.babylonjs.com): https://playground.babylonjs.com/#ZMCFYA#597
- Expected result: background should be transparent (works well in WebGL2)
- Current result: background color becomes black

**Screenshots**
![Screenshot 2023-08-02 at 3 24 22 PM](https://github.com/BabylonJS/Babylon.js/assets/47841931/8dd1d3b2-e972-4e6b-b027-a3c36654cfab)

**Desktop (please complete the following information):**
 - OS: MacBook Air M2
 - Browser: Chrome Version 115.0.5790.114 (Official Build) (arm64)

**Comment by Popov72** [comment]
As stated in the template, please discuss the issue in the forum first: https://forum.babylonjs.com/

To answer quickly:
* the video performance problem is a known bug, see https://forum.babylonjs.com/t/performance-issues-with-using-webgpu-for-videodome/41467/5
* regarding the alpha problem, it seems the implementation of WebGPU in Chrome does not retain the alpha component of the source video. Doing some more investigation (will follow up in the forum after you create the issue there).

**Comment by ghtea** [comment]
I created the issue in the forum

https://forum.babylonjs.com/t/hasalpha-for-alpha-video-webm-does-not-work-in-webgpu/42968
