### ISSUE TITLE
Clear color + HDR pipeline = incorrect color

### ISSUE THREAD

**Issue by Queatz** [BabylonJS/Babylon.js#14202]
I finally found out what was going on with my fog color.  If I enable HDR on my `DefaultRenderingPipeline`, then my fog color no longer matches my clear color that's equal to the fog color. I think the fog color is okay but the scene clear color appears to have changed.

**Repro**
- Bug repro on [playground](https://playground.babylonjs.com/#7G0IQW#245) (change the boolean on line 27 to see the correct result)
- Expected result: Boxes fade away into the clear color
- Current result: Boxes fade away into a different color than the clear color

**Screenshots**
Incorrect:
![Screenshot from 2023-08-24 15-21-00](https://github.com/BabylonJS/Babylon.js/assets/540620/bbc1b044-e544-45e6-8e33-4463b829e3ad)

Correct:
![image](https://github.com/BabylonJS/Babylon.js/assets/540620/0a9bc348-0533-49ed-b0fd-28f11ca2a7a1)

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu]
 - Browser [e.g. Firefox]

**Comment by Popov72** [comment]
As stated in the template, please use the [forums](https://forum.babylonjs.com/) first to discuss issues.

In your case, it's a known side-effect of using the default rendering pipeline: you should call `.toLinearSpace()` on the clear color you use for the scene (https://playground.babylonjs.com/#7G0IQW#247)
