### ISSUE TITLE
Is it possible to follow group of targets with the camera?

### ISSUE THREAD

**Issue by hashiramen** [BabylonJS/Babylon.js#14232]
So I know that there is this FollowCamera where you can attach lockedTarget.
I am wondering it is possible to achieve the effect of grouped locked targets, in the sense that camera will resize according to how close or far are the targets from each other.

Here is the example of what I mean that you can do in Unity through the cinemachine (around 18:14 you can see the effect).
It is called Group Target.

https://youtu.be/EZtxeldMlK4?si=2iG0LNd655UiZmCu&t=1094

Thanks in advance.

**Comment by carolhmj** [comment]
The issues page is only for issues validated on the forum, please ask questions on the forum first 🙂 https://forum.babylonjs.com/
