### ISSUE TITLE
Conversion from float to int inconsistent in NGE nodes

### ISSUE THREAD

**Issue by PatrickRyanMS** [BabylonJS/Babylon.js#14244]
When using the float/int convertor node any float passed to the node is converted to int with a floor operation. When passing an int through a Map range node where the output is fractional and then passing that int into the count input of an instantiate node, the value is converted from the fractional value to a whole number with a ceiling operation. At least [this is what appears to happen as illustrated in the repro NGE graph](https://nge.babylonjs.com/#GX5H8Z). The comments in the frame describe the problem as well

The value of the float in the image below being 2.6875 is converted with the float/int converter to an int value of 2. That value is passed into the map range node which results in a value of 5.383562509012257 which by the standard set by the float/int converter, we should expect that a value of 5 is passed to count in the instantiate block. What actually happens is the instantiate block uses a ceil operation to loop 6 times instead of the expected 5 times.

![image](https://github.com/BabylonJS/Babylon.js/assets/31326855/8ac38c4a-1670-459a-9481-30bb3ff93e35)

It seems that whenever our nodes are doing a conversion of a value to int that we should choose one method and stick with it so that users don't end up with inconsistent results.

**Comment by sebavan** [comment]
It is probably cause it uses a for loop and then ends up with < 5.38 so needs to be at 6 to exit the loop :-)

I wonder if round should not be the default ?

**Comment by PatrickRyanMS** [comment]
The output of Map Range suggests the data is still an int from the color and icon, so I am wondering if Map Range is presented with an int for input, if it should also convert the value to an int for output in the same way we convert with float/int converter (floor is the current method, but if round is better it doesn't matter - whatever is the most common practice is fine) before returning the final value. 

The other option is to return a float value (and color code/use float icon on output) whenever an int is connected to the input of Map Range and the user will need to convert back to an int manually before using it. Either method is fine, but the UI needs to reflect whatever path we take so that the user can immediately tell what's going on.

**Comment by deltakosh** [comment]
Yep this was a missing cast to int at the end of the range. I went with floor everywhere ;)
