### ISSUE TITLE
Math.PI / 2

### ISSUE THREAD

**Issue by RolandCsibrei** [BabylonJS/Babylon.js#14245]
Hi! What about to replace Math.PI / 2 with a global constant in the whole codebase to gain a little bit of speed?

**Comment by sebavan** [comment]
not opposed if you fancy doing a PR :-)

**Comment by RolandCsibrei** [comment]
Sure, why not? Where should I put the constant?
Create a global on window?
On Math?
Babylon namespace?

Is PI_HALF an acceptable name? 

Maybe we could do a PI_DOUBLE as well. There are only 35 occurrences in the whole code base. PI / 2 117 occurences. 

It's your call. ;-) 

Thx!

**Comment by carolhmj** [comment]
I think Math is the best place 🤔

**Comment by sebavan** [comment]
I am stupid with names. let s ask @bghgary :-)

**Comment by kzhsw** [comment]
Since this is about performance, microbenchmarks would be nice to have, maybe the profiler in devtools, or standalone tools like d8 from [v8](https://github.com/GoogleChromeLabs/jsvu).

**Comment by Popov72** [comment]
I don't think it will make any difference regarding performance, V8 is probably able to replace `Math.PI / 2` with the right value at bytecode / native code generation time.

Even if V8 does not make this optimization, we would have to do millions of such operations per frame for the difference to be measurable. I think the PR is more about readability than performance.

**Comment by sebavan** [comment]
@RolandCsibrei, do you still want to do this ? or should we close it ?

**Comment by RolandCsibrei** [comment]
> I don't think it will make any difference regarding performance, V8 is probably able to replace `Math.PI / 2` with the right value at bytecode / native code generation time.
> 
> Even if V8 does not make this optimization, we would have to do millions of such operations per frame for the difference to be measurable. I think the PR is more about readability than performance.

In this case I will close this. Thanks!
