### ISSUE TITLE
Evaluate Debug node for NGE like teleport node so it doesn't need to be connected to GeometryOutput

### ISSUE THREAD

**Issue by PatrickRyanMS** [BabylonJS/Babylon.js#14281]
There are times when it could be great to debug a value that isn't wired to the GeometryOutput like this example:

![image](https://github.com/BabylonJS/Babylon.js/assets/31326855/d7c4e5b7-4905-4b7b-ae06-864a7ef48b29)

If the debug nodes could evaluate without connecting to GeometryOutput extending what the teleport nodes already do, it would increase the value of the debug nodes.

**Comment by deltakosh** [comment]
Unfortunately this is not possible without having a lot of hacky code:
- The evaluation of the graph start from the output and conveys a state up the stack
- As the debug node is not connected we have no idea of the state
- Only way I could think of as of now is to store the state on all nodes in case of one of their outputs is a debug node
- In that case we could ask the debug node to somehow simulate the state

I do not believe it is an acceptable solution as this is painfully slow, memory consuming and backward to the overall idea of optimization :(

**Comment by deltakosh** [comment]
Well I may had an idea actually
