### ISSUE TITLE
GUI Editor Code Export

### ISSUE THREAD

**Issue by carolhmj** [BabylonJS/Babylon.js#14317]
Forum discussion: https://forum.babylonjs.com/t/gui-editor-export-ui-design-as-javascript-file/44165

**Comment by BackupMiles** [comment]
I'm interested in working on this issue. Can it be assigned to me?

**Comment by RaananW** [comment]
Of course. Let us know if you have any questions. The best place to discuss it would be he forum post.

**Comment by thomlucc** [comment]
https://forum.babylonjs.com/t/gui-editor-code-export/52133
