### ISSUE TITLE
GLTFFileLoader does not support EXT_mesh_features extension

### ISSUE THREAD

**Issue by wywzixin** [BabylonJS/Babylon.js#14353]
GLTFFileLoader does not support EXT_mesh_features extension

![企业微信截图_20230926173555](https://github.com/BabylonJS/Babylon.js/assets/22430715/859b76fa-30c1-438a-836a-f3a04905de70)

**Comment by bghgary** [comment]
This glTF extension is a multi-vendor extension. This extension can be implemented using [the glTF loader extension mechanism](https://babylonjs.medium.com/extending-the-gltf-loader-in-babylon-js-588e48fb692b). I wouldn't be opposed to adding this to the list of extensions we support if someone is willing to contribute the code.

**Comment by thomlucc** [comment]
https://forum.babylonjs.com/t/gltffileloader-support-for-ext-mesh-features-extension/52132
