### ISSUE TITLE
CreateScreenshot and friends don't fire unless you use runRenderLoop()

### ISSUE THREAD

**Issue by AndrewRayCode** [BabylonJS/Babylon.js#14369]
**Repro**
Run this code:
```js
BABYLON.Tools.CreateScreenshotUsingRenderTarget(
  engine,
  camera,
  400,
  (data) => console.log(data)
);
```
In an environment where you manually call `scene.render()` instead of using `engine.runRenderLoop()`
- Expected result: The callback to be called, and the data to b logged
- Current result: Nothing happens

**Additional context**
This happens because `CreateScreenshot` and friends use [`engine.onEndFrameObservable.addOnce()`](https://github.com/BabylonJS/Babylon.js/blob/6fdf720b19639dc6a887c5f488364c342a76aeaa/packages/dev/core/src/Misc/screenshotTools.ts#L99). This observable is only executed in [`engine.endFrame()`](https://github.com/BabylonJS/Babylon.js/blob/6fdf720b19639dc6a887c5f488364c342a76aeaa/packages/dev/core/src/Engines/engine.ts#L1314), and `endFrame()` is only executed if you use `engine.runRenderLoop()`.

As a workaround, users who set up a manual render loop can do:
```js
    engine.beginFrame();
    scene.render();
    engine.endFrame();
```

One option is to update the docs to explicitly call out this edge case. But there might be something bigger here? Is it an issue that `scene.render()` doesn't notify engine observables? [An official forum reply](https://forum.babylonjs.com/t/scene-render-vs-engine-runrenderloop/15830/2) says there should be no functional difference between `scene.render()` and `runRenderLoop()`. Not running before/after engine observables seems like it could have fundamental differences. In this case it means screenshots don't work. Searching the babylonjs codebase for `onBeginFrameObservable|onEndFrameObservable` shows 18 results. Should `scene.render()` be changed to call engine observables? Should there be a new method to do something similar? Should the various documentation pages like screenshot documentation be updated to add this edge case instruction?

**Comment by Popov72** [comment]
Yes, in this case it's expected to call at least `engine.endFrame` yourself (it's best to also call `engine.beginFrame` even if it's not strictly necessary in this case - but it may be with WebGPU...).

See also https://forum.babylonjs.com/t/screenshots-and-framebuffer-problems/26066/19

Would you be willing to update the docs?

**Comment by sebavan** [comment]
I wonder how we could simplify this to prevent any confusions like engine.render(scenes) or smthg like this ?

**Comment by thomlucc** [comment]
Fixed
