### ISSUE TITLE
Error when trying to load it from jsDelivr 

### ISSUE THREAD

**Issue by Weefle** [BabylonJS/Babylon.js#14370]
**Repro**
- Expected result: to compile
- Current result: Uncaught SyntaxError: The requested module '/npm/babylonjs@5.18.0/+esm' does not provide an export named 'Axis' (at index.js:1:1)

**Screenshots**
![image](https://github.com/BabylonJS/Babylon.js/assets/18496043/87a65daa-e3ff-4bbf-a6f0-6a6a998de42b)

**Desktop (please complete the following information):**
 - OS: Windows 11 pro 64bits
 - Browser: Chrome
 - Version: 117.0.5938.92

**Comment by carolhmj** [comment]
Hello! What happens if you try with a more recent version?

**Comment by Weefle** [comment]
> Hello! What happens if you try with a more recent version?

With latest version 6.22.0

![image](https://github.com/BabylonJS/Babylon.js/assets/18496043/2783a361-abc2-43b0-b555-8f957850896c)

**Comment by sebavan** [comment]
the babylonjs package is not esm friendly. The @babylonjs/core one is lets move the conversation to our forum as we keep github for validated issues only:

![image](https://github.com/BabylonJS/Babylon.js/assets/16655165/829355aa-9861-457a-8d8f-8da23e803925)
