### ISSUE TITLE
NGE saving cached mesh data to json

### ISSUE THREAD

**Issue by PatrickRyanMS** [BabylonJS/Babylon.js#14417]
When pushing glTF meshes to the MeshBlock in node geometry, it appears in the tool as cached data:

![image](https://github.com/BabylonJS/Babylon.js/assets/31326855/1acadb59-bd0c-4e4d-aa2c-4bc18065e5b3)

When a change is made to the graph and then saved, the cached data is saved in the json along with the rest of the graph data which bloats the file size of the json. We likely should ignore any cached vertex data when saving the graph.

![image](https://github.com/BabylonJS/Babylon.js/assets/31326855/78925b67-7d03-4f3e-820f-f6ee7e60e22b)

**Comment by PatrickRyanMS** [comment]
I think having a flag to set serialization of cached data is a good trade off. Should this also appear on the texture node for data that is cached?

**Comment by deltakosh** [comment]
Yes it will (both for texture node and mesh node)
