### ISSUE TITLE
Scene.getMeshesByTags doesn't use argument predicate as filter

### ISSUE THREAD

**Issue by fre-sch** [BabylonJS/Babylon.js#14424]
Documentation states:

> getMeshesByTags(tagsQuery: string, forEach?: ((mesh: [AbstractMesh](https://doc.babylonjs.com/typedoc/classes/BABYLON.AbstractMesh)) => void)): [Mesh](https://doc.babylonjs.com/typedoc/classes/BABYLON.Mesh)[]
> forEach: ((mesh: [AbstractMesh](https://doc.babylonjs.com/typedoc/classes/BABYLON.AbstractMesh)) => void)
> defines a predicate used to filter results

This code clearly doesn't filter using `forEach`:
```ts
        for (const i in list) {
            const item = list[i];
            if (Tags && Tags.MatchesQuery(item, tagsQuery)) {
                listByTags.push(item);
                forEach(item);
            }
        }
```

https://github.com/BabylonJS/Babylon.js/blob/8a5077e0efb4ba471d16f7cd010fe6124ea8d005/packages/dev/core/src/scene.ts#L5229C1-L5235C10

On a side note: I'd argue the argument `forEach` should just be removed. In the current form the workaround using `filter` on the return value is also the better approach than passing a predicate.

**Comment by carolhmj** [comment]
I think this is a documentation issue with the forEach, even the argument name seems to indicate it was never used for filtering in first place (is it correct @deltakosh ?). The documentation should read instead: "function applied on each result".

**Comment by sebavan** [comment]
@carolhmj I would bet on the predicate and a bug here :-) Do you want to create a PR for the fix ?
