### ISSUE TITLE
Description of Vector3.TransformNormal & Vector3.TransformNormalToRef & Vector3.TransformNormalFromFloatsToRef is wrong.

### ISSUE THREAD

**Issue by Fzc09** [BabylonJS/Babylon.js#14423]
**Repro**
Now:

![image](https://github.com/BabylonJS/Babylon.js/assets/50564179/73e4db91-0ed1-434b-bbea-bc8f63db9309)

Expect:
![image](https://github.com/BabylonJS/Babylon.js/assets/50564179/cab25c61-4ffb-40e8-8cdc-1ea733f0ddc9)

It is because only rotation matrix satisfies the inverse of the transpose is equal to itself.

**Comment by Popov72** [comment]
The method is simply multiplying the (x,y,z) coordinates with the matrix and does not account for the translation. So, the description is right, and adding that it does not apply scaling is wrong if the matrix passed by the user has some scaling. It's up to the user to pass the right matrix (that is, the inverse transpose matrix of the initial transformation in case there's some scaling in the initial matrix).
