### ISSUE TITLE
Two scenes were created by babylon. In the first scene, add a ball and add a gizmoManager. In the second scene, add a cube and add a gizmoManager. You will find the gizmo of the two scenes, They can only be rendered in the first scene

### ISSUE THREAD

**Issue by hpyou** [BabylonJS/Babylon.js#14437]
**Repro**
run the code 
```
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>Babylon.js Example</title>
    <script src="https://cdn.babylonjs.com/babylon.js"></script>
</head>
<body>
<button id="toggleSceneButton">Toggle Scene</button>
<canvas id="renderCanvas" style="width: 100%;height:100%;"></canvas>
<script>
    var canvas = document.getElementById("renderCanvas");
    var engine = new BABYLON.Engine(canvas, true);
    var scene1 = createScene1(engine);
    var scene2 = createScene2(engine)

    engine.runRenderLoop(function () {
        scene1.render();
    });

    window.addEventListener("resize", function () {
        engine.resize();
    });

    var currentScene = 1;
    var toggleSceneButton = document.getElementById("toggleSceneButton");
    toggleSceneButton.addEventListener("click", function () {
        if (currentScene === 1) {
            scene1.detachControl(canvas);
            scene2.attachControl(canvas, true);
            currentScene = 2;
            engine.stopRenderLoop();
            engine.runRenderLoop(function () {
                scene2.render();
            });
        } else {
            scene2.detachControl(canvas);
            scene1.attachControl(canvas, true);
            currentScene = 1;
            engine.stopRenderLoop();
            engine.runRenderLoop(function () {
                scene1.render();
            });
        }
    });

    function createScene1(engine) {
        var scene = new BABYLON.Scene(engine);
        var camera = new BABYLON.ArcRotateCamera("camera1", 0, 0, 10, new BABYLON.Vector3(0, 0, 0), scene);
        camera.attachControl(canvas, true);
        var sphere = BABYLON.MeshBuilder.CreateSphere("sphere1", {diameter: 2}, scene);
        var gizmoManager = createGizmoManager(scene);
        gizmoManager.attachToMesh(sphere);
        return scene;
    }

    function createScene2(engine) {
        var scene = new BABYLON.Scene(engine);
        var camera = new BABYLON.ArcRotateCamera("camera2", 0, 0, 10, new BABYLON.Vector3(0, 0, 0), scene);
        camera.attachControl(canvas, true);
        var box = BABYLON.MeshBuilder.CreateBox("box1", {size: 2}, scene);
        box.position = new BABYLON.Vector3(2, 2, 2);
        var gizmoManager = createGizmoManager(scene);
        gizmoManager.attachToMesh(box);
        return scene;
    }

    function createGizmoManager(scene) {
        const gizmoManager = new BABYLON.GizmoManager(scene);
        gizmoManager.positionGizmoEnabled = true;
        gizmoManager.rotationGizmoEnabled = true;
        gizmoManager.scaleGizmoEnabled = true;
        gizmoManager.gizmos.scaleGizmo.scaleRatio = 0.7;
        return gizmoManager;
    }
</script>
</body>
</html>
```

- Expected result: the scene2's gizmoManager need render in scene2.
- Current result: the scene2's gizmoManager render in scene1.

**Screenshots**
![image](https://github.com/BabylonJS/Babylon.js/assets/15992591/88b46e07-4f06-4dc7-afdc-de671e2a0684)

**Desktop (please complete the following information):**
 - OS: window10
 - Browser: chrome
 - Version: latest

**Additional context**
I use babylon 5.52.0, and the latest version will also have this problem.

**Comment by carolhmj** [comment]
Hello! As per our bug report template, please use the forum: https://forum.babylonjs.com/c/bugs/8 to discuss bugs before opening an issue on Github.

**Comment by hpyou** [comment]
> Hello! As per our bug report template, please use the forum: https://forum.babylonjs.com/c/bugs/8 to discuss bugs before opening an issue on Github.

ok，thanks！

**Comment by hpyou** [comment]
> Hello! As per our bug report template, please use the forum: https://forum.babylonjs.com/c/bugs/8 to discuss bugs before opening an issue on Github.

I got the solution in https://forum.babylonjs.com/t/two-scenes-were-created-by-babylon-in-the-first-scene-add-a-ball-and-add-a-gizmomanager-in-the-second-scene-add-a-cube-and-add-a-gizmomanager-you-will-find-the-gizmo-of-the-two-scenes-they-can-only-be-rendered-in-the-first-scene/45024

```
var utilLayer = new BABYLON.UtilityLayerRenderer(scene);
utilLayer.setRenderCamera(camera);
const gizmoManager = new BABYLON.GizmoManager(scene, 1, utilLayer);
```

I thought of using UtilityLayerRenderer, but the last two parameters are not in the constructor of gizmoManager.So I think there may be something wrong with this document
https://endoc.cnbabylon.com/api/classes/babylon.gizmomanager.html
![image](https://github.com/BabylonJS/Babylon.js/assets/15992591/8007e3ac-7b13-4590-9b9a-8ccacdf5a8eb)

**Comment by Popov72** [comment]
Your link to the documentation is not up to date:

https://doc.babylonjs.com/typedoc/classes/BABYLON.GizmoManager#constructor

**Comment by hpyou** [comment]
> Your link to the documentation is not up to date:
> 
> https://doc.babylonjs.com/typedoc/classes/BABYLON.GizmoManager#constructor

ok, get it , thank you!
