### ISSUE TITLE
Flipped faces in glTF export

### ISSUE THREAD

**Issue by HoferMarkus** [BabylonJS/Babylon.js#14445]
**Repro**
- Bug repro on [playground](https://playground.babylonjs.com/#ZW1D6T):
- Expected result: model gets exported correctly, as it was the case pre version 6.7.0
![276497406-0543fc82-c68f-4308-b059-17f0b744dc25](https://github.com/BabylonJS/Babylon.js/assets/60605717/a25cd8ea-e3c1-4e1d-80d3-d55c538d1eb5)
- Current result: faces are flipped in glTF export
![276497111-4974a246-4fc3-4304-aa2b-6edc83b229f9](https://github.com/BabylonJS/Babylon.js/assets/60605717/3f3ca110-1ecc-43e7-afc6-d3c9c27fb3ac)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 118.0.5993.89
 ...issue is independent of browser and OS

**Additional context**
Issue got introduced in this [PR](https://github.com/BabylonJS/Babylon.js/pull/13909).

**Comment by bghgary** [comment]
A couple of notes:
- This model has skins even though it serves no purpose AFAICT
- This model has root skeleton nodes with a negative Y scale.

**Comment by HoferMarkus** [comment]
@bghgary I don't know if it helps but it also happens for a very simple model like this:
![image](https://github.com/BabylonJS/Babylon.js/assets/60605717/a2892747-8a4d-459c-9c80-ac5115e7c811)

I updated the [PG example](https://playground.babylonjs.com/#ZW1D6T#5).

**Comment by bghgary** [comment]
Thanks, I already reduced your other model to a single mesh. 😏 

This turned out to be an issue with the `.babylon` loading code. It will be fixed shortly.
