### ISSUE TITLE
Shader code is not compatible in webgpu mode

### ISSUE THREAD

**Issue by rookiewxy** [BabylonJS/Babylon.js#14446]
float Get3DNoise(vec3 pos) 
{
    float p = floor(pos.z);
    float f = pos.z - p;
    
    const float invNoiseRes = 1.0 / 64.0;
    
    float zStretch = 17.0 * invNoiseRes;
    
    vec2 coord = pos.xy * invNoiseRes + (p * zStretch);
    
    vec2 noise = vec2(texture(iChannel0, coord).x, texture(iChannel0, coord + zStretch).x);
    
    return mix(noise.x, noise.y, f);
}

example url:
https://playground.babylonjs.com/#MSV6UG#18

**Comment by Popov72** [comment]
As indicated in the template, please first discuss the issue in [our forums](https://forum.babylonjs.com/) so that it can benefit the whole community.
