### ISSUE TITLE
WebGPU support

### ISSUE THREAD

**Issue by ZGltYQ** [BabylonJS/Babylon.js#14515]
Hi, could you please add WebGPU support ?

**Comment by sebavan** [comment]
It is already in https://doc.babylonjs.com/setup/support/webGPU

**Comment by ZGltYQ** [comment]
> It is already in https://doc.babylonjs.com/setup/support/webGPU

Yes, but when i try to use WebGPUEngine in editor it doesn't work because current version of electron doesn't support webGPU

**Comment by sebavan** [comment]
This would be an electron feature request in this case or an editor one when the support will be available

**Comment by ZGltYQ** [comment]
> This would be an electron feature request in this case or an editor one when the support will be available

Support already available but in version 14+ (Babylon Editor use 13.6.6)
