### ISSUE TITLE
Bounding box hints (tooltips)

### ISSUE THREAD

**Issue by FluorescentHallucinogen** [BabylonJS/Babylon.js#14555]
It would be very nice to have optional hints (tooltips/labels) for bounding box while rotating, scaling, and translating objects:

https://github.com/BabylonJS/Babylon.js/assets/7892779/c8834749-0727-48d2-b513-cafe4e24cf71

Values in tooltips while scaling can be not only relative (in percentages), but also absolute (in meters).

https://user-images.githubusercontent.com/7892779/216831883-8211c3ff-3d96-4fb1-bd82-583cb3e3eb3c.mp4

**Comment by sebavan** [comment]
As the template mentions, lets discuss the feature first on the forum: 

![image](https://github.com/BabylonJS/Babylon.js/assets/16655165/8b63ce1a-a588-46a7-a0d1-6ce3e8093069)

Let me close the Request for now and lets reopen once everyone agree there. Don't take it the wrong way, I love the feature and it sounds pretty reasonable but there might be some gotchas I am not aware of and we are using the forum to centralize those.
