### ISSUE TITLE
skeleton.bone rendering abnormal by using Space.WORLD

### ISSUE THREAD

**Issue by lukexxl** [BabylonJS/Babylon.js#14619]
https://playground.babylonjs.com/#D4ZZ8#8 instance, starting from this instance, there are rendering problems in using Space.WORLD for bone rotation, but adding Debug.SkeletonViewer can enable normal rendering.

**Comment by sebavan** [comment]
As the template mentions 
![image](https://github.com/BabylonJS/Babylon.js/assets/16655165/1d914ec8-b8c2-4587-baff-6767aea66c51)

Would be great to discuss the issue on the forum first, let s reopen once validated there.

cc @Popov72

**Comment by Popov72** [comment]
You have to call `skeleton.computeAbsoluteMatrices()` first because the `Space.WORLD` mode relies on the absolute matrices being up to date.
