### ISSUE TITLE
Exporting node geometry from inspector is producing inconsistent winding order

### ISSUE THREAD

**Issue by PatrickRyanMS** [BabylonJS/Babylon.js#14618]
When exporting node geometry to glTF, the resulting mesh has inconsistent winding order between meshes. The original node geometry in the PG looks like this:

![image](https://github.com/BabylonJS/Babylon.js/assets/31326855/043cb0a8-5567-4d0c-805e-fed18ef0d971)

The exported mesh has an inverted winding order for the ground mesh where the scene elements retain the original winding order.

![image](https://github.com/BabylonJS/Babylon.js/assets/31326855/4dcd4e3d-1ea1-4b6c-935a-19156d921b95)

![image](https://github.com/BabylonJS/Babylon.js/assets/31326855/51907fd1-1d8d-4806-9c71-11186970ea22)

Repro scene: https://playground.babylonjs.com/#18WTCK

Sample exported mesh: [ngeExport.zip](https://github.com/BabylonJS/Babylon.js/files/13679283/ngeExport.zip)

**Comment by bghgary** [comment]
This one is because the ground is using a node material and the code doesn't handle this correctly. I have a local fix but node materials won't be able to export and thus it will use the glTF default material.
