### ISSUE TITLE
Strange issue with intersections

### ISSUE THREAD

**Issue by jumpjack** [BabylonJS/Babylon.js#14630]
https://playground.babylonjs.com/#VI1NQB#18

In case a rotating object has a parent, the result of  CSG intersect() function gets weird (also applying same parent to resulting section):

No parent:

![image](https://github.com/BabylonJS/Babylon.js/assets/1620953/c0958b96-e925-49a5-9344-8bfcbd0ee483)

Parent:

![image](https://github.com/BabylonJS/Babylon.js/assets/1620953/e81958f5-7760-4b4a-9270-a92dce7bd0a1)

![image](https://github.com/BabylonJS/Babylon.js/assets/1620953/7a397dca-a088-469b-8c0e-53ef4a841ea0)

**Comment by Popov72** [comment]
As stated in the template, please discuss it on the forum first.

Anyway, the problem is that you should not manipulate `_worldMatrix` yourself: just remove the `blueBox._worldMatrix = sphereL._worldMatrix` line.
