### ISSUE TITLE
Adding Web Browser Support in 3d for babylon

### ISSUE THREAD

**Issue by shashi0d** [BabylonJS/Babylon.js#14641]
We only accept feature requests that are discussed on the BabylonJS forum

**Is your feature request related to a problem? Please describe.**
I'm trying to create a VR enabled 3d Experience Game where there is a need for me to show a browser inside the 3d world which is VR interactable

**Describe the solution you'd like**
As How Unreal has provided a web browser plugin it would be nice if Babylon can also do the same
**Discussion**
You must provide a link to the forum post where the initial discussion happened
https://forum.babylonjs.com/t/ar-vr-browser-inside-scene-and-interaction-with-browser-content/5891/5
https://forum.babylonjs.com/t/embed-web-page-to-3d-mesh-in-babylonjs/9060

**Comment by Popov72** [comment]
Maybe this new extension can help you (I don't know if it works in XR, though):

https://github.com/BabylonJS/Extensions/tree/master/HtmlMesh

**Comment by sebavan** [comment]
Closing as I do not think it is possible in webxr support which is not there yet. Cc @RaananW
