### ISSUE TITLE
LoadAssetContainer parameter data can directly receive BABYLON. SceneSerializer. Serialize serialized json, not just a json string

### ISSUE THREAD

**Issue by dengbupapapa** [BabylonJS/Babylon.js#14654]
https://github.com/BabylonJS/Babylon.js/blob/a0801fab7013bef5712e84b43ced0d77a9d34cb9/packages/dev/core/src/Loading/Plugins/babylonFileLoader.ts#L153

**Comment by sebavan** [comment]
Please use our forum to discuss any feature request before login them on Github as the template mentions.

Sounds like a good idea :-)
