### ISSUE TITLE
setTimeStep method not working with Havok

### ISSUE THREAD

**Issue by alparslanahmed** [BabylonJS/Babylon.js#14776]
**Repro**
- Bug repro on [playground](https://playground.babylonjs.com/#WCRLHB#4): https://playground.babylonjs.com/#WCRLHB#4
- Expected result: Cube to fall down way more faster like [this](https://playground.babylonjs.com/#WCRLHB#1) example with Ammo
- Current result: Cube falls at normal speed **setTimeStep** function doesnt have any effect.

**Desktop (please complete the following information):**
 - OS: Pop OS 
 - Browser: Chrome
 - Version: 6.42.0

**Comment by bghgary** [comment]
Fixed.

**Comment by michael-meetkai** [comment]
Hey! @bghgary @alparslanahmed I'm having issues with setTimeStep, I'm using @babylonjs/havok 1.3.4, having trouble to track release notes for that package, could u tell if this fix is already live or point me to release notes ?
Thanks!!
