### ISSUE TITLE
Add function to control sleep activation mode for havok physics

### ISSUE THREAD

**Issue by FlorentMasson** [BabylonJS/Babylon.js#14810]
**Is your feature request related to a problem? Please describe.**
There is no function to force a body to be always active. The issue I had is that COLLISION_CONTINUED events stop being dispatched once a body is going to sleep mode, which is not desirable for some bodies like a player character (I use that for floor detection)

**Describe the solution you'd like**
Havok SetActivationControl() function could be made available through the PhysicsBody class.

This is the workaround I had to implement.
```
function setBodyAlwaysActive(body: PhysicsBody) {
  havok.HP_Body_SetActivationControl(body._pluginData.hpBodyId, havok['ActivationControl'].ALWAYS_ACTIVE);
}
```
I had also found previously a quirkier workaround which was to apply a zero-vector impulse to the body every frame.

**Discussion**
[A topic with code for SetActionControl function](https://forum.babylonjs.com/t/about-havok-feature/40253/31)
[A topic where I found out about applying a zero impulse](https://forum.babylonjs.com/t/havok-wake-up-from-sleep-mode/40852/5)

**Comment by CedricGuillemet** [comment]
This looks like a nice addition but make the method more generic. Use the same name as Havok with an abstraction on the enum and it should be fine.

**Comment by CedricGuillemet** [comment]
@FlorentMasson Can you open a PR for this feature?
