### ISSUE TITLE
GLTF2Export - export to GLB flickering

### ISSUE THREAD

**Issue by acerov** [BabylonJS/Babylon.js#14814]
Hi all,

if scene is exported to glb using GLTF2Export materials zOffset is not preserved, it is reset to 0, as a consequence we have flickering (z-fighting).

Thank you for excelent library.

**Comment by bghgary** [comment]
`zOffset` is not supported in glTF, so there is no way to support this without a custom extension. We can perhaps log a warning though.

**Comment by acerov** [comment]
> `zOffset` is not supported in glTF, so there is no way to support this without a custom extension. We can perhaps log a warning though.

Ok, is there a workaround because otherwise GLB format works ok for me, but after saving I need to reopen scene/model.

I tried also with babylon format, exporting directly from Inspector but it fails to reload, it throws error "Unable to load from file:scene.babylon: loadAssets of unknown Lights: Name: light, type: Hemispheric ..."

What file format or method is reliable way to save scene and reload it? Thnx.

**Comment by bghgary** [comment]
That sounds like a bug if saving to `.babylon` doesn't load. Please send a repro. It might also be good to move this discussion to the [forum](https://forum.babylonjs.com/).

**Comment by thomlucc** [comment]
Closing as the discussion can continue on the forum
