### ISSUE TITLE
[NGE/NME] - UI Value Copy Bug

### ISSUE THREAD

**Issue by PirateJC** [BabylonJS/Babylon.js#14822]
When you click on a Vector node and edit its properties, then immediately click on another vector node, the values from the first node are copied onto the second node. This is not desired behavior.

![image](https://github.com/BabylonJS/Babylon.js/assets/1668182/85870162-2ab1-4aa8-95f0-965267be2702)

![image](https://github.com/BabylonJS/Babylon.js/assets/1668182/fce1273b-34b2-4455-9d58-77924d32496c)

![image](https://github.com/BabylonJS/Babylon.js/assets/1668182/ad9d6b46-632f-4ba4-9f35-c778646d1a7f)

**Comment by AfirstsAi** [comment]
Transition action as a new task must be done
