### ISSUE TITLE
[NGE] - Allow the Set Colors node to accept Vector 3s as an input

### ISSUE THREAD

**Issue by PirateJC** [BabylonJS/Babylon.js#14823]
Currently, the "Set Colors" node only accepts a vector 4. This automatically sets the mesh to transparent. Ideally, the "Set Colors" node should also be able to accept a vector 3 as an input, not forcing the user to use the alpha channel.

![image](https://github.com/BabylonJS/Babylon.js/assets/1668182/09804cc2-8a87-4684-9e5b-c11ee1e9b990)

**Comment by AfirstsAi** [comment]
We need to make a relationship between the vectors
