### ISSUE TITLE
SolidParticleSystem is not empty when addShape() is used with nb parameter of 0

### ISSUE THREAD

**Issue by JohnGrime** [BabylonJS/Babylon.js#14837]
**Use Github issues ONLY for bugs validated on the forum first!**

I could not find this issue discussed on the forum.

When creating a SolidParticleSystem, calling [addShape()](https://doc.babylonjs.com/typedoc/classes/BABYLON.SolidParticleSystem#addShape) with an `nb` param of 0 does not result in an empty mesh - there's a single particle in there as also reflected by the `nbParticles` attribute of the SPS.

**Repro**

https://playground.babylonjs.com/#W6PNJ7#1

**Screenshots**

See "Repro" above.

**Desktop (please complete the following information):**

 - OS: windows, macOS, probably others.
 - Browser: Safari, probably others.

**Additional context**

Calling addShape() with This may seem like a strange thing to do, but I'd like to always have a "valid" SPS / mesh in my data even when the number of particles contained in the SPS is zero.

**Comment by sebavan** [comment]
We only use the forum for validated issue on the forum first. it would be great if you could move the conversation there first: https://forum.babylonjs.com/

The system has unfortunately not been build like this mostly for perf reasons I believe. Basically every meshes has an extra cost associated to it and if you have no particles, the shape would not even be stored and therefor buildMesh() does "create" a triangle to  return a none empty mesh I guess.

Let s discuss it more on the forum to better understand the use case. Closing for now.
