### ISSUE TITLE
Can't control blend mode of NGE preview window

### ISSUE THREAD

**Issue by PatrickRyanMS** [BabylonJS/Babylon.js#14842]
If setting vertex colors on a mesh and then displaying vertex color in the preview window, we have no way to toggle the blend mode of the render. We need to pass a Color4, and in doing so the preview window assumes an alpha blend, even if the user intends to render the mesh as opaque. This makes viewing meshes using vertex color hard to understand, even when using other render modes like matcap or texture. It seems we need a control somewhere on the preview window to render the material as either an alpha blend material or an opaque material.

![image](https://github.com/BabylonJS/Babylon.js/assets/31326855/6e3e7588-a370-40d1-9136-d347250f3075)

![image](https://github.com/BabylonJS/Babylon.js/assets/31326855/3c98c4c2-ba5e-42fd-a62d-7ae38c3ead6e)

![image](https://github.com/BabylonJS/Babylon.js/assets/31326855/0ac398cf-c712-45a3-9779-18301e6b2a5b)

**Comment by deltakosh** [comment]
You can plug the rgb channel into the SetColors and it will disable the transparency
