### ISSUE TITLE
Execution count and call count displaying too many times on vector converter block

### ISSUE THREAD

**Issue by PatrickRyanMS** [BabylonJS/Babylon.js#14843]
The execution count and call count on the vector converter block when it is connected to a SetXXX block repeats several times in the inspector. Sometimes there is a single pair that has the correct information and the rest at 0 and other times there are several pairs listed with correct value as seen below:

Repro: https://nge.babylonjs.com/#MU63TT

![image](https://github.com/BabylonJS/Babylon.js/assets/31326855/ee4e651b-c210-4ef7-a2ba-efd4984f4b07)

![image](https://github.com/BabylonJS/Babylon.js/assets/31326855/f7ffc15e-610d-4f11-801a-6cbef738dc15)

**Comment by deltakosh** [comment]
I was not able to repro but I added a change on the display so we now which output is what:
![image](https://github.com/BabylonJS/Babylon.js/assets/1306056/f346b28e-a15e-41a7-9704-2b3f10ede28b)

so we can see that only the connected get calls (as expected)

@PatrickRyanMS do you have a way to repro the issue? I was not able to get in the same state as you
