### ISSUE TITLE
Add Save/Load for materials in the Inspector

### ISSUE THREAD

**Issue by wright-luda** [BabylonJS/Babylon.js#14874]
Our artists frequently tweak materials directly in-game using the Inspector, and it's a great workflow for perfecting materials at runtime! But the artists have to manually send material settings to the engineers team to implement once they have something that they like.

To improve the workflow, we'd like to be able to save and load materials as JSON right from within the Inspector, so that an artist can save their settings to a JSON file that can be checked into Git directly. This would work exactly the way that saving/loading ParticleSystems works.

Also, would be great to add ultra-simple instructions for how to load materials in the Importing Assets and/orMaterials section of the documentation. I'm a designer and novice coder, and I'm finding it more difficult than I thought it would be to do this.

Link to BabylonJS forum thread:

https://forum.babylonjs.com/t/save-material-as-json-from-inspector/48703

**Comment by thomlucc** [comment]
https://forum.babylonjs.com/t/add-save-load-for-materials-in-the-inspector/52130
