### ISSUE TITLE
Posterize block in NGE results in NaN

### ISSUE THREAD

**Issue by PatrickRyanMS** [BabylonJS/Babylon.js#14892]
When using a posterize node in NGE, the output is resulting in NaN. In the repro below, bypassing the posterize node will show that the colors derived from position work, then when posterizing that input, the result is NaN. 
- repro: [https://nge.babylonjs.com/#WP45S8](https://nge.babylonjs.com/#WP45S8)

![image](https://github.com/BabylonJS/Babylon.js/assets/31326855/bc7783f3-57f7-42b0-8a2a-ec73c0dfd4ea)

**Comment by deltakosh** [comment]
Fixed
