### ISSUE TITLE
Audio not working on AVP in immersive mode

### ISSUE THREAD

**Issue by docEdub** [BabylonJS/Babylon.js#14927]
**Repro**
https://playground.babylonjs.com/#KR5CRQ#17:
- Audio should work in immersive mode (bells should ring when clicked and birds should be singing in background)
- Currently, audio only works in non-immersive mode.
- After clicking on a few bells in immersive mode, exiting immersive mode causes all the clicked bells to ring at the same time.

**Comment by deltakosh** [comment]
Up as this is a bug it should be prioritized

**Comment by docEdub** [comment]
I looked into this and found Safari is suspending the audio context when entering immersive mode. This occurs with any XR experience that uses the Web Audio API, so it's not a Babylon-specific issue.

I was able to resume the audio context from the JS console while debugging in immersive mode, so we should be able to do the same in the Babylon audio engine.

Note that the Quest browser doesn't have this issue and won't be affected by repeated calls to `AudioContext.resume()` while it's already running since they will just be ignored, so no worries there for a potential workaround.

I'll discuss it with @RaananW to see what he thinks about addressing this AVP Safari behavior/feature.

**Comment by matthargett** [comment]
Thanks for digging into this and fixing it. We noticed this a few months ago in our BabylonJS WebXR app, but hadn't gotten around to investigating since most of our ideal customers are using Pico 4s (and that browser doesn't have this problem).
