### ISSUE TITLE
Missing Havok Physics World Speed Limit Set/Get Functions

### ISSUE THREAD

**Issue by nyan-left** [BabylonJS/Babylon.js#14965]
### Issue 

The `havok.HP_World_SetSpeedLimit` function is undefined in Havok Physics version 1.3.2, despite a type being defined for it. 
Additionally, there is no getter to retrieve the current world speed limit.

### Expected
Expected result: The `havok.HP_World_SetSpeedLimit` function should be properly exported and available for use. There should also be a corresponding getter function to retrieve the current world speed limit value.

### Current 
Current result: The `havok.HP_World_SetSpeedLimit` function is undefined and unavailable for use. There is no built-in way to get the current world speed limit.

### Additional context

This issue was originally brought up and discussed on the Babylon.js forum:
https://forum.babylonjs.com/t/how-to-enable-faster-moving-rigidbodies-in-havok/40631/13?u=nyan-left

The missing bindings for setting and getting the Havok world speed limit were noticed after an update to version 1.3.2. In previous versions, workarounds using direct memory access were provided, but a proper API for this functionality is desired.

It would be greatly appreciated if the function could be properly exported, and a corresponding getter function added as well. This will allow developers to adjust the world speed limit in a supported manner, without resorting to memory hacks.

Thank you for looking into this!

**Comment by CedricGuillemet** [comment]
https://github.com/BabylonJS/Babylon.js/pull/15158
