### ISSUE TITLE
[Physics]  would like to have motorized constraints added.

### ISSUE THREAD

**Issue by Octo8080X** [BabylonJS/Babylon.js#14979]
We only accept feature requests that are discussed on the BabylonJS forum

**Is your feature request related to a problem? Please describe.**

Motor is introduced in Phicisc v1(Cannon, Ammo, Oimo), but not in Phicisc v2(havok).
I want this very much.

This requires us to use techniques when moving things around in physical space. For example, rotation.

https://forum.babylonjs.com/t/havok-motorized-constraints/40415
https://forum.babylonjs.com/t/want-to-reproduce-the-movement-like-a-motor/47801
https://forum.babylonjs.com/t/havok-physics-on-walk/45184
https://forum.babylonjs.com/t/how-to-rotate-with-physics-applied-and-with-parent-child-relationship/48008/8

**Describe the solution you'd like**

Added `setMotor` method to each constraint.
Introduction of get~~ for convenient use of the process of calculating the determination of the motor motion, such as the amount of rotation, distance to the connected object, etc.

If you recommend to use 6DOF constraints to realize what is equivalent to Motor, we strongly suggest to improve the documentation.

**Discussion**
You must provide a link to the forum post where the initial discussion happened

https://forum.babylonjs.com/t/havok-motorized-constraints/40415/15

Thank you in advance. Best regards.

**Comment by sebavan** [comment]
@Octo8080X Could you check the current status on the forum first so that we can reopen the issue with all the relevant info ?

We only keep feature request that has been fully reviewed on the forum first and I am really wondering whether things have changed since May 2023 regarding motors
