### ISSUE TITLE
Shadows look weird

### ISSUE THREAD

**Issue by quangtri3111996** [BabylonJS/Babylon.js#14971]
I am working BabylonJS and RectJS, when I add a HemisphereLight (0, -1, 0) and a directionalLight with position is (0,  10, -20), and direction is (0, -1, 1) the shadows are not correct (attached image).

Please help me. Thanks!

<img width="557" alt="shadow" src="https://github.com/BabylonJS/Babylon.js/assets/24564957/73eb7662-8c28-4d2a-a0b9-84fe0b00da2e">

**Comment by dennemark** [comment]
Please check out the docs: https://doc.babylonjs.com/features/featuresDeepDive/lights/shadows#troubleshooting
There are lots of explanations of how the shadow generator works. You might be especially interested in the bias value.

I would recommend using babylon inspector. When you click on your directional light you should be able to access all properties of your shadow generator and you can tune it.

**Comment by Popov72** [comment]
Also, as stated in the template, you should refer to the [forum](https://forum.babylonjs.com/) first and continue the discussion there.

Closing the issue.
