### ISSUE TITLE
Cannot build. Missing ImageEncodeOptions, VideoFrame, etc.

### ISSUE THREAD

**Issue by fudom** [BabylonJS/Babylon.js#14976]
Cannot build on Angular 14 + TypeScript 4.7 with Babylon 7 or 6. Workaround: Use version 5 of Babylon.

Missing types:

- ImageEncodeOptions
- OffscreenRenderingContextId
- OffscreenRenderingContext
- VideoFrame

https://doc.babylonjs.com/setup/frameworkPackages/es6Support

Upgrading Angular and/or Typescript is currently impossible. It's not just a hello world project. ^^

Is there a compatibility info? What version is depending on what dependencies. And how to handle it? Not sure, but I also could just define the missing types as any-type. Or babylon could support these type fallbacks/polyfill. It's great that babylon comes with types. But it's sad that TypeScript (indirect) types are blocking the use. Since types have no effect on runtime. It's just the d.ts behind in node_modules of babylon. At least we could provide some docs and how to handle this. I just wondering how to avoid that.

**Comment by sebavan** [comment]
cc @RaananW

**Comment by RaananW** [comment]
Those classes require a newer version of typescript. It's that possible for your project?

**Comment by RaananW** [comment]
Adding the types is more than possible, we can look into that
