### ISSUE TITLE
Internal types exported in definition types.

### ISSUE THREAD

**Issue by damil42** [BabylonJS/Babylon.js#14980]
Is it intended to make the underscored internal types available in definition file? See screenshot below.

![screenshot](https://github.com/BabylonJS/Babylon.js/assets/126908176/22c0ee79-e111-47ca-a0dd-bd401cc12e29)

Why not using access modifier `private` and `protected`? Or tell the types exporter to ignore types with doc comments including `internal` tag. I'm just asking because my autocomplete (IntelliSense suggestions) is flooded with these internal types.

`@babylonjs/core: 7.2.1`

**Comment by sebavan** [comment]
cc @RaananW 

Please use out forum first https://forum.babylonjs.com/ as the issue template mentions.
