### ISSUE TITLE
scene.ambientColor does not work

### ISSUE THREAD

**Issue by damil42** [BabylonJS/Babylon.js#14981]
I wanted to use ambientColor to lighten the dark/black shadows a bit. But it does not work.

[Playground](https://playground.babylonjs.com/#N6YNFM)

For testing I just set the red color. But nope, nothing changes.

```ts
scene.ambientColor = new BABYLON.Color3(2, 0, 0);
```

<img src="https://github.com/BabylonJS/Babylon.js/assets/126908176/88359831-4ea5-4776-947c-b38c8f48d077" width="300" />

Version 7.2.1 

I expected something like in other engines like Godot:

<img src="https://github.com/BabylonJS/Babylon.js/assets/126908176/2371789e-7810-4c5d-b3f5-1813506b491b" width="300" />

In Godot I change the ambient light color in world enviroments.

In Babylon you can use the HemisphericLight for ambient light. But it's similar like a DirectionalLight. It's not a real ambient light because it comes from one side. I want an overall light from none direction. Just lighten the scene and the shadows and farside of objects.

**Comment by sebavan** [comment]
Please use the forum first as the template mentions.

Ambient needs to be enabled on both the scene and materials: https://playground.babylonjs.com/#N6YNFM#1 both will be multiplied against each other.
