### ISSUE TITLE
GLB Import Not Displaying in BabylonJS Sandbox

### ISSUE THREAD

**Issue by zhy437488627** [BabylonJS/Babylon.js#15021]
Issue Description
When importing a GLB file into the BabylonJS Sandbox, the model no longer displays. This issue did not occur previously and may have started after a recent update.

Steps to Reproduce
Navigate to the BabylonJS Sandbox.
Attempt to import a GLB file.
Observe that the model does not display as expected.
Expected Behavior
The GLB file should be displayed correctly in the Sandbox.

Actual Behavior
The GLB file does not display after import.

Possible Solution
This issue might be related to a recent update. Reverting to an earlier version could potentially resolve the problem.

**Comment by josephdave** [comment]
Same thing is happening to me, tested in diferent browsers and configurations

**Comment by deltakosh** [comment]
Seems to work for me
Please provide a repro in the PG (forum.babylonjs.com)
