### ISSUE TITLE
7.4.0 and Custom Procedural Textures

### ISSUE THREAD

**Issue by Mosferator** [BabylonJS/Babylon.js#15030]
They worked just fine with 7.3.0 and the previous versions.
With the current 7.4.0 the Custom Procedural Textures crash the app.
The console error is: `Uncaught Error: loadFileInjection is not defined`
Example: https://playground.babylonjs.com/#24C4KC#51

**Comment by RaananW** [comment]
> They worked just fine with 7.3.0 and the previous versions. With the current 7.4.0 the Custom Procedural Textures crash the app. The console error is: `Uncaught Error: loadFileInjection is not defined` Example: https://playground.babylonjs.com/#24C4KC#51

Will be fixed here - https://github.com/BabylonJS/Babylon.js/pull/15032

Thanks for reporting!
