### ISSUE TITLE
Improve GaussianSplatting for VR

### ISSUE THREAD

**Issue by CedricGuillemet** [BabylonJS/Babylon.js#15109]
Potential improvement for rendering quality and Gaussian Splatting.
See  https://forum.babylonjs.com/t/gaussian-splats-rotate-incorrectly-in-vr/50256/41

Current quality:

![image](https://github.com/BabylonJS/Babylon.js/assets/1312968/a78d5306-0e38-47bb-9022-9a1669c0886d)

potential improvement:

![image](https://github.com/BabylonJS/Babylon.js/assets/1312968/8a5cdb87-5fd0-49e8-9cff-04b9101877d6)

I believe it's a small fix related to viewport and focal computation. I could find a fix that worked with a VR rig locally but it doesn't work on real device (no idea why).

Check this as a starting point:

https://github.com/BabylonJS/Babylon.js/blob/bf55ce26227a4fb5285e817daeb8848095d996b5/packages/dev/core/src/Materials/GaussianSplatting/gaussianSplattingMaterial.ts#L219

**Comment by CedricGuillemet** [comment]
with https://playground.babylonjs.com/#45KYTJ#44
changing the fov from 1.6 to 2.2 helps having better rendering.
a high value results in smaller splats up to a single point.

**Comment by RaananW** [comment]
This should also be checked in VR headsets, as the quality there is better than the first image. I will be happy to help with that
