### ISSUE TITLE
Why is the texture the same after different mesh Settings?

### ISSUE THREAD

**Issue by qq378488249** [BabylonJS/Babylon.js#15157]
**Use Github issues ONLY for bugs validated on the forum first!**

We have a really active forum to help answering questions (https://forum.babylonjs.com/)

**Repro**
- Bug repro on [playground](https://playground.babylonjs.com):
- Expected result: diff material
- Current result: same material

**Screenshots**
![f2285202ba358611e1d5f7231b2b9235](https://github.com/BabylonJS/Babylon.js/assets/13046994/61a18278-15ef-4267-a798-871e87a0420b)

**Desktop (please complete the following information):**
 - OS: [windows]
 - Browser [chrome]
 - Version [7.4.0]

**Additional context**
meshName and img is params, this is my code，please help me
``` js
scene.meshes.forEach((mesh) => {
    if (mesh.material) {
        if (mesh.material.name === meshName) {
            mesh.material.albedoTexture = BABYLON.Texture.CreateFromBase64String(img, scene)
        }
    }
});
```

**Comment by sebavan** [comment]
@qq378488249 can you please use the forum sharing your repro there first ? we only use github once the issue has been validated there first. And most importantly, share a repro there :-)
