### ISSUE TITLE
ios13 mobile browser can't open

### ISSUE THREAD

**Issue by xxf2zq** [BabylonJS/Babylon.js#15155]
BJS - [16:40:43]: Uniforms:  world, view, viewProjection, vEyePosition, vLightsType, vFogInfos, vFogColor, pointSize, vClipPlane, vClipPlane2, vClipPlane3, vClipPlane4, vClipPlane5, vClipPlane6, mBones, vPrimaryColor, vPrimaryColorShadow, vReflectionInfos, reflectionMatrix, vReflectionMicrosurfaceInfos, fFovMultiplier, shadowLevel, alpha, vBackgroundCenter, vReflectionControl, vDiffuseInfos, diffuseMatrix, vLightData0, vLightDiffuse0, vLightSpecular0, vLightDirection0, vLightFalloff0, vLightGround0, lightMatrix0, shadowsInfo0, depthValues0, viewFrustumZ0, cascadeBlendFactor0, lightSizeUVCorrection0, depthCorrection0, penumbraDarkness0, frustumLengths0, vLightData1, vLightDiffuse1, vLightSpecular1, vLightDirection1, vLightFalloff1, vLightGround1, lightMatrix1, shadowsInfo1, depthValues1, viewFrustumZ1, cascadeBlendFactor1, lightSizeUVCorrection1, depthCorrection1, penumbraDarkness1, frustumLengths1, diffuseSampler, reflectionSampler, reflectionSamplerLow, reflectionSamplerHigh, shadowSampler0, depthSampler0, shadowSampler1, depthSampler1

**Comment by RaananW** [comment]
As kindly asked in the issue template, please use the forum (forum.babylonjs.com) to ask these kinds of questions
