### ISSUE TITLE
An error occurs when 'const' is added to the enum export and the tsconfig.json setting is 'isolatedModules': true'.

### ISSUE THREAD

**Issue by wisdomstar94** [BabylonJS/Babylon.js#15238]
# Commit that caused the problem
https://github.com/BabylonJS/Babylon.js/commit/a6dc77a5c1cbab71b4ba8559bb5d8269a0bda811

# Description
1. Suppose that the options for tsconfig.json are. <br />![image](https://github.com/BabylonJS/Babylon.js/assets/93423564/11af26fe-4431-4f0a-9a22-66780ec0d1c8)
2. The typecript displays an error when using the `PhysicsMotionType` enum as follows. <br /> ![image](https://github.com/BabylonJS/Babylon.js/assets/93423564/d7a3cebb-400f-44be-ab18-4a3427d4de3b)

<br />
<br />

I don't think it's a good idea to simply modify the option "isolatedModules" to false, for example, because Next.js, a much-used framework, recommends using the option "isolatedModules" as true.

This is my personal opinion and I would like to hear from the contributors.

**Comment by RaananW** [comment]
let me find a solution for this. This is a typescript types-only issue, as the enums are exported correctly. Will probably need to adjust the types exported.

**Comment by kai-dorschner-twinsity** [comment]
updated to [7.13.2](https://github.com/BabylonJS/Babylon.js/releases/tag/7.13.2), now everything works, great job 😚
