### ISSUE TITLE
Babylon.js V7.14.0 - new BABYLON.Texture() ERROR after BABYLON.Tools.CreateScreenshot()

### ISSUE THREAD

**Issue by msykosch** [BabylonJS/Babylon.js#15253]
After a screenshot has been taken with

BABYLON.Tools.CreateScreenshot()

no more new textures can be created with

new BABYLON.Texture()

because an error occurs

Unhandled Promise Rejection: TypeError: undefined is not an object (evaluating 'h._features.forceBitmapOverHTMLImageElement')
t - texture.ts:536

Babylon.js V7.14.0
All Browsers

**Comment by sebavan** [comment]
Can you share a repro in the playground and first contact us on the forum ?

**Comment by sebavan** [comment]
This seems to be ok : https://playground.babylonjs.com/#750168#99 as well as https://playground.babylonjs.com/#750168#100 so closing until we find a repro.
