### ISSUE TITLE
`collisionInfo` types question

### ISSUE THREAD

**Issue by regnaio** [BabylonJS/Babylon.js#15304]
I may be wrong about the types, though could we replace `collisionInfo: any` with `collisionInfo: IBasePhysicsCollisionEvent`?

[Line 2313](https://github.com/BabylonJS/Babylon.js/blob/master/packages/dev/core/src/Physics/v2/Plugins/havokPlugin.ts#L2313)

[Line 2341](https://github.com/BabylonJS/Babylon.js/blob/master/packages/dev/core/src/Physics/v2/Plugins/havokPlugin.ts#L2341)
May need to use `IPhysicsCollisionEvent` for this case and the one below

[Line 2363](https://github.com/BabylonJS/Babylon.js/blob/master/packages/dev/core/src/Physics/v2/Plugins/havokPlugin.ts#L2363)

**Comment by RaananW** [comment]
cc @CedricGuillemet
