### ISSUE TITLE
Node - should mark _isDirty as false after setting parent?

### ISSUE THREAD

**Issue by gemini133** [BabylonJS/Babylon.js#15313]
https://github.com/BabylonJS/Babylon.js/pull/14888/files#diff-787cbd66cc071b93d893e6770ac7ddda81e4715e3d6ce8adfc977e761b172ecaL241

first, sorry for my igoreance if I say something wrong.
I upgraded babylonjs from 6.33.2 to 7.15.1 and some of my models are broken.
I narrow down to 7.1.0 and find out  it's related to this pr https://github.com/BabylonJS/Babylon.js/pull/14888/ .
more specifically the line "this._isDirty = true;"
my models work if I comment out the line or add "this._isDirty = false;" in the end of function.
I've been battling this for a few hours but no luck. 
due to privacy, I can't provide a mininal repo for you testing...

**Comment by deltakosh** [comment]
Without a minimal repro it will be tough to discuss or validate:(

**Comment by gemini133** [comment]
find out the issue.
I was using 
`mesh.parent = root` to reassign the root node.
right now, I changed to `mesh.setParent(root)`

and it works now. lol

**Comment by deltakosh** [comment]
Please use the forum next time :)
