### ISSUE TITLE
GLTFExporter not working with PBRMaterial

### ISSUE THREAD

**Issue by Hamid293** [BabylonJS/Babylon.js#15320]
I’m creating a simple plane with PBRMaterial on it. I’m applying an albedotexture and setting the unlit property to true. Then I’m using the export to glb option in the inspector to export the scene as a glb model.

It works correctly for StandardMaterial but when I switch it to PBRMaterial it doesn’t export the material/texture the created glb file has no texture.

Bug repro on [playground](https://playground.babylonjs.com/#Q9VZS9#2142)
Discussion on the [forum](https://forum.babylonjs.com/t/gltfexporter-not-working-with-pbrmaterial/52209)

**Comment by sebavan** [comment]
Answered in detail in the forum. This results from the workflow conversion between spec/gloss and metal/rough. Closing for now as there are no perfect ways to convert.
