### ISSUE TITLE
PickWithRay's predicate parameter is invalid

### ISSUE THREAD

**Issue by dalidaliW** [BabylonJS/Babylon.js#15337]
` 
 private _floorRaycast(offsetx: number, offsetz: number, raycastlen: number): BABYLON.Vector3 {
 let raycastFloorPos = new BABYLON.Vector3(this._player?.position.x ?? 0 + offsetx, this._player?.position.y ?? 0 + 0.5, this._player?.position.z ?? 0 + offsetz);
        let ray = new BABYLON.Ray(raycastFloorPos, BABYLON.Vector3.Up().scale(-1), raycastlen, 0.1);
        const t = Date.now()
        let pickMesh = null

        //defined which type of meshes should be pickable
        let cb = (mesh) => {
            console.log(mesh)
            return true
        }
        console.log("start")
        let pick = this._scene.pickWithRay(ray, cb);
        console.log(pick, "pick")
        console.log("end")

    }

this._floorRaycast(0, 0, .6)

 `

BJS - [18:16:20]: Babylon.js v7.9.0 - WebGL2 - Parallel shader compilation

![Uploading image.png…]()

**Comment by dalidaliW** [comment]
![Uploading 微信截图_20240729181903.png…]()

**Comment by dalidaliW** [comment]
![image](https://github.com/user-attachments/assets/77f6495d-0647-46a6-b746-28fc6d4f3b90)

**Comment by sebavan** [comment]
As the template mentioned, can you start the thread on the forum with a repro in the playground ?
