### ISSUE TITLE
CSG subtract Broken

### ISSUE THREAD

**Issue by boggan** [BabylonJS/Babylon.js#15343]
Oy!

I've noticed the CSG Subtract operation not behaving properly with the latest versions. 

before the subtraction was creating a hole in my geometry and generated the internal faces of said hole but now, the geometry used to punch a hole in the geometry is still present and the internal faces are no longer generated.

the code used to generate the hole is as follow: 

```
        const meshToCutCSG: CSG = CSG.FromMesh(meshToCut, true);
        const cuttingTemplateCSG: CSG = CSG.FromMesh(cuttingTemplate, isAbsolute);

        meshToCutCSG.subtractInPlace(cuttingTemplateCSG);
        
        return meshToCutCSG.toMesh(meshToCut.id + " -- cutout", meshToCut.material, scene, true);
```

I've tracked which version of babylonJS this started happening

starting from version 10.0.3 we have a problem
but before it's all good (ie: 10.0.2)

here are visual example of the issue (taken from 6.49.0 vs 7.17.2, I've also offset the geometry primitives to show the parts)

<img width="502" alt="Screenshot 2024-07-30 at 7 50 22 AM" src="https://github.com/user-attachments/assets/13f93534-8f46-4bed-a045-e2a225832f09">

and

<img width="748" alt="Screenshot 2024-07-30 at 7 55 12 AM" src="https://github.com/user-attachments/assets/59c950a3-1ea2-4f34-9013-1e796534e3fb">

if you guys have time to look at this issue, it would be greatly appreciated :)

Thanks!

**Comment by deltakosh** [comment]
Hey there! As we ask on the issue template please use the forum.babylonjs.com for bug reporting:)

**Comment by boggan** [comment]
Ok! sorry about that, missed the info, I'll report it on the forum's page :)

**Comment by deltakosh** [comment]
Much appreciated! A repro in the playground will do wonders as well!
