### ISSUE TITLE
Local Cache Toggle

### ISSUE THREAD

**Issue by ggzola** [BabylonJS/Babylon.js#15354]
**Is your feature request related to a problem? Please describe.**
When making small, frequent changes to the code, the constant saving to the server slows down the local iteration process. Additionally, concerns about potential browser crashes lead to unnecessary frequent saves, interrupting the workflow.

**Describe the solution you'd like**
I would like to see an option for "Local Cache" in the Babylon.js Playground settings. This feature would enable local code changes to be saved without needing to upload them to the server, reducing the frequency of server-based saves. The attached image shows a mock-up of this feature, where the user can toggle "Local Cache" to allow faster, worry-free saving of code changes locally. You could then toggle the option again to perform a refresh.
![image](https://github.com/user-attachments/assets/f8c4d6d6-4021-4075-87bb-4a871fc41687)

**Discussion**
[Enhancing Babylon.js Playground: Local Version Control for Faster Iteration](https://forum.babylonjs.com/t/enhancing-babylon-js-playground-local-version-control-for-faster-iteration/52274)
_Credit to user- qq2315137135_

**Comment by deltakosh** [comment]
Please create a feature request on the forum so users can vote for it:)

**Comment by deltakosh** [comment]
Oh it is already a feature request so no need for more.
