### ISSUE TITLE
Typo in NME shader exporter

### ISSUE THREAD

**Issue by FlorentMasson** [BabylonJS/Babylon.js#15363]
I found this a bit randomly
https://github.com/BabylonJS/Babylon.js/blob/28c0ca45648eab6331644bd5f1f492bd6279e523/packages/dev/core/src/Materials/Node/nodeMaterialBuildState.ts#L151

I think

> this.compilationString = "#if defined(WEBGL2) || **defines**(WEBGPU)\nprecision highp sampler2DArray;\n#endif\n" + this.compilationString;

should be

> this.compilationString = "#if defined(WEBGL2) || **defined**(WEBGPU)\nprecision highp sampler2DArray;\n#endif\n" + this.compilationString;

**Comment by deltakosh** [comment]
nice one!
wanna do a PR?

Also we use the forum for discussion and feedback :)
