### ISSUE TITLE
Provides the ability to natively load 3d tiles resources while making it easy for developers to create digital twin projects with Cesium.

### ISSUE THREAD

**Issue by BraveMomo** [BabylonJS/Babylon.js#15383]
We only accept feature requests that are discussed on the BabylonJS forum

**Is your feature request related to a problem? Please describe.**

The use of 3D engine to develop digital twins in China is very hot, there may be tens of billions of markets in the future, and almost all projects need to be displayed with browsers, Babylon has great potential, but in the Chinese platform, there is very little relevant information, especially the lack of complete sets, zero-based series of videos, I hope you can open some official accounts, release some teaching video collections, in addition, China's digital twin projects, often design a large area, including sites, buildings, such as smart cities, Even including indoor scenes, so that the model is often very large, then use Babylon to load, the speed is very slow, can not meet the needs of users, a possible way is to use the model's tile data format to load, such as 3d tiles such a format, but Babylon does not seem to natively support the loading of files in these formats, I hope you can add the function of supporting such files, especially do not have the problem of breaking the surface, at the same time, GIS information such as terrain often needs to be operated in the project, Babylon doesn't seem to be easy to use, such as some of Cesium's capabilities, such as I want to put the project model on the earth of Cesium, users can browse from the earth to the ground, which is very common in China's digital twin projects, I hope you can think of some ways to make it easy for developers to achieve similar effects, and finally, I really hope you can open a demo video, just use Babylon to make a smart city, including indoor and outdoor, while doing and explaining, This is not only convenient for other beginners, but also contributes to the future metaverse

**Describe the solution you'd like**

The desire was to provide the ability to load tile resources natively, while making it easy for developers to create digital twin projects using Cesium. The former seems to have some plugins that can do it, but a lot of problems, especially broken surfaces, the latter is even more difficult, I hope you can help solve it

**Discussion**
You must provide a link to the forum post where the initial discussion happened

**Comment by deltakosh** [comment]
Please use the forum for feature requests

**Comment by BraveMomo** [comment]
> Please use the forum for feature requests

Please tell me the address of the forum

**Comment by deltakosh** [comment]
Forum.babylonjs.com :)
