### ISSUE TITLE
When popping out the inspector, right-click context menus revert to browser defaults

### ISSUE THREAD

**Issue by PatrickRyanMS** [BabylonJS/Babylon.js#15392]
When popping out the inspector - as illustrated below in embedMode - the right-click context menus we have for adding lights, materials, particles, etc. are replaced with the default browser right-click context menu. Is there any way we can retain our context menu when popping out the inspector? Popping out is useful when the canvas size is small but it would be great to retain the full functionality we have built into the inspector for debugging and/or experimenting.
 
![image](https://github.com/user-attachments/assets/c39aa073-799a-4f8d-9c5a-ee18f95fc066)

**Comment by deltakosh** [comment]
Closing as discussed offline
