### ISSUE TITLE
The PointerInfo provided in onPointerObservable has an undefined pointerType on MacOS Safari

### ISSUE THREAD

**Issue by AmoebaChant** [BabylonJS/Babylon.js#15466]
**Repro**
- Bug repro on [playground](https://playground.babylonjs.com/#HVZZ6G):
- Expected result: In Safari, mousing over the scene should display "event.pointerType = mouse" in the UI
- Current result: Only in Safari, it actually shows ".pointerType is missing"

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Safari

**Additional context**
It appears that Safari supports pointerType in the pointer* events, but Babylon currently wires up to the mouse* events for Safari which don't support that field.  See GetPointerPrefix() in tools.ts.

**Comment by RolandCsibrei** [comment]
I needed to fix this for my project so I created a PR: https://github.com/BabylonJS/Babylon.js/pull/15645
Sorry for hijacking.

**Comment by AmoebaChant** [comment]
Thanks for the fix @RolandCsibrei!
