### ISSUE TITLE
Fully local version of viewer without Internet access

### ISSUE THREAD

**Issue by hu-xd** [BabylonJS/Babylon.js#15478]
**Is your feature request related to a problem? Please describe.**
I need to use Babylon Viewer in local network without Internet access, but it seems like BabylonJS requires many scripts/assets on the Internet, and there is no way to config a custom url for them.
I've changed 'assetsRootURL' in configuration but there are many more.

**Describe the solution you'd like**
I'd like to have more config/control over which domain/baseUri that Babylon Viewer loads its external scripts/assets.

**Discussion**
https://forum.babylonjs.com/t/is-it-possible-to-create-fully-local-version-of-babylon-viewer/19693

**Comment by sebavan** [comment]
Feature request are now managed through the forum, can you open one there? cc @ryantrem for the requirement

**Comment by ryantrem** [comment]
The linked forum discussion is pretty old. @hu-xd maybe revive that discussion, or start a new one. It's worth revisiting in discussion because we are early in the development of a [new Viewer](https://www.npmjs.com/package/@babylonjs/viewer/v/7.22.3-alpha) that will replace the old one.

**Comment by hu-xd** [comment]
started a new discussion: https://forum.babylonjs.com/t/fully-local-version-of-babylon-viewer/53256
