### ISSUE TITLE
boundingBoxGizmo dragging is buggy since v7.21.0

### ISSUE THREAD

**Issue by kai-dorschner-twinsity** [BabylonJS/Babylon.js#15485]
**Repro**
- Bug repro on [playground](https://playground.babylonjs.com/#YIU90M#1204):
- Expected result: Gizmos should follow the dragged direction
- Current result: Gizmo drag axis are twisted (e.g. horizontal rotation gizmos are rotated by moving the mouse vertically)

Also, some of the gizmos have a wrong orientation, see the following screenshot:
![image](https://github.com/user-attachments/assets/dabbb2c7-401d-4291-89a8-1e3ee23e8ff6)

**Desktop (please complete the following information):**
 - OS: Microsoft Windows 11 Business (10.0.22631 Build 22631)
 - Browser MS Edge 
 - Version 128.0.2739.42 (Official build) (64-bit)

**Additional Context**
The styling of gizmos has changed in https://github.com/BabylonJS/Babylon.js/releases/tag/7.21.0. See https://github.com/BabylonJS/Babylon.js/pull/15415 for reference.

**Comment by CedricGuillemet** [comment]
https://github.com/BabylonJS/Babylon.js/pull/15487
Thanks for testing snapshots when they are available @kai-dorschner-twinsity

**Comment by kai-dorschner-twinsity** [comment]
Thank you guys for being this quick in solving issues 💯

**Comment by kai-dorschner-twinsity** [comment]
Hey guys! There might've been an oversight regarding the issue. Title title said that the dragging itself is buggy, and, as a side node the handles are also twisted. As far as I can see only the twisted handles have been fixed, but not the dragging itself.
See [playground](https://playground.babylonjs.com/#YIU90M#1204) to verify.
To be more precise:
* grabbing the left middle handle, the rotation around the Y axis should happen by moving the mouse horizontally on the X axis, though it only rotates by moving the mouse vertically on the Y axis.
* Here's an images indicated in RED what is expected and in BLUE what is actual
![image](https://github.com/user-attachments/assets/0f2b431c-3e95-4b8f-b349-30b033c5df06)

This goes on for many, but not all handles, here's a (maybe incomplete) list of broken and correct handles (RED: broken, GREEN: correct):
![image](https://github.com/user-attachments/assets/51d752e3-93ae-4fc4-b9ee-94d7d7e0732a)

**Comment by CedricGuillemet** [comment]
I'm taking a look.

**Comment by CedricGuillemet** [comment]
I did 2 passes of testing https://github.com/BabylonJS/Babylon.js/pull/15503
thanks for doing checks on your side @kai-dorschner-twinsity :)
