### ISSUE TITLE
raycast support for webgpu?

### ISSUE THREAD

**Issue by xuzhuang1996** [BabylonJS/Babylon.js#15556]
Is there GPU acceleration in the current calculation process of ray intersection? For example, is ray intersection supported by WebGPU

**Comment by Popov72** [comment]
Please, use our [forum](https://forum.babylonjs.com/) for such questions. To answer briefly, no, there's no GPU acceleration in the current calculation of ray intersections, but you can use Havok for such calculations, which benefits from years of optimization.
