### ISSUE TITLE
Add the steepness constant to the parameters of the skyMaterial

### ISSUE THREAD

**Issue by bvaisman-GitHub** [BabylonJS/Babylon.js#15703]
It will be useful to add the steepness parameter to get a more realistic skyMaterial because if we look at the sun, the sky behind the camera is too dark.

Here's the forum discussion : 

https://forum.babylonjs.com/t/skybox-environment/54107/8

**Comment by deltakosh** [comment]
We do not create issue until we actually work on them. Please use the feature request on the forum so users can vote:)
