### ISSUE TITLE
URLs not ending with file extension can't be loaded by `appendSceneAsync()`

### ISSUE THREAD

**Issue by hybridherbst** [BabylonJS/Babylon.js#15793]
When URLs don't end in a file extension, Babylon doesn't seem to be able to understand the served mime type or headers to determine the correct loader.

Example URL: https://cloud-staging.needle.tools/-/assets/Z23hmXB1tXjQr/1tXjQr/file

**Repro**
- Bug repro on [playground](https://playground.babylonjs.com): https://playground.babylonjs.com/#WGZLGJ#10762
- Expected result: File loads
- Current result: File does not load, exception in the console: 
```js
babylon.js?t=1731053735677:1 Uncaught (in promise) RuntimeError: 
Unable to load from https://cloud-staging.needle.tools/-/assets/Z23hmXB1tXjQr/1tXjQr/file: 
importScene of undefined from undefined version: undefined, exporter version: undefined
importScene has failed JSON parse
    at t [as constructor] (babylon.js?t=1731053735677:1:530981)
    at new t (error.ts:76:9)
    at d (sceneLoader.ts:1026:42)
    at Object.load (babylonFileLoader.ts:1056:17)
    at sceneLoader.ts:1063:35
    at f (sceneLoader.ts:643:13)
    at fileTools.ts:526:13
    at XMLHttpRequest.e (fileTools.ts:675:33)
```

**Screenshots**
<img width="880" alt="image" src="https://github.com/user-attachments/assets/18ca1b41-1cf2-4c76-b74d-a8ed71252fe7">

**Desktop (please complete the following information):**
 - OS: MacOS 15.1
 - Browser: Chrome, Safari

**Additional context** 

The URLs are served with the correct mime type. Other viewers load the file correctly, e.g.  
- ✅ Needle Viewer: https://viewer.needle.tools/?file=https://cloud-staging.needle.tools/-/assets/Z23hmXB1tXjQr/1tXjQr/file
- ✅ three.js: https://stackblitz.com/edit/three-dev-6gar8k?file=main.js
- ✅ model-viewer: https://stackblitz.com/edit/progressive-gltf-modelviewer-aw5kts?file=index.html
- ✅ PlayCanvas: https://playcanv.as/p/cs43ZE3p/
- ❌ Babylon 😢  https://playground.babylonjs.com/#WGZLGJ#10762

**Comment by deltakosh** [comment]
As stated in our issue template please start with the forum

**Comment by deltakosh** [comment]
And here is your fix: https://playground.babylonjs.com/#WGZLGJ#10767

We askj to chat on the forum first so we augment our knowledge base there

**Comment by hybridherbst** [comment]
Thanks for the note, I opened issues here in the past just fine so must have overread the new note about the forum.

I still believe this is a bug – it should not be necessary to provide the plugin because the file is served with the correct mime-type. Other viewers support that just fine, see above.

Do you want me to open a new forum post about this nonetheless before you reopen the issue?

**Comment by deltakosh** [comment]
Well we are all different ;)
You do two things:
- Open a feature request on the forum (in the feature request category) so people can vote and it helps us prioritize
- Do the PR and I will gladly merge it

**Comment by deltakosh** [comment]
@hybridherbst  https://github.com/BabylonJS/Babylon.js/pull/15798 :D

**Comment by hybridherbst** [comment]
Haha, thanks so much!
