### ISSUE TITLE
When HtmlMesh has a large scale, there may be a deviation in the display position, which may be caused by calculation accuracy

### ISSUE THREAD

**Issue by CTOSPACE** [BabylonJS/Babylon.js#15799]
When I apply HtmlMesh to a scene with a large scale, there will be a certain deviation in the display position of the elements in HtmlMesh. For example, when I scale to 0.01, the display position deviation will be very obvious. I think it should be caused by the calculation accuracy. Maybe this is a bug, maybe not, I’m not sure.

My application is to draw an HtmlMesh on a large geo based on the actual coordinates, and then scale the entire node of the geo so that the full view can be seen on the screen. However, the position of the HtmlMesh is displayed incorrectly

https://www.babylonjs-playground.com/#V51D3D

**Comment by deltakosh** [comment]
I double checked with 64bits matrices in babylon.js but the problem lies with the CSS matrix why has a lower precision we cannot control. My only recommendation would be to stick with scale > 1 (and play with the camera to get what you need):
https://playground.babylonjs.com/#V51D3D#2
