### ISSUE TITLE
Border of InputText

### ISSUE THREAD

**Issue by kadinuguru** [BabylonJS/Babylon.js#15870]
I have created a sample playground where I have added a StackPanel inside AdvancedDynamicTexture. 

The panel will hold an InputText field that will allow users to enter description and I will be adding other components to the panel. 

The issue I am facing with the InputText is that by default it has a black border but when I put the cursor in the input field to start typing the border goes away.
![image](https://github.com/user-attachments/assets/74ec3783-8dfb-4aa5-a06c-201a33a5ba30)
![image](https://github.com/user-attachments/assets/40480c6f-9113-4d89-9d03-a1a02b4dfa07)
The outline border shows back when the focus is moved away from the InputText field as shown in the images. 

![image](https://github.com/user-attachments/assets/2e59d97c-efd7-4316-b457-9d6b08b813ac)

I tried setting outline width to 1 by using  'descriptionInput.outlineWidth = 1;' which makes sure the black border always shows up for the text input field but it also make the text inside the field look bold as shown in the last screenshot

![image](https://github.com/user-attachments/assets/d7227985-ba34-4d29-8a92-6b9c06e1a0a2)

How can I fix the issue and make sure the border always shows up without making the text bolder

I appreciate any help on this. Here is a link for my playground
https://playground.babylonjs.com/#ZI9AK7#4239

`var createScene = function () {

    // This creates a basic Babylon Scene object (non-mesh)
    var scene = new BABYLON.Scene(engine);

    // This creates and positions a free camera (non-mesh)
    var camera = new BABYLON.FreeCamera("camera1", new BABYLON.Vector3(0, 5, -10), scene);

    // This targets the camera to scene origin
    camera.setTarget(BABYLON.Vector3.Zero());

    // This attaches the camera to the canvas
    camera.attachControl(canvas, true);

    // This creates a light, aiming 0,1,0 - to the sky (non-mesh)
    var light = new BABYLON.HemisphericLight("light1", new BABYLON.Vector3(0, 1, 0), scene);

    // Default intensity is 1. Let's dim the light a small amount
    light.intensity = 0.7;

    // Our built-in 'sphere' shape. Params: name, subdivs, size, scene
    var sphere = BABYLON.Mesh.CreateSphere("sphere1", 16, 2, scene);

    // Move the sphere upward 1/2 its height
    sphere.position.y = 1;

   var advancedTexture = BABYLON.GUI.AdvancedDynamicTexture.CreateFullscreenUI("UI");
    advancedTexture.idealWidth = 600;

     const panel = new BABYLON.GUI.StackPanel("Panel");
    panel.width = 0.28;
    panel.heightInPixels = 150;
    panel.horizontalAlignment = BABYLON.GUI.Control.HORIZONTAL_ALIGNMENT_RIGHT;
    panel.verticalAlignment = BABYLON.GUI.Control.VERTICAL_ALIGNMENT_TOP;
    panel.background = "white";
    panel.isVisible = true;
    advancedTexture.addControl(panel);

    var descriptionPanel = new BABYLON.GUI.StackPanel("DescriptionPanel");
    descriptionPanel.isVertical = true;

    var label = new BABYLON.GUI.TextBlock("DescriptionLabel");
    //label.widthInPixels = 45;
    label.heightInPixels = 15;
    label.text = "Description: ";
    label.color = "black";
    //label.style = descriptionLabelStyle;
    descriptionPanel.addControl(label);

    var descriptionInput = new BABYLON.GUI.InputText("DescriptionInput");
    descriptionInput.widthInPixels = 120;
    descriptionInput.maxWidth = 0.2;
    descriptionInput.heightInPixels = 15;
    descriptionInput.color = "black";
    descriptionInput.background = "transparent";
    descriptionInput.focusedBackground = "transparent";
    descriptionInput.focusedColor = "black";
    descriptionInput.thickness = 1;
    descriptionInput.outlineWidth = 0;
    descriptionInput.outlineColor = "black";
    descriptionInput.focusedColor = "black";
    descriptionInput.fontWeight = "light";
    descriptionInput.fontSize = "8px";
    //descriptionInput.style = "border: 1px solid black";
    descriptionInput.onKeyboardEventProcessedObservable.add(function (value) {
      value.preventDefault();
    })

    descriptionInput.onFocusObservable.add(() => {
      descriptionInput.outlineColor = "black";
      descriptionInput.thickness = 1;
    });

    descriptionInput.onBlurObservable.add(() => {
      descriptionInput.outlineColor = "black";
      descriptionInput.thickness = 1;
    });

    descriptionPanel.addControl(descriptionInput);

    panel.addControl(descriptionPanel);
 

    return scene;

};`

**Comment by sebavan** [comment]
Your outlineWidth should be 1 but please use the forum as explained in the template.

**Comment by kadinuguru** [comment]
@sebavan  I tried setting outlineWidth to 1 but it makes the text inside the field appear bold

![image](https://github.com/user-attachments/assets/ee367a30-a0d4-4291-939c-c32ef6f1c011)

**Comment by sebavan** [comment]
cc @RaananW
