### ISSUE TITLE
Splat rotated depending on camera pose

### ISSUE THREAD

**Issue by ryantrem** [BabylonJS/Babylon.js#15893]
Specifically in the new Babylon Viewer, when a splat is loaded and the camera is rotated, it seems like the splat is either rotated or somehow changes its pose relative to the camera. This didn't happen in earlier versions of the Viewer, so I'm not sure what is broken. @CedricGuillemet 

This can easily be reproed by running the Babylon Viewer test app in the Babylon monorepo and dragging/dropping a splat file onto the test app, then rotating the camera around the y axis.

EDIT: I just realized this only repros with WebGPU when snapshot rendering is enabled. @Popov72 

https://github.com/user-attachments/assets/e23e7b80-f911-4896-b04d-f32bf387781f

**Comment by CedricGuillemet** [comment]
This is an issue with splatIndex buffer. This buffer is sorted on CPU in a webworker and then pushed to the GPU. It looks like the buffer has not been updated. Can it be the case with snapshot enabled?

**Comment by CedricGuillemet** [comment]
GPU buffer update is done by calling thinInstanceSetBuffer . So, thin instances buffer updates are not considered when in snapshot mode? Is it the same with any updatable buffer? @Popov72

**Comment by Popov72** [comment]
Upading buffers should work, I'm going to have a look.

**Comment by Popov72** [comment]
PR to support gaussian splatting meshes with the snapshot rendering helper:

https://github.com/BabylonJS/Babylon.js/pull/15906

**Comment by sebavan** [comment]
Closing as #15906 as been merged
