### ISSUE TITLE
Please help. I want to load a large scene, including many buildings and trees. 

### ISSUE THREAD

**Issue by BraveMomo** [BabylonJS/Babylon.js#15916]
Please help. I want to load a large scene, including many buildings and trees. My model is placed on the server. Every time the user loads it, it is very slow and takes a long time. Are there any tricks to increase the loading speed and improve the user experience?

**Comment by sebavan** [comment]
As the template mentions, we keep Github exclusively for validated issues. We centralize our questions on the forum https://forum.babylonjs.com/ where you should ask. Several techniques like LODs, draco… can be discussed there
