### ISSUE TITLE
Add support for cascaded shadows

### ISSUE THREAD

**Issue by deltakosh** [BabylonJS/Babylon.js#1818]

**Comment by sebavan** [comment]
directional Light only seems the way to go as they are representing lights from a far distance.

**Comment by bnolan** [comment]
I'm very interested in this, happy to help if someone can point me in the right direction. Cryptovoxels has a really large world with a directional light and can't make the shadow map high enough res to cover a large are of the world, so CSM would be perfect for my case.

**Comment by sebavan** [comment]
This would be Awesome :-) can you pm me on the forum so that we could check how to make this happen ?

**Comment by bnolan** [comment]
Ok awesome. I'm guessing at a basic level, if I had two `shadowGenerators` overlaid over each other, I'd just need to edit the shader code so that it smoothly transitioned from querying the more detailed to the less detailed shadowmap?

**Comment by sebavan** [comment]
We were more thinking something like https://docs.microsoft.com/en-us/windows/desktop/DxTechArts/cascaded-shadow-maps

But the idea is totally similar indeed

**Comment by bnolan** [comment]
Yes I was just about to post that article, it goes over the details really well. The view frustrum -> shadow map transforms are a bit over my head, but I think I'll have a stab at this using some really simple cases and see if I can get it to sort of hang together. I think most of this code can go into the `ShadowGenerator` class, or maybe create a class `CascadedShadowGenerator` or similair.

**Comment by sebavan** [comment]
Sounds like an amazing plan to me !!! keep us posted.

**Comment by bnolan** [comment]
This is an [old example of CSM](https://alteredqualia.com/three/examples/webgl_road.html) in three.js, might be some code worth referencing in there.

**Comment by sebavan** [comment]
Close by #7372
