### ISSUE TITLE
Add support for webgl2 uniform buffers

### ISSUE THREAD

**Issue by deltakosh** [BabylonJS/Babylon.js#1821]

**Comment by QuantumInformation** [comment]
I'm playing with webgl2 native now, wow so much code to write to do simple things)

Can you help me understand how uniform buffers will benifit babylon?

**Comment by deltakosh** [comment]
It will allow to update shaders uniform with less calls.
Like instead of 10 calls to uniform1v you can do it with one. 

When dealing with complex shaders like the one use by StandardMaterial or PBRMaterial the gain could be substantial

**Comment by CraigFeldspar** [comment]
I'm on it 👍 
Can you assign this to me ?

**Comment by deltakosh** [comment]
I can only affect it to core members. But no worry I leave it to you :)
