### ISSUE TITLE
not support WebGL on PLayground

### ISSUE THREAD

**Issue by dad72** [BabylonJS/Babylon.js#1830]
Hi,
Today I received an error on the playground, on which each demo say :

Your browser does not support WebGL

But my browser supports WebGL. What is strange is that it works on FireFox, but not Google Chrome that I use for some years with WebGL JavaScript without any problems. Why suddenly this error?  Maybe my PC gone bad start this morning?

**Comment by deltakosh** [comment]
hello this is not a babylon.js bug. Do you mind using the forum for it?

**Comment by dad72** [comment]
Yes I should restart my PC before posting it. I was thinking too quickly.

I just restarted my PC and it works, so it was my PC did not start well be morning.

Sorry for the false alarm.

**Comment by deltakosh** [comment]
No worry but please use github issues for validated bugs
