### ISSUE TITLE
Disposing Primitive is not safe

### ISSUE THREAD

**Issue by nockawa** [BabylonJS/Babylon.js#1857]
@royibernthal reported instable behaviors with disposing primitives, no use cases

On 2/22/2017 at 3:01 AM, @wyklion (MasterK) said:

And my current version of c2d has a problem for long: set primitave levelVisible = false. and do some change to it, when canvas use Cache Strategy, it will throw gii is null or other error on next display frame. I dont make case. but lots of cases of our project show this problem. So lots of our UI panel need to delete canvas and recreate again. Just let you known about this.
Can you elaborate a bit more? Is it something like:
1) use the CANVASLEVEL cached strategy
2) hide a primitive by setting its levelVisible = false
3) change the primitive position/size or any other attribute
Then an error is thrown next frame.

**Comment by nockawa** [comment]
@wyklion hey mister, I've made few tests, I'm with CACHESTRATEGY_CANVAS, I create a text, animate it, move it, hide it, change its position and text content (hide/display again), dispose it and so far things are working. Would you have more information that I could use to reproduce the crash? Thanks!

**Comment by wyklion** [comment]
yeah it looks more safer..

**Comment by nockawa** [comment]
ok, I let this issue open until you have a chance to test the latests dev

**Comment by abow** [comment]
@deltakosh I can't reproduce this bug either.

http://www.babylonjs-playground.com/#VZKMS4#2
