### ISSUE TITLE
PointerUp event processing bug when design size is set

### ISSUE THREAD

**Issue by TMTHY** [BabylonJS/Babylon.js#1868]
Here is PG http://babylonjs-playground.com/#CUABM
Intended behaviour - you click on small rectangle,  big rectangle has to change its fill color.

It's OK without design size.
When design size is set, sometimes click is not processed - try clicking on the right part of small rectangle.

**Comment by nockawa** [comment]
Thing is, I not use a new Scale property specific for DesignSize, and I didn't introduced in all places it should have been, it's the same kind of issue than #1867 I'm on it, I'll solve both immediately

**Comment by abow** [comment]
@deltakosh this also appears to be fixed
