### ISSUE TITLE
Intersection element

### ISSUE THREAD

**Issue by juanrbachiller** [BabylonJS/Babylon.js#1870]
Is there a way to get the actual intersection of to geometries?

E.g. the intersection point of a line and a plane, the line intersection of two planes, the arc intersection of a sphere and a plane, etc...

Thanks!

**Comment by jbousquie** [comment]
Please ask in the forum : 
http://www.html5gamedevs.com/forum/28-questions-answers/

**Comment by deltakosh** [comment]
https://github.com/BabylonJS/Babylon.js/blob/master/contributing.md#forum-and-github-issues
