### ISSUE TITLE
3 vectors por a straight line?

### ISSUE THREAD

**Issue by juanrbachiller** [BabylonJS/Babylon.js#1871]
Is it mandatory to use 3 vectors to draw a 2d straight line? When using 2 vectors the line stretches around the midpoint: http://babylonjs-playground.com/#15C96V#26

**Comment by jbousquie** [comment]
github issues are for validated bug only
please ask in the forum

**Comment by deltakosh** [comment]
https://github.com/BabylonJS/Babylon.js/blob/master/contributing.md#forum-and-github-issues
