### ISSUE TITLE
Wrong values with object rotated along X AND Y AND Z

### ISSUE THREAD

**Issue by Raphy44260** [BabylonJS/Babylon.js#1873]
Hi,

We've made several tests to try to understand why we got a problem with some objects once exported from Max. It seems like when an object has some rotation inside Max on the 3 axis, it is not exported as it should be, and rotation values are wrong. I haven't found any particular "rule" in the calculation of these wrong values.

We've made the same test with only 1 rotation (along X OR Y OR Z), and 2 rotations (X+Y OR X+Z OR Y+Z) : the exporter seems to work fine in this case. The issue appears only when an object is rotated along X+Y+Z.

Thanks a lot for your help,

Raphaël

**Comment by deltakosh** [comment]
Hello please use forum for questions:  https://github.com/BabylonJS/Babylon.js/blob/master/contributing.md#forum-and-github-issues
