### ISSUE TITLE
attachToBone does not work anymore

### ISSUE THREAD

**Issue by dad72** [BabylonJS/Babylon.js#1881]
Hello,

In the demo available here : http://doc.babylonjs.com/tutorials/how_to_use_bones_and_skeletons
 to attach an object to a bone no longer works. 
The sphere is attached to the character when I look in the inspector. but she is not render. she is not visible.

http://www.babylonjs-playground.com/#11BH6Z#18

**Comment by deltakosh** [comment]
@abow will check is asap :)

**Comment by dad72** [comment]
Thanks Abow
