### ISSUE TITLE
Move HDRRenderingPipeline and SSAORenderingPipeline into Standard Rendering Pipeline

### ISSUE THREAD

**Issue by julien-moreau** [BabylonJS/Babylon.js#1903]
Then developers can focus only on one rendering pipeline which is fully customizable
Effects will be
* SSAO V2 - TODO
* Highlight rendering - DONE
* Luminance adaptation - DONE
* Pseudo Lens Flare - DONE
* Depth Of Field - DONE

**Comment by deltakosh** [comment]
Good idea! But we also need to keep the current pipeline for backward compat

**Comment by julien-moreau** [comment]
I planned to just add a Tools.warn on these pipelines and then remove in future version
You ok with that ?

**Comment by deltakosh** [comment]
You cannot reuse them? It is pretty simple to use to day. But let's see how your API will look like :)

The easier the better!

**Comment by julien-moreau** [comment]
Sure !! Will try to find an awesome solution and submit it to you :)

**Comment by deltakosh** [comment]
I trust you!

**Comment by julien-moreau** [comment]
Unfortunately I found no idea at the moment to use the HDRRenderingPipeline inside the Standard one without creating breaking changes. The best I can do (until I find a solution) is to share the glsl equations between HDR and Standard then we can save some bytes

**Comment by julien-moreau** [comment]
Or mark the HDR pipeline as deprecated and keep only the standard. Allows to maintain only one pipeline

**Comment by deltakosh** [comment]
Like this idea

**Comment by julien-moreau** [comment]
Will do the changes and pull request :)

**Comment by julien-moreau** [comment]
I close this issue has hdr has been moved into it and ssao has its own pipeline now :)
