### ISSUE TITLE
Add support for Exponential Soft Shadows

### ISSUE THREAD

**Issue by deltakosh** [BabylonJS/Babylon.js#1916]

**Comment by BitOfGold** [comment]
Hi!
Maybe the new ESM causes problems with PBR shadows:
http://www.html5gamedevs.com/topic/29309-pbr-shadow-shader-error/

Test case:
http://www.babylonjs-playground.com/index.html#1MJ2U8#8

**Comment by sebavan** [comment]
Hello,

Yes, I have just noticed and I am fixing it right now.

Thanks for the feedback,

**Comment by sebavan** [comment]
#1932 is the associated pull request.

**Comment by deltakosh** [comment]
PG updated :)
