### ISSUE TITLE
Support for WebGL2RenderingContext

### ISSUE THREAD

**Issue by nkemnitz** [BabylonJS/Babylon.js#1917]
Type definitions for WebGL 2 are now available on [Definitely Typed](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/webgl2).

I have no good idea yet how to modify Babylon.js to return / accept a WebGL2RenderingContext, so for now I am just leaving this issue here for you :P

**Comment by deltakosh** [comment]
Actually I already extended wegbl1 context with what we need in bjs
you can check the mixin.ts file
