### ISSUE TITLE
ScreenSpaceCanvas not resized properly on canvas resize

### ISSUE THREAD

**Issue by royibernthal** [BabylonJS/Babylon.js#1937]
When resizing canvas after page load, ScreenSpaceCanvas elements get distorted instead of resizing along with scene.
I think it used to work properly at some point.
It can't be seen in a PG because it doesn't resize the canvas according to window size, but test on any window with canvas width and height set to % of window (e.g. 100%) and you'll notice it immediately.

**Comment by nockawa** [comment]
In this PG: http://www.babylonjs-playground.com/#22PLQU#0
When the window is resized, the Sprite's position is unstable (DesignMode, should be stable)
Also report to @wyklion

**Comment by albertbuchard** [comment]
Might be related, if size of the ScreenSpaceCanvas is null it resize automatically relatively well but its width and height are not updated / correct when accessed like so canvas.width.
