### ISSUE TITLE
Feature requests - 3ds Max exporter

### ISSUE THREAD

**Issue by Gil-1** [BabylonJS/Babylon.js#1957]
Hello,

Here are 2 small features that could be usefull with the exporter :

- Add an option to not export material of a mesh
    I know I can remove the material of the object before export but sometimes is just nice to have that option.
- Add the exporter version in the window title (I don t ask for a check update but at least knowing the current version would be nice)

**Comment by deltakosh** [comment]
Hello! 
I did not see the use case for 1. You can remove it either in JS as you mentioned or in 3dsmax
For 2, this is a good idea.

**Comment by Gil-1** [comment]
Hello,

Sometimes I don't want to export materials from the objects since I will need to do them in javascript.
So it's just datas I don't need.

Maybe I miss some info on how to export all kinds of materials from 3ds max.

For example, I don t know if it s possible to export from max an object with a PBR material. So I create it in JS after the export.

**Comment by deltakosh** [comment]
not possible yet. the js option is my recomm dation so far

**Comment by Gil-1** [comment]
Yes, that's what I thought. So having the ability to discard materials on export makes sense now. Don t you think ?

**Comment by deltakosh** [comment]
I would prefer adding support for PBR:)

**Comment by S0ulAssass1n** [comment]
Hey there, good job on the plug-in! 
I have a question concerning the skin wrap modifier. Is it possible to export say a shirt that is skin wrapped on top of a body with multiple morph targets so that when we play with morph targets the shirt is deforming accordingly? Could that be implemented in babylonjs?

**Comment by deltakosh** [comment]
Duplicate with #2193
