### ISSUE TITLE
physicsEnabled not set by blender exporter 4.6.1

### ISSUE THREAD

**Issue by sijakret** [BabylonJS/Babylon.js#1964]
When using the blender -> *.babylon exporter and activating physics on object i get the following error

    BJS - [20:41:25]: Physics not enabled. Please use scene.enablePhysics(...) before creating impostors.

if i add this "physicsEnabled":true in the json root of the exported file it seems to work.
The scene loader thus seems ok, however, looking through the exporter python script I cannot find a line that could actually write that flag.

Am i missing something or is there something missing in the exporter?

**Comment by deltakosh** [comment]
ping @jcpalmer

**Comment by Palmer-JC** [comment]
I have never used physics.  Any physics in exporter was not put there by me.  Adding an element is not really hard, but known whether it needs to be added could be.  Is there any drawback to always enabling it.  If so, could something in the blend be used, or can it only be known by keeping track as every mesh get processed?

FYI, 4.6.1 is never going to be edited by me.  I only kept it for very old versions of Blender.

**Comment by sijakret** [comment]
you could enable it if there are any physics(/collision)-enabled objects present..
is 4.6.1 the wrong exporter? is there a more up-to-date one?

**Comment by Palmer-JC** [comment]
[https://github.com/BabylonJS/Babylon.js/blob/master/Exporters/Blender/Blender2Babylon-5.2.zip](url)  You do not need to un-zip.  Just select in 'User preferences->load file' .

I can put it on my list.  Would not get to for a while.  Work around is fairly minor.

**Comment by sijakret** [comment]
i monkey-patched the 5.2 loader.
`file_handler.write('"physicsEnabled":true,\n')`
in to_scene_file(self) does the job for me for now..

thank you!
