### ISSUE TITLE
3DS Max Exporter - Light Performance Issue

### ISSUE THREAD

**Issue by licantre** [BabylonJS/Babylon.js#1968]
Sup, Guys I was setting up lights for our project in 3DS Max scene before export, just 2 skies to have full 360 degree sphere light which is equivlant i think of hemisphere in babylon. Well the point is there were lack of performance in scene, so i exported without any preset light. On default light added during export by babylon exporter and with hemisphere added in editor I had almost tripple better performance.  Made screenshots to visualize issue.
![1234](https://cloud.githubusercontent.com/assets/13338712/24698816/43747e7a-19f2-11e7-81ef-2c0313d85eef.jpg)

**Comment by deltakosh** [comment]
can you please use our forum? the capture on the left clearly states that the number of draw calls is twice as what you have on other captures
si perhaps the light you used had shadows enabled?

________________________________

**Comment by deltakosh** [comment]
you can test it by turning on and off the shadows with the inspector

**Comment by licantre** [comment]
Wait, strange thinks i notice there is 0.8 version so I replaced my old 0.7 exporter. And it's working! 280 potential fpse but looks strange. When u do not enable Darkness on spotlight there are big artifacts on mesh. Anyway yes i used shadowmap enabled in max. So far on 0.8 there is no more doubling verticles anymore in scene. But i will try do your trick maybe will be more potential fps-es with editor enabled. With less drawcalls

**Comment by deltakosh** [comment]
Sounds good!
