### ISSUE TITLE
Advanced Textures manipulations

### ISSUE THREAD

**Issue by Gil-1** [BabylonJS/Babylon.js#1972]
Hello,

I got some feature request for the engine.
I know all of that would be doable when creating shaders but I think that would be cool to be able to do that when setuping the scene and the shaders directly.

Here is what I would like to be able to do :
- Access RGBA separately of a texture so I can store multiple textures / masks inside one.
- Basic computation between textures : multiply a texture one by one or by a % or mask (other texture), add a texture on top on another... (it could be used to animate texture between them). Basicly I would like to do +-/* .
- Texture blending we can animate.
- Textures controls like saturation, contrast, luminosity... I saw with PBR we have some sort of controls over the shader but I think it would be more efficient to do that on the texture level.
- Normal Bump Scale

I think that just doing that would be huge for me as the shading right now is pretty simple. We could then add several textures together to make more complex shader. Maybe there will be some limitation but I would love to see that.

**Comment by deltakosh** [comment]
Hello hello!

All of this can be achieved with DynamicTexture: http://doc.babylonjs.com/classes/2.5/dynamictexture

See this example where the texture is generated: http://www.babylonjs-playground.com/#10WU6Z#0

**Comment by Gil-1** [comment]
Hello,

Well that's good news but is there a more explicit example like an animated blend between two bitmaps ?

Also, I don t see how I can access RGBA or manage saturation and so on. Sorry.

**Comment by deltakosh** [comment]
The dynamic texture gives you with a canvas context (like the same you get when you call canvas.getContext("2d"))

There are plenty of samples on internet about image manipulation with canvas:
http://www.qoncious.com/questions/changing-saturation-image-html5-canvas-using-javascript
