### ISSUE TITLE
move colorcurves, contrast + aperture to camera

### ISSUE THREAD

**Issue by deltakosh** [BabylonJS/Babylon.js#2009]
+ add support for contrast and aperture to stdmaterial

**Comment by sebavan** [comment]
Create a default environment texture as well.

**Comment by sebavan** [comment]
Global environment has been added to the scene as well as createDefaultSkybox

**Comment by sebavan** [comment]
This has been moved to the new defaultRenderingPipeline for contrast and aperture.
