### ISSUE TITLE
Exporter 5.2 - how to use texture atlases

### ISSUE THREAD

**Issue by sijakret** [BabylonJS/Babylon.js#2023]
Are texture atlases currently supported in conjunction with cycles baking?

If i use the blender plugin that allows to map multiple objects to one atlas and then bake some lighting layers in there it renders fine in blender.
The plugin apparently assigns UV maps to the mesh. After that, subsequent exports will trigger baking and it seems they try to use the existing UVs somehow and somehow the baked textures don't match or are blank. Removing the UVs then makes things work again.

In general: i couldn't find any good material on how to
* export baked lighting (cycles)
* in conjunction with diffuse textures
how can the UVs of on-the-fly-baked maps coexist with hand-made textures UVs?

Thank you!

**Comment by deltakosh** [comment]
Hello do you mind asking your question on our forum: http://www.html5gamedevs.com/forum/16-babylonjs/ ?

thanks a lot
