### ISSUE TITLE
Disposing materials is broken in nightly

### ISSUE THREAD

**Issue by andyhall** [BabylonJS/Babylon.js#2026]
Disposing a material currently crashes any scene with a mesh.

PG: http://www.babylonjs-playground.com/#IXWTVK

Buggy code appears to be [here](https://github.com/BabylonJS/Babylon.js/blob/3818803c03438a61e0f3489069b8fc637a188fdf/src/Materials/babylon.material.ts#L499-L509). Note that that loop messes with every mesh in the scene - regardless of whether they had the disposed material.

**Comment by deltakosh** [comment]
Fixed with https://github.com/BabylonJS/Babylon.js/commit/2e3fe889bc7003d16e5246e2a976526712b8ec2f
 Thank you very much Andy!
