### ISSUE TITLE
Change Texture of Sprite2D

### ISSUE THREAD

**Issue by nockawa** [BabylonJS/Babylon.js#2029]
Right now the Texture and UV Coordinates are immutable in the Sprite2D primitive.
It could be nice to make them mutable.

Report to @royibernthal

**Comment by royibernthal** [comment]
Changing textures of an existing sprite would be the best way to create buttons with different textures for different states (up, over, down). It'd be a very useful feature.

**Comment by nockawa** [comment]
If the different states are all packed horizontally you can use the spriteFrame property to switch from one state to another. Otherwise you can also rely on the AtlasPicture to address/change many sub picture stored into one big texture.
So there's already two way of doing it.
I agree a third is possible, but I don't think I'll invest time on that in a near future.
