### ISSUE TITLE
STL Loader doesn't return mesh array on callback

### ISSUE THREAD

**Issue by michael-hawker** [BabylonJS/Babylon.js#2030]
The 'meshes' argument to ImportMesh in the STL File Loader never gets updated after the call to parseSolid [here](https://github.com/BabylonJS/Babylon.js/blob/master/loaders/src/STL/babylon.stlFileLoader.ts#L40).

    var babylonMesh = new Mesh(meshName, scene);
    this.parseSolid(babylonMesh, matches[2]);
    // Should do something like this after:
    meshes.push(babylonMesh);

Therefore, the intended contract to have access to the loaded meshes in the callback is broken.

**Comment by deltakosh** [comment]
Fancy doing a PR?
