### ISSUE TITLE
buffer or buffer range not large enough at index 0

### ISSUE THREAD

**Issue by rimmartin** [BabylonJS/Babylon.js#2052]
Hi,

I pulled a fresh working copy today and running the getting started example on http://doc.babylonjs.com/
am now getting the following:
```
.Offscreen-For-WebGL-0x390aea350c00]GL ERROR :GL_INVALID_OPERATION : glDrawElements: uniform buffers : buffer or buffer range not large enough at index 0
```

if I comment out the sphere and ground creation the error goes away.

Not sure what is being referred to at 'index 0'.  Earlier today I was using a Feb 19 pull successfully

**Comment by rimmartin** [comment]
I'm using the ~/Babylon.js/dist/preview release

**Comment by deltakosh** [comment]
Ping @CraigFeldspar

**Comment by CraigFeldspar** [comment]
Hello @rimmartin,
What browser are you using ? What's your GPU ?

Also, can you try the playground examples https://playground.babylonjs.com/ and see if you get the same errors ?

**Comment by deltakosh** [comment]
(just FYI: I did not publish the UBO to playground yet)

**Comment by rimmartin** [comment]
I tried Firefox 53.0 on Ubuntu 16_04 an then Chrome 58.0.3029.81 both on ASUS 64 bit laptop with nvidia driver 375.39 GeForce GTX 560M.

**Comment by rimmartin** [comment]
multiple playground examples work for me

**Comment by CraigFeldspar** [comment]
can you send me a pastebin of the exact code you're using ? thanks !

**Comment by CraigFeldspar** [comment]
I will attempt a small fix meanwhile, see PR https://github.com/BabylonJS/Babylon.js/pull/2057

**Comment by deltakosh** [comment]
Pg is updated. Do you still have the issue?

**Comment by rimmartin** [comment]
Sorry, at work yesterday I don't have access to internet from my laptop to make a pastebin

Albeit good news is I did a pull just now and you fixed it without seeing the problem!  Thank you!

**Comment by deltakosh** [comment]
Excellent:)
