### ISSUE TITLE
First step towards Deferred and SSAO v2 with MRT

### ISSUE THREAD

**Issue by CraigFeldspar** [BabylonJS/Babylon.js#2055]
WebGL allows us to use multi render target, to draw to several buffers in one pass (see http://webglsamples.org/WebGL2Samples/#fbo_rtt_draw_buffers).

My first goal is to implement rendering to 3 buffers in one pass : color, normals and depth. I will try to provide an easy way to port existing shaders (probably by including a chunk into the main function that will have in charge to render normals and depth).

Following that, we could improve performance and quality of current SSAO pipeline by A LOT, and also start to provide a deferred/forward+ approach to rendering (hello hundreds of pointlights at 60 FPS !).

**Comment by deltakosh** [comment]
Ssao improvment is a great idea:)
The deferred engine could be cool but only if there is no impact to the main forward path

**Comment by julien-moreau** [comment]
Having a depth + normal RTTs at same time may save a lot the current SSAO performances !

Would be awesome to use the depth render function separately in custom materials like materials library then use it with shadow maps. Then animated vertices can cast properly shadows in all cases, such as waves and bones. Do you agree ?

**Comment by CraigFeldspar** [comment]
Yes, you can either get the depth buffer from a render, or render to 2 targets : 1 for color and the other for depth.

I've tried my g-buffer with SSAO, but performance still aren't that great. I think the shader does too many cache trashing, I'm gonna look into it.

**Comment by julien-moreau** [comment]
Right, unfortunately the current SSAO is based only on depth and estimates the normal by taking two depth points, which is expansive. The method "getNormal" should be replaced by return texture2D(normalSampler, uv)

**Comment by CraigFeldspar** [comment]
Yes, that's what I did, but the shader still slows down a lot when the camera is close to objects. This problem probably comes from the fact the random texture sampling is spread all across the screen for every pixel, which cause the GPU to trash the texture cache a lot.

**Comment by xuchen-shadow** [comment]
Hi folks, is there any progress about this? This really sounds exciting.

**Comment by deltakosh** [comment]
We do have SSAO2 and support for MRT now ;)

**Comment by xuchen-shadow** [comment]
@deltakosh, yes bug I think CraigFeldspar would like to render color, depth and normal buffer in one pass, which means we need to rewrite all the material shaders :)

**Comment by deltakosh** [comment]
So far this is not on the plan:)
