### ISSUE TITLE
Access-Control-Allow-Origin

### ISSUE THREAD

**Issue by despotZZ** [BabylonJS/Babylon.js#2065]
I write this code "var url1='xxxx';  var DiffuseTexture = new BABYLON.Texture(url1, scene);"
and I get a error "No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'null' is therefore not allowed access."

**Comment by RaananW** [comment]
What is the url you are trying to load? Where are you running this code? Locally, on a server, or in the playground?

**Comment by deltakosh** [comment]
Up

**Comment by despotZZ** [comment]
on a server，and the url is on another

**Comment by deltakosh** [comment]
OK so this is under your control. Your server CORS needs to be setup to allow anonymous origin

**Comment by despotZZ** [comment]
it's solved,thank you~

**Comment by ghanshyamweb** [comment]
how to setup CORS, can you give exmaple??

**Comment by RaananW** [comment]
> how to setup CORS, can you give exmaple??

This is a server configuration that you need to set up yourself. Read about it here - https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

Please use our forum if you have any questions :-)
