### ISSUE TITLE
Friction physics bodies bug

### ISSUE THREAD

**Issue by 01Lizard10** [BabylonJS/Babylon.js#2068]
For some reason both physics bodies have the same material object.
PG: http://www.babylonjs-playground.com/#249T6Y
More details here: http://www.html5gamedevs.com/topic/29044-friction-bug-workaround/

**Comment by deltakosh** [comment]
This is not a bug per se. To optimize we share materials.
If you want afterward to change a mat, just recreate a new impostor for the mesh (with new physics material )
