### ISSUE TITLE
can't unzip Blender2Babylon-5.2.zip on mac

### ISSUE THREAD

**Issue by zoth** [BabylonJS/Babylon.js#2084]
When unzipping in OSX finder getting error "Unable to expand ... (Error 1 - Operation not permitted.)"
When I unzip in a terminal the expanded folder is locked to me even if I use sudo.

I'm using OSX 10.10.5

**Comment by Palmer-JC** [comment]
Are you doing "Install From File" button, on the Add-ons Tab of User Preferences.  Blender does the unzip for you.  It also does it in a place which should allow it.  sudo is kind of a flag that you are trying to do it yourself.

**Comment by zoth** [comment]
Sorry. I'm a Blender newbie. I was indeed trying to unzip it myself.
But out of curiosity. Why would that zip file be locked down like that?

**Comment by Palmer-JC** [comment]
Make sure you have read permission.  Maybe something having to do with some kind of download quarantine.  Or was the location in the blender.app file (.app is really a directory with special treatment).
