### ISSUE TITLE
Cross product precision? Rotating a cylinder into place

### ISSUE THREAD

**Issue by rimmartin** [BabylonJS/Babylon.js#2107]
Hi,
I was testing http://www.babylonjs-playground.com/#1RWE59#12
which has two spheres and a cylinder placed between them. As you make the spheres more and more in the y axis direction the quality of the cylinder placement breaks down. And rather rough.

I've experimented with other axes to come up with the quaternion axis and angle which is doable yet the range is narrow where a given chosen axis yields quality.

Is there a better way to take a cylinder from it's initial reference frame and plunk it in place?

**Comment by deltakosh** [comment]
Hey!
can you please use the forum for questions?

**Comment by rimmartin** [comment]
Ok, but this looked like a major bug

**Comment by deltakosh** [comment]
I agree but let's discuss potential fixes on the forum where vast majority of our users are

**Comment by rimmartin** [comment]
Ah ok, I misunderstood the role of the forum and github issues.  I'll get there; digging in the code and trying some comparisons to eigeneigen so I can maybe start a better discussion

**Comment by deltakosh** [comment]
Clearly appreciate the help :)
