### ISSUE TITLE
3ds max skin wrap to babylonjs

### ISSUE THREAD

**Issue by S0ulAssass1n** [BabylonJS/Babylon.js#2109]
Hey there, good job on 3dsmax2babylon plug-in! 
I have a question concerning the skin wrap modifier. Is it possible to export say a shirt that is skin wrapped on top of a body with multiple morph targets so when we play with morph targets sliders the shirt is deforming accordingly? Could that be implemented in babylonjs?

**Comment by deltakosh** [comment]
See forum discussion:
http://www.html5gamedevs.com/topic/30302-3ds-max-skin-wrap-to-babylonjs/
