### ISSUE TITLE
how to make 3d text in babylon.js

### ISSUE THREAD

**Issue by jiweigang1** [BabylonJS/Babylon.js#211]
how to make 3d text in babylon.js

**Comment by Yonet** [comment]
@deltakosh can we re-open this issue as a feature request? 

Thanks!

**Comment by sebavan** [comment]
Actually a contributor proposed this solution : https://forum.babylonjs.com/t/3d-text-in-babylon/253

Would that fit your need ?

**Comment by Yonet** [comment]
Thank you for pointing me @sebavan, the examples doesn't work, I'll open an issue on extensions repo.

**Comment by deltakosh** [comment]
I think posting a bug on the forum could work as well as the other is also on the forum :)

**Comment by sebavan** [comment]
I asked on the forum thread as it looks like the server used in the demo is having a cert issue and as it it an external contrib, we do not own the servers to fix it.
