### ISSUE TITLE
Warning errors on texture that needs to be converted on some scenes in Chrome and Firefox

### ISSUE THREAD

**Issue by davrous** [BabylonJS/Babylon.js#2116]
Repro: http://playground.babylonjs.com/#YITJU9#1

In Chrome:

[.Offscreen-For-WebGL-0000021E833688F0]RENDER WARNING: there is no texture bound to the unit 0
/#YITJU9#1:1 [.Offscreen-For-WebGL-0000021E833688F0]RENDER WARNING: there is no texture bound to the unit 1
2/#YITJU9#1:1 [.Offscreen-For-WebGL-0000021E833688F0]RENDER WARNING: there is no texture bound to the unit 0

In Firefox:

Error: WebGL warning: texImage2D: Conversion requires pixel reformatting. babylon.js:5:9325
Error: WebGL warning: texImage2D: Conversion requires pixel reformatting.

**Comment by deltakosh** [comment]
https://github.com/BabylonJS/Babylon.js/commit/5d15bd551bd471bcdbd3cc6a65a3269dc813429b
