### ISSUE TITLE
[Feature request] ArcRotateCamera panning when inertia set to 0

### ISSUE THREAD

**Issue by Poolminer** [BabylonJS/Babylon.js#2117]
Currently this is not possible, as this demo shows:

http://www.babylonjs-playground.com/#2HD14C

I think the best would be to allow a custom inertia value to be set for panning, because rotation and panning are different functions that you may not want to be linked together like that.

Thanks.

**Comment by deltakosh** [comment]
Good feedback..I'll flag it as "todo"

**Comment by deltakosh** [comment]
Actually it works right now. I can pan even with inertia set to 0
