### ISSUE TITLE
camera key controls on 3.0-alpha

### ISSUE THREAD

**Issue by durrantlab** [BabylonJS/Babylon.js#2119]
I believe this is a bug... let me know if I should post on the forum instead.

I am adding key controls to my camera like this:
```
camera.keysUp.push(87);  // W
camera.keysLeft.push(65);  // A
camera.keysDown.push(83);  // S
camera.keysRight.push(68);  // D
```

This works fine in version 2.5. But in 3.0-alpha, the keys are not detected. I press W, A, S, and D, and no camera movement occurs.

Interestingly, when I select the camera through the new debugging layer, the keysDown, keysLeft, etc. variables appear to be empty.

But the javascript console tells another story. `scene.activeCamera.keysDown`, for example, returns `[40, 83, 83]`.

So my selected values are being recorded in the engine, but the engine appears to be ignoring them.

Just to reiterate, I don't have this problem in Babylon 2.5. Thanks.

**Comment by deltakosh** [comment]
Can you provide a repro in the PG?

**Comment by durrantlab** [comment]
Nevermind, guys. There was a difference when I switched to the new 3.0-alpha, but it seems to be related to the collision system, not the key-binding system. When I turned camera collisions off, it worked fine. I think my camera might have been "stuck" in the ground. Thanks.
