### ISSUE TITLE
Missing pictures in documentation

### ISSUE THREAD

**Issue by gleborgne** [BabylonJS/Babylon.js#2138]
Pictures are missing on this page in documentation
https://doc.babylonjs.com/tutorials/particles

**Comment by sebavan** [comment]
Thanks for reporting. Seems link to #2125

**Comment by sebavan** [comment]
Fixed

**Comment by Jaskar** [comment]
Was fixed : https://github.com/BabylonJS/Documentation/pull/435
Just not deployed.
You may find other images missing due to babylon.js website changes.
