### ISSUE TITLE
Shader conversion to GLSL v3.0

### ISSUE THREAD

**Issue by Samotorcan** [BabylonJS/Babylon.js#2139]
Shader conversion to glsl v3.0 has a problem with the following playground https://playground.babylonjs.com/#YMZ7V3

These three lines
```
// varying
varying vec2 vUV
varying vec2 vPosition;
```
are converted to
```
// out out vec2 vUV;
out vec2 vPosition;
```

As you can see there is a missing new line between the two out words.

When you add a new line manually everything works fine.
```
// varying

varying vec2 vUV
varying vec2 vPosition;
```

Version: v3.0-alpha

**Comment by sebavan** [comment]
Also reported here. http://www.html5gamedevs.com/topic/30388-unable-to-compile-effect-error/

**Comment by sebavan** [comment]
The issue is coming from the replacement in the comment (varying is replaced), I am making a fix for it, during this time, you can workaround it by not placing variyng at the end of your comment line.

https://playground.babylonjs.com/#YMZ7V3#2
