### ISSUE TITLE
light.excludedOnlyMeshes bug

### ISSUE THREAD

**Issue by kschiffer** [BabylonJS/Babylon.js#2156]
I'm experiencing a weird issue using the `includedOnlyMeshes` method of a point light. I have loaded two OBJ models into the scene and what I am trying to achieve is to have a point light for each, that is only illuminating the single mesh.

Here's the important part of my code:

```javascript
var loader = new BABYLON.AssetsManager(scene);

var displayTask = loader.addMeshTask('mon_viskura', '', 'models/', 'monitor_viskura.obj');

displayTask.onSuccess = function(task) {
  task.loadedMeshes[0].position = new BABYLON.Vector3(10, 0, 20);
  task.loadedMeshes[0].rotation.y = deg2rad(-140);
  display = task.loadedMeshes[0];
};

var iphoneTask = loader.addMeshTask('iphone', '', 'models/', 'iphone.obj');
iphoneTask.onSuccess = function(task) {
  task.loadedMeshes[0].scaling = new BABYLON.Vector3(0.9, 0.9, 0.9);
  task.loadedMeshes[0].position = new BABYLON.Vector3(3, -7, 20);
  task.loadedMeshes[0].rotation.y = deg2rad(10);
  iphone = task.loadedMeshes[0];
};

loader.onFinish = function() {
  var light = new BABYLON.PointLight('Omni0', new BABYLON.Vector3(0, 0, 0), scene);
  light.includedOnlyMeshes = [iphone];
  light.diffuse = new BABYLON.Color3(1, 1, 1);
  light.specular = new BABYLON.Color3(1, 1, 1);
  light.intensity = 10;
  light.range = 300;

  engine.runRenderLoop(function() {
    scene.render();
  });
};

loader.load();
```

However the light is still illuminating both meshes, although I used the `includedOnlyMeshes` method on my scene light. Though it seems to exclude other objects I have in the scene, like a Sphere.
Am I doing something wrong or is there indeed an issue here?

**Comment by sebavan** [comment]
Thank you for reporting the issue, I can reproduce it here: https://www.babylonjs-playground.com/#8INCIV#4
I will take a look ASAP

**Comment by sebavan** [comment]
Found the culprit, could you use .includedOnlyMeshes.push instead of affecting the array ? 

I will later make a fix for the array affectation:

https://www.babylonjs-playground.com/debug.html#8INCIV#5

**Comment by sebavan** [comment]
This can now work as you can see on this playground:
https://www.babylonjs-playground.com/#8INCIV#8
