### ISSUE TITLE
Raytracing doesn't work for skeletal animations

### ISSUE THREAD

**Issue by henryJack** [BabylonJS/Babylon.js#2220]
Raytracing (similar to this example http://www.babylonjs-playground.com/#KNE0O#17) doesn't seem to work on skeletal animations whilst they are animating. Is this a known limitation of BABYLON.Skeleton and BABYLON.Bone?

**Comment by deltakosh** [comment]
It is a known limitation. Bones are animated GPU side so out of CPU reach
There is an option to compute bones on CPU side but performance will be terrible
