### ISSUE TITLE
Including package.json in repo?

### ISSUE THREAD

**Issue by jasonayre** [BabylonJS/Babylon.js#2229]
Trying to try out the new GUI stuff in preview version, I'm using yarn/npm - Trying to install directly from github, i.e.

yarn add https://github.com/BabylonJS/Babylon.js.git#preview

Is there a necessary reason for not having the package.json file in the root? If not, can we git unignore / add that file for us yarn users? (I would think it would break NPM installation from source as well). Also can't develop against it using yarn link, etc

Another NPM build with the GUI stuff would be great also

**Comment by deltakosh** [comment]
Please update the npm package to include guide and do a PR
Regarding the package.json not being at root: I agree:).
We need to fix it
(Ping @sebavan)

**Comment by jasonayre** [comment]
Cool, I tried getting it to build properly, couldn't for some reason. Eventually gave up on it and included the files directly in my project. I will try and untangle it when I have more time.

**Comment by deltakosh** [comment]
@jasonayre : You are mentioning this file correct ?
https://github.com/BabylonJS/Babylon.js/blob/master/Tools/Npm/package.json

**Comment by deltakosh** [comment]
btw I've just published bjs 3.0.1-beta on npm (including GUI)

**Comment by sebavan** [comment]
Would be great to do it for 3.0, have it only at the root with auto deploy to npm of preview on any push to preview.
