### ISSUE TITLE
Error when destroying Lines in preview release

### ISSUE THREAD

**Issue by jasonayre** [BabylonJS/Babylon.js#2231]
Getting the following error when trying to destroy a CreateLines mesh,after upgrading to the preview release

Uncaught TypeError: Cannot set property material of [object Object] which has only a getter

More of the error:

```
client.js:112081 Uncaught TypeError: Cannot set property material of [object Object] which has only a getterMaterial.dispose @ client.js:112081ShaderMaterial.dispose @ client.js:113625LinesMesh.dispose @ client.js:113603destroyCurve @ client.js:149515CardTargetPicker.onMouseMove @ client.js:149448
3client.js:134998 after children required
```

- I tried to reproduce in playground but seems like it's only in the preview release. 

https://www.babylonjs-playground.com/#SGU89D

^ you won't see the issue, but that's essentially all I'm doing in my project to trigger that error

**Comment by deltakosh** [comment]
There must be something else as the Playground uses the latest preview:(

**Comment by jasonayre** [comment]
Hmmm didn't realize, k I will continue to debug in project. Thanks for the freakishly fast response :)

**Comment by deltakosh** [comment]
My pleasure:)
