### ISSUE TITLE
Issues compiling with typescript.

### ISSUE THREAD

**Issue by jmitchell89** [BabylonJS/Babylon.js#2251]
I'm trying to write a simple game in nw.js and I am using typescript/babel/webpack and babylon.js.

I can't seem to get the `HTMLCanvasElement` type  to be the same as the babylonjs type. I get the error:
```
message: 'Argument of type 'HTMLCanvasElement' is not assignable to parameter of type 'HTMLCanvasElement'.
  Types of property 'getContext' are incompatible.
    Type '{ (contextId: "2d", contextAttributes?: Canvas2DContextAttributes): CanvasRenderingContext2D; (co...' is not assignable to type '(contextId: "webgl2" | "experimental-webgl2", contextAttributes?: WebGLContextAttributes) => WebG...'.
      Types of parameters 'contextId' and 'contextId' are incompatible.
        Type '"webgl2" | "experimental-webgl2"' is not assignable to type '"2d"'.
          Type '"webgl2"' is not assignable to type '"2d"'.'
```

with this code:

```
let canvas = <HTMLCanvasElement>document.createElement('canvas');
let engine = new BabylonJS.Engine(canvas, true);
```

here is my TS config:

```
{
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "experimentalDecorators": true,
    "module": "es6",
    "moduleResolution": "node",
    "noImplicitAny": false,
    "target": "es6",
    "lib": ["dom", "es6", "scripthost"],
    "types": [
      "history",
      "webpack-env",
      "nw.js",
      "babylonjs"
    ]
  },
  "exclude": [
      "node_modules",
      "build"
  ],
  "compileOnSave": false
}
```

The only other place creating an interface for `HTMLCanvasElement` is in the dom library. Any help would be appreciated! 👍

**Comment by deltakosh** [comment]
Are using latest TS 2.2?

**Comment by jmitchell89** [comment]
I am using typescript 2.3.2.

**Comment by deltakosh** [comment]
Can you try to also reference the webgl2.d.ts we have in the repo?

**Comment by jmitchell89** [comment]
I get the same error when I reference the `webgl2.d.ts` file.

**Comment by deltakosh** [comment]
This should work as this is where we define the specific get context
Try to add it last?

**Comment by jmitchell89** [comment]
I am referencing directly in my app.ts file. Here it is:
```
/// <reference path="../webgl.d.ts" />
import BABYLON from 'babylonjs';

let width = 1280;
let height = 720;

interface Gui {
    App: nw.App;
    Clipboard: nw.Clipboard;
    Menu: nw.Menu;
    MenuItem: nw.MenuItem;
    Screen: nw.Screen;
    Shortcut: nw.Shortcut;
    Tray: nw.Shell;
    Window: nw.Window;  
}

declare var gui: Gui;

gui.Window.get().width = width;
gui.Window.get().height = height;

let canvas:HTMLCanvasElement = <HTMLCanvasElement>document.createElement('canvas');
canvas.width = width;
canvas.height = height;
document.appendChild(canvas);

let engine = new BABYLON.Engine(canvas, true);
```

**Comment by deltakosh** [comment]
And did you add the file in the list of file that TS references?

**Comment by deltakosh** [comment]
There must be something in the config because it works in bjs

**Comment by jmitchell89** [comment]
I tried adding the file to the tsconfig as well, however there was no change.

**Comment by deltakosh** [comment]
I don't know what to add unfortunately
The definition you need is in the webgl2.d.ts file

**Comment by jmitchell89** [comment]
I tried this as well with no luck:
```
{
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "experimentalDecorators": true,
    "module": "es6",
    "moduleResolution": "node",
    "noImplicitAny": false,
    "target": "es6",
    "lib": ["dom", "es6", "scripthost"],
    "types": [
      "history",
      "webpack-env",
      "nw.js",
      "babylonjs",
      "webgl2"
    ]
  },
  "exclude": [
      "node_modules",
      "build"
  ],
  "compileOnSave": false
}
```

webgl2 comes from the npm package @types/webgl2.

**Comment by deltakosh** [comment]
Ping @sebavan: any idea?

**Comment by jmitchell89** [comment]
Just as a side note. If I use any it works fine, although that defeats the purpose of having types. Also I'm just starting out but I imagine if I needed to manipulate the canvas I might have problems later on by using any on the canvas.

**Comment by deltakosh** [comment]
Using any will fix it for sure and you won't have any issue later but I agree this is not how we want to use TS

**Comment by sebavan** [comment]
Would be great if you could share a project skeleton (I do not see anything obvious) ?

Earlier in the comments I noticed 
/// <reference path="../webgl.d.ts" /> 
and not 
/// <reference path="../webgl2.d.ts" />

I am only wondering if that could be it ???

**Comment by jmitchell89** [comment]
Here is an example. 

[Test.zip](https://github.com/BabylonJS/Babylon.js/files/1059250/Test.zip)

You do need to setup nwbuild separately to actually run it however it could be easily changed to run in a browser instead using webpack-dev-server. I also use yarn to install my packages instead of npm.

**Comment by sebavan** [comment]
This is because our typings are not deployed to the typings folder during install.
You can manually add a babylonjs folder under @typings or your chosen root and insert ababylon.d.ts renamed in index.d.ts to double check.

It works if you reference the babylon declaration file as a workaround or add it in your tsconfig in the include files:
``` /// <reference path="../node_modules/babylonJS/babylon.d.ts" />```  (used npm here but should be pretty similar to you)

**Comment by jmitchell89** [comment]
Ah that does indeed work! It makes sense because my typings folder was empty..
