### ISSUE TITLE
Scalar vector math

### ISSUE THREAD

**Issue by jmitchell89** [BabylonJS/Babylon.js#2263]
It sucks that we can't have proper vector operators(Javascript/Typescript don't have any). :( 

It would be nice if we could get some more vector math method overrides for instance:

`myVector3.divide(myNumber);`
Where currently I would have to do:
`myVector3.divide(new Vector3(myNumber, myNumber, myNumber));`

There is no subtraction method either which means: you have to do something like this:
`new BABYLON.Vector3(v1.x - v2.x, v1.y - v2.y, v1.z - v2.z);`

I think I can just extend the `BabylonJS.Vector3` class but I feel as though this should be apart of the `BabylonJS.Vector3` class in the first place.

**Comment by deltakosh** [comment]
You can scale a vector with myvector.scale(1/number)
