### ISSUE TITLE
Loaders are unavailable through NPM

### ISSUE THREAD

**Issue by zakhenry** [BabylonJS/Babylon.js#2265]
Not sure if I'm doing something wrong but I am unable to get the objLoader from NPM? I feel like I should be able to do something like 

```ts
import { Component, OnInit } from '@angular/core';
import {
  Engine, ArcRotateCamera, HemisphericLight, Scene, Vector3, AssetsManager, Color3,
} from 'babylonjs';

import 'babylonjs/loaders/objFileLoader';
```
To register the file loader with babylon for the use with `AssetsManager` etc.

However, there doesn't appear to be any loader code available in the npm deployed package, I suspect they would need to be defined in the `files` entry in https://github.com/BabylonJS/Babylon.js/blob/master/package.json#L17

OR, the individual loaders could be bundled individually, perhaps under a namespace like

```sh
npm install @babylonjs/core @babylonjs/obj-loader
```

**Comment by deltakosh** [comment]
I see no problem to add it to the npm package
Please do a PR to update the package.json

**Comment by zakhenry** [comment]
Hey @deltakosh  thanks for adding the file reference, however I still can't get the import to function I think because between imports the global binding of `BABYLON` is lost somehow, so when the loader tries to `SceneLoader.RegisterPlugin`, there is no instance of `BABYLON` available.

Scratching my head on how best to resolve it, maybe the pattern that rxjs uses for adding operators might be useful? https://github.com/ReactiveX/rxjs#es6-via-npm

**Comment by deltakosh** [comment]
Do you mind trying a PR?

**Comment by Toktik** [comment]
+1
