### ISSUE TITLE
HighlightLayer no longer works

### ISSUE THREAD

**Issue by zhutq** [BabylonJS/Babylon.js#2284]
The highlight layer feature described here https://doc.babylonjs.com/tutorials/highlight_layer no longer works.
Objects added to highlight layer are black.
Playground: http://www.babylonjs-playground.com/#1KUJ0A#0

**Comment by sebavan** [comment]
I am on it and this should be fixed soon, thank you for reporting.

**Comment by sebavan** [comment]
Fixed, thanks again for reporting it.
