### ISSUE TITLE
Semantic Error  TS2430: Interface 'WebGL2RenderingContext' incorrectly extends interface 'Web GLRenderingContext' in baylon.d.ts 3.0.0 preview

### ISSUE THREAD

**Issue by ParadineG** [BabylonJS/Babylon.js#2285]
error TS2430: Interface 'WebGL2RenderingContext' incorrectly extends interface 'Web
GLRenderingContext'.
  Types of property 'texImage2D' are incompatible.
    Type '{ (target: number, level: number, internalformat: number, width: number, height: number, border: ...'
 is not assignable to type '{ (target: number, level: number, internalformat: number, width: number, height: nu
mber, border: ...'. Two different types with this name exist, but they are unrelated.
      Types of parameters 'pixels' and 'pixels' are incompatible.
        Type 'ArrayBufferView | null' is not assignable to type 'ArrayBufferView | undefined'.
          Type 'null' is not assignable to type 'ArrayBufferView | undefined'.

**Comment by deltakosh** [comment]
Can you give us some context?

**Comment by ParadineG** [comment]
I compiled with gulp my own code:
"gulp": "3.9.1",
"gulp-typescript": "3.1.7"
And used your babylon.js and babylon.d.ts from dist/preview releases.
With typescript compiler options: 
    "compilerOptions": {
        "target": "es5",
        "module": "none",
        "strictNullChecks": true,
        "allowUnusedLabels": false,
        "noImplicitReturns": true,
        "sourceMap": true,
        "baseUrl": "."
    }
And got only this error on compilation.

**Comment by deltakosh** [comment]
what if you clone the repo and try to compile it?

**Comment by ParadineG** [comment]
I prefer not to as it will take time to configure.
But I made small project for vscode to reproduce this error [here.](http://moleql.com/api/rootFolder.zip)
Was using node version 8 sth. Other instructions at readme file there.

**Comment by deltakosh** [comment]
Can you confirm you were using latest version from the repo?

**Comment by ParadineG** [comment]
Yes.
From here: https://github.com/BabylonJS/Babylon.js/tree/master/dist/preview%20release
Tried again against this commit: https://github.com/BabylonJS/Babylon.js/commit/4606804c4d38554a4d50fa91a96fcc70b8dae57a

**Comment by deltakosh** [comment]
Fixed by https://github.com/BabylonJS/Babylon.js/commit/2716f09725eee6a0f75be998a8097a0f5c0851cc
