### ISSUE TITLE
package.json main points to the wrong file

### ISSUE THREAD

**Issue by meltedspark** [BabylonJS/Babylon.js#2294]
Currently main in package.json points to a non-existing file in root, which makes it impossible to use with webpack without additional tweaks. 

```
},
"main": "babylon.max.js",
"files": [
```
It should point to the actual `babylon.max.js` which is `dist/preview release/babylon.max.js`.
I can create a PR if needed.

**Comment by deltakosh** [comment]
Please do:)

**Comment by meltedspark** [comment]
#2295
