### ISSUE TITLE
  babyloncomponentselector.azurewebsites.net is currently unable to handle this request.

### ISSUE THREAD

**Issue by proehlen** [BabylonJS/Babylon.js#2303]
Have been getting a http 500 error on the component selector website for nearly 24 hours now.  Really hoping to use the component selector because I'm struggling to use Babylon with the procedural grass texture using the CDN or NPM versions.

**Comment by deltakosh** [comment]
Seems to work for me. Can you try again?

**Comment by proehlen** [comment]
Urgh, working now.  I swear it wasn't working for nearly a full day when I tried a dozen times or so.

Thanks for the reply and sorry to waste your time.
