### ISSUE TITLE
Add spritesheet support to GUI.

### ISSUE THREAD

**Issue by ParadineG** [BabylonJS/Babylon.js#2345]
Its really common to use spritesheets for GUI also as its bandwidth-friendly and makes it easier to organize GUI images for animations and also add all GUI elements especially same size, under one image.

**Comment by deltakosh** [comment]
Good idea. I'll do it

**Comment by benaadams** [comment]
Texture packer is a common spritesheet tool https://www.codeandweb.com/texturepacker

**Comment by ParadineG** [comment]
Thank You! 
I know that packer its really good.
