### ISSUE TITLE
GLTF loader failing with certain buffer view byte offsets

### ISSUE THREAD

**Issue by jamesgk** [BabylonJS/Babylon.js#2352]
The GLTF loader fails when an accessor with type VEC3 uses a buffer view with a non-multiple-of-4 byte offset. I believe this kind of GLTF data is valid. [This code](https://github.com/BabylonJS/Babylon.js/blob/6801156e1c696c43526b73eb104b1f07c66afefd/loaders/src/glTF/2.0/babylon.glTFLoaderUtils.ts#L96) causes the crash.

Would it be possible to slice up buffers per-bufferView before creating these new typed arrays for accessors? I understand this would incur a performance penalty but I don't see any other way to deal with this scenario.

**Comment by deltakosh** [comment]
ping @bghgary

**Comment by bghgary** [comment]
@jamesgk Yes, this kind of data is invalid. See https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#data-alignment

Do you have an example of this glTF asset that I can review?

**Comment by jamesgk** [comment]
Ah, thanks, and sorry I didn't see that before. I don't think I can share my GLTF assets, but they were converted from collada files with assimp so it would seem the converter is at fault.

**Comment by bghgary** [comment]
@jamesgk I think assimp exports glTF 1.0 files. The restrictions on glTF 1.0 is a bit different.

https://github.com/KhronosGroup/glTF/tree/master/specification/1.0#bufferview-and-accessor-byte-alignment

But it looks like you pointed to the 2.0 BJS glTF loader code. Did you get a 2.0 glTF from assimp somehow?

**Comment by jamesgk** [comment]
Right, my mistake, I'm definitely working with glTF 1.0, and this is the code I meant to link to:
https://github.com/BabylonJS/Babylon.js/blob/aec514120ae0df53bbd56ba39b4fe7298d04ea61/loaders/src/glTF/1.0/babylon.glTFLoaderUtils.ts#L171

Still, I think the issue is the same for 1.0 an 2.0 -- a Float32Array is being created from a buffer so the byte offset must be a multiple of 4.

**Comment by bghgary** [comment]
Agreed. I was just wondering if someone was working on glTF 2.0 for assimp. 😮

**Comment by jamesgk** [comment]
I don't think anyone has started on that, though a github issue was opened for it. That's progress! 😛
