### ISSUE TITLE
About DAE(collada) file format

### ISSUE THREAD

**Issue by TomAditazz** [BabylonJS/Babylon.js#2365]
Hi,

I'm going to load collada files into babylon canvas. I saw in http://doc.babylonjs.com/whats-new page, it says "Support for DAE (COLLADA) file format".
My question is is there a demo or document to see how to do it?

Thanks,
Tom

**Comment by deltakosh** [comment]
Hey
this is done through the FBX exporter:https://github.com/BabylonJS/Babylon.js/tree/master/Exporters/FBX

(But if you have the option, it could be safer to use gltf instead which is fully supported)

**Comment by TomAditazz** [comment]
Thanks for reply. Two more questions:
1. I checked this FBX folder but have no idea how to implement it, it's like a out side converter or also a javascript library?
2. You mean using gltf as the converter?

**Comment by deltakosh** [comment]
1. It is a windows command line tool :(
2. No I meant (But not sure if this is possible): use gltf as your file format
