### ISSUE TITLE
PBR refractionTexture to default to environmentTexture when linkRefractionWithTransparency is true ?

### ISSUE THREAD

**Issue by benaadams** [BabylonJS/Babylon.js#2368]
As per reflectionTexture in https://github.com/BabylonJS/Babylon.js/pull/2238

**Comment by sebavan** [comment]
I may add a helper for it but we do not want always refraction.

Reflection is a mandatory maybe could do if linkRefractionWithTransparency is true ?

**Comment by benaadams** [comment]
> maybe could do if linkRefractionWithTransparency is true ?

Makes sense

**Comment by benaadams** [comment]
Though... I think for the objects I'm rendering what I'd like to do is screen space refraction.

So something like

1. Render non-transparent (fb1)
2. swap framebuffer (fb2)
3. Render transparent refracting using (fb1); outside screen use environment + record depth + stencil
4. swap back (fb1)
5. Render (fb2) onto (fb1) using stencil and depth test
6. Present (fb1)

If that makes sense?

**Comment by deltakosh** [comment]
It does and it is kind of what we are doing with reflection probes

**Comment by deltakosh** [comment]
http://www.babylonjs.com/demos/refraction/

**Comment by deltakosh** [comment]
Kind of:) but I like the idea a lot:)

**Comment by benaadams** [comment]
That's a lot heavier weight? Though, will give it a go :)

**Comment by deltakosh** [comment]
It helps when you have curved surface where the retracted pixel is out of screen.

But I also like your screen space idea

**Comment by sebavan** [comment]
Yup I ll do if both are linked together 👍

**Comment by sebavan** [comment]
Done :-)
