### ISSUE TITLE
Rendering error of GLTF 2.0 models with interleaved attributes

### ISSUE THREAD

**Issue by AngeloReppucci** [BabylonJS/Babylon.js#2374]
According to the gltf 2.0 spec, on the bufferview there is a byteStride property to specify the byte distance beetween consecutive elements. 
This seems not taken in consideration in the gltf loader.

To test the issue, load the BoxInterleaved sample of the KhronosGroup/glTF-Sample-Models repo [https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/BoxInterleaved](url)

**Comment by bghgary** [comment]
Yes, adding support for this is in our backlog. This sample model will help. Thanks!
