### ISSUE TITLE
Actions always set to last frame upon export

### ISSUE THREAD

**Issue by FunFetched** [BabylonJS/Babylon.js#2416]
animation.py line #104->append_range() introduces an issue where the scene's current frame is changed as the range is iterated through, but not restored upon completion. This leads to all animated objects being exported in their final positions/orientations, regardless of the current frame in the Timeline.

I managed to resolve the issue on my end in f_curve_animatable.py. I added `currentFrame = bpy.context.scene.frame_current` before the `for action in bpy.data.actions:` loop on line 37, restoring the scene's current frame immediately after this loop with `bpy.context.scene.frame_set(currentFrame)`.

**Comment by deltakosh** [comment]
Ping @Palmer-JC
