### ISSUE TITLE
babylon.2.5.d.ts errors

### ISSUE THREAD

**Issue by raould** [BabylonJS/Babylon.js#2441]
(i also get these kinds of errors going back and trying to use 2.4, so my current guess is that either I am doing something dumb wrong in my setup, or that the version of tsc I am using is not whatever BabylonJS actually works with?)

Babylon release 2.5
Ubuntu Linux 14.04 64 bit
tsc 2.1.4

38c63ab7574438eb74965d7c09af8e3c  lib/babylon.2.5.d.ts
709fd7a736e6c5f716fee0b0a0fd24dc  lib/babylon.2.5.js

(A) using tsconfig.json

```
{
    "compilerOptions": {
        "module": "system",
        "noImplicitAny": true,
        "removeComments": true,
        "preserveConstEnums": true,
        "sourceMap": true,
        "outFile": "out/game.js"
    },
    "include": [
        "src/**/*.ts",
	"lib/**/*.ts"
    ]
}
```

```
lib/babylon.2.5.d.ts(412,131): error TS7006: Parameter 'ArrayBuffer' implicitly has an 'any' type.
lib/babylon.2.5.d.ts(10918,75): error TS7006: Parameter 'i' implicitly has an 'any' type.
lib/babylon.2.5.d.ts(11012,54): error TS7006: Parameter 'item' implicitly has an 'any' type.
lib/babylon.2.5.d.ts(11024,50): error TS7006: Parameter 'i' implicitly has an 'any' type.
lib/babylon.2.5.d.ts(11928,74): error TS7006: Parameter 'ArrayBuffer' implicitly has an 'any' type.
lib/babylon.2.5.d.ts(12037,31): error TS7006: Parameter 'AbstractMesh' implicitly has an 'any' type.
src/Main.ts(9,3): error TS2322: Type 'HTMLElement' is not assignable to type 'HTMLCanvasElement'.
  Property 'height' is missing in type 'HTMLElement'.
```

(B) using command line tsc

```
$ tsc  lib/babylon.2.5.d.ts src/Main.ts 
src/Main.ts(9,3): error TS2322: Type 'HTMLElement' is not assignable to type 'HTMLCanvasElement'.
  Property 'height' is missing in type 'HTMLElement'.
```

**Comment by deltakosh** [comment]
Please use v3.0 from dist/preview release folder

**Comment by raould** [comment]
thanks!

can you tell me what was happening so i can understand e.g. in case it shows up again? am i on the wrong version of typescript? and/or is there some reason the .d.ts file for 2.5(.1) won't be fixed? i am just not familiar enough with ts to know.

**Comment by deltakosh** [comment]
No worry :) bjs 2.5 was done with a previous version of TS and thus we added some missing typings in bjs core 
Now these typings are in TS so we removed them from bjs 3.0
