### ISSUE TITLE
Create a particles helper library

### ISSUE THREAD

**Issue by deltakosh** [BabylonJS/Babylon.js#2445]
Something like createFire or createSmoke

**Comment by deltakosh** [comment]
https://playground.babylonjs.com/#PSK6N1

**Comment by yovanoc** [comment]
I can do that.
`/src/Helpers` is this the right place for that?
I will start this very soon.

I'm open for more create methods like that :)

**Comment by deltakosh** [comment]
The idea is to create one-liner for smoke, fire, etc...
I think we can  have it in helpers folder with a static class named ParticleHelper or something along this line 
Assets should default to ressources saved to assets.babylonjs.com (which is mapped to the /assets folder)
The idea is not to have particles setup hard written in the helper.
I suggest to set up a folder in /assets named particles where particles textures and a json file describing each setup should be

The json file could describe all parameters of each particle setup

From a user standpoint, I see it like that:

```
var system = ParticleHelper.Create("fire", true);
```

The first parameter will look for a configuration named fire in the central json. The second one indicates that I want a GPU system (if the configuration allows it)


I hope this makes sense:)
Thanks a lot for your appreciated help!

**Comment by yovanoc** [comment]
Ok, nice, but the third argument for the ParticleSystem constructor is the Scene, so, Is there a way to get the scene, or we have to pass it to the main create() method too?

**Comment by deltakosh** [comment]
Right:) we need a third one (optional as Engine.LastCreatedScene can be used)

**Comment by yovanoc** [comment]
Great, I'll make a first try. Then we can discuss around that

**Comment by deltakosh** [comment]
Wonderful!!

**Comment by yovanoc** [comment]
Also, how can I correctly read a .json file in the /assets/particles folder, knowing that it becomes the domain name you told me?

For now, I've already put that for basic textures that I will use but can I use it for the json file properly?

```javascript
private static _baseAssetsUrl = "https://assets.babylonjs.com/particles/";
```

**Comment by deltakosh** [comment]
This is fine!

**Comment by yovanoc** [comment]
Where do you want I add a unit test for that?

**Comment by deltakosh** [comment]
in /tests/unit please :)

**Comment by yovanoc** [comment]
Yeah, of course, but i add a new file?

**Comment by deltakosh** [comment]
Sure thing!

**Comment by yovanoc** [comment]
But why there are no scripts in package.json to run tests? how do I launch these tests so?
