### ISSUE TITLE
Add a tool to simplify material creation

### ISSUE THREAD

**Issue by deltakosh** [BabylonJS/Babylon.js#2447]
Like createPlastic or createMetal

**Comment by HeadClot** [comment]
Maybe a node based shader creation tool would be beneficial to Babylon.js?

Have a look a [Source Shader editor](https://www.youtube.com/watch?v=82AMwQGjc8Y), Unreal Engine's Material Editor, [Amplify Shader Editor](http://amplify.pt/unity/amplify-shader-editor/), etc.

This would also be a great first step towards some awesome tooling for Babylon.js

**Comment by deltakosh** [comment]
It was more tooling in the code like material.createGlass or createGOld etc..

**Comment by deltakosh** [comment]
Will be fixed by #6012
