### ISSUE TITLE
canvas2d crash with null pointer on 'getUVsForCustomSize'

### ISSUE THREAD

**Issue by xiaobaker** [BabylonJS/Babylon.js#2474]
this crash happens really randomly but often enough to be a problem. hope the callstack gives enough clue on what it is.

TypeError: Cannot read property 'getUVsForCustomSize' of null
n._bindCacheTarget
http://localhost:3000/babylon.canvas2d.min.js:7:27667
n._groupRender
http://localhost:3000/babylon.canvas2d.min.js:7:21423
n._render
http://localhost:3000/babylon.canvas2d.min.js:11:13757
e.callback
http://localhost:3000/babylon.canvas2d.min.js:10:15949
e.notifyObservers
http://localhost:3000/babylon.min.js:2:30727
r.render
http://localhost:3000/babylon.min.js:10:24319
(anonymous function)
src/index.js:36
  33 | 
  34 | // run the render loop
  35 | engine.runRenderLoop(() => {
> 36 |   scene.render();
  37 |   update(engine.getDeltaTime());
  38 | });
  39 | 
View compiled

**Comment by deltakosh** [comment]
Hello, canvas2d is no more a core component of babylonjs and was moved to extensions: https://github.com/BabylonJS/Extensions

Perhaps you should think about using doc.babylonjs.com/overviews/gui
