### ISSUE TITLE
Support 360 videos

### ISSUE THREAD

**Issue by deltakosh** [BabylonJS/Babylon.js#2500]

**Comment by RaananW** [comment]
Are you referring to movies like this - https://www.youtube.com/watch?v=2IaL8xTpK24 ? or 3D VR?

**Comment by deltakosh** [comment]
something like that but encapsulated and with video as well :)
https://www.babylonjs-playground.com/#VUECIW#1

**Comment by deltakosh** [comment]
https://www.babylonjs-playground.com/#UU7RQ#58

**Comment by deltakosh** [comment]
https://www.babylonjs-playground.com/#UU7RQ#61

**Comment by littlebigben** [comment]
Thanks for this new feature! 
Do you now when top/bottom cut issue will be fixed?
Thanks :)

**Comment by deltakosh** [comment]
Early January :)

**Comment by littlebigben** [comment]
A nice gift for a new year! It will allow me to do my 360 video online editor :)
Thanks!

**Comment by littlebigben** [comment]
Hello David, 
hope you had good holidays!

Working on my project this week, I found two things that could interest you if you haven't try yet:
- I tried to rotate the skybox, but it seams that when we use VideoTexture the skybox cannot be rotate
- When the camera look at forward, the video is not centered (it's looking at +90 degrees)

Thanks a lot for your work! :)

**Comment by deltakosh** [comment]
Hey:)
You can rotate the skybox but it won't change anything visually as the projection of the texture is in view space. This is one of the thing this issue will fix
Can you repro on the playground foe the second issue?

**Comment by littlebigben** [comment]
I copy/paste your sample : https://www.babylonjs-playground.com/#682D2P
The original video : https://yoda.blob.core.windows.net/videos/uptale360.mp4

As you can see we should aim the center of the video (the white building).

**Comment by littlebigben** [comment]
By the way, I don't know if it is an issue, but I cannot turn my camera : http://www.html5gamedevs.com/topic/34957-rotate-camera-in-vr/

**Comment by deltakosh** [comment]
OK so the aim problem will be fixed Ed by this issue 
For you other question @raananw gave you an answer :)

**Comment by DavidHGillen** [comment]
Taking a look at this in the new year, along with @gskinner-Blair

**Comment by gSkinner-Blair** [comment]
yup ^

**Comment by baludwig** [comment]
yup ^

**Comment by deltakosh** [comment]
Main code is done. Just need the documentation + samples

**Comment by deltakosh** [comment]
http://doc.babylonjs.com/how_to/360videodome
