### ISSUE TITLE
ReflectionProbe is broken

### ISSUE THREAD

**Issue by vanRepin** [BabylonJS/Babylon.js#2512]
https://www.babylonjs-playground.com/#8HA5Y6

seems like the couse is this commit: 
https://github.com/BabylonJS/Babylon.js/commit/a0e7b234ceda79496d3843a21400d53cf16e9e21

**Comment by deltakosh** [comment]
I'm on it :)
Thanks for reporting.

**Comment by vanRepin** [comment]
cheers!

**Comment by vanRepin** [comment]
I tryed to fix it like this:
![image](https://user-images.githubusercontent.com/1905474/28123542-8014ffc2-6721-11e7-82cf-31f91bd42bb7.png)
but not sure, if it's valid solution

**Comment by vanRepin** [comment]
nvm, seems like this will break spherical harmonics generation

**Comment by deltakosh** [comment]
Yeah I have the feeling that I forgot to unbind the texture somehow. See the console here: http://www.babylonjs.com/demos/refprobe/

**Comment by deltakosh** [comment]
ok found the bug :) Update in progress

**Comment by deltakosh** [comment]
Fixed now.
Here is a better version to test: https://www.babylonjs-playground.com/#8HA5Y6#2

**Comment by vanRepin** [comment]
cool, thank ya!
