### ISSUE TITLE
Create headless version of babylon.js

### ISSUE THREAD

**Issue by deltakosh** [BabylonJS/Babylon.js#2529]
A version which could be used with no DOM

**Comment by nicktendo** [comment]
:-)

**Comment by furcatomasz** [comment]
Great idea! I still waiting for headless version of BJS. Do you have ETA for that?

**Comment by deltakosh** [comment]
Not yet unfortunately

**Comment by a-galminas** [comment]
Any news on headless?

**Comment by deltakosh** [comment]
Not yet. I will post here when the work will start

**Comment by deltakosh** [comment]
https://github.com/BabylonJS/Babylon.js/commit/4c1e3fecf38f934d15010fbe6d28a10d7f6d8d02
http://doc.babylonjs.com/generals/nullengine

**Comment by furcatomasz** [comment]
Yeah!!! :) Thanks @deltakosh

**Comment by ransico** [comment]
Updated documentation link: http://doc.babylonjs.com/classes/3.1/nullengine
