### ISSUE TITLE
Make things more Webpack friendly

### ISSUE THREAD

**Issue by lpadukana** [BabylonJS/Babylon.js#2530]
Using babylonjs core with webpack/npm was straight forward. However, getting webpack working with `materialsLibrary`, `inspector (babylon-v3.0)`, etc. turned out to be complicated (I did find forum posts and some work arounds are possible through webpack `loaders`, `HtmlWebpackPlugin`, etc.). Depending on what proportion of babylon community is interested in webpack, could you provide stencils/recommendations on webpack integration as part of standard documentation?

**Comment by deltakosh** [comment]
Can you suggest some improvements?

**Comment by lpadukana** [comment]
Other than providing a webpack stencil (a starting point that people can adopt/customize), we could make other files in `dist/` available through the npm `babylonjs` distribution (for example `materialsLibrary/*`, `inspector/*`, etc.) or make them available as separate npm distributions if core is considered sacrosanct.

**Comment by deltakosh** [comment]
I'll update npm package then :)

**Comment by lpadukana** [comment]
Thanks @deltakosh
