### ISSUE TITLE
gui rendering broken when using SceneOptimization

### ISSUE THREAD

**Issue by xiaobaker** [BabylonJS/Babylon.js#2531]
I noticed that when SceneOptimizer downgrades the render quality, gui TextBlock rendering would get messed up. Positioning will be off and the text would appear to be scaled. I was using LowDegradationAllowed, and rendering a TextBlock linked to a mesh. 

Any idea how to avoid this?

**Comment by deltakosh** [comment]
I can fix it but I will need a repro on the playground

**Comment by deltakosh** [comment]
Up?

**Comment by xiaobaker** [comment]
will get a playground repro here soon!

**Comment by xiaobaker** [comment]
https://www.babylonjs-playground.com/#D7K1EP

keep looking at the scene for a few seconds and you should be able to see the repro.

**Comment by deltakosh** [comment]
Fixed. THe control will automatically unlink if a mesh is disposed.
Beware here, the optimization will also change the DPI so everything will look bigger.

**Comment by xiaobaker** [comment]
thanks! will it automatically get re-linked though?

**Comment by deltakosh** [comment]
Nope because there is no obvious mesh to attach to

**Comment by xiaobaker** [comment]
seems like when optimization happens i should just recreate the gui?

**Comment by deltakosh** [comment]
This is a good option because the dpi can change and meshes can be disposed in order to be merged together
