### ISSUE TITLE
Simple GLTF model problem

### ISSUE THREAD

**Issue by nbouayad** [BabylonJS/Babylon.js#2534]
Hello,
I have been working with VRML and GlTf seems promising.
I am writing a converter from VRML to GlTF,but I think that there is something which I am doing wrong because I cannot even convert a simple VRML to GLTF (Please see the attached files,I including a simple vrml, and the coresponding the gltf/bin.
No validation error, but I always get index out of bounds for OGL DrawElement (Using Babylon.js sandbox viewer), and I am wondering what am I doing wrong.
Thanks in advance.

[test.zip](https://github.com/BabylonJS/Babylon.js/files/1153721/test.zip)

**Comment by deltakosh** [comment]
Hello you should post it to the gltf repo:) 
P
