### ISSUE TITLE
SphericalPolynomial is inverted on Y

### ISSUE THREAD

**Issue by vanRepin** [BabylonJS/Babylon.js#2548]
https://www.babylonjs-playground.com/#A04X1Z#2
![image](https://user-images.githubusercontent.com/1905474/28358209-514eb258-6c6e-11e7-8aa8-b27ed90b9a8f.png)
it looks like world dirrection is calculated incorrectly

**Comment by sebavan** [comment]
Nice catch, you are the first one to try it from probe, I was only focusing on the pre-processed textures. I ll fix it ASAP.

**Comment by vanRepin** [comment]
cool! thx 👍

**Comment by sebavan** [comment]
Should be good now for renderTargetCubeTexture (will be on the pg tomorrow morning).
