### ISSUE TITLE
Visual artefacts with transparent meshes

### ISSUE THREAD

**Issue by vkuchinov** [BabylonJS/Babylon.js#2550]
Hi there,

It seems that current version has an issue with transparent objects. 
A demo for "Transparency and How Meshes Are Rendered" article has these glitches.

[https://www.babylonjs-playground.com/#1PHYB0#6](url)

I have upload a very short video on YouTube, here it is:
[https://youtu.be/0GlRZUb79MU](url)

My example:
[https://yadi.sk/i/6ks16ROe3LCmeu](url)

Is there any existed solution? 
There are some references to RenderManager, which probably has alpha/depth sorting prior to rendering, but I couldn't find any info how to use it.

**Comment by deltakosh** [comment]
Hello this is working as expected. The glitches are here to explain how depth sorting works.

It sorts objects from their center to the camera and then do a back to front rendering.
You can change this and define the order you want by setting ,mesh.alphaIndex to the value you want :)

BTW, please use the forum for questions, it would be easier for community to help then

**Comment by vkuchinov** [comment]
Thanks, a little question to this topic: is it possible to set alphaIndex to mesh faces individually?
So, I could write function for sorting faces by its distance from camera.

**Comment by deltakosh** [comment]
This will be counter performant unfortunately :(

**Comment by vkuchinov** [comment]
So, you are saying that I couldn't solve an issue when an object has these glitches with itself like on my last linked image?

**Comment by deltakosh** [comment]
Not with this technique.
THe ting is that your object is not transparent so why do you want to use transparency with it? If you use only transparency for glasses your should separate the meshes and keep the main object opaque
