### ISSUE TITLE
Highlight when viewed through transparent mesh bug

### ISSUE THREAD

**Issue by AleksaSvitlica** [BabylonJS/Babylon.js#2552]
https://playground.babylonjs.com/#CK01ZE
This playground should illustrate what I believe is incorrect behavior. The sphere has highlighting applied to it and that works fine. However when I place a mesh with a visibility between 0 and 1 in the way the highlighting just turns the entire mesh black.

**Comment by deltakosh** [comment]
You can exclude the alpha blended mesh: https://playground.babylonjs.com/#CK01ZE#1
