### ISSUE TITLE
GLTF 2.0 , children of children nodes are not loaded

### ISSUE THREAD

**Issue by nbouayad** [BabylonJS/Babylon.js#2563]
Hello,
I have a node tree in my GLTF, but apparently, only the first level children are loaded.
I can fix It, but I wanted to know if there was a plan for that.

**Comment by deltakosh** [comment]
ping @bghgary

**Comment by nbouayad** [comment]
After some checks, that only appends when I have empty nodes.Removing them worked...

**Comment by bghgary** [comment]
@nbouayad Can you attach the glTF file? I can take a look.

**Comment by deltakosh** [comment]
Up?
