### ISSUE TITLE
buffer or buffer range not large enough at index 0

### ISSUE THREAD

**Issue by nghenglim** [BabylonJS/Babylon.js#2585]
seems like same issue with https://github.com/BabylonJS/Babylon.js/issues/2052 but that issue is closed.

link to code https://gist.github.com/nghenglim/4115adf5249202fd2e528e7b045a49f8

using https://cdn.babylonjs.com/babylon.js give me error

```
BJS - [21:29:14]: Babylon.js engine (v3.0) launched
index.html:1 [.Offscreen-For-WebGL-0xc45a91d4300]GL ERROR :GL_INVALID_OPERATION : glDrawElements: uniform buffers : buffer or buffer range not large enough at index 0
index.html:1 WebGL: too many errors, no more errors will be reported to the console for this context.
```

replacing it with https://cdnjs.cloudflare.com/ajax/libs/babylonjs/2.5.0/babylon.js then everything works fine.

using Dell Inspiron 5547 with lubuntu 14.04 LTS chrome Version 58.0.3029.81 (64-bit)
sudo lshw -C video output

```
*-display               
       description: VGA compatible controller
       product: Haswell-ULT Integrated Graphics Controller
       vendor: Intel Corporation
       physical id: 2
       bus info: pci@0000:00:02.0
       version: 0b
       width: 64 bits
       clock: 33MHz
       capabilities: msi pm vga_controller bus_master cap_list rom
       configuration: driver=i915 latency=0
       resources: irq:64 memory:b0400000-b07fffff memory:c0000000-cfffffff ioport:5000(size=64)
  *-display
       description: Display controller
       product: Topaz XT [Radeon R7 M260/M265]
       vendor: Advanced Micro Devices, Inc. [AMD/ATI]
       physical id: 0
       bus info: pci@0000:03:00.0
       version: 00
       width: 64 bits
       clock: 33MHz
       capabilities: pm pciexpress msi bus_master cap_list rom
       configuration: driver=fglrx_pci latency=0
       resources: irq:67 memory:a0000000-afffffff memory:b0000000-b01fffff ioport:3000(size=256) memory:b0900000-b093ffff memory:b0940000-b095ffff
```

the http://playground.babylonjs.com v3.1-alpha and v3.0 are both giving same error

**Comment by deltakosh** [comment]
Can you provide a repro scene on the background where you see this issue?

**Comment by deltakosh** [comment]
BTW this seems related to a bad webgl2 implementation in your browser. You can force bjs to only use webgl1 when creating the engine by using disableWebGL2Support=false in the options parameter

**Comment by nghenglim** [comment]
@deltakosh is using the code https://gist.github.com/nghenglim/4115adf5249202fd2e528e7b045a49f8,
launch it with chrome. 

How can I set disableWebGL2Support=false? Is it somewhere at `var engine = new BABYLON.Engine(canvas, true);`?

**Comment by nghenglim** [comment]
using `var engine = new BABYLON.Engine(canvas, true, {disableWebGL2Support: true});`
and no complain from the browser.

I'll close this issue then.

**Comment by deltakosh** [comment]
Perfect:)
