### ISSUE TITLE
Add support for PBR to blender and 3dsmax exporter

### ISSUE THREAD

**Issue by deltakosh** [BabylonJS/Babylon.js#2596]

**Comment by Palmer-JC** [comment]
I do not know enough about how either does PBR.  Please add it to the
mult-file version 5.  Was only keeping the single file 4.6.1 around for old
versions of Blender, prior to 2.71, I think.  There is a Gulp task to make
the zip file.  If you are making changes to the multi-file version, it is
safest restart after an update.  I do not know why, but sometimes changes
do not take effect once running.

Another alternative might be once the preferences are up, remove it, then
addit back & enable.
.

**Comment by deltakosh** [comment]
Thanks!!

**Comment by Palmer-JC** [comment]
Also, in the multi-file version, the version is in __init__.py

**Comment by Vinc3r** [comment]
About PBR export in Blender, you have to know that in the near future next version of Blender (2.79, RC1 is released, final version should be out in september I think) they're implement a new shader which could be **exactly** what we want! [the principled BSDF](https://wiki.blender.org/index.php/Dev:Ref/Release_Notes/2.79/Cycles#Principled_BSDF), [example](https://julperado.wordpress.com/2017/06/26/principled-shader-o-disney-shader-en-blender-cycles/).

But this shader is on cycles, not blender render, so this required to add an option to disable automatic baking when under cycles.

**Comment by deltakosh** [comment]
This is really cool. I agree this should be an option

**Comment by Vinc3r** [comment]
As for Blender Render, which may be a more simple first step to PBR export, , I suggest adding a checkbox in scene panel, something like _Export scene as PBR workflow_, and made links from blender standard material to BJS PBR material.
Example for [textures](http://i.imgur.com/dtQoWqW.png): diffuse color to albedoTexture, specular color to metallicTexture, etc.

**Comment by deltakosh** [comment]
Yep I like this idea!

**Comment by Vinc3r** [comment]
By the way, official Blender 2.79 just released today (containing the Principled BSDF node).

**Comment by Vinc3r** [comment]
I don't know if this can be useful, but a set a very basic test scene to convert standard material to PBR, zip can be downloaded here : https://www.nothing-is-3d.com/tools/babylonJS/std2PBR.zip (a little readme is included).
[As you can see](https://www.nothing-is-3d.com/tmp/std2PBR/), it's just an object with 3 textures : BaseColor, Normal and OcclusionRoughnessMetallic in RGB channels.

Just to know, is someone is on this task at this moment ? Is it @Temechon or @Palmer-JC which are original writers of this plugin ?

(Yes I'm very impatient about this feature, I can't use PBR in BJS without this exporter, sooo frustrating :) )

**Comment by deltakosh** [comment]
This is now supported in 3dsmax :) please give us your feedback!!!

**Comment by Vinc3r** [comment]
Yes I've seen that, but I don't want to crack software at home, and Blender is our main software in our workflow at work, so I guess I have to wait a little (or become a strong python dev', but I'm not sure this can be easily doable ^^).

**Comment by deltakosh** [comment]
The blender gltf exporter from khronos supports Pbr :)

**Comment by Vinc3r** [comment]
OK! Thanks for info, I will test that soon.
(I need to watch glTF developpement a little closer, it seems to be kind of future of webGL 3D format, and maybe later [who know's] successor of .babylon files ? Anyway, thanks for info)

**Comment by Palmer-JC** [comment]
If .blend files existed with EXACTLY one mesh plane, no lights or camera for what you wanted, then a hand made .babylon with generous line feeds of what should come out for each, then there would be specs.

I am doing nothing without specs.  I realize the notion of PBR implies that there be more than one mesh, I just do care.  Specs are different than test scenes.
