### ISSUE TITLE
Highlight Layer / Mesh dispose multiplying drawCalls

### ISSUE THREAD

**Issue by jasonayre** [BabylonJS/Babylon.js#2624]
Note: I can't reproduce what I am seeing in my project locally on the playground. However, I am wondering if it could be due to the locked down render loop, or whatever the PG does in the render loop.

Additionally, I am on 3.0.7 preview release version. I tried upgrading to latest, but latest release is fubar atm due to gui package move (not in the current NPM package.), so haven't been able to see if it is actually fixed, however the code I suspect is causing the problem seems to be the same in master.

So the past few nights I've been trying to fix a draw calls leak in my project. Basically what happens is,

1. Scene loads, I have 97 draw calls.
2. Call dispose() on a mesh, any mesh in the scene.
3. Draw calls are now 210+

I eventually ended up going through line by line replicating a dispose call from the console, to see at what point the issue surfaces. The point at which it surfaced was:

https://github.com/BabylonJS/Babylon.js/blob/master/src/Mesh/babylon.mesh.ts#L1479

So I took the highlight layer out of my scene, and problem was solved. dispose() no longer caused the multiplication of draw calls.

I was not able to replicate on a PG, but here is attempt - https://www.babylonjs-playground.com/#1KUJ0A#65

Wondering if PG is preventing it from happening, seeing as how in render loop it always returns 0 draw calls and what not, and since render loop behaves different on PG?

At any rate:

It seems like the code in question is passing in the mesh regardless of whether it is contained by the highlight layer. I would think it should be checking to see if it exists in the highlight layer first? I didn't fully step through the code yet to see what in the removeMesh function is causing the draw call multiplication, but have to call it for tonight, figured I would open issue while it's fresh.

**Comment by jasonayre** [comment]
(also worth nothing, in project locally, I hadn't actually added any meshes to the highlight layer, all I did was instantiate a highlight layer on the scene).

**Comment by sebavan** [comment]
I will look at it ASAP. Thanks for reporting the issue.

**Comment by sebavan** [comment]
It looks impossible to repro on the PG and outside the PG: https://www.babylonjs-playground.com/#1KUJ0A#75

Would be really nice if you can provide a repro.

**Comment by sebavan** [comment]
I close the issue from Github for now and we can continue the investigation on the forum to better target the issue.

**Comment by aWeirdo** [comment]
Bug reproduced here; http://www.html5gamedevs.com/topic/33816-highlight-layer-creating-additional-draw-calls-bug/?do=findComment&comment=196939

**Comment by sebavan** [comment]
Thanks for the repro it is fixed and will be deployed later today.
