### ISSUE TITLE
create engine error

### ISSUE THREAD

**Issue by chenzhenyao** [BabylonJS/Babylon.js#2642]
`import BABYLON from 'babylonjs'`
`const engine = new BABYLON.Engine(document.querySelector("#renderCanvas"), true)`

`babylon.max.js:7300 Uncaught TypeError: `
`   Cannot assign to read only property 'RGBA16F' of object '#<WebGL2RenderingContext>'`
`   at new Engine (babylon.max.js:7300)`

* babylonjs@3.1.0-alpha1
* chrome@59.0.3071.109

**Comment by deltakosh** [comment]
Hey can you repro it on a simple page and share it

**Comment by yvele** [comment]
Hey @chenzhenyao how did you solve this issue? I have the exact same problem here https://github.com/BabylonJS/Babylon.js/issues/2988 

Can you help? 😉
