### ISSUE TITLE
 edgesRenderer super slow

### ISSUE THREAD

**Issue by Andre741** [BabylonJS/Babylon.js#2643]
I import a obj file and the edges rendere takes ages >30min on an iMac, compared with seconds in three.js

**Comment by deltakosh** [comment]
Do you mind using the forum for your question? We try to use issues only for bugs to fix.
Did you try using highlights layer? Or outline rendering? Not sure the edge renderer is the best option if you have a complex mesh.

**Comment by Andre741** [comment]
I will ask the question in the forum and come back when it's a bug

**Comment by deltakosh** [comment]
Thanks a lot
