### ISSUE TITLE
Can not load *.babylon file

### ISSUE THREAD

**Issue by ArchieKing** [BabylonJS/Babylon.js#2650]
Hi,
i just export fbx from 3ds Max with Babylon export tools , i can see the *.babylon file work in the babylon sand box but not in my code , is that something wrong?

    var createScene = function () {
        var scene = new BABYLON.Scene(engine);
        var light = new BABYLON.DirectionalLight("dir01", new BABYLON.Vector3(0, -0.5, -1.0), scene);
        var camera = new BABYLON.ArcRotateCamera("Camera", 0, 0, 10, new BABYLON.Vector3(0, 30, 0), scene);

        camera.attachControl(canvas, false);
        camera.setPosition(new BABYLON.Vector3(20, 70, 120));
        light.position = new BABYLON.Vector3(50, 250, 200);
        light.shadowOrthoScale = 2.0;
        camera.minZ = 1.0;

        scene.ambientColor = new BABYLON.Color3(0.3, 0.3, 0.3);

        BABYLON.SceneLoader.ImportMesh("him", "models/", "test.babylon", scene, function (newMeshes2, particleSystems2, skeletons2) {
            var modelTest = newMeshes2[0];

            for (var index = 1; index < newMeshes2.length; index++) {
                shadowGenerator.getShadowMap().renderList.push(newMeshes2[index]);
            }

            modelTest.position = new BABYLON.Vector3.Zero();
        });

        return scene;
    };

**Comment by deltakosh** [comment]
Hello do you mind using the forum for your question? We try to use github only for bugs

**Comment by ArchieKing** [comment]
oh~sorry~i just new here :)

**Comment by deltakosh** [comment]
No worry at all:)
