### ISSUE TITLE
Shadow documentation

### ISSUE THREAD

**Issue by zakhenry** [BabylonJS/Babylon.js#2669]
Do shadows only work with textured materials? See http://www.babylonjs-playground.com/index#20GGCS which I found in the forums - I think that demo should be displaying shadows, but I can't seem to get them to work. I am not using textures, so I suspect that might be the cause?

**Comment by deltakosh** [comment]
Hello, nope you just need to provide a position for your light: https://www.babylonjs-playground.com/#20GGCS#11

**Comment by zakhenry** [comment]
@deltakosh ah! thanks for the quick response.
