### ISSUE TITLE
LOD and instance behaviours

### ISSUE THREAD

**Issue by pandaGaume** [BabylonJS/Babylon.js#2671]
Hello, we are experiencing a non expected behaviour when instances are in use with LOD. 
Playground for reproducing is : 
[playground](https://www.babylonjs-playground.com/#0720FC#6)
on this demo, one of the instances (name='3' at z=-20) located on the z axis is not showing when at LOD distance and show the master mesh when any other show the master mesh...
to reproduce, move the camera backward and turn arround Y axis until crossing the positiv z axis, then move forward to origin..
My surface book run ES2.0 and then use instance hardware acceleration.
behave the same under chrome Version 60.0.3112.90 (Official Build) (64-bit) and Edge 40.15063.0.0
Windows 10 Pros v 15063.540
SEE UPDATE BELOW

**Comment by pandaGaume** [comment]
une mise a jour de la demo deplace le problème à la sphere centrale. 
[playground](https://www.babylonjs-playground.com/#0720FC#7)

**Comment by deltakosh** [comment]
Hello,
actually it is not a bug per se but more a limitation.
If you want to use LOD on instances (without duplicating every LOD levels), you cannot display the root objects at all.

Here is a fix where I have just added another instance to cover the root object and be able to hide it.
(Will also require the very latest version of bjs to work):
https://www.babylonjs-playground.com/#0720FC#9

(I'll update the doc to mention this limitation)
