### ISSUE TITLE
Big camera.maxZ will cause registered actions not working

### ISSUE THREAD

**Issue by mind0n** [BabylonJS/Babylon.js#2676]
Refer to the demo below, the actionManager stops working (no respond to mouse click events) due to the line `camera.maxZ = 100000000;`
And there're no error / warning messages displayed inside the browser console.

http://www.babylonjs-playground.com/#N3IBKT

Expected Result:
Mouse click should work like demo http://www.babylonjs.com/playground/?17
Or, warning / error messages should display to let the developer know that the maxZ is too big.

**Comment by deltakosh** [comment]
Hello and thanks for reporting it. Unfortunately this is not something we can test as the ray caster is done quite intensively by the engine. But we can definitely document it
