### ISSUE TITLE
Ke parameter not supported in ObjLoader

### ISSUE THREAD

**Issue by pandaGaume** [BabylonJS/Babylon.js#2695]
I suggest to include support for Ke parameter (if present) in the obj loader using the following simple add into parseMTL function.

```
else if (key === "ke") {
// Emissive color using RGB values
color = value.split(delimiter_pattern, 3);
material.emissiveColor = BABYLON.Color3.FromArray(color);
}
```

Also avoiding to trying to load Texture with Empty Url, as many MTL file come with property without value.
```
newmtl grass
Ka 0 0 0
Kd 1 1 1
Ks 0.9 0.9 0.9
ke 1 1 1
illum 2
Ns 64
map_Kd grass_diffuse.png
map_bump 
bump 
map_opacity 
map_d 
refl 
map_kS 
map_kA 
map_Ns 
````

the impacted function is MTLFileLoader._getTexture.

**Comment by deltakosh** [comment]
Fancy doing a PR?

**Comment by deltakosh** [comment]
Actually i did it ;)
