### ISSUE TITLE
Color3.Teal is undefined

### ISSUE THREAD

**Issue by PERECil** [BabylonJS/Babylon.js#2710]
Hello,

When trying to use the `GridMaterial` with the latest beta of `Babylon.js` available on cdnjs (3.0.1-beta), I get the following error: `i.Color.Teal` is undefined.

After inspecting `BABYLON.Color3` function, there is afaik no static property `Teal`.

Suggestions: either add the `Teal` color to `Color3` or fix the `GridMaterial` (my preference would be for the first option).

**Comment by deltakosh** [comment]
It is already defined.
You should rely on either the latest npm version or use our cdn: preview.babylonjs.com
