### ISSUE TITLE
PBR shader error on Edge/IE10 when using single image as reflectionTexture

### ISSUE THREAD

**Issue by BobRazowsky** [BabylonJS/Babylon.js#2711]
Cf. [playground](https://www.babylonjs-playground.com/#IRZYH#20)
Works on Chrome, fails on IE10/Edge.

**Comment by deltakosh** [comment]
Unfortunately this is expected. Edge/IE do not support a required extension: texture_lod. when used with a cubemap we are doing a lot of work under the hood to generate fake LODs. But this is not done when used with a 2d texture

So I recommend to stick with a cubetexture here (or use the standard material)
