### ISSUE TITLE
Error , when more than 10 lights .

### ISSUE THREAD

**Issue by clong365** [BabylonJS/Babylon.js#2721]
Error , when more than 10 lights .

I add 5 more lights in the demo Playground.

https://www.babylonjs-playground.com/#IRVAX#58

material.maxSimultaneousLights = 16;

BJS - [10:29:03]: Unable to compile effect:
BJS - [10:42:53]: Error: program not linked

**Comment by deltakosh** [comment]
hello it works for me on Edge/chrome/firefox
Which computer are you running on? Which browser?

**Comment by clong365** [comment]
Windows 10 , Chrome 60.

**Comment by deltakosh** [comment]
Unfortunately I cannot repro it:(

**Comment by clong365** [comment]
As I know, Edge/IE11 use WebGL 1, and Chrome/Firefox suppurt WebGL 2.

I installed a new Firefox 55, the error ocurred  the same as Chrome 60.

![image](https://user-images.githubusercontent.com/150419/29994768-ca6cbcd4-9009-11e7-8104-94d4214da7bd.png)

**Comment by deltakosh** [comment]
I've just pushed an update where you can ask the engine to disable uniform buffers. This will reduce overall performance but it will let you use more lights as we won't be limited by the number of UB.
https://www.babylonjs-playground.com/#IRVAX#61
