### ISSUE TITLE
Make particles capable of picking a part of the particle texture

### ISSUE THREAD

**Issue by deltakosh** [BabylonJS/Babylon.js#2725]
So far the particles will pick the entire texture:
https://github.com/BabylonJS/Babylon.js/blob/master/src/Particles/babylon.particleSystem.ts#L390
(check third and forth parameter)

It could be great to add an option where a particle can be pick a specific subset. This subset could be constant or could evolved over time to create an animation

**Comment by IbraheemOsama** [comment]
Will start to investigate and working on this.

**Comment by wilson-yong** [comment]
Hi, I have a few suggestions here:
animationType:
WholeSheet: Animate over the whole texture sheet from left to right, top to bottom.
SingleRow: Animate a single row in the sheet from left to right. that is, each row of the sheet represents a separate Animation sequence.

1. numTilesX: Defines the tiling of the texture in the X axis.
2. numTilesY: Defines the tiling of the texture in the Y axis.
3. cycleCount: Specifies how many times the animation will loop during the lifetime of the particle.
4. enabled: Enable/disable the Texture Sheet Animation module.
5. useRandomRow: Use a random row of the texture sheet for each particle emitted. This option is only available when Single Row is selected as the Animation mode.
6. rowIndex: Selects a particular row from the sheet to produce the animation This option is only available when Single Row mode is selected and Random Row is disabled.
7. startFrame: Allows you to specify which frame the particle animation should start on (useful for randomly phasing the animation on each particle).
8.easingMode : specifies how the frame of animation increases as time progresses.

I hope it can help you :P

**Comment by IbraheemOsama** [comment]
@deltakosh 
So I'm going to rephrase what I understood :) 
we need to enable the emitter to specify a subset of it self to emit the particles (doesn't minEmitBox and maxEmitBox in ParticleSystem do this job ?) ?
and "could evolved over time to create an animation" means we need to give the developer an option to specify how this subset can animate\move while emitting ?

One more thing third and forth parameters are the xOffset and yOffset in method _appendParticleVertex ?

**Comment by IbraheemOsama** [comment]
@wilson-yong thanks for your suggestions :) will consider it in the implementation.

**Comment by deltakosh** [comment]
Not the emitter. Just the part of the texture used by particles over time. For now they all use the entire texture.
The idea here is too pick a part of it and change the part used over time.

**Comment by IbraheemOsama** [comment]
aha :) thanks for clarification.

**Comment by deltakosh** [comment]
Closing it (only Doc and samples are missing:))
