### ISSUE TITLE
Add support for additional controls on arcrotatecamera

### ISSUE THREAD

**Issue by deltakosh** [BabylonJS/Babylon.js#2728]
- [x] Pan with two fingers
- [x] Pan with right click with pencil
- [x] CTRL+cursor to pan
- [x] \ to reset to initial position
- [x] Mouse double click to reset position
- [x] Double tap to reset position (touch and pencil)

**Comment by sebavan** [comment]
https://github.com/BabylonJS/Babylon.js/commit/cd1d1a56782a1f5456102c85415bbe7dfbd23cc8
