### ISSUE TITLE
Update unity Exporters to Unity 2017.1

### ISSUE THREAD

**Issue by HeadClot** [BabylonJS/Babylon.js#2769]
Hey,

The current versions of Unity3D exporters for Babylon JS are stuck on unity 5.x Would it be possible to update them to Unity 2017.1.?

I am asking this as I am making some large environments in Unity that I want to export to Babylon.js.

Thank you,

HeadClot

**Comment by deltakosh** [comment]
Absolutely we are about to update the unity exporter. Perhaps @mackey24 can give us an ETA?

**Comment by HeadClot** [comment]
I got a reply from @MackeyK24 which can be found [here](http://www.html5gamedevs.com/topic/32841-update-the-unity-exporters/). 

I would like to know what new features he is adding to the tool kit. An ETA would be awesome.
