### ISSUE TITLE
Add support for light texture projection

### ISSUE THREAD

**Issue by deltakosh** [BabylonJS/Babylon.js#2771]

**Comment by quocsinh** [comment]
Hi @deltakosh ! 
My project has been completed 95% and i expect this feature each day. My company are urging me, i'm worrying :( . Sorry if you are busy or have too many tasks.
Thank you!
SinhNQ.

**Comment by deltakosh** [comment]
Hey. Unfortunately we did not start working on it yet:(

**Comment by quocsinh** [comment]
OK thanks Mr.Dk :(

**Comment by lostink** [comment]
Started working on that part now.

**Comment by deltakosh** [comment]
Excellent

**Comment by quocsinh** [comment]
I have waited a long time for this, i will be one of the first to test this feature 👯‍♂️

**Comment by deltakosh** [comment]
Done :) http://doc.babylonjs.com/babylon101/lights#projection-texture
