### ISSUE TITLE
Bug in Tools.LoadFile with FF 52.3.0

### ISSUE THREAD

**Issue by innerground** [BabylonJS/Babylon.js#2772]
Hello,
I came accross a bug with FireFox 52.3.0 in the function Tools.LoadFile.

Line 5516 : request.readyState === (XMLHttpRequest.DONE || 4)

XMLHttpRequest.DONE is defined but is not a number, as expected.Therefore loading fails as request.readyState is never equals to XMLHttpRequest.DONE.

Quick fix is to replace  request.readyState === (XMLHttpRequest.DONE || 4) by  request.readyState === 4

Or, we can also check if XMLHttpRequest.DONE is a number.

Best regards,

![capture](https://user-images.githubusercontent.com/31859850/30286165-e4135008-9720-11e7-97df-9dca24338384.PNG)

**Comment by deltakosh** [comment]
Good catch..Do you want to do a PR?

**Comment by innerground** [comment]
Sure!

**Comment by deltakosh** [comment]
both I would say :)

**Comment by deltakosh** [comment]
up?

**Comment by RaananW** [comment]
Just a note, I did some tests on firefox nightly 55, 56 developer edition, both deliver  XMLHttpRequest.DONE === 4 . Are you sure it is actually a bug?

**Comment by deltakosh** [comment]
Closing for now. Please reopen at will

**Comment by deltakosh** [comment]
Closing for now. Please reopen at will
