### ISSUE TITLE
Draco: is there a plan to build a DracoLoader?

### ISSUE THREAD

**Issue by guzuomuse** [BabylonJS/Babylon.js#2779]
hope Draco can be used with babylon

https://github.com/google/draco

https://github.com/mrdoob/three.js/pull/10879

**Comment by deltakosh** [comment]
I know that @bghgary was doing some experiments

**Comment by guzuomuse** [comment]
@deltakosh @bghgary thanks for reply
I think there should be two widgets.one is an encoder,the other is a 'decoder'(loader)

**Comment by bghgary** [comment]
I have been doing experiments here: https://github.com/bghgary/Babylon.js/commit/57bf92980cbb0e844219dfc1a7ba78a0a8098a96

**Comment by guzuomuse** [comment]
@deltakosh glad to see that and thanks for your work. expecting this can be released asap. 
i'm new to draco,i think this feature is very important to reduce downloading time. do u think so?

by the way, are you Chinese?

**Comment by deltakosh** [comment]
This is now done :)
Thanks @bghgary
