### ISSUE TITLE
When Babylon is loaded from npm package, shadows do not generate

### ISSUE THREAD

**Issue by zakhenry** [BabylonJS/Babylon.js#2781]
I've scratched my head over this one for a while, and can't seem to find a good reason for it, but when loading Babylon using NPM, shadows do not generate.

I have created a minimal reproduction at https://github.com/zakhenry/babylonjs-npm-demo/

I'm guessing it might be something to do with the gulp bundler that is creating the babylon.max.js files?

**Comment by deltakosh** [comment]
Can you publish a running repro?

**Comment by zakhenry** [comment]
Sure, see https://zakhenry.github.io/babylonjs-npm-demo/

**Comment by RaananW** [comment]
Hi @zakhenry ,

Just for me to understand - you can't see the shadows in the demo?

This is what I see: 

![image](https://user-images.githubusercontent.com/1381702/30367506-b3f26694-986e-11e7-8069-a162fe7340ae.png)

**Comment by zakhenry** [comment]
@RaananW hmm. in the demo [in the playground](http://www.babylonjs-playground.com/#OPL98) I see shadows, but in the demo [I created ](https://zakhenry.github.io/babylonjs-npm-demo/) I don't see shadows. As far as I can tell the code is identical, except one loads babylon from the cdn, and the other from the npm module

**Comment by zakhenry** [comment]
<img width="1030" alt="screen shot 2017-09-13 at 09 41 39" src="https://user-images.githubusercontent.com/721513/30368093-05df677e-9868-11e7-997e-36e859dfa8a2.png">

**Comment by RaananW** [comment]
Hi @zakhenry ,

The image I pasted was from your demo, and not the playground. 
![image](https://user-images.githubusercontent.com/1381702/30369211-f5da7d76-9873-11e7-99ff-c6a03af63c51.png)


Can I ask for some more information about your system? OS / Browser ? 

Any errors in the console?

**Comment by zakhenry** [comment]
@RaananW ok that is weird. I'm on an iMac with `Radeon Pro 575 4096 MB`, I tried in Chrome, Safari, Firefox Nightly. All don't show shadows (though the playground sample is fine.) I also double checked on a colleagues PC with FF on Ubuntu, same result as me.

**Comment by zakhenry** [comment]
To further confuse things, I just found it to work on my phone

**Comment by zakhenry** [comment]
Also no console errors, there is a verbose warning from chrome, but I doubt that is the cause
```
[Violation] Added non-passive event listener to a scroll-blocking 'mousewheel' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
```

**Comment by zakhenry** [comment]
Sorry for the spam, but I'm digging in to this a bit deeper to see if I can help work out a pattern

|OS/Browser| Shadows work |
|-|:-:|
| osx/chrome | ❌ |
| osx/firefox (nightly) | ❌ |
| osx/safari | ❌ |
| ios/chrome | ✅ | 
| ios/safari | ✅ | 
| ubuntu/chrome | ❌ | 
| ubuntu/firefox | ❌ | 
| windows/chrome | ✅ | 
| android/chrome | ❌ |

**Comment by zakhenry** [comment]
Finally, also of note is that if I roll back to `3.1.0-alpha0`, it works, so this issue seems to have been introduced in `3.1.0-alpha1`.

**Comment by deltakosh** [comment]
I can create an update of the npm package with the very latest alpha. So you will have the same version ad the playground

**Comment by deltakosh** [comment]
I've just published a new package. Let me know if this works

**Comment by zakhenry** [comment]
@deltakosh excellent! that did the trick, thanks a lot. And thanks for being so responsive with Babylon, it is a pleasure to work with 😄

**Comment by deltakosh** [comment]
I'm happy when customers are happy :)
