### ISSUE TITLE
3.1.0-alpha2 Assigning Material to Mesh throws Uncaught TypeError: engine.getColorWrite is not a function

### ISSUE THREAD

**Issue by BlackRookSix** [BabylonJS/Babylon.js#2807]
In 3.1.0-alpha2, there is a bug when assigning a Material to a Mesh.  This behavior does **not** appear in 3.0.7.

>     var material = new BABYLON.StandardMaterial('material', scene)
>     material.diffuseColor = new BABYLON.Color3(1, 0, 0)
>     material.emissiveColor = new BABYLON.Color3(1.0, 0.0, 0.0)
>     // material.specularColor = new BABYLON.Color3(1.0, 0.0, 0.0)
>     // material.ambientColor = new BABYLON.Color3(1.0, 0.0, 0.0)
>     mesh.material = material

Assigning the Material to the Mesh in 3.1.0-alpha2 causes the following error:

> home/rook/Documents/Projects/testing/node_modules/babylonjs/dist/prev…:25221 Uncaught TypeError: engine.getColorWrite is not a function
>     at Function.MaterialHelper.PrepareDefinesForFrameBoundValues (/home/rook/Documents/Projects/testing/node_modules/babylonjs/dist/prev…:25221)
>     at StandardMaterial.isReadyForSubMesh (/home/rook/Documents/Projects/testing/node_modules/babylonjs/dist/prev…:31138)
>     at Mesh.render (/home/rook/Documents/Projects/testing/node_modules/babylonjs/dist/prev…:22375)
>     at SubMesh.render (/home/rook/Documents/Projects/testing/node_modules/babylonjs/dist/prev…:24285)
>     at t.renderUnsorted (babylon.js:9)
>     at t.render (babylon.js:9)
>     at t.render (babylon.js:9)
>     at r._renderForCamera (babylon.js:10)
>     at r._processSubCameras (babylon.js:10)
>     at r.render (babylon.js:10)

**Comment by deltakosh** [comment]
Can you repro on the playground?
