### ISSUE TITLE
Possible bug with updating updatable meshes, i.e. tube

### ISSUE THREAD

**Issue by jasonayre** [BabylonJS/Babylon.js#2815]
Not sure if this is a bug or working as intended, but I found the behavior surprising so figured I'd open.

Basically if you another option such as radius during mesh creation, but fail to include the property on update, it will reset to the default value.

https://www.babylonjs-playground.com/#9U370L#3

Call updateTube() in console to see behavior.

I would think it would still use the value provided at construction if that option is omitted, but maybe there is a reason for the behavior I'm missing?

**Comment by jbousquie** [comment]
Yep, that was the expected behavior so far (the reason was to not change the internal structure of the Mesh object as the tube is only a mesh, not an instance of a specific Tube class). But we can change it to keep the last passed value.

**Comment by jbousquie** [comment]
added on my todo list

**Comment by jbousquie** [comment]
mmmh... I understand better : the documentation uses a new _options_ object each call in didactic purpose.  

The best way to use the _options_ parameter with parametric shapes would be to re-use a single variable from the creation step instead of creating a new one each call.
```javascript
var options = {radius: 10, path: array, etc ...};
// creation step
var tube = BABYLON.MeshBuilder.CreateTube("t", options, scene);
// now add the property "instance" for further morphing
options.instance = tube;


// later on ... morphing, just update the path elements before
BABYLON.MeshBuilder.CreateTube(null, options);
```

**Comment by jbousquie** [comment]
done : https://github.com/BabylonJS/Babylon.js/pull/2833
