### ISSUE TITLE
When scaling a mesh, babylon calculates normals incorrectly 

### ISSUE THREAD

**Issue by focomoso** [BabylonJS/Babylon.js#2820]
When scaling a mesh (in 2.5 and 3.0), babylon exaggerates the effect of the scale on the normals by a power of two in each direction.

For example. Both of the spheres in this playground are identical. The one on the left was scaled down in tinkercad to 25% in the y axis and then scaled back up once it's loaded in babylon. The one on the right is loaded with no scaling.

https://www.babylonjs-playground.com/indexstable#V3A6F8#16

Expected behavior is that the two spheres would be identical given that their geometry is identical after scaling, but the normals on the scaled sphere are exaggerated in the y.

In this playground, both meshes look identical because I've computed the normals by hand and compensated for the scale by dividing the normals' components by the scale components.

https://www.babylonjs-playground.com/indexstable#V3A6F8#18

The bug here is that none of this should be necessary. babylon should correctly calculate the normals when a mesh is scaled.

**Comment by deltakosh** [comment]
This is an expected behavior as we do not update normal for non uniform scaling. This would be too expensive and can easily be fixed by code as you did

**Comment by focomoso** [comment]
I understand not updating the normals automatically, but what about the issue with mesh.setVerticesData(BABYLON.VertexBuffer.NormalKind, normals, true); ?

The normals are getting scaled a second time which is why we have to "unscale" them beforehand. That seems unexpected.

**Comment by deltakosh** [comment]
The setVerticesData do not change the data. It sends everything to the GPU unchanged.
Check my comment here:http://www.html5gamedevs.com/topic/32913-recalculate-mesh-shading/?tab=comments#comment-189162
