### ISSUE TITLE
Error while trying to load image

### ISSUE THREAD

**Issue by admilne** [BabylonJS/Babylon.js#2824]
Hello, I seem to be getting an error when loading files through a .mtl file when using Internet Explorer or Edge. So my .mtl file has the following:

map_Kd image_combined.jpg
map_Ks image_spec.jpg
map_Bump image_norm.png

When I load the web page in the browser I get the following errors:

BJS - [09:53:25]: Error while trying to load image: assets/image_combined.jpg
BJS - [09:53:25]: Error while trying to load image: assets/image_spec.jpg
BJS - [09:53:25]: Error while trying to load image: assets/image_norm.jpg

I then see the object on the page but without any of the textures. This is working perfectly fine in Chrome and Firefox but won't seem to work in either IE11 or Microsoft Edge. Any thoughts and suggestions would be amazing as I'm a bit confused as to what the problem might be. Thanks!

**Comment by RaananW** [comment]
Hi @admilne ,

A few questions just to understand the issue:

1. Is there a way we can see that reproduced?
2. is the assets directory automatically added? Is there a reason for the loader to add this directory?
3. Are the errors and images you entered correct? It seems like the filenames are also completely off.

**Comment by admilne** [comment]
Hi @RaananW, thanks for your reply

1. Unfortunately no. The work is confidential which I know doesn't help at all.

2. When I load in the .obj file I use the following line of code - 
`var meshTask = assetsManager.addMeshTask("RBS", "", "./assets/", "RBS15_mod_stripped.obj");`

I think that should load in the assets directory? I guess there is no real need for the directory other than to keep the files tidy.

3. No sorry! I had to change the file names I mentioned above to hide the name of the file I was actually using. So the errors I get are actually:

BJS - [09:53:25]: Error while trying to load image: assets/image_combined.jpg
BJS - [09:53:25]: Error while trying to load image: assets/image_spec.jpg
BJS - [09:53:25]: Error while trying to load image: assets/image_norm.png

**Comment by admilne** [comment]
I've navigated to the individual image files in the web browser and gone back to my page using babylon.js and it now works! It seems that once I have the images cached the issue goes away, although this isn't very practical for people who come to visit the page...

I wonder if babylonjs has some sort of time out when trying to load the assets and for some reason IE and Edge are slow in getting those assets?

**Comment by admilne** [comment]
@RaananW I figured out the problem! The whole project is underneath a password protected directory. If I remove the password protection from the directory then everything loads up fine. For some reason having the password protection on the directory stops IE and Edge from being able to access those assets.

**Comment by RaananW** [comment]
I was just writing an answer to the last post you wrote :smile:

I am glad you found the issue. I guess this is a browser-specific behavior (which doesn't make too much sense to me, but I guess there is a reason behind it).

I assume you have already entered the username and password, but it still won't deliver the files correctly. The best I can offer is that you try and protect your files in a different way.
