### ISSUE TITLE
Updates for Inspector

### ISSUE THREAD

**Issue by deltakosh** [BabylonJS/Babylon.js#2827]
- [x] Selecting a mesh does not select it in the list of meshes. Only properties are updated
- [x] Use real sliders (controls) when possible
- [x] We should order sub properties:
![image](https://user-images.githubusercontent.com/1306056/31021648-571e3766-a4eb-11e7-9674-03e9dfdf9308.png)
- [x] We should round numbers:
![image](https://user-images.githubusercontent.com/1306056/30620252-1dfde506-9d59-11e7-9d3f-4dda75050737.png)
- [x] Add a margin to make the list clearer:
![image](https://user-images.githubusercontent.com/1306056/30620269-2a435512-9d59-11e7-917e-5731d91afa97.png)
- [x] Weird bottom bar:
![image](https://user-images.githubusercontent.com/1306056/30620297-4f0df118-9d59-11e7-9dab-b1597f0a174d.png)
- [x] Center color box on the line:
![image](https://user-images.githubusercontent.com/1306056/30620310-5cab8e16-9d59-11e7-8e15-23b84d4d6217.png)
- [x] Hitting tab should validate an edited field (like Enter)
- [x] Hitting tab and then clicking on a field produces a weird result:
![image](https://user-images.githubusercontent.com/1306056/30620349-a6610dce-9d59-11e7-9fb8-14e55194f41d.png)
- [x] Boolean fields should be represented with check boxes
- [x] Avoid using double scroll bar:
![image](https://user-images.githubusercontent.com/1306056/30620371-d0d6616c-9d59-11e7-9f14-45ffe0edbb02.png)

**Comment by bghgary** [comment]
It would be good to fix the order of components the drop down too. For example, in the first example above, the order of RGB field is B, G, R in the drop down. Some XYZs are also in the wrong order:

![image](https://user-images.githubusercontent.com/19158740/30708609-50e1d674-9eb4-11e7-9715-bd87358d3920.png)

**Comment by treefort** [comment]
Not sure if a new issue would be more appropriate, but I had a few thoughts as well:

- Up/down arrows "nudge" numerical fields by +/- 1, respectively. holding down shift changes this to +/- 10.
- Ability to see a wireframe representation of physics impostors
- Proper integration into chrome's devtools (as an extension)
- Fix redundant CSS includes:
![image](https://user-images.githubusercontent.com/1132492/30813269-f92340ba-a1da-11e7-8783-b4d3e31e1765.png)

**Comment by deltakosh** [comment]
Yes please add a specific issue:)

**Comment by abow** [comment]
> Ability to see a wireframe representation of physics impostors

look under the Physics tab of the Inspector

**Comment by treefort** [comment]
@deltakosh will do—thanks!

@abow I saw that, but perhaps it isn't working? these trees are using a cylinder impostor...
![image](https://user-images.githubusercontent.com/1132492/30814969-acc12764-a1df-11e7-9e98-faef19d37fd6.png)

same result w/ wireframes
![image](https://user-images.githubusercontent.com/1132492/30815002-d004bf38-a1df-11e7-9792-7a9e6e91fb2a.png)

**Comment by abow** [comment]
Someone needs to add support for cylinders. 

https://github.com/BabylonJS/Babylon.js/blob/master/src/Debug/babylon.physicsViewer.ts#L128
