### ISSUE TITLE
WebVR camera doesn't use VRDisplay.stageParameters

### ISSUE THREAD

**Issue by leweaver** [BabylonJS/Babylon.js#2831]
The WebVR 1.1 API contains an optional [stageParameters](https://w3c.github.io/webvr/spec/1.1/#interface-vrstageparameters) property on the VRDisplay. 

This transform can be applied to the camera to turn it into a standing experience. If not null, this should be used in the `VRExperienceHelper` class to offset the VRFreeCamera. If null, can fall back to the existing behavior (hard-coded 2m offset).

Note that in Edge, this property is currently always null; Firefox and Chrome implement this feature for Oculus/OpenVR devices.

**Comment by RaananW** [comment]
As the webvr support was implemented, the stageParameters had no meaning whatsoever and they were therefore ignored. The browsers didn't support it, and it didn't seem needed. 

I noticed you wrote firefox and chrome - are they actually changing the values between sitting and standing positions? is the `sittingToStandingTransform` actually updated as well? How can I know if a person is sitting or standing? Is it my decision as a developer?

About the sizeX and sizeY - most devices (I know the vive and oculus) always display the boundaries. We can offer those params to the developer, but he/she can also retrieve it directly from the vrDisplay if needed.

**Comment by leweaver** [comment]
As an app developer, you need to decide whether your experience wants the users head position to start at the origin (seated: eg, a 3DOF experience or 360 photo with in-world UI overlayed), or at a standing offset; and inform the engine appropriately. 

It could be a reasonable fix for that to simply add a parameter to the scene.createDefaultVRExperience() such that a developer can specify that they wish to use a seated experience, thus no offset/transform is applied to the camera at all.

Re: sizeX/sizeY - agree with you that it is not the engines responsibility to render boundaries. These are here simply as hints to app developers so that they do not place intractable content out of reach of the user (potentially for cases where teleportation is not used). It is reasonable for the developer to simply get the VRDisplay off the engine, then inspect these properties themselves.

Now... the `sittingToStandingTransform` matrix. (Yuck, btw!). Regarding browser support; it looks like (based on my testing just now on a Vive, not sure of Oculus behavior) that Chrome and Firefox are populating the matrix. They return a transform representing the users height as defined in Room Setup (this will be different depending on if the user opted for roomscale or standing setup on their device).

When setup for roomscale: 
```
sittingToStandingTransform: [-0.880, 0.000,-0.475, 0.000, 0.000, 1.000, 0.000, 0.000, 0.475, 0.000,-0.880, 0.000, 0.773, 1.200, 0.747, 1.000 ]
sizeX: 2.900
sizeZ: 2.500
```

When setup for standing: 
```
sittingToStandingTransform: [ 1.000, 0.000, 0.000, 0.000, 0.000, 1.000, 0.000, 0.000, 0.000, 0.000, 1.000, 0.000, 0.000,-0.350, 0.000, 1.000 ]
sizeX: 1
sizeZ: 1
```

You are right that there is no explicit way of knowing whether or not the transform that is given by the API is already in standing space - this is a problem with the API. (and is something that the spec writers are aware of and aim to fix in WebVR 2.0). As a consequence, I have noticed in existing WebVR content on the web that uses these transforms, your head will be in the floor if room setup has not been run. Perhaps one approach could be, if the Y of the translation portion is < 0.3m (magic number!), instead use an arbitrary human height (1.6m?) - otherwise use the provided transform.

**Comment by deltakosh** [comment]
Ping @davrous for the VRExperienceHelper update

**Comment by TrevorDev** [comment]
Previously added in 3.1 see methods in  https://github.com/BabylonJS/Babylon.js/blob/master/src/Cameras/VR/babylon.webVRCamera.ts
- useStandingMatrix
- deviceDistanceToRoomGround

By default, all devices will start where they are as sometimes the standing matrix will not be populated.

To use the transform, a developer can call useStandingMatrix to check if the matrix is available and initialize it. deviceDistanceToRoomGround can then be used to get the exact distance from the ground if supported.
