### ISSUE TITLE
Opacity within the same mesh, depth order

### ISSUE THREAD

**Issue by a-carvallo** [BabylonJS/Babylon.js#2832]
I'm creating this simple scene : https://www.babylonjs-playground.com/#1PLV5Z#18

![image](https://user-images.githubusercontent.com/9554119/30602707-b2cceb80-9d65-11e7-9397-4c9bbbacedfb.png)

(Simple torus knot, blue material with alpha = 0.9)

The red lines mark the part of the "crossings" which are closer to the camera, for the one on the right, everything is ok, but for the one on the left it appears that the part "behind" is actually closer to the camera.

The rendering seems therefore wrong, for comparison the same kind of scene rendered with threejs looks like this :

![image](https://user-images.githubusercontent.com/9554119/30632834-cab28780-9de9-11e7-9b4e-6b266f9139f6.png)

It's also not perfect but at least the order of the parts is correct (parts closer to the camera do look closer to the camera)

Would there be a way to obtain a result closer (as in more accurate) to the threejs one ?

**Comment by deltakosh** [comment]
Hello,
actually threejs has the same issue (you can see that the right part is not transparent). The problem of self opacity and order independent transparency is a big beast.
Babylon.js still has some options for you:

- You can change the alpha blending to move to a purely additive one. Alpha value will not be used but the rendering could work in your case
- You can rely on a new option we introduced recently: mesh.material.needDepthPrePass = true (see doc here:http://doc.babylonjs.com/tutorials/transparency_and_how_meshes_are_rendered#depth-pre-pass-meshes

**Comment by a-carvallo** [comment]
Hi again,

I indeed said that threejs wasn't perfect as well, but there was no doubt about perspective (you know which parts are closer by just looking).
I also know that the subject of transparency in 3D can be quite a huge pain...

I looked a bit more into additive alpha mode, it's good, but the shiny/ghost effect is not cool :/

For needDepthPrePass, it works for simple stuff, as soon as 2 'objects' are in the same mesh, it will fail, for example : https://www.babylonjs-playground.com/#JB6H3P#1

If you have the camera with the big purple box at front, you won't see the green box or the yellow one.

Both options have advantages but bring other issues.

Also posted a topic with additional context for my specific case regarding this issue (which is pending approval as it's my first post on the forum).


Thank you as well for the quick answer :)

**Comment by deltakosh** [comment]
Let's chat about it on the forum :)

**Comment by deltakosh** [comment]
Hey hey!
we just introduced a new option that can work for you:
https://www.babylonjs-playground.com/#JB6H3P#5

Check line #20

**Comment by a-carvallo** [comment]
Hi, thanks for replying again, and introducing another potential fix, sadly it doesn't seem to work for my specific case (still might be useful for other people/other cases though).

I posted a reply in the thread, including a video to show exactly what I work with and what I'm trying to do (which is a bit more complex than the "general" examples I'm trying to provide for the issue :p).

Thread : http://www.html5gamedevs.com/topic/33026-transparency-alpha-issues/

**Comment by srothst1** [comment]
Hi everyone. The documentation for `needDepthPrePass` can be found here:
https://doc.babylonjs.com/typedoc/classes/BABYLON.Material#needDepthPrePass
Note that the [link listed above](https://github.com/BabylonJS/Babylon.js/issues/2832#issuecomment-330893280) is broken.
