### ISSUE TITLE
Any plans for GPU.js support?

### ISSUE THREAD

**Issue by HeadClot** [BabylonJS/Babylon.js#2864]
Hey got a question are there any plans for supporting [GPU.js](http://gpu.rocks/) in Babylon.js?

Just curious. :)

- HeadClot

**Comment by deltakosh** [comment]
Hello not for now.
The math operation we have are pretty short and we are not sure the overhead of creating a GPU shader for them will worth it

**Comment by HeadClot** [comment]
Alright thanks for the insight. :)
