### ISSUE TITLE
Add oimo and cannon as peer dependencies of BabylonJS

### ISSUE THREAD

**Issue by RaananW** [BabylonJS/Babylon.js#2867]
And include them, if they exist, so we wouldn't need to set the `window.OIMO` or `window.CANNON` object

**Comment by RaananW** [comment]
https://github.com/BabylonJS/Babylon.js/pull/2875  solves

**Comment by RaananW** [comment]
Documentation needs to be updated

**Comment by deltakosh** [comment]
See #2641 :)

**Comment by RaananW** [comment]
I was thinking about the es6-imports documentation . but this one as well! ;)
