### ISSUE TITLE
Helpers for shadows and intersection when submeshes

### ISSUE THREAD

**Issue by meulta** [BabylonJS/Babylon.js#2894]
It would be awesome to have helpers to:
- Automatically add all submeshes to a **ShadowGenerator** object.
- Automatically check **collision** between two meshes **with all submeshes** when using Mesh.intersectsMesh(mesh, true, true) (where the last parameter is something like: **includeAllSubmeshes**)

**Comment by deltakosh** [comment]
- [x] Automatically add all submeshes to a ShadowGenerator object: `shadowGenerator.addShadowCaster(mesh)`
- [ ] Automatically check collision between two meshes with all submeshes when using Mesh.intersectsMesh(mesh, true, true)
