### ISSUE TITLE
Use WebGLTexture texture directly

### ISSUE THREAD

**Issue by YousefED** [BabylonJS/Babylon.js#2906]
If we have a handle to a webgltexture, is there an option to use it directly as a material / babylon texture?

I'm trying to accomplish something similar to the example here: https://github.com/mrdoob/three.js/issues/5230

Thanks!

**Comment by deltakosh** [comment]
Hello you can create a RawTexture and the do this:
```
myTexture._texture = myHandleToWebGLTexture
```

Here is how to create a RawTexture:
```
var myTexture = BABYLON.RawTexture.CreateRGBATexture(new Uint8Array(4), 1, 1, scene)
```

obviously this will generate a 1x1 texture. for a bigger one do not forget to change the size of the UInt8Array :)
