### ISSUE TITLE
arcRotateCamera: implement adaptive speed of zoom based on distance to target

### ISSUE THREAD

**Issue by deltakosh** [BabylonJS/Babylon.js#2912]

**Comment by deltakosh** [comment]
Zoom should be fast when you’re far away, and slow when you get in close
For now the speed is constant

**Comment by jbousquie** [comment]
slightly different suggestion : shouldn't the current speed be simply a fixed (but customizable) percentage of the remaining distance ?

thus, the speed will be adaptative to any initial distance and the camera ever will slow down in any case when getting near to its target

**Comment by deltakosh** [comment]
Interesting idea! Would be worth a try

**Comment by deltakosh** [comment]
Now you can use camera.pinchDeltaPercentage and camera.wheelDeltaPercentage
