### ISSUE TITLE
Is it really necessary to store local coordinates not in vectors? 

### ISSUE THREAD

**Issue by tovarisch** [BabylonJS/Babylon.js#2916]
Mb its better approach to have numeric vectors(Vector2) for storing all sorts of coordinates and separate variables for other stuff. For example to use percent values have Vec2(public percPosition) which translates to private when set (private _localPosition) and nullifies absolute Vec2(public absPosition) and so on. This gives to developers more common interface makes vector operations easy possible to use and uses main babylon API ?

**Comment by deltakosh** [comment]
This is mostly for easyness: control.left instead of control.position.x

**Comment by tovarisch** [comment]
but it returns string and for using it in math some not trivial operations needed
`        
public get left(): string | number  {
            return this._left.toString(this._host);
        }`

It is real problem for dealing with dynamical interfaces

**Comment by tovarisch** [comment]
i mean is it overall make things easier?

**Comment by deltakosh** [comment]
this is because you can use in the css way: control.left = "20px" or control.left="50%"

**Comment by tovarisch** [comment]
not sure that this is good practice in web to manipulate css directly as strings. If it is done then some masking frameworks used to hide string manipulations - "jqury" for example used for "bad" css animations. Overall programming side prefers number manipulations and css used only as description language. CSS with all it practices made not for coding and havent any purpose to be used like so.
I'm not sure what advantages this approach will give for game development.
Is it final decision? Or may be some discussion?

**Comment by deltakosh** [comment]
It is already public so final for sure as we do not introduce breaking changes
The goal was not to allow developers to either use pixels or percentage with the same property

But not opposed to add additional properties if this makes sense

**Comment by tovarisch** [comment]
here is what iv done to make dragndrop on element.

`
var BABYLON = require("babylonjs");
require("babylonjs-gui");

var RecipeTechnique = function RecipeTechnique() {
    this.mainControl                = new BABYLON.GUI.Rectangle();
    this.mainControl.width          = "100px";
    this.mainControl.height         = "100px";
    this.mainControl.color          = "rgb(0, 0, 0)";
    this.mainControl.background     = "rgb(125, 166, 232)";
    this.mainControl.horizontalAlignment = BABYLON.BoneIKController.HORIZONTAL_ALIGNMENT_LEFT;
    this.mainControl.verticalAlignment = BABYLON.BoneIKController.VERTICAL_ALIGNMENT_TOP;

    this.mainControl.onPointerDownObservable.add((coordinates) => this.onPointerDown(coordinates));
    this.mainControl.onPointerUpObservable.add(() => this.onPointerUp());
    this.mainControl.onPointerOutObservable.add(() => this.onPointerOut());
    this.mainControl.onPointerMoveObservable.add((coordinates) => this.onPointerMove(coordinates));

    this.pointerDownCoordinates = BABYLON.Vector2.Zero();
    this.pointerDownLeft        = 0;
    this.pointerDownTop         = 0;
    this.isWaitForDrag          = false;
    this.isOnDrag               = false;
};

RecipeTechnique.prototype.onPointerDown = function onPointerDown(coordinates) {
    this.pointerDownCoordinates = coordinates.clone();
    this.pointerDownLeft        = this.mainControl._left._value;
    this.pointerDownTop         = this.mainControl._top._value;
    this.isWaitForDrag          = true;
};

RecipeTechnique.prototype.onPointerUp = function onPointerUp() {
    this.isWaitForDrag          = false;
    this.isOnDrag               = false;
};

RecipeTechnique.prototype.onPointerOut = function onPointerOut() {
    this.isWaitForDrag          = false;
    this.isOnDrag               = false;
};

RecipeTechnique.prototype.onPointerMove = function onPointonPointerMoveerDown(coordinates) {
    if (this.isWaitForDrag) {
        if (BABYLON.Vector2.Distance(this.pointerDownCoordinates, coordinates) > 10) {
            this.isOnDrag = true;
            this.isWaitForDrag = false;
        }
    }
    else if (this.isOnDrag) {
        var dragOffset  = coordinates.subtract(this.pointerDownCoordinates);
        var newX        = this.pointerDownLeft + dragOffset.x;
        var newY        = this.pointerDownTop + dragOffset.y;

        console.log(this.pointerDownLeft, this.pointerDownTop);
        console.log(dragOffset.x, dragOffset.y);
        console.log(this.mainControl.left, this.mainControl.top);
        console.log(newX, newY);

        this.mainControl.left = newX + "px";
        // this.mainControl.left = "10px";
        this.mainControl.top = newY + "px";
        // this.mainControl.top = "10px";
    }
};


module.exports = RecipeTechnique;
`

can you provide any suggestions how you see this functionality in your vision?

**Comment by deltakosh** [comment]
Perhaps exposing something good like control.position which is bound to left and top properties 
But I see several things to  consider :
• We must keep only properties in sync(how?)
• What if left or top were setup with percentage

**Comment by tovarisch** [comment]
Its an option to have readonly property `calculatedPixelPosition` which can hide percent value. or something like. I think i get you and might have better ideas, need to think about it more.

**Comment by deltakosh** [comment]
Yeah my point.
We can always expose a readonly value. Not a big deal
But a dual way variable won't be worth the complexity
