### ISSUE TITLE
GUI linkWithMesh, controls not able to be removed once linked

### ISSUE THREAD

**Issue by jasonayre** [BabylonJS/Babylon.js#2917]
Looks like if a control is linked with a mesh, it is no longer removable.

https://www.babylonjs-playground.com/#XCPP9Y#277

Also, is there any reason for the separate removeControl api having to exist at all? (i.e., could a dispose() method on the child controls replace removeControl, so calling child.dispose() would remove it from its parent? And parent.dispose() would remove children) Would be much easier to work with + consistent with the rest of babylon. Or is there a reason for the divergence?

**Comment by deltakosh** [comment]
I'll have a look to this bug
Regarding your question: You may want to remove a control but you may want to keep it to add it later.

**Comment by deltakosh** [comment]
I will also make sure that the dispose works like you described :)

**Comment by deltakosh** [comment]
Hey!
I cannot reproduce the issue. Anyway I will fix the dispose ;)

**Comment by deltakosh** [comment]
https://www.babylonjs-playground.com/#XCPP9Y#285
