### ISSUE TITLE
EnterWebVR button

### ISSUE THREAD

**Issue by mattwojo** [BabylonJS/Babylon.js#2929]
It would be very helpful to add a EnterWebVR button accessible via the Babylon library. 

I see that you have coded in such a button on this sample: https://david.blob.core.windows.net/babylonjs/SponzaVR/index.html 
![image](https://user-images.githubusercontent.com/7566797/31408276-d5b1a598-adbc-11e7-9741-a5404c865ca5.png)

It would be nice to easily call such a button from the library similar to how A-frame handles switching in and out of WebVR with such an icon: https://aframe.io/examples/showcase/helloworld/ 

![image](https://user-images.githubusercontent.com/7566797/31408245-b3bb362a-adbc-11e7-9582-e0e99b0d4343.png)

(added via svg in a CSS background in their case [.a-enter-vr-button](https://github.com/aframevr/aframe/blob/299eadfe7f1261e9dc6fc43aef75f8e3707a73cf/src/style/aframe.css))

**Comment by deltakosh** [comment]
Ping @davrous

**Comment by davrous** [comment]
Hello,

This is already the case if you use our logic via scene.createDefaultVRExperience()

David

**Comment by mattwojo** [comment]
Awesome -- thanks @davrous !

Is there any documentation available for how to properly use this logic? I can add that code to my project JS, but where do I get the headset image?

I tried it in a simple codepen here and am not having any luck yet: https://codepen.io/MicrosoftEdgeDocumentation/pen/QqrXLM
