### ISSUE TITLE
Improve particles System

### ISSUE THREAD

**Issue by deltakosh** [BabylonJS/Babylon.js#2971]
- [x] More emitter shapes (cone, sphere)
- [x] Noise:  Being able to read random values from perlin noise textures instead of pure JS random code
- [x] Sub emitters: Particles should be able to spawn a new system when they die

**Comment by IbraheemOsama** [comment]
Can you assign me this task :)

**Comment by deltakosh** [comment]
Will do as soon as you accept the invite

**Comment by IbraheemOsama** [comment]
@deltakosh yaaaaaaaaay I did it my self 😃 thanks David

**Comment by IbraheemOsama** [comment]
@deltakosh hi David, I don't get what is 
_Noise: Being able to read random values from perlin noise textures instead of pure JS random code_
I assumed you want to use a similar random method like class PerlinNoiseTextures but I don't see any similar functions. !!

**Comment by deltakosh** [comment]
So far the particles use random object from js
The idea would be to rely on external data loaded into an data array and use this data to generate random values.
The external data could be then loaded from an image containing perrin noise data (which can be generated by our procedural textures)

**Comment by IbraheemOsama** [comment]
@deltakosh have a few question if I want to generate random values between 1.5 and 2 for example then I should fill this array previously with values between 1.5 and 2 then use a random method to choose from this array isn't that less efficient than JS rand function ??

**Comment by deltakosh** [comment]
The idea is to let artists provide the random texture ( a gray level texture filled with value between 0 and 1). Then the random method will start for pixel at coordinate 0,0 and move forward to fetch new random values.
Does it make sense?
