### ISSUE TITLE
GUI not supported when zipping from Playground

### ISSUE THREAD

**Issue by ashanhol** [BabylonJS/Babylon.js#2973]
GUI worked fine when coding in browser, but as soon as you zip the file it's missing https://preview.babylonjs.com/gui/babylon.gui.min.js. 

**Note**: I'm happy to fix this since it seems like a one line add to the index.html in Babylon.js/Playground/zipContent.

**Comment by deltakosh** [comment]
Correct :) Please submit a PR. I will merge it asap !

**Comment by ashanhol** [comment]
Thank you @deltakosh, opened PR #2974 😄
