### ISSUE TITLE
Physics are too fast with CannonJS plugin ?

### ISSUE THREAD

**Issue by ivan-mogilko** [BabylonJS/Babylon.js#2978]
I am relatively new to the Babylon.js, so might not know or miss some things, for which I apologize beforehand, but I have a suspicion that there might be a mistake in how Babylon passes deltaTime into cannon.js physics engine.

It all started with me trying to predict the time at which a thrown ball will reach destination. I found that the ball moves noticeably faster than calculations tell (used classic kinematic formulas). Long story short, I went on investigating Babylon's source code (also running under debugger), and [found this call](https://github.com/BabylonJS/Babylon.js/blob/master/src/Physics/Plugins/babylon.cannonJSPlugin.ts#L40):

<pre>
public executeStep(delta: number, impostors: Array<PhysicsImpostor>): void {
     // Delta is in seconds, should be provided in milliseconds
     this.world.step(this._fixedTimeStep, this._useDeltaForWorldStep ? delta * 1000 : 0, 3);
 }
</pre>

Here delta is passed as milliseconds (multiplied by 1000 for that). There are two reasons why I suppose that this may be a mistake.

### First reason
Here is a playground test I made: https://www.babylonjs-playground.com/#BEFOO#210
It puts a ball at coordinates (0,10,0) and lets it freefall down. There is a registered callback that is called when ball touches ground and displays how much time has passed.

If we use formula of freefall ( t = Math.sqrt(2 * h / g) ) the ball should pass 10 meters in roughly 1.43 s.
(I also used [this online calculator](http://keisan.casio.com/exec/system/1224852055) just to double check myself). However, in Babylon it passes this distance in 0.47-0.48 s.

To see what happens if deltaTime is passed as seconds, I added an "override" for BABYLON.CannonJSPlugin.prototype.executeStep function in the very beginning of the code. Simply uncomment that part and fall duration will become 1.43-1.45 s.

### Second reason
During debugging I learnt that cannon.js intends to do physics processing in several steps, and the number of these steps are calculated by comparing "fixed time step" and "real delta time". 

This is, for example, the code  [from the latest cannon.js version on github](https://github.com/schteppe/cannon.js/blob/master/src/world/World.js#L536):
<pre>
this.accumulator += timeSinceLastCalled;
var substeps = 0;
while (this.accumulator >= dt && substeps < maxSubSteps) {
            // Do fixed steps to catch up
            this.internalStep(dt);
            this.accumulator -= dt;
            substeps++;
}
</pre>

The problem is that Babylon passes timeSinceLastCalled is milliseconds, but dt (or _fixedTimeStep from Babylon) is still in seconds (1/60 by default). This results in ridiculously high number of steps required (like 3000+ instead of 3). Although this number is capped by maxSubSteps, it still affects engine somehow.

It also looks like that seconds are passed to world.step in example provided in cannon.js [README.md](https://github.com/schteppe/cannon.js/blob/master/README.markdown):
<pre>
var dt = (time - lastTime) / 1000;
world.step(fixedTimeStep, dt, maxSubSteps);
</pre>

**Comment by RaananW** [comment]
Thanks for reporting!

I was pretty sure I fixed that already, I'll look into that.

**Comment by RaananW** [comment]
I remembered I fixed it :smile: https://github.com/BabylonJS/Babylon.js/commit/c1a0ecf3de4439b792a8a1611f0ca669113276e1 .
It made a lot of sense back then, as the entire scene was too slow. I guess I missed something, I am debugging this right now.

**Comment by RaananW** [comment]
Merged in the playground. No side effects so far.
