### ISSUE TITLE
Search is broken for this url: http://doc.babylonjs.com/playground?code=advancedTexture

### ISSUE THREAD

**Issue by deltakosh** [BabylonJS/Babylon.js#2979]

**Comment by Wingnutt** [comment]
Wow, thx for the bug issue submit, DK.  And thanks to the repair team, too.

7 bad PG saves... I think that's what causes it.  The metadata on those 7 repaired files... is stinky, somehow.  Maybe.  I'll shut up now.  :)

**Comment by Jaskar** [comment]
Hi @Wingnutt 
A weird typo was hidden in the playground.
I don't know why the playground accepted to save it!

@deltakosh You can close this issue please :)

**Comment by Wingnutt** [comment]
YAY!!!   Well done, Tony!  err... Jaskar.  :)  (Wingnut breathes again)  :)

Want to work on another "issue"?

http://doc.babylonjs.com/playground?code=showBoundingBox()   = fail

Perhaps expected, but can we prevent silent fail?  (thx for info)  (new issue?)

**Comment by deltakosh** [comment]
Yes please create another issue

**Comment by Wingnutt** [comment]
That was scary but I think I did it.  First time, I think.  Dog is hiding under bed.  :)
