### ISSUE TITLE
shadow value is reset to 1 in every lightFragment

### ISSUE THREAD

**Issue by makc** [BabylonJS/Babylon.js#2983]
I was trying to use babylon's native light in my shader along with texture-based shadow map like this:
```glsl
    float shadow=1.0 - texture2D(dynamicTexture, vTextureUV).x;
    #include<lightFragment>[0..maxSimultaneousLights]
```
what this computes to, however, is this:
```glsl
    float shadow=1.0 - texture2D(dynamicTexture, vTextureUV).x;
        info=computeHemisphericLighting(viewDirectionW,normalW,vLightData0,vLightDiffuse0.rgb,vLightSpecular0,vLightGround0,glossiness);
shadow=1.;
diffuseBase+=info.diffuse*shadow;
info=computeSpotLighting(viewDirectionW,normalW,vLightData1,vLightDirection1,vLightDiffuse1.rgb,vLightSpecular1,vLightDiffuse1.a,glossiness);
shadow=1.;
diffuseBase+=info.diffuse*shadow;
```

as you see, it completely defeats my attempt. I understand you generally need to calculate proper shadow for every light fragment, however, in this case I do not ask you to compute any shadows at all, so what's the need to reset it to 1?

the workaround I am using now is
```glsl
    diffuseBase -= info.diffuse * texture2D(dynamicTexture, vTextureUV).x;
```
but, obviously, this only fixes the shadow for one last light.

**Comment by deltakosh** [comment]
hello do you mind using the forum for question? :)

**Comment by makc** [comment]
@deltakosh I have no idea where the forum is, nor do I have an account there. I thought I would point out the inconvenience with your current lighting system but, if you are not interested, I do not care much either.

**Comment by deltakosh** [comment]
I care a lot n the contrary  :) but in order to get much more traction on your topic I suggest to just publish it here: http://www.html5gamedevs.com/forum/16-babylonjs/
