### ISSUE TITLE
Playground search failing with anyterm()  (trailing parentheses)

### ISSUE THREAD

**Issue by Wingnutt** [BabylonJS/Babylon.js#2985]
Playground search failing with anyterm()  (trailing parentheses)

identity()  (for example)  random(), too.  thx.

**Comment by Wingnutt** [comment]
Crap.  Even a single trailing SPACE on term like showBoundingBox... fails.  hmm.

**Comment by Jaskar** [comment]
Hmmm... It seems like T-SQL does not support queries with parentheses.
I'll search for a solution this week-end.

**Comment by Jaskar** [comment]
Temp fix on https://github.com/BabylonJS/Documentation-search-engine/pull/18
I'll check that after the week-end :)

**Comment by Wingnutt** [comment]
Thx J!
Want a new issue for trailing space?  Use this issue?  Thoughts?

**Comment by Jaskar** [comment]
Bad news. We're using "CONTAINS" clause in queries, and parentheses are prohibited.

**Comment by deltakosh** [comment]
There must be a void to escape them?

**Comment by Jaskar** [comment]
I have tried a bunch of escaping functions already but none of them seems to work
I'll try again later.

**Comment by deltakosh** [comment]
Double quote over the entire text should work: https://stackoverflow.com/questions/319730/escaping-bracket-in-a-contains-clause

**Comment by Jaskar** [comment]
Yes it works.
https://github.com/BabylonJS/Documentation-search-engine/pull/20
