### ISSUE TITLE
Cannot assign to read only property 'RGBA16F' of object in strict mode

### ISSUE THREAD

**Issue by yvele** [BabylonJS/Babylon.js#2988]
Edit: This is caused by strict mode, see https://github.com/BabylonJS/Babylon.js/issues/2988#issuecomment-340539936

I have the exact same error as https://github.com/BabylonJS/Babylon.js/issues/2642 but the issue is closed and I don't know why and how it has been resolved by OP

Context:
 - Developing on `localhost`
 - With MacOSX and ArchLinux
 - With Chrome and Firefox
 - Using `babylonjs` as a CommonJS module with rollup (and babel)
 - With `babylon.3.0-beta12.max.js` and `babylon.3.0-beta12.js`  (with and without npm)

Error:

> ```
> babylon.3.0-beta12.max.js:7623 Uncaught TypeError:
> Cannot assign to read only property 'RGBA16F' of object '#<WebGL2RenderingContext>'
>    at new Engine (babylon.3.0-beta12.max.js:7623)
> ```

It looks like the following [WebGL constants](https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API/Constants) `RGBA16F`, `RGBA32F` and `RGBA32F` are read only and cannot be set during engine creation.

See: https://github.com/BabylonJS/Babylon.js/blob/7482c84713f0b97d32e3e1a1ac42b70893b77468/src/Engine/babylon.engine.ts#L1080-L1082

Strangely `HALF_FLOAT_OES` can be set without any problem...

**Comment by deltakosh** [comment]
can you try with latest release?

**Comment by yvele** [comment]
@deltakosh I just tried with https://github.com/BabylonJS/Babylon.js/blob/7482c84713f0b97d32e3e1a1ac42b70893b77468/dist/babylon.max.js and I have the exact same problem

![image](https://user-images.githubusercontent.com/4225430/31832312-de01769e-b5c6-11e7-9361-e4543588a945.png)

**Comment by yvele** [comment]
Do you have any clues? It looks like we have no problem when using babylonjs as an external library.. we are now switching to rollup + babel with modules.. that's really strange because `_gl` is not a module.. Maybe some polyfills are messing around?

**Comment by deltakosh** [comment]
Can you try updating the source and set:
(<any>this._gl).RGBA16F = 0x881A

**Comment by yvele** [comment]
@deltakosh same problem

![image](https://user-images.githubusercontent.com/4225430/31832524-9d3870ee-b5c7-11e7-9099-699b921d9e93.png)

**Comment by yvele** [comment]
Simple question.. why are you setting those constants? Aren't constant supposed to be readonly? And by the way I checked and the [exact same values](https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API/Constants) are already set on my browser

**Comment by yvele** [comment]
@deltakosh hum ok

or another option is 

```js
if (this._gl.RGBA16F !== 0x881A) {
   this._gl.RGBA16F !== 0x881A;
}
```

That doesn't explain why the code is working when accessing to `babylon.3.0-beta12.max.js` with `<script src="" />` instead of rollup module.. 🤔

**Comment by deltakosh** [comment]
Certainly because babel (I guess it is the one which check that) can't see it?

**Comment by yvele** [comment]
Babel is not touching `babylon.3.0-beta12.max.js` at all.. either in commonjs module or `script`. I've explicitly excluded it from my babel plugin, that a good practice to exclude all `node_modules` and `vendors` folders.

My babel config is very simple I'm only using [`babel-preset-env`](https://github.com/babel/babel-preset-env) that is in charge of picking that appropriate polyfills. I've no weird transformations.

**Comment by deltakosh** [comment]
Hum so no idea ;)
I will push an update soon to fix it

**Comment by yvele** [comment]
I also now that `Cannot assign to read only property..` is a common error with people using modules for the first time but `this._gl` is not a module and is directly created via either:

- `canvas.getContext("webgl2", options)`
- `canvas.getContext("experimental-webgl2", options)`
- `canvas.getContext("webgl", options)`
- `canvas.getContext("experimental-webgl", options)`

I don't think babel or rollup can mess around with that. 

The only thing I can see are the polyfills.. because with rollup they are in the same scope as babylonjs and babylonjs is impacted with them.. Maybe the polyfills are making `this._gl` Object compliant with the constant standards and then does not allow it to be modified.. because it is actually a constant.

The babel polyfills comes from [core-js](https://github.com/zloirock/core-js) and maybe [one of those](https://github.com/zloirock/core-js/tree/de6719b9ca437e154663ff10c0eec76260851b01/modules) are activating some read only stuff ([getter](https://github.com/zloirock/core-js/blob/de6719b9ca437e154663ff10c0eec76260851b01/modules/es7.object.define-getter.js)? [define.property](https://github.com/zloirock/core-js/blob/de6719b9ca437e154663ff10c0eec76260851b01/modules/es6.object.define-property.js)?)

That's only suppositions 😄 

Can't wait for the fix, thanks!

**Comment by yvele** [comment]
@deltakosh I still have the issue with the latest release

I've seen that you've reverted the `if (...)` thing here in [this commit](https://github.com/BabylonJS/Babylon.js/commit/4a513abe21f8c93075c3b26f3c000de9a22e1cda#diff-c5e36d2c529e0623cfb58b616c79943fL8600) 🤔  Why did you revert this? Is it related to [strict check null](https://github.com/BabylonJS/Babylon.js/pull/2986)?

I figured out exactly why this is happening using a bundler like rollup or webpack, the thing is that the bundler is enabling **[strict mode](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode)** by default by adding `'use strict';` which is good for ES6

In rollup documentation https://rollupjs.org/#strict

> Strictly-speaking, ES6 modules are always in strict mode, so you shouldn't disable this without good reason.

So I still have the problem with those 3 lines:

```js
this._gl.RGBA16F = 0x881A; // RGBA 16-bit floating-point color-renderable internal sized forma
this._gl.RGBA32F = 0x8814; // RGBA 32-bit floating-point color-renderable internal sized forma
this._gl.DEPTH24_STENCIL8 = 35056;
```

But also in `new Mesh(...)` [at this line](https://github.com/BabylonJS/Babylon.js/blob/a79e2e828ddd38de855a935c4e29bf5a1d2ac42c/src/Mesh/babylon.mesh.ts#L178), the `Tools.DeepCopy`function is throwing [at this line](https://github.com/BabylonJS/Babylon.js/blob/a79e2e828ddd38de855a935c4e29bf5a1d2ac42c/src/Tools/babylon.tools.ts#L682):

```
Uncaught TypeError: Cannot set property source of [object Object] which has only a getter
    at Function.Tools.DeepCopy (babylon.3.0.7.max.js:5704)
    at new Mesh (babylon.3.0.7.max.js:19816)
    at Mesh.clone (babylon.3.0.7.max.js:21060)
```

Seems like `Mesh.source` is a getter (from `this._source`) and then cannot be set ⚠️ 

My workaround is to disable strict mode in my bundler, but I think there is several benefits to use **strict mode** directly in BabylonJS in development mode. In production mode we should be able to use it or not because there are many resources about **performance improvements**, see [this](https://news.ycombinator.com/item?id=9180338) and [this](https://github.com/petkaantonov/bluebird/wiki/Optimization-killers#3-managing-arguments) and [this](https://github.com/tweenjs/tween.js/issues/282).

@deltakosh do you want me to create 2 separate issues? Or to create another issue called **Enable strict mode**? Do you also think enabling strict mode is a good thing?

**Comment by deltakosh** [comment]
Sorry for the bug with constants. I'll revert back to what it was. I was looking for a bug and forgot to bring the code back
I'll also fix the this._source bug for sure
Regarding enabling strict mode, it has a lot of implications in the codebase and after introducing the strict null check I need more time before allowing another big rework

**Comment by yvele** [comment]
@deltakosh I think you forgot `DEPTH24_STENCIL8` (I made a copy/paste mistake in my issue)

There is another problem, in the case where the constants doesn't equal what we are expecting (the browser only supports WEBGL 1) then we will still get the error in **strict mode**.

May I suggest something more explicit like

```js

// Inspired by https://stackoverflow.com/a/10480227/1480391
const isStrict = (function() { return !this; })();

// See https://github.com/BabylonJS/Babylon.js/issues/2988
const trySetReadOnlyProperty = (prop, value) => {
  if (this._gl[prop] === value) {
    return;
  }
  if (isStrict) {
    // I don't know how you actually log warnings
    console.warning(`Cannot force property "${prop}" of WebGL context with strict mode enabled`);
    return;
  }
  this._gl[prop] = value;
}


// RGBA 16-bit floating-point color-renderable internal sized format.
trySetReadOnlyProperty("RGBA16F", 0x881A);

// RGBA 32-bit floating-point color-renderable internal sized format.
trySetReadOnlyProperty("RGBA32F", 0x8814);

trySetReadOnlyProperty("DEPTH24_STENCIL8", 35056);

```

If you want me to fill a PR, I'll do it

**Comment by deltakosh** [comment]
I'm in a middle of an update so I'll add it no worry :) (directly though)
