### ISSUE TITLE
Add option to automatically adapt the scaling level based on performances

### ISSUE THREAD

**Issue by sebavan** [BabylonJS/Babylon.js#2995]
We are currently choosing statically the hardware scaling level. It would be nice to have an option to automatically scale up/down the scaling level based on the FPS o better benefits form the hardware capabilities of the target device/experience.

**Comment by sebavan** [comment]
Scaling up when static would also be nice.

**Comment by deltakosh** [comment]
I will add more flexibility to the SceneOptimizer in order to get support for it seamlessly
