### ISSUE TITLE
Implement rectangle mesh?

### ISSUE THREAD

**Issue by cyle** [BabylonJS/Babylon.js#30]
Hi, it'd be great if there was a Mesh.CreateRect() method that works like Mesh.CreateBox() but accepts width, height, depth instead of just "size". I created my own that just does CreateBox and then applies scaling to x, y, and z, but then any child mesh will be scaled the same way. Is this possible, or outside the scope of current plans? Thanks!

**Comment by kevzettler** [comment]
This should be in the core library
