### ISSUE TITLE
Add support for clipboardData pasting

### ISSUE THREAD

**Issue by deltakosh** [BabylonJS/Babylon.js#3006]
Let the engine load data from the clipboard if the clipboard contains relevant data

**Comment by IbraheemOsama** [comment]
Should we close this issue @deltakosh  ? 
(For Reference) it is not possible right now to achieve this behavior. tested on Chrome & FireFox but not working.

**Comment by deltakosh** [comment]
You are right.CLosing for now until we can do it in browsers :)
