### ISSUE TITLE
Tiny ui error when labels are too  long

### ISSUE THREAD

**Issue by deltakosh** [BabylonJS/Babylon.js#3050]
http://doc.babylonjs.com/how_to/optimizing_your_scene#instrumentation

**Comment by Temechon** [comment]
Would it be acceptable to have three dots at the end of the word ? 
For example, today we have : 
```
onNewMeshAddedObservab
le
```
With this solution, it would be:
```
onNewMeshAddedObserv...
```

**Comment by deltakosh** [comment]
Oh yes:)

**Comment by Temechon** [comment]
Perfect. It will be done tonight 👍
