### ISSUE TITLE
Alpha shows as latest in npm

### ISSUE THREAD

**Issue by corbinu** [BabylonJS/Babylon.js#3055]
The current alpha always shows as latest in npm rather than the latest stable version

https://docs.npmjs.com/cli/dist-tag

```
Package         Current        Wanted          Latest  Location
babylonjs         3.0.7         3.0.7  3.1.0-alpha3.6
```

**Comment by deltakosh** [comment]
Ping @raananw

**Comment by RaananW** [comment]
Hi,

this is actually deliberate. Due to the way we deal with bugs and new features (and backwards-compatibility) the latest "stable" is actually the alpha :smile:

I do agree this is confusing, and will discuss it internally with the team to see if we can use better terms. We do say "alpha" and "beta", but still use it as stable. 

Not closing ATM.

**Comment by corbinu** [comment]
Ok does that mean the main release is some kind of LTS or something?

**Comment by deltakosh** [comment]
Exactly. Updated every 6months or so

**Comment by corbinu** [comment]
Ahh ok ya better language on that it is not a preview release is probably the correct solution then. Will bump my version.

**Comment by corbinu** [comment]
Version seems jacked up again. I have it set as `"^3.2.0-alpha10"`

however I keep getting `babylonjs  3.2.0-alpha9  3.2.0-alpha9  3.2.0-alpha10  packingviewer` when I run `npm update`

**Comment by deltakosh** [comment]
Just remove the caret before the version. We will fix the numbering for beta version (alpha10 is considered alpha1 by npm)

**Comment by corbinu** [comment]
Ok can this at least be reopened then as a marker that the naming scheme should be reconsidered as @RaananW suggested

**Comment by deltakosh** [comment]
We will make sure to do it now worry

**Comment by corbinu** [comment]
This is happening again

**Comment by deltakosh** [comment]
Not sure why? Done you get alpha.1 now?

**Comment by deltakosh** [comment]
I mean 3.3.0-alpha.0 should be smaller than 3.3.0-alpha.1

**Comment by corbinu** [comment]
No I get 3.2.0 Your naming scheme is not valid semver

**Comment by deltakosh** [comment]
How could you get 3.2 when 3.3.0is part of the naming? What could be the good naming then?

**Comment by corbinu** [comment]
I am saying that my project has the version specified at ^3.2.0 which will automatically pick up 3.3.0 when it is released but will not automatically install 3.3.0-alpha.* even though the ^ specifies to give me 3.*.*

So as my original post pointed out by telling NPM that a version is latest (and therefor stable) but naming its version in a way that semver considers not stable NPM has no idea how to handle that and so it doesn't pull the new version.

The semver documentation can be found here: https://semver.org/

**Comment by deltakosh** [comment]
So how would you recommend you name intermediate version? 3.3.0.1?

**Comment by deltakosh** [comment]
But if I read correctly the semver site, we are doing it correctly :)
Adding -alpha identifies pre-release so we are good. 

Sorry then I do not understand the problem here.

**Comment by corbinu** [comment]
latest indicates to NPM that it is not prerelease so there is a direct conflict. Your naming it as pre-release and then publishing it as stable. All you need to do is not tag it as latest when you publish

**Comment by deltakosh** [comment]
But what will try change for you? Only trying to understand

**Comment by corbinu** [comment]
It will cause npm to not report that there is a new version when it shouldn't. Again read my orignal post.

If you go here https://docs.npmjs.com/cli/dist-tag

You can read the section ```
Publishing a package sets the latest tag to the published version unless the --tag option is used. For example, npm publish --tag=beta.
```

This is what babel does for example. In this case you would tag it as alpha instead of latest then I stay on the stable version but don't get warnings that there is a new stable version when there is not.

**Comment by deltakosh** [comment]
OK gotcha. I see your point. Will fix that

**Comment by corbinu** [comment]
thanks!

**Comment by RaananW** [comment]
Latest is now the latest stable release. Alpha and beta releases will be a part of the "preview" stream on npm, so you can install `babylonjs@preview` to get the latest push to npm, or `babylonjs@latest` to get the latest stable.
