### ISSUE TITLE
[question ] will you condider support uv tiling and offset  for gltf2.0 format?

### ISSUE THREAD

**Issue by sonygod** [BabylonJS/Babylon.js#3068]
will you condider support uv tiling and offset  for gltf2.0 format? or  already  have done that?
current gltf2.0 do not support uv tiling and offset ,Don't know why ?
here what I want to know babylon.js tearm will consider these features?
and some extent information into gltf format to support that ?

**Comment by deltakosh** [comment]
Hello I think this question would be more appropriate on gltf repo:)
Babylon.js natively supports uv tiling and offset so as soon as gltf will support it we will enable it for our gltf loader

**Comment by sonygod** [comment]
thank you for reply !
