### ISSUE TITLE
Inspector does not work in either IE11 or Edge

### ISSUE THREAD

**Issue by abow** [BabylonJS/Babylon.js#3084]
To reproduce the issue, open up the PG in IE11 or Edge and view the debug layer.

**Comment by deltakosh** [comment]
Ping @Temechon : Is that something you can work on ? I try to close all issues before 3.1

**Comment by Temechon** [comment]
I'll see what I can do, but debugging IE/EDge is very difficult as the browser crash as soon as the console is opened...

**Comment by deltakosh** [comment]
For IE This may require a win7 install:(

**Comment by deltakosh** [comment]
Up?

**Comment by QuentinRillet** [comment]
I'm on it but like @Temechon when I launch IE it crashes directly, I'm looking for a solution.

**Comment by abow** [comment]
The only way I know of to debug IE11 issues is by using Visual Studio.

**Comment by deltakosh** [comment]
or with a win7 build

**Comment by sebavan** [comment]
Color picker is the culprit input type="color" makes it crash please disable on IE

**Comment by Temechon** [comment]
Didn't see your comment but came to the same conclusion! Thank you :)
It's fixed now.
