### ISSUE TITLE
Exporting from Blender: Y and Z axes are flipped

### ISSUE THREAD

**Issue by cyle** [BabylonJS/Babylon.js#31]
Hello again. I'm having a weird issue exporting models from Blender into Babylon.js -- it seems that the axes get flipped around. For example, if I make a cone in Blender and point it upwards along the Z axis, it imports into Babylon as pointing along the Y axis. Putting a sphere at (x = 0, y = 0, z = 1) in Blender results in the item importing as (x = 0, y = 1, z = 0) in Babylon.js. Is this something that could be fixed in the exporter? It looks like line 66 of io_export_babylon.py is flipping the Y and Z coordinate -- is that intentional? It seems to also be the case on lines 435 and 436, as well. Any help would be appreciated! Thanks.

**Comment by marcusdiy** [comment]
Yep. Seems like this problem was not solved. Exporting with "Preserve Z-up right-handed" doesnt work eighter. I tried to export using Blender 2.91.2 and for preview https://sandbox.babylonjs.com/
