### ISSUE TITLE
Add support for VRExperienceHelper to Mansion scene and add it to main babylonjs.com website

### ISSUE THREAD

**Issue by deltakosh** [BabylonJS/Babylon.js#3119]
https://david.blob.core.windows.net/babylonjs/SponzaVR/index.html

**Comment by deltakosh** [comment]
Also add mansion VR demo

**Comment by davrous** [comment]
Mansion VR is now completed thanks to the last version of the VRHelper: http://playground.babylonjs.com/#JA1ND3#15
