### ISSUE TITLE
bug: mesh.updateIndices() behaves differently according to the passed typed array

### ISSUE THREAD

**Issue by jbousquie** [BabylonJS/Babylon.js#3134]
https://playground.babylonjs.com/#A4V5U3

The user can't know how the indices array is converted in the underlying index buffer but he's allowed to pass the type he wants to updateIndices()
If the passed type differs from the generated one under the hood, it leads to weird shapes

**Comment by deltakosh** [comment]
Not a bug for me. There is an expected format and you have to stick with it.
Not sure to know how we can help on that.

This is an advanced function expecting 16 bits indices unless you create a mesh with more than 65536 vertices

**Comment by jbousquie** [comment]
ok, I reacted to fast by putting a bug here
Let's inform the user in the API doc that he needs to pass the same type in the parameter than the one of existing indices array
ok for this ?
(and let's close this ;-) )

**Comment by deltakosh** [comment]
sure thing
