### ISSUE TITLE
setPivotPoint not working correctly in the beta version

### ISSUE THREAD

**Issue by aminebens** [BabylonJS/Babylon.js#3146]
Since the switch from version alpha 3.7 to version beta 1.1, the setPivotPoint behaviour seemed to have change and the mesh position is translated to the world space even if setting it to Space.LOCALE.

**Comment by deltakosh** [comment]
Do you have a repro in the playground?

**Comment by deltakosh** [comment]
Ping? @aminebens

**Comment by aminebens** [comment]
I tried on the playground, it seems to work fine:
[http://www.babylonjs-playground.com/#PVXRL8](url)
However I notice that the problme in our case was that the worldMatrix was not correctly calculated anymore since beta. 
before in the method getWorldMatrix,

`AbstractMesh.prototype.getWorldMatrix = function () {
if (this._masterMesh) {
		return this._masterMesh.getWorldMatrix();
	}
	if (this._currentRenderId !== this.getScene().getRenderId() || !this.isSynchronized()) {
		this.computeWorldMatrix();
	}
	return this._worldMatrix;
};`

the condition !this.isSynchronized() was met and the method this.computeWorldMatrix(); was called which gave the correct matrix.

Since beta, the method changed to
`AbstractMesh.prototype.getWorldMatrix = function () {
            if (this._masterMesh) {
                return this._masterMesh.getWorldMatrix();
            }
            return _super.prototype.getWorldMatrix.call(this);
 };`
which give the wong matrix

**Comment by deltakosh** [comment]
if you want you can force the complete matrix resync at any time with mesh.computeWorldMatrix(true)

My fix was to avoid computing world matrix too much which is a big problem on low end devices.

**Comment by deltakosh** [comment]
I'm closing this one as we have an explanation. Please feel free to reopen if it is not the case
