### ISSUE TITLE
Inspect if we can support es6 imports without breaking UMD support

### ISSUE THREAD

**Issue by RaananW** [BabylonJS/Babylon.js#3147]
At the moment we compile Babylon with es5 in mind, using UMD (supporting commonJS, AMD and in-browser). 
Will it be possible to add es6 support?

**Comment by deltakosh** [comment]
As we need to support ie11, I'm afraid no:(

**Comment by RaananW** [comment]
es6 requires "export", so we might be able to extend the UMD to check if "export" is supported (as opposed to "exports, or define). This will be a simple inspection with a simple yes or no. We won'T compile the entire framework using es6, but only allow exposing the BABYLON namespace.

**Comment by deltakosh** [comment]
Oh ok..so I'm fine with it :D

**Comment by RaananW** [comment]
So, closing.
export is (as I feared) a keyword which cannot be a part of an expression or caught with an exception. Was hoping it is possible, but it only makes sense that it isn't.

So, it's a no!
