### ISSUE TITLE
Path2 addLineTo use a global "closed" variable

### ISSUE THREAD

**Issue by jddaigle** [BabylonJS/Babylon.js#3151]
Hi,
I found a problem runing a single Typesript file with a simple method using Path2.addLineTo.
Path2 addLineTo and addArcTo use a global "**closed**" variable rather than the **this.closed** variable,  filled in the constructor of Path2.

In this specific case the global **closed** variable hasn't been initialized.

Look at the first line of the addLineTo method

tks!

**Comment by deltakosh** [comment]
Hello can you repro in the playground?

Ping @jbousquie

**Comment by jddaigle** [comment]
nope... in this case I didn't use the scene and cam. So something in the initialization of the environment must set "closed" variable to false.

to reproduce, run only this:

import * as BABYLON from 'babylonjs'

export class Test {
    public init() {
        const pline = new BABYLON.Path2(0, 0)
        pline.addLineTo(0, 1)
        pline.addLineTo(1, 1)
        pline.addLineTo(1, 0)
        pline.close()
    }
}

const instance: Test = new Test()
instance.init()

**Comment by deltakosh** [comment]
Sorry not sure to see what the problem is
I did this repro:
https://www.babylonjs-playground.com/#KD1AHI

**Comment by jddaigle** [comment]
As I said, something somewhere must set the variable to false, during the init phase. If you put my class (previous post) into an EDI like Visual Source Code and run it il will crash...

Loot at this snippet of babylon.max.js, in the ctor the this,closed variable is initialized and in the method addLineTo the global variable "**closed**" is used (without the "**this**")

var Path2 = (function () {
        /**
         * Creates a Path2 object from the starting 2D coordinates x and y.
         */
        function Path2(x, y) {
            this._points = new Array();
            this._length = 0.0;
            **this.closed = false;**
            this._points.push(new Vector2(x, y));
        }
        /**
         * Adds a new segment until the passed coordinates (x, y) to the current Path2.
         * Returns the updated Path2.
         */
        Path2.prototype.addLineTo = function (x, y) {
            **if (closed) {**
                //Tools.Error("cannot add lines to closed paths");
                return this;
            }
            var newPoint = new Vector2(x, y);
            var previousPoint = this._points[this._points.length - 1];

**Comment by deltakosh** [comment]
Ok gotcha I'll fix it for next commit :)
thanks a lot

**Comment by jddaigle** [comment]
thanks !

**Comment by deltakosh** [comment]
Fixed!
