### ISSUE TITLE
_getPluginForFilename breaks for query strings containing periods

### ISSUE THREAD

**Issue by FreakTheMighty** [BabylonJS/Babylon.js#3156]
I'm generating a signed url using google cloud storage. I've placed an example URL below (Not a working url). The query parameters contain `.` which is throwing off the plugin selection [here](https://github.com/BabylonJS/Babylon.js/blob/c1e88daa4a1c944d0fca6336672d98fb373474e3/src/Loading/babylon.sceneLoader.ts#L128).

I have a few thoughts/questions.

* Is there a reason to have `rootUrl` and `sceneFilename` [here](https://github.com/BabylonJS/Babylon.js/blob/c1e88daa4a1c944d0fca6336672d98fb373474e3/src/Loading/babylon.sceneLoader.ts#L346) aside from picking the loader plugin? I found it a little annoying to have to parse my url into those separate parts. I'd prefer to just pass the entire path into the loader.

* Is there a way to be more explicit about which plugin to use?

Example of problematic url
-------
https://storage.googleapis.com/somebucket/YellowCar.glb?GoogleAccessId=bucket-upload@someproject.iam.gserviceaccount.com

This results in this `?googleaccessid=bucket-upload@someproject.iam.gserviceaccount.com` being extracted as the extension.

**Comment by FreakTheMighty** [comment]
My apologies, it looks like this was a parsing error on my end.

**Comment by deltakosh** [comment]
The reason we need both is because the rootUrl will be use to load additional resources like textures

(No problem :))

**Comment by FreakTheMighty** [comment]
Got it, makes sense. On third inspection there may still be an issue here:

## With period in query params
```js
SceneLoader._getPluginForFilename("YelloCar.glb?GoogleAccessId=foo.bar")
```

results in

```json
{"plugin":{"name":"babylon.js","extensions":".babylon"},"isBinary":false}
```

## Without period
```
SceneLoader._getPluginForFilename("YelloCar.glb?GoogleAccessId=foobar")
```
You get the right plugin
```
{"plugin":{"coordinateSystemMode":0,"name":"gltf","extensions":{".gltf":{"isBinary":false},".glb":{"isBinary":true}}},"isBinary":true}
```

**Comment by deltakosh** [comment]
There is a way to specify the extension you want to force:
https://github.com/BabylonJS/Babylon.js/blob/master/src/Loading/babylon.sceneLoader.ts#L253
(check last parameter)

**Comment by FreakTheMighty** [comment]
@deltakosh thanks for pointing that out. That unblocked me. Not sure if you want to keep this open to improve the extension parsing, I'll leave that up to you.

**Comment by deltakosh** [comment]
I keep it open because I want to fix this issue:)
