### ISSUE TITLE
Error: Cannot set property hasLODLevels of <Mesh> which has only a getter

### ISSUE THREAD

**Issue by tommhuth** [BabylonJS/Babylon.js#3158]
Trying to `clone` a mesh, throws this error in the console: 

```
Uncaught TypeError: Cannot set property hasLODLevels of [object Object] which has only a getter
    at Function.Tools.DeepCopy (babylon.max.js:6337)
    at new Mesh (babylon.max.js:22911)
    at Mesh.clone (babylon.max.js:24259)
    at makeBox (app.js:20)
    at match (app.js:102)
    at HTMLDocument.<anonymous> (app.js:107)
```

Similiar error happens if I try to use `createInstance` . Is this a know bug in the 3.1.0-beta3? I'm using webpack to build, and error happens in Chrome 62.

**Comment by deltakosh** [comment]
Hello
can you repro in the playground?
I tried this simple one and it works:
https://www.babylonjs-playground.com/#BWG24J

**Comment by tommhuth** [comment]
that playground froze my tab :/

im not really doing anything exotic, simply and array of meshes, and trying to get clone on picked out of those

**Comment by deltakosh** [comment]
Woot really? Could you try again with f12 console opened?

**Comment by tommhuth** [comment]
that forced my debug console to close? There seems to be alot of problems with the playgrounds tho, I've come across many that do not load, or error out.

**Comment by deltakosh** [comment]
I'm not aware of any of them so I'm really interested to see your console outputs.

Remember also that playgrounds are done by users from the community so they may contain wrong code::)

**Comment by deltakosh** [comment]
Any update?

**Comment by tommhuth** [comment]
I was referring to playgorunds linked to from the docs, sorry I cannot remember which one now, just that it was more than one. 

could it possibly have something to do with the mesh being stored in an array and access from there?  (that wouldn't make any sense to me, but I am an noob at this)

**Comment by tommhuth** [comment]
The playground works now, and i get no errors.

**Comment by deltakosh** [comment]
Regarding doc playgrounds: please report them here if you find them again

Regarding your initial question: Can you try to replicate your code in the playground ? I need a repro case to find the source cause :)

**Comment by TrevorDev** [comment]
[Here ](https://www.babylonjs-playground.com/index.html#9V5FER )is a playground with an example of cloning a loaded mesh. 

[Here ](https://github.com/TrevorDev/babylonExperiments/tree/webpackBuild)is a small babylon project using webpack to build with a mesh that is cloned

Both are working in chrome 62 so I will close this unless a repro case can be provided.
