### ISSUE TITLE
Bower Package

### ISSUE THREAD

**Issue by Aeal** [BabylonJS/Babylon.js#316]
It would be great to have this as a bower component!

**Comment by JeroMiya** [comment]
I don't think so. I have plans to use hand.js for non Babylon projects (now that chrome devs are no longer implementing them). It is better to limit its scope to just a pointer events polyfill.

**Comment by deltakosh** [comment]
Agree

**Comment by neutrino84** [comment]
hand.js needs to be on bower
babylon.js needs to be on bower
pleeeeeseeee :D
