### ISSUE TITLE
Poor assumptions about file protocol lead to failure.

### ISSUE THREAD

**Issue by emackey** [BabylonJS/Babylon.js#3171]
Some environments allow local file access from JavaScript.  In particular, Electron-based environments, such as the HTML preview window in Visual Studio Code, allow this.

There are at least two different places in Babylon where a poor assumption about the presence of `file:` in a string leads to local file access failure.  One is on [line 460 of Babylon.Tools.LoadImage](https://github.com/BabylonJS/Babylon.js/blob/96541517193b5d7bdc19ed006ab4552e78244af5/src/Tools/babylon.tools.ts#L460) and another is on [line 540 of Babylon.Tools.LoadFile](https://github.com/BabylonJS/Babylon.js/blob/96541517193b5d7bdc19ed006ab4552e78244af5/src/Tools/babylon.tools.ts#L540).

The presence of `file:` leads Babylon to look in `FilesInput.FilesToLoad`, which is not correct for this case.  The intended behavior in this use case is to send the full XHR request to the file-protocol URL as-is.

For Windows-based local-drive filenames, this problem can be worked around:  The Windows drive letter is enough of a clue to Chromium to load from the local file, even without the file protocol being specifically named on the front of the URL.  But on Mac/Linux/Unix systems, or even on Windows network shares, there is no drive letter on the front of the URL, and the URL ends up looking like a host-relative root path, not a file-protocol path.  Adding an explicit `file:` protocol to the front of such URLs is the only available fix, but Babylon sees that and refuses to issue an XHR request at all.

/cc @bghgary @sbtron This is deeply related to the issue blocking the glTF Extension for VSCode from working on other platforms, see https://github.com/AnalyticalGraphicsInc/gltf-vscode/issues/58#issuecomment-345111944

**Comment by deltakosh** [comment]
An easy to implement fix could be to add a general flag in the engine to tell it to no uses filesInput if file:// is found
So in election kind of environment you could just set this flag to true

**Comment by deltakosh** [comment]
Or even better :
We could try first to load from filesInput and if not found then simply issue an xhr
Thoughts?

**Comment by emackey** [comment]
Both sound good.  I wonder if other devs would want the auto-fallback, or would want control with a flag?

I think either one would work for me.

**Comment by deltakosh** [comment]
I'll give it some thoughts and implement one asap:)

**Comment by emackey** [comment]
(Unrelated but, thanks for `babylon.max.js` in the npm package, that's super helpful!)

**Comment by emackey** [comment]
Awesome.  Did you want to fix `Tools.LoadImage` too?  Seems like the same logic there.

**Comment by deltakosh** [comment]
My bad I forgot about this one

**Comment by deltakosh** [comment]
Ok better now!

**Comment by emackey** [comment]
Thanks!

**Comment by deltakosh** [comment]
Not sure about that fix..We still need to detect the present of real files. Would love to review a PR as this will be easier to discuss over ;)

**Comment by emackey** [comment]
@pascalbayer This issue is believed already fixed and closed.  Can you share a reproduce case where it's still broken?  Are you using an old version?

**Comment by pascalbayer** [comment]
@emackey This can be reproduced on the latest 4.0.0-alpha.6 by loading a file with rootUrl `file://` via `SceneLoader.ImportMeshAsync()`. I would be happy if there is a workaround that I'm not aware of.

**Comment by pascalbayer** [comment]
Proposal to fix the described behavior: #5468

**Comment by deltakosh** [comment]
This is a perfect fix! Merging!

**Comment by pascalbayer** [comment]
Thanks @deltakosh! Looking forward to see it in the next preview release
