### ISSUE TITLE
Babylon 3.1 beta 3 - Firefox 57 - Error: WebGL warning: drawElements

### ISSUE THREAD

**Issue by dcardin** [BabylonJS/Babylon.js#3180]
Error: WebGL warning: drawElements: Active texture 0 for target 0x0de1 is 'incomplete', and will be rendered as RGBA(0,0,0,1), as per the GLES 2.0.24 $3.8.2: The dimensions of `level_base` are not all positive.

Is that a problem in our code that doesn't show on chrome? or is that a problem with FFox?

Thanks

**Comment by deltakosh** [comment]
Hello can you repro on any sample on the playground?

**Comment by deltakosh** [comment]
If not, could you try to repro in the playground so we can analyze this further

**Comment by dcardin** [comment]
I'll see if I can do that. It is related to a polygon mesh, super thin (0.01) with an SVG texture and an alpha channel. Juste au cas où ça parle ;)

**Comment by deltakosh** [comment]
Thanks ;) Clearly the problem seems to come from the SVG texture

**Comment by dcardin** [comment]
To give you an idea of how it's used (there is some object context, but you'll get the idea
`

        const shape = new Path2(this.startX, this.startY)
            .addLineTo(this.startX + this.buttonWidth, this.startY)
            .addLineTo(this.startX + this.buttonWidth, this.startY + this.buttonHeight)
            .addLineTo(this.startX, this.startY + this.buttonHeight)
            .addLineTo(this.startX, this.startY)
            .close()

        const polygonButtonTriangulation = new PolygonMeshBuilder(this.assetName, shape, this.scene)
        const polygonButton = polygonButtonTriangulation.build(false, 0.01)
        const texture = new Texture(this.assetName, this.scene)
        const buttonMaterial = new StandardMaterial('handleMaterial', this.scene)
        buttonMaterial.opacityTexture = texture
        buttonMaterial.diffuseTexture = texture
        buttonMaterial.useGlossinessFromSpecularMapAlpha = false
        texture.hasAlpha = true
        buttonMaterial.specularColor = new Color3(0.02, 0.02, 0.02)

        polygonButton.material = buttonMaterial

        const pivotCenter = polygonButton.getBoundingInfo().boundingBox.center
        polygonButton.setPivotPoint(new Vector3(pivotCenter.x, pivotCenter.y, pivotCenter.z))

        polygonButton.rotation.y = this.rotation
        polygonButton.position.y = this.parent.getPosition().y + 10.1
`

**Comment by dcardin** [comment]
Rename as svg, obviously :)

[stairs.txt](https://github.com/BabylonJS/Babylon.js/files/1484297/stairs.txt)

**Comment by deltakosh** [comment]
if you can repro a simple example in the PG I will be able to fix it (if this is not a pure firefox issue)

**Comment by dcardin** [comment]
I'll have to figure out how to refer to external svg. 
It works find in chrome though... and it used to work in FFox, up until 57

**Comment by deltakosh** [comment]
This looks really suspicious yeah:)
You can share files from github using cdn.rawgit.com

**Comment by deltakosh** [comment]
Did you manage to get more info about this issue? Or a repro ?
