### ISSUE TITLE
Cube Map DDS issues

### ISSUE THREAD

**Issue by benaadams** [BabylonJS/Babylon.js#3188]
Single file DDS doesn't parse correctly; for compressed texture `bbs` is always `0` so `dataOffset` doesn't advance:

https://github.com/BabylonJS/Babylon.js/blob/e3b20e41f69b3aa7f43269ae08126eb9db5d00b4/src/Tools/babylon.dds.ts#L520

Multi-file DDS ignores the `files` parameter  only loading single `rootUrl`
https://github.com/BabylonJS/Babylon.js/blob/e3b20e41f69b3aa7f43269ae08126eb9db5d00b4/src/Engine/babylon.engine.ts#L3933

**Comment by benaadams** [comment]
I'd probably prefer the multi-file as making a single file cubemap DDS has very poor tooling. Will have a look in the morning.

**Comment by deltakosh** [comment]
Do you have a file for me to test? For the bbs issue I mean

**Comment by benaadams** [comment]
var bpp = header[off_RGBbpp]; //off_RGBbpp == 22

Regular DX1 dds:

header 
```
0: 542327876
1:124
2:659463
3:2048
4:2048
5:2097152
6:0
7:12
8:0
9:0
10:0
11:0
12:0
13:0
14:0
15:0
16:0
17:0
18:0
19:32
20:5
21:827611204
22:0
23:0
24:0
25:0
26:0
27:4198408
28:0
29:0
30:0
```

Cubemap dds: https://aoa.blob.core.windows.net/babylon/spacedrop.dds

**Comment by deltakosh** [comment]
Thanks! I'll have a look :)

**Comment by benaadams** [comment]
Would just changing
```
dataOffset += width * height * (bpp / 8);
```
to
```
dataOffset += dataLength;
```
do it or any of the other dataLengths non 1:1 with the input data?

**Comment by deltakosh** [comment]
this seems the best fix to me: dataOffset += dataLength;
We have the dataLength on every case so this should work
