### ISSUE TITLE
LinesMesh.alpha not working anymore

### ISSUE THREAD

**Issue by Kesshi** [BabylonJS/Babylon.js#3200]
setting the alpha value of a line does not work in the latest Version:
https://playground.babylonjs.com/#GSWPLY
the stable version is working:
https://playground.babylonjs.com/indexstable#GSWPLY

**Comment by jbousquie** [comment]
@deltakosh 
it seems that the alphablending was always enabled by default on LinesMesh (last JCPalmer's commit :  https://github.com/BabylonJS/Babylon.js/commit/4c55dc653b74e6a7b51f8ec810642c4a596d3a90#diff-4385e2867e9b0fa4a74500e56db24bd0 ) before my last fix where you recommended me to enable it only on demand, here : https://github.com/BabylonJS/Babylon.js/commit/a7ec87305548e0a7af7a70255258fba68f3215e4#diff-4385e2867e9b0fa4a74500e56db24bd0

Should I modify it back to always set alphablendind to `true` ?
Please let me know _(if this is the cause of the issue)_ .

**Comment by deltakosh** [comment]
Rats... can you just keep your parameter but set it to true by default?

**Comment by jbousquie** [comment]
Ok, will do it tomorrow

**Comment by deltakosh** [comment]
thanks!
