### ISSUE TITLE
gltf 1.0 model loading is having issues.

### ISSUE THREAD

**Issue by sebavan** [BabylonJS/Babylon.js#3207]

**Comment by julien-moreau** [comment]
What kind of issue ?

**Comment by sebavan** [comment]
seem to be only sandbox actually:
https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/1.0

**Comment by cx20** [comment]
I tried to display the glTF 1.0 model in the latest version of Babylon.js (3.1 beta-6).
https://github.com/cx20/gltf-test/blob/1.0/README.md
https://cdn.rawgit.com/cx20/gltf-test/c4c3bb30f3a7d5b6d92e8c3198838741175be266/index.html

However, I confirmed that some models are not displayed.
Several skinning animation models and models of version 1.0.1 do not appear to be displayed.

Below is the test result of the previous Babylon.js (2.6).
https://github.com/cx20/gltf-test/blob/317363071f100df5ae7ebbc7d747319451bdf8fd/README.md
https://cdn.rawgit.com/cx20/gltf-test/a3cff7d95e33d626e81e2487159603cf84d2f9bb/index.html

**Comment by sbtron** [comment]
1.0.1 wasn't an official release was it? Should the assets just be 1.0 ?

**Comment by deltakosh** [comment]
Agree we only need to support 1.0

**Comment by cx20** [comment]
If you output the glTF 1.0 model with collada2gltf, the version seems to be 1.0.1.

Relate:
https://github.com/KhronosGroup/glTF-Sample-Models/issues/71

**Comment by kcoley** [comment]
PR created #3254
