### ISSUE TITLE
corrupted textures if multiple cameras/viewports are used

### ISSUE THREAD

**Issue by Kesshi** [BabylonJS/Babylon.js#3210]
If multiple viewports are used texture are shown with black borders.
See this playground:
https://www.babylonjs-playground.com/index.html#HV6CD1
its still working with the stable release:
https://www.babylonjs-playground.com/indexstable#HV6CD1

This only happens on browsers without WebGL 2 support (Edge, IE).
It seems to be related to the resizing of the textures (power of 2)

**Comment by deltakosh** [comment]
Thanks for reporting it!
