### ISSUE TITLE
Using Mesh.lookAt doesn't update Mesh.rotation

### ISSUE THREAD

**Issue by Exolun** [BabylonJS/Babylon.js#3237]
Described in subject, calling .lookAt doesn't update the .rotation transform values.

Example:
https://www.babylonjs-playground.com/#LEDXWF

Note:  The value of rotationQuaternion is affected.

**Comment by sebavan** [comment]
This is by design cause when the quaternion is set it is the one in use. 

You  can not change the euler notation anymore.

@Exolun  do you have a special use case where you need it after ?

**Comment by sebavan** [comment]
Agree, Will be built in dist tonight.
