### ISSUE TITLE
Material's uniform cannot be updated after another material is added

### ISSUE THREAD

**Issue by zhutq** [BabylonJS/Babylon.js#3241]
Playground:
https://www.babylonjs-playground.com/#3WN9C6#4

I asked related questions here:
http://www.html5gamedevs.com/topic/32203-custommaterial-updating-custom-uniforms-custom-alpha-and-precision/

Is it considered a bug or not supported? Is there any plan for it?
Is there any way I can work around it, if I really need to update uniforms values for my shader?

Thank you very much!

**Comment by sebavan** [comment]
moving the issue to the extension repo as custom material is an extension: https://github.com/BabylonJS/Extensions/issues/122
