### ISSUE TITLE
API inconsistency for `normalize`

### ISSUE THREAD

**Issue by Breush** [BabylonJS/Babylon.js#3259]
## The problem

The fact is `normalize()` does the operation in-place, while `subtract()` and such have a second interface (`subtractInPlace`).

Once you know that, it is easy to do `clone().normalize()` whenever needed, but you have to remember this special behaviour and this breaks the learning curve hardly.

## First proposal

Changes:
- `normalize`: make this creating a new Vector instance ;
- `normalizeInPlace`: have the same behavior than old `normalize`.

**Problem with this proposal** : this clearly breaks compatibility with existing applications.

## Second proposal

Changes:
- `normalize`: keep as existing but deprecate it (logging some warning) ;
- `unitVector`: new instance of normed vector ;
- `unitVectorInPlace`: normed vector in place.

**Comment by sebavan** [comment]
As back compat is one of our huge promise, I vote for the second one :-) Can you create a PR ?

**Comment by Breush** [comment]
For sure then, I will.

**Comment by sebavan** [comment]
@Breush As I am trying to close the issue for the next release I introduced in my previous commit: 
normalizeToNew
and 
normalizeToRef

It is easier to spot in Typescript Intellisense and I hope the ToNew help catching the other is in place. LEt see what we could do in a major release.
