### ISSUE TITLE
.d.ts issues in Kotlin

### ISSUE THREAD

**Issue by unicomp21** [BabylonJS/Babylon.js#3260]
There are a couple quick cleanups we need for Kotlin support in the next release:

Paste this:
var ts2kt = require("babylonjs")

in here:
https://npm.runkit.com/ts2kt

to get:
ReferenceError: window is not defined

**Comment by unicomp21** [comment]
https://github.com/Kotlin/ts2kt/issues/57

**Comment by RaananW** [comment]
the d.ts is being auto-generated, so we won't be able to actively clean it up. And sadly, as we do work with the window object - mainly in the engine class, it will stay in the global d.ts .
I don't know Kotlin and won't be able to directly help with that, but I will be happy to check together what can be done to achieve this.

Knowing those kind of issues (and having dealt with node and babylon.max.js) I can tell you this will compile (here - https://npm.runkit.com/ts2kt) :

```javascript
global.window = {location: {href: ""}};
global.navigator = {};
var babylon = require("babylonjs")
``` 
But I am not sure this will help you with the conversion process.

**Comment by sebavanmicrosoft** [comment]
@unicomp21 is @RaananW solution working for you ?

**Comment by RaananW** [comment]
We are waiting for an answer, I am closing the issue for now.

**Comment by unicomp21** [comment]
I'm good, thanks guys.
