### ISSUE TITLE
Can I use this Babylon.js for 3d model transform.

### ISSUE THREAD

**Issue by aathirag** [BabylonJS/Babylon.js#3261]
I have a project where I need to convert autocad file .step, .obj, .stp etc to .stl file. I have tried the following ways

1. http://www.3dtransform.com/ - In this while adding a file and sending via mail is working. But when I try to implement the give php api code its returning null value. I tried with postman also then its responding with a link via post man its working. But curl using php is not working

2. https://cloud.materialise.com/ - I tried this with node.js . This i have tried in local i got an error .
   Cannot find module './ApiHttpRequest'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
   is it because I am using local 

3. https://docs.cad.ai/#cadai-api-documentation - I tried this also after 5 attempt. Its showing error key is invalid.

So I want to know in which way I can implement 3d convertion. Can I use babaylon.js?

**Comment by RaananW** [comment]
Hi,

BabylonJS doesn't support .step or .stp. We do have loaders for .obj, .stl, .gltf and .babylon (our own JSON-based format), and exporters from 3DS and blender.
We also have a mesh-serializer to the .babylon and the .obj formats.

I am not sure if Babylon can really help here with the conversion. You could write your own loaders, if you know the file specifications.
