### ISSUE TITLE
Request for gl.FLOAT support in RawTexture

### ISSUE THREAD

**Issue by matthewtebbs** [BabylonJS/Babylon.js#3271]
Pardon my ignorance in this feature request. There may be a supported way already that I've yet to find.

I'm using RawTextures to pass non-image data to my shader that can be indexed in shader code using non-constants, i.e. via samplers. They work great for the `UInt8Array` / `gl.UNSIGNED_BYTE` combination BUT I'd love to pass a large array of floats to the sampler without having to pack/unpack to/from a vec4.

Because my target is WebGL1 my options are limited. Relying on support for the 'OES_texture_float' extension seems like a reasonable option on desktop. It's supported by IE 11.

The engine function `updateRawTexture` does not support `Float32Array` / `gl.FLOAT`. It'd be awesome if it did :). `RawTextures` don't seem to persist a notion of texture type and assume `gl.UNSIGNED_BYTE` for non-compressed texture formats. They could potentially infer texture type from the ArrayBufferView data argument and everything would be awesome.

**Comment by sebavan** [comment]
This will be available in a couple of hours on the main dist.

**Comment by sebavan** [comment]
You can see it in action here: https://www.babylonjs-playground.com/#E0WY4U#22
