### ISSUE TITLE
TargetCamera (and children classes) upVector ignores set value

### ISSUE THREAD

**Issue by JulienNoble** [BabylonJS/Babylon.js#3276]
Hello,

I've been trying to use the `upVector` property to change the z rotation of a `TargetCamera`, but I've realized the property seems to ignore the value. Same for `rotation.z` and `rotationQuaternion`.

**Basis**
I have been using this source to understand the use of `upVector`, they answer what I need : http://www.html5gamedevs.com/topic/11380-rotate-camera-around-z-axis/

**Environment**
I'm using the npm version, rebuilt and packaged with browserify and babelify, but it is reproducible on the playground and in the classic js minified version.

- babylonjs version : 3.1.0beta6
- tested on these browsers :
  - Chrome desktop 62.0.3202.94
  - Edge 40.15063.674.0
  - Firefox desktop 57.0
  - Safari desktop 10.1.2
  - Safari mobile (ipad and iphone) on ios 10.3 and 11.1
  - Chrome mobile (android) 62.0.3202.84

**What was expected**
Unless I'm mistaken, the idea was to tilt the camera on Z using the up vector. Makes sense mathematically, seems to make sense in the linked thread.

For a rough example of what I'm trying to achieve, here's a sample of F-Zero GX keeping the camera up vector relative to the ship rather than the world : https://youtu.be/dQ8vMW4QOOc?t=21m21s

**What happened**
The prop is ignored, even with `noRotationConstraint` on true. Most evident is on the actual playground linked in the thread : http://www.babylonjs-playground.com/#2FNBTG#1 . Nothing happens, the camera stays at its default up tilt. As noted too, `rotation.z` and `rotationQuaternion` seem to be ignored too.

**Notes**
I've checked in typescript code and noticed several things in `babylon.targetCamera.ts`  inside `setTarget(target: Vector3)` :

- line 151 : `Matrix.LookAtLHToRef` takes the `this._defaultUpVector` instead of `this.upVector`
- line 164 : `this.rotation.z = 0;` I might be missing something, but... why?
- lines 178-180 : if the `rotationQuaternion` is set, it is replaced by the components in `rotation`, meaning the value you set is just dumped

I'd like to note I'm probably missing a lot of stuff by just analyzing this method, but it did feel weird in this context. However if this actually is impacting the issue, I can do a PR. Haven't had time to try and build a custom version yet though.

**Comment by sebavan** [comment]
thx for the detailed explanation. i ll have a look today.

**Comment by sebavan** [comment]
On target camera the upVector is currently set by the camera itself to point at the target as you notice you can rely instead on the camera.rotation.z: https://www.babylonjs-playground.com/#2FNBTG#25

Or simulate your tilt from an up vector: https://www.babylonjs-playground.com/#2FNBTG#26

We ll address the rest of the issue next week.
