### ISSUE TITLE
Ability to outline groups of objects

### ISSUE THREAD

**Issue by PixelsCommander** [BabylonJS/Babylon.js#3277]
Ability to outline/stroke on groups of objects. Like HighlightLayer but not blurred. API wise it is possible to deliver as additional parameter to HighlightLayer `threshold` which will `smoothstep` alpha on blur texture. I will introduce a PR on this next week.

**Comment by sebavan** [comment]
cool thx :-)

**Comment by 3dos** [comment]
Hi there, I tried it with no success. Even the playground https://playground.babylonjs.com/#K7UNC7 shows the blurry outline (tried it on chrome and firefox on OSX).

**Comment by PixelsCommander** [comment]
Option property was changed to isStroke: true, instead of threshold: .025

2018-04-30 16:28 GMT+02:00 Filipe Dos Santos Mendes <
notifications@github.com>:

**Comment by 3dos** [comment]
Oh great thank you. Works better now :D
