### ISSUE TITLE
RawTexture with BABYLON.Engine.TEXTURETYPE_FLOAT does not pass this type to Update().

### ISSUE THREAD

**Issue by matthewtebbs** [BabylonJS/Babylon.js#3283]
Code change was in response to 'Request for gl.FLOAT support in RawTexture #3271'.
I cannot re-open the closed issue, hence this 2nd issue submission.

In short, a RawTexture can be created with a _FLOAT texture type but not then subsequently updated with a modified buffer.

**Comment by sebavan** [comment]
The type is available as well in the update method

Maybe I could default to the previous one instead of INT ?

**Comment by matthewtebbs** [comment]
A possible fix would be to reference the InternalTexture for the types.
e.g. changing `RawTexture.update()` to,

```typescript
        public update(data: ArrayBufferView): void {
            this._engine.updateRawTexture(this._texture, data, this.format, this.invertY, null, this.type);
        }
```

**Comment by matthewtebbs** [comment]
Edited /\.

**Comment by sebavan** [comment]
I ll do no worry :-)

**Comment by sebavan** [comment]
Thanks for reporting

**Comment by matthewtebbs** [comment]
It's weird. You can use this._invertY or this._texture.invertY. So I'm not sure which would be best.

**Comment by sebavan** [comment]
They should be eaqual as one wraps the other one and pulling one out now would break back compat :-(

**Comment by matthewtebbs** [comment]
Personally I'd go with this._texture.<blah> for invertY and type.

**Comment by sebavan** [comment]
Done Thx
