### ISSUE TITLE
GUI InputText width

### ISSUE THREAD

**Issue by abow** [BabylonJS/Babylon.js#3286]
Setting the width of an input text doesn't work when autoStretchWidth is set to true.  This will probably be confusing to new users since autoStretchWidth is set to true by default.

I'm thinking that autoStretchWidth should be false by default or maybe width should act as minimum width when autoStretchWidth is set to true.

**Comment by deltakosh** [comment]
I will keep it at true because of compat but I can automatically turn it off if you set the width manually
What do you think?

**Comment by abow** [comment]
That sounds like a good solution.
