### ISSUE TITLE
[Awkwardness] setParent throws an error when used with a camera, parent do not

### ISSUE THREAD

**Issue by noalak** [BabylonJS/Babylon.js#3295]
From a total noob perspective the following is awkward (not intuitive):
BABYLON.Mesh.setParent function throws an error when parameter is a BABYLON.Camera
Error is "t.computeWorldMatrix is not a function"
Setting 'parent' attribute directly is still legal though
[Playground](http://www.babylonjs-playground.com/#WEZYAQ)

**Comment by abow** [comment]
It really isn't legal because camera in not a TransformNode.  I do agree that this should be possible, though.

**Comment by abow** [comment]
Oh, I misunderstood you.  Yes, setting the parent attribute directly is possible.
