### ISSUE TITLE
Transitioning between separate scenes while keeping VR active is currently not possible

### ISSUE THREAD

**Issue by AlienDeathRay** [BabylonJS/Babylon.js#3308]
To avoid complexity of managing separate sets of content within a single scene, It would be great to be able to maintain separate scenes and be able to switch from one to another while keeping the original VR rig active. Perhaps a 'moveScene' function on the VRExperienceHelper would be a good addition with the ability to set a new camera position within the target scene.

**Comment by sebavan** [comment]
Allow transfer of other type of objects would be amazing as well.

**Comment by deltakosh** [comment]
Renamed it to better align with the feature which will be released

**Comment by TrevorDev** [comment]
- [x] Fix add/remove lighting issues
- [x] LoadAssetContainer method
- [ ] Update docs
