### ISSUE TITLE
Materials working differently in firefox vs chrome

### ISSUE THREAD

**Issue by TrevorDev** [BabylonJS/Babylon.js#3316]
1. Open http://www.babylonjs-playground.com/#RA9C0A in firefox, edge and in chrome
2. Observe that the ground's material is somehow being set to the same material as the sphere in firefox but not in other browsers
3. Expected only the sphere's material to be modified

**Comment by ericboyd** [comment]
![giphy-2](https://user-images.githubusercontent.com/5985363/33648976-121619cc-da97-11e7-83e6-4eae1712fb0f.gif)

**Comment by deltakosh** [comment]
Works for me in firefox
Wre you using ff 55? (If so they have plenty of bugs to fix yet)

**Comment by Kesshi** [comment]
The problem is not Firefox, its Chrome.
With Chrome 63 the ground material is wrong. I didn't have this problem with chrome 62.
![screen](https://user-images.githubusercontent.com/15049407/33707583-23a70362-db38-11e7-8e24-829bdd18fb47.jpg)

**Comment by deltakosh** [comment]
Ok I can repro..let me check who is the culprit ;)

**Comment by deltakosh** [comment]
Bug created in chromium db:
https://twitter.com/deltakosh/status/938813751096049664

**Comment by Vorion86** [comment]
The bug also exists in Firefox, but only using v58 beta or 59 nightly. Linux versions of firefox and chrome seem to run fine, at least for me, so it's possible that only Windows versions have this bug.

**Comment by deltakosh** [comment]
Yes I can repro on nightly only for ff
Reallllly weird

**Comment by Vorion86** [comment]
This was also reported on babylonjs forum about a month ago by sable, maybe it helps tracking down the culprit:
http://www.html5gamedevs.com/topic/33865-diffuse-colour-with-chrome-canary-ff-dev-edition-angle/
