### ISSUE TITLE
Custom VR button ends up being hijacked

### ISSUE THREAD

**Issue by haroldma** [BabylonJS/Babylon.js#3320]
Use a custom VR button. The button's style gets overridden. The problem being inside [`updateButtonVisibility`](https://github.com/BabylonJS/Babylon.js/blob/ef628ae59a16203a1d50a183c822a2a1e040279a/src/Cameras/VR/babylon.vrExperienceHelper.ts#L394-L406). No logic for custom button.

**Comment by TrevorDev** [comment]
https://github.com/BabylonJS/Babylon.js/pull/3325

Validated it working with http://playground.babylonjs.com/#4EJ173#3 after changes above have been made

**Comment by deltakosh** [comment]
should be good now

**Comment by haroldma** [comment]
Thanks, guys!
