### ISSUE TITLE
Exiting VR does not switch to the previous active camera

### ISSUE THREAD

**Issue by Exolun** [BabylonJS/Babylon.js#3328]
Playground for repro:
[http://playground.babylonjs.com/#WSMD93](http://playground.babylonjs.com/#WSMD93)

Steps to reproduce:
- Move the camera a bit (note you're using an ArcRotateCamera)
- Switch to VR using the goggles button
- Exit VR

Observe that you're no longer using the camera you were before.

**Comment by TrevorDev** [comment]
By default the vrHelper creates it's own non-vr camera. Recently the feature to use a custom camera has been added. See http://doc.babylonjs.com/how_to/webvr_helper.

Create your own camera before creating the vr helper and then set the new camera creation to false.
```
scene.createDefaultVRExperience({createDeviceOrientationCamera: false}
```

See this playground and let me know if you still have an issue.
http://playground.babylonjs.com/#WSMD93#1

For even more custom logic you can listen to the VRHelper.onExitingVR event and manually switch cameras.
