### ISSUE TITLE
Entering VR ordering issue

### ISSUE THREAD

**Issue by haroldma** [BabylonJS/Babylon.js#3329]
**Context**: We're hooking up to `onEnteringVR` to change the active camera to one used for FPV.
**Issue**: Before this event is called by Babylon it captures the position of the active camera.
**POI**: [Code](https://github.com/BabylonJS/Babylon.js/blob/ef628ae59a16203a1d50a183c822a2a1e040279a/src/Cameras/VR/babylon.vrExperienceHelper.ts#L413-L415).
**Suggested solution**: Move the lines above after `onEnteringVR`. This let us override the position before entering VR.

**Comment by deltakosh** [comment]
Good for me. I will add this in next commit
