### ISSUE TITLE
Don't remove observer from within observer callback

### ISSUE THREAD

**Issue by leweaver** [BabylonJS/Babylon.js#3337]
https://github.com/BabylonJS/Babylon.js/blob/030600725f8b960e33c04526e2739322fab03885/src/babylon.node.ts#L122

Shouldn't modify the observable list while it is being iterated over (ends up skipping entries). 

What is the best way to handle this; add a flag to the observable event arg, that can flag that the listener wishes to be removed? Or, make a copy of the observer array (in observable.ts:190) prior to iteration?

**Comment by deltakosh** [comment]
I will add a setTimeout(0) to the removeBehavior call
