### ISSUE TITLE
Playground search by title or tag is broken?

### ISSUE THREAD

**Issue by bghgary** [BabylonJS/Babylon.js#3342]
https://doc.babylonjs.com/playground?q=gltf (0 results)
https://doc.babylonjs.com/playground?tag=gltf (0 results)

where as https://doc.babylonjs.com/playground?code=gltf (53 results) including some tagged with glTF and have titles that contain glTF.

**Comment by bghgary** [comment]
The results show up now, but the count of results still say 0.

**Comment by deltakosh** [comment]
On it!

**Comment by Jaskar** [comment]
PR for the count.
