### ISSUE TITLE
mikkt space and glTF

### ISSUE THREAD

**Issue by unicomp21** [BabylonJS/Babylon.js#3345]
This is a placeholder for tracking whether or not mikkt space support in babylonjs makes sense.

See thread:
http://www.html5gamedevs.com/topic/34364-gltf-support-and-mikkt-space/

**Comment by unicomp21** [comment]
Reference material:

https://github.com/gltf-rs/mikktspace/tree/master/libmikktspace

Not sure if it make sense to rewrite in typescript, or use emscripten to compile the above for babylon.

https://github.com/kripken/emscripten

**Comment by unicomp21** [comment]
Great description of the situation:

https://wiki.blender.org/index.php/Dev:Shading/Tangent_Space_Normal_Maps

**Comment by deltakosh** [comment]
Closing as we do not plan to work on it. Please reopen if this needs to be reevaluated

**Comment by donmccurdy** [comment]
FYI: https://github.com/KhronosGroup/glTF/issues/1252#issuecomment-771358688

**Comment by bghgary** [comment]
There is now a WebAssembly module for MikkTSpace: [donmccurdy/mikktspace-wasm: MikkTSpace vertex tangent calculation for JavaScript/TypeScript/Node.js, using Web Assembly. (github.com)](https://github.com/donmccurdy/mikktspace-wasm). It would be good to integrate.

**Comment by unicomp21** [comment]
@bghgary do babylonjs shaders make use of the MikkTSpace tangents mentioned above?

**Comment by bghgary** [comment]
If tangents are provided, yes. If not, we use a runtime compatible algorithm.
https://github.com/BabylonJS/Babylon.js/blob/61c912b555c549794d976204975a051c038429d6/packages/dev/core/src/Shaders/ShadersInclude/bumpFragmentMainFunctions.fx#L84-L107
