### ISSUE TITLE
Node._cache is nulled by TransformNode

### ISSUE THREAD

**Issue by SvenFrankson** [BabylonJS/Babylon.js#3346]
Hi,

A TransformNode instance will null its _cache property when disposed (see TransformNode.dispose)

As a consequence, calling some method (like computeWorldMatrix) on a disposed TransformNode will cause a Javascript error

While it can be considered to be by design, please note it was possible to call computeWorldMatrix on a disposed mesh in last stable version (see playground below).

http://playground.babylonjs.com/indexstable#SY6SYY

**Comment by deltakosh** [comment]
It is by design and for memory reason. Disposing an object means you don't want it anymore and thus there is no guarantee about the availability f the object.
