### ISSUE TITLE
Vive not working with VR helper

### ISSUE THREAD

**Issue by TrevorDev** [BabylonJS/Babylon.js#3352]
Suspected helper bugs:
- [x] Cannot see ray from controller
- [x] Not handling if webvrController.hand == ""
- [x] Teleporting backwards is crooked at certain rotations
- [x] Teleporting backwards sets y position too high
- [x] Pad values on vive are backwards compared to windows mixed reality controller 
- [x] Not using standing matrix for height
- [x] Teleporting does not work (This works in older version in firefox.)
- [x] Facing backwards at start (this also works as expected in older version of firefox)
- [x] Dispose vr helper when scene is disposed

Suspected bug in browser:
- [ ] Some standard materials change color when gaze cursor is selecting something.[Originally thought to be a lighting issue] (This does not occur in older firefox, this might be the webgl2 issue but this still happens in firefox)

**Comment by deltakosh** [comment]
Woot
@ranaanw please test on oculus ASAP:)

**Comment by RaananW** [comment]
will do

**Comment by deltakosh** [comment]
Ok only lighting remains
