### ISSUE TITLE
Click issue

### ISSUE THREAD

**Issue by TrevorDev** [BabylonJS/Babylon.js#3353]
From David R:
On this sample : http://playground.babylonjs.com/#U0A5TN#32
 
You'll find the small game I'm working on. Using the Windows MR controller, click start using the laser and trigger. The game starts. Press the menu button in game, the game pauses. Press the continue button, the game continues. So far so good.
 
But if you now press again the menu button to pause the game, you'll need to click twice on the continue button to make it works. The first time you'll see the button going back to its normal un pressed state.
 
I didn't have the time to build a repro without WebVR  so don't know if it's VR specific or not.

**Comment by deltakosh** [comment]
Should be good now
