### ISSUE TITLE
[viewer] - Allow for any model to be exploded

### ISSUE THREAD

**Issue by eamon-obrien** [BabylonJS/Babylon.js#3363]
It would be very nice to have a button / slider on the viewer that allows you to explode any model that you are viewing. This would be incredibly useful when trying to understand the architecture of any model as opposed to having to create an explosion animation for any model and then exporting for the viewer. 

![image](https://user-images.githubusercontent.com/3632104/33847135-6dec183a-de5e-11e7-9d30-524c52c0355a.png)
![image](https://user-images.githubusercontent.com/3632104/33847167-875b4c82-de5e-11e7-8660-adc98b06d42f.png)

**Comment by deltakosh** [comment]
Great idea. This will require a new function on mesh as well but this should be straightforward

**Comment by RaananW** [comment]
I think we could calculate the center of the mesh and calculate rays from it to the rest of the meshes. Then move them on this ray. Wouldn't that work without adding additional info?

**Comment by deltakosh** [comment]
This feature is not a priority for now

**Comment by eamon-obrien** [comment]
Hi David,

Are there no plans to enable this? This is a feature that AutoCad's online
viewer has enabled

**Comment by deltakosh** [comment]
Sorry I thought you did not need it anymore

**Comment by danjpar** [comment]
I have some ideas for this

**Comment by deltakosh** [comment]
Wonderful!

**Comment by danjpar** [comment]
https://brave-gates-959b79.netlify.com/

Just my initial thought about breaking a mesh down into multiple meshes. I suppose it should be indiscriminate whether the model is made up of a bunch of meshes, or a single mesh with multiple submeshes. What do you think?

**Comment by deltakosh** [comment]
pinging @eamon-obrien

**Comment by danjpar** [comment]
New example on that link. I'm sure it can be refined and improved.
code is here:
https://github.com/danjpar/babylonjsTesting

**Comment by danjpar** [comment]
[PR](https://github.com/BabylonJS/Babylon.js/pull/5875)

**Comment by deltakosh** [comment]
Done! Thanks a lot @danjpar !!!
