### ISSUE TITLE
Default behavior of ArcRotateCamera's right button changes from rotating to panning

### ISSUE THREAD

**Issue by zhutq** [BabylonJS/Babylon.js#3385]
Playground:
http://www.babylonjs-playground.com/#12WBC#137

It was rotating in 3.1.0 alpha.

Is it a bug or a feature?
If it is a feature by design, can I config it back to do rotating?
The link for behavior's document http://doc.babylonjs.com/features/Behaviours (cited here https://github.com/BabylonJS/Babylon.js/releases) returns "Page Not found".

Thank you very much!

**Comment by zhutq** [comment]
Oh I see I can achieve what I want by assigning another button for panning:
`camera.attachControl(canvas, false, true, 1);`
RMB: rotation; Ctrl+RMB: panning
http://www.babylonjs-playground.com/#12WBC#138

**Comment by deltakosh** [comment]
Correct:)
