### ISSUE TITLE
Unable to open models in sandbox

### ISSUE THREAD

**Issue by donmccurdy** [BabylonJS/Babylon.js#3386]
When testing glTF models in http://sandbox.babylonjs.com/, I've been having some issues lately:

1. I usually try clicking what I thought was an upload icon. I only just now saw the tooltip and realized it only supports .babylon files. Allowing that to be used for any file type would be ideal, and might improve things for browsers with weaker drag-and-drop support e.g. Safari. The message `Press this button to open your assets' files` contributes to this misunderstanding. 😄 
2. Currently dragging in a zip is not working either. I get the following message using BoxAnimated.gltf from the sample models repo:

```
Failed to load file:///BoxAnimated0.bin: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.
```

The verbatim URI is `BoxAnimated0.bin`.

Thanks!

**Comment by deltakosh** [comment]
Sorry about 1. THe tooltip is misleading. You can definitely open gltf as well. I'll fix the tooltip
for 2. I cannot reproduce (You cannot drag'n'drop zip files but if you drag'n'drop all gltf + textures files it should work)

**Comment by donmccurdy** [comment]
I see, thanks! Looks like dragging individual files works, but a folder (similar to ZIP) does not. JavaScript's drag-and-drop APIs are quite an adventure. 😕 

FWIW [this is the code](https://github.com/donmccurdy/three-gltf-viewer/blob/master/src/drop-controller.js) used for drag-and-drop on https://gltf-viewer.donmccurdy.com/. A few open issues but does handle folders and ZIPs if that's helpful.

**Comment by deltakosh** [comment]
Folder is supported but the gltf file itself has to be at root level (so gltf and folder with textures side by side)
