### ISSUE TITLE
Perf degredation with VRHelper.enableTeleportation

### ISSUE THREAD

**Issue by leweaver** [BabylonJS/Babylon.js#3391]
In the [Hill Valley](http://playground.babylonjs.com/#JA1ND3#18) demo scene, I am seing significant performance drops when the `VRHelper.enableTeleportation({floorMeshName: "Road1"});` line is included.

I ran some performance traces using xperf, which showed that the time spent in the RAF callback was divided as follows. The last 3 lines (emboldened) look like they are caused by raycasts, and are taking up 44% of the RAF callback time:

- 16.03ms: render
  - 8.9ms: _processSubCameras
    - 7.03ms: render
      - 3.03ms: bindForSubMesh
      - 2.05ms: _bind
      - 0.99ms: isReadyForSubMesh
      - 0.94ms: _processRendering
    - 1.95ms: evaluateMeshes
  - 7.04ms: **notifyObservers**
    - 4.01ms **intersects**
    - 3.03ms **intersectsTriangle**

Not sure if this is an issue with the raycasting engine itself, or the way that the scene is set up.

**Comment by deltakosh** [comment]
This is not a bug per se. By default the teleportation checks all objects. I will improve that to only pick collisions meshes only
