### ISSUE TITLE
ArcRotateCamera around axes other than world X and Y

### ISSUE THREAD

**Issue by zhutq** [BabylonJS/Babylon.js#3392]
Hi,
ArcRotateCamera is a really greate camera.
I'm wondering if it can be made around some other axes instead of world X and Y. Because I mainly work in a Z-up coordinate system, and sometimes, I need to align the viewport to an arbitrary rectangle in 3D and do some panning.

Using a parent for the camera can make rotation work but seems not panning:
http://www.babylonjs-playground.com/#12WBC#139

What I did was hacking the `rebuildAnglesAndRadius` and `_getViewMatrix` methods code, changing the computation of alpha, beta and target. This works for me but is too hacky.

What's your suggestion?
It's appreciated if there's a convenient way.

Thank you very much!

**Comment by deltakosh** [comment]
Hello can you sue the forum for question related topic?
(Also did you try to change the up vector of the camera?)
