### ISSUE TITLE
Upgrade to Chrome 63.0.3239.84 (64 bits) - Material flickering

### ISSUE THREAD

**Issue by innerground** [BabylonJS/Babylon.js#3393]
Dear All,
I just upgraded to Chrome 63.0.3239.84 (64 bits) and the GLTF rendering blinks with material_commons extension.
The previous version was just working fine.
Any idea?

**Comment by RaananW** [comment]
Hi, this is a known bug in chrome and WebGL 2. The 3.1.1 release has this issue resolved. Are you using the latest version?

**Comment by innerground** [comment]
No, I will update It now and keep you informed.

**Comment by innerground** [comment]
I upgraded and now It works fine.Thanks.
