### ISSUE TITLE
Can't download WMR controller models

### ISSUE THREAD

**Issue by edzis** [BabylonJS/Babylon.js#3401]
Getting a 404 error on https://controllers.babylonjs.com/microsoft/left.glb and https://controllers.babylonjs.com/microsoft/right.glb

Others models ar loading fine.

**Comment by RaananW** [comment]
Are you trying to load them manually? the links are:
https://controllers.babylonjs.com/microsoft/default/left.glb and https://controllers.babylonjs.com/microsoft/default/right.glb

Or are device specific. It is being managed by this class: https://github.com/BabylonJS/Babylon.js/blob/master/src/Gamepad/Controllers/babylon.windowsMotionController.ts#L209

**Comment by edzis** [comment]
@RaananW Thanks for clarification. Even though I have pasted here the wrong url the issue still remains.
The failing url I see in my console when using WMR headset is https://controllers.babylonjs.com/microsoft/045e-065e/left.glb

**Comment by RaananW** [comment]
As I stated in the issue you created (https://github.com/BabylonJS/Babylon.js/issues/3402), this seems like we don't have this device ID as an asset. We should fall back to the default.

**Comment by edzis** [comment]
@RaananW I had another typo when reading the url from console - I see that it (045E-065B) is served fine.
Now trying to figure out why it is failing to load in my experience.

**Comment by edzis** [comment]
@RaananW It turned out that I had to include the GLTF loader for these models to load. Could you include a mention of that on https://doc.babylonjs.com/how_to/webvr_helper?

**Comment by deltakosh** [comment]
Agree on that. We should also generate a warning at runtime

**Comment by RaananW** [comment]
There is now a warning, and a fallback redirect to default is new controller versions are added (just in case it wasn't a typo :smile:). I am closing this one, will continue tracking on 3402
