### ISSUE TITLE
Improve access to VR controller models

### ISSUE THREAD

**Issue by edzis** [BabylonJS/Babylon.js#3402]
Please add an alternative path for obtaining controller models that does not depend on network access or a centralized server.

This will help for various scenarios:
- offline mode with bundled output
- when another issue like #3401 hits https://controllers.babylonjs.com
- to use custom controller models

I imagine that it involves the following steps:
- [x] include the models in code base for (I could not find them)
- [x] allow to override `MODEL_BASE_URL`
- [x] add documentation

**Comment by RaananW** [comment]
Assets are here - https://github.com/BabylonJS/Babylon.js/tree/master/assets/meshes/controllers/microsoft .  It is true that we should state which devices are supported an fall back to default if we don't have the models.

**Comment by RaananW** [comment]
Documentation updated - https://github.com/BabylonJS/Documentation/pull/723/files , since it is merged I am closing the issue.
