### ISSUE TITLE
Import mesh fails

### ISSUE THREAD

**Issue by haroldma** [BabylonJS/Babylon.js#3407]
Unable to import meshes from https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Models/master/2.0/BoomBox/glTF/BoomBox.gltf: importMesh of unknown TypeError: Cannot read property '0' of undefined

**Comment by deltakosh** [comment]
Hello can you open this file in the sandbox?
Did you make sure to reference gltf loader?

**Comment by haroldma** [comment]
Agh, forgot the gLTF loader! Closing.
