### ISSUE TITLE
Add animation group concept

### ISSUE THREAD

**Issue by bghgary** [BabylonJS/Babylon.js#3411]
See this issue for context: https://github.com/KhronosGroup/glTF/issues/1179#issuecomment-351546794

glTF (and engines like Unity3D) support the concept of grouping animation curves together into a single named animation object where each curve in the group can target different properties on different objects.

Also in related issue https://github.com/BabylonJS/Babylon.js/issues/3076, we want to expose UI to allow a user to select between glTF animations (which are these groups).

To support this, it would be ideal to introduce an animation group to Babylon that enables the user to add multiple `BABYLON.Animation` objects to it and expose the following functionality:
* Play this group
* Stop this group
* Options for looping, etc. and clamping the curve on both ends if the curve does not include key frames for the entire time frame of the group.

For reference:
* glTF animations = Unity3D animations = ***Babylon animation groups***
* glTF animation channels = Unity3D animation clips = `BABYLON.Animation`

**Comment by deltakosh** [comment]
I will add a new object named AnimationGroup. It will be referenced by name at scene level and will provide the following API:
- animations: BABYLON.Animation[]
- name
- start
- stop
- play/pause
- normalize(lastKeyTime: number): it will align all animations on the same timeline by duplicating last animation key and creating a new one at lastKeyTime

**Comment by bghgary** [comment]
> normalize(lastKeyTime: number): it will align all animations on the same timeline by duplicating last animation key and creating a new one at lastKeyTime

Also need one at the beginning if necessary.

**Comment by deltakosh** [comment]
ok so perhaps something like: normalize(beginTime: number, endTime: number)

**Comment by deltakosh** [comment]
Done!
