### ISSUE TITLE
Exiting VR does not switch to the previous active camera

### ISSUE THREAD

**Issue by Exolun** [BabylonJS/Babylon.js#3412]
Logging a new bug because I can't reopen [this bug](https://github.com/BabylonJS/Babylon.js/issues/3328)...

I'm still seeing issues with camera switching upon exiting VR.  When exiting VR, I expect to Babylon to switch back to the camera I was using before I entered VR, but it switches to the camera that was active when I first created the VR helper.

Playground for repro:
[http://playground.babylonjs.com/#WSMD93#2](http://playground.babylonjs.com/#WSMD93#2)

Steps to reproduce:
- Move the camera a bit (note you're using an ArcRotateCamera)
- Switch to VR using the goggles button
- Exit VR

Observe that you're no longer using the camera you were before. (it switches to the ArcRotateCamera)

**Comment by deltakosh** [comment]
Ping @raananw to have a look
