### ISSUE TITLE
Orientation of a texture w.r.t. a sphere

### ISSUE THREAD

**Issue by jkidd08** [BabylonJS/Babylon.js#3417]
I am attempting to apply a texture of a diffuse image of the Earth to a sphere and have the scene render with the Earth's north pole aligned with the body/local +Z axis. However, I can't seem to implement this. Below is a playground scenario I put together for the scene.

I've attempted to achieve this with the following lines (26 - 33 of the playground scene). 
```
    earthSurface.diffuseTexture.uAng = 0;
    earthSurface.diffuseTexture.vAng = 0;
    earthSurface.diffuseTexture.wAng = 0;
    earthSurface.diffuseTexture.uScale = 1.0;
    earthSurface.diffuseTexture.vScale = 1.0;
    earthSurface.diffuseTexture.wScale = 1.0;
```

http://www.babylonjs-playground.com/#634KR1

**Comment by deltakosh** [comment]
Hello would you mind to use our forum? We try to keep github issues for bug and features tracking
