### ISSUE TITLE
Improve Shadows

### ISSUE THREAD

**Issue by sebavan** [BabylonJS/Babylon.js#3440]
- [x] Introduce Depth Texture only on RTT
- [x] Introduce support for sampler2dshadow and proj in Webgl2
- [x] Rely on them in PCF and Simple Shadow (fallback stays as current implementation)
- [x] Limit PCF Kernel size in fromt of the actual texel size
- [x] Introduce Normal Offset Bias
~~Add automatic setup for near plane~~
~~Add automatic setup for far plane~~
- [ ] Add Samples
- [ ] Add Tests
- [ ] Add Doc

**Comment by TrevorDev** [comment]
Please take into account multicamera depth texture.

**Comment by sebavan** [comment]
Done
