### ISSUE TITLE
Use Threejs and Babylonjs together on one canvas??

### ISSUE THREAD

**Issue by bitores** [BabylonJS/Babylon.js#3447]
Is it possible to use both A and B on a single canvas?

**Comment by deltakosh** [comment]
Yes and no. Technically yes because Babylon.js can be created on an already creative gl context.
And no because Babylon.js has a lot of cache and using the context outside of Babylon.js while break all of them

**Comment by bitores** [comment]
@deltakosh thank you for your answer, I am also trying to restore the cache, but failed...so...Can I expect to work with other webgl engines in the near future?

**Comment by deltakosh** [comment]
It should right now if you call engine.wipeCaches(true) before rendering with bjs

**Comment by bitores** [comment]
@deltakosh  i have an example with engine.wipeCaches(true), but still failed...,i dont know why..




var scene, camera, renderer;
	var geometry, material, mesh;

	var sceneB, engine, cameraB;
	var box;

	var canvas;
	init();
	animate();

	function init() {

		canvas = document.getElementById("renderCanvas");

		canvas.addEventListener('webglcontextrestored', function(e) {
		  console.log(e); 
		}, false);


		scene = new THREE.Scene();
		
		camera = new THREE.PerspectiveCamera( 75, window.innerWidth / window.innerHeight, 1, 10000 );
		camera.position.z = 1000;

		geometry = new THREE.BoxGeometry( 200, 200, 200 );
		material = new THREE.MeshBasicMaterial( { color: 0xff0000, wireframe: true } );

		mesh = new THREE.Mesh( geometry, material );
		scene.add( mesh );

		renderer = new THREE.WebGLRenderer({canvas:canvas});
		renderer.autoClear = false;
		renderer.setSize( window.innerWidth, window.innerHeight );


		// babylon
		engine = new BABYLON.Engine(canvas, true);
		sceneB = new BABYLON.Scene(engine);
		cameraB = new BABYLON.ArcRotateCamera("camera", 1, 0.8, 10, new BABYLON.Vector3(0, 0, 0), sceneB);
		sceneB.activeCamera.attachControl(canvas);
		sceneB.autoClear = false;
		sceneB.beforeRender = function(){
			engine.wipeCaches(true);
			console.log('wipeCaches');
		}

		var light = new BABYLON.DirectionalLight("light", new BABYLON.Vector3(0, -1, 0), sceneB);
		light.diffuse = new BABYLON.Color3(1, 0, 0);
		light.specular = new BABYLON.Color3(1, 1, 1);


		box = BABYLON.Mesh.CreateBox("box", 3.0, sceneB);
		var material = new BABYLON.StandardMaterial("texture", sceneB);

		box.material = material;
		material.diffuseTexture = new BABYLON.Texture("monster.jpg", sceneB);


	}

	function restore_ThreeJS_WebGL_state()
	{
		var gl = renderer.context;

		gl.enable(gl.DEPTH_TEST);
		gl.depthFunc(gl.LEQUAL);
		gl.enable(gl.CULL_FACE);
		gl.cullFace(gl.BACK);
		gl.clearDepth(1);
		gl.clear(gl.DEPTH_BUFFER_BIT);

		renderer.resetGLState();

	}



	function animate() {

		requestAnimationFrame( animate );

		
 		// 开启threejs 
		restore_ThreeJS_WebGL_state();
		console.log("threejs");
		mesh.rotation.x += 0.01;
		mesh.rotation.y += 0.02;

		renderer.render( scene, camera );



		// babylon 绘制
     	box.rotation.x += 0.005;
		box.rotation.y += 0.01;
		sceneB.render();
	}

**Comment by bitores** [comment]
@deltakosh 
![image](https://user-images.githubusercontent.com/17512181/34344550-d658868c-ea21-11e7-8c3a-aff3388efc61.png)

**Comment by deltakosh** [comment]
can you try this?
```
sceneB.beforeRender = function(){
engine._currentProgram = null;
		engine.wipeCaches(true);
		console.log('wipeCaches');
	}
```

If it works, I'll add it to the wipeCaches API

**Comment by bitores** [comment]
@deltakosh still faild... but  , feeling is about to succeed....

**Comment by deltakosh** [comment]
Can you share the code as zip file? Will make it work;)

**Comment by bitores** [comment]
[example.zip](https://github.com/BabylonJS/Babylon.js/files/1586565/example.zip)

**Comment by bitores** [comment]
@deltakosh [example.zip](https://github.com/BabylonJS/Babylon.js/files/1586566/example.zip)

**Comment by bitores** [comment]
@deltakosh 
this is result what i want
![image](https://user-images.githubusercontent.com/17512181/34347731-9accd13a-ea40-11e7-8967-b3f9481a1c1e.png)

some error threw, when exec the zip code ... i think .. the mesh data is lost or wrong after rendering with threejs ... 
![image1](https://user-images.githubusercontent.com/17512181/34347732-9b458aa8-ea40-11e7-8852-cb42d5b6d02d.png)

**Comment by deltakosh** [comment]
https://www.babylonjs-playground.com/#C72JLZ#3

Ball starts at a position where there is no intersection with the plane:
![image](https://user-images.githubusercontent.com/1306056/34361638-b9a9e144-ea20-11e7-8f0d-759045e94073.png)

So this is correct:
![image](https://user-images.githubusercontent.com/1306056/34361621-922c9a6c-ea20-11e7-9451-70f590f3f6ae.png)

**Comment by deltakosh** [comment]
Ok found it
Just add "gl.bindVertexArray(null);" in your restore_ThreeJS_WebGL_state function

**Comment by deltakosh** [comment]
Also make sure to init bjs like this:
```
engine = new BABYLON.Engine(renderer.context, true);
```

**Comment by bitores** [comment]
@deltakosh  Coo..l, and thanks
