### ISSUE TITLE
Strange behavior intersectsMesh()

### ISSUE THREAD

**Issue by Luummii** [BabylonJS/Babylon.js#3448]
This is your example https://www.babylonjs-playground.com/#C72JLZ#1

Please go to string number  68. Open console and see! At first it will print as expected! but if you replace the parameter as indicated in the comments, you'll see that the first works - "after", and only once.

Just watch when and what parameters are output in the console! When changing from truth to false and vice versa.

The same strange behavior occurs in other balls, if you change this BABYLON.Mesh.CreateBox to this BABYLON.MeshBuilder.CreateBox

**Comment by deltakosh** [comment]
Good catch!
I'll make sure to fix it asap

**Comment by deltakosh** [comment]
![image](https://user-images.githubusercontent.com/1306056/34361276-5f9d9b44-ea1d-11e7-9e53-7b718f59747d.png)

**Comment by Luummii** [comment]
![deepinscreenshot_select-area_20171226202154](https://user-images.githubusercontent.com/21025345/34361359-8f2943d8-ea7a-11e7-81a3-8011244d1a25.png)
It should not be!

**Comment by deltakosh** [comment]
It should :) the ball starts in a position where it is not in collision

**Comment by Luummii** [comment]
Change the position of the ball! And everything will remain the same!

**Comment by deltakosh** [comment]
Not sure to follow you. THe test is about checking if the ball intersects the plane. If you move it to a position where it does not intersect then the message will be written.
Perhaps the text should be changed to "no intersection" instead of "after"

**Comment by Luummii** [comment]
IN your opinion, the animation starts with the fact that the ball collided with the ground? Regardless of where the ball is, the first animation is such!

pos 1: Ball has not yet collided with the ground , but in the picture he has already faced
pos 2: The ball is approaching the earth!
 
![deepinscreenshot_select-area_20171226203403](https://user-images.githubusercontent.com/21025345/34361572-51ae03de-ea7c-11e7-986e-70ebe95f0707.png)

**Comment by deltakosh** [comment]
https://www.babylonjs-playground.com/#C72JLZ#3

Ball starts at a position where there is no intersection with the plane:
![image](https://user-images.githubusercontent.com/1306056/34361638-b9a9e144-ea20-11e7-8f0d-759045e94073.png)

So this is correct:
![image](https://user-images.githubusercontent.com/1306056/34361621-922c9a6c-ea20-11e7-9451-70f590f3f6ae.png)

**Comment by Luummii** [comment]
https://www.babylonjs-playground.com/#C72JLZ#4

Look at this example. Do the ball has already collided with the earth? Of course not! but in the picture the first picture shows that the collision occurred!

**Comment by Luummii** [comment]
Your picture suggests that the ball in the first frame collided with the ground! But really it's not!

**Comment by deltakosh** [comment]
ok I see it now :) will fix it!
Thank you !

**Comment by Luummii** [comment]
change state issues - unable to reproduce

**Comment by deltakosh** [comment]
yes my lord!

**Comment by Luummii** [comment]
)))

**Comment by deltakosh** [comment]
So it is not a bug actually :)
https://www.babylonjs-playground.com/#C72JLZ#5

I fixed it by using registerAfterRender. The point is we need the meshes to update their bounding info which is done automatically during render

Other way to fix it:
https://www.babylonjs-playground.com/#C72JLZ#6

you manually update the matrices

**Comment by Luummii** [comment]
Yes!)) It is elementary)) registerAfterRender and registerBeforeRender! Please, sorry me! Thank you!

**Comment by deltakosh** [comment]
No problem :)
