### ISSUE TITLE
Inspector Error

### ISSUE THREAD

**Issue by sebavan** [BabylonJS/Babylon.js#3449]
Moved form https://github.com/BabylonJS/Spector.js/issues/84

I get an error when I try to run the babylon inspector with

```scene.debugLayer.show();```
And it only happens when I go to the GUI tab.

```
"babylonjs": "3.1.1",
"babylonjs-gui": "^3.1.1",
```

![image](https://user-images.githubusercontent.com/16655165/34361561-0518305a-ea20-11e7-9f88-1876ddb8b390.png)

**Comment by sebavan** [comment]
I reopened the issue in the babylon repo (Spector is different from the Inspector): https://github.com/BabylonJS/Babylon.js/issues/3449

**Comment by RaananW** [comment]
What error do you get? can it be related to the way we deliver the packages (npm)?

**Comment by deltakosh** [comment]
@RaananW are you on it?

**Comment by RaananW** [comment]
I can be, I thought it was an inspector error. Will look into it first thing tomorrow.

**Comment by deltakosh** [comment]
Thanks

**Comment by RaananW** [comment]
I cannot reproduce this. I tested with 3.1.1, with 3.2.0-alpha, GUI tab is working fine, no exception thrown. 
Maybe it is the scene itself. I am keeping it open and will write the original poster in Spector. I can't reference him here for some reason.

**Comment by Ericky14** [comment]
I am sorry for taking so long to reply, but I have been really busy.

The error occurs even if I only have a camera in the scene and nothing else. If I remove the camera, it does not occur.

Here's a picture of the line of code where it occurs.

<img width="1073" alt="screen shot 2018-01-05 at 12 00 26 pm" src="https://user-images.githubusercontent.com/21248862/34619420-1073e5d2-f210-11e7-8c05-2c1fc76b2e68.png">

**Comment by Ericky14** [comment]
Installing `babylonjs-inspector@3.2.0-alpha0` and doing `require('babylonjs-inspector');` inside my `componentDidMount` method worked.

**Comment by deltakosh** [comment]
cool!
