### ISSUE TITLE
Remove DOM interfaces that are declared by TypeScript

### ISSUE THREAD

**Issue by mootari** [BabylonJS/Babylon.js#3454]
Most of the DOM interfaces exported by BJS appear to be already available in [TypeScript](https://github.com/Microsoft/TypeScript/blob/v2.6.2/lib/lib.dom.d.ts). It might be a good idea to remove them from the BJS source.

Related issue: #550

**Comment by mootari** [comment]
Disclaimer: I'm a bloody noob when it comes to TypeScript. There might be other problems with this request that I'm not aware of.

**Comment by deltakosh** [comment]
Can you point some of the interfaces you think about in bjs code?

**Comment by mootari** [comment]
> Can you point some of the interfaces you think about in bjs code?

On it. In general, when creating a pull request, should I recompile and include everything or only add my raw changes?

**Comment by deltakosh** [comment]
Only raw changes:)

**Comment by mootari** [comment]
A lot of the mixins for `WebGLRenderingContext` are actually part of the `WebGL2RenderingContext` interface. I won't touch them for now, but they probably need additional changes.
