### ISSUE TITLE
Allow setting sampling mode on GUI Images

### ISSUE THREAD

**Issue by Queatz** [BabylonJS/Babylon.js#3460]
I am making a game with pixel graphics and some UI Image are scaled up, however I haven't found a way to make them pixelized like the rest of the graphics.

![screenshot from 2017-12-29 20-48-02](https://user-images.githubusercontent.com/540620/34450808-a2507236-ecd9-11e7-81c2-c6f8ee62b5ca.png)

**Comment by deltakosh** [comment]
Did you try to change the fourth constructor parameter to nearest mode?
```
var advancedTexture = BABYLON.GUI.AdvancedDynamicTexture.CreateFullscreenUI("UI", true, scene, BABYLON.Texture.NEAREST_SAMPLINGMODE);
```

**Comment by Queatz** [comment]
@deltakosh just tried it.  Doesn't seem to work, I guessing because the image is rendered scaled-up onto the dynamic texture (which is per-pixel.)

**Comment by deltakosh** [comment]
Unfortunately there is no standard way to change that at canvas level.
Perhaps you could rely on a texture for this display? Because you can control the interpolation of the texture.

**Comment by Queatz** [comment]
@deltakosh Perhaps, but I am unsure of how I would get my texture inside my dialog (GUI.Rectangle)?

**Comment by deltakosh** [comment]
Woot!
excellent..Thank you for reporting it back :D
