### ISSUE TITLE
WebGL2UniformBuffersExceptionList and Firefox

### ISSUE THREAD

**Issue by mjschlot** [BabylonJS/Babylon.js#3462]
I found that Firefox/58 has the "same" issues as Chrome. I added "Firefox/58" WebGL2UniformBuffersExceptionList and the material issue I was seeing went away.

@deltakosh I see you wrote the code so I am wondering if you have been able to find a bug report for Chrome or have details on the underlying bug in Chrome?

I don't see the issue in Chrome any more and wonder if it is fixed in a minor version update of Chrome. I'd like to get a feature detection in place or a more specific version check in place since uniforms are hugely beneficial to performance.

**Comment by deltakosh** [comment]
Sounds good. Would you mind adding an enry to firefox bug DB?
Here is the one for Chrome: https://bugs.chromium.org/p/chromium/issues/detail?id=792966
It is fixed in Chrome 64.

There is no way to detect it as it is a bug in Angle code.

**Comment by deltakosh** [comment]
Actually the update was sent to Chrome 63. I'll update the list then :)

**Comment by mjschlot** [comment]
@deltakosh You're quick! I was submitting another PR (https://github.com/BabylonJS/Babylon.js/pull/3463) which I tacked it on to, but maybe that was unnecessary at this point.

**Comment by deltakosh** [comment]
I think it is a good PR :) just have some concerns about unnecessary changes regarding tests
(the new interface is a good idea)
