### ISSUE TITLE
Add param to CreateAndStartAnimation to specify whether the animation should apply to all children of the given node

### ISSUE THREAD

**Issue by RabidDawg** [BabylonJS/Babylon.js#3469]
See http://www.babylonjs-playground.com/#6VDYJ8#2

I would like to be able to group nodes into one logical object and animate that object at once w/o having to traverse every child node and apply the animation to that node as well.

**Comment by deltakosh** [comment]
Excellent idea

**Comment by deltakosh** [comment]
Done!
https://www.babylonjs-playground.com/#MH0VLI

**Comment by RabidDawg** [comment]
Great, thanks!

________________________________
