### ISSUE TITLE
Texturing with a 2D canvas

### ISSUE THREAD

**Issue by unicomp21** [BabylonJS/Babylon.js#347]
Is there a demo showing how to apply a 2D canvas as a texture to a mesh?  Is this the function of DynamicTexture?

**Comment by unicomp21** [comment]
Also, doing texturing with a video would be nice as well.

**Comment by deltakosh** [comment]
For video texture:
https://github.com/BabylonJS/Babylon.js/wiki/Advanced-Texturing

For DynamicTexture:
http://blogs.msdn.com/b/eternalcoding/archive/2013/06/27/babylon-js-a-complete-javascript-framework-for-building-3d-games-with-html-5-and-webgl.aspx#chap8

**Comment by unicomp21** [comment]
Thanks!
