### ISSUE TITLE
Assets Manager weird loading behavior

### ISSUE THREAD

**Issue by kutomer** [BabylonJS/Babylon.js#3484]
Hello,

When calling `load()` before `assetTask` is done `AssetsManager` is invoking the same task again even though it's already in progress.

Here is a playground that reproduces this behavior:
http://playground.babylonjs.com/#W6ZVM2

![screen shot 2018-01-04 at 18 46 53](https://user-images.githubusercontent.com/3729904/34574313-b504f708-f17f-11e7-9ebc-bcf8389c0a73.png)

**Comment by deltakosh** [comment]
Good catch..I'll fix it

**Comment by kutomer** [comment]
@deltakosh thanks for the quick fix you're awesome!
any idea when the fix(alpha-2) will be available on NPM?

**Comment by deltakosh** [comment]
This Friday :) unless @raananw can do it earlier

**Comment by RaananW** [comment]
This Wednesday! 😁

**Comment by kutomer** [comment]
@RaananW ידעתי שיש על מי לסמוך ;)
