### ISSUE TITLE
Physics impostor has wrong pivot point when scaling an exported object

### ISSUE THREAD

**Issue by RaananW** [BabylonJS/Babylon.js#3489]
See http://www.babylonjs-playground.com/#GA8XI#89  

http://www.html5gamedevs.com/topic/34802-impostor-bigger-than-the-mesh-after-scaling/?tab=comments#comment-200239

**Comment by dad72** [comment]
In fact it is not a problem of pivot or bone, I create a primitive box as an example on 3ds max and export it and we can see that the object does not fall on the ground (without bones).

If I create the primitive box with babylon, it works.

PG with the box :
http://www.babylonjs-playground.com/#GA8XI%2395

**Comment by dad72** [comment]
I did another test to understand what happens concretely. It is therefore the impostor that is offset with respect to the exported object of 3ds max (and can be blender).

See this PG to see the problem. The box 2 made with Babylon enters the box 1 of the depth that is missing between the ground and the box 1

I guess that can help.

http://www.babylonjs-playground.com/#GA8XI#99
