### ISSUE TITLE
Removing light does not work as expected

### ISSUE THREAD

**Issue by TrevorDev** [BabylonJS/Babylon.js#3492]
Related to #3308

see https://playground.babylonjs.com/#F2JDZC 

1. Create light
2. Create sphere
3. Remove light
4. Observe sphere is still lit (Unexpected)
5. Create ground
6. Observe ground is unlit but sphere remains lit

Expected removing light does not keep any meshes lit

**Comment by deltakosh** [comment]
Will fix it!
Thanks :)

**Comment by adergham** [comment]
It seems that removeLight is still broken to me.
If you call this function in a timeout, the light is never removed.
[https://playground.babylonjs.com/#NEPXRP#1](https://playground.babylonjs.com/#NEPXRP#1)

**Comment by deltakosh** [comment]
True..fix on its way
