### ISSUE TITLE
Assets manager not firing onFinish/onTasksDoneObservable if no tasks

### ISSUE THREAD

**Issue by bobalazek** [BabylonJS/Babylon.js#3496]
Not sure why, but when you don't specify any tasks in the assets manager, it doesn't trigger either the onFinish callback, nor the onTasksDoneObservable. I did check the code part but seems to be everything ok there.

PG: https://playground.babylonjs.com/#89F51L

It does fire, however, if you specify a task: https://playground.babylonjs.com/#89F51L#1

**Comment by bobalazek** [comment]
After some experimentation with the AssetsManager I figured that if I delay the execution of `onFinish()` & `onTasksDoneObservable.NotifyObservers()` (wrap them into a `setTimeout()`), it does fix the issue, but still not sure about the actual reason for it.

**Comment by deltakosh** [comment]
As there is no task, the load function will return immediately.In this case you will need to ensure the observables are set BEFORE calling load():
https://playground.babylonjs.com/#89F51L#2
