### ISSUE TITLE
Babylon.js for GPGPU

### ISSUE THREAD

**Issue by elessarperm** [BabylonJS/Babylon.js#350]
Hi! 

I need to compute heightmap every frame and the method of computation is very expensive.
GPU can perform all these operations much faster and I want to try this approach.

The only way I see to achieve this is use RenderTargetTexture and make the 'computation' shader for it, then read data from this texture and use it on CPU.

But this approach is kind of awkward because I need to set up special mesh and camera for it and so on. 

Are there any better ways?

p.s. I know about web workers but the algorithm is highly parallelizable and GPU computation time is significantly lower.

**Comment by deltakosh** [comment]
Could you please use the forum for questions:)
