### ISSUE TITLE
The wiki and API docs don't always explain the purpose or range of values/arguments.

### ISSUE THREAD

**Issue by Terrycloth** [BabylonJS/Babylon.js#351]
When describing different properties, values, arguments, etc, the wiki here on GitHub, and [API docs website](http://www.sokrate.fr/documentation/babylonjs/index.html), usually tell you things like a variable's *type*, but does not always give you a range, or explain the purpose of these things.

I've noticed two examples so far, which have confused me when learning how Babylon works.

One is the [`BABYLON.Color3`](http://www.sokrate.fr/documentation/babylonjs/BABYLON.Color3.html) class. Currently, the docs say that it accepts the arguments `r`, `g`, and `b`, for 'red', 'green', and 'blue' values, and it defines these values as numbers -- but it does *not* say that they should be floating-point numbers between 0 and 1. Is this a typical notation for colors in JavaScript? I'm still new to writing JS, so I was expecting numbers from 0 to 255, like in CSS. Even if floating points between 0 and 1 was the standard in JS, I think it would be helpful to include the normal range for any number values, for *all* the classes, in the documentation.

Another thing that confuses me is I notice a lot of the classes for creating cameras and meshes have a string `name` as the first argument. The tutorials usually use a string value that is the same or similar to the name of the *variable* containing the mesh or camera. I assume if you ever need to call or modify a camera or mesh, you'd be calling the variable name. So I can't figure out what purpose the `name` string argument serves.

**Comment by deltakosh** [comment]
For first point, You are right. Hopefully contributors will help completing the wiki
For second point, you can find meshes or cameras or lights by name when for instance you loaded your scene from a .babylon file

**Comment by Terrycloth** [comment]
You mean, if I created a scene in a `.babylon` file, I wouldn't be able to reference a mesh by the variable name in the game scripts, but I could reference the mesh using it's `name` string value?

**Comment by deltakosh** [comment]
If you load your scene from the .babylon, you will receive a scene object. This object will have a .meshes array. If you want to reach a specific object, you have to differentiate it from others by using its name.

**Comment by deltakosh** [comment]
*if you want to reach a specific mesh

**Comment by deltakosh** [comment]
Perhaps this example could be clearer:
http://www.babylonjs-playground.com/?16

The newMeshes array could be browsed to find a specific mesh by name

**Comment by Terrycloth** [comment]
Hmm. Alright, I guess that makes sense, then. Thanks.

After I've spent more time working with Babylon, I might be able to contribute to the wiki by making edits based on the things that confused me the first time around.

**Comment by deltakosh** [comment]
Excellent:)

**Comment by Terrycloth** [comment]
...If I can figure out how to work with Babylon in the first place. I'm finding very little that explains input controls for gamepad, and less for keyboard and mouse.

**Comment by deltakosh** [comment]
Please use the forum for question, we have a great community
Regular keyboard/mouse camera (freeCamera):
http://www.babylonjs-playground.com/

For gamepad:
http://www.babylonjs-playground.com/#2AUKG

Pretty easy, correct? You just have to switch between cameras to change inputs

**Comment by Terrycloth** [comment]
Sorry, I mean controlling a character on-screen. I'm trying to make a fairly simple third-person game where players on desktop and laptop computers can use a gamepad if they have one, and a keyboard and/or mouse if they don't. 

Thank you for your patience.

**Comment by Terrycloth** [comment]
I would have originally brought my questions to the forum instead, but for a few days now, it's saying that my forum account is waiting on admin approval, and I can't post anything.
