### ISSUE TITLE
Abstraction of the (Generic) Gamepad class

### ISSUE THREAD

**Issue by RaananW** [BabylonJS/Babylon.js#3514]
A few issues that should be addressed:

* The Gamepad class has leftStick and rightStick definitions, but there is no guaranty that a Gamepad has those. Due to backwards-compatibility they can not be removed, but generic buttons and axes should be added. The user should also be able to state the amount of axes they expect.
* If the Gamepad class is extended (technically possible) there is no way to register the new implementation with the gamepad manager and allow creating it. My suggestion here - add a "register gamepad type" to the manager (mainly using regex with the gamepad.id, but probably using a "isThisGamepadTheOneIWant()" function in the (extended) gamepad class itself). the _addNewGamepad function should use this method instead of the fixed way

**Comment by zakhenry** [comment]
To give more context to this issue for future reference, this requirement was encountered when trying to add support for the  [3dconnexion spacenavigator](https://www.3dconnexion.co.uk/products/spacemouse/spacenavigator.html), which has 6 axes.

**Comment by deltakosh** [comment]
Hello, how do you see the integration of this feature?

**Comment by deltakosh** [comment]
Closing this one for now as we see no traction. Will reopen if required
