### ISSUE TITLE
Crash when disposing of instanced mesh

### ISSUE THREAD

**Issue by Ericky14** [BabylonJS/Babylon.js#3516]
Hello,

I have been running into an issue when trying to dispose of instances on my scene. I am not exactly sure why the error happens, but I've got 1000+ instances on the scene and I try to dispose of them all at once with a for loop.

<img width="663" alt="screen shot 2018-01-09 at 12 09 20 pm" src="https://user-images.githubusercontent.com/21248862/34736913-8935a944-f542-11e7-9e57-5e9ddfc8afc7.png">

**Comment by deltakosh** [comment]
would you mind to repro the issue in the playground?

I'll make sure to fix it right away!

**Comment by Ericky14** [comment]
Here you go. Sorry for the messy code, I didn't have much time. But I figured out that the error only happens if you call `createOrUpdateSelectionOctree`.

https://playground.babylonjs.com/#I04RBE
