### ISSUE TITLE
Support for picking complex (nested) meshes with ActionManager

### ISSUE THREAD

**Issue by Exolun** [BabylonJS/Babylon.js#3520]
It would be nice if we had functionality that supports adding an action on a parent mesh that applies to interactions on child meshes.

Imagine I have a complex model that I've imported into a Babylon scene with many child meshes, let's call it 'myMesh'.  I would like to be able to create an event that's fires if the action occurs on any child mesh.

The API syntax would look something like the following - just pass recursive: true to indicate that the trigger should fire if the interaction occurs on any child meshes

```typescript
//< Import model here >

myMesh.actionManager = new BABYLON.ActionManager(scene)
myMesh.actionManager.registerAction(
    new BABYLON.ExecuteCodeAction(
        {trigger: BABYLON.ActionManager.OnDoublePickTrigger, recursive: true}, () => {
            console.log('My model clicked!')
        }
    )
);
```

Regarding performance - the implementation of such a feature would necessitate a more lightweight approach than registering all child meshes as observers for the action.  I would recommend building a map of unique mesh Ids that are listening for events and for each event (picking, clicks, input, etc), just check the mapping to see if the pickedMesh is one of the meshes listening.  (As opposed to checking if the actionManager for that particular mesh has a trigger)

**Comment by haroldma** [comment]
Any updates on this? Action manager is pretty unusable with any 3D object with more than one mesh.

**Comment by deltakosh** [comment]
Unusable is a strong word.
This is not for 3.2 so far

**Comment by deltakosh** [comment]
Can you folks provide a sample of what is expected in the playground? I'll use it to work on the feature

**Comment by haroldma** [comment]
Here is a quick [PG](https://www.babylonjs-playground.com/#K4RR60).

What we wanted was for a way that an action manager could work recursively. For example in the playground, you would hover over any mesh under `root` and it will show the alert.

**Comment by deltakosh** [comment]
Wonderful! I'll work on it next week

**Comment by deltakosh** [comment]
So it is done
Slightly difference the isRecursive information has to be on actionManager for performance reason:
```
BABYLON.SceneLoader.ImportMesh("", "/playground/scenes/BoomBox/", "BoomBox.gltf", scene, function(meshes) {

        // The first parameter can be used to specify which mesh to import. Here we import all meshes
        BABYLON.SceneLoader.ImportMesh("", "/playground/scenes/", "skull.babylon", scene, function(newMeshes) {
            var root = new BABYLON.Mesh('Name', scene);
            newMeshes[0].parent = root;
            meshes[0].parent = root;

            newMeshes[0].enablePointerMoveEvents = true;
            meshes[0].enablePointerMoveEvents = true;
            meshes[1].enablePointerMoveEvents = true;

            root.actionManager = new BABYLON.ActionManager(scene);
            root.actionManager.isRecursive = true;

            root.actionManager.registerAction(new BABYLON.ExecuteCodeAction(
                { trigger: BABYLON.ActionManager.OnPointerOverTrigger },
                function() {
                    alert('Mouse over!');
                }));
        });
    })
```

**Comment by haroldma** [comment]
Fast delivery 👍 😄

**Comment by deltakosh** [comment]
Always :D

**Comment by shaileshiyer** [comment]
Hey about support for complex meshes with multiple children for actionManager is the isRecursive flag broken in the latest release?
https://playground.babylonjs.com/#4SH4JZ#5

**Comment by deltakosh** [comment]
I'll check asap :)

**Comment by shaileshiyer** [comment]
Thanks in advance :)

**Comment by deltakosh** [comment]
Will be fixed in next commit!

**Comment by shaileshiyer** [comment]
Im a bit interested in the issue can i know whats causing it?

**Comment by deltakosh** [comment]
Here is the fix :)
https://github.com/BabylonJS/Babylon.js/commit/f0c743afdae972a885319ec63d51fc855e85d084

**Comment by shaileshiyer** [comment]
Thanks . That was fast. :)

**Comment by shaileshiyer** [comment]
would the actionManager isRecursive not work if it is attached on a transform node?

**Comment by shaileshiyer** [comment]
https://playground.babylonjs.com/#8PFA14
here is an example.

**Comment by deltakosh** [comment]
Nope only real meshes can have action manager
