### ISSUE TITLE
AssetsManager doesn't clear loaded tasks

### ISSUE THREAD

**Issue by kutomer** [BabylonJS/Babylon.js#3533]
Hello :)

AssetsManager doesn't clear loaded tasks. [here is a playground that reproduces this wierd behavior](https://www.babylonjs-playground.com/#ZJYNY#57)
<img width="470" alt="screen shot 2018-01-11 at 20 18 00" src="https://user-images.githubusercontent.com/3729904/34842713-9463483c-f70c-11e7-86e7-295cfef9ce59.png">
*Of course  assetsManager.reset() solve the issue
*I assume that 6s is enough to load the assets

Thanks!

**Comment by deltakosh** [comment]
Hello, why do you want the assetsManager to clear the tasks? It should not do that. It's user data so it must be cleared by user (using reset)

**Comment by kutomer** [comment]
Hi,
I don't see the tasks themselves as user data, but the loadedMeshes.
I'm building room designer, when ever a user is adding an item I fetch the asset.
The problem now is that everytime I request for new item I get all the old ones all over again.

May I ask for the reason why you've decided to implement it this way?

**Comment by deltakosh** [comment]
This is why we added reset() API. So you can decide to clear the tasks or not depending on your needs.

But this is perhaps to much and we should clear the successful tasks upon completion?

**Comment by kutomer** [comment]
I think that as an infrastructure I would have started with the naive solution - clear every finished task (error / success) instead of the reset function.
If that's not enough abort (to stop pending requests), retry (to retry failed tasks) and reload (reload all tasks)

**Comment by deltakosh** [comment]
I think I will follow you on this one :)
I'll work on that asap (Or you may want to do a PR perhaps?)

**Comment by deltakosh** [comment]
I did the code. But I will use this PR to also add comments to the class
So I think I will be able to merge it this tuesday. Stay tuned ;)

**Comment by kutomer** [comment]
Sorry for the delay, I'm on holiday in France and therefore less available.
That was quick! Thanks!

**Comment by deltakosh** [comment]
My pleasure!

**Comment by kutomer** [comment]
Thanks again! that's really helpful!
Any idea when it will be available via npm?

**Comment by deltakosh** [comment]
Next update is aimed to be this Friday ( cc @RaananW )

**Comment by kutomer** [comment]
Sorry to bug you about that but any updates about 3.2-alpha6?
Maybe you guys can update about releases in [announcements](http://www.html5gamedevs.com/forum/29-announcements/)?

**Comment by deltakosh** [comment]
This Monday:) I promise

**Comment by kutomer** [comment]
@deltakosh thanks for the fix!
But here is another thing:
http://playground.babylonjs.com/#VA21EY

Only the first model is being loaded, but I would expect the assets manager to load them both - what do you guys think?

Maybe a simple "loadMeshTask" function can solve this all issue?

Thanks again :)

**Comment by deltakosh** [comment]
You are loading the model named t. Isn't it what you expected?

**Comment by kutomer** [comment]
Oh.
I'm sorry but that's not the playground I intended to send, here is a fixed version:
http://playground.babylonjs.com/#VA21EY#2

**Comment by deltakosh** [comment]
Ok gotcha, this is not supported, you have to launch load only after having added all tasks.
