### ISSUE TITLE
Use stencil for clipplanes

### ISSUE THREAD

**Issue by deltakosh** [BabylonJS/Babylon.js#3539]

**Comment by xuchen-shadow** [comment]
Is it possible to add multiple clipping planes support?

**Comment by deltakosh** [comment]
Nope but I'm interested by your use case as based on htat we may want to consider supporting multiple clip planes

**Comment by xuchen-shadow** [comment]
Actually I am writing a viewer for an BIM application. The users really need multiple clipping planes. I am now using CustomMaterial for it. But I also want to support it for PBR materials.

**Comment by deltakosh** [comment]
Ok makes sense so perhaps instead of using stencil for a single plane we should add support for multiple planes

**Comment by gedw99** [comment]
+1 regarding multiple planes. 
My use case:
I have to do medical brain scans and these are non orthagonal. Users need many clipping planes in order to cognitively understand the 3d volumes they are looking at

**Comment by deltakosh** [comment]
Not needed as we now have: https://github.com/BabylonJS/Babylon.js/issues/3765
