### ISSUE TITLE
Bad performance on some Macs

### ISSUE THREAD

**Issue by gonchar** [BabylonJS/Babylon.js#3542]
Hello! I've noticed big performance differences between two default demos in babylon.js site.

This demos has good performance http://www.babylonjs.com/demos/yeti/ Performance capture in Firefox https://www.dropbox.com/s/505txu74d717gyq/good-performance.json?dl=0

This one is low http://www.babylonjs.com/demos/flighthelmet/ Performance capture in Firefox https://www.dropbox.com/s/d4dw8pgakcvdlvd/bad-performance.json?dl=0

The difference I've noticed is that there is the huge gap between calling next rendering frame. and everything in between is taken by "Graphics".

I don't have such issues on Windows machines.
My iMac info that has this issue:
<img width="698" alt="screen shot 2018-01-14 at 12 39 56" src="https://user-images.githubusercontent.com/1416917/34915981-0937bbb2-f928-11e7-82d4-7c0bd318318d.png">

Do you have any idea what can be different in these two demos? I thought that only my project has this issue but I've debugged it to the state that default demos has the same performance issue on my machine and some others(Mac Pro, late 2016 macbook pro).

Thank you!

P.S. I've tried Safari, Chrome, Firefox. Everything is the same there. Babylon engines says that it uses WebGL 2.0 and it uses power GPU for rendering.

**Comment by gonchar** [comment]
I see that increases drawcalls a lot.
<img width="1584" alt="screen shot 2018-01-14 at 14 37 51" src="https://user-images.githubusercontent.com/1416917/34917010-8d640020-f938-11e7-8a51-f8610726be3f.png">

**Comment by julien-moreau** [comment]
Hey! Reproduced on MacBook Pro with ATI chipset
Will take a look to find the issue, the mansion demo runs at 3 frames per second

**Comment by gonchar** [comment]
Thank you so much!

Just want to share some findings:
- Please ignore the previous comment. Seems like there is a bug in babylon debug overlay. When you show the debug overlay and start switching between Stats and Mesh tabs it increases number of drawcalls with each switch
- For this demo when I disable all textures in Scene tab it renders 60fps but when I enable just one of the texture types(one of Diffuse, Normal, Ambient and etc) it drops the frame rate immediately.

**Comment by deltakosh** [comment]
Hello and thank you very much for having reported this issue

Several things to test (I do not have a mac but I'll find one this Tuesday)

- [ ] Turn off webgl2: Is it better?
- [ ] Try to run your code with 3.1. is it the same behavior? If yes this could mean that there is an issue with the ATI driver. Furthermore, as I can see in your screenshot, we spend all time in Inter-frame (so outside of our JS code) which means it has to do with driver or something wrong in the shader
- [ ] Can you try turning on only ambient and normal textures? 
- [ ] Can you try turning lights off?

**Comment by deltakosh** [comment]
I was NOT able to reproduce on

- iPhoneX
- Surface Pro 3 (intel chipset)
- Desktop PC with nVidia card

So it seems to be Mac related.

**Comment by gonchar** [comment]
**Can you try turning on only ambient and normal textures?**
Yep still the same. It has low framerate even with one texture type enabled. I've captured a video for you https://www.dropbox.com/s/qxscvcqnun8dquo/helmet-performance.mov?dl=0

**Can you try turning lights off?**
I've run helmet demo. Enabled only diffuse textures and made all materials disableLighting = true
and got this frame rate. still low. and strange thing is that it is volatile.
<img width="188" alt="screen shot 2018-01-14 at 19 46 04" src="https://user-images.githubusercontent.com/1416917/34920002-a1d04a7a-f963-11e7-8d8d-5124bbc2ad0d.png">
in that state when I disable diffuse textures(so lighting on materials is turned off) I get this
<img width="184" alt="screen shot 2018-01-14 at 19 46 15" src="https://user-images.githubusercontent.com/1416917/34920014-d894e4c6-f963-11e7-9704-dafaeb2eec48.png">

**Can you provide a capture of the debug layer without switching tabs? I see a too big number of materials on your capture (should be 95 and not 1691)**
<img width="542" alt="screen shot 2018-01-14 at 19 49 17" src="https://user-images.githubusercontent.com/1416917/34920025-0a315208-f964-11e7-8600-a5438ff2f337.png">

**Comment by gonchar** [comment]
**Turn off webgl2: Is it better?**
nope, still the same. I used disableWebGL2Support to check that

**Comment by deltakosh** [comment]
Can you try this scene: https://www.babylonjs-playground.com/indexstable#4AM01A#6

**Comment by deltakosh** [comment]
You potential FPS is 725 which means that there is something wrong on browser native level or at OS level

**Comment by gonchar** [comment]
**Can you try this scene: https://www.babylonjs-playground.com/indexstable#4AM01A#6**
This one works like a charm! 60 FPS!

**Comment by deltakosh** [comment]
And this one?
https://www.babylonjs-playground.com/index.html#4AM01A#6

**Comment by gonchar** [comment]
**And this one? https://www.babylonjs-playground.com/index.html#4AM01A#6**
Yep. This one is bad. So 3.1 works good, 3.2 works bad with this demo.

**Comment by deltakosh** [comment]
Rats!

**Comment by deltakosh** [comment]
Ok digging into that right now

**Comment by deltakosh** [comment]
Should be good now
Pushing to preview channel

**Comment by deltakosh** [comment]
Pushed. Clear your cache before testing but this should be good

**Comment by gonchar** [comment]
Thank you! It works like a charm! 

Btw I try to understand how you fixed this issue. In [this commit](https://github.com/BabylonJS/Babylon.js/commit/09be535947e9c573ca830cebc505be37a031f4e4#diff-17c850aa91890c42f3d3d7cf166b2b94R4860) I see that you've added disableTextureBindingOptimization which equals true when on Macintosh. and I see that it executes exactly the same code that it was before. How this fix solves the issue?
