### ISSUE TITLE
Multiple animation layers in one GLB mixing sampler keys, possible bug

### ISSUE THREAD

**Issue by MilosBulat** [BabylonJS/Babylon.js#3548]
Hi BabylonJS team,

I've made a simple GLB with two different animation layers from our last discussion.
Simple mesh rigged with 5 joints and one of them moving on the X axis from 0 to 1 in "move_left" animation and from 0 to -1 on X axis in "move_right" animation. Both animations samplers contain right position keys for animated joint and Babylon sandbox starts "move_left" animation inspected from chrome dev tools.
Animated joint position goes from 0 to -1 on the X axis instead of 0 to 1. Is this a bug or is something wrong with the file?

[46323_Gltf_Anim.zip](https://github.com/BabylonJS/Babylon.js/files/1632714/46323_Gltf_Anim.zip)

Thanks for your help,
Miloš

**Comment by deltakosh** [comment]
Pinging @bghgary

**Comment by bghgary** [comment]
I debugged a bit. This is a bug in the loader if you have two animations targeting the same property.
