### ISSUE TITLE
Sphere Emitter not emitting in the right direction

### ISSUE THREAD

**Issue by IbraheemOsama** [BabylonJS/Babylon.js#3550]
The sphere emitter logic is not working like it is suppose to.
https://www.babylonjs-playground.com/#6P6U4G#4

the logic is inside class Babylon.js\src\Particles\babylon.sphereParticleEmitter.ts in the direction function.
What is suppose to happen, the emitter should emit the direction from the sphere center to the particle. (direction outside the sphere) you will notice that some of the particles are moving inward the sphere.

**Comment by sebavan** [comment]
i have the fix done just adding all the documentation for the apis. eta for the fix is tomorrow.

**Comment by sebavan** [comment]
Fixed

**Comment by IbraheemOsama** [comment]
@sebavan what was wrong within my code ? :)

**Comment by sebavan** [comment]
This was really cool to look at :-) and I added all the doc at the same time.

Main cone changes start here (emit from cone not disqus alongside base to position): https://github.com/BabylonJS/Babylon.js/pull/3562/files#diff-b8780ab14ac9a157ee86ebd09e73e2f8L11

And the sphere ones (emit alongside radius): https://github.com/BabylonJS/Babylon.js/pull/3562/files#diff-1cdea3ae89592306b47efb67d16d7150L8

**Comment by IbraheemOsama** [comment]
@sebavan thanks :)
