### ISSUE TITLE
Occlusion query seems broken

### ISSUE THREAD

**Issue by deltakosh** [BabylonJS/Babylon.js#3552]
http://www.html5gamedevs.com/topic/35113-occlusion-queries-does-not-appear-right/

**Comment by deltakosh** [comment]
ping @IbraheemOsama for info

**Comment by IbraheemOsama** [comment]
Will have a look :)

**Comment by sebavan** [comment]
Assign back to @deltakosh  as I ll run out of time for this one.

**Comment by IbraheemOsama** [comment]
Looks like an urgent one, will have a look right now

**Comment by deltakosh** [comment]
Thanks mate:)

**Comment by IbraheemOsama** [comment]
The problem is with the bounding box :) it doesn't get drawn if the camera cam from the right 😆 
Will check whats wrong with the bounding box and right angle (it is not the query it is the bounding box)
