### ISSUE TITLE
Embrace Prettier

### ISSUE THREAD

**Issue by edzis** [BabylonJS/Babylon.js#3572]
This is a suggestions on top of #3571

I have seen a lot of value from removing formatting decisions from developers by embracing [Prettier](https://prettier.io/) and I believe it would bring value here.

There are 3 critical parts to get the benefits:
- test and define clear set of prettier config values and ignore rules
- ask developers to use it on contribution guidelines
- format all current code (using npm/yarn task like `prettier --write '**/*.{ts,tsx,js,json,css}'`)

There are more steps to take later, but it does not have to be enforced strictly, at least not in the beginning.

**Comment by deltakosh** [comment]
Only my thought here:)
First thanks a lot for your interest and your contributions (the video one is really cool)

I tend to refuse adding more and more external tools to the project. The build process is already pretty crowded
