### ISSUE TITLE
Use `namespace` instead of `module`

### ISSUE THREAD

**Issue by edzis** [BabylonJS/Babylon.js#3573]
This is a suggestions on top of #3571

Since TypeScript 1.5 instead of `module` we should use `namespace`. See https://www.typescriptlang.org/docs/handbook/namespaces-and-modules.html

This is one thing that Prettier automatically changes and I currently have to revert that change for every commit.

**Comment by RaananW** [comment]
This requires changing all of the files in the src folder, just so a configurable plugin will not autochange it. 
When compiled it generated the same code - module and namespace are practically the same thing 
 and module is not deprecated. From the documentation you referenced : "(namely that module X { is equivalent to the now-preferred namespace X {)."

**Comment by edzis** [comment]
I am suggesting to run all code through prettier in #3572  

Even if the compiled code is perfectly fine as is this syntax prevents efficient usage of tooling (in this case, prettier) when contributing.

**Comment by deltakosh** [comment]
Hello! I'm not sure I want to go through a full framework change for the sake of an external tool

**Comment by edzis** [comment]
What if the full framework change takes 20 seconds, can be run at will, is not enforced but helps to make the codebase in consistent style? See https://github.com/BabylonJS/Babylon.js/pull/3571/files

**Comment by deltakosh** [comment]
The point is more over using Prettier as an official tool for bjs or not ;)

**Comment by deltakosh** [comment]
By the way I'm fine to move to namespace is this is the bestway to go for Typescript
