### ISSUE TITLE
Configuring using external JSON issue with babylonjs Viewer

### ISSUE THREAD

**Issue by electroheadfx** [BabylonJS/Babylon.js#3576]
I am trying to load  json configuration via HTML and I got this error:

- TypeError: undefined is not an object (evaluating 'cacheReference')
- line 107028 in viewer.js

I followed the doc here : https://doc.babylonjs.com/extensions/configuring_the_viewer -> 'Configuring using external JSON"

config.json content is:
{   
    "scene": {
        "debug": true
    }
}

The HTML is:
https://bin.fuelphp.com/snippet/view/OE

Online test is:
http://efxdesign.fr/babylonjs/loadconfig/

I think the JSON is malformated or its doesn't want load ?

**Comment by electroheadfx** [comment]
Thanks RaananW you fixed it here: https://github.com/BabylonJS/Babylon.js/commit/d3e75cebc609c2aec46b58bdbeae3de510233a3a

**Comment by RaananW** [comment]
Forgot to close the issue :)
