### ISSUE TITLE
Update NuGet package for latest release(s)

### ISSUE THREAD

**Issue by mwpowellhtx** [BabylonJS/Babylon.js#3593]
The last NuGet package released was [2.3.1](http://www.nuget.org/packages/BabylonJS/2.3.1), however, I see that there have been several updates to the Github ([2.4.0](http://github.com/BabylonJS/Babylon.js/releases/tag/v2.4.0), [2.5.0](http://github.com/BabylonJS/Babylon.js/releases/tag/v2.5.0), [3.0.7](http://github.com/BabylonJS/Babylon.js/releases/tag/v3.0.7), [3.1.0](http://github.com/BabylonJS/Babylon.js/releases/tag/v3.1.0)). I could look into what it would take to support NPM, however, I am working on a project that is more geared to support NuGet. Thanks!

**Comment by deltakosh** [comment]
Hello! We decided to switch to npm only as this is the tool used by the vast majority of our users
Let me ping @meulta to see if he can transfer the nuGet ownership to me

**Comment by mwpowellhtx** [comment]
@deltakosh Thanks! I'm also interested to distill just the bits that are necessary for run-time distribution. I don't care about samples, in particular, in this context, especially because it just adds unnecessary clutter to my projects. Worst case, I'll see about handling the NPM, but for aforementioned caveats.

**Comment by mwpowellhtx** [comment]
@deltakosh So, to clarify, I'm trying to identify the [BabylonJS NPM](http://www.npmjs.com/~babylonjs) package in a brand new empty *ASP.NET* project using VS2015, but the versions are not listed via *IntelliSense*? First, is there a way to list the available *NPM* versions, as in for *NuGet*? Second, how to get it wired up in *Visual Studio*? Thanks again!

**Comment by deltakosh** [comment]
Unfortunately I'm not experienced with asp.net and VS enough to help:(

**Comment by mwpowellhtx** [comment]
@deltakosh No worries. For simplification, I'm focused mainly on interfacing with *NPM* via the *packages.json*, and potentially using *gulp* to help with the digestion of the packaged files, if it helps. I found an [NPM registry](http://registry.npmjs.org/babylonjs) which lists the version history. Latest stable appears to be *3.1.1*.

**Comment by deltakosh** [comment]
This is correct:)

**Comment by mwpowellhtx** [comment]
@deltakosh From inspection of the installed NPM package, it would seem that the samples, etc, were a ``NuGet`` packaging thing. So, ``NPM`` would be the better place for me to begin.

Next note, and possibly a follow on issue, is what appears to be an **[Oimo](http://www.npmjs.com/package/oimo)** dependency as a baked in JavaScript file instead of a true NPM packaging dependency? BabylonJS does appear to depend upon *[cannon](http://www.npmjs.com/package/cannon)* properly. Gauging from the appearances of ``Oimo`` in the source, it would seem this is a stronger dependency than a baked in file, though?

**Comment by deltakosh** [comment]
Definitely agree. We never took time to update the package for that
Pinging @raananw as I think this is a good idea

**Comment by mwpowellhtx** [comment]
@deltakosh Thanks for the feedback! :+1:  I haven't quite sorted out my dependencies yet, but I've got a clearer idea how to proceed.

**Comment by deltakosh** [comment]
Closing the issue as we are no more supporting NuGet
