### ISSUE TITLE
issue with exporting indices in glTF Serializers

### ISSUE THREAD

**Issue by kcoley** [BabylonJS/Babylon.js#3598]
It has been reported that a glTF asset generated with the serializer has incorrect indices: 
[glTF issue #1216](https://github.com/KhronosGroup/glTF/issues/1216).

**Comment by ashutoshmaurya10** [comment]
Hi
Attached is the .babylon file we are using to convert to .gltf . Any pointers will be really helpful.
Thanks & Regards
[Anim-GE 5.babylon.zip](https://github.com/BabylonJS/Babylon.js/files/1654770/Anim-GE.5.babylon.zip)

**Comment by deltakosh** [comment]
Can you open a new issue please?

**Comment by deltakosh** [comment]
Associated with #3247

**Comment by kcoley** [comment]
I have a pending bug fix which should address this issue: #3638

**Comment by VarshaKamble159** [comment]
Hi,
I have installed the babylonjs and babylon-serializers using npm. Following are the versions installed

 ```
 "babylonjs": "^3.2.0-alpha6",
 "babylonjs-serializers": "^3.2.0-alpha6",
```

When i am trying to run my code, i am getting following error.

```
ERROR in .../node_modules/babylonjs-serializers/babylonjs.serializers.module.d.ts (286,94): Cannot find name 'IMaterialPbrMetallicRoughness'.
ERROR in .../node_modules/babylonjs-serializers/babylonjs.serializers.module.d.ts (313,57): Cannot find name 'MaterialAlphaMode'.
```
Kindly suggest for the same.

Thanks

**Comment by RaananW** [comment]
Hi @VarshaKamble159 ,
Thanks for letting us know! WOuld you be able to create a different issue? as those two issues are not related. We will look into it.

**Comment by VarshaKamble159** [comment]
Hi @RaananW ,

Thanks for the quick reply. Created new issue [#3654](https://github.com/BabylonJS/Babylon.js/issues/3654)
Thanks.

Regards,
Varsha
