### ISSUE TITLE
Start supporting promises

### ISSUE THREAD

**Issue by deltakosh** [BabylonJS/Babylon.js#3600]
- [x] Create a tiny polyfill
- [x] Rely on existing promises if possible

**Comment by julien-moreau** [comment]
Try to find where it should be used: everywhere where you can await for example?

**Comment by JeanPhilippeKernel** [comment]
Example of using ?!,

**Comment by julien-moreau** [comment]
const content = await Tools.LoadFile(url, ...);

**Comment by deltakosh** [comment]
The plan is to support continuation but not await as it is not possible to polyfill it :(

**Comment by JeanPhilippeKernel** [comment]
So Then...catch or fetch ? (Fetch dont have progress évent interface if I dont lié )

**Comment by deltakosh** [comment]
correct

**Comment by julien-moreau** [comment]
Oh :(

**Comment by JeanPhilippeKernel** [comment]
Okay we Can deal with It :), to make some loading.. It 'll be easy to write polyfill for es6  support

**Comment by RaananW** [comment]
I support the cause. The viewer is already promise-based, with a polyfill for IE11

**Comment by deltakosh** [comment]
Promises are in!
