### ISSUE TITLE
VideoTexture with autoplay false is "not renderable"

### ISSUE THREAD

**Issue by DavidHGillen** [BabylonJS/Babylon.js#3607]
Tried to create a VideoTexture with autoPlay set to false
`WARNING: texture bound to texture unit _ is not renderable.`
running through the console.

Perfect fix would be to render the first frame of video, patch would be to have the texture slot initialized with renderable information.

No actual issue beyond filling console with warning messages.

**Comment by deltakosh** [comment]
Good catch
Please feel free to submit a PR for this

**Comment by deltakosh** [comment]
I fixed it actually:)
