### ISSUE TITLE
ERROR on TextBlock adding to box faces

### ISSUE THREAD

**Issue by chopin** [BabylonJS/Babylon.js#3614]
I tried to add TextBlock on box faces, but an error is raised.  I tried Rectangle, and StackPanel, too, but error again. Only Button is added on box faces successfully. Following is a Playground example I created showing the error:

https://www.babylonjs-playground.com/#YZR3I3#5

I tried to use other ways to go ground this problem such as drawText() fillText(), etc. but multiline and resize- to-fit is complicated to implement. TextBlock already has them implemented, but it is not added to box faces. Now, I am using Button on box faces, but I am afraid that it consume more computational resources making slower. 

I am looking for a better way to put text on box faces. Please let me know if you have any advice.

**Comment by deltakosh** [comment]
You need to instantiate the controls with new keyword:
https://www.babylonjs-playground.com/#YZR3I3#6
