### ISSUE TITLE
Group Animation doesn't run in Chromium using 3.1.2 alpha 4. 

### ISSUE THREAD

**Issue by davidbawel** [BabylonJS/Babylon.js#3633]
However, it runs on the Chrome Browser.

**Comment by deltakosh** [comment]
Do you have a repro?seems weird as it is no linked to webgl

**Comment by deltakosh** [comment]
Closing it for now. 

Please reopen if you have a repro case obviously ;)

**Comment by davidbawel** [comment]
Hi David,

Sorry I couldn't get back to you concerning the repository question. I only have a repository personally to access the private repository we use here at Sony. Unfortunately, we cannot share the repository, but the bug still exists. To be more specific, we're using Electron - which runs the latest version of Chromium. I tested this morning, and animation Group won't run at all in Electron; but runs fine in the Chrome browser. However, I simply stopped using Animation Group and set "for loops" to accomplish the same result. But as we will always be using Electron in our current pipeline, it would be great to have animation Groups available in the future. Please let me know how you would like to proceed, or if I can help you with fixing the bug. Otherwise we're moving forward fine on the multiplayer game for South by Southwest - just allot of work for me.

Thanks,

David Bawel
Sony Senior Developer

**Comment by davidbawel** [comment]
There is no additional info in the console - and the animation group is getting called -but simply not starting the animation. The code is exactly taken from your last playground scene. So I'm not sure how to assist in solving, however if there is something I can do to assist, please let me know. 

FYI - the scene that does start the animation in Electron is simply the standard scene.beginAnimation();

Thanks,

David
