### ISSUE TITLE
Customize webVR gaze pointer

### ISSUE THREAD

**Issue by Bulisor** [BabylonJS/Babylon.js#3640]
It would be nice if we had the posibility to customize more the gaze pointer, or why not, to add our texture, or gui element. Thank you.

**Comment by TrevorDev** [comment]
See PR to customize the gaze tracker by setting a mesh to be used. Is that along the lines what you are looking for?

**Comment by deltakosh** [comment]
Clsoing for now. Please open a new one if @TrevorDev works was not what you needed
