### ISSUE TITLE
gltf 2.0 model causes exception in loader

### ISSUE THREAD

**Issue by webprofusion-chrisc** [BabylonJS/Babylon.js#3642]
The attached model is exported from threejs using the gltf exporter. I can load it in various other gltf viewers with varying success, the strongest so far being https://pissang.github.io/clay-viewer/editor/ and looks like this (once you zoom inside the environment sphere):
![image](https://user-images.githubusercontent.com/2445502/35493609-96cbd44a-04ef-11e8-9a2c-548025379046.png)

In a BabylonJS viewer (as used in VS Code Gltf preview etc) the loader complains with:
`babylon.glTFFileLoader.js:sourcemap:3186 Uncaught RangeError: start offset of Float32Array should be a multiple of 4
    at typedArrayConstructByArrayBuffer (<anonymous>)
    at new Float32Array (native)
    at http://editor.babylonjs.com/libs/loaders/babylon.glTFFileLoader.js:3186:46
    at http://editor.babylonjs.com/libs/loaders/babylon.glTFFileLoader.js:3118:25`

[ormsby.zip](https://github.com/BabylonJS/Babylon.js/files/1672178/ormsby.zip)

The source scene is from this app (currently threejs but in the future hopefully other renderers): https://designer.ormsbyguitars.com/app/

If there is an independent validator I can try this on I could do that, otherwise I can't tell if the export is wrong or if it's the babylon import.

Thanks!

**Comment by deltakosh** [comment]
You can use the gltf validator: http://github.khronos.org/glTF-Validator/
Your file seems containing multiple errors

I close this issue. Please reopen it if you think there is still a bug obviously
