### ISSUE TITLE
Issues with the Blender Exporter (Animations)

### ISSUE THREAD

**Issue by kpko** [BabylonJS/Babylon.js#365]
Hi,

I'm having two problems with the exporter for Blender at the moment. 

1. I have 3 key frames in my animation in Blender, the exporter exports 100 key frames (one for each frame in the animation). This doesn't really make sense to me, since we could use those 3 key frames and interpolate. Which leads to my second problem...

2. Babylon.js doesn't support interpolation between matrices. I animated the position and rotation of a bone in Blender, so it should export the key frames with the position as a vector3 and the rotation as a quaternion - both data types where Babylon.js could interpolate by itself. Shouldn't the exporter export the simple vectors and quaternions? Or is it possible to somehow interpolate between matrices?

**Comment by deltakosh** [comment]
Hello could you please use the forum? Thank you so much!

**Comment by kpko** [comment]
Done. Thank you!
