### ISSUE TITLE
Error in babylonjs.serializers.module.d.ts

### ISSUE THREAD

**Issue by VarshaKamble159** [BabylonJS/Babylon.js#3654]
Hi,
I have installed the babylonjs and babylon-serializers using npm. Following are the versions installed

 ```
 "babylonjs": "^3.2.0-alpha6",
 "babylonjs-serializers": "^3.2.0-alpha6",
```

When i am trying to run my code, i am getting following error.

```
ERROR in .../node_modules/babylonjs-serializers/babylonjs.serializers.module.d.ts (286,94): Cannot find name 'IMaterialPbrMetallicRoughness'.
ERROR in .../node_modules/babylonjs-serializers/babylonjs.serializers.module.d.ts (313,57): Cannot find name 'MaterialAlphaMode'.
```
Kindly suggest for the same.

Thanks

**Comment by ravip** [comment]
Yes, I am also getting this issue. Could not test further until this gets resolved.

**Comment by deltakosh** [comment]
@RaananW would you mind pushing an update to NPM?

**Comment by RaananW** [comment]
I will push an update later today. versiln will be 3.2.0-alpha7

**Comment by RaananW** [comment]
3.2.0-alpha7 was just published, could you test if it is working correctly now?

**Comment by VarshaKamble159** [comment]
Hi @RaananW ,

I tried installing latest babylon and babylon-serializers.js.  
`
  "babylonjs": "^3.2.0-alpha7",
  "babylonjs-serializers": "^3.2.0-alpha7",
`

The previous error is resolved now. 

I am using  **SERIALIZERS.GLTF2Export.GLTF(scene, path)** method to serialize .babylon file.
With previous version i was able to get .bin and. gltf object as returned value of this method.
With current version the method returns **undefined** and i am getting warnings in developer tool. 
![error](https://user-images.githubusercontent.com/9550268/35622291-454d0ee4-06ad-11e8-9bdc-6fbe0c41c5eb.png)


Please suggest for the same.
Thanks.

Regards,
Varsha

**Comment by deltakosh** [comment]
Pinging @kcoley for this error
Can you provide a repro of the error on the playground?

**Comment by kcoley** [comment]
Hi @VarshaKamble159 !

The warnings should be expected since MultiMaterials are not yet implemented and StandardMaterials are partially completed but not fully supported in glTF.  Though I am curious as to why the methods are returning undefined.

**Comment by VarshaKamble159** [comment]
Hi @kcoley ,

Babylon file is getting converted to .gltf and .bin files.  Function is returning object including gltf+bin.

With latest version i am able to load texture as well. But applied texture is not correct. 
Created the new issue [#3678](https://github.com/BabylonJS/Babylon.js/issues/3678) for the same.

Thanks.

Regards,
Varsha
