### ISSUE TITLE
[Feature requests][Inspector] some ideas to enhance the tool

### ISSUE THREAD

**Issue by Vinc3r** [BabylonJS/Babylon.js#3659]
Hi guys, after few days using the inspector (nice tool by the way), here some ideas to (maybe?) enhance it:

- [x] when showing colors values, clamp to 3 decimals (when tweaking colors, that's quite enough, and this will be a way more convenient to use and view)
- [x] add a *filter by name* field for properties ([example](https://i.imgur.com/soreJEw.png))
-  [x] option to show colors as hex instead as rgb (sometimes more convenient)
- [x] make bigger the square color button to launch the color picker (I have often to mass-clicking in a random way around this button to hope opening it)

**Comment by deltakosh** [comment]
Only good ideas :)
Validated!

Fancy trying to do it?

**Comment by Jaskar** [comment]
Hi @Vinc3r ,

I'm on it :)

Color values are only showing 2 decimals actually. Can you tell me where you see more please ?

**Comment by Vinc3r** [comment]
Nice!
I was talking about values next to the color picker: [screenshot](https://i.imgur.com/T40E9sO.png)

**Comment by Jaskar** [comment]
Got it, thanks!
https://github.com/BabylonJS/Babylon.js/pull/3700  :)

**Comment by Vinc3r** [comment]
Thanks to you! :)

**Comment by Bloadrick** [comment]
Hi,

I made the improvements for the inspector : https://github.com/BabylonJS/Babylon.js/pull/3810 :)

**Comment by Vinc3r** [comment]
I think this issue can be closed isn't it?

**Comment by deltakosh** [comment]
Right :)
