### ISSUE TITLE
Conflicting use of Tmp.Vector3 in SolidParticleSystem

### ISSUE THREAD

**Issue by a-carvallo** [BabylonJS/Babylon.js#3660]
Hello,

I think I found a little conflict with the use of the `Tmp.Vector3` array in `SolidParticleSystem`, it messes with the bounding box's minimum  of the mesh built from the SPS, here is an example : 

https://www.babylonjs-playground.com/#3GWJFE

Moving the mouse over the canvas leads to calling the `Ray`'s `update` function which uses `Tmp.Vector3[0]` and overwrites it, also overwriting the SPS's `_minimum` property 😕 

There could be other conflicts beside that one, not sure, but I think using its own `Vector3` instance for this property might be better (use `Tmp` variables inside limited scopes rather than properties that tend to stay in use for a long time).

(This is kind of the same thing as #1221)

Also, nice work on the latest version, the `FramingBehavior` is quite sweet! (except when the bounding box you want to zoom on keeps changing whenever you move 😛 )

**Comment by deltakosh** [comment]
Pinging @jbousquie

**Comment by a-carvallo** [comment]
It looks fixed so far with #3667 (tested on 3.2.0 alpha7).

Thanks @jbousquie
