### ISSUE TITLE
animatable.goToFrame bug when animatable.speedRatio is !== 1

### ISSUE THREAD

**Issue by maxime1992** [BabylonJS/Babylon.js#3672]
Hi,

First of all, I'm new to `Babylon.js` and `WebGL` in general. So I might be wrong or missing something here :angel: 

I do have a simulation running with Babylon and within the "player" I can select the exact time I want to go to by clicking on a "timeline".

It works great! But the thing is, if the `animatable.speedRatio` is different than 1, it's going to a (random?) wrong time.

I've just added a simple `console.log` before calling `animatable.goToFrame`:
No matter what's the current speed ratio, if I click at the same spot, it's calling `animatable.goToFrame` with the same (good) value.

Here's why I believe it's a bug from Babylon.js and not the app.

**Comment by deltakosh** [comment]
Hey!
can you repro the issue in the Playground?

**Comment by maxime1992** [comment]
Hi, I don't think for 2 reasons:

- I just arrived in a big project using Babylon.js and I've never used it before so I don't feel comfortable with it yet
- I won't have the time at home as I have many other things to repro/contribute ¯\_(ツ)_/¯ 

If there anything I forgot to mention or if you have any further questions, I'd be happy to answer :+1:

**Comment by deltakosh** [comment]
Unfortunately without a repro I can't fix it

**Comment by zakhenry** [comment]
@deltakosh I've had a go at a repro, and I believe this covers it:

https://www.babylonjs-playground.com/#JYIUDS#1

I'm not convinced that the speed ratio is actually at fault, as there appears to be an issue even when not changing the speed ratio

**Comment by deltakosh** [comment]
Will check it asap!
Thanks a lot
