### ISSUE TITLE
Very strange behavior

### ISSUE THREAD

**Issue by Luummii** [BabylonJS/Babylon.js#3679]
see here - http://www.html5gamedevs.com/topic/35401-very-strange-behavior/

**Comment by RaananW** [comment]
As written in the forum, the physics engine needs a bit more to work with :) https://www.babylonjs-playground.com/#BXII#27
0.35 is simply too small for collisions against a flat ground. you can use a box, and then it works - https://www.babylonjs-playground.com/#BXII#28
