### ISSUE TITLE
Camera switching broken when using multiple active cameras

### ISSUE THREAD

**Issue by jasonayre** [BabylonJS/Babylon.js#3688]
Expected behavior: when using multiple scene.activeCameras, and switching the scene.activeCamera, scene.activeCamera should switch

Actual behavior: activeCamera never gets updated, as if it's being overridden in the render loop (because neither scene.activeCamera = camera1 or scene.switchActiveCamera(camera1) seem to be working correctly as far as I can tell)

https://playground.babylonjs.com/#9BWDBU#1

(steps to reproduce behavior I am seeing commented in the playground code)

(additionally, multicam gunsight demo is broken, presumably due to same issue) https://www.babylonjs-playground.com/index.html#2GXKNW#18

**Comment by deltakosh** [comment]
Hello please use the forum for question :)
Nevertheless, the activeCameras will overwrite activeCamera.

When they are activeCameras, the engine will render them one by one (And will ignore activeCamera property)

**Comment by deltakosh** [comment]
No worry. I did not create this demo. Where does it come from ?

**Comment by jasonayre** [comment]
It's the main example given for how to set up a multi camera scene in the docs

https://doc.babylonjs.com/how_to/layermasks_and_multi-cam_textures

**Comment by deltakosh** [comment]
I'll fix that:)
Here is an example demonstrating the feature in the meantime: http://www.babylonjs.com/demos/defaultrenderingpipeline/

**Comment by deltakosh** [comment]
Fixed :)
thanks a lot!
