### ISSUE TITLE
Check if Video dome works in VR mode

### ISSUE THREAD

**Issue by deltakosh** [BabylonJS/Babylon.js#3692]
- [x] WMR
- [x] HTC Vive

**Comment by TrevorDev** [comment]
Vive works but the video in docs here http://doc.babylonjs.com/how_to/360videodome did not seem to load so I used https://www.babylonjs-playground.com/#1E9JQ8#8 to get it working

**Comment by deltakosh** [comment]
The video from Doc should work

**Comment by TrevorDev** [comment]
Oh, you are right, that file was just too large for my slow internet took about 45 seconds to load.

**Comment by deltakosh** [comment]
Cool so it worked on vive?

**Comment by deltakosh** [comment]
OK good to know

**Comment by TrevorDev** [comment]
Works on WMR as well 👍
