### ISSUE TITLE
Raise isDisposed from AbstractMesh class to Node class

### ISSUE THREAD

**Issue by SvenFrankson** [BabylonJS/Babylon.js#3698]
Hi, 

The **isDisposed()** public method (and the **_isDisposed** private property) is declared in the **AbstractMesh** class.

Considering the public method **dispose()** can be called on any **Node** instance, is there a reason not to move **isDisposed()** at the **Node** class level ?

Thanks !

**Comment by deltakosh** [comment]
No problem:)

**Comment by SvenFrankson** [comment]
Thanks a lot !
