### ISSUE TITLE
3dsmax exporter 0.36.0 for 3ds Max 2018 not working on 3ds max 2018.4 update

### ISSUE THREAD

**Issue by MINT1TINM** [BabylonJS/Babylon.js#3699]

**Comment by deltakosh** [comment]
Is it crashing? Or don't you see it at all? Was it working before?

**Comment by deltakosh** [comment]
Please open it with more info on the right repo: 
https://github.com/BabylonJS/Exporters

**Comment by MINT1TINM** [comment]
I'm sure i've installed the right version correctly, but i didn't see babylon menu in my 3ds max.

**Comment by deltakosh** [comment]
Someone reported that you may need to wipe your 3dsmax configuration to make it appears

**Comment by deltakosh** [comment]
See here : https://github.com/BabylonJS/Exporters/issues/75

**Comment by MINT1TINM** [comment]
Not work for me, but thank you

**Comment by deltakosh** [comment]
We did a new fix. Can you try using the latest version of the exporter?

**Comment by Jaskar** [comment]
Hi @MINT1TINM , is it ok for you ?
If not, please ping me or @noalak :)

**Comment by MINT1TINM** [comment]
It works greatly now, sorry for the delayed feedback 👍
