### ISSUE TITLE
Highlight layer visual bug in 3.2

### ISSUE THREAD

**Issue by deltakosh** [BabylonJS/Babylon.js#3709]
https://www.babylonjs-playground.com/#1WROZH#21
Reported here: http://www.html5gamedevs.com/topic/34712-changes-in-layermasks-and-edgesrenderer/?tab=comments#comment-203623

**Comment by sebavan** [comment]
Alpha Blending mode has been set to an invalid value (0 means disabling alpha) so only displays the highlights.

Removing the invalid setup fixes it: https://www.babylonjs-playground.com/#1WROZH#25
