### ISSUE TITLE
Particle doesn't stop

### ISSUE THREAD

**Issue by valentinbdv** [BabylonJS/Babylon.js#3710]
I don't undestand why the updateFunction of my particle system is still called after I stop the system.
See console in this playground : https://www.babylonjs-playground.com/#DJVT90
I stop the particle system after a 1 second timeout and the console show that the updateFunction is still called.
Thanks, Pichou

**Comment by deltakosh** [comment]
This is not a bug actually.
The updateFunction will be called until all particles are dead. In your case the updateFunction does not kill particles so the system will keep calling  update

Stopping a system ensures that no more new particles will be emitted
