### ISSUE TITLE
Animations are getting removed after serializing

### ISSUE THREAD

**Issue by VarshaKamble159** [BabylonJS/Babylon.js#3721]
Hi,

I am using one babylon file which has auto animation enabled. If i serialize it , the auto animation part gets removed but mesh animations exists. 

Also i am exporting this model to GLTF. The exported GLTF model does not contain any mesh animation.

Attaching babylon model before and after serialization .
[after.zip](https://github.com/BabylonJS/Babylon.js/files/1705967/after.zip)
[before.zip](https://github.com/BabylonJS/Babylon.js/files/1705968/before.zip)

Following are the babylon versions used:
`        "babylonjs": "^3.2.0-alpha7",
        "babylonjs-serializers": "^3.2.0-alpha7",
`

Please suggest for the same.

Thanks,
Varsha

**Comment by kcoley** [comment]
Hi @VarshaKamble159 .  Unfortunately, I have not implemented animation export for the glTF exporter yet, though it is on the roadmap.  You can track the feature updates here: #3601.  
Thanks for using the glTF serializer and please keep me updated on any other issues you run into!
