### ISSUE TITLE
Error while exporting to GLTF

### ISSUE THREAD

**Issue by VarshaKamble159** [BabylonJS/Babylon.js#3722]
Hi,

I am using one .babylon model. While exporting it to GLTF, i am getting following  error.

`
 ERROR TypeError: Cannot read property 'length' of undefined
    at r.setPrimitiveAttributes (babylonjs.serializers.min.js:1)
    at r.createScene (babylonjs.serializers.min.js:1)
    at new r (babylonjs.serializers.min.js:1)
    at Function.t.GLTF (babylonjs.serializers.min.js:1)
`

![error](https://user-images.githubusercontent.com/9550268/35959470-cd682a38-0ccb-11e8-9c7f-60dd8088e2b6.png)

Other link from the error log is pointing to the following line of my code.
`
  let returnData = SERIALIZERS.GLTF2Export.GLTF(this._scene, filename);
`

Attaching model for your reference.
[ge_anim_issue.zip](https://github.com/BabylonJS/Babylon.js/files/1705999/ge_anim_issue.zip)

Following are the babylon versions used:
`        "babylonjs": "^3.2.0-alpha7",
        "babylonjs-serializers": "^3.2.0-alpha7",
`

Kindly, suggest for the same.
Thanks.

Regards,
Varsha

**Comment by kcoley** [comment]
Thanks for flagging @VarshaKamble159.  I'll look into this.

**Comment by kcoley** [comment]
@VarshaKamble159, we recently merged a fix for this.  I was not handling children properly in Babylon when exporting to glTF, so it should work now.  You can give it a go and reopen if this is still an issue.

**Comment by VarshaKamble159** [comment]
@kcoley ,

 I updated babylon dependency. Now its pointing to following version.
` "babylonjs": "^3.2.0-alpha8", "babylonjs-serializers": "^3.2.0-alpha8"`

But still i am getting same error.
![err](https://user-images.githubusercontent.com/9550268/36417141-20829af8-1651-11e8-8890-762e45d6159c.png)

Kindly check for the same.

Thanks,
Varsha
