### ISSUE TITLE
[Feature request][Playground] Ability to know how many versions of a scene exists

### ISSUE THREAD

**Issue by Vinc3r** [BabylonJS/Babylon.js#3723]
I don't know if it's even possible, but what do you think to add a little menu to navigate between different versions of a playground scene ?

We can imagine something like that:
![playground version menu](https://i.imgur.com/6Mauhnm.png)

This can be usefull to user for example by alllowing him to quickly go to the last version of an old scene linked in an old forum thread, to see if the code was updated. Same thing for the playground links.

What do you think about that idea?

[edit] note that I've update the button "Version: latest" to avoid confusion.

**Comment by deltakosh** [comment]
The main problem is that there is no guarantee that versions are related. You can change everything between versions

**Comment by Vinc3r** [comment]
Yes, but is it really annoying? The user will probably notice if something is wrong between versions.

But indeed, maybe this is not a valuable idea, 'cause user always can increment manually the anchor value.

I close this request.
