### ISSUE TITLE
LoadAssetContainer bug

### ISSUE THREAD

**Issue by deltakosh** [BabylonJS/Babylon.js#3725]
http://www.html5gamedevs.com/topic/35580-sceneloaderloadassetcontainer/

**Comment by TrevorDev** [comment]
Smaller repro https://playground.babylonjs.com/#JTENJ0#1 seems to be mismatch between meshes added to the scene and what importMesh is currently returning when using gltfLoader.

**Comment by bghgary** [comment]
This is a bug in the glTF loader. I'll take it.
