### ISSUE TITLE
The firematerial's opacity texture looks bugged

### ISSUE THREAD

**Issue by adergham** [BabylonJS/Babylon.js#3727]
Hello!

The firematerial is not  transparent anymore: the black parts of the opacity texture are displayed black instead of transparent.
This is seen in version 3.2.0-alpha7:

https://www.babylonjs-playground.com/index.html#21IIM9#29

**Comment by julien-moreau** [comment]
Will check ASAP! :)

**Comment by julien-moreau** [comment]
Just fixed here! https://github.com/BabylonJS/Babylon.js/commit/829f75af6d617b7bf3e4ef7acf6c68e581ab9569

**Comment by deltakosh** [comment]
Thanks a lot
