### ISSUE TITLE
Add Oimo as a package reference

### ISSUE THREAD

**Issue by mwpowellhtx** [BabylonJS/Babylon.js#3729]
Currently [Oimo](http://www.npmjs.com/package/oimo) is included as a static file but it really should be a [package dependency](http://github.com/BabylonJS/Babylon.js/blob/0f5eb467e1f73bc6fe27a2d7d3fefab28990bb1d/package.json#L36) in the appropriate version. This was discussed at some length [previously](http://github.com/BabylonJS/Babylon.js/issues/3593#issuecomment-359101567).

There may be similar such [dependencies](http://github.com/BabylonJS/Babylon.js/blob/2524a6d34a798e1f830a70c5a2a2ffc84908c351/bower.json), such as [poly2tri](https://www.npmjs.com/package/poly2tri).

**Comment by RaananW** [comment]
Thanks for the suggestion.
The oimo version we are using cannot be found on npm. This is the reason we are providing it as part of the repository. Cannon, for example, is added as an external dependency.
I agree about poly2tri. I will discuss this with the team and see if we can take it out in 3.2, or if there is any reason I am not seeing for not doing that.

**Comment by RaananW** [comment]
hey, I am closing this and moving to the new issue - https://github.com/BabylonJS/Babylon.js/issues/3730

**Comment by mwpowellhtx** [comment]
@RaananW So there's nothing that can be done to merge paths with the ``Oimo`` migration path? I'm not sure I use ``Oimo``, yet, but I'm more concerned with correctness of package dependencies.

**Comment by RaananW** [comment]
We will migrate to the current production version (1.0.9) which will solve the dependency problem. Then we will have oimo as a dependency, like cannon.
