### ISSUE TITLE
Object instances causes original object freeze on movement

### ISSUE THREAD

**Issue by DaviisLV** [BabylonJS/Babylon.js#3731]
- Context: I have a scene with two meshes- a **Template** and an **Instance** of it. I can attach an any of them to camera as a child and walk around.

- Expectation: No matter which mesh is added to the camera, it should always remain just in front of the camera while moving around.

- Result: When Instance is added to camera, everything works as expected. 
![80f9f485c1776c7087e96fc287d4062d](https://user-images.githubusercontent.com/19565602/36026298-17f48780-0d9f-11e8-8bff-856eee9057d9.gif)

- Bug: When  **Template** is added to camera, the mesh stops moving as soon as the **Instance** is outside of the viewport. It resumes moving when the Instance is back in the viewport. 
![040124a02374af7e9fdf46fe03b6b11a](https://user-images.githubusercontent.com/19565602/36026224-d16e4b48-0d9e-11e8-9027-a4998ef1982c.gif)

You can see it here: http://playground.babylonjs.com/#Z7GQ5Y#1

**Comment by deltakosh** [comment]
Thanks a lot  I'll check it asap
