### ISSUE TITLE
No onTouchpadButtonStateChangedObservable when reading controller's touchpad value

### ISSUE THREAD

**Issue by deltakosh** [BabylonJS/Babylon.js#3734]
http://www.html5gamedevs.com/topic/35560-reading-controllers-touchpad-value/?tab=comments#comment-204187

**Comment by deltakosh** [comment]
http://playground.babylonjs.com/#M5XR49%236

**Comment by TrevorDev** [comment]
It looks like everything is working as expected to me when I modified the PG to the following:
http://localhost:1338/Playground/index-local.html#M5XR49#16

"However, the onTouchpadButtonStateChangedObservable is still returning zero for the value btw. Is this actually expected ?"
I believe so. I think the value field maps to the pressed boolean on the button state. There is another boolean on the the state called touched which can be used to check for when it gets touched.
