### ISSUE TITLE
VLS does not work when using VR mode

### ISSUE THREAD

**Issue by deltakosh** [BabylonJS/Babylon.js#3743]
- [x] Bug repro on [playground](https://playground.babylonjs.com): https://www.babylonjs-playground.com/#6ZRJP9#1
- [x] Expected result: VLS should be visible
- [x] Current result: VLS are not rendered

**Comment by julien-moreau** [comment]
@deltakosh or @RaananW, it looks like the VRDeviceOrientationArcRotateCamera doesn't renders the custom render targets.

(hre: https://github.com/BabylonJS/Babylon.js/blob/master/src/PostProcess/babylon.volumetricLightScatteringPostProcess.ts#L257) If I replace camera.customRenderTargets.push(this._volumetricLightScatteringRTT); to scene.customRenderTargets.push(this._volumetricLightScatteringRTT); the internal render target is rendered. Any idea from our VR specialist? :)

**Comment by deltakosh** [comment]
I'll have a look asap

**Comment by julien-moreau** [comment]
Thanks!

**Comment by julien-moreau** [comment]
Thank you @deltakosh!
