### ISSUE TITLE
Viewer support for VueJS?

### ISSUE THREAD

**Issue by dtrinh100** [BabylonJS/Babylon.js#3779]
I really like Babylon and would like to use it on a future website, but I will be using the Vue framework. Will there be support for the Viewer in Vue (I know there will be one for Angular and React)? :)

**Comment by deltakosh** [comment]
Not for now but can you evaluate the work to do?

Cc @raananw

**Comment by RaananW** [comment]
We didn't plan on shipping a vue-compatible viewer, but let's keep it open and see

**Comment by veikkoeeva** [comment]
~I'll record on the same token http://aurelia.io/ here. I'm not sure if it should be a separate issue or perhaps the headline altered. Also, I'm not sure what this would require (but maybe I eventually find out).~ Scrap that, my search failed big time. I found the other issues, created https://github.com/BabylonJS/Babylon.js/issues/3824.

**Comment by deltakosh** [comment]
Moved to https://github.com/BabylonJS/Babylon.js/projects/6
