### ISSUE TITLE
DepthRenderer is delayed in 3.1

### ISSUE THREAD

**Issue by PierreLeBlond** [BabylonJS/Babylon.js#3787]
Hi all !

Since 3.1, there's a visual issue related to the depth renderer :
The depth map seems to be late by one frame, which result in delayed shadows when shaking
the camera.
This can be seen in the soft shadow [playground](https://www.babylonjs-playground.com/#IIZ9UU), though it is barely noticeable.
If the bug isn't too obvious to you, I'll set a playground where it's more noticeable.

I'll keep investigating a bit, but if you guys know where it could come from, it would spare me some headaches.

**Comment by sebavan** [comment]
Hello @PierreLeBlond ,

The Shadow Generator does not rely on the depth renderer but only on render target textures. I will investigate the issue on my side but would really appreciate if you could create a repro ???

Thx

**Comment by PierreLeBlond** [comment]
Hey,

Yeah sorry, I was referencing to the depth renderer because that's how I first saw the issue; when I pre-calculate some shadows using the depth renderer, or when I use our own SSAO implementation.

I'm able to clearly see the issue when I just render the depth map via the depth renderer, and then mix the result with the final fragment color from the lighting step. Here the delay between the depth and the corresponding pixel color is obvious.

When camera is moving rapidly :
![selection_024](https://user-images.githubusercontent.com/6840047/36438145-44b25324-1669-11e8-8897-22511f2af571.png)

When camera is still :
![selection_025](https://user-images.githubusercontent.com/6840047/36438148-46b2c6c2-1669-11e8-9b20-bd2bd2b39ceb.png)

I already saw this kind of artifact when the depth map is being add to the end of the scene.customRenderTargets, but here I make sure it is always rendered first.
I also make sure that before bjs 3.1 release there is no such artifact.

I'll try to reproduce it in a playground, just need to set the right scene.

Thx !

**Comment by sebavan** [comment]
@PierreLeBlond I can not see anything obvious, I will then wait for your repro.

**Comment by PierreLeBlond** [comment]
Here it is :
https://www.babylonjs-playground.com/#005S3E

**Comment by sebavan** [comment]
Thanks for the repro it is perfect to troubleshoot, I ll let you know ASAP

**Comment by PierreLeBlond** [comment]
Thanks !
You guys rocks :)
