### ISSUE TITLE
Animations are not working when animation is attached to individual object of a animation group.

### ISSUE THREAD

**Issue by ravip** [BabylonJS/Babylon.js#3788]
Individual and group animations are working properly. However when there is animation attached to individual object of a animation group, animations are not working. Below are the two scenarios demonstrated using playground. 

----------------
**Working Scenario**
Individual object animations are working fine
1. Load the Playground (http://www.babylonjs-playground.com/#6MZV8R#86)
2. Zoom out the playground scene, 3D model will get displayed
3. Rotate the model 180 degrees
4. Click on the sphere

Result:
Drawer animation will get played

More info:
Animated Mesh present in model
Drawer_1

--------------

**Non-working Scenario or Bug**:
When animation is available for individual object in animation group then its dosn't work
1. Load the Playground (http://www.babylonjs-playground.com/#6MZV8R#86)
2. Zoom out the playground scene, 3D model will get displayed
3. Rotate the model 180 degrees
4. Click on the sphere

Actual Result:
Animations are not played properly

Expected Result:
Animations should played properly 
Below playground autoplay all the animations from animated meshes
http://www.babylonjs-playground.com/#6MZV8R#88

More Info:
Animated Meshes present in model:
Bellow_part_3
Bellow_part_4
Bellow_part_5
pasted__Bellows_Part_1
pasted__Bellows_Part_2
pasted__Bellows_Part_6

----------------

**Comment by deltakosh** [comment]
Sorry but I have hard time understanding the issue.
You launch animations on "drawer1" on your Playground (http://www.babylonjs-playground.com/#6MZV8R#86) and I clearly see the drawer animating so what is not expected?

**Comment by ravip** [comment]
Oh...My Mistake. Please use below playground to see issue - non working scenario

http://www.babylonjs-playground.com/#6MZV8R#87

**Comment by deltakosh** [comment]
Oh ok :)
and how the gltf is produced?

**Comment by ravip** [comment]
This issue is with .Babylon file. Used 3ds Max babylon exporter.

**Comment by deltakosh** [comment]
I'll check

**Comment by ravip** [comment]
Great! In case you would like to have corresponding .fbx, kindly let me know.

**Comment by deltakosh** [comment]
So I've checked your data and the object you try to animate has its animation from key 360 to 1000
here is a working PG:
http://www.babylonjs-playground.com/#6MZV8R#89

**Comment by ravip** [comment]
@deltakosh Thanks a lot. Its working properly.

Could you please provide me details how did you got to know details about exact animation key frames, so that I can debug and resolve similar issues at my end in future.

**Comment by deltakosh** [comment]
Sure thing!
I dumped the content of mesh.animations[0].keys
it contains the data and time frame

**Comment by ravip** [comment]
@deltakosh  Thanks a lot for the support. I appreciate the way you communicates :)

**Comment by deltakosh** [comment]
My pleasure :)
