### ISSUE TITLE
Dome.dispose does not remove the video 360 dome from scene

### ISSUE THREAD

**Issue by hololite** [BabylonJS/Babylon.js#3792]
Here is the PG
https://www.babylonjs-playground.com/#4LT5TC#7

Hit the canvas with key 'd' to dispose, see the console log for confirmation.
The dome is still there even after dome.dispose() has been called.

**Comment by deltakosh** [comment]
Thanks I'll make sure to fix it asap

**Comment by hololite** [comment]
Thanks!!
