### ISSUE TITLE
Bad performance on some iPads

### ISSUE THREAD

**Issue by afaenger** [BabylonJS/Babylon.js#3793]
The performance is really bad with my own test scenes on iPad Air 2 since this [commit ](https://github.com/BabylonJS/Babylon.js/blob/a3164f850ae818ab7f0a22cdbc7beaaad79e659a/dist/preview%20release/babylon.max.js) (Dec 14, 2017).
The root cause is the same as in issue #3542 and the workaround is identical:
engine.disableTextureBindingOptimization=true

Maybe this can be added to the exception list similar to the Macintosh entry.

**Comment by deltakosh** [comment]
Sure thing! will be in next commit
