### ISSUE TITLE
Is it possible to add time and add sorts to result set entries in playground?

### ISSUE THREAD

**Issue by bitores** [BabylonJS/Babylon.js#3808]
For learning and ease of use, is it possible to add time and add ordering to a resultset entry in playground?

**Comment by deltakosh** [comment]
Do you mean in the Doc.babylonjs.com?

**Comment by bitores** [comment]
http://doc.babylonjs.com/playground  @deltakosh

**Comment by deltakosh** [comment]
Unfortunately we do not store the creation date:(
