### ISSUE TITLE
Albedo Color / Base color of the material not getting serialized properly from .babylon to GLTF

### ISSUE THREAD

**Issue by ravip** [BabylonJS/Babylon.js#3809]
Albedo Color (Base color) of the material for model is became black when serialized .babylon to .gltf (.gltf+.bin+texture)

1. Used below .babylon model
[model_in_the_form_of_babylon.zip](https://github.com/BabylonJS/Babylon.js/files/1751101/model_in_the_form_of_babylon.zip)

2. Serialized it to .gltf and got below .gltf model
[model_in_the_form_of_gltf.zip](https://github.com/BabylonJS/Babylon.js/files/1751103/model_in_the_form_of_gltf.zip)

3. Code used to export .babylon to .gltf
let returnData = SERIALIZERS.GLTF2Export.GLTF(this._scene, finalPath);

Expected Result: 
The Albedo Color / Base color for material should be serialized properly in .gltf

Actual Result:
The Albedo Color / Base color for material became black

More information:
Tested .babylon and .gltf with sandbox and below images shows the difference.
![babylon_model_tested_with_sandbox](https://user-images.githubusercontent.com/714971/36586916-7bb88a9a-18a9-11e8-8ec1-3a3cc7e028d0.JPG)

![serialized_gltf_model_tested_with_sandbox](https://user-images.githubusercontent.com/714971/36586922-8047085c-18a9-11e8-9d69-6f115a5442ef.JPG)

**Comment by kcoley** [comment]
Hi @ravip.  Thanks for putting this information together!  I'll take a look at this.

**Comment by kcoley** [comment]
@ravip, I missed the emissive color parameter during standard material conversion.  You can try the conversion again.  Thanks for flagging this issue!

**Comment by ravip** [comment]
@kcoley wow, you guys are awesome. Thanks for so quick turn around time. Which alpha version this will get released?

**Comment by ravip** [comment]
@kcoley wow, you guys are awesome. Thanks for so quick turn around time. Which alpha version this will get released?

**Comment by ravip** [comment]
@kcoley wow, you guys are awesome. Thanks for so quick turn around time. Which alpha version this will get released?

**Comment by deltakosh** [comment]
Next one is aimed for Tuesday

**Comment by ravip** [comment]
@deltakosh @kcoley  Looks like it still reproducible. I have tested it with 3.2.0-alphaB.

**Comment by kcoley** [comment]
Hi @ravip .  The fix should have already be committed, but I can try to check the npm package to see if it's there.

**Comment by kcoley** [comment]
Hi @ravip , sorry, finally got a chance to test this.  I was able to export the model with the correct emissive values from 3.2.0-alphaB
```
+ babylonjs@3.2.0-alphaB
+ babylonjs-serializers@3.2.0-alphaB
```
Below is the generated glb file.  
[test.zip](https://github.com/BabylonJS/Babylon.js/files/1777158/test.zip)

Is this file what you are expecting or was there something else you had in mind?

**Comment by ravip** [comment]
@kcoley @deltakosh Verified again. Its working fine. Thanks a lot.

**Comment by ravip** [comment]
@deltakosh @kcoley 

Here are the revised observations -

The serialized gltf is displayed properly on Babylon Sandbox but its not getting displayed properly on other GLTF Viewers like "Windows Mixed Reality Viewer". The Red blocks are still displayed as black on "Windows Mixed Reality Viewer"

Here is the required Attachments:
**GLTF Bundle:**
[ge_gltf.zip](https://github.com/BabylonJS/Babylon.js/files/1793321/ge_gltf.zip)

**Windows  Mixed Reality Viewer's display:**
![windows_mixed_reality_viewer](https://user-images.githubusercontent.com/714971/37153814-ebdff010-2303-11e8-9172-65e05e15be05.png)

**Babylon Sandbox display:**
![babylon_sandbox_display](https://user-images.githubusercontent.com/714971/37153838-0223ef5c-2304-11e8-81e2-0230d977dc65.png)

**Comment by deltakosh** [comment]
Let me check with MRV folks :)

**Comment by deltakosh** [comment]
Did you try the file in the gltf validator?

**Comment by cwelman** [comment]
Regarding this issue in MRV:  there is a bug logged and a fix in progress for this.
Thanks for the report - much appreciated!
