### ISSUE TITLE
Camera Bugs with position.y

### ISSUE THREAD

**Issue by somarlyonks** [BabylonJS/Babylon.js#3818]
# Bugs

- Bug repro on [playground](https://www.babylonjs-playground.com/#1AU0M4#5)
  - LINE15 & LINE98
  - VERSION: LATEST

## LINE15--ArcRotateCamera - position

- Expected result: I was going to create an ArcRotateCamera at `Vector3(0, -150, 0)`
- Current result: It only works if the Vector3.x is not Zero, so I have to change it to `Vector3(1, -150, 0)` and it works.

## LINE98--FreeCamera or UniversalCamera - mouse inputs

-The FreeCamera at `Vector3(0, -150, 0)` couldn't response to the mouse inputs properly.
- You may change the current active camera by editing LINE98 and try other cameras and find them working properly, so I supposed it might be a bug?

**Comment by deltakosh** [comment]
This is a known limitation of perspective cameras
Both issues can be fixed by setting x or z to a really small value like 0.0001.

**Comment by somarlyonks** [comment]
Thanks. That's close to my guess. I'll close the issue.
