### ISSUE TITLE
scene.workerCollisions doesn't work with mesh instances

### ISSUE THREAD

**Issue by vujadin** [BabylonJS/Babylon.js#3819]
- Bug repro on http://playground.babylonjs.com/#8007QV   (uncomment line 4 to see the problem)
- Expected result:   it should work like with scene.workerCollisions = false;
- Current result:   runtime error - Cannot read property 'geometry' of undefined

does worker starts too early (before mesh instances are created) as instance.sourceMesh is null ??

**Comment by RaananW** [comment]
No collision workers are available on the playground (to use the workers you will need to use the babylon.workers file in the dist repo). There was also a bug concerning the way the worker is getting the geometry of instances, which was fixed as well.
So, the fallback to workerCollisions in the playground is the regular collisions system.
