### ISSUE TITLE
postMessage call in WebWorker is wrong

### ISSUE THREAD

**Issue by RaananW** [BabylonJS/Babylon.js#3822]
See - http://www.html5gamedevs.com/topic/35924-webworker-error/
postMessage signature in web workers is different than the one in Window.
Since Typescript doesn't knwo the contect the collision worker will be executed in, it assumes "self===window", thus forcing the Window signature.
postMessage therefore doesn't work on certain browsers that check what the 2nd variable provided is (which, at the moment, is an empty string).

**Comment by cecilemuller** [comment]
Incompatible postMessage is unfortunately a recurring limitation of Typescript at the moment, I wish it was possible to opt-in to built-in libs (like "dom" and "webworker") per file like you can with thirdparty types.

The "clean" solution is to separate code that expects the webworker context from the code that expects dom context and use multiple tsconfig files, which brings a lot of complexity as tools don't expect multiple tsconfigs in a single project.

The pragmatic solution is to keep a single tsconfig and just add `//@ts-ignore` before the postMessage call in the webworker code :/
