### ISSUE TITLE
Babylon.js uses deprecated WebRTC functionality that fails on Firefox and Edge

### ISSUE THREAD

**Issue by veikkoeeva** [BabylonJS/Babylon.js#3825]
- Bug repro on [https://www.babylonjs-playground.com/#1R77YT#2](https://www.babylonjs-playground.com/#1R77YT#2).
- Expected result: The playground works and show the camera feed overlayed with ASCII art.
- Current result: Black box is shown on Firefox (also nightly) and Edge, only Chrome (latest) seem to function.

It appears the code uses deprecated features, which Firefox calls out. Edge fails with the mention "not found". The following is a screenshot from Firefox developer tools:
![deprecated](https://user-images.githubusercontent.com/5158694/36685580-6853e3c0-1b2c-11e8-9573-72e512bbfc40.png)

Using search, it appears this function (and functionality) is found in a few places: https://github.com/BabylonJS/Babylon.js/search?q=mozGetUserMedia&type=Code&utf8=%E2%9C%93. The way to fix could be something along these lines: https://github.com/webrtc/adapter/issues/772#issuecomment-364425723.

**Comment by sebavan** [comment]
Fixed and deployed.
