### ISSUE TITLE
Modifying  advancedTexture.renderscale resizes texture but breaks interactions with GUI

### ISSUE THREAD

**Issue by TrevorDev** [BabylonJS/Babylon.js#3826]
# Bugs

- Bug repro on [playground](http://playground.babylonjs.com/#Y3C0HQ#17):
- Expected result:
Gui checkbox to be enabled and disabled when clicked
- Current result:
The hitbox for the checkbox is somewhere else on the screen and does not match rendering. If renderScale is set back to 1 it works as expected.

**Comment by deltakosh** [comment]
On it!
