### ISSUE TITLE
Removing babylon exporter files from 3ds max.

### ISSUE THREAD

**Issue by propiro** [BabylonJS/Babylon.js#3828]
Hello,
I've tried to remove the babylon exporter from max - simply by removing the .dll files copied from the zip. 3ds max now spawns errors on various maxscript files that look really unrelated to the exporter - anyway for clean uninstall of exporter files?

**Comment by deltakosh** [comment]
Is it for 3dsmax 2017? If so I believe there is a procedure to clean the user interface
btw there is a specific repo for the exporters: https://github.com/BabylonJS/Exporters

Closing this issue as this is beyond the scope of the exporter itself (but we can keep chattin ghere obviously)

**Comment by propiro** [comment]
Yes it is max 2017.
I'd be glad for any links for that cleaning procedure you've mentioned.

Thanks,
A.

**Comment by deltakosh** [comment]
You may find it here: http://doc.babylonjs.com/resources/3dsmax#extra-setup-for-3ds-max-2018

**Comment by Milincho** [comment]
How does one uninstall or clean up this pile of "Babylon attributes" from a scene? searching for "uninstall" in that documentation link shows "0 results". Searching for "cleaning" doesn't show any related help either.

**Comment by sebavan** [comment]
Using the installer you have an uninstall button https://doc.babylonjs.com/extensions/Exporters/Maya
