### ISSUE TITLE
ImportMesh callback gets called a split second after the mesh is loaded

### ISSUE THREAD

**Issue by haroldma** [BabylonJS/Babylon.js#3848]
This results in the mesh *always* appearing at position(0, 0, 0).

Before upgrading from alpha7 the callback immediately ranned. Meaning in the scene there was no room for the mesh to be in the middle of the scene, since the callback assigned it's parent.

Tested with both ImportMesh and ImportMeshAsync (on a .gltf).

**Comment by bghgary** [comment]
This is a side-effect of moving to using promises. Promises will always wait until the next frame before continuing. Not sure how to handle this one yet.

**Comment by deltakosh** [comment]
I agree this is an important point to tackle we have to make sure that import mesh does not break compatibility
importMeshAsync obviously can remain unchanged

**Comment by RaananW** [comment]
non-async methods will need to use either callbacks or synched promises, which are not A+ complient. The observers are also sync (unless notifiying with promise), so they are a good candidate as well.

**Comment by deltakosh** [comment]
@bghgary we have other problems surfacing due to this change (@davrous reported a breaking changes in his demo recently)
Do you mind prioritizing this fix?

**Comment by bghgary** [comment]
Will try. I have some other high priority fixes as well.

**Comment by bghgary** [comment]
@haroldma Do you have a playground with a repro? I want to make sure my fix works for you.

**Comment by bghgary** [comment]
> @bghgary we have other problems surfacing due to this change (@davrous reported a breaking changes in his demo recently)

FYI @davrous issue is not related this.

**Comment by deltakosh** [comment]
Is it loader related?

**Comment by bghgary** [comment]
Yes. The code that split the mesh per primitive is causing the problem. I think maybe I should make it such that the behavior of the loader is the same as before if there is only one primitive. Only do what I'm currently doing if there are more than one primitive. That should fix most cases. I'll do this separately though.

**Comment by deltakosh** [comment]
OK thanks:)

**Comment by haroldma** [comment]
@bghgary [here's](https://playground.babylonjs.com/#IL3L6Q) a repro of the issue.
