### ISSUE TITLE
Gui Lines do not work in VR.

### ISSUE THREAD

**Issue by sebavan** [BabylonJS/Babylon.js#3853]
Can be reproed here, Looking at Spector the lines are not in the dynamic texture:

https://www.babylonjs-playground.com/#W5SWE9#3

**Comment by TrevorDev** [comment]
After discussing this, this is by design. moveToVector3 expects the texture to be overlaid on the screen which is not the case when in VR. For scenarios like this using a line mesh will work to link objects in 3D space.

**Comment by deltakosh** [comment]
I dropped a note in the doc
