### ISSUE TITLE
mirrorTexture can't handle sprites

### ISSUE THREAD

**Issue by vujadin** [BabylonJS/Babylon.js#3872]
- Bug repro on https://www.babylonjs-playground.com/#HEJBM7
- Expected result: sprites should be reflected/rendered on mirrorTexture
- Current result: Uncaught TypeError: mesh.isReady is not a function

**Comment by deltakosh** [comment]
This is per design. The renderList can only contain meshes
Sprites are not mirrored as they are 2d objects.

But you can instead use planes with billboard mode. Example of billboard: https://www.babylonjs-playground.com/#0720FC#14
