### ISSUE TITLE
Add button mask support for gui (non-rectangular buttons)

### ISSUE THREAD

**Issue by Vorion86** [BabylonJS/Babylon.js#3897]
# Feature request

- Link to [forum](http://www.html5gamedevs.com/topic/36147-can-you-add-button-masks-for-non-rectangular-buttons/) discussion about the feature:
- It would be nice to be able to set a button mask for gui buttons, so we can have non-rectangular buttons, that will only be clickable (hover) on desired areas.
My idea for an implementation would be to create a bitmask of the image, where every pixel of the image has a true/false value for being clickable or not. The creation of the bitmask could use the alpha channel of the image for this. This way we would only need to get to current position of the mouse cursor on the image and check against the bitmask.
We could also allow to add an optional image, which will then be used for the creation of the bitmask, because a button can also have some transparency an the inside (a circle for example). 
I don't know how we could handle scaling of the image here, so it may not be the best idea for implementation, if the bitmask would have to be recreated every time the image is scaled.
Another idea would be to use Path2d to recreate the form of the clickable area, and check if the mouse cursor position is inside that area. Path2d data could also be loaded from an .svg file.
- Additional links that could help implementing the feature:
The godot engine (C++) uses this kind of implementation (bitmask), so maybe there's something useful there:
https://github.com/godotengine/godot/blob/master/scene/gui/texture_button.cpp
Path2D: https://www.rgraph.net/blog/an-example-of-html5-canvas-path2d-objects.html

**Comment by sebavan** [comment]
https://github.com/BabylonJS/Babylon.js/issues/4924

**Comment by matanliram** [comment]
Hey guys, I'm new to the project :)
I started looking at this issue a bit and saw that someone implemented **Image** attribute __detectPointerOnOpaqueOnly_. I've seen this property is not used anywhere in the project.

Which tests would you run to see if calling _getImageData_ every time the _contains_ method is called takes a reasonable amount of memory? (i.e. every mouse move)
Say the memory consumption in this case is considered too high, it's possible to:

1. Implement some timer that avoids calling _getImageData_ too frequently
2. Check the pixels only when screen rendering cache invalidation occurs. Button images usually don't change, so we'll check the pixels only on environment changes, resizes or camera changes.
3. I don't like this solution, but anyways: add handlers to practically anything that can change the button, resize, camera change, button image change, and only in these cases call getImageData

In all solutions we will save the bitmap array in the image/button instances.
Would you suggest other solutions? What do you think about these two?

**Comment by deltakosh** [comment]
It is used here: https://github.com/BabylonJS/Babylon.js/blob/e40ec8a91dd6ce98294c99a7cf74f17b1d406383/gui/src/2D/controls/image.ts#L437

For your question, I think it is reasonable to cache the image data to run your testing.

**Comment by matanliram** [comment]
This is the attribute implementation, so I didn't consider it a "use".
I'll look up on how and where to invalidate the image cache data and update if I have any further questions.
I'd maybe run some stress with ~100 buttons and artificial _contains_ events to see how the memory is handled.
Thanks 🙂

**Comment by deltakosh** [comment]
Sorry I misread your post

**Comment by deltakosh** [comment]
Closing as this does not seem to be a large ask

**Comment by Popov72** [comment]
Is this still needed?

It seems to me that `detectPointerOnOpaqueOnly` is doing the job and the `getImageData ` performance problem is addressed by #8661

**Comment by deltakosh** [comment]
TOtally agree. that's why I closed it in first hand. But I wanted your thoughts so all good
