### ISSUE TITLE
Trailing mesh for particles

### ISSUE THREAD

**Issue by deltakosh** [BabylonJS/Babylon.js#3900]
- ribbon based
- Tube based
- Life time based

**Comment by furcatomasz** [comment]
Is the task to do trail effect like that: https://blenderartists.org/uploads/default/original/4X/a/5/9/a5912d5cd1e5155611249f262a7cd53d8ffc1145.jpg ?

**Comment by deltakosh** [comment]
exactly sir!

**Comment by furcatomasz** [comment]
Is any ETA exists of this feature?

**Comment by danjpar** [comment]
This looks like a fun one to try.

I found this [Playground](https://www.babylonjs-playground.com/#1WM8Z7#2) from this [Thread](http://www.html5gamedevs.com/topic/12844-object-leaving-trail-and-babylonjs/)
The playground itself doesn't work, but if you copy and run the code locally, it works. I know it's not exactly what is sought, but I think it's pretty close to the idea.

This one might be over my head, though, but I'll try to do what I can.

Is this something that would accompany a particle system, attached to the emitter mesh, leaving a trail if the mesh moves? I imagine it would need to be able to be toggled/triggered.

**Comment by furcatomasz** [comment]
I achieve effect of trail mesh. Check it on my gif from my game: https://discourse-cdn-sjc2.com/standard10/uploads/babylonjs/optimized/1X/cb5ee0780d238bf07cc33da1a36c078d81bc582d_2_690x460.gif

**Comment by danjpar** [comment]
Would be awesome to see your code for that effect.

**Comment by furcatomasz** [comment]
https://github.com/furcatomasz/slavs/blob/master/TrailMesh.ts

**Comment by furcatomasz** [comment]
`
//Trailbox as parent of sword in my example
trailBox = BABYLON.Mesh.CreateBox('test', 1,scene, false);
this.trailMesh = new TrailMesh("Test", trailBox, scene, 0.2, 40);

//and if you want to animate run:
observer = scene.onBeforeRenderObservable.add(trailMesh.update);

**Comment by furcatomasz** [comment]
Did anyone try use trail mesh? :)

**Comment by deltakosh** [comment]
I like this API!!!

**Comment by danjpar** [comment]
Do you want me to work on a pull request for this using his code? 
Should I try to add it into an existing API or create a new file?
There are probably a few options that should be added to the constructor, like a material to use instead of white.

**Comment by deltakosh** [comment]
I think (but open to any suggestion) that the API mentioned earlier is fine so we should create a TrailMesh class (and file)

Let's do a PR and use it to discuss options

**Comment by danjpar** [comment]
[PR](https://github.com/BabylonJS/Babylon.js/pull/5828)

**Comment by deltakosh** [comment]
Thank to you!! congrats
