### ISSUE TITLE
[Feature] Allow RenderTextureTarget to have custom textureFormat

### ISSUE THREAD

**Issue by foemaverik** [BabylonJS/Babylon.js#3901]
Hello guys, 

It would be awesome if you could allow the developers to modify the textureFormat of a RenderTargetTexture.

# Feature request

- http://www.html5gamedevs.com/topic/36095-cant-change-the-textureformat-for-a-rendertargettexture/

Here's a list of texture formats supported by unity (just in case you want to add more)
https://docs.unity3d.com/ScriptReference/RenderTextureFormat.html

Cheers

**Comment by deltakosh** [comment]
really good idea! Will work on it as soon as possible

**Comment by deltakosh** [comment]
Unfortunately even if OpenGL can support it it is not supported by webgl:
https://groups.google.com/forum/#!topic/webgl-dev-list/ms21hnWk0tg

**Comment by deltakosh** [comment]
You can still create a raw luminance texture but you'll need to fill it manually
