### ISSUE TITLE
new PointerEvent() is not defined in firefox.

### ISSUE THREAD

**Issue by TrevorDev** [BabylonJS/Babylon.js#3916]
http://www.html5gamedevs.com/topic/36228-getting-exception-on-oncontrollermeshloadedobservable-callback-on-firefox/?tab=comments#comment-207685

Expected gui to work in webVR

**Comment by TrevorDev** [comment]
It looks like this already works in the playground in firefox because it includes a polyfill for PoitnerEvent called pep.min.js found here https://github.com/BabylonJS/Babylon.js/blob/d146f5c31f0df7f9e70dd2b73839c45bc1b36be6/Viewer/src/index.ts#L16 
@RaananW @deltakosh do either of you know why this was not added as part of babylon?

Should we:

- Always recommend users to use this library
- Somehow bundle it with babylon
- Re implement PointerEvent in babylon

option 2 or 3 are preferred by me.

**Comment by RaananW** [comment]
The viewer is a one-stop-ship that should work everywhere. This is why it's automatically included in the build.
Before PEP Babylon was using hand.js, and it was also not integrated in the framework. Back then pointers were not an integral part of the framework. Maybe we should (re)consider adding it, but then again - if you want to target all browsers, simply add PEP yourself and it'll work.

**Comment by deltakosh** [comment]
W  do not include third party unless they are vital.
For a poly fill our position is to recommend jouer PEP as it has the support for all the ecosystem

**Comment by tatsujb** [comment]
hello I am getting 
```
ReferenceError: PointerEvent is not defined
```

in firefox console (the app fails to load - white screen)

while the same angular app works fine under every other browser.

what is this caused by and is this issue related?

**Comment by deltakosh** [comment]
Hello please use the forum (as mentioned in the issue template) for questions.

**Comment by deltakosh** [comment]
(did you reference pep.js in your app?)
