### ISSUE TITLE
Creating instance from a cloned mesh makes the cloned mesh and its instances disapear

### ISSUE THREAD

**Issue by RaananW** [BabylonJS/Babylon.js#3932]
This is the example - https://www.babylonjs-playground.com/index.html#QE7KM#130

If you clone a mesh that already has instances and then create an instance from the cloned mesh, the original mesh and its clones are not being rendered. Their position and bounding info stays correct.

If you clone a mesh with no instances and create an instance it works correctly - https://www.babylonjs-playground.com/index.html#QE7KM#131 .

**Comment by deltakosh** [comment]
This is a known limitation. You need to first call clone.makeGeometryUnique() before being able to createInstance.
