### ISSUE TITLE
Regression with standard materials

### ISSUE THREAD

**Issue by innerground** [BabylonJS/Babylon.js#3933]
Dear all,
I am encoutering a problem with the latest preview version of Babylon, I am creating standard materials using the following code (As GLTF1Loader) :
```
var result = new BABYLON.StandardMaterial(material.name || "mat" + material.index,loader._babylonScene);

result.sideOrientation = BABYLON.Material.CounterClockWiseSideOrientation;
if (properties.technique === "CONSTANT") {
    result.disableLighting = true;
}
result.backFaceCulling = properties.doubleSided === undefined ? false : !properties.doubleSided;
result.alpha = properties.values.transparency === undefined ? 1.0 : (1.0 - properties.values.transparency);
result.specularPower = properties.values.shininess === undefined ? 0.0 : properties.values.shininess;
result.ambientColor = BABYLON.Color3.FromArray(properties.values.ambient || [0, 0, 0]);
result.diffuseColor = BABYLON.Color3.FromArray(properties.values.diffuse || [0, 0, 0]);
result.emissiveColor = BABYLON.Color3.FromArray(properties.values.emission || [0, 0, 0]);
result.specularColor = BABYLON.Color3.FromArray(properties.values.specular || [0, 0, 0]);
return result;
```
The materials look wrong (There is transparency, flickering...).
That issue have been solved in a previous release but It appeared again.
Any idea?
Thanks,

**Comment by deltakosh** [comment]
Do you mind repro it in the pg?

**Comment by innerground** [comment]
If I use the code under dist, I got this issue,but If I use the code under preview release,It works fine...

**Comment by deltakosh** [comment]
So it is fixed:)

**Comment by innerground** [comment]
Yes, but  a clearer structure of the project would be appreciated ;)
I expect that the preview-release branch dist folder is what It is called ...

**Comment by deltakosh** [comment]
It is..:) it is the preview of the upcoming release while the dist folder contains the current immutable release
