### ISSUE TITLE
Bug in ParticleSystem createBoxEmitter

### ISSUE THREAD

**Issue by BabylonJSGuide** [BabylonJS/Babylon.js#3947]
Found when editing docs for issue 855

https://www.babylonjs-playground.com/#9NJHHI

parameters given when creating box emitter have no affect.  Make lines 49 to 53 active as oppose to comments to see expected result.

Believe the following to be the problem. Have shown it in Javascript because do not know enough about Typescript to show problem there.

From dist/preview release/babylon.max.js

`ParticleSystem.prototype.createBoxEmitter = function (direction1, direction2, minEmitBox, maxEmitBox) {
            var particleEmitter = new BABYLON.BoxParticleEmitter();
            this.direction1 = direction1;
            this.direction2 = direction2;
            this.minEmitBox = minEmitBox;
            this.maxEmitBox = maxEmitBox;
            this.particleEmitterType = particleEmitter;
            return particleEmitter;
        };`

should be
`ParticleSystem.prototype.createBoxEmitter = function (direction1, direction2, minEmitBox, maxEmitBox) {
            var particleEmitter = new BABYLON.BoxParticleEmitter(direction1, direction2, minEmitBox, maxEmitBox);
            this.direction1 = direction1;
            this.direction2 = direction2;
            this.minEmitBox = minEmitBox;
            this.maxEmitBox = maxEmitBox;
            this.particleEmitterType = particleEmitter;
            return particleEmitter;
        };`

**Comment by deltakosh** [comment]
Excellent catch.
I'll fix it!
