### ISSUE TITLE
Bug in ParticleSystem createConeEmitter??

### ISSUE THREAD

**Issue by BabylonJSGuide** [BabylonJS/Babylon.js#3949]
Not sure if it is a bug this time or if I am missing something in the intentions

https://www.babylonjs-playground.com/#X643HR

In this PG I would expect that when I made the cone radius bigger the cone would scale up. However change the 1 in line 32 to a 10 and the cone gets longer and thinner rather than proportionally bigger.

I think the line `radius = radius * h / this._height;` in the code below should be `radius = radius * h` but this depends on my expectations which may be different to the authors.

`ConeParticleEmitter.prototype.startPositionFunction = function (worldMatrix, positionToUpdate, particle) {
            var s = BABYLON.Scalar.RandomRange(0, Math.PI * 2);
            var h = BABYLON.Scalar.RandomRange(0, 1);
            // Better distribution in a cone at normal angles.
            h = 1 - h * h;
            var radius = BABYLON.Scalar.RandomRange(0, this._radius);
            radius = radius * h / this._height;
            var randX = radius * Math.sin(s);
            var randZ = radius * Math.cos(s);
            var randY = h * this._height;
            BABYLON.Vector3.TransformCoordinatesFromFloatsToRef(randX, randY, randZ, worldMatrix, positionToUpdate);
        };`

**Comment by deltakosh** [comment]
I'm so glad you think alike!
I will fix it (I was thinking the same but I considered it was just me)

**Comment by sebavan** [comment]
Please, do, dunno why I did this way :-)
