### ISSUE TITLE
Alpha is applied to GUI elements inside of a mesh

### ISSUE THREAD

**Issue by Exolun** [BabylonJS/Babylon.js#3968]
Good afternoon!  I'm working on a bit of functionality where the camera and an object + some UI controls are enclosed in a semitransparent box that obscures the surrounding scene.  This was achieved by creating a box with flipped faces around the target area, and applying some alpha and a dark color to the enclosure box.

I noticed that meshes inside / outside the enclosure render as expected, but UI controls rendered on planes inside the box seem to have the alpha of the enclosure applied to them.

- **Bug repro:** 
[playground](https://www.babylonjs-playground.com/#PKS2KJ#2)

- **Expected result:**  
Alpha of the outer object would not be applied to the GUI controls inside the cube. (See sphere adjacent to it)

- **Current result**: 
Alpha of the outer object is applied to the GUI controls.

Update - flipping the faces wasn't a relevant detail.  The same effect occurs if the faces aren't flipped and backface culling is turned off on the enclosure cube.

**Comment by deltakosh** [comment]
By default GUI will attach the texture on both emissive and opacity so you can have alpha on your ADT
you can just turn it of like I did at line #45:
https://www.babylonjs-playground.com/#PKS2KJ#3

**Comment by Exolun** [comment]
That doesn't really solve the issue because removing the opacity texture on the ADT also removes the transparency of the ADT and makes it so you can't resize the child controls on the ADT without seeing a secondary color around it.

In the playground below, you can see that adjusting the height of the inner rectangle creates a black border around it rather than the typical transparent region:
[https://www.babylonjs-playground.com/#PKS2KJ#4](https://www.babylonjs-playground.com/#PKS2KJ#4)

**Comment by deltakosh** [comment]
Then you. Can force the text to be on top with alpha index
See more here:
http://doc.babylonjs.com/resources/transparency_and_how_meshes_are_rendered#alpha-index

**Comment by Exolun** [comment]
I don't think that works because the alpha blending from the box is still applied even if the text is on the top of the alpha index.

**Comment by deltakosh** [comment]
like that: https://www.babylonjs-playground.com/#PKS2KJ#5

**Comment by Exolun** [comment]
Ahh thank you, I was using the wrong values.

Looks like I could use a box intersection to manually get the effect I want on an outside UI plane as well.
https://www.babylonjs-playground.com/#PKS2KJ#6

Thanks again

**Comment by deltakosh** [comment]
My pleasure:)
