### ISSUE TITLE
Expose animation groups in loader callback

### ISSUE THREAD

**Issue by deltakosh** [BabylonJS/Babylon.js#3971]

**Comment by RaananW** [comment]
It is already there, I just fixed a small issue with it in my last PR

**Comment by RaananW** [comment]
this line - https://github.com/BabylonJS/Babylon.js/blob/master/loaders/src/glTF/babylon.glTFFileLoader.ts#L376 was missing

**Comment by deltakosh** [comment]
We need to surface it in the on success callback of load,appears and importMesh

**Comment by bghgary** [comment]
> this line - https://github.com/BabylonJS/Babylon.js/blob/master/loaders/src/glTF/babylon.glTFFileLoader.ts#L376 was missing

Oops, good catch.
