### ISSUE TITLE
typescript typings for vr don't match webvr-api

### ISSUE THREAD

**Issue by mhalle** [BabylonJS/Babylon.js#3989]
Babylon.js typescript typings for VR don't match with those in webvr-api, leading to failed complication of typescript programs that include both babylon.js and threejs (which brings in webvr-api typings) via npm.

See: 
https://www.npmjs.com/package/@types/webvr-api
which is exported from:
https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/webvr-api
and imported with the "three" npm package.

The problematic typings are:
```javascript
// babylon.js
declare var VRDisplay: any; 
```
vs
```javascript
// webvr-api
declare var VRDisplay: {  
    prototype: VRDisplay;
    new(): VRDisplay;
};
```

and

```javascript
// babylon.js
interface Navigator { 
    getVRDisplays: () => any;  
    ...
}
```
vs
```javascript
// webvr-api
interface Navigator { 
    getVRDisplays(): Promise<VRDisplay[]>;
    readonly activeVRDisplays: ReadonlyArray<VRDisplay>;
    ...
}
```

**Comment by deltakosh** [comment]
Good catch!
I'll fix it for next commit
