### ISSUE TITLE
Manually specify Draco decoder URL

### ISSUE THREAD

**Issue by emackey** [BabylonJS/Babylon.js#3991]
Apologies if I'm asking for stuff that's already further down the roadmap...

[It looks like the only way](https://github.com/BabylonJS/Babylon.js/blob/c399d6bc131d25d4c76341cdf7f4fa02d787f76d/src/Mesh/Compression/babylon.dracoCompression.ts#L196) to specify the Draco decoder URL is with a custom script type of `x-draco-decoder`.  Can there be some cleaner API for users to tell Babylon what the decoder URL is?

For example, in ThreeJS: `THREE.DRACOLoader.setDecoderPath(dracoLoaderPath);`

Something similar would be great.  Thanks!

/cc https://github.com/AnalyticalGraphicsInc/gltf-vscode/pull/90

**Comment by bghgary** [comment]
@emackey You can set BABYLON.DracoCompression.DecoderUrl to the url. The function you linked to is just for the default.

**Comment by emackey** [comment]
Beautiful.  Thanks!
