### ISSUE TITLE
Material Firefox

### ISSUE THREAD

**Issue by kopacabana** [BabylonJS/Babylon.js#3992]
Hello,

In firefox when I try to apply different materials to my meshes, there's very strange problem.
Sometimes that's work, sometimes Babylon become crazy and apply last apply material to all my meshes even if I apply diffferent materials to my meshes.
I try many things but nothing works.
In Chrome no problem but I've got another problem, console.log doesn't work. I've never seen that before !!! It's make me crazy ! I loose couple of hours on this two issues....

Thanks for your help.
Loïc

**Comment by deltakosh** [comment]
It is not Babylon.js but Firefox :)
They have an annoying bug that we workaround in 3.2
