### ISSUE TITLE
Adding a Gitter badge on the repo page

### ISSUE THREAD

**Issue by veikkoeeva** [BabylonJS/Babylon.js#3993]
I was wondering if it would be possible to add a Gitter badge to the repo page? The room exists now, Gitter seem to be rather popular in general with GH projects, but now the room is difficult to find.

Examples:
- https://github.com/dotnet/orleans
- https://github.com/aspnet/Blazor

I can provide a PR for this if it's OK. :)

Cross-referecing https://github.com/BabylonJS/Babylon.js/issues/661.

**Comment by deltakosh** [comment]
We do not want a different place to discuss than our actual forum. 
One single means no dispersion of users and if someone needs to search something he will know it is on the forum:)
