### ISSUE TITLE
Playground/scenes/Alien doesn't play its morph targets

### ISSUE THREAD

**Issue by najadojo** [BabylonJS/Babylon.js#3999]
- Bug repro on [sandbox](http://sandbox.babylonjs.com/):
Using [Alien](https://github.com/BabylonJS/Babylon.js/blob/master/Playground/scenes/Alien/Alien.gltf)
- Expected result:
Morph target and skeletal animation channels play.
- Current result:
Only skeletal animation channels play.

**Comment by deltakosh** [comment]
Hello this is expected as the sandbox follows GLTF spec and only start the first animation
You can do something like that to force gltf to start ALL animations:
https://github.com/BabylonJS/Website/blob/c9fa4efa45ab52719c2e10e6f80b5d22d059710d/Demos/ChibiRex/index.js#L12

**Comment by najadojo** [comment]
Sorry I didn't make it clear but the Alien asset contains a single animation that has channels for both morph target and skeletal animations.

**Comment by deltakosh** [comment]
OK pinging @bhgary

**Comment by bghgary** [comment]
Good find. This is a regression from fixing #3846. I have a local fix, but I want to add some tests to make sure it stays fixed.
