### ISSUE TITLE
GradientMaterial does not stay with the object it's applied to

### ISSUE THREAD

**Issue by Exolun** [BabylonJS/Babylon.js#4000]
**Bug repro:**
[http://playground.babylonjs.com/#BWY5S5](http://playground.babylonjs.com/#BWY5S5)

**Expected result:**  
Gradient material follows objects as they move

**Current result:**
Objects move out of the material

**Comment by deltakosh** [comment]
This is how it was designed :)
The gradient uses the world space coordinates of each vertex. so it is based on 0,0,0 as origin

I guess that you would be interested by a gradient based on local coordinates

**Comment by Exolun** [comment]
It would be nice to have since we are trying to use it for a selection effect on objects that could be placed anywhere. 

Are there many Materials that share this characteristic?  

I'm not sure i understand why it isn't a bug, because a material is normally applied to a geometry and should match the transforms of the geometry it's on.  If a material does not match its geometry, is it actually a material?  Wouldn't it be some sort of effect instead?
