### ISSUE TITLE
wheelDeltaPercentage is not the same when zooming in vs zooming out

### ISSUE THREAD

**Issue by emackey** [BabylonJS/Babylon.js#4004]
Let's say I set `scene.activeCamera.wheelDeltaPercentage = 0.1;`.  This code runs:

https://github.com/BabylonJS/Babylon.js/blob/0c2ba69ea3de0f130697f703ff1e3a563fe08b9d/src/Cameras/Inputs/babylon.arcRotateCameraMouseWheelInput.ts#L26

When I'm at a particular radius, let's say radius `10.0`, and I zoom out one click (disregarding some multipliers there for the sake of this simple example), I get `radius = radius + (radius * wheelDeltaPercentage)`, which is `radius = 10.0 + (10 * 0.1)`, which is `11`.

Great!  Now it's time to zoom in one click.  But radius is now `11`, and that same percentage of `11` works out to `1.1`, which is more travel distance.  I end up zooming past where I used to be at `10.0` and down to `9.9`.

Written out like this, it may not sound like such a big deal, but these mousewheel bumps stack up fast, and zooming in becomes noticeably faster than zooming out.

The correct solution is to divide, not multiply, when zooming in.

```
// Zoom Out
radius *= (1.0 + wheelDeltaPercentage);

// Zoom In
radius /= (1.0 + wheelDeltaPercentage);
```

Closing out my example above, `11.0 / (1.0 + 0.1)` would get you back to the original radius of `10`.  But more generally, dividing the same number that was multiplied earlier will effectively reverse the direction while maintaining the zoom speed.  `a * b = c`, `c / b = a`.

**Comment by deltakosh** [comment]
Good catch. I'll fix it asap
