### ISSUE TITLE
Provide a way to avoid offline/manifest call for some files, but not others

### ISSUE THREAD

**Issue by RabidDawg** [BabylonJS/Babylon.js#4005]
I am requesting an upgrade to the current "enableOfflineSupport" (which is handy) so that I can specify that *some* files should be offlined and not others. WIth the solution I'm working on, there will be some assets which I control and can easily be offlined. But other content will be pulled from locations I don't control, and therefore don't have the ability to add .manifest files for those assets. I'd like the ability to turn disable offlining for those files so I don't waste time on a network call that won't succeed. 

Thanks!

**Comment by deltakosh** [comment]
http://doc.babylonjs.com/how_to/caching_resources_in_indexeddb#exceptions
