### ISSUE TITLE
Arc rotate camera not jumping back to original radius, after collision is over

### ISSUE THREAD

**Issue by bobalazek** [BabylonJS/Babylon.js#4006]
If you try to force the camera into the ground to create a collision, the camera closes towards the target, but once the collision is over, the camera stays in the last radius so you can actually go inside the mesh with the camera.

Repro: https://www.babylonjs-playground.com/#4HUQQ#218

**Comment by aWeirdo** [comment]
Hi, It helps quite a bit if you actually enable collisions for the "player" box and set camera's minZ to stop clipping 😄

https://www.babylonjs-playground.com/#4HUQQ#219

**Comment by RaananW** [comment]
Hi, I can't seem to reproduce this. If you set the material's backface culling to false (https://www.babylonjs-playground.com/#4HUQQ#220) you can see that the camera is actually not "going in" but going a bit backwards. 
Setting the camera's minZ to a very low value (not too recommended, i guess), also shows the back of the crate correctly (so you don't get "into" the mesh) - https://www.babylonjs-playground.com/#4HUQQ#221

If I misunderstood, please let me know

**Comment by bobalazek** [comment]
So, if you go to this scene (https://www.babylonjs-playground.com/#4HUQQ#218), just hold the down arrow key. The camera will just slide into the mesh. Well, with the .minZ it can be solved, that it doesn't slide directly into the mesh, but let's say that your camera was originally 8 units back (the radius)... not you hold the down arrow key, so the camera slides totally into the mesh (the radius becomes close to 0).

**Comment by bobalazek** [comment]
Oh sorry, ok, actually, I now understand the confusion. So, the thing is, I'm using the arc rotate camera WITHOUT the input controls. I see now, that this is not an issue in this case because you can solve that by scrolling out with the mouse wheel again.
But now let's say, that I have a third person character controller and don't have the option to use the mouse wheel.

Actually, I just found the solution with .upper/.lowerRadiusLimit... so not a bug, I should just have checked the documentation or code. :)
