### ISSUE TITLE
Earcut not available in 3.2

### ISSUE THREAD

**Issue by BabylonJSGuide** [BabylonJS/Babylon.js#4011]
1. Open http://www.babylonjs-playground.com/#4GBWI5#1
2.     An error appears "Line 12:13 - Earcut is not defined"
3.     All other samples using Earcut on the playground fails to run

Works in stable version
https://www.babylonjs-playground.com/indexstable#4GBWI5#1

**Comment by RaananW** [comment]
Earcut is now an external dependency - https://github.com/BabylonJS/Babylon.js/pull/4012

Should be working after the next playground update

**Comment by RaananW** [comment]
Merged and fixed in the playground.
