### ISSUE TITLE
RenderTargetTexture clone method creates a texture with wrong size

### ISSUE THREAD

**Issue by nxddsnc** [BabylonJS/Babylon.js#4065]
I am using the RenderTargetTexture to some offscreen processing. I create a renderTargetTexture with size equals '{width: 800, height: 400}'. It's works fine until I cloned it. The cloned one's size is 800x800, instead of 800x400; 
Here's the demo.
https://playground.babylonjs.com/#T9IKYV
I checked the code and found that when cloning the RenderTargetTexture, only the width of the source is taken. Is this a mistake or you did it in purpose for some special case?

**Comment by deltakosh** [comment]
Nope it is a bug.I'll fix it
