### ISSUE TITLE
 DebugLayer onChange event

### ISSUE THREAD

**Issue by devAxeon** [BabylonJS/Babylon.js#4079]
[Here](http://www.html5gamedevs.com/topic/36846-debuglayer-onchange-event/) is the forum's link where I posted the question, but all is in the title.

**Comment by Jaskar** [comment]
Hi @devAxeon ,

I don't really understand what you expect. (Maybe because english is not my native language, or because it's getting late here ...)

Can you explain it please ?
Do you have any exemple ?

Thanks :)

**Comment by devAxeon** [comment]
Salut @Jaskar, 

En fait je pensais à truc dans le genre:
`BABYLON.debugLayer.onGlobalPropertyChange.add((result) => {
        console.log(result.object); // The modified object
        console.log(result.property); // The proeprty changed (as string)
        console.log(result.value); // New value after change
        console.log(result.initialValue); // Value before change
});`
C'est un Event déclenché sur les changements dans le debug layer. Si par exemple je me sert du débug layer pour changer la position Z d'un mesh, je voudrais qu'un event me prévienne et me donne le maximium d'info sur cette modification.
`{
        object: myMeshObj,
        property: 'position.z', //Il y a peut-être une meilleur façon de représenter ça...
        value: 2,
        initialValue: 1.7
}`

**Comment by Jaskar** [comment]
Ping @devAxeon
https://github.com/BabylonJS/Babylon.js/pull/4460

Is this what you're looking for ? :)

**Comment by devAxeon** [comment]
Exactly !! Many thanks @Jaskar !!

**Comment by Jaskar** [comment]
I tested it on the Inspector test scene, but it must be tested on real scenes to be sure there are no errors.
Ping me if you find one.
