### ISSUE TITLE
RuntimeAnimation blending bug

### ISSUE THREAD

**Issue by WJsjtu** [BabylonJS/Babylon.js#4088]
https://github.com/BabylonJS/Babylon.js/blob/54bd6963463f988ac6980420f43d577a5562536f/src/Animations/babylon.runtimeAnimation.ts#L330-L342
The number variables also have constructor `Number()`, the blending for number won't got to 'Direct value' branch as expected (Maybe the 'Direct value' branch' will never be reached except for `null` or ` Object.create(null)`.).
Related commit can be found at https://github.com/BabylonJS/Babylon.js/commit/54bd6963463f988ac6980420f43d577a5562536f#diff-63760f0683a184935aa3139053f3594f

Suggestion: What you mean Complex Value is Object I guess.
The `typeof` keyword  may be a way of detecting `Object`, however `var a = new Number(1);` will also make a `Number Object`, the safest way may be `Object.prototype.toString.call(this._originalBlendValue) === "[object Object]"`

**Comment by deltakosh** [comment]
Thanks a lot
I 'll fix that asap :)
