### ISSUE TITLE
glTF Serializer extension support

### ISSUE THREAD

**Issue by sbtron** [BabylonJS/Babylon.js#4098]
Once #3601 is completed, add support for following extensions: 
- [ ] KHR_Unlit
- [ ] KHR_Lights
- [ ] KHR_texture_transform

**Comment by kcoley** [comment]
Working on KHR_texture_transform.  ETA June 8th

**Comment by kcoley** [comment]
Splitting this issue into three:
[KHR_texture_transform](https://github.com/BabylonJS/Babylon.js/issues/4385)
[KHR_Unlit](https://github.com/BabylonJS/Babylon.js/issues/4386)
[KHR_Lights](https://github.com/BabylonJS/Babylon.js/issues/4387)
