### ISSUE TITLE
Expose glTF extension interfaces so that export can use them

### ISSUE THREAD

**Issue by sbtron** [BabylonJS/Babylon.js#4103]
Needed for #4098

**Comment by bghgary** [comment]
Just take all of the interfaces in the loader extensions and put them in a new file so that serializers can use them.

**Comment by Popov72** [comment]
Why not just exporting the interfaces instead of moving them in a new file?

**Comment by bghgary** [comment]
That's a possibility. We weren't using modules when this issue was created.

**Comment by sebavan** [comment]
Yup from the same file will do !!!
