### ISSUE TITLE
Add glTF tab to inspector

### ISSUE THREAD

**Issue by sbtron** [BabylonJS/Babylon.js#4104]
Add glTF in inspector with support for

- [x] <strike>Select animation group</strike> This is already done in the sandbox.
- [ ] <strike>Show validation errors</strike> This will be covered by #4094
- [x] Select which extension to load/display (e.g. use PBR_SpecGloss or Unlit) (PR #4336)
- [ ] <strike>Stats about the glTF file</strike> we have logs with some stats. can improve later if necessary.
- [x] Export glTF/glb

**Comment by bghgary** [comment]
See https://bghgary.github.io/glTF/sandbox-bjs/ for example functionality for some of the items above.
