### ISSUE TITLE
PBRMaterial to dark under safari (DDS conversion to int loses hdr info)

### ISSUE THREAD

**Issue by Kesshi** [BabylonJS/Babylon.js#4115]
IOS shows PBR materials darker than other browsers. All other features of the PBR material are working correctly only the colors are to dark.
I tested Chrome, Firefox, Edge and Android-Chrome. Only IOS has that issue.

Playground: http://www.babylonjs-playground.com/index.html#FTD1E8
The left material is a PBR material and the right one is a StandardMaterial as a color reference.
Both materials should look identical.

Expected result (firefox):
![firefox](https://user-images.githubusercontent.com/15049407/38601084-bda53fca-3d66-11e8-898a-c02246ae63ab.png)

Current result (ios):
![ios](https://user-images.githubusercontent.com/15049407/38601153-e59659d8-3d66-11e8-8c6e-c7c583c9b201.PNG)

**Comment by deltakosh** [comment]
I have the same issue of my iPad. Pinging @sebavan

**Comment by sebavan** [comment]
So it all comes down from the conversion of the environment from float to int loosing the hdr information contained in the environment texture.

I will make a fix tomorrow for this.

Thanks again for reporting.

**Comment by sebavan** [comment]
This will be available in tomorrow s nightly thanks @TrevorDev

**Comment by DerDominic** [comment]
Problem persists using "EquiRectangularCubeTexture".
Need a playground?

**Comment by deltakosh** [comment]
We need a discussion in the forum :) forum.babylonjs.com
