### ISSUE TITLE
CustomRenderTarget needs to be able to share the same depth buffer with the default frame buffer.

### ISSUE THREAD

**Issue by xuchen-shadow** [BabylonJS/Babylon.js#4122]
# Feature request

- Link to [forum](http://www.html5gamedevs.com/topic/36922-is-there-a-way-to-render-meshes-into-customrendertargets-against-the-existing-depth-buffer/?tab=comments#comment-211330) 
discussion about the feature:
- CustomRenderTarget can share the same depth buffer with the default frame buffer.

**Comment by deltakosh** [comment]
Unfortunately I did not find a way to get the depth buffer from the default frame buffer
