### ISSUE TITLE
Add plugin support for SceneSerializer.Save and SceneSerializer.Serialize

### ISSUE THREAD

**Issue by deltakosh** [BabylonJS/Babylon.js#4130]
By default babylonjs format will be used
OBJ and GLTF serializers will register themselves as plugin (like loaders)

- [ ] Add plugin mechanism
- [ ] Make OBJSerializer a plugin
- [ ] Make GLTF2Serializer a plugin

**Comment by thomlucc** [comment]
Good to have but not requested. Re-open if needed.
