### ISSUE TITLE
Allow offline functionality w/o fetching manifests

### ISSUE THREAD

**Issue by RabidDawg** [BabylonJS/Babylon.js#4143]
One thing I'd love to see implemented in Babylon would be the ability to use the offline functionality w/o having Babylon load the manifests for the assets. The way I'm doing asset management is to use a unique url if an object changes, so I don't need Babylon to fetch the manifests every time a scene is loaded since the version number in the manifest will never change. Instead, the url will change, which would let Babylon know it needed to fetch new assets. Thanks!

**Comment by deltakosh** [comment]
What is your timeline for this feature?
