### ISSUE TITLE
[REQUEST]  Give a way to custom `_fontOffset` of Button & TextBlock

### ISSUE THREAD

**Issue by finscn** [BabylonJS/Babylon.js#4157]
# Feature request

Now, if user wants to custom fontOffset of button , he/she has to use this code: 
```
button.children[0]._fontOffset = {
    ascent: a,
    height: b,
    descent: c
};
```

It's not a good way.

I hope there is a getter & setter methods about `fontOffset` in Button & TextBlock.
It's useful in some cases.

**Comment by finscn** [comment]
Now , the _fontOffset is computed via `dom & bom` , 
but I need to run babylonjs in a specific context without `full dom/bom features`.
 for example :      
https://github.com/phoboslab/Ejecta
https://github.com/alibaba/GCanvas   , 
WeChatTinyApp

**Comment by deltakosh** [comment]
ok gotcha! will add a setter

**Comment by finscn** [comment]
Hi @deltakosh  , I see you add setter-fontOffset on Control , but I think it's not enough for Button.
when I use 
```
button.offset = { ....}
```
it's invalid.
 
Button Class should has its own `setter of fontOffset`, like this : 
```
set fontOffset(value) {
 this.textBlock._fontOffset = value;
}
```

**Comment by deltakosh** [comment]
Nope you can just do button.chldren[0].fontOffset

**Comment by finscn** [comment]
But it is not better than  `button.children[0]._fontOffset` , just remove one char `_`.

**Comment by deltakosh** [comment]
It is because you are not using non public API.
Button can be made of only image, image with text, text or anything else so there is no easy way to deal with it

**Comment by finscn** [comment]
When users use different methods to create button , the index  of textBlock will be different.

I think you could set  `this.textBlock = textBlock` , when create button ,
then 
```
set fontOffset(value) {
 this.textBlock._fontOffset = value;
}
```

**Comment by deltakosh** [comment]
But what if there is multiple textboxes?
The button is a container
