### ISSUE TITLE
Playground/textures/environment.babylon.hdr >> Uncaught Bad HDR Format

### ISSUE THREAD

**Issue by Vinc3r** [BabylonJS/Babylon.js#4164]
- Bug repro on [playground](http://playground.babylonjs.com/#CGA05F#2)
- Expected result:
  - load the hdr file (like [here](http://playground.babylonjs.com/#CGA05F#3))
- Current result:

  - get a console result saying `Uncaught Bad HDR Format` for the file https://github.com/BabylonJS/Babylon.js/blob/master/Playground/textures/environment.babylon.hdr

**Comment by sebavan** [comment]
The format .babylon.hdr is our old environment used for prefiltered cubemap that we retired in favor of DDS with Lys, IBLBaker, CMFT

If you remove the .babylon from the extension it is all good: http://playground.babylonjs.com/#CGA05F#10

But be aware they are not preprocessed so should not be used with rough materials.
