### ISSUE TITLE
Adding PhysicsImpostor to mesh loaded from gltf causes unexpected collision area

### ISSUE THREAD

**Issue by TrevorDev** [BabylonJS/Babylon.js#4168]
- Using plane.glb in [plane.zip](https://github.com/BabylonJS/Babylon.js/files/1933004/plane.zip)
- Bug repro on https://playground.babylonjs.com/#6MTUAW
- Updated repro that does not rely on gltf: https://playground.babylonjs.com/#6MTUAW#1
- Expected result: collision matches rendered mesh position
- Current result: collision seems to be where the mesh would be rendered if the rotation was left handed

Workaround this for now by setting:
plane.rotationQuaternion.x *=-1
plane.rotationQuaternion.y *=-1
This breaks the rendering of the mesh to the wrong position but fixes the collision hitbox.

**Comment by deltakosh** [comment]
@RaananW unless you have time to check it before end of next week
