### ISSUE TITLE
360 videos sometimes don't show the first frame in Edge

### ISSUE THREAD

**Issue by RabidDawg** [BabylonJS/Babylon.js#4171]
I'm working on putting a 360 video inside a sphere. I do not want it to autoplay, but if I turn off autoplay, I don't see the first frame render in the sphere in Edge.  

Repro:
https://playground.babylonjs.com/#BPH3U5

Just using a regular <video> tag with autoplay turned off works fine in both Chrome & Edge. 

Thanks!

**Comment by sebavan** [comment]
Thanks for the repro, I have just push an update to fix it, the playground example is now ok.
