### ISSUE TITLE
Community Forum Signup is busted... and how to chain pixel shader?

### ISSUE THREAD

**Issue by theodox** [BabylonJS/Babylon.js#4183]
> Any attempt to create a new account on http://www.html5gamedevs.com fails because a captcha problem -- I've tried this on Chrome and Firefox from both Windows and OSX.  So, I can't ask this question there....

I wanted to ask how to create a chain of effects to do iterative processing -- effectively, render an effect into an RT then pass the result of that back to a copy of the same effect.   

I originally envisioned it as a pair of CustomProceduralTextures that alternated with each other, but that doesn't work. Postprocesses seem to be tied to cameras, but in this case I don't need to render the effect in 3d, it's just a chain of pixel shaders.  

Is this something I can do out the box? If not, what would the appropriate strategy? It's not conceptually very difficult but the implementation details are kind of gnarly.

**Comment by deltakosh** [comment]
You can rely on rendering pipeline which are exactly designed for that:
http://doc.babylonjs.com/how_to/how_to_use_postprocessrenderpipeline

Example: 
http://doc.babylonjs.com/how_to/using_default_rendering_pipeline

You will see if you check the code of the default rendering pipeline that you can easily control which effect is applied to which rtt. And even reuse rtt multiple time.
