### ISSUE TITLE
WebVR not working in chrome for Mixed reality headsets

### ISSUE THREAD

**Issue by TrevorDev** [BabylonJS/Babylon.js#4187]
Loading webvr works in edge and firefox. Chrome recently claims this is now supported: https://www.androidpolice.com/2018/04/20/chrome-66-adds-experimental-support-oculus-rift-htc-vive-windows-mixed-reality-vr-headsets/ 

However it fails to load in babylon playgrounds https://playground.babylonjs.com/#6HQTPR

Tested on: Version 66.0.3359.117 (Official Build) (64-bit) with the samsung mixed reality headset I am seeing:
"DOMException: Presentation request was denied."
In the promise rejection of the vrDisplay.requestPresent
This behavior is the same with Babylon, ThreeJS and Aframe 
https://webvr.info/samples/03-vr-presentation.html

**Comment by TrevorDev** [comment]
It looks like there are still issues in chrome's webVR. The gamepadconnected does not seem to work with Vive causing issues in Babylon and AFrame examples: https://aframe.io/examples/showcase/tracked-controllers/ not initializing controllers.

**Comment by deltakosh** [comment]
Closing as Won't fix because it seems to be a bug in Chrome
