### ISSUE TITLE
glTF Serializer: Known issues

### ISSUE THREAD

**Issue by kcoley** [BabylonJS/Babylon.js#4196]
- [x] Export primitive modes
- [x] Export meshes with multiple uv combinations
- [x] Fix material alpha blending issue
- [x] Support texture sampling
- [x] Export line geometry

**Comment by tdurand** [comment]
I just tried the glTF serializer, really great work here I can't wait to use it for my project

I found a little bug with Submeshes and Submaterial textures, maybe it's already in the list above but I'm not sure as I'm not a pro.

Here is how to reproduce it, you can open this playground: http://www.babylonjs-playground.com/#1XBLWB#6 , and export the glTF.

Here is a screenshot of the babylon scene:
![screen shot 2018-04-26 at 19 00 27](https://user-images.githubusercontent.com/533590/39334454-1017486e-4985-11e8-8dd3-728986fe3c51.png)

and the glb export:
![screen shot 2018-04-26 at 19 00 02](https://user-images.githubusercontent.com/533590/39334460-16e6c8ae-4985-11e8-9165-482233a66781.png)

You can see that the texture is repeated on the export one one column...

I would like to help but I think I do not know well enough the internal of Babylon / the glTF format to do something... So I'll probably just help to report bugs ;-)

Thanks a lot for your work on babylon.js again !

**Comment by kcoley** [comment]
Hi @tdurand , thanks for flagging this issue!  I'll look into this as I am working on another glTF serializer update.

**Comment by kcoley** [comment]
Hi @tdurand , I plan on starting work on your texture issue.  As a heads up, this will make use of the KHR_texture_transform extension https://github.com/KhronosGroup/glTF/pull/1015, so some glTF loaders may need to implement support for it.  I plan on having this implemented in less than two weeks

**Comment by tdurand** [comment]
Great, good luck let me know if you want me to test it 😉. No problem anyway I don't really need it I was just curious to try it on my project !

**Comment by kcoley** [comment]
@tdurand no problem!  I'll be tracking progress on this issue here: [KHR_texture_transform](https://github.com/BabylonJS/Babylon.js/issues/4385)

**Comment by kcoley** [comment]
Hi @tdurand .  I made a recent update to the glTF serializer to support texture uScale, vScale, offset, etc during export.  Feel free to try it when you get a chance.  I was able to serialize your previously posted playground.

[scene.glb.zip](https://github.com/BabylonJS/Babylon.js/files/2368224/scene.glb.zip)

**Comment by tdurand** [comment]
Hey ! Great, I'll give it a try on the project later, thanks for all the work you put in babylon.js !
