### ISSUE TITLE
[REQUEST] Please Remove `#version 300 es` & `#if __VERSION__ >= 200` in shader source

### ISSUE THREAD

**Issue by finscn** [BabylonJS/Babylon.js#4206]
the Mobile devices are very chaos.
 many different hardwares , many different OSs, many different browsers.

So we need many hacks , or patches , or `if-else/switch` for making WebGL could work.
But when do them in shader, it will take some problems.

like this : 
![image](https://user-images.githubusercontent.com/288367/39226822-6ea95f92-4887-11e8-8bf5-2e58d5332b13.png)

The reason is  the shader-compiler of my device can't understand  `#version 300 es` & `__VERSION__`

I don't know what's `#version 300 es` , but I know `#if __VERSION__ >= 200`

In many other engines (like threeJS , pixi.js) , Checking webgl-version is working in JS, but BabylonJS do it in shader.

I hope babylonJS could do it like other engines.

example of ThreeJS 
```
		var lineWidthAvailable = false;
		var version = 0;
		var glVersion = gl.getParameter( gl.VERSION );

		if ( glVersion.indexOf( 'WebGL' ) !== - 1 ) {

			version = parseFloat( /^WebGL\ ([0-9])/.exec( glVersion )[ 1 ] );
			lineWidthAvailable = ( version >= 1.0 );

		} else if ( glVersion.indexOf( 'OpenGL ES' ) !== - 1 ) {

			version = parseFloat( /^OpenGL\ ES\ ([0-9])/.exec( glVersion )[ 1 ] );
			lineWidthAvailable = ( version >= 2.0 );

		}
```

**Comment by deltakosh** [comment]
We are generating version based on wbgl version. If you write your own shader just target write shader for webgl1 and babylonjs will convert it to webgl2 is the hardware supports it

**Comment by deltakosh** [comment]
You may also face devices wrongly reporting wegl2 support.
In this case you can use a specific option when instantiating the engine to turn webgl2 off:
http://doc.babylonjs.com/api/interfaces/babylon.engineoptions#disablewebgl2support

**Comment by deltakosh** [comment]
You can check here that shaders does not come with a version:
https://github.com/BabylonJS/Babylon.js/blob/master/src/Shaders/default.vertex.fx

Version is added only if the device reports a wegl2 compatibly
