### ISSUE TITLE
[REQUEST] Add a switch for disable/enable manifestChecked

### ISSUE THREAD

**Issue by finscn** [BabylonJS/Babylon.js#4207]
Now, when I load mesh file , Babylon will always try to load `.manifest` , if the file is not exist , there is an error , this error can't be void.

![image](https://user-images.githubusercontent.com/288367/39227637-48247df2-488c-11e8-8174-0b9daacddaad.png)

I hope there should be a switch to disable manifestChecked,  or a new API without load manifest file , like this :  ` BABYLON.SceneLoader.ImportMeshWithoutManifest(....)`

**Comment by deltakosh** [comment]
Already supported:
http://doc.babylonjs.com/api/classes/babylon.engine#enableofflinesupport

**Comment by finscn** [comment]
@deltakosh  , I've tried , whatever enableOfflineSupport=true or false , babylon will always try to load manifest file.

**Comment by deltakosh** [comment]
Can you repro on the pg?
This demo here works for instance
https://www.babylonjs-playground.com/frame.html#PSR2ZX#10

**Comment by finscn** [comment]
Oh, I think you don't understand me (my fault).

The demo could be run , and the result  is OK.

But it will take an 404 error in browser console (it's not the key point of this issue) , and will take a server error 404 (this is the key point) .

**Comment by deltakosh** [comment]
Check my demo there is no 404 (the ufo has no manifest) because of the enableOfflineSupport = false

**Comment by finscn** [comment]
See this demo : at https://www.babylonjs-playground.com/
![image](https://user-images.githubusercontent.com/288367/39228808-82db0f28-4892-11e8-9d6b-2fbe66a02a7f.png)

**Comment by deltakosh** [comment]
Your link is wrong. It only bings the default playground

**Comment by sebavan** [comment]
This demo does not emit the error or the request as well: https://www.babylonjs-playground.com/#PSR2ZX#30 Using @deltakosh recommendation.

**Comment by finscn** [comment]
Oh , I see.  @deltakosh  , @sebavan  , 
I create the engine use : 
```
    engine = new BABYLON.Engine(canvas, true , {
        enableOfflineSupport: false,
        disableWebGL2Support: true,
    });
```
Is it wrong ? 

I use `engine.enableOfflineSupport=false` is ok

**Comment by deltakosh** [comment]
Nope because it is related to engine construction as it deals with canvas initialization
