### ISSUE TITLE
Directional light position and shadowcaster

### ISSUE THREAD

**Issue by Vinc3r** [BabylonJS/Babylon.js#4215]
- Bug repro on [playground](http://www.babylonjs-playground.com/#R1EVD0#3):
- Expected result: as the light is directional, its position should not influenced the light direction and so the shadow generated
- Current result: the light impact is OK, but the shadow disappear when the X position of the light is positive (in this playground example)

**Comment by deltakosh** [comment]
This is because shadows from light direction still require a position to compute the shadow map (which is what the light see).
There is no infinite direction light unfortunately.

This is why you need to setup carefully the light position to make sure you can see the entire scene from this POV

**Comment by Vinc3r** [comment]
woops OK! thanks for explanation :)

**Comment by deltakosh** [comment]
My pleasure:)

________________________________
