### ISSUE TITLE
Move motion blur to default rendering pipeline

### ISSUE THREAD

**Issue by deltakosh** [BabylonJS/Babylon.js#4223]

**Comment by julien-moreau** [comment]
100% agree :)
Still keeping motion blur on standard ? Or literally move ?

**Comment by deltakosh** [comment]
Dunno yet..I think we will keep it there for back compat

**Comment by julien-moreau** [comment]
Okay, I thought to make standard rendering pipeline extending the default one in future (if possible). Will consider It more seriously to not have code duplication :)

**Comment by deltakosh** [comment]
Can't agree more :)

**Comment by deltakosh** [comment]
Not a priority. Closing for now. Will revisit in the future if needed
