### ISSUE TITLE
glTF animations don't respect a waiting channel

### ISSUE THREAD

**Issue by najadojo** [BabylonJS/Babylon.js#4224]
1. Bug repro on [sandbox](http://sandbox.babylonjs.com/)
2. Extract and drop in [BoxAnimated.zip](https://github.com/BabylonJS/Babylon.js/files/1957056/BoxAnimated.zip)

- Expected result:

No changes for 1.25s
Rotate for 1.25s
loop back to waiting for 1.25s
Expected result can been seen with [three.js](https://gltf-viewer.donmccurdy.com/)

- Current result:

The 1.25s wait is ignored.

The attached model has a single channel animation with input values:
    1.25
    2.5

**Comment by deltakosh** [comment]
Fixed and published to preview so sandbox should be up to date

**Comment by deltakosh** [comment]
@najadojo our interpretation so far was the one in UFO file. This may be wrong. We need to check with gltf spec. In the meantime you can add a key at frame 0s to get what you need

Sorry about the inconvenience
