### ISSUE TITLE
Sampling mode and anisotropic filtering (Windows only?)

### ISSUE THREAD

**Issue by andyhall** [BabylonJS/Babylon.js#423]
On windows, textures with sampling mode 1 (nearest-neighbor) do not render correctly unless anisotropic filtering is also set to 1.

Demo:
http://www.babylonjs-playground.com/#17NG1A
Textures in that scene should appear pixelated, rather than blurry.

Tested on windows in recent Chrome, IE, FF.
Mac works fine - tested on Chrome, FF, Safari.

**Comment by TriBlade9** [comment]
Tested on Linux. Same issue as Windows:
GPU: Intel 1000,
Distro: Ubuntu Gnome 14.10
Browser: Chromium 40, Firefox 36.

**Comment by andyhall** [comment]
This is really weird. I tested in current three.js and found the same issue, which suggests it could be a fundamental OpenGL thing, rather than an engine bug. But I can't find any discussion anywhere of this being a known limitation. I opened an issue on three.js - perhaps someone there knows what's going on.

**Comment by deltakosh** [comment]
I fixed it :)

**Comment by andyhall** [comment]
DK: do you mean [these lines](https://github.com/BabylonJS/Babylon.js/blob/4fc7ced80731ea8f5b6b0fee3c761cfb6273d289/Babylon/babylon.engine.js#L1639-L1646)? The bug here was that sampling=1 was ignored when anisotropic filtering>1, but this fix just reverses it so that anisotropic filtering>1 is ignored when sampling=1, correct?

The goal is to render with both nearest-neighbor sampling **and** anisotropic filtering.

**Comment by deltakosh** [comment]
Yes. but this sounds not possible so for now I give priority to nearest

**Comment by deltakosh** [comment]
And as a side note, I'm working with IE engineering team to understand better this issue

**Comment by andyhall** [comment]
Great to hear that! Since I found the same issue in three.js, I guess it could be a low-level issue (bug or fact of life) with windows/webGL. But if that were the case I'm surprised that I can't find any past discussion of it anywhere.

Hope the IE folks can shed some light on it!

**Comment by deltakosh** [comment]
I keep you posted guys:)

**Comment by deltakosh** [comment]
More info:
In D3D, setting anisotropic filtering is mutually exclusive with the other filtering options.  

Here is the way IE works with the extension enabled.

If you set the max texture anisotropy to a value greater than 1, we instruct D3D to use anisotropic filtering and set your max anisotropy value.  If you set max anisotropy to 1, then we will instruct D3D to use the other texture filtering constants you specified (“NEAREST_MIPMAP_LINEAR, LINEAR, etc).  Setting max anisotropy to 1 effectively disables it and acts as if the extension was turned off.

**Comment by andyhall** [comment]
Ah! Well that explains it.

Is it possible for BJS to detect when D3D is being used? It would be preferable to still be able to use both kinds of filtering when available (i.e. mac)...

**Comment by deltakosh** [comment]
Unfortunately no. And I do not want to sniff UA so I think we will remain like this (at least same experience everywhere)

**Comment by andyhall** [comment]
Hmm, I see.

Another option would be what three.js does, which is to leave anisotropic filtering at 1 by default. That way people who explicitly set either kind of filtering get what they want, and it's still possible to set them both if you know what you're doing.

**Comment by deltakosh** [comment]
I'm not fan because all scenes will suddenly be less beautiful and this will require people to set it manually(and go through all loaded textures for instance). That said, requiring nearest and anisotropic is pretty rare:)

**Comment by andyhall** [comment]
Yeah, that makes sense. And I see that the mutual exclusivity is in D3D 11 as well, so it's not going to be changing.
