### ISSUE TITLE
GUI component is not getting saved.

### ISSUE THREAD

**Issue by VarshaKamble159** [BabylonJS/Babylon.js#4255]
Hi,

I am adding dynamic mesh to Babylon file and I want a text for each of the mesh. I am using following code to do so.
` var advancedTexture = BABYLON.GUI.AdvancedDynamicTexture.CreateFullscreenUI("UI", true, this._scene);
        var rect1 = new BABYLON.GUI.Rectangle();
        rect1.width = 0.2;
        rect1.height = "40px";
        rect1.cornerRadius = 20;
        rect1.color = "Orange";
        rect1.thickness = 4;
        rect1.background = "green";
        advancedTexture.addControl(rect1);
        var label = new BABYLON.GUI.TextBlock();
        label.text = 'My Text';
        rect1.addControl(label);
        rect1.linkWithMesh(this.currentMesh);
        rect1.linkOffsetY = -50;`

Here, the text is getting added properly(attached is the screenshot of the same). 
When I am trying to save (serialize Babylon file), added text block is not getting saved and eventually, it is not getting loaded again.

I have checked **this._scene.textures** object before and after saving. Before saving it is giving me newly added texture with name **'UI'**. After saving this texture disappears from this._scene.textures array.
Please suggest for the same.

![mytext](https://user-images.githubusercontent.com/9550268/39517899-ec906d5a-4e1e-11e8-8a3c-081b04badef9.png)
![notsaved](https://user-images.githubusercontent.com/9550268/39517900-ecbfa994-4e1e-11e8-8276-aa4887499bbf.png)

**Comment by deltakosh** [comment]
Hello this is an expected behavior as GUI is not part of the core engine so it is not  saved when serializing a scene

**Comment by deltakosh** [comment]
You can still manually serialize it though

**Comment by VarshaKamble159** [comment]
Hi @deltakosh ,

Thanks for the explanation. Can you please help me with serializing GUI component manually. I want it to save with my Babylon file.

Regards,
Varsha

**Comment by deltakosh** [comment]
You can save a string in the scene.metadata. This data can be set to a JSON.stringify of whatever you want to save.

So the idea is to create an object like 
{
 "label": "text",
 "left": "0",
...
}

this value can then be found on scene.metadata after loading the file. And then you can call JSON.parse to get your object back

Regarding gltf2, there is no support for GUI in the spec unfortunately
