### ISSUE TITLE
MeshBuilder.CreatePolygon - uncaught tyepError i is not a function (Line 42:28949)

### ISSUE THREAD

**Issue by saurabhsh96** [BabylonJS/Babylon.js#4259]
BabylonJs Version 3.2.0 CDN link: https://cdn.babylonjs.com/babylon.js

I am trying to create a square polygon. The code (reproduced in the playground link) was working fine two days ago. However, now the same code is producing the following error. 

```
Uncaught TypeError: i is not a function
    at t.build (babylon.js:formatted:50943)
    at Function.t.CreatePolygon (babylon.js:formatted:37781)
    at createScene (test.js:86)
```

Error is against this line: 

`var poly = BABYLON.MeshBuilder.CreatePolygon("square", {shape: vect}, scene);`

# Bugs

- Bug repro on [playground] (http://www.babylonjs-playground.com/indexstable#2EE9UD#3)
- Expected result: A square
- Current result: uncaught typeError i is not a function (Line 42:28949)

**Comment by deltakosh** [comment]
You have to add a reference to earcut.js from Cdn.babylonjs.com as well. It is now an external dependency. I'll do it for the pg as well:)

**Comment by deltakosh** [comment]
The same way you added a ref to babylon.js you can add a reference to earcut.js from our cdn

**Comment by deltakosh** [comment]
Hello! the pg provided seems to not be the good one as I see no call to CreatePolygon

**Comment by deltakosh** [comment]
Any way, just replace your ref to earcut by this one:

        <script src="https://preview.babylonjs.com/earcut.min.js"></script>

I fixed the stable PG :)
