### ISSUE TITLE
AnimationEvent at time 0 doesn't fire after first loop

### ISSUE THREAD

**Issue by najadojo** [BabylonJS/Babylon.js#4260]
1. Repro on [playground](https://www.babylonjs-playground.com/#CBGEQX#7)
2. Click Play
3. Animation contains two events first (at frame 0) changes the lower box red second (at frame 20) turns the lower box blue. 

- Expected result:
Each iteration of the loop should have the box turn red again and then blue later.
- Current result:
First iteration of the loop the box turns red then turns blue but never turns red again.

**Comment by deltakosh** [comment]
Good catch it is a bug..Will fix it for next nightly (on preview branch and in dist/preview release)
Thanks a lot!
