### ISSUE TITLE
Viewer navbar UI UX issues

### ISSUE THREAD

**Issue by sebavan** [BabylonJS/Babylon.js#4276]
- [ ] Full screen button should be hidden if not supported (IOS for instance)
- [x] Navbar should be visible in full screen

**Comment by deltakosh** [comment]
Not sure about full-screen navbar

**Comment by RaananW** [comment]
Navbar in fullscreen is a flag in the nav-.bar template. it is set to true per default, but it wouldn't break anything is we set it to false.

**Comment by deltakosh** [comment]
So go for it:)

**Comment by RaananW** [comment]
so we want navbar in fullscreen

**Comment by deltakosh** [comment]
Yes

**Comment by RaananW** [comment]
It will soon be available in the viewer's CDN (https://viewer.babylonjs.com/viewer.js)

**Comment by RaananW** [comment]
Since I don't want to sniff mobile support, I removed the fullscreen button on screens smaller than 540px using a media query. If this is an acceptable solution you can close this ticket.
