### ISSUE TITLE
[BUG] Only the first created cubeTexture is used

### ISSUE THREAD

**Issue by somarlyonks** [BabylonJS/Babylon.js#4278]
#3762 

It seems still not working in v3.2 or v3.3-alpha.0

Reproduced PG: <http://playground.babylonjs.com/#TGNTGT#18>

**Comment by deltakosh** [comment]
It is a different problem. You must give different rootUrl which will be used as key to differentiate them in the cache:
http://playground.babylonjs.com/#TGNTGT#21

**Comment by somarlyonks** [comment]
Thanks.
