### ISSUE TITLE
Animation Events don't fire/reset after animation stopped and started again.

### ISSUE THREAD

**Issue by najadojo** [BabylonJS/Babylon.js#4283]
1. Bug repro on [playground](https://www.babylonjs-playground.com/#CBGEQX#10):
2. Hit "Play 1"
3. Wait for animation to loop once (lower box turns red)
4. Hit "Play 2"
5. Wait for animation to loop once (lower box turns purple)
6. Hit "Play 1" again.

- Expected result:
When "Play 1" starts again it should turn the cube red right away and then turn blue 20 frames later.

- Current result:
When "Play 1" start again it stays the current color from "Play 2" until the animation loops and then proceeds as expected.

The sandbox has this behavior as well when playing a glTF with multiple animations.

**Comment by deltakosh** [comment]
Sorry about that! Fixing now

**Comment by najadojo** [comment]
Thanks, works great!
