### ISSUE TITLE
getHierarchyBoundingVectors should have a flag to exclude non-visible meshes

### ISSUE THREAD

**Issue by haroldma** [BabylonJS/Babylon.js#4294]
For example when a mesh is not enabled, isVisible is set to false or when visibility = 0

**Comment by sebavan** [comment]
Hello,

This has been added through a predicate https://github.com/BabylonJS/Babylon.js/commit/7466867a73ee0bb05fd005b2b9cd58739d434ca8#diff-617e6d0738ee01f1cec87d5e9a2f0a41R1062

It helps you totally customize what meshes should be included in the computation.

Please, let me know if that works for you.

**Comment by sebavan** [comment]
Addressed in https://github.com/BabylonJS/Babylon.js/commit/7466867a73ee0bb05fd005b2b9cd58739d434ca8
