### ISSUE TITLE
New submeshes get incorrect bounding info if parent has a transform

### ISSUE THREAD

**Issue by andyhall** [BabylonJS/Babylon.js#430]
After running code like this:
```
mesh.position.x = 1000
var sub = new SubMesh( .... , mesh )
````
the new SubMesh's bounding info gets created as if the mesh had no transform.

Code like this works correctly:
```
var sub = new SubMesh( .... , mesh )
mesh.position.x = 1000
````

Repro: http://www.babylonjs-playground.com/#OM4QU
(Swing the camera up or down to see the cubes being incorrectly culled due to bad bounding info.)

**Comment by deltakosh** [comment]
Fixed!
