### ISSUE TITLE
Protential FPS update rate too fast

### ISSUE THREAD

**Issue by aWeirdo** [BabylonJS/Babylon.js#4302]
# Inspector Feature request

- Link: 
http://www.html5gamedevs.com/topic/37510-layermask-is-ignored-when-alwaysselectasactivemesh-is-true/?do=findComment&comment=214334

- Feature description:
Slowing down the update rate of potential FPS.

It's close to impossible to get a clear reading of the protential FPS, can we slow it down to update just a couple times a second?

Cheers.

**Comment by deltakosh** [comment]
@Jaskar  do you mind taking care of this request?

**Comment by Bloadrick** [comment]
Hi,
I have add an input to modify the refresh rate.
PR : https://github.com/BabylonJS/Babylon.js/pull/4318
