### ISSUE TITLE
Add support for some MRTK controls

### ISSUE THREAD

**Issue by deltakosh** [BabylonJS/Babylon.js#4310]
The overall idea is to create a sets of 3D controls available in GUI that can be use in flat screen and VR modes.

Controls are:
- [x] [Interactable object (Button)](https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/master/Assets/HoloToolkit-Examples/UX/Readme/README_InteractableObjectExample.md)
- [x] [Object collection](https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/master/Assets/HoloToolkit-Examples/UX/Readme/README_ObjectCollection.md)
- [x] [Menu system](https://twitter.com/cre8ivepark/status/966861297324146688)
- [x] [Bounding Box](https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/master/Assets/HoloToolkit-Examples/UX/Readme/README_BoundingBoxGizmoExample.md)
- [x] [App Bar](https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/master/Assets/HoloToolkit-Examples/UX/Readme/README_BoundingBoxGizmoExample.md)
- [x] [Support for styling](https://docs.microsoft.com/en-us/windows/mixed-reality/typography)

Misc tasks:

- [x] base button exposes onPointerDown
- [x] all controls work with mouse, touch, pencil & VR Controller thanks to Pointer Events
- [x] custom shader for Fluent Reveal
 * [x] raise onPointerEnter, onPointerDown, onPointerOut events
 * [x] provide a default behavior: onPointerEnter small scaling up (1.1)  + potential highlight (bloom?) + specific 3D sound played, onPointerDown scaling down (0.9) + specific 3D sound played, onPointerOut back to scale 1.0
- [x] root 3D container will be in charge of the layout computation in the 3D space
- [x] specialized containers will override the root 3D for: stack panel, curved container and so on
- [x] Bounding box will customize the new Gizmo 
- [ ] create associated documentation
- [ ] create examples

Some notes:
- Menu and appbar will be specialized object collection
- Styling should be done first for 3D controls but can be reused for 2D controls as well. It can be seen like the style system of XAML. Controls have a style property that controls properties in a centralized way. First version will be just about font size, name and weight.
- All 3D controls should leverage the new Utilities layer of Babylon.js v3.3

**Comment by davrous** [comment]
Adding more details on the various subtasks to work on

**Comment by davrous** [comment]
First great starting sample done by @deltakosh : https://www.babylonjs-playground.com/#K1A9K3

Reference video of the MR Portal/Cliff House behavior for the Bounding Box: https://1drv.ms/u/s!AsZFp14PveQOxu5LBb8FChv5eejtGg

To better understand some small details of the Bounding Box ultimate experience. Let’s describe the video flow:

-	At the beginning, we can see the App Bar being used. Some details:
o	It uses transition animations we probably won’t implement but TBD
o	It has 2 states: collapsed with a unique button “…” or expanded with the “>” collapse option, “cube” to resize/rotate, “X” to close
o	MRTK offers the option to add other additional button in the expanded mode, we should do the same. However, I think that the default behavior should be the same as the Cliff House
-	Clicking on the cube will enter the Bounding Box experience
o	The App Bar now exposes only 1 button to validate
o	A central circle displays “Drag to move” and notice that the reveal shader effect is being applied on it
o	The reveal shader effect is also applied on the spheres and cubes attached to the Bounding Box meshes. MRTK doesn’t do it, shall we do it?
o	PointerHover on the sphere will display an 3D icon to indicate it’s the rotation and a 3D icon on the cube 
-	Rotation/Scaling
o	The laser pointer is attached on the controller and on the sphere or cube
o	It becomes curved
o	Note that MRTK allows to scale using the 2 controllers, I don’t think we should ship it in our first version
-	Move
o	Click on the “drag to move” 
o	You can move around the object using the controller 
o	Collisions are tested to avoid moving the object across another one

We now need to decide how far we should go based on this video.

**Comment by davrous** [comment]
Video in action of the MRTK sample using interactable objects in collections: https://1drv.ms/v/s!AsZFp14PveQOxu9UY-rbuei962ipXQ

**Comment by davrous** [comment]
Video in action of the MRTK sample on BoundingBox: https://1drv.ms/u/s!AsZFp14PveQOxu9WkAAadUHu9eoK4g

Compared to the CliffHouse, the experience is a bit weird as the ray is not attached to the controller point (sphere or cube) and the scaling / rotation feels much less natural than the CliffHouse. I think we should really try to target the CliffHouse experience as close as possible.

**Comment by deltakosh** [comment]
Object collection: http://doc.babylonjs.com/how_to/gui3d#volumebasedpanel

**Comment by TrevorDev** [comment]
@davrous Yep, the behavior of the bounding box has not been optimized for vr interactions yet but its on my todo list. See: https://github.com/BabylonJS/Babylon.js/issues/4141

**Comment by davrous** [comment]
MRTK has also the equivalent of our GUI2D controls in 3D using radio buttons, check boxex, sliders, toggle button like shown in this video: https://1drv.ms/v/s!AsZFp14PveQOxu9XoNojjUE2VjLDBQ  Getting those controls shouldn't be difficult. 

The way is built is interesting also. In the Unity's properties, you can affect different colors for each state. Something we could be inspired by.

**Comment by davrous** [comment]
Adding this doc: https://docs.microsoft.com/en-us/windows/mixed-reality/periodic-table-of-the-elements as inspiration for future samples to build

**Comment by davrous** [comment]
MeshButton3D samples series:

- using default MeshButton3D behavior: https://playground.babylonjs.com/#0Y75BA
- customizing click on a pushButton: https://playground.babylonjs.com/#0Y75BA#1
- customizing click & hover on a push button: https://playground.babylonjs.com/#0Y75BA#2
- several customized pushButton in a Cylinder container: https://playground.babylonjs.com/#0Y75BA#3
- several customized meshButton3D in a Cylinder container with 3D sounds attached: https://playground.babylonjs.com/#0Y75BA#4

**Comment by deltakosh** [comment]
@trevordev please add the app bar Doc so we can close this issue

**Comment by TrevorDev** [comment]
https://github.com/BabylonJS/Documentation/pull/1181

**Comment by deltakosh** [comment]
Wonderful thanks!
