### ISSUE TITLE
Break down the viewer to importable modules

### ISSUE THREAD

**Issue by RaananW** [BabylonJS/Babylon.js#4339]
The viewer should be separated to a few (UMD/es6-based) modules, mainly:

* Templating / UI - for handling HTML-based UI elements (including handlebars)
* Scene Manager - for handling the scene creating and (scene-related) configuration loading 
* Model Loader and Viewer Model - model container and loaders-integration
* Labs - for experimental features and features that might change till the next stable build.
* Viewers - The abstract viewer and the default viewer (that use the other modules)

The viewer should also allow injecting your own version of Babylon (in case you use a custom build)

* [x] reduce dependencies in main classes
* [x] create assets-package that could potentially be loaded. 
* [x] make changes to the npm package (include sources), making sure preview builds stay the same.

**Comment by deltakosh** [comment]
Can you evaluate a potential ETA?

**Comment by RaananW** [comment]
[] reduce dependencies in main classes
[] create assets-package that could potentially be loaded. 
[] make changes to the npm package (include sources), making sure preview builds stay the same.

**Comment by RaananW** [comment]
I will close the ticket after making sure the npm package published correctly
