### ISSUE TITLE
An example page for the viewer

### ISSUE THREAD

**Issue by RaananW** [BabylonJS/Babylon.js#4340]
Create an examples page for the viewer, including code for each example, similar to the examples pages of angular (for example) - https://material.angular.io/components/datepicker/overview

**Comment by deltakosh** [comment]
Will be an awesome addition to the Doc site!

**Comment by RaananW** [comment]
it actually makes more sense to add this feature to the doc site, you are right.

Provide a configuration file with code and link to playground (or actual html to embed) and have it compiled for the doc page. I'll work on that instead :)

**Comment by deltakosh** [comment]
In progress so closing as it is already published for some ;)
