### ISSUE TITLE
AnimationGroup onAnimationEnd callback not working as expected (by design?)

### ISSUE THREAD

**Issue by RaananW** [BabylonJS/Babylon.js#4341]
The onAnimationEndObservable is being notified when each (target) animation in the group has ended. 
I agree that according to the name, it makes sense that this will be triggered when each animation in the group has ended, but a user probably expects a callback to be called when all animations had ended (something like onAnimationGroupEnded ?)

An example where this would make sense:
https://www.babylonjs-playground.com/index.html#9DDUHI#5
And
http://www.html5gamedevs.com/topic/37734-how-to-resetrestart-multiple-animations-in-one-animationgroup/

Another issue (related this this) is that the _isStarted flag should be set to false when all animations have ended (see the same example).

Not sure if this is a feature or a bug, but it feels like it should work differently.

**Comment by deltakosh** [comment]
I agree we should add a on Animationgroup ended.
Same for_isStarted

**Comment by dingoogle** [comment]
Additional info:
at the end of animationGroup, replay it as below, 
           animationGroup.reset(); 
           animationGroup.stop();
           animationGroup.play();
the property "currentFrame" of RuntimeAnimation won't be updated
https://www.babylonjs-playground.com/index.html#9DDUHI#7
