### ISSUE TITLE
Converter is broken

### ISSUE THREAD

**Issue by kevzettler** [BabylonJS/Babylon.js#436]
Looks like http://api.babylonjs.com/converter is broken.

getting this error

> There was no endpoint listening at net.pipe://localhost/exportservice that could accept the message. This is often caused by an incorrect address or SOAP action. See InnerException, if present, for more details.

https://www.dropbox.com/s/n2zfl4fot80jncc/Screenshot%202015-03-12%2020.51.08.png

**Comment by deltakosh** [comment]
I know, this converter is a piece of crap. We will shut it down soon :)

**Comment by kevzettler** [comment]
@deltakosh ok. Not a helpful response though. Whats the suggested alternative? Specifically I have an FBX that I want to use with BabylonJs where do I look?

**Comment by deltakosh** [comment]
Sorry, you can use either 3dsmax exporter or blender3d exporter (and soon unity5 exporter)
