### ISSUE TITLE
IE11 - HighlightLayer not working

### ISSUE THREAD

**Issue by vfabioux** [BabylonJS/Babylon.js#4361]
- Bug repro on [playground](https://playground.babylonjs.com): https://www.babylonjs-playground.com/#1KUJ0A#0
- Expected result: Glowing green halo around the sphere.
- Current result: A black background with nothing but the sphere.

The highlight layer is not working on Internet Explorer 11; initializing a new highlight layer throws the following error: WEBGL11049: INVALID_ENUM: texImage2D : invalid type
I'm not sure what the source of the error is, since IE is pointing to minified code, but comparing with the sources it looks like the problem lies here: https://github.com/BabylonJS/Babylon.js/blob/master/src/Engine/babylon.engine.ts#L4277

**Comment by RaananW** [comment]
If I am not mistaken, HighlightLayer is using webgl2 features, which are not supported in IE11. I will wait before closing it to be sure about it.

**Comment by vfabioux** [comment]
Is there a place listing BJS webgl2 exclusive features?
I have only found this page: http://doc.babylonjs.com/features/webgl2 but finding specifically which BJS features are not working from there is hard.

**Comment by deltakosh** [comment]
Highlight layer is webgl 1 based so it should work on ie11.

**Comment by sebavan** [comment]
Will be fix by the next nightly. Highlight Layer was not supporting non HalfFloat ready browsers: https://github.com/BabylonJS/Babylon.js/pull/4368/files
