### ISSUE TITLE
Extract DDS, KTX or texture creation as plugin

### ISSUE THREAD

**Issue by deltakosh** [BabylonJS/Babylon.js#4364]

**Comment by sebavan** [comment]
- [ ] Constant to readonly
- [ ] No more gl in dds tools
- [ ] No more gl in telemetry manager
- [ ] Plugin System for texture loaders
- [ ] Create plugin for env dds ktx tga.... and standard (jpg bmp...)

**Comment by sebavan** [comment]
Internal vs Base texture fields are all none duplicated.
