### ISSUE TITLE
Unable to get current frame of played animation

### ISSUE THREAD

**Issue by VarshaKamble159** [BabylonJS/Babylon.js#4372]
Hi @deltakosh,

I want to show some progress bar while playing the animations. I am using following code to play all animations within given min-max values 

 ```
 for (let i = 0; i < this._scene.meshes.length; i++) {
                    var animationPlayed = this._scene.beginAnimation(this._scene.meshes[i], 10, 500, false, 1.0, () => {
                        console.log('Animation loop');
                    });
console.log('currentFreame',animationPlayed.getAnimations()[0].currentFrame)
}
```
I want to get currently playing animation frame, so that i can assign it to my progress bar.  
In above codebase, Log printed to get currentFrame is always returning me 0.
Please help for the same.
Thanks.

Regards,
Varsha

**Comment by deltakosh** [comment]
Hello can you please use the forum for question?
Thanks  a lot
