### ISSUE TITLE
Unable to get mesh on click event

### ISSUE THREAD

**Issue by VarshaKamble159** [BabylonJS/Babylon.js#4373]
Hi @deltakosh,

I am trying to get mesh on which I am clicking. For some models, it works fine. But for the attached model it is not getting detected. It returns undefined for the clicked mesh.

Attaching Babylon model for reference.
[ge_model.zip](https://github.com/BabylonJS/Babylon.js/files/2034088/ge_model.zip)
Following is the log of pickedMesh got from this model click
![pickedinfo](https://user-images.githubusercontent.com/9550268/40485926-78802782-5f7d-11e8-84d1-55729f2d94bd.png)

But it works fine for the following model
[cube.zip](https://github.com/BabylonJS/Babylon.js/files/2034089/cube.zip)
and the log of picked mesh for this model is:
![correctpickedmesh](https://user-images.githubusercontent.com/9550268/40485987-a283179c-5f7d-11e8-8ce0-3cf90bcbd8f2.png)

Please suggest the same.
Thanks,

Regards,
Varsha

**Comment by deltakosh** [comment]
Hello can you save the model somewhere and create a repro in the playground?

**Comment by deltakosh** [comment]
Also please post the question on the forum so people will be able to help you quickly :)
http://www.html5gamedevs.com/forum/16-babylonjs/
