### ISSUE TITLE
Update Font Awesome

### ISSUE THREAD

**Issue by Gil-1** [BabylonJS/Babylon.js#4374]
When using @fortawesome/fontawesome >= 5.0 in the project the debug layer doesn't work as some icons are not found.

Maybe an update of fontawesome would just resolve it ?

**Comment by Gil-1** [comment]
Sweet, thanks :)

**Comment by Jaskar** [comment]
Hi @Gil-1 ,

I'll do a PR today.

It brokes a lot of icons, so I hope it's ok.
I you found any missing icon let me know.

**Comment by Gil-1** [comment]
Great and thanks !
I will test it as soon as it's out :)
