### ISSUE TITLE
points with no indices do not show

### ISSUE THREAD

**Issue by makc** [BabylonJS/Babylon.js#4392]
```javascript
var vertexData = new BABYLON.VertexData;
vertexData.uvs = real data;
vertexData.positions = real data;
vertexData.indices = []; // *
vertexData.applyToMesh (mesh);
...
mesh.material.pointsCloud = true;
```
if you remove marked line, the points will not show. I guess something inside bjs depends on indices buffer being defined even when it's not used.

p.s.
> Babylon.js engine (v3.1-alpha)

**Comment by deltakosh** [comment]
Good catch! I'll fix it
