### ISSUE TITLE
[Bug] GUI - onPointerClickObservable not trigger on mobile

### ISSUE THREAD

**Issue by quocsinh** [BabylonJS/Babylon.js#4393]
Please refer to http://www.babylonjs-playground.com/#7RH606 and switch to mobile mode.
The cause is that this._enterCount in _onPointerUp function always equals 0.

**Comment by deltakosh** [comment]
This is expected. Click is for mouse only.
You ca use onPointerUpObservable if you want the event everywhere

**Comment by deltakosh** [comment]
Well after giving it some thoughts I think this would be better to have it everywhere.
I'll make it work:)
