### ISSUE TITLE
Assets Manager don't clear failed tasks

### ISSUE THREAD

**Issue by kutomer** [BabylonJS/Babylon.js#4403]
Hello,
I've noticed that AssetsManager don't clear failed tasks, here is a playground that reproduces this behavior: http://playground.babylonjs.com/#66IDU8

![screen shot 2018-05-30 at 18 40 35](https://user-images.githubusercontent.com/3729904/40731088-ffcf1f62-6438-11e8-8495-30cfc6ba0d46.png)

Or at least do we have any way to remove the failed task besides resetting the entire AssetsManager?

What do you think?

**Comment by RaananW** [comment]
Hi @kutomer - I agree that the assets manager should not invoke a task that is marked as failed. Let's see how we solve this

**Comment by RaananW** [comment]
@deltakosh - I see two options - https://github.com/BabylonJS/Babylon.js/blob/master/src/Tools/babylon.assetsManager.ts#L868 can check for DONE or ERROR,
or:
leave the error and filter them when executing (when calling load()). A failed task can be reset (which will technically put its state back to INIT) so it will execute again if load was called. (my favorite option, btw :smile: )

**Comment by deltakosh** [comment]
It is an expected behaviors as I want to give you a chance to fix stuff and be able to retry

**Comment by deltakosh** [comment]
Here is what we can do:
- keep failed tasks
- provide a way to reset them if you want to retry
- provide a way to remove them

**Comment by kutomer** [comment]
Honestly, I think it makes sense to have both - 
1. failed task should be ignored on next load().
2. removeTask function, I think the easiest implementation for it will be to return a DisposeCallback, something like:
```
const disposer = assetsManager.addMeshTask(...);
//...
disposer();
```

**Comment by RaananW** [comment]
my plan was to allow the dev to change the state to INIT back again, so the task will retry on the next load call. the task won't be automatically removed
Would also be good to add a removeTask function (should be straight forward).
I'll assign it to me.

**Comment by kutomer** [comment]
@RaananW I see that you already fixed it, awesome thanks!

**Comment by RaananW** [comment]
we try to break the world record in open-to-close time of github issues.
