### ISSUE TITLE
Camera.detachControl workaround

### ISSUE THREAD

**Issue by kutomer** [BabylonJS/Babylon.js#4405]
Hello,
As you can see in the [playground](http://playground.babylonjs.com/index.html#08AX88#1) the Camera.detchControl have a different behavior between the stable and the latest version.
Funny thing is that the latest is actually the correct one (consistent with previous versions and other events like move and down).
Do you have any temporary workaround? or should I downgrade the version back to 3.2.0-beta.4?

Tomer.

**Comment by RaananW** [comment]
it is not a downgrade, it is an upgrade to 3.3.0-alpha.3 (latest)

**Comment by kutomer** [comment]
Yeah, but I'm not sure I want to upgrade to a version in alpha, so I'm thinking about downgrading to 3.2.0-beta.4.
I'll try to check if 3.3.0-alpha.3 is working fine, if not I'll just downgrade for the time being.

**Comment by RaananW** [comment]
I thought it works correctly in the playground's latest (which is 3.3.0-alpha). We handle versions a bit differently. For us our nightly are, in general, production ready. The only thing that might change until the next version are public APIs that were added in this version. So if we fixed a bug, it is safe to take the latest.

**Comment by kutomer** [comment]
Awesome, that's very good to know :)
Thanks a lot!
you can close the issue if you like.
