### ISSUE TITLE
Inspector is missing mesh bounding box

### ISSUE THREAD

**Issue by sbtron** [BabylonJS/Babylon.js#4407]
The mesh bounding box isn't being displayed on the Mesh tab

![image](https://user-images.githubusercontent.com/967499/40751715-4161a62e-6421-11e8-86ae-32381a73d3b7.png)

**Comment by bghgary** [comment]
This is happening again.

**Comment by deltakosh** [comment]
On it :)

**Comment by davesauce14** [comment]
Where can I find this "Mesh Tab"? I am not able to find it in the inspector

**Comment by bghgary** [comment]
I would recommend you post a question to the [forum](https://forum.babylonjs.com/) for these kind of questions next time. Posting to a really old issue on GitHub isn't very helpful.

In any case, the inspector has long been changed to use React, so it looks quite different now. See this docs:
https://doc.babylonjs.com/toolsAndResources/tools/inspector#mesh-actions
