### ISSUE TITLE
[Viewer] VR Button for the viewer

### ISSUE THREAD

**Issue by RaananW** [BabylonJS/Babylon.js#4413]
Add a VR button to the viewer's default template.

I will be using the VR experience helper. the ground will be the floor, so the user can teleport. Normalized models will always be the same size (1 unit / 1 meter)

Requires #4338

**Comment by deltakosh** [comment]
Can we consider it done?

**Comment by RaananW** [comment]
yes, initial vr support is integrated.
The next step would be interaction with the model itself (rotating, scaling etc').
