### ISSUE TITLE
Configurable up direction support for SkyMaterial

### ISSUE THREAD

**Issue by kkimdev** [BabylonJS/Babylon.js#4422]
# Feature request
- http://www.html5gamedevs.com/topic/37416-skymaterial-with-z-axis-up-scene/
- https://github.com/BabylonJS/Babylon.js/tree/master/materialsLibrary/src/sky
- Configurable up direction support for SkyMaterial.  Currently SkyMaterial assumes Y is up.  But it would be nice if we can reconfigure for Z up games. Or maybe it's worth to support an arbitrary up direction.

**Comment by thomlucc** [comment]
@kkimdev - We are about to close as we didn't have other requests for for. Do you still need it?
