### ISSUE TITLE
null in addLODLevel

### ISSUE THREAD

**Issue by jroxx911** [BabylonJS/Babylon.js#4425]
# Bugs

- Bug repro on [playground](https://playground.babylonjs.com):
                this.label.addLODLevel(300, null);
- Expected result: Being allow to put null in the second argument
- Current result: In the function definition, the type is BABYLON.Mesh (non-nullable) I expected the type to be nullable mesh.

**Comment by RaananW** [comment]
What would you expect to happen? that the mesh would disappear?

**Comment by deltakosh** [comment]
Unfortunately the link to your PG is not working but you are right regarding TS signature
I'll fix it
