### ISSUE TITLE
Bug in CSG scaling

### ISSUE THREAD

**Issue by jroxx911** [BabylonJS/Babylon.js#4440]
# Bugs

- Bug repro on [playground](https://playground.babylonjs.com/#MDZV4K#3)

- Expected result: I want to have a hollow cylinder. When i'm applying the scaling on the inner mesh it works. But when I apply the scaling on the innerCSG it doesn't work 

- Current result: Scaling doesn't apply correctly and the CSG subtract themself.

**Comment by RaananW** [comment]
The scaling in CSG is applied to the exported mesh and not to the CSG itself.
if you want to do that (as you already wrote in your playground), you would need to scale the input mesh, or export the CSG to a mesh and create a new CSG.
You will notice that there is also position and rotation values. both are applied to the exported mesh but not the vertex data of the mesh, which is what being used to create the polygons for the CSG.
