### ISSUE TITLE
Mesh#billboardMode doesn't work with parented cameras

### ISSUE THREAD

**Issue by andyhall** [BabylonJS/Babylon.js#445]
Meshes with billboardMode >=1 display incorrectly if the scene's camera has a parent. I imagine they are probably facing themselves towards the camera's position in local coords rather than its world position.

Repro: http://www.babylonjs-playground.com/#NVAOX#1
Comment out the line that parents the camera for correct behavior.

**Comment by RaananW** [comment]
The reason is (probably?) this line of code - https://github.com/BabylonJS/Babylon.js/blob/3f6e0504897325312f3668fc52e00860b4289cab/Babylon/Mesh/babylon.abstractMesh.ts#L446
The position of the camera doesn't change, it's absolute position does.

**Comment by deltakosh** [comment]
I'll fix it with the next commit

**Comment by andyhall** [comment]
@RaananW @deltakosh 

This is broken again. ;)

I'm pretty sure I tested the original fix, and it worked, but in current builds the bug reproduces again. (Or possibly just a similar-looking bug).
Repro is same PG as above.

Thanks!

**Comment by deltakosh** [comment]
My gosh, I though I fixed it!

i will fix it for the next push FOR REAL:)

**Comment by andyhall** [comment]
Thanks!

By the way - one handy thing to do is leave GH issues open, and when you make the fix just put "fixes #445" or "closes #445" in the commit message. Then GH will automatically close the issue and link it to the commit... which becomes very useful later if it breaks again. ;)

**Comment by deltakosh** [comment]
Right :)

**Comment by andyhall** [comment]
Works again, thanks! :+1:
