### ISSUE TITLE
[Playground example] "PBR with music analyzer #2" doesn't work through https

### ISSUE THREAD

**Issue by Vinc3r** [BabylonJS/Babylon.js#4459]
# Bugs

- Bug repro on [playground](https://www.babylonjs-playground.com/#2JOSXE#21)
- Expected result: music playing, like in [http version](http://www.babylonjs-playground.com/#2JOSXE#21)
- Current result: music not playing

[edit] This scene is on the [playground examples](https://i.imgur.com/pV7Kcqx.png) [/edit]

Maybe it's because synergy-development.fr doesn't have https on it? (and also, for copyright reasons, maybe it could be better to use open source music, e.g. from [jamendo](https://www.jamendo.com/) ?)

**Comment by Jaskar** [comment]
Did someone know the dev of "synergy-development.fr" ?
Maybe we can take the mp3 and host it on the playground website ? I'm not sure if there is copyright things or not.

**Comment by Vinc3r** [comment]
I dont think Prodigy music is free from copyrights.

**Comment by RaananW** [comment]
it this an official babylon demo? somewhere in the doc or on the website?
(btw - more beastie boys than prodigy :) )

**Comment by RaananW** [comment]
oh, and no - we cannot host this music on the playground.

**Comment by Vinc3r** [comment]
yep sorry to haven't show the source of this PG scene : it's on the Examples

![PG examples](https://i.imgur.com/pV7Kcqx.png)

**Comment by Vinc3r** [comment]
If a track is needed I suggest [this one](https://www.jamendo.com/track/1466090/universal-funk) (it's on Creative Commons licence).

**Comment by deltakosh** [comment]
Fixed (Will be pushed soon)

**Comment by Stvsynrj** [comment]
Hi guys... i didnt saw this issue before ....
I changed the music for a new one under Common Creative Licence.
I askek @deltakosh to update the exemple with this new playground.
http://www.babylonjs-playground.com/#2JOSXE#23

**Comment by sebavan** [comment]
Done https://github.com/BabylonJS/Documentation/commit/67c4f4fee5e498fd2ebda1d77be12e6b2bc4ace0

Will be deploy soon.
