### ISSUE TITLE
[Inspector] "Hey there!" message :)

### ISSUE THREAD

**Issue by Vinc3r** [BabylonJS/Babylon.js#4461]
https://github.com/BabylonJS/Babylon.js/blob/57c1a3019bc2b2f645a5f16025541bea1c13fcbc/inspector/src/Inspector.ts#L379

I think it's not a big deal, but this `Coucou!` stay visible once popup is opened :-D

![coucou](https://i.imgur.com/NOANtFA.png)

**Comment by Jaskar** [comment]
My bad, it was a test when I tried to fix Edge version. I thought I rejected this change.
Will fix it asap !!!

**Comment by RaananW** [comment]
Coucou!

**Comment by Jaskar** [comment]
PR done.
Will be fixed with the next nightly build :)

**Comment by Vinc3r** [comment]
At least it wasn't the classic "Toto" :)
