### ISSUE TITLE
Log entries with whitespace do not display properly in inspector console tab

### ISSUE THREAD

**Issue by bghgary** [BabylonJS/Babylon.js#4469]
https://playground.babylonjs.com/#MBCCSC

![image](https://user-images.githubusercontent.com/19158740/41133945-b1f8bf22-6a7e-11e8-8bd8-85229279a834.png)

**Comment by Jaskar** [comment]
Correction here : https://github.com/BabylonJS/Babylon.js/pull/4464

Awaiting for review
