### ISSUE TITLE
Receiving console error when trying to update any value using debuging layer

### ISSUE THREAD

**Issue by IbraheemOsama** [BabylonJS/Babylon.js#4495]
- Bug repro on https://www.babylonjs.com/demos/glowingespilit/
Steps:
1) Open Control Panel.
2) Click Debug Layer.
3) Go to mesh view.
4) Click on any mesh and try to update it's value
- Expected result:
Mesh data to be updated like position.
- Current result:
Nothing get updated and I receive this error in the console:

Uncaught TypeError: Cannot read property 'notifyObservers' of undefined
    at n.set [as value] (babylon.inspector.bundle.js:2)
    at n.validateInput (babylon.inspector.bundle.js:2)
    at n._validateInput (babylon.inspector.bundle.js:2)

**Comment by deltakosh** [comment]
Thanks for catching it
It is deu to the new onValue Changed observable

**Comment by deltakosh** [comment]
Pinging @Jaskar

**Comment by Jaskar** [comment]
Sorry for the delay. A PR is coming to fix this!

**Comment by Jaskar** [comment]
@deltakosh is it possible to deploy the updated version ?

**Comment by RaananW** [comment]
if you are referring to npm, I am publishing a new version very soon

**Comment by deltakosh** [comment]
Publication done and bug fix confirmed!
nice work guys
