### ISSUE TITLE
Animations in imported GLTF won't stop

### ISSUE THREAD

**Issue by adrientetar** [BabylonJS/Babylon.js#4514]
- Bug repro: [Animation bug](https://www.babylonjs-playground.com/#QY1WYT#1)
- Expected result: The animations in imported GLTF shouldn't play, as currently after loading we run (cf. repro link)

~~~js
animationGroups.forEach(group => {
    group.stop();
    group.reset();
});
~~~

This used to work until we recently upgraded to v3.3.0-alpha.5. Another method I found on [this thread](http://www.html5gamedevs.com/topic/10758-stop-the-mesh-animation-autoanimate/) also doesn't seem to work:

~~~
scene.stopAnimation(newMeshes[0]);
~~~

- Current result: The animation in imported GLTF is playing in a loop, though we added code to disable it

**Comment by adrientetar** [comment]
Okay so it seems the second method does work, I just wasn't applying it to the right mesh (the root mesh isn't the one with the animation), doing scene.stopAnimation recursively does work. The animationGroups method remains broken though.

**Comment by bghgary** [comment]
I'll take a look at this bug, but in the meantime, a better way to not start an animation after loading a glTF is to do something like this:

```
    BABYLON.SceneLoader.OnPluginActivatedObservable.addOnce(function (plugin) {
        if (plugin.name === "gltf") {
            plugin.animationStartMode = BABYLON.GLTFLoaderAnimationStartMode.NONE;
        }
    });
```

**Comment by adrientetar** [comment]
Thanks, I'll check-in that code. We do use animationGroups to control the animations also, so it being broken remains problematic.

**Comment by adrientetar** [comment]
@bghgary I tried to add your code snippet right after creating the BABYLON.Engine and it doesn't seem to work - the "if plugin.name" line is only called once with plugin.name set to "babylon.js".
Am I to call this line right before the first GLTF file gets loaded? If so I'm wary of adding such timing-sensitive code (behavior could break if someone loads a GLTF some other place in the code, etc.).

**Comment by deltakosh** [comment]
The bug is fixed now so you should just need to get a drop from the preview folder :)

Regarding your question here is an example in the Playground: https://www.babylonjs-playground.com/#QATUCH#3

**Comment by adrientetar** [comment]
Okay I see replacing addOnce with add makes the code less dependent on its position - I'll do that. Thanks.
