### ISSUE TITLE
GLTF Serializer Error - 'Cannot read property 'EmissiveTexture' of null'

### ISSUE THREAD

**Issue by VarshaKamble159** [BabylonJS/Babylon.js#4515]
Hi,

I am updating Babylon model by adding new meshes to it and serializing it to GLTF. I am facing following error very frequently.
![emissivetextureissue](https://user-images.githubusercontent.com/9550268/41335686-471e76c8-6f07-11e8-864d-e3813d71d823.png)

Following is the code for adding mesh to the scene:
```
addMesh(color){
            var hotspotId = String(Date.now()) + Math.floor(Math.random() * 10000)
            var hotspotMesh = BABYLON.Mesh.CreateBox(hotspotId, 3, this._scene);
            hotspotMesh['position'] = new BABYLON.Vector3(0, 0, 0);
            var hpMat = new BABYLON.StandardMaterial("ground" + hotspotId, this._scene);
            hpMat['diffuseColor'] = BABYLON.Color3.FromHexString(color);
            hpMat['specularColor'] = BABYLON.Color3.FromHexString(color);
            hpMat['emissiveColor'] = BABYLON.Color3.FromHexString(color);
            hotspotMesh['material'] = hpMat;
}
```

Following is the code for serializing scene
```
SERIALIZERS.GLTF2Export.GLTFAsync(this._scene, filename).then((gltf) => {
    //stuff to work with gltf files
}
```

Kindly help me with the same.
Thanks.

Regards,
Varsha

**Comment by deltakosh** [comment]
@kcoley  should be able to help:)

**Comment by kcoley** [comment]
Hi @VarshaKamble159, thanks for flagging this issue. I’ll look into it today and get back to you ASAP

**Comment by kcoley** [comment]
@VarshaKamble159, sorry for the delay.  I just ran your code snippet in a playground, but was able to get it to work: http://playground.babylonjs.com/#IGUTWY

Are you running the latest version of the glTF serializer?

**Comment by VarshaKamble159** [comment]
Hi @kcoley,
I am using following versions of babylon and serializer.
 ```
 "babylonjs": "^3.2.0",
  "babylonjs-serializers": "^3.2.0",
```
I have created babylon playground to show my usecase and reproduce the issue:
https://playground.babylonjs.com/#6HDGLC#2.

But here i am facing some other issue.
![issue](https://user-images.githubusercontent.com/9550268/41394376-53ff2b42-6fc7-11e8-8a47-fbf09b75431d.png)

Thanks.

Varsha

**Comment by deltakosh** [comment]
Up?

**Comment by VarshaKamble159** [comment]
Hi @kcoley ,

Thank you so much. The error disappeared now :)

The latest version is not yet available on npm?  I had to manually specify version 3.3.0-alpha.7, but it did work well.
Thanks.

Regards,
Varsha

**Comment by deltakosh** [comment]
It is in npm but flagged as preview:
https://www.npmjs.com/package/babylonjs/v/3.3.0-alpha.8
