### ISSUE TITLE
origin shift with large coordinate

### ISSUE THREAD

**Issue by yaoyao-cn** [BabylonJS/Babylon.js#4516]
# Feature request

i am developing a GIS system that need a large coordinate. i put my coordinate origin in the center of the earth, the radius of earth is set to 6378137.0 m . so most of  my coordinate value looks like this:[ 6378137+ someValue, *, *  ] and at least one of x,y,z is very big.

in my client application written with c++, i use double value for the position of 
a model,  and float value for others(world matrix, rotation, scaling, local position). then i record a scene origin, the scene origin will be updated automatically. so the origin always follow the camera. every time the origin updated, the world matrix of a node will be updated at the time it be cliped by camera.

hope there will be a origin shift metod built in babylon.js and update the origin automatically

thank you !

**Comment by yaoyao-cn** [comment]
the reason i use double is that , the resolution of 32 bit float is too low for big value. and the scene will shake when camera moving

**Comment by deltakosh** [comment]
would it be something you can fix with a root object that move the world and apply the offset?
How would you see it implemented else?

**Comment by yaoyao-cn** [comment]
@deltakosh 
a root object may solve the problem, but may not be efficient i guess. in my desktop implement,i use a scene origin counter , update the origin is just increase the counter, the world matrix of a node will be update at the time it be cliped by camera. every time the node update it's world matrix, it will cache the counter. the clip method use the double typed octree and aabb box of node. so the aabb box need not be updated when the scene origin change.

now i am going to implement a web version of my desktop GIS application. and i also use the left hand coordinate with x axis goes right, y axis goes up, z axis goes forward. every thing is perfect except the large value problem. 

i found that three.js lib use the js number type for its matrix class, which will be ok for large value but use more memory! and i think this is the most simple way to solve my problem.
what if leaving the user to choose the matrix's value type(float32array, or js number array) with a config option?

here is the code i test with babylon playground, try to move the camera and you will notice the shake

    var someBigValue = new BABYLON.Vector3(6378137, 0, 0);


    // This creates a basic Babylon Scene object (non-mesh)
    var scene = new BABYLON.Scene(engine);

    // This creates and positions a free camera (non-mesh)
    var camera = new BABYLON.FreeCamera("camera1", 
        new BABYLON.Vector3(0, 5, -10).add(someBigValue),
        scene);

    // This targets the camera to scene origin
    camera.setTarget(someBigValue);

    // This attaches the camera to the canvas
    camera.attachControl(canvas, true);

    // This creates a light, aiming 0,1,0 - to the sky (non-mesh)
    var light = new BABYLON.HemisphericLight("light1", new BABYLON.Vector3(0, 1, 0), scene);
    // Default intensity is 1. Let's dim the light a small amount
    light.intensity = 0.7;

    // Our built-in 'sphere' shape. Params: name, subdivs, size, scene
    var sphere = BABYLON.Mesh.CreateSphere("sphere1", 16, 2, scene);

    // Move the sphere upward 1/2 its height
    sphere.position.y = 1;
    sphere.position = sphere.position.add(someBigValue);

    return scene;

you can do the same thing in the three.js editor: https://threejs.org/editor/
1.add a box
2.change box's position to a large value(eg:6378137, 0, 0) in the object pannel on the right
3.also change the camera's position , so you can see the box
4.then change the camera's position slowly, and the scene will not shaking

**Comment by deltakosh** [comment]
I've just try to store data in the matrix as number[] instead of Float32Array but the problem remains. I think more than the matrix has to be changed

**Comment by deltakosh** [comment]
Well we should have something else because I tried with Flaot64Array and number[] and the problem remains

**Comment by deltakosh** [comment]
#4519 
Closing for now until we find a way to improve it

**Comment by deltakosh** [comment]
The ideal solution here is to have a root node and move the world with the camera so camera is always at 0,0,0

**Comment by N3GIS** [comment]
Is there a solution to this problem？

**Comment by Popov72** [comment]
We now have an option `useHighPrecisionMatrix` that you can set to `true` when creating the engine. That will make matrix computations to use doubles instead of floats.

However, that won't solve everything because we use a separate world and view matrix in the shader. We would need to use a combined worldView matrix so that the big numbers in each matrix are cancelling each others.

For eg:
* https://playground.babylonjs.com/#97STEZ#1 => standard PG with small numbers, everything is ok: the sphere is a sphere and movements are smooth
* https://playground.babylonjs.com/#97STEZ#2 => X position of the sphere and camera is big: the sphere is not a sphere anymore and movements are jerky (use the keyboard arrows to move)
* https://playground.babylonjs.com/#2EERDJ#5 => same thing than above but using a custom shader that is using `worldView` instead of `world * view`. The sphere is now a sphere again but the movements are still jerky
* https://playground.babylonjs.com/#2EERDJ#6 => same thing than above but with `useHighPrecisionMatrix = true`. The sphere is ok and the movements are not jerky anymore

You can see that even in this last PG the specular highlight is not well defined and change when moving (compare with the PG #1). That's because some computations are done in world space, and because of the big values we have in the world matrix the results are not accurate enough...

**Comment by Popov72** [comment]
Note that using NME you can overcome those problems by using the worldView projection and not world/view separated and by doing your computations in the view space.

**Comment by N3GIS** [comment]
I didn't have this problem with version 4.2." NME" yes

**Comment by tanzle-aames** [comment]
There appears to be a regression here. Take a look at this playground example, that was linked as the solution in a comment above:

- https://playground.babylonjs.com/#2EERDJ#6

The sphere looks ok, but disappears at the slightest movement of the camera. Occurs with WebGL and WebGL2.

**Comment by Popov72** [comment]
I don't think it's a regression, it was already that way in #6 when you use the camera. Using the keyboard does work as expected.

I think it has to do with the steps used by the camera to update the position/rotation, one would need to lower them somehow but I'm not knowledgeable enough about inputs to know.

**Comment by tanzle-aames** [comment]
Ah yes! My mistake.

**Comment by yaoyao-cn** [comment]
what about use a dummy-world and a dummy-view matrix
here dummy means: when send matrix to shader, change the translation item of viewMatrix to [0,0,0,0] and substract the world space translation of camera from worldmatrix.
the result is: translation of viewMatrix is[0,0,0,0], translation of world matrix is small, and the shader knows nothing about this, so it can still use separated world view matrix

**Comment by Popov72** [comment]
The new `floatingOriginMode` parameter (new in v8.28.2) fixes all these problems (pass this parameter when you create the scene):

~~https://playground.babylonjs.com/#97STEZ#4~~ https://playground.babylonjs.com/#97STEZ#6

**Comment by N3GIS** [comment]
> The new `floatingOriginMode` parameter (new in v8.28.2) fixes all these problems (pass this parameter when you create the scene):
> 
> https://playground.babylonjs.com/#97STEZ#4

[](https://doc.babylonjs.com/typedoc/interfaces/BABYLON.EngineOptions)
<img width="1765" height="379" alt="Image" src="https://github.com/user-attachments/assets/73940c92-95ee-4bc7-9fdd-57ce960bbde5" />

**Comment by Popov72** [comment]
Yes, we now have to set `useLargeWorldRendering` to enable floating origin mode:

https://playground.babylonjs.com/#97STEZ#6
