### ISSUE TITLE
SceneLoader with GLTF : freezeActiveMeshes bug in onSuccess callback

### ISSUE THREAD

**Issue by vfabioux** [BabylonJS/Babylon.js#4518]
- Bug repro on [playground](https://playground.babylonjs.com): https://playground.babylonjs.com/#BV41NK#1

- Expected result: when loading a GLB file with SceneLoader.Append(), the whole file should load, then active meshes should be froze when calling scene.freezeActiveMeshes() in the onSuccess callback.

- Current result: the onSuccess callback is called too soon, so some imported meshes are froze before they can be rendered. They are still being added to the list of meshes as shown by the console logs on the playground.

**Comment by RaananW** [comment]
Will that be the expected behavior? https://playground.babylonjs.com/#BV41NK#2

**Comment by vfabioux** [comment]
Seems like I misinterpreted the "active" word. I though it was refering to the enabled state of the mesh (Mesh.isEnabled()) while it is actually refering to whether it is visible in the current view or culled.

Here is a camera independant solution following the recommendations in the docs: https://playground.babylonjs.com/#BV41NK#3
