### ISSUE TITLE
Moving the ArcRotateCamera causes it's parent to shake when a large mesh is also added to the Scene

### ISSUE THREAD

**Issue by Upperfoot** [BabylonJS/Babylon.js#4519]
# Bugs

- Bug repro on http://playground.babylonjs.com/#Z19AFM#1
- Expected result: Moving the ArcRotateCamera should not cause the camera.parent (player mesh) to shake when adding a large mesh is added to the scene (Sphere with a diameter of (6371 * 1000 * 2))
- Current result: Moving the ArcRotateCamera causes the camera.parent to shake when a large mesh is added to the scene (Sphere with a diameter of (6371 * 1000 * 2))

# Backstory

I am creating a spherical world with a similar diameter of the earth if it was perfectly spherical, because BabylonJS is normalised to meters I am setting the diameter of this sphere mesh to be (6371 * 1000 * 2) meters, and my Player mesh which the camera is attached to is set to 2 meters high.

I'm unsure if this shaking is caused by a limitation of precision or not.

**Comment by deltakosh** [comment]
Actually the player is not moving per se. But due to the use of really BIG numbers we are losing so much precision that the matrix computation are no more precise enough

You should probably try to use km as unit instead of meters

**Comment by Upperfoot** [comment]
@deltakosh Can you explain what you mean by not moving? Here is an example of it moving https://gph.is/2JFWwOY

I tried reducing it by a factor of 100 (6371 * 10 * 2) http://playground.babylonjs.com/#Z19AFM#2 and its still exhibiting the shaking problem, how low do I need to go on these values to stop it from shaking? 

I can't reduce it much further than that, because I want my player to be kept in relative scale to the sphere, I tried reducing it to (6371 * 2) and the shaking stops, but my ArcRotateCamera radius doesn't allow me to set it to 0.01, its either 0, or 1.

**Comment by deltakosh** [comment]
Well keep in mind that we can only use 24bits depth buffer so something around 10000 units is the max you can do before entering the unprecise world

radius could be anything you want but you have to set camera.lowerLimitRadius = null

**Comment by deltakosh** [comment]
Closing as won't fix so far as we have no clue on how to improve it (unless using a root node to offset all the world but this is already feasible)
