### ISSUE TITLE
Add Support For Structures in ShaderMaterial

### ISSUE THREAD

**Issue by abogartz** [BabylonJS/Babylon.js#4520]
- Discussion Here: [forum](http://www.html5gamedevs.com/topic/38179-updating-a-shader-material-frag-shader/?do=findComment&comment=218073) 
- ShaderMaterial should support structures. A typical use is to combine properties in a single object to make code more readable.

```
struct Material = {
  sampler2D diffuse;
  sampler2D normal;
};

uniform Material myMaterial;

vec4 diffuse = texture2D(myMaterial.diffuse, uv);
```

**Comment by deltakosh** [comment]
Thanks!

**Comment by deltakosh** [comment]
Already working actually :D
https://www.babylonjs-playground.com/#CNE3P8#2
