### ISSUE TITLE
[Feature Request] GUI2D - Add support wrap for Container

### ISSUE THREAD

**Issue by quocsinh** [BabylonJS/Babylon.js#4526]
This is useful in some cases when want to display exactly width & height actually of Container.

**Comment by deltakosh** [comment]
Can you tell me more about this feature? How do you think it should work?

**Comment by quocsinh** [comment]
Like this:

![image](https://user-images.githubusercontent.com/13402645/41388407-fbda52ea-6fb5-11e8-9380-4b436bb198c1.png)

I think we need 2 boolean properties: _wrappingWidth_ and _wrappingHeight_ or something similar...
By default, the width & height of Container is 100%. When set them = true, the Container will compute all controls/components inside it and after that the Container will reset width & height.
Thanks :)

**Comment by deltakosh** [comment]
Ok understood. Feel free to PR if you want to help

**Comment by menduz** [comment]
We use `TransformNode`, only create one as a parent and assign the children to it. Tell me if it works for you. @quocsinh

**Comment by menduz** [comment]
```ts
container = new BABYLON.TransformNode()
child1.parent = container
child2.parent = container
container.parent = scene
container.position.set(1.....)
```

**Comment by deltakosh** [comment]
Closing for now as we have Grid and StackPanel now that can handle that easily
