### ISSUE TITLE
Canvas or camera in portrait mode (configuration)

### ISSUE THREAD

**Issue by Fer-AR** [BabylonJS/Babylon.js#4536]
Hi all,

I am very new with Babylon.js (I started today), and I am trying a design with a **.GLB** file that works very well in many other projects, but I have a problem and I hope you can help me.

My current project is 100% mobile (**ever vertical view or portrait mode**) and with this (see bellow) code I can not make the image (or the canvas) appear vertical, occupying the whole screen in its width and height (**width: 100% + height: 100%**) and I think I understand that it is a camera configuration problem (which I have not done), and I need help with this.

Another problem is that the object (or the camera) has zoom and I can not see the full object (is trimmed up and down), besides being tilted backwards, approximately 33 degrees, and I understand that everything is a matter of configuring the camera.

You can see the original example of Babylon here: https://viewer.babylonjs.com/domexample

But my object is vertical (here's my problem).

You can download my GLB file here ( .zip - 1 Mb ) : https://goo.gl/u1BRKn

Where is my problem, or what am I missing?

Thanks

**This is my current code:**

```
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>BabylonJS Viewer - DOM usage</title> 

<style>
        html{
            width:100%;
            min-height:100%;
            margin:auto;
            top:0;
            left:0;
            padding:0;
            overflow:hidden
        }

        body{
            top:0;
            left:0;
            margin:0;
            padding:0;
            overflow:hidden
        }
        
        babylon {
            width:480px;
            height:960px;
       /*  width:100%;
            height:100%; */
            margin:0 auto
        }

     /*canvas {
            width:100%;
            max-width:480px;
            height:auto;
       }

       viewer {
            width:100%;
            max-width:480px;
             height:720px;
       } */

</style>

</head>

<body>

<babylon extends="minimal">
            <model url="models/shampu/shampu.glb"> <!-- replace here with your route -->
            <scaling x="1" y="1" z="1"></scaling>
            </model>

            <camera>
                <!--<behaviors>
                    <auto-rotate type="0"></auto-rotate>
                </behaviors>-->
            </camera>
</babylon>

        <script src="js/viewer.js"></script> <!-- replace here with your route -->

</body>
</html>
```

**Comment by deltakosh** [comment]
Hello we recommend using the forum for faster help :)
http://www.html5gamedevs.com/forum/16-babylonjs/
