### ISSUE TITLE
bug report: PickingInfo.prototype.getNormal

### ISSUE THREAD

**Issue by sherleyyan** [BabylonJS/Babylon.js#4572]
- Bug repro on [playground](https://playground.babylonjs.com/#7PL1WY):
- Expected result:  These two lines should not be parallel. When scaling the first sphere, the normal line should vary the direction.
- Current result: There was a 'const' normal line.
- The problem: in method 'PickingInfo.prototype.getNormal', the transformation to world coordinate should be earlier than the 'Cross'  product.

**Comment by RaananW** [comment]
Does this solve the issue? https://playground.babylonjs.com/#7PL1WY#1 notice line 12, computing the world matrix again. We compute it on each frame, but if you need to change in the current frame you will need to compute it yourself

**Comment by sherleyyan** [comment]
I'm afraid not. In fact, this line is not the 'normal' line.

**Comment by RaananW** [comment]
Well, they are not parallel :smile:

Without world coordinates, it works as expected, right?  https://playground.babylonjs.com/#7PL1WY#2

**Comment by sherleyyan** [comment]
That's great! 

And there is another question: what does the 'useWorldCoordinates' exactly mean? When it was set to 'true', the result should be in the local space, or the global space?

**Comment by deltakosh** [comment]
if set to true you can get the normal in world space (to display it for instance or to get world orientation)

**Comment by deltakosh** [comment]
Actually there is a bug :)
Fixing it with #4581 
In your case to draw normal you have to set 'useWorldCoordinates' = true but because of the non uniform scaling there was a bug
