### ISSUE TITLE
Support for previewing compressed textures in Inspector

### ISSUE THREAD

**Issue by justinctlam** [BabylonJS/Babylon.js#4589]
# Feature request

If you load a model with a compressed texture, for example a DXT1 texture, I want to be able to see the texture in the inspector just like the jpg or png textures. This is the texture previewer under the texture tab in the inspector.

**Comment by Bloadrick** [comment]
Hi,

I am actually working on your request, can you give me more information ? 
For me DXT1 is a compression algorithm and it can give you a texture in png.

Can you share your texture or tell me what format of image you want to preview ?

**Comment by justinctlam** [comment]
What specific information do you need?

You can load any DXT compression image as an example. Eg container can be dds.
