### ISSUE TITLE
Animation: one child fades in instead of out

### ISSUE THREAD

**Issue by adrientetar** [BabylonJS/Babylon.js#4592]
- Bug repro on playground: https://www.babylonjs-playground.com/#LTUJIT
- Expected result: The rectangle and the cylinder with the picture should both fade out (visibility: 1 -> 0)
- Current result: The rectangle is OK, but the cylinder hides then fades in (!)

**Comment by deltakosh** [comment]
Good news! It is not a bug
When you animate the visibility, the status of the mesh move from opaque to transparent. And transparent objects are sorted back to front. So you actually see the cylinder pops up :)

To fix it, you can force Babylon.js to sort the objects based on an index:
https://www.babylonjs-playground.com/#LTUJIT#1

See lines 28 and 43

**Comment by adrientetar** [comment]
I see, thanks!
