### ISSUE TITLE
Option OcclusionQueries in 3ds max

### ISSUE THREAD

**Issue by dad72** [BabylonJS/Babylon.js#4617]
# Feature request

It would be useful to have a checkbox that would allow objects to have occlusion queries. because when a scene is big, it's very difficult to do it after.

Like checkCollision but with occlusion queries.

Thanks

**Comment by dad72** [comment]
Ah darn. But babylon does a check if webgl2, in this case, if this is checked in 3ds max, then export with a value to true, babylon will not take it into account if webgl2 is not supported ?

Or else put the checkbox and a parenthesis (for webgl2)

**Comment by deltakosh** [comment]
Well thus could be an option but I'm not a big fan of stuff that only works sometimes because then it is a nightmare to support. I will get hundred of times the same question about "why doesn't it work while I checked the check box"

**Comment by dad72** [comment]
Yes I understand. That's not wrong. I will try to find a solution (that comes to mind).

Can we add tags with 3ds max and that this tags be exported, then create a loop in js that lists the tag to put the occlusions? It's an idea that would simplify things. unless another idea comes to me.

**Comment by deltakosh** [comment]
Like the idea of the tag! Let's create a new issue:)

**Comment by dad72** [comment]
I have to create the new issue or are you going to do it ?

**Comment by deltakosh** [comment]
Please do it:)
