### ISSUE TITLE
Can write and export tags in 3ds max

### ISSUE THREAD

**Issue by dad72** [BabylonJS/Babylon.js#4618]
# Feature request

It would be useful to be able to create tags in 3ds max to group objects. then that it is exported in ways that in our script js we can create loops to list the objects of a precise tag and apply options like occlusion query or others.

Thanks.

**Comment by deltakosh** [comment]
Good idea!

**Comment by deltakosh** [comment]
https://github.com/BabylonJS/Exporters/issues/244
