### ISSUE TITLE
A scaled lines mesh disappears at certain angles

### ISSUE THREAD

**Issue by ShimShamSam** [BabylonJS/Babylon.js#462]
[In this demo](http://www.babylonjs-playground.com/#2JWIFR), I create two lines. One is visible and one isn't. The only difference between the lines is the rotation.y value.

My reason for scaling a line is to draw a "laser" between one point and another. Unless I missed something in the docs, I can't find a way to create a single lines mesh and change the coordinates, thus I have to keep creating and disposing of new lines meshes. The source code hints at using something like:

```javascript
var vertexData = VertexData.CreateLines(points);
vertexData.applyToMesh(lines, updatable);
```

While this works, there is no documentation and there seems to be a decent performance hit. Scaling the lines is much simpler for my purposes.

Additionally, the current source shows another parameter on Mesh.createLines called *linesInstance*. From what I can tell, this accepts an existing lines mesh and updates the points rather than creating a whole new mesh. However, in the most recent compiled version, I do not see this parameter.

**Comment by deltakosh** [comment]
You cannot scale a line because it is only based on a line :) For scalable "lines" you should use tubes
