### ISSUE TITLE
OBJFileLoader

### ISSUE THREAD

**Issue by individ2016** [BabylonJS/Babylon.js#4627]
I dont know where to load OBJ model for repro issue on playground, but it is easy and will perproduct with every model, that is not simmetry about ZoY.

Issue is that imported model is mirrored about ZoY, and you can fix it by scaling.x = -1.

**Comment by RaananW** [comment]
hi,

we didnt have any problem with obj loading until now. The playground supports OBJ loading, wanna try reproducing it there?

**Comment by deltakosh** [comment]
Here is an example with the Stanford bunny: https://www.babylonjs-playground.com/#8INCIV#20
And it works

**Comment by individ2016** [comment]
Ok. you see that rabbit looking for left. And try import it in 3dmax for example. You will see issue.
Better sample will be car, or something with 3d text.

**Comment by deltakosh** [comment]
understood
Do you want to submit a PR to fix the loader ?

**Comment by individ2016** [comment]
My english not so good)) What is PR?

**Comment by deltakosh** [comment]
sorry my bad: pull request

**Comment by individ2016** [comment]
well.. it is not so big problem. But it will be great if objloader be little better

**Comment by deltakosh** [comment]
Completely agree that's why I'm ok to merge a pull request if you want to do one :)

**Comment by individ2016** [comment]
Ok, lets do it))

**Comment by individ2016** [comment]
Other question, if i may do it here.. Is there sample of obj loading with texture? I think i know second issue with it..

**Comment by deltakosh** [comment]
We don't have one unfortunately :(

**Comment by deltakosh** [comment]
And thank you so much for your help

**Comment by individ2016** [comment]
nevermind. BabylonJS is best framework i ever seen

**Comment by individ2016** [comment]
well.. to reproduce second issue you need to load OBJ file with texture and mtl. And you see that model is very dark. Than you just create StandardMaterial with same parameters and same diffuseTexture and it will be normal. I think that the problem is in shader (effect), that attached to material after loading from obj

**Comment by individ2016** [comment]
i can mistake though..

**Comment by deltakosh** [comment]
If you have a obj with texture I can make it available on the playground for us to test :)

**Comment by RaananW** [comment]
We do have an MTL parser that does work (we had a batman model with textures that I can't seem to find right now).

**Comment by individ2016** [comment]
Didnt think of it.. You right. Lets create just a box with texture. It is my photo. And my box ;)

https://cloud.mail.ru/public/7UsH/K4mQ6gWBQ

**Comment by deltakosh** [comment]
Here we are: https://www.babylonjs-playground.com/#8INCIV#22

**Comment by individ2016** [comment]
You can see issue here: https://www.babylonjs-playground.com/#8INCIV#24

**Comment by deltakosh** [comment]
Interesting...this seems to come from the way we load the image (wrapping issue?)

**Comment by individ2016** [comment]
well.. i dont know what the problem exactly.. Just setted diffuseColor to be same as in StandardTexture:
https://www.babylonjs-playground.com/#8INCIV#25
But result is not same though :( It is darker

**Comment by individ2016** [comment]
But texture.. You can use exactly same texture from first imported material, but the result is not same - texture loaded correctly i think: https://www.babylonjs-playground.com/#8INCIV#26

**Comment by deltakosh** [comment]
Well...I agree this is weird..this needs some debug :)

**Comment by RaananW** [comment]
How about this? https://www.babylonjs-playground.com/#8INCIV#27

**Comment by karimhhh** [comment]
Hey
how to load obj with mtl using url 
i tried it  using BABYLON.SceneLoader.ImportMesh() , with my url of obj file and it's mtl 
and it only load the obj file without loading it's materials ,also i tried to use this line 

        BABYLON.OBJFileLoader.MATERIAL_LOADING_FAILS_SILENTLY = false;

to enforce it to load the materails and still Useless.
plz help

**Comment by individ2016** [comment]
> plz help

Did you seen what is in your mtl file? I mean file paths.. Is it correct?

**Comment by karimhhh** [comment]
I don't know what is the file paths
but when i tried to load this obj and mtl  localy (in project file) it worked great and loaded with it's materails
but  when i tried to upload it (obj and mtl) and imported it using url it load the obj file only without materails 

--
u can access this file too , hope anyone solve this

https://quizgametesting.000webhostapp.com/BtcObj/

**Comment by karimhhh** [comment]
screenshot of mtl file

![image](https://user-images.githubusercontent.com/6688936/54296222-2ac1f300-45bd-11e9-9f6c-739b59ce6369.png)

**Comment by individ2016** [comment]
> screenshot of mtl file

And where is texture files here?
What you mean, when tell us that mtl does not loaded?

**Comment by karimhhh** [comment]
there is no texture's here dude 
it just a solid color (no images)
--
i mean it load the obj it self without it's  materails

(Without material)
![image](https://user-images.githubusercontent.com/6688936/54296680-09add200-45be-11e9-91cb-57396cfa4935.png)

(With material) 
![image](https://user-images.githubusercontent.com/6688936/54296823-3f52bb00-45be-11e9-9942-2ea98427136e.png)

**Comment by deltakosh** [comment]
pinging @brianzinn

**Comment by brianzinn** [comment]
I'm able to load it in my local playground with just changing the locations from the example "Load glTF model".
![image](https://user-images.githubusercontent.com/542756/54329691-f0158600-45cf-11e9-842d-1109dffc1f03.png)

This works when I point it at your webserver, though.
```javascript
BABYLON.SceneLoader.Append("https://quizgametesting.000webhostapp.com/BtcObj/", "Btco.obj", scene, function (newMeshes) {
        scene.activeCamera = null;
        scene.createDefaultCameraOrLight(true);
        scene.activeCamera.attachControl(canvas, false);
    });
```
If you are loading from elsewhere then  this may be a CORS or http server issue (ie: MIME types) on your MTL file when you are loading from a URL.  Can you share a repro, because for me it is working.  Thanks.

**Comment by karimhhh** [comment]
Thank you guys so much ,I am really appreciate this
I just noticed my mistake , the problem is that i was putting the whole obj url in "sceneFilename" parameter
without split it to two parts "rootUrl" and "sceneFilename" 
i tried to split it and it worked fine ,i think that was my problem 

And i have other question  about the ability of make babylonjs *import fbx*  models also like threejs
is it possible even if soon or in next version ?

thx anyway
@brianzinn  @deltakosh

**Comment by deltakosh** [comment]
fbx are not supported for now but if someone is motivated to write a loader I will gladly merge it:)
