### ISSUE TITLE
TextBlock line-wrapping improvements

### ISSUE THREAD

**Issue by adrientetar** [BabylonJS/Babylon.js#4642]
I'm looking to do line-wrapping on TextBlock, but there are a couple things missing:

- I need to be able to get the final size of the block at creation time. Currently it seems one oughta wait until the TextBlock is rendered to get that (textBlock.height/heightInPixels isn't set), but I want to size my enclosing elements based on the size of the TextBlock so I'd need the value right away.
- Looking at [textBlock.ts](https://github.com/BabylonJS/Babylon.js/blob/6d569bfece6d10b39323bb29c49c376d223c53ff/gui/src/2D/controls/textBlock.ts), the line breaking algorithm only uses LF and space as line-wrapping opportunities. To be robust from an i18n perspective it should rather use the Unicode line breaking algorithm ([UAX &#0035;&#xfeff;14](http://unicode.org/reports/tr14/)) – which [niklasvh/css-line-break](https://github.com/niklasvh/css-line-break) seems to be a solid implementation of.

**Comment by deltakosh** [comment]
Good plan! We can definitely make the size computation function publicly available

For the line breaker, also agree as long as it is not slowing things down

**Comment by adrientetar** [comment]
Cool, might take a look at this - does Babylon take dependency on 3rd party libs and how would I go about adding one?

**Comment by deltakosh** [comment]
nope we try to avoid for main features as we want to keep bjs simple to reference and use
Appreciate the help a lot!


if you think it is mandatory we can think about adding a textblock extension in the extension repo but this will lead to less usage

**Comment by adrientetar** [comment]
Uhm, how does no-dependencies make things simpler given that you release as a single JS file?

Well I guess you can copy-paste the code to this repo, but everything Unicode is [some data tables](https://github.com/niklasvh/css-line-break/blob/master/src/LineBreak.js) and [data structure](https://github.com/niklasvh/css-line-break/blob/master/src/Trie.js) so it's more practical to have it as a distinct/reusable library, afaict.

**Comment by deltakosh** [comment]
No problem to have a dependency but it has to be moved to extensions repo
No worry then

**Comment by adrientetar** [comment]
Any suggestion of API to expose the size calculation directly? —the size of the text block will depend on that of its parent(s), yes? So then should the size calculation request a traversal of the widgets tree w/ measurements calculation?  
In my case I think I just want to set the width and get the height back but that size API should handle all cases presumably?

**Comment by deltakosh** [comment]
Well this is a really good question. I wanted to introduce this change multiple times.
First do a measure and then an arrange (like XAML if you know it).My problem is that it will involve traversing the tree 3 times (measure, arrange and draw)

**Comment by adrientetar** [comment]
I've been looking to expose a simple API to just get the expected height, but how do I get a 2d context for measurements from TextBlock?
