### ISSUE TITLE
An issue with babylon.worker.js + babylonjs.materials.js + webpack.

### ISSUE THREAD

**Issue by kkimdev** [BabylonJS/Babylon.js#4646]
I've noticed that babylonjs.materials.js has `require("babylonjs")` statement and it causes for webpack to bundle babylon.js always even if the app uses babylon.worker.js instead. I think ideally it should be straightforward to change the linkage.

I'm not sure if there is an easy way to do given the current distribution structure.  Or if there is, I guess it's good to update the document? https://doc.babylonjs.com/features/npm_support

**Comment by RaananW** [comment]
Using webpack you can configure the file to be loaded when requiring "babylonjs".
You can do the following:

(from https://webpack.js.org/configuration/resolve/) 

```javascript
module.exports = {
  //...
  resolve: {
    alias: {
      babylonjs: path.resolve(__dirname, 'node_modules/babylonjs/babylon.worker.js')
    }
  }
};
```
