### ISSUE TITLE
1000 animations / frame rate drops from 60 to 30ish

### ISSUE THREAD

**Issue by yosun** [BabylonJS/Babylon.js#4647]
- Bug repro on [playground](https://playground.babylonjs.com): https://www.babylonjs-playground.com/#QYFDDP#48
- Expected result: Post Instantiation runtime animation should be more performant 
- Current result: Runtime animation drops 10x10x10 cube configuration from 60fps to 30fps https://gyazo.com/f9a1acc4d69608fe306aafac3c673a3d

**Comment by deltakosh** [comment]
Also even if rendering is improved by instances you are animating the 1000 meshes
The animation engine has to go through all meshes manually on the cou side causing the frame drop

Please start a thread on the forum if you want to discuss ideas for optimizations

**Comment by deltakosh** [comment]
For instance solid particles could be a fine for your need: https://doc.babylonjs.com/how_to/solid_particles
