### ISSUE TITLE
Debug layer statistics are confusing

### ISSUE THREAD

**Issue by andyhall** [BabylonJS/Babylon.js#465]
Some of the debug layer statistics report confusing data.

 1. "Total meshes" includes all meshes in the scene regardless of state, while "Total vertices" excludes some (though not all) inactive contents.
 2. "Total vertices" reports vertices, while "Active vertices" is actually counting **indices**.

As a new user these were quite confusing. I haven't checked other statistics in detail.

**Comment by deltakosh** [comment]
What do you propose?

**Comment by andyhall** [comment]
I think it would be clearest for "total vertices" to report the total of all vertices in the scene (regardless of culling, etc.), because the other "total" stats (bones, meshes, etc..) are doing that. (I think?)
Incidentally right now "total vertices" is the count of vertices *after* octree/LOD culling but *before* per-mesh frustum culling, which confused me.

As for "active vertices", it's currently [counting indices](https://github.com/BabylonJS/Babylon.js/blob/master/Babylon/babylon.scene.ts#L1164). Is that by design?

**Comment by deltakosh** [comment]
Agree for total, but I do not want to parse all meshes before octree selection just to get a number :(
I will rename active vertices to active indices

**Comment by andyhall** [comment]
That makes sense about not parsing meshes. Though in that case, I think it would be clearer to simply remove "total vertices". 

Or maybe skip "total vertices" when `scene._selectionOctree` is set? Then it would basically be accurate I think.
