### ISSUE TITLE
GlowLayer doesn't work in alpha.10

### ISSUE THREAD

**Issue by menduz** [BabylonJS/Babylon.js#4666]
alpha.9:
![image](https://user-images.githubusercontent.com/260114/42233513-2f5fdc2c-7ec8-11e8-82a8-2e09cf3008db.png)
![image](https://user-images.githubusercontent.com/260114/42233585-5da00ddc-7ec8-11e8-8420-ea0e7c901f4b.png)

alpha.10:
![changematerial 1](https://user-images.githubusercontent.com/260114/42233552-44f5bb1a-7ec8-11e8-8dff-a103e7e041b8.png)
![materialmutation 1](https://user-images.githubusercontent.com/260114/42233591-6216b65e-7ec8-11e8-8e3d-61f8e60e6f2f.png)

#### Creating with

```ts
const effectLayers: BABYLON.EffectLayer[] = []
effectLayers.push(new BABYLON.GlowLayer('glow', scene))
```

Feel free to close this issues if they don't contain enough information.

**Comment by deltakosh** [comment]
Can you repro in the playground?

**Comment by sebavan** [comment]
A repro in the pg would be amazing as I did some recent changes and might have introduce a regression. 

Unfortunately, my test pg are all still ok so I can not identify the issue.

**Comment by menduz** [comment]
@sebavan

**Comment by sebavan** [comment]
Ohhhhh interesting, there should not be any component._effectLayers anymore as we are only targetting the scene now.

What version are you using npm, cdn ?

**Comment by menduz** [comment]
npm, alpha.10

**Comment by menduz** [comment]
Well... I have more information:
Just after the GlowLayer is created, it appears both in the `scene.effectLayers` and in `EffectLayerSceneComponent._effectLayers`.

IDK when it disappears from that array.

**Comment by sebavan** [comment]
yup it should be only scene.effectLayers I ll fix it today and we ll redeploy npm tomorrow.

**Comment by sebavan** [comment]
Actually the code is ok on the cdn Let s check on the next npm push tomorrow

**Comment by menduz** [comment]
Take a look at this line https://github.com/BabylonJS/Babylon.js/blob/5269bc8602b71125c30d36aff75be8dd72beb085/src/Layer/babylon.effectLayerSceneComponent.ts#L76

It makes sense that those are duplicated.

**Comment by RaananW** [comment]
I will update npm tomorrow to alpha.11 with the fix. Seems like it wasn't in the master when i pushed alpha.10

**Comment by deltakosh** [comment]
I'll do it later today as we have more fix to push in it :)

**Comment by deltakosh** [comment]
Done!

**Comment by menduz** [comment]
Verified, fixed in alpha.11

**Comment by deltakosh** [comment]
pinging @sebavan

**Comment by menduz** [comment]
Thanks, I'll put debug information here. 

I'm receiving two messages in the console:

```
Babylon.js engine (v3.3.0-alpha.11) launched
babylon.js:4 BJS - [12:34:33]: Babylon.js null engine (v3.3.0-alpha.11) launched
```

**Comment by sebavan** [comment]
Could you confirm it is not linked to the _effectLayers in the component as you were seeing before ?

A repro in the playground would be really helpful if possible ?

**Comment by deltakosh** [comment]
Cam I close?

**Comment by deltakosh** [comment]
Closing for now. Please reopen if the bug is still present
