### ISSUE TITLE
[Bug] (Some?) animations consume more CPU with time

### ISSUE THREAD

**Issue by fmmoret** [BabylonJS/Babylon.js#4673]
# Bugs

- Bug repro on [playground](https://www.babylonjs-playground.com/index.html#4GJCJ3)
- Expected result: I expect my game to perform in a consistent way & not degrade as time passes.
- Current result: My game goes from ~10% cpu to 100% after a few minutes of idle animation.

I binary searched the commits & narrowed it down to this PR https://github.com/BabylonJS/Babylon.js/pull/4563

If I revert this change, my game does not degrade with time.

Here's a screenshot of the profiler output. The listener curve is truncated, but it's a saw-tooth & doesn't leak upward / accumulate beyond a certain point.
![untitled 2](https://user-images.githubusercontent.com/5396858/42251537-daecddd2-7eec-11e8-9938-3a00b634b9e8.png)

**Comment by deltakosh** [comment]
Thanks a lot for finding this!!
Will fix it asap :)

**Comment by deltakosh** [comment]
Do you have a repro in the PG that can help us fix it?

**Comment by fmmoret** [comment]
I'll try to craft one

**Comment by deltakosh** [comment]
Much appreciated

**Comment by fmmoret** [comment]
Updated post & https://www.babylonjs-playground.com/index.html#4GJCJ3

**Comment by fmmoret** [comment]
This playground abuses the crap out of the issue. I would suggest profiling within the first 10 seconds of opening it & then let it run in a fresh window for a couple minutes and then check your CPU. The difference is vast. 

If you switch the version to latest, you won't see any degrade of experience (though it's still choppy b/c the code is very adversarial).

**Comment by deltakosh** [comment]
Thanks this is perfect
@bghgary will probably check on thursday as tomorrow is 4th of july :)

**Comment by fmmoret** [comment]
Sounds good. You guys will probably hear from me a lot. I'm working on a 3d fighting game that touches nearly every part of the babylon codebase & pushes it pretty hard. The regressions are easy to catch (though tough to narrow down).

Cheers

**Comment by deltakosh** [comment]
Well this is an excellent news!!! More than happy to fix everything you can find :D

**Comment by bghgary** [comment]
It looks like the playground code is creating new animation objects every time `objectTick` is called. This is definitely going to leak. You can see this if you type `BABYLON.Engine.LastCreatedScene.animatables` in the debug console. This array just keeps growing and growing as calling `scene.beginDirectAnimation` will just keep adding to the list.

@fmmoret
> I binary searched the commits & narrowed it down to this PR #4563

I'm not sure what you are seeing with this. My PR makes it such that animations can have only one frame. Without this change, the code in your playground doesn't work at all since it immediately throws an exception.

**Comment by fmmoret** [comment]
Did you visit the playground link on stable vs not: 

https://www.babylonjs-playground.com/index.html#4GJCJ3
https://www.babylonjs-playground.com/indexStable.html#4GJCJ3

**Comment by fmmoret** [comment]
And https://github.com/BabylonJS/Babylon.js/blob/master/src/Animations/babylon.animatable.ts#L381 they should be getting cleaned up when they finish. I estimate that your early return is bypassing some clean-up mechanism down the road.

**Comment by fmmoret** [comment]
`BABYLON.Engine.LastCreatedScene.animatables` doesn't grow on stable -- stays at a flat 3-4 depending on how fast setInterval kicks off the next function call

**Comment by deltakosh** [comment]
Makes sense to me

**Comment by bghgary** [comment]
Agreed. The animatables should be removed on end. I'll look at it more.

**Comment by fmmoret** [comment]
It's https://github.com/BabylonJS/Babylon.js/blob/master/src/Animations/babylon.animatable.ts#L372 getting the wrong value back from https://github.com/bghgary/Babylon.js/blob/ee0b2ad49a57c9094337ae9385bce749c986daea/src/Animations/babylon.runtimeAnimation.ts#L408

**Comment by deltakosh** [comment]
Agree, should just return loop instead of !loop

**Comment by fmmoret** [comment]
I think it should be `return loop;` ? If we're looping, we're definitely still running, and if we're not -- we're done b/c its just one frame.

**Comment by bghgary** [comment]
Yes, I relied on the comment too much. But I don't think that's the only issue.

**Comment by menduz** [comment]
I'm having the same issue but it is consuming that much CPU because of the garbage collector

<img width="1327" alt="image" src="https://user-images.githubusercontent.com/260114/42339307-01fca14c-8063-11e8-9f35-003c72877810.png">

The function `_registerTargetForLateAnimationBinding` is allocating 50% of the memory of Decentraland

**Comment by deltakosh** [comment]
We need memory to blend animation together unfortunately, We need to keep track of all animations targeting the same object/path and then resolve the merge

**Comment by deltakosh** [comment]
Do you have a lot of blended animations?

**Comment by menduz** [comment]
Yes... several, less than 10 tho, we made an adapter for animations and the default interface creates weighted animations even if you decide to play only one animation at 100% or the model has only one animation.

https://docs.decentraland.org/sdk-reference/entity-interfaces/#gltf-models

**Comment by deltakosh** [comment]
Well we can try to see if I can optimize that :)
can you repro something in the PG that shows this problem?
