### ISSUE TITLE
Every link to custom Playground point to default playground

### ISSUE THREAD

**Issue by nathanidp** [BabylonJS/Babylon.js#4679]
Currently every demo or other links to a babylonJs playground redirect to the default playground website.

**Comment by RaananW** [comment]
are you refering to the doc page?

**Comment by RaananW** [comment]
I can only assume this is the same as this - https://github.com/BabylonJS/Babylon.js/issues/4680

**Comment by nathanidp** [comment]
Not only the doc pages but every playground forked and saved
Like this one : https://www.babylonjs-playground.com/#3QW4J1#1
or this one : https://www.babylonjs-playground.com/#MJ6YSM

Who redirect to https://babylonjs-playground.com which is the default playground. I believe the problem is the same between the issue you mentionned.

**Comment by deltakosh** [comment]
Ok problem fixed!
thank you for the heads up :)

**Comment by deltakosh** [comment]
Wait!! No still failing:(

**Comment by deltakosh** [comment]
good now
