### ISSUE TITLE
arcRotateCamera pinch direction is opposite

### ISSUE THREAD

**Issue by lfung** [BabylonJS/Babylon.js#468]
I think it's great that pinching is now available!

But it goes in the opposite direction that I'd expect.   When I pinch my fingers together, I expect that it moves the center of interest (and the objects) farther away.  When I move my fingers apart, it should bring the center of interest (and the objects) closer to the eye.

I suspect it means reversing the default pinch direction in attachControl() where _onPointerMove() is defined. But tbh I haven't looked closely at the code yet.
-Lisa.

**Comment by deltakosh** [comment]
Hey I suggest adding a boolean parameter to allow people to select direction :)

**Comment by lfung** [comment]
That is a good idea!  Do you have anything against a default value for this new parameter?
-Lisa.

**Comment by deltakosh** [comment]
Not at all this is perfectly fine. Do you want to submit a PR?

**Comment by RaananW** [comment]
hi @lfung , any progress on this one? 2.1 is almost out, would be great having that in the final release.

**Comment by lfung** [comment]
Hi Raanan,
Sorry, I did not have time to work on this.  Please proceed without my input.
-Lisa.
