### ISSUE TITLE
Attempting to save playground gives 500 internal server error

### ISSUE THREAD

**Issue by zakhenry** [BabylonJS/Babylon.js#4680]
When trying to save any snippet in the playground a `500 internal server error` response is returned from `POST https://babylonjs-api2.azurewebsites.net/snippets`. The ui displays `Unable to save your code. It may be too long.` which is unlikely to be the issue (I'm trying to save the default demo)

<img width="1284" alt="screen shot 2018-07-05 at 10 00 25" src="https://user-images.githubusercontent.com/721513/42313324-5af44a4e-803a-11e8-91fc-bd2204cef809.png">

**Comment by RaananW** [comment]
Hi,

Thanks, just noticed that as well. We are investigating and will repair that asap

**Comment by deltakosh** [comment]
Fixed
