### ISSUE TITLE
Problem with orthographic camera and picking

### ISSUE THREAD

**Issue by Skleni** [BabylonJS/Babylon.js#469]
I've got a camera with its mode set to ORTHOGRAPHIC_CAMERA and want to let the user pick objects with the mouse, like this:

http://www.babylonjs-playground.com/#HA7OJ#4

The sample draws some boxes on a plane. When you click on a box, it should draw a red selection indicator beneath it. However, this only seems to work in the upper half of the canvas. No matter how you rotate the camera, picking only works for the boxes above an imaginary line in the center of the screen.
When when you look at the scene from below (so that the ground vanishes), the lower half works, but the upper half doesn't.

**Comment by samuelgirardin** [comment]
Hi, 

try this : 

http://www.babylonjs-playground.com/#HA7OJ#5

**Comment by samuelgirardin** [comment]
I just set your cam like this : 

var camera = new BABYLON.FreeCamera("camera", new BABYLON.Vector3(300, 150, -300), scene);

**Comment by Skleni** [comment]
Thank you! That works, but to be honest I don't fully understand why that solved the problem. Could you give a little more details? Thanks!

**Comment by samuelgirardin** [comment]
I already had the same problem, in fact I suppose your first camera was too close of your objects.
