### ISSUE TITLE
Resource destruction and memory recycling

### ISSUE THREAD

**Issue by sherleyyan** [BabylonJS/Babylon.js#4691]
- Link 
  I am sorry I was not able to create a topic on the forum because I failed to upload  a picture, which was seemed to be required.

- Feature description： 
When I created a scene, I added some models and effects (like reflections with ReflectionProbe, and linked some meshes to them).
After I had unlinked the linked meshes from the probes, and disposed any meshes and probes, I found out that not all of the data had been destroyed, as well as some Matrixes, UniformBuffers, and so on. They were still held by some private properties like '_renderingTarget'.

Do you have any idea of 'clear' the cache when mesh or a probe is disposed?

**Comment by deltakosh** [comment]
Hello, could you provide a repro on our playground?
Technically disposing meshes and probes should be enough

**Comment by deltakosh** [comment]
Well in your sample, I can see that you are not disposing the probes created by the generateSatellite function

**Comment by sherleyyan** [comment]
And the UniformBuffer related to a mesh (or material?) cannot be disposed neither.

**Comment by deltakosh** [comment]
Hello Sherley,
If you call material.dispose, this line will be executed:
https://github.com/BabylonJS/Babylon.js/blob/master/src/Materials/babylon.material.ts#L1302

Can you provide a repro that highlights your issue?

**Comment by deltakosh** [comment]
Up?

**Comment by deltakosh** [comment]
Closing for now. Please reopen if needed :)
