### ISSUE TITLE
ArcRotateCamera Alpha radius problem?

### ISSUE THREAD

**Issue by wwepenguin** [BabylonJS/Babylon.js#4693]
https://github.com/BabylonJS/Babylon.js/blob/46b82f38e1c8f4b6fdf9336c95c33489193607f3/src/Cameras/babylon.arcRotateCamera.ts#L579

if i set 
lowerAlphaLimit  = 3.14;
upperAlphaLimit = 0 ;
it can't limit at alpha > 0 case

**Comment by RaananW** [comment]
You are totally right. Will be fixed soon
