### ISSUE TITLE
Componentize engine and scene

### ISSUE THREAD

**Issue by deltakosh** [BabylonJS/Babylon.js#4702]

**Comment by sebavan** [comment]
Here is the list of components migrated during our test phase:
- GamepadSystemSceneComponent
- LayerSceneComponent
- SimplicationQueueSceneComponent
- PostProcessRenderPipelineManagerSceneComponent
- BoundingBoxRenderer
- DepthRendererSceneComponent
- GeometryBufferRendererSceneComponent

Here is the list of components still in progress of migration:
- [ ] PostProcess
- [ ] ProceduralTexture
- [ ] OutlineRenderer
- [ ] Sprite
- [ ] Particle
- [ ] RenderTarget
- [ ] Shadow
- [ ] ActionManager
- [ ] Animations
- [ ] Physics
- [ ] Audio
- [ ] Helpers
- [ ] Octree
- [ ] EdgesRenderer
- [ ] LineEdegesRenderer
