### ISSUE TITLE
Child mesh removed when scene optimiser run

### ISSUE THREAD

**Issue by zakhenry** [BabylonJS/Babylon.js#4704]
- Bug repro on https://playground.babylonjs.com/#5F4SC5
- Expected result: Scene is optimised, but all meshes remain visible
- Current result: Child meshes are removed. If the mesh is not a child, the mesh stays visible.

I suspect this might actually be caused by the same root cause of #4558 ?

**Comment by deltakosh** [comment]
Will check that asap
