### ISSUE TITLE
VR - Six degrees of freedom not functioning in Edge/Windows MR

### ISSUE THREAD

**Issue by Exolun** [BabylonJS/Babylon.js#4713]
**Description**
While trying to reproduce a different VR bug, I noticed in the playground that my VR headset is no longer moving like a 6-dof device in the playground.  It turns like a 3-dof device and doesn't respond to any height / head tilt movements as I would expect it to.

Bug repro on [https://www.babylonjs-playground.com/#HWQGP2#3](https://www.babylonjs-playground.com/#HWQGP2#3)

**Steps to reproduce:**
- Load the above link in Edge
- Click the view in VR button
- Equip headset
- Move your head closer / further from the sphere or up/down/sideways

Expected result:  Head movements affect distance from sphere / ground
Actual result:  Head movements are ignored as though the headset only has gyro sensors

**Environment Details**
- Browser:  Microsoft Edge 42.17134.1.0
- Headset:  Lenovo Explorer
- Graphics Card:  GeForce GTX 1080 Ti

**Comment by TrevorDev** [comment]
@Exolun It looks like the objects in your scene are very large and far away so like when looking at a mountain in the distance, moving your head doesn't have much of an effect. After resizing, it seems to work as expected: https://www.babylonjs-playground.com/#HWQGP2#5

**Comment by TrevorDev** [comment]
Closing this, if you are still having issues feel free to reopen.
