### ISSUE TITLE
Z Fighting with transparent planes

### ISSUE THREAD

**Issue by menduz** [BabylonJS/Babylon.js#4715]
There are two planes on the floor, depending on the position of the camera, the first one is behind the second. 

Repro: https://www.babylonjs-playground.com/#UCORW#10

![z fight bug](https://user-images.githubusercontent.com/260114/42475765-003f3d6e-83a2-11e8-9257-e9998a7721d9.gif)

Edit: In the repro, the planes are separated by 0.001 in the Y-axis. That also happens if we separate the entities any distance (like 1 meter from each other)

**Comment by deltakosh** [comment]
Please use the forum for questions :)
This is not a bug. You have to use alphaIndex to define which one must go first as they are at an equivalent distance from the camera:
https://www.babylonjs-playground.com/#UCORW#11

**Comment by menduz** [comment]
@deltakosh please read the "edit" of the issue and reopen. 

It only seems to happen if we move one of the planes in the X axis, if both share the same X works as expected. And it only seems to happen with PBRMaterial.

Update with perspective:
![z fight 2](https://user-images.githubusercontent.com/260114/42477078-4a216426-83a6-11e8-8445-c3aae2be3d33.gif)


We are betting on you guys, on Babylon, please do not dismiss the issues like this, we have been working months with Babylon without raising any issue to not make noise and learning the tool in the meantime, this is free QA! We are trying to contribute to the overall quality of this library by using the bleeding edge alpha version, this bugs will happen. Otherwise, we have to stick to the "stable" release and this kind of bug hunt cannot be done.



--- 
https://www.babylonjs-playground.com/#UCORW#12
Here is another one. Things disappear, the bounding box is there
![dissapearing](https://user-images.githubusercontent.com/260114/42476923-d9f18a0a-83a5-11e8-8d87-ea87b7997c0e.gif)

In this case, the planes seem to disappear when the box occludes them.

**Comment by deltakosh** [comment]
No need to escalate or beg for anything. That won't work  :)
I only ask you to start with the forum first. You are using a free engine and you kind of expect paid support.

Did you try with the alphaIndex I mentioned? Can you provide a better repro as I fixed the first PG with the alphaIndex.

Other option would be to add remove opacityTexture from the ground so the ground will be able to write to depth buffer: https://www.babylonjs-playground.com/#UCORW#13

**Comment by deltakosh** [comment]
So not a bug for now, hence the closed issue :)
If you manage to prove it is a bug I will publicly apologize obviously :D

**Comment by deltakosh** [comment]
And please, don't get me wrong. I want to help you at 150%!! I want you guys to be more than happy with Babylonjs and I want to make sure that you have no blocker.

But as we are a really tiny team, I really need the help of the community to achieve this goal hence the forum first when it is not an obvious bug

**Comment by menduz** [comment]
:+1: we will try to filter those issues even more, thanks.
