### ISSUE TITLE
Shadow Issue with RenderingGroup

### ISSUE THREAD

**Issue by sebavan** [BabylonJS/Babylon.js#4729]
cc: @PixelsCommander 

Following on https://github.com/BabylonJS/Babylon.js/issues/4463#issuecomment-404217046

Extracted from the issue:

2 shadows should be present http://playground.babylonjs.com/#6T9SI9#4
Without generator.usePercentageCloserFiltering = true; the second appears

A similar issue is reproducible in a demo here http://www.babylonjs-playground.com/#R1EVD0#3 but this time with another property of shadowGenerator.useBlurExponentialShadowMap = true; and no rendering groups. Basically, the demo is broken currently.

**Comment by sebavan** [comment]
The point 2 should be adressed by https://github.com/BabylonJS/Babylon.js/commit/39f0d72293aa8c79bbd267645c93a5bb823fd84b

I ll fix the first one in the afternoon.

**Comment by sebavan** [comment]
About the  1st one it comes down to renderingGroup setup not being shared with rendertarget texture.

I ll carry over the setting for PP, Shadow, Probe and Mirror.

**Comment by sebavan** [comment]
Will be close with the attached PR.

**Comment by PixelsCommander** [comment]
It fixes DirectionalLight but still does not work with SpotLights. Changed the demo http://playground.babylonjs.com/#6T9SI9#5

**Comment by sebavan** [comment]
IT seems that there is no shadow on this scene even without the rendering group ?
http://playground.babylonjs.com/#6T9SI9#6

The angle of the spot is too large to allow shadow:
http://playground.babylonjs.com/#6T9SI9#5
