### ISSUE TITLE
Billboards don't face camera with non-moving parent

### ISSUE THREAD

**Issue by andyhall** [BabylonJS/Babylon.js#473]
Similar to previous billboard issues.
http://www.babylonjs-playground.com/#NVAOX#3
Tap to stop/start the camera's parent and see the issue.

**Comment by deltakosh** [comment]
Sorry but I do not reproduce
Did you clean your cache in order to use latest version?

**Comment by deltakosh** [comment]
Ok I can reproduce :)
Working on a fix

**Comment by andyhall** [comment]
Confirmed, thanks!
