### ISSUE TITLE
Babylon in an Ember component, Error: renderingGroup.prepare is not a function

### ISSUE THREAD

**Issue by DanLeininger** [BabylonJS/Babylon.js#474]
Hi, I'm attempting to use Babylon within EmberJS, in a comoponent, and am getting the following error on scene.render():
```
renderingGroup.prepare is not a function
```
Here is the code for the component (works fine outside of Ember), any ideas? 

```
import Ember from 'ember';

export
default Ember.Component.extend({
    buildScene: function() {
        var self = this;
        var canvas = document.getElementById("renderCanvas");
        var engine = new BABYLON.Engine(canvas, true);
        var scene = new BABYLON.Scene(engine);

        // This creates and positions a free camera (non-mesh)
        var camera = new BABYLON.FreeCamera("camera1", new BABYLON.Vector3(0, 5, -10), scene);

        // This targets the camera to scene origin
        camera.setTarget(BABYLON.Vector3.Zero());

        // This attaches the camera to the canvas
        camera.attachControl(canvas, true);

        // This creates a light, aiming 0,1,0 - to the sky (non-mesh)
        var light = new BABYLON.HemisphericLight("light1", new BABYLON.Vector3(0, 1, 0), scene);

        // Default intensity is 1. Let's dim the light a small amount
        light.intensity = 0.7;

        // Our built-in 'sphere' shape. Params: name, subdivs, size, scene
        var sphere = BABYLON.Mesh.CreateSphere("sphere1", 16, 2, scene);

        // Move the sphere upward 1/2 its height
        sphere.position.y = 1;

        // Our built-in 'ground' shape. Params: name, width, depth, subdivs, scene
        var ground = BABYLON.Mesh.CreateGround("ground1", 6, 6, 2, scene);
        engine.runRenderLoop(function() {
            scene.render();
        });
        window.addEventListener("resize", function() {
            engine.resize();
        });
    }.on('didInsertElement'),
});
```
Thanks,
Dan

**Comment by deltakosh** [comment]
Oh! I've already seen this. This is because ember redefine the array prototype :( You have to define array.prototype.prepare() to fix it

**Comment by DanLeininger** [comment]
Thanks for the quick answer @deltakosh, where would I define it, overwrite the renderingGroup.prepare() function?

**Comment by deltakosh** [comment]
I think so, from what I can remember this is due to Ember that redefine array prototype like: array.prototype = foo

**Comment by DanLeininger** [comment]
The (sort of) solution to this issue is to disable prototype extensions in Ember, you can do that by changing some environment variables in config/environment.js (Ember CLI):
```
EmberENV: {
    EXTEND_PROTOTYPES: false
}
```
This will disable all prototyping in Ember, which will force you to rewrite / change syntax on a bunch of stuff, see here:

http://guides.emberjs.com/v1.10.0/configuring-ember/disabling-prototype-extensions/

The only conflict specifically with Babylon.js are the Arrays, so you can also use:
```
EmberENV: {
    EXTEND_PROTOTYPES: {
        String: true,
        Array: false,
        Function: true
    }
}
```
Which will keep Ember's prototyping on Strings and Functions, but remove it for Arrays.  Then in your project, you'll need to find any Arrays you've declared as properties (you only need to do the ones you yourself declared) and convert them to Ember Arrays like so:
```
//Old Array
var myArray = [1, 2, 3, 4];

//New Array
var myArray = [1, 2, 3, 4];
Ember.A(myArray); // converts it to an Ember Array
```
Then things should work.  I'm not sure if turning Babylon into AMD (#62) would fix this altogether.  Also / alternatively, it'd be great if you could set the extend properties in Ember on a per component basis.
