### ISSUE TITLE
Sky extension reflection support

### ISSUE THREAD

**Issue by kkimdev** [BabylonJS/Babylon.js#4744]
Babylonjs has sky extension that supports parametic sky rendering via shader https://doc.babylonjs.com/extensions/sky .  But to my understanding there is no easy way to set this as reflection texture for objects.

Though I'm not sure where would be the best place to implement this. Perhaps it could be as simple as updating the doc explaining how to save rendered material to texture and use it as a cubemap, or providing an API that does it.

**Comment by deltakosh** [comment]
This is correct. Perhaps @julien-moreau can help?

**Comment by kkimdev** [comment]
@julien-moreau oh great, thanks!! =D

**Comment by kkimdev** [comment]
@julien-moreau Yeah you're right, I was able to use the probe with the sky extension.

```javascript
const probe = new BABYLON.ReflectionProbe('', 8, scene);
probe.renderList.push(skybox);
probe.refreshRate = BABYLON.RenderTargetTexture.REFRESHRATE_RENDER_ONCE;
shape.material.environmentTexture = probe.cubeTexture;
```

**Comment by julien-moreau** [comment]
Yeaaaaah ! I created a playground here :)
https://www.babylonjs-playground.com/#4R1H1U

**Comment by julien-moreau** [comment]
Do you think that it is really interesting to add this trick in the documentation?

**Comment by deltakosh** [comment]
I vote for!

**Comment by kkimdev** [comment]
I think it's good to include in the skybox extention doc since it's a common technique.  Regular skybox doc also explains reflection texture https://doc.babylonjs.com/how_to/skybox

**Comment by julien-moreau** [comment]
Okay will PR asap ! :)

**Comment by julien-moreau** [comment]
Pull request done :)
https://github.com/BabylonJS/Documentation/pull/1125
