### ISSUE TITLE
TextBlock: updating fontFamily does not trigger rerender

### ISSUE THREAD

**Issue by vfabioux** [BabylonJS/Babylon.js#4748]
- Bug repro on [playground](https://playground.babylonjs.com): https://www.babylonjs-playground.com/#XCPP9Y#573
- Expected result: Changing TextBlock fontFamily should change its font on screen on next frame.
- Current result: Changing it does not update the TextBlock on screen ; it does update only when something else is changed on the TextBlock (the left property in the bug repro).

**Comment by deltakosh** [comment]
Thanks! I'm checking this one right now
