### ISSUE TITLE
gltf: rendering issue on animated character model with toon-outline effect 

### ISSUE THREAD

**Issue by vtange** [BabylonJS/Babylon.js#4760]
I am testing simple animation (just head turning) with gltf files. There were some rendering issues that I opened an issue about in the blender-gltf exporter. We've gotten to the point where it renders fine in three.js but displays artifacts in Babylon.js.

This is what I see in my not-up-to-date-Babylon.js. Earlier in the issue mentioned below the black artifact was larger. The playground somehow fully hides the black artifact but shows holes on the model.
![animationblack](https://user-images.githubusercontent.com/4667949/42720622-2b44699a-86df-11e8-8a2b-e085fb748d14.gif)

The hunch is this is related to uint32 indices in the model due to the toon outlines.

Further discussion and .blend files can be seen:
https://github.com/KhronosGroup/glTF-Blender-Exporter/issues/240

Playground:
https://playground.babylonjs.com/#XRQZX7#2

**Comment by deltakosh** [comment]
Thanks @bghgary
