### ISSUE TITLE
creating new instances should not modify the existing meshes

### ISSUE THREAD

**Issue by TrevorDev** [BabylonJS/Babylon.js#4762]
# Bugs

- Bug repro on [playground](http://localhost:1338/Playground/index-local.html#123B18#1):
- Expected result:
creating new instances should not modify the existing meshes
- Current result:
creating new instances does modify the existing meshes

**Comment by deltakosh** [comment]
This is expected actually.
To make sure you can create an instance from a cloned mesh, you have to first call mesh.makeGeometryUnique(): https://www.babylonjs-playground.com/#123B18#6

I will improve documentation and code comments
