### ISSUE TITLE
[Inspector - Feat.Requ.] Show code tooltips

### ISSUE THREAD

**Issue by Vinc3r** [BabylonJS/Babylon.js#4772]
# Feature request

Like said in this [forum message](http://www.html5gamedevs.com/topic/33982-whats-next/?do=findComment&comment=221902), it could be a nice enhancement to get some infos inside popups﻿ for some properties, like in [Blender for example](https://i.imgur.com/vWe2wV7.png).
This could give us something like that:
![img](https://i.imgur.com/LnWhpfc.png)
If possible, having a `right click > copy js data` could be a great bonus (with that, you should be able to get direct access to a material or a mesh, for example: `scene.getMeshByName("myWonderfulName")` )

**Comment by Jaskar** [comment]
Hi,
I created a PR.
Could you tell me if you have more ideas for tooltips ?
I only putted tooltips on the scene panel yet.

**Comment by Vinc3r** [comment]
I suppose we have to [wait this PR](https://github.com/BabylonJS/Babylon.js/pull/4986) before be able to test it on the playground?

**Comment by Jaskar** [comment]
Yes

**Comment by Vinc3r** [comment]
It seems working, GG :)
