### ISSUE TITLE
[Sandbox - bug inspector] The inspector does not show up in the sandbox

### ISSUE THREAD

**Issue by Bloadrick** [BabylonJS/Babylon.js#4776]
Hi,

I saw that the inspector was not working on the sandbox.

https://sandbox.babylonjs.com/

I tried to find where the bug was and I saw that if I replaced  the preview.babylonjs.com version of the inspector by the cdn.babylonjs.com version it work.

I think it was working yesterday so it must be an update from the last 30 hours that brock it.

**Comment by deltakosh** [comment]
Good catch
will fix it asap!

**Comment by valeriob** [comment]
Is this related ? i'm not able to use the inspector anymore : 

![image](https://user-images.githubusercontent.com/1522516/42930039-2edfac66-8b3c-11e8-9825-b880ac6d6de9.png)

**Comment by RaananW** [comment]
Yes, it is related. I'm working on a fix right now, will commit a fix later today. 

The sandbox now works, with a small issue of missing GUI elements.

**Comment by rodrix385** [comment]
The inspector is not working outside the sandbox either.

Running: 

scene.debugLayer.show();
			
Gives the following error:

Inspector.ts:190 Uncaught ReferenceError: Split is not defined
    at new e (Inspector.ts:190)
    at t._createInspector (babylon.js:30)
    at t.show (babylon.js:30)
    at <anonymous>:1:18


Thanks!

**Comment by deltakosh** [comment]
It was merged a few minutes ago:)
I will push a nightly asap
