### ISSUE TITLE
edgeRenderer doesn't show the right color

### ISSUE THREAD

**Issue by Vinc3r** [BabylonJS/Babylon.js#4778]
# Bugs

- Bug repro on [playground](https://www.babylonjs-playground.com/#K4S3GU#8) (line 51)
- Expected result: get pur green edgeColor
- Current result: kind of lighter color, but the pure green appears when activating the inspector!

![img](https://i.imgur.com/caJM1iL.gif)

**Comment by deltakosh** [comment]
Good try young padawan but this is not a bug:)
The edgeColor is a color4: https://www.babylonjs-playground.com/#K4S3GU#9
