### ISSUE TITLE
GUI Control: make fontWeight and fontStyle follow CSS standard

### ISSUE THREAD

**Issue by vfabioux** [BabylonJS/Babylon.js#4788]
- Bug repro on [playground](https://playground.babylonjs.com): https://www.babylonjs-playground.com/#XCPP9Y#575
- Expected result:
fontStyle should only be used for setting the text italic or not, and it should be possible to combine it with fontWeight to make it bold + italic at the same time.
Example: https://jsfiddle.net/e0tdL98n/7/
Correct formula is "font = font-style font-weight font-size font-family" according to https://www.w3schools.com/cssref/pr_font_font.asp

- Current result:
fontWeight overrides fontStyle value, see https://github.com/BabylonJS/Babylon.js/blob/master/gui/src/2D/controls/control.ts#L1285
This section of the docs and the playground example should be updated since fontStyle value cannot be "bold": https://doc.babylonjs.com/how_to/gui#styles

**Comment by deltakosh** [comment]
Fancy doing a PR to fix it?

**Comment by deltakosh** [comment]
Doc fixed already :)

**Comment by deltakosh** [comment]
Will fix it!

**Comment by deltakosh** [comment]
Done!
