### ISSUE TITLE
Invalid shader creating when running in exokit browser

### ISSUE THREAD

**Issue by TrevorDev** [BabylonJS/Babylon.js#4807]
Running http://www.babylonjs-playground.com/frame.htm#EIX8SD#3 in exokit (https://exokitbrowser.com) fails to function properly due to invalidly constructed shader (`LOGARITHMICDEPTH` is not defined)

Exokit logging:
> Babylon.js engine (v3.3.0-alpha.13) launched
BJS - [23:19:35]: Unable to compile effect:
BJS - [23:19:35]: Uniforms:  LensCenter, Scale, ScaleIn, HmdWarpParam, scale, textureSampler
BJS - [23:19:35]: Attributes:  position
BJS - [23:19:35]: Error: unknown #version type: 300 es
BJS - [23:19:35]: Unable to compile effect:
BJS - [23:19:35]: Uniforms:  world, view, viewProjection, vEyePosition, vLightsType, vAmbientColor, vDiffuseColor, vSpecularColor, vEmissiveColor, vFogInfos, vFogColor, pointSize, vDiffuseInfos, vAmbientInfos, vOpacityInfos, vReflectionInfos, vEmissiveInfos, vSpecularInfos, vBumpInfos, vLightmapInfos, vRefractionInfos, mBones, vClipPlane, diffuseMatrix, ambientMatrix, opacityMatrix, reflectionMatrix, emissiveMatrix, specularMatrix, bumpMatrix, normalMatrix, lightmapMatrix, refractionMatrix, diffuseLeftColor, diffuseRightColor, opacityParts, reflectionLeftColor, reflectionRightColor, emissiveLeftColor, emissiveRightColor, refractionLeftColor, refractionRightColor, vReflectionPosition, vReflectionSize, logarithmicDepthConstant, vTangentSpaceParams, alphaCutOff, vLightData0, vLightDiffuse0, vLightSpecular0, vLightDirection0, vLightGround0, lightMatrix0, shadowsInfo0, depthValues0, diffuseSampler, ambientSampler, opacitySampler, reflectionCubeSampler, reflection2DSampler, emissiveSampler, specularSampler, bumpSampler, lightmapSampler, refractionCubeSampler, refraction2DSampler, shadowSampler0, depthSampler0
BJS - [23:19:35]: Attributes:  position, normal
BJS - [23:19:35]: Error: unknown #version type: 300 es
BJS - [23:19:35]: Trying next fallback.
BJS - [23:19:35]: Unable to compile effect:
BJS - [23:19:35]: Uniforms:  world, view, viewProjection, vEyePosition, vLightsType, vAmbientColor, vDiffuseColor, vSpecularColor, vEmissiveColor, vFogInfos, vFogColor, pointSize, vDiffuseInfos, vAmbientInfos, vOpacityInfos, vReflectionInfos, vEmissiveInfos, vSpecularInfos, vBumpInfos, vLightmapInfos, vRefractionInfos, mBones, vClipPlane, diffuseMatrix, ambientMatrix, opacityMatrix, reflectionMatrix, emissiveMatrix, specularMatrix, bumpMatrix, normalMatrix, lightmapMatrix, refractionMatrix, diffuseLeftColor, diffuseRightColor, opacityParts, reflectionLeftColor, reflectionRightColor, emissiveLeftColor, emissiveRightColor, refractionLeftColor, refractionRightColor, vReflectionPosition, vReflectionSize, logarithmicDepthConstant, vTangentSpaceParams, alphaCutOff, vLightData0, vLightDiffuse0, vLightSpecular0, vLightDirection0, vLightGround0, lightMatrix0, shadowsInfo0, depthValues0, diffuseSampler, ambientSampler, opacitySampler, reflectionCubeSampler, reflection2DSampler, emissiveSampler, specularSampler, bumpSampler, lightmapSampler, refractionCubeSampler, refraction2DSampler, shadowSampler0, depthSampler0
BJS - [23:19:35]: Attributes:  position, normal
BJS - [23:19:35]: Error: unknown #version type: 300 es

Invalid produced shader:
`https://exokit.slack.com/files/U90GZV4GN/FBUMQB3EH/broken_shader.txt`

**Comment by modulesio** [comment]
The above error is for WebGL2. Here is the WebGL1 error, which is not the same but similar problem with shaders:

```
$ exokit -w1 http://www.babylonjs-playground.com/frame.htm#EIX8SD#3
Babylon.js engine (v3.3.0-alpha.13) launched
BJS - [05:00:47]: Unable to compile effect:
BJS - [05:00:47]: Uniforms:  world, view, viewProjection, vEyePosition, vLightsType, vAmbientColor, vDiffuseColor, vSpecularColor, vEmissiveColor, vFogInfos, vFogColor, pointSize, vDiffuseInfos, vAmbientInfos, vOpacityInfos, vReflectionInfos, vEmissiveInfos, vSpecularInfos, vBumpInfos, vLightmapInfos, vRefractionInfos, mBones, vClipPlane, diffuseMatrix, ambientMatrix, opacityMatrix, reflectionMatrix, emissiveMatrix, specularMatrix, bumpMatrix, normalMatrix, lightmapMatrix, refractionMatrix, diffuseLeftColor, diffuseRightColor, opacityParts, reflectionLeftColor, reflectionRightColor, emissiveLeftColor, emissiveRightColor, refractionLeftColor, refractionRightColor, vReflectionPosition, vReflectionSize, logarithmicDepthConstant, vTangentSpaceParams, alphaCutOff, vLightData0, vLightDiffuse0, vLightSpecular0, vLightDirection0, vLightGround0, lightMatrix0, shadowsInfo0, depthValues0, diffuseSampler, ambientSampler, opacitySampler, reflectionCubeSampler, reflection2DSampler, emissiveSampler, specularSampler, bumpSampler, lightmapSampler, refractionCubeSampler, refraction2DSampler, shadowSampler0, depthSampler0
BJS - [05:00:47]: Attributes:  position, normal
BJS - [05:00:47]: Error: 0(1990) : error C1008: undefined variable "unique_fragColor"
```

Note: You can swap the WebGL version to exposed with the `-w1` and `-w2` flags.

I'm thinking this is a feature detection problem in what Exokit is exposing and this is playing badly with the #defines and #ifdefs built to the shader.

**Comment by modulesio** [comment]
[Dumped source of the WebGL1 shader](https://github.com/BabylonJS/Babylon.js/files/2216035/broken_shader.txt), demonstrating its invalidity:

```
#ifdef LOGARITHMICDEPTH
out vec4 unique_fragColor;
#endif
```

**Comment by deltakosh** [comment]
Not sure to understand why this is a Babylon.js bug:)

**Comment by TrevorDev** [comment]
This exokit bug https://github.com/webmixedreality/exokit/issues/143 also looks like a dupe of this as the shader used in that threejs example also contains a #extension line:

`#extension GL_EXT_frag_depth : enable`

**Comment by modulesio** [comment]
@deltakosh Not a Babylon.js bug!

@TrevorDev thanks for the excellent analysis of Babylon's shader runtime behavior here.

It was indeed a GLSL rewrite problem on our end: `#extension` was interfering if it came after the `uniform`s/`varying`s. Also `#version 300 es` needed a whitelist.

With https://github.com/modulesio/webgl-to-opengl/commit/7af62c288e92a3214f9a6c52ccfed9eac9a6b6f9 and https://github.com/modulesio/webgl-to-opengl/commit/4354923b13aace46f68188cb4512ffd7f41824f8, http://www.babylonjs-playground.com/frame.htm#EIX8SD#3 seems to be launching same as Chrome now.

![capture 12](https://user-images.githubusercontent.com/6926057/43365210-1f352d6e-92f7-11e8-9061-c652ab61b222.PNG)

As a bonus this fixed webmixedreality/exokit#143 too, so double thanks! 👏

**Comment by TrevorDev** [comment]
Thanks @modulesio , Ill close this as this issue seems to be resolved but I have a couple other questions.

 - I am now trying to get http://www.babylonjs-playground.com/frame.htm#EIX8SD#7 to work.
When not using -w1 it still fails with 

> Error: this._gl.getUniformBlockIndex is not a function

 - When I am using -w1 ("C:\exokit\exokit.cmd" http://www.babylonjs-playground.com/frame.htm#EIX8SD#7 -w1) and click on the app to enter webVR the left and right eye seem to be rendered to the bottom left of the left eye.

 - When launching the exokit browser to try to use the reality tabs feature, I cant seem to enter webVR (I can only move with wasd and mouse to control controllers) when i type http://www.babylonjs-playground.com/frame.htm#EIX8SD#7 into the url field I see the sphere created by babylon but it does not update based on movement within exokit

any thoughts?

**Comment by modulesio** [comment]
I got http://www.babylonjs-playground.com/frame.htm#EIX8SD#7 working by fixing bugs https://github.com/webmixedreality/exokit/pull/282 + https://github.com/webmixedreality/exokit/pull/281.

I filed https://github.com/webmixedreality/exokit/issues/283 to track the too small viewport calls coming from Babylon.js. I'll have to understand the Babylon architecture more, but the `setViewport()` calls are using the old canvas size to set `gl.viewport`, resulting in a too small render.

Regarding Reality Tabs, [it is Ctrl-1 to enter VR](https://github.com/webmixedreality/exokit-home/blob/0826def29c14600e69caf9f3d4137aac24a20931/index.html) but we still need to document many of these features on https://docs.webmr.io/.

Finally, if I missed something re: Exokit, could you file an issue at the [Exokit repo](https://github.com/webmixedreality/exokit/issues)?

**Comment by TrevorDev** [comment]
@modulesio Thanks so much, will do.

I might be able to dig a bit more into webmixedreality/exokit#283 to see where/when in babylon the viewport is somehow setting the wrong values when I get some free time.

**Comment by ngokevin** [comment]
Getting similar issues with Sketchfab. Variable name is the same, do they use Babylon or something now? https://sketchfab.com/models/6e6c037748ce4fb9a9afb36ed21194a4/embed?auto_play=true&autoplay=1&autostart=1

```
[x] ERROR: 0:13: Use of undeclared identifier 'unique_fragColor'

Could't compile shader #version 100
#ifdef GL_FRAGMENT_PRECISION_HIGH
  precision highp float;
#else
 precision mediump float;
#endif
uniform sampler2D uT0;
uniform sampler2D uT1;
uniform sampler2D uT2;
uniform sampler2D uT3;
uniform ivec4 uR;
varying vec2 vT;
varying vec3 vC;
varying vec3 vColor;
varying vec4 vColor2;
void f(in vec3 a, out vec3 b) {
b = 2.0 * a;
}
#define LIN_SRGB(x) x < 0.0031308 ? x * 12.92 : 1.055 * pow(x, 1.0/2.4) - 0.055
#define SRGB_LIN(x) x < 0.04045 ? x * (1.0 / 12.92) : pow((x + 0.055) * (1.0 / 1.055), 2.4)
float linearTosRGB(const in float color) { return LIN_SRGB(color); }
vec3 linearTosRGB(const in vec3 color) { return vec3(LIN_SRGB(color.r), LIN_SRGB(color.g), LIN_SRGB(color.b)); }
vec4 linearTosRGB(const in vec4 color) { return vec4(LIN_SRGB(color.r), LIN_SRGB(color.g), LIN_SRGB(color.b), color.a); }
void main(void) {
vec4 col;
col.r = linearTosRGB(vColor2.r);
col.rgb = linearTosRGB(vColor);
f(vC, col.xyz);
if ( uR.x == 3 ) {
  col.rgb = texture2D( uT0, vT ).aaa;
  col.a = uR.y == 0 ? texture2D( uT1, vT ).r : texture2D( uT1, vT ).a;
} else if ( uR.x == 2 ) {
  col.rgb = texture2D( uT0, vT ).rgb;
  col.a = uR.y == 0 ? texture2D( uT1, vT ).r : texture2D( uT1, vT ).a;
} else {
  col.r = uR.x == 0 ? texture2D( uT0, vT ).r : texture2D( uT0, vT ).a;
  col.g = uR.y == 0 ? texture2D( uT1, vT ).r : texture2D( uT1, vT ).a;
  col.b = uR.z == 0 ? texture2D( uT2, vT ).r : texture2D( uT2, vT ).a;
  col.a = uR.w == 0 ? texture2D( uT3, vT ).r : texture2D( uT3, vT ).a;
}
gl_FragColor = gl_FrontFacing ? vec4(col.rgb, 1.0) : col;
}
ERROR: 0:44: Use of undeclared identifier 'unique_fragColor'
```
