### ISSUE TITLE
Mesh CullingMode

### ISSUE THREAD

**Issue by jbousquie** [BabylonJS/Babylon.js#4812]
# Feature Request
Add a new property to the Mesh class : cullingMode.

This could be set with static values defining the chosen way to check the culling of the given mesh.   
Example of values :  
- [x] standard (default) : current culling algo
- [x] bSphereOnly : skip the BBox culling test in the current algo
- [x] optimisticInclusion : quick pre-test of mesh inclusion, then current algo (ex : mesh position inside the rectangle corresponding to the unprojected screen at the mesh position in the camera view system)
- [ ] optimisticExclusion : quick pre-test of mesh exclusion, then current algo (ex : bSphere outside the external conical frustum)
- [x] optimisticInclusionAndBSphereOnly  
- [ ] optimisticExclusionAndBSphereOnly

test code : http://jerome.bousquie.fr/BJS/test/frustum.js

**Comment by deltakosh** [comment]
Will prepare the work!

**Comment by jbousquie** [comment]
As both the optimistic modes (fast inclusion or exclusion) rely on the camera view matrix, maybe would it be nice to update this matrix once before calling isInFrustum() and not for each mesh ?  knowing it's updated anyway before the rendering process ...

**Comment by deltakosh** [comment]
Not sure to get why you say updated for each mesh? 
The camera view matrix is updated once before calling the frustum  test

**Comment by jbousquie** [comment]
ok
what I was afraid of (not read the full code so far) was that we compute
the cam view matrix on each call to isInFrustum(), so for each mesh.

2018-07-24 15:39 GMT+02:00 David Catuhe <notifications@github.com>:

**Comment by deltakosh** [comment]
Doc: https://github.com/BabylonJS/Documentation/blob/master/content/How_To/scene/Optimizing_your_scene.md#changing-culling-strategy

**Comment by deltakosh** [comment]
Ok first stab done! Feel free to chime in when you can!

**Comment by deltakosh** [comment]
You are right! I'll  change that

**Comment by deltakosh** [comment]
@jbousquie still interested? :)

**Comment by jbousquie** [comment]
yes... I was wondering if the stuff had started or not
I'll have a look then (I'm on a  f..g php code for my "official" work in
the same time)

Le jeu. 6 déc. 2018 à 19:12, David Catuhe <notifications@github.com> a
écrit :

**Comment by deltakosh** [comment]
It is done and waiting for your updates;)

**Comment by jbousquie** [comment]
Optimistic exclusions are cancelled because they can't really compete the current exclusion tests.  
Optimistic Inclusions added in complement on standard and bSphereOnly processes.  
#5624 

Tests done on my computer with 83 meshes, 81 moving and 2 static (a ground and a column) : 
- switching to bSphereOnly processes (with or with optimistic inclusion mode) always gives a good gain vs standard process, whatever none, some or all meshes are in the frustum. It's expected because there aren't any longer the BBox evaluations (so 48 iterations less).  
- switching to Optimistic Inclusion processes (with or without bSphereOnly mode) gives a very little gain when all the meshes are visible and no sensible loss when no mesh is visible.  

In brief, Optimistic Inclusions work but give very little gain. They keep the same accuracy than the basic mode on what they are applied (standard or bSphereOnly).  
bSphereOnly, because it reduces a lot the accuracy, gives a good perf gain.  This should not be used with high poly meshes while sending false positives to the GPU has a real rendering cost. This can be very interesting for numerous low poly meshes instead.
