### ISSUE TITLE
Add support for loading MSFT_lod extension as rendering LODs

### ISSUE THREAD

**Issue by bghgary** [BabylonJS/Babylon.js#4818]
See https://github.com/KhronosGroup/glTF/issues/1404

**Comment by thomlucc** [comment]
Also: https://forum.babylonjs.com/t/msft-lod-screen-coverage-documentation-wrong/40635

**Comment by bghgary** [comment]
https://forum.babylonjs.com/t/msft-lods-extension-screencoverages-support/46535

**Comment by thomlucc** [comment]
Closing, Feel free to re-open.
