### ISSUE TITLE
Add support for GUI Hover change Cursor

### ISSUE THREAD

**Issue by dad72** [BabylonJS/Babylon.js#4825]
# Feature request

http://www.html5gamedevs.com/topic/39038-gui-hover-change-cursor/

Can change the cursor when hovering clickable GUI elements like buttons or in case you want to change the cursor on elements of Control.

Thanks

**Comment by deltakosh** [comment]
Will work on that ASAP!

**Comment by deltakosh** [comment]
Demo: https://www.babylonjs-playground.com/#XCPP9Y#588
Will work when PR merged
