### ISSUE TITLE
[glTF] Changing the mesh material swaps the faces

### ISSUE THREAD

**Issue by rlouvat** [BabylonJS/Babylon.js#4833]
Following the issue on the forum: http://www.html5gamedevs.com/topic/39028-gltf-exporter-fur-material-issue/?tab=comments#comment-222990
Previous issue: https://github.com/BabylonJS/Exporters/issues/276

After loading a glTF scene from the [glTF-Sample-Model:](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/SimpleMeshes)
- the mesh is rotated 180 degrees on the y-axis﻿
- changing the mesh material doesn't work as expected (nomal or uv flipped ?)
- Bug repro on http://www.babylonjs-playground.com/#DTAJTU

**Comment by rlouvat** [comment]
Hi @bghgary 
Thank you for your clear answer.

Like the original problem posted on the forum, I try with the fur material. And it's like the fur is going inside the mesh...

Here is a test with a box and a standard material. Even with `sideOrientation` set to CCW, the faces are flipped.
http://www.babylonjs-playground.com/#DTAJTU#3

Here is the test with a duck and a fur texture:
http://www.babylonjs-playground.com/#DTAJTU#4

**Comment by bghgary** [comment]
The material for this should be set to CW because Babylon is in left-handed and there is a negative determinant due to the negative z-scale on the root.

**Comment by bghgary** [comment]
Here is a fixed version: http://www.babylonjs-playground.com/#DTAJTU#5

**Comment by rlouvat** [comment]
Hi @bghgary,

Thank you for the explanation :)

**Comment by tibotiber** [comment]
Gold answer @bghgary, thank you!
