### ISSUE TITLE
[Optimization] Use heavy array operations less

### ISSUE THREAD

**Issue by fmmoret** [BabylonJS/Babylon.js#4850]
# Problem
We use splice a ton. This is not a problem in places where arrays are very short and/or splice is called with low frequency. However, there are a ton of places where one of those two conditions is not necessarily true.

Here's all the places we use splice:
https://github.com/BabylonJS/Babylon.js/search?q=splice&type=Code

Similarly we use indexOf probably too much:
https://github.com/BabylonJS/Babylon.js/search?q=indexOf&type=Code

Animations are a place, in particular, where we use them heavily and we use them in loops. 

As a prime example, take a look here where an animatable finishes:
https://github.com/BabylonJS/Babylon.js/blob/33850ac7dc1a78f9eab6947dd09d555e134c2361/src/Animations/babylon.animatable.ts#L379

First, we scan up to the whole `scene._activeAnimatables` array, then we loop over all runtimeAnimations and call dispose on them (https://github.com/BabylonJS/Babylon.js/blob/b7abafff2dc5ddfaa5ac593a7c44e333211057e0/src/Animations/babylon.runtimeAnimation.ts#L213). 

Let's take a look at a real-world example: 
In my current game, I have 10 unique characters running around the screen. 
I have 200 active animatables. Each has between 1 and 200 runtime animations. Cleaning up a stopped animatable takes `O(n)` time to find, another `O(n)` time to splice, allocates new memory, & frees up space for the GC to do even more work.

Say I have 200 runtime animations for this animation (this is a real-world case -- I have complex characters in my game, and each animatable has 1-200 runtime animations with a median 125). In a worst case to clean-up these runtime animations, we do `m` calls to dispose, each with an indexOf call that costs us  `O(m)` time and a splice call that costs us  `O(m)`  time, `O(m)` new space allocated, and `O(m)` space now free to be cleaned up by the GC. This is`O(m*(m+m))` -> `O(m^2)` time, `O(m^2)` space allocated, `O(m^2)` space freed up that the GC now needs to clean up.

In the case of 200 runtime animations, this is up to ~20000 equality checks, ~20000 reference copies for new arrays, 20000 array slots worth of memory allocated, 20000 array slots of garbage created that will need to be cleaned up. In the average case, all of those numbers are the same except for equality checks which are ~10000 if all are approximately in the middle of the array. (Note the numbers are not 40000 because the array size is shrinking -- sum(n from 1 to n) is (n * (n+1)) / 2)

With an optimal implementation, each of these numbers could be reduced to `O(m)`.

# Solution
Nearly every place we use splice or indexOf, we could replace it with usage of native Map, native Set, or a combination of an object for active index tracking and a pre-allocated array filled with either null values or references to active objects.

# Real world complaint
I'm trying to make a rather complex combat game with lots of effects & animations that are standard to any game that could compete with decent ones on steam. Already, I'm not too far from a world where a consistent 60 fps just wont be possible & stuttering from GC's will be the norm.

Perf seems hard to keep in check; I might not be too far from a point where I'll either need to re-write significant portions (either in JS or pop this out to electron and do it in rust / c++ & use FFI) or move off of the library in general (I'm in love with the Babylon.js API -- so I'm going to give it my best effort).

**Comment by deltakosh** [comment]
Well this is an interesting issue:) can you give me an example of how could be replace the dispose code that we have?

Pragmatically we still need to traverse the array, call dispose on everyone and free the array. We had very several Smarter ray that helps with the GC so perhaps moving active animations to a SmartArray could help in your case?

I'm all in to follow you in this path in you want to start a PR

**Comment by fmmoret** [comment]
The only places I spotted that we actually need an array are for syncing / getting that master frame. 

In theory, you could use an ordered set and get the best of both worlds. This is just a doubly-linked list + a map with keys from data you care about to doubly linked list nodes. Instead of `indexOf` + `splice` you can just expose a `.remove` on an ordered set and it'll remove the object key from the internal map & update the prev & next references on the doubly-linked list node that it found in the map.

Javascript is an untameable beast though, so it COULD be that it ends up slower in practice because of some silly JIT tricks that V8 (or the mozilla & microsoft equivalents) pull at runtime -- despite big O being much better.

**Comment by fmmoret** [comment]
I'm going to keep moving forward & see if very particular bottlenecks present themselves & I'll maybe make a PR in a couple weeks to tackle those precise pain-points. Just a flag that my CPU usage & memory usage seem to be scaling non-linearly as I add objects in a linear-ish fashion.

**Comment by deltakosh** [comment]
CLosing it for now
