### ISSUE TITLE
Playground GUI Minor Bugs

### ISSUE THREAD

**Issue by rodrix385** [BabylonJS/Babylon.js#4851]
These bugs are minimal, but I believe it's helpful that I report them.
Site: https://playground.babylonjs.com/

Bug 1: Mini map
Replication steps:
 - Go to Playground at specific demo.
- Mini map by default will be ON but on Settings it will show that it is off.

Bug 2: Inspector
Replication steps:
-  Go to Playground at specific demo.
- Open Inspector, close it using it's X button-
- Settings will show that it is still ON while it is off and so to enable you need to click on Inspector twice (to turn it off and on again) 

These bugs are minimal, but I though it would be useful to report them for newbies that use our Playground to improve the experience.

![image](https://user-images.githubusercontent.com/26559703/43371306-415767c2-9365-11e8-99a7-343d702f4383.png)

![image](https://user-images.githubusercontent.com/26559703/43371333-dad58d98-9365-11e8-80b2-ce9241cf462a.png)

**Comment by rodrix385** [comment]
The Inspector bug occurs again when you click on SAVE also.

**Comment by Jaskar** [comment]
Hi @rodrix385 ,
Thanks for your feedback.
I'll work on it this week 👍

**Comment by Jaskar** [comment]
Sorry for the delay!
Tell me if this one is good for you :)
