### ISSUE TITLE
[Viewer] When leaving VR, model and environment are scaled incorrectly

### ISSUE THREAD

**Issue by RaananW** [BabylonJS/Babylon.js#4852]
Model and environment (skybox and ground) are being re-scaled when entering VR in the viewer (because the model is normalized when opening it in the viewer).
When leaving VR the model and environment are downscaled again. The downscale doesn't work correctly. The camera's upper radius limit is also changed which allows a user to scroll out of the environment.

- [x] onExistVRObservable firing twice if button is used to exit vr (We can check if its already exited and not fire it again in vrExperienceHelper)
- [x] onEnteringVR not being fired when config is updated (observables in the viewer should be moved to the viewer level instead of vr helper, similar to other observables)
- [x] Controller and gaze dot showing up after exiting vr
- [x] Vr scaling hard to know if its happening correctly
- [x] Exiting vr is still showing both eyes and only rendering for left eye on the 2D screen

**Comment by TrevorDev** [comment]
https://github.com/BabylonJS/Babylon.js/pull/4873
https://github.com/BabylonJS/Babylon.js/pull/4874

**Comment by TrevorDev** [comment]
https://github.com/BabylonJS/Babylon.js/pull/4909
