### ISSUE TITLE
Mesh.MergeMeshes crashes on more than 65336 vertices mesh with allow32BitsIndeces on - BUG

### ISSUE THREAD

**Issue by rodrix385** [BabylonJS/Babylon.js#4859]
BABYLON.Mesh.MergeMeshes(...) crashes if the meshes to merge have more than 65336 even though flag allow32BitsIndices = true.

Attached is a full test suite with html, gtlf file, bin, and textures. The file includes an html to run on local server, which will load a gltf that has multiple meshes of the _same_  material, with more than 65536 vertices.

An attempt to merge all meshes with same materials is done on lines 118 - 147 of the bug.html script, producing a failure.

**Function:** 
BABYLON.Mesh.MergeMeshes(meshesWithSameMaterial, disposeSource, allow32BitsIndices, meshSubclass, subdivideWithSubMeshes);

**Result:**  TypeError: this.indices.push is not a function

```
babylon.js:1 BJS - [01:53:21]: Error running tasks-done callbacks.
m._ErrorEnabled @ babylon.js:1
e._decreaseWaitingTasksCount @ babylon.js:1
(anonymous) @ babylon.js:1
e.onDoneCallback @ babylon.js:1
(anonymous) @ babylon.js:1
(anonymous) @ babylon.js:1
f @ babylon.js:1
(anonymous) @ babylon.js:1
Promise.then (async)
(anonymous) @ babylon.js:1
f @ babylon.js:1
o @ babylon.js:1
XMLHttpRequest.send (async)
l @ babylon.js:1
n @ babylon.js:1
m.LoadFile @ babylon.js:1
g @ babylon.js:1
r @ babylon.js:1
(anonymous) @ babylon.js:1
load (async)
c._checkManifestFile @ babylon.js:1
c @ babylon.js:1
P._loadData @ babylon.js:1
P.ImportMesh @ babylon.js:1
e.runTask @ babylon.js:1
e.run @ babylon.js:1
e._runTask @ babylon.js:1
e.load @ babylon.js:1
createScene @ bug.html:163
(anonymous) @ bug.html:170
babylon.js:1 TypeError: this.indices.push is not a function
    at q.merge (babylon.js:1)
    at Function.p.MergeMeshes (babylon.js:1)
    at e.assetsManager.onFinish (bug.html:144)
    at e._decreaseWaitingTasksCount (babylon.js:1)
    at babylon.js:1
    at e.onDoneCallback (babylon.js:1)
    at babylon.js:1
    at babylon.js:1
    at f (babylon.js:1)
    at babylon.js:1

```

 
[bug.zip](https://github.com/BabylonJS/Babylon.js/files/2243798/bug.zip)

**Comment by deltakosh** [comment]
I cannot run the sample because a file named Aluminum-Scuffed_normal.png is missing but I saw that you try to merge meshes with no data and this won't work.

You have to make sure that the mesh.getTotalVertices() > 0

**Comment by rodrix385** [comment]
Hi @deltakosh ! Thanks for checking it out.
...are you sure? I am quite sure I am only combining the meshes that have data. 
I have also encountered that error again on other similar cases..
![aluminum-scuffed_normal](https://user-images.githubusercontent.com/26559703/43470686-8aa78244-94bf-11e8-890a-462941ecf2f5.png)


Let me upload that missing file :)
Done. Attached

**Comment by rodrix385** [comment]
Confirmed. Bug is still on.

I added:
if(mesh.getTotalVertices() > 0) 	meshesWithSameMaterial.push(mesh);

..but I still get the same bug.

**Comment by deltakosh** [comment]
I found the bug ;)

**Comment by rodrix385** [comment]
Awesome!!!! :)

**Comment by rodrix385** [comment]
@deltakosh please re-open this.
Your fix generated a new bug.

Now the merge is completely incorrect.

Without merge:
![image](https://user-images.githubusercontent.com/26559703/43623297-e323bc6e-96b6-11e8-9405-50fb1920dc7f.png)

After merge (with your new code changes):
![image](https://user-images.githubusercontent.com/26559703/43623330-02cc12a0-96b7-11e8-8c48-bc33fadce996.png)

Something in your code is doing an incorrect mesh, breaking the model completely.
It seems that vertices are incorrectly connected.

To check this simply load the test suite that I uploaded and comment lines 140 and 144 with	 BABYLON.Mesh.MergeMeshes(..) to disable the merge and see the before and after results.

Thanks!

**Comment by deltakosh** [comment]
Will check that
