### ISSUE TITLE
Lazy loaded inspector retrieves js bundle from preview.* rather than cdn.*

### ISSUE THREAD

**Issue by zakhenry** [BabylonJS/Babylon.js#4863]
This isn't really something that can be tested on the playground, so here's a description:

Currently, the inspector bundle is loaded on the fly when the inspector is requested to be open _from the preview url_ `https://preview.babylonjs.com/gui/babylon.gui.min.js` (https://github.com/BabylonJS/Babylon.js/blob/master/inspector/src/Inspector.ts#L58) rather than the stable cdn url.

This causes an issue when there is an issue with the unstable preview inspector and loading it into an app running the stable version of babylon.

Ideally the inspector should load the exact version of the inspector from babylon cdn to match the version of babylon that is currently loaded.

The workaround for now is to simply run
```ts
DebugLayer.InspectorURL = 'https://cdn.babylonjs.com/inspector/babylon.inspector.bundle.js';
```
before trying to open the inspector

**Comment by deltakosh** [comment]
Well this is why there is the InspectorUrl :p

There is no plan to reference cdn by default as we ship release from master
