### ISSUE TITLE
SceneLoader.Load() creates multiple requests to a single texture file 

### ISSUE THREAD

**Issue by kimamula** [BabylonJS/Babylon.js#487]
If a single texture file is referred to multiple times in a .babylon file, SceneLoader.Load() creates multiple requests to that texture file, while the same method of v1.14 creates only a single request per a single texture.
This results in a long initial loading time.
This is because BaseTexture._getFromCache() always returns null as the samplingMode property of a texture cached in Engine is not set until the texture actually loaded.

Is this an expected behavior?

When I add a below line just before https://github.com/BabylonJS/Babylon.js/blob/v2.0/Babylon/babylon.engine.ts#L1461, it works fine for me.
```
texture.samplingMode = samplingMode;
```

**Comment by deltakosh** [comment]
Hey this is perfectly right! Thank you for the heads up! I completely missed it
I'll fix it asap
