### ISSUE TITLE
Holographic Button Tooltips

### ISSUE THREAD

**Issue by nbduke** [BabylonJS/Babylon.js#4881]
# Feature request
MRTK now supports tooltips that appear when hovering on a 3D button. Specifically, when the controller pointer hovers on the face of a 3D button for about 1 second, a small text block fades in revealing configurable text for that button. When the pointer exits the button, the text block immediately begins fading out.

Here is a screenshot from the Cliff House showing the tooltip:

![image](https://user-images.githubusercontent.com/38300641/43615244-923d2b64-966b-11e8-8233-253462560bf3.png)

I am requesting that this feature be added to the Holographic button. At a minimum, the `text` property would be used to set the tooltip's content, and an additional Boolean flag, e.g. `useTooltip`, would cause the text to appear in the tooltip _instead of_ within the button itself. Hover would be triggered by mouse _and_ VR controller enter.

A nice-to-have feature would be the ability to set an alignment preference for the tooltip. For example, there could be an enum property like `tooltipAlignment` with possible values of `Top`, `Bottom`, `Left`, and `Right`. The property would cause the tooltip to appear on the given side of the button.

**Comment by nbduke** [comment]
Would it be possible to expose this functionality on other buttons too? Particularly `BABYLON.GUI.Button`? @TrevorDev

**Comment by TrevorDev** [comment]
@nbduke Sure, Ill see what I can do.

**Comment by nbduke** [comment]
Cool, this is very helpful! Would it be possible to expose the tooltipText property on the 2D button as well? Tooltips as a part of the button UI probably ought to be standardized across Babylon.

I'm also curious where the tooltip will appear relative to the button. Is there any way to control its positioning?

**Comment by TrevorDev** [comment]
The tooltip appears above the button, I didn't want to add too much customization on the button to avoid overloading the button class with tooltip controls. Fully custom tooltips can be created with a mesh as shown in the linked playground.
![image](https://user-images.githubusercontent.com/3753071/44070580-70e8db58-9f39-11e8-8076-220ec2d8b965.png)

As for the 2D button, as it can be used in multiple ways (On a 3D mesh, full screen UI, aligned to top with no additional space, etc.) I did not find clean way to generalize how a tooltipText property should be rendered. The playground I mentioned shows one example of rendering a tooltip with a 2D button. If wanting to render a tooltip when using fullscreen UI you could also look at this thread I found http://www.html5gamedevs.com/topic/33409-best-way-to-create-tooltip/

**Comment by nbduke** [comment]
Sounds reasonable, thanks.

**Comment by sebavan** [comment]
Closing the issue for now then and we can create new ones for improvments. Thanks Trevor.
