### ISSUE TITLE
Normal "Z-order" Issue

### ISSUE THREAD

**Issue by BryanChrisBrown** [BabylonJS/Babylon.js#4886]
# Bugs
I've exported this model out of 3ds max using the .gltf file format. Other models have exported fine, while this one seems to have a strange normal issue. The normals are correct in the original max file, so I'm not sure what is causing this.

- Expected result: Trashcan look solid while viewing from outside.
- Current result: Trashcan has strange transparency/normal issues

![image](https://user-images.githubusercontent.com/22871421/43649804-20de38c2-970c-11e8-9a9d-b59927ec40b2.png)

link to the gltf file
https://drive.google.com/open?id=1D8HTq0o9AhLe9ghfu8KP9uqcpQyU8uxF

**Comment by deltakosh** [comment]
Can you make sure this model does not use png or alpha source material? This is probably the cause of the unwanted transparency

**Comment by BryanChrisBrown** [comment]
we originally had a .tga file, which can have an alpha channel. 

I've replaced it with a .jpeg image, Still getting weird results. 
![image](https://user-images.githubusercontent.com/22871421/43651562-b67ad9ea-9710-11e8-829f-6a7d8b47d10f.png)

**Comment by BryanChrisBrown** [comment]
We've rebuilt the model from scratch and that seems to have fixed the normal issues. If you'd like I can send the max file for the broken trash can If you want to look into the normal issue further. 
![image](https://user-images.githubusercontent.com/22871421/43651687-107cd8a8-9711-11e8-854e-65f566870fd6.png)

**Comment by deltakosh** [comment]
Ok good news thanks! (The material was probably flagged as AlphaSource)
