### ISSUE TITLE
GUI and post processing overlapping

### ISSUE THREAD

**Issue by vfabioux** [BabylonJS/Babylon.js#4898]
Currently every "post process" overlap GUI controls in fullscreen mode except for the glow layer:
- Highlight layer (overlaps): https://www.babylonjs-playground.com/#XCPP9Y#589
- Glow layer (does not overlap): https://www.babylonjs-playground.com/#XCPP9Y#590
- Blur (overlaps): https://www.babylonjs-playground.com/#XCPP9Y#591

For the highlight layer I don't think it makes sense to have it overlap the GUI. The only use I can think of is to make a HUD for the player's character (as if he is wearing a spaceship helmet for example), but then it would be probably better for immersion to use the GUI in texture mode or the 3D GUI.
As for other post processes such as blur, users might want to do both. A workaround was already posted here: http://www.html5gamedevs.com/topic/30914-postprocess-and-babylongui/ with the following example: https://www.babylonjs-playground.com/#U9AC0N#58 (slightly modified). If this is the expected solution the example should probably be added to the docs: https://doc.babylonjs.com/how_to/gui

**Comment by deltakosh** [comment]
Do you want to do a PR for the docs?

**Comment by deltakosh** [comment]
Actually I have a few minutes free so I'll do it
Thanks for the heads up!
