### ISSUE TITLE
fbx conversion

### ISSUE THREAD

**Issue by jeromeetienne** [BabylonJS/Babylon.js#490]
Hello,

i love how it is easy to convert models to babylon js format via http://www.babylonjs.com/converter.html

I would be specially interested in the fbx converter, can you please explain how you handle it ?

Is that somewhere on github ?

Thanks

**Comment by deltakosh** [comment]
Yes sir:
here==> https://github.com/BabylonJS/Babylon.js/tree/master/Exporters/XNA%20-%20OBJ

**Comment by jeromeetienne** [comment]
thanks :)
