### ISSUE TITLE
Link to custom playground down again :(

### ISSUE THREAD

**Issue by nathanidp** [BabylonJS/Babylon.js#4918]
It seems like all playground link (customed like this one => https://www.babylonjs-playground.com/#1KUJ0A) redirect to the default playground page.

**Comment by sebavan** [comment]
Hello,

It looks like it is working for me:
![image](https://user-images.githubusercontent.com/16655165/43955915-75487f80-9ca2-11e8-8e18-4e0036010038.png)

What browser are you using ?

**Comment by RaananW** [comment]
it works for me. might have been temporary?

**Comment by nathanidp** [comment]
It don't work for me ...

**Comment by sebavan** [comment]
@nathanidp Do you have any other precision like browser and version of the browser and the page where it fails so I can repro ?

**Comment by nathanidp** [comment]
I'm on chrome 68.0.3440.84.
Every link do the same things for me and here's a GIF link that shows the problem 
https://media.giphy.com/media/fdM2eANnPBoGxETAid/giphy.gif

**Comment by sebavan** [comment]
Do you see any error in the console or network ?

I am using the exact same version without issues :-(

**Comment by nathanidp** [comment]
![image](https://user-images.githubusercontent.com/16017488/43965037-793dc87c-9cbe-11e8-805b-d58e7e527830.png)

**Comment by sebavan** [comment]
It looks like an issue to reach the snippet server.

Could you put a breakpoint line 1174 (empty catch) of the index.js of the playground so that we could try to troubleshoot your error ?

Sorry again and thanks for your help troubleshooting the issue.

**Comment by nathanidp** [comment]
I don't find the index.js in the devtool
