### ISSUE TITLE
[GUI] button on click event stop working on iPhone

### ISSUE THREAD

**Issue by kutomer** [BabylonJS/Babylon.js#4928]
Hello,
When registering "onClick" event to babylon gui button, a long press will execute the event but afterward the click event will stop working. (os x & android works perfectly fine)

https://www.babylonjs-playground.com/#XCPP9Y#596
```
    button1.onPointerUpObservable.add(function() {
        console.log('up');
    });
    button1.onPointerDownObservable.add(function() {
        console.log('down');
    });
    button1.onPointerClickObservable.add(function() {
        console.log('click');
    });
```

Expected behavior will be: down -> click -> up, after long press you'll see only down->up.
Print screen from iPhone 6s (also reproduced with iPhone 7) safari console:
![screen shot 2018-08-13 at 11 54 16](https://user-images.githubusercontent.com/3729904/44022842-7de57098-9ef1-11e8-88fc-4d8af02b7d3c.png)

Devices info:
iPhone 6s version 11.4
iPhone 7 version 11.4.1

Tomer.

**Comment by sebavan** [comment]
@TrevorDev Could you help with this one ?
