### ISSUE TITLE
Firefox running simple BJS scene turns my laptop into a heat gun

### ISSUE THREAD

**Issue by Dimous** [BabylonJS/Babylon.js#4941]
Hello!
So, I assembled this simple scene -- http://dimous.github.io/babylonjs/
I get 3-4% of CPU usage in Chrome and 35-38% in Firefox 61.0.2 x64. I also tested it on a desktop computer and got the same results.
_UE's action-rpg demo consumes less CPU, wtf?_

Babylonjs version: v3.3.0-beta.1
My laptop's video hardware: Intel(R) HD Graphics 4000, NVIDIA GeForce GT 740M (I installed latest drivers for both cards)

about:config
<details>

| setting | value |
|---|---|
| webgl.1.allow-core-profiles | false |
| webgl.allow-fb-invalidation | false |
| webgl.angle.force-d3d11 | false |
| webgl.angle.force-warp | false |
| webgl.angle.try-d3d11 | true |
| webgl.bypass-shader-validation | false |
| webgl.can-lose-context-in-foreground | true |
| webgl.default-no-alpha | false |
| webgl.disable-DOM-blit-uploads | false |
| webgl.disable-angle | false |
| webgl.disable-extensions | false |
| webgl.disable-fail-if-major-performance-caveat | false |
| webgl.disable-wgl | false |
| webgl.disabled | false |
| webgl.dxgl.enabled | true |
| webgl.dxgl.needs-finish | false |
| webgl.enable-debug-renderer-info | true |
| webgl.enable-draft-extensions | false |
| webgl.enable-privileged-extensions | false |
| webgl.enable-webgl2 | true |
| webgl.force-enabled | false |
| webgl.force-index-validation | 0 |
| webgl.force-layers-readback | false |
| webgl.lose-context-on-memory-pressure | false |
| webgl.max-contexts | 32 |
| webgl.max-contexts-per-principal | 16 |
| webgl.max-warnings-per-context | 32 |
| webgl.min_capability_mode | false |
| webgl.msaa-force | false |
| webgl.perf.max-acceptable-fb-status-invals | 0 |
| webgl.perf.max-warnings | 0 |
| webgl.perf.spew-frame-allocs | true |
| webgl.prefer-16bpp | false |
| webgl.renderer-string-override |  |
| webgl.restore-context-when-visible | true |
| webgl.vendor-string-override |  |
| webgl.webgl2-compat-mode | false |

</details>

**Comment by sebavan** [comment]
could you ensure in http://webglreport.com/?v=2 that in Firefox you are using the discrete GPU ?

**Comment by Dimous** [comment]
https://screenshots.firefox.com/XNP9KT1Ia0f2OMN6/webglreport.com

**Comment by sebavan** [comment]
It looks like you are using the integrated gpu in firefox could you check if it is the same on Chrome ?

Might also be interested to see the perf profiler comparison between chrome and firefox just in case we are using an API that firefox does not like as much.

**Comment by Dimous** [comment]
http://dimous.github.io/babylonjs/webglreport.com.png
SpectorJS capture for chrome -- http://dimous.github.io/babylonjs/capture%2018_32_48.chrome.json
For some reason Firefox version does not save captured data, just nothing happens (it's a bug I suppose).

**Comment by Dimous** [comment]
http://dimous.github.io/babylonjs/profile.chrome.json
http://dimous.github.io/babylonjs/profile.firefox.json

**Comment by sebavan** [comment]
You are using the same GPU in both so we can get read of this possibility.

Could you run the profilers without Spector running ? it does add a lot of extra work that we show in them.

At a first glance it looks like you have a bit too much GC and update style.

The easiest for me to help would be to be able to access your app or working on a babylon playground. is it possible ?

**Comment by Dimous** [comment]
https://playground.babylonjs.com/#DI8SXJ

**Comment by Dimous** [comment]
I removed spector plugin and detached development panel _to prevent resizing when I start profiler_.

http://dimous.github.io/babylonjs/profile.firefox.v2.json
http://dimous.github.io/babylonjs/profile.chrome.v2.json

**Comment by sebavan** [comment]
I can not repro the issue locally with the difference you have. Looking at your profiles now, it looks like gecko is spending all its time in the Graphics which might highlight an issue with your GPU on Firefox:
![image](https://user-images.githubusercontent.com/16655165/44153224-f2b733f4-a0a7-11e8-9411-1e016c3a3da3.png)
This also seems to be the case on Chrome:
![image](https://user-images.githubusercontent.com/16655165/44153358-54f3f44e-a0a8-11e8-8338-b583ea4b1b3a.png)

Unfortunately it does not look like there is anything obviously wrong highlighting the difference.

What Firefox version are you using ?

Also could you try to force the usage of your nvidia card from the nvidia panel for those apps ?

**Comment by Dimous** [comment]
61.0.2 x64
I also tested it on a desktop computer with only (_probably integrated_) card NVIDIA GeForce 8400GS. As I stated earlier with the same result. Would upload profiles if you need.

**Comment by sebavan** [comment]
Yup I do definitely not see any huge diff between both browsers :-( it does not look to come from the BJS code.

You might try a report on the Mozilla team to understand why is there such a big diff across the browsers?

**Comment by Dimous** [comment]
Ok. Thanks for your time.

**Comment by sebavan** [comment]
@Dimous please do let me know if you have news on it I am always willing to fix such kind of issues. Sorry it did not help as much.

**Comment by Dimous** [comment]
No worries! My previous comment sounds like a mute reproach, but it's not 😂
It's the same situation with https://armory3d.org/demo/animation/ It's definitely a Firefox issue.
