### ISSUE TITLE
Cloned updatable tubes don't update correctly

### ISSUE THREAD

**Issue by fmmoret** [BabylonJS/Babylon.js#4946]
# Bugs
- Bug repro on [playground](http://www.babylonjs-playground.com/#165IV6#443):
I've copied over the path3D -- `tube2.path3D = new BABYLON.Path3D(myPath);`. If you comment this out, it'll just error out at  https://github.com/BabylonJS/Babylon.js/blob/fe3e8842a1dea266de88b0ece940b967383a9a9e/src/Mesh/babylon.meshBuilder.ts#L1018
- Expected result:
    Cloned tubes update correctly when you pass them new paths.
- Current result:
    They throw a runtime error. If you fill the path like `https://github.com/BabylonJS/Babylon.js/blob/fe3e8842a1dea266de88b0ece940b967383a9a9e/src/Mesh/babylon.meshBuilder.ts#L1018`, it'll kinda update but tear at the seam.

.....
I'm doing this in my game to mitigate stuttering when I build these tubes.

**Comment by sebavan** [comment]
The main issue is by cloning, the  geometry would be shared then modifying the path would end up modifying it for both objects.

It still does not remove the issue with cloning and updating though but i am not sure it would be suitable for your game.

**Comment by sebavan** [comment]
I fixed the clone issue but you would need to call makeGeometryUnique to ensure the geometry is not shared between your clones.

http://www.babylonjs-playground.com/#165IV6#445

**Comment by fmmoret** [comment]
Cool thanks!
