### ISSUE TITLE
[Bug] GPUParticle clip planes broke GPUParticle emitters

### ISSUE THREAD

**Issue by fmmoret** [BabylonJS/Babylon.js#4954]
# Issue

Repro in GPU particle example playground: https://www.babylonjs-playground.com/#PU4WYI#4 from https://doc.babylonjs.com/babylon101/particles#gpu-particles 

I'm getting 
`404 Not Found - Unable to load src/Shaders/ShadersInclude/clipPlaneVertexDeclaration2.fx`
after bumping my babylon version when using GPU particles. It tries to make a network request to load the file.
It's not clear to me how https://github.com/BabylonJS/Babylon.js/commit/2de9bb3e818df3e505df013290814bd4e5649e98 broke it.

**Comment by sebavan** [comment]
Thanks for reporting, I am fixing it ASAP.

**Comment by sebavan** [comment]
Fixed in https://github.com/BabylonJS/Babylon.js/pull/4956
