### ISSUE TITLE
Use standarized wheel event

### ISSUE THREAD

**Issue by haroldma** [BabylonJS/Babylon.js#4976]
[Code](https://github.com/BabylonJS/Babylon.js/blob/9d6f4db1e205c72ad58dc8168dda72ccda2ac3e3/src/babylon.scene.ts#L2195-L2196)

Both `mousewheel` and `DOMMouseScroll` are non-standard events. Babylon should use standardized wheel event if available (`wheel`).

**Comment by sebavan** [comment]
@haroldma, Is it creating some direct impact on your project?

If not, I would prefer to keep track of it for after the release as changing those events unfortunately always put us in trouble in the past in respect of back compat with older browsers.

**Comment by sebavan** [comment]
Perfect, I ll flag the issue as a 4.0 to ensure we ll have enough time to go through a lot of testing.

Thanks,

**Comment by sebavan** [comment]
This does not create any issue in BJS so far but would be good to follow the standard, there is no rush on it:
https://playground.babylonjs.com/#5YNU3K
