### ISSUE TITLE
Add more gradient to particles

### ISSUE THREAD

**Issue by deltakosh** [BabylonJS/Babylon.js#4979]
- [x] emitRate over time
- [x] Start size over time
- [x] Drag over time

**Comment by deltakosh** [comment]
@PatrickRyanMS:  Emit rate is done ==> http://doc.babylonjs.com/babylon101/particles#emit-rate-over-time

**Comment by PatrickRyanMS** [comment]
I will test it out. Thanks!

**Comment by deltakosh** [comment]
@PatrickRyanMS: start size done ==> http://doc.babylonjs.com/babylon101/particles#start-size-over-time

**Comment by deltakosh** [comment]
@PatrickRyanMS : and Drag ==> http://doc.babylonjs.com/babylon101/particles#drag-factor
