### ISSUE TITLE
Add BLENDMODE.MULTIPLY as an option for particle blending

### ISSUE THREAD

**Issue by PatrickRyanMS** [BabylonJS/Babylon.js#4983]
# Feature request
Add another blendmode to allow particles to multiply against each other. This should work with alpha similar to BLENDMODE_STANDARD and BLENDMODE_ADD, but using a multiply function instead.

This would be useful for smoke particles so that we can use a lighter color on the individual particle and have the smoke get darker with more particle density just as ADD does for brightness.

**Comment by deltakosh** [comment]
I've just pushed a new blend mode (BLENDMODE_MULTIPLY) which will multiply particle's color with current color.
Let me know if this is what is expected :)

**Comment by PatrickRyanMS** [comment]
Looks like we aren't respecting alpha with multiply like we do with BLENDMODE_ADD

**Comment by deltakosh** [comment]
Well this is expected as I've used a srcColor*destColor
Would you expect to be srcAlpha*srcColor*destColor ?

**Comment by deltakosh** [comment]
After checking more into it, webgl as no way to do a triple multiplication.
So if we want to use multiply, the alpha cannot be taken in account. Perhaps setting the texture background to white should be enough?

**Comment by deltakosh** [comment]
To give more context, this is how we can control the blending pipeline:
https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/blendFunc#Constants

**Comment by PatrickRyanMS** [comment]
In thinking about how we can get around this in the texture, I can't use white for the background because we are using a white texture with alpha to multiply the particle color against so we have the most flexibility with color over time in the system. We would need to multiply the particle color by the texture then add 1 minus alpha to the texture before multiplying SrcDst
