### ISSUE TITLE
Possible Bug in Mesh.bakeTransformIntoVertices

### ISSUE THREAD

**Issue by apptaro** [BabylonJS/Babylon.js#4987]
See here:
https://github.com/BabylonJS/Babylon.js/blob/master/src/Mesh/babylon.mesh.ts#L1748

When the vertex buffer has positions but not normals, bakeTransformIntoVertices will return without restoring submeshes. I don't know what is the consequence of it, but it smells like a bug.

**Comment by deltakosh** [comment]
Oups ;)

I'll fix that immediatly
