### ISSUE TITLE
Particles isStarted behaves differently with gpu than cpu particles

### ISSUE THREAD

**Issue by TrevorDev** [BabylonJS/Babylon.js#4991]
gpuParticles isStarted is never false after started
cpu isStarted is set to false after stop() and all particles have disapeared

Neither of these behaviors is what I expected, I expected this to be true when start() is called and false after stop() is called

See http://localhost:1338/Playground/index-local.html#ZWE24S#11 vs http://localhost:1338/Playground/index-local.html#ZWE24S#19

@deltakosh do you agree with this or is one of the existing behaviors correct?

**Comment by deltakosh** [comment]
Here is the reason why: http://doc.babylonjs.com/babylon101/particles#stopping-a-gpu-particle-system

Does it make sense?

**Comment by deltakosh** [comment]
for the cpu, we could change it to be like you wanted it to be. I see no problem with that.
Same for GPU actually but users have to understand that the system is not REALLY stopped
