### ISSUE TITLE
Starting/stopping gpu particles causes large burst

### ISSUE THREAD

**Issue by TrevorDev** [BabylonJS/Babylon.js#4992]
See http://playground.babylonjs.com/#ZWE24S#21

Expected starting again will have the same behavior as starting initially, this works using cpu particles

**Comment by deltakosh** [comment]
same reason as here: #4991

**Comment by deltakosh** [comment]
When stopped, the GPU particles are only hidden. We need to find a better way to stop it if we want to fix that behavior
