### ISSUE TITLE
Pointer Drag Behavior keeps offsetting with every click when using a custom matrix

### ISSUE THREAD

**Issue by haroldma** [BabylonJS/Babylon.js#5005]
[Playground](http://www.babylonjs-playground.com/#IP9IBX)

**Comment by sebavan** [comment]
Adding @TrevorDev  as I guees it is pretty close from the guizmo one ???

**Comment by TrevorDev** [comment]
It is similar but it looks like this time the pivot is being set using the older method (second parameter set to false). It works as expected if the second parameter isn't set see: http://www.babylonjs-playground.com/#IP9IBX#1 

@haroldma, is it possible to rework your code to use the newer pivot as in the PG above, or by using a parent node acting as a pivot as in this PG https://www.babylonjs-playground.com/#GH4N1R#1 or are those solutions unreasonable?

**Comment by haroldma** [comment]
@TrevorDev that also breaks if you scale the mesh: http://www.babylonjs-playground.com/#IP9IBX#2

**Comment by TrevorDev** [comment]
Gotcha, I'll investigate further

**Comment by TrevorDev** [comment]
@haroldma, closing this as the change was merged. Please let me know if you find any other issues with this.
