### ISSUE TITLE
NoiseProceduralTexture causing compile errors on some GPUs

### ISSUE THREAD

**Issue by andy-hanson** [BabylonJS/Babylon.js#5008]
- Bug repro on [playground](https://playground.babylonjs.com): https://playground.babylonjs.com/ts.html#Y3VC4C
- Expected result: No compile error.
- Current result:
```
Unable to compile effect: babylon.js:1:108460
Uniforms:  brightness, octaves, persistence, timeScale babylon.js:1:108460
Attributes:  position babylon.js:1:108460
Error: ERROR: 0:37: 'i' : Loop index cannot be compared with non-constant expression
```

Note: This only happens on my desktop and not on my laptop, so this likely has to do with the webgl capabilities available.

**Comment by julien-moreau** [comment]
Will check that ASAP :)

**Comment by julien-moreau** [comment]
Found that is not possible to stop a for loop dynamically using an uniform

To perform the motion blur, for example, the trick was to give a define and check the « i » value :( https://github.com/BabylonJS/Babylon.js/blob/master/src/Shaders/standard.fragment.fx#L443

**Comment by deltakosh** [comment]
Fixed:)

**Comment by deltakosh** [comment]
https://github.com/BabylonJS/Babylon.js/commit/6dcd6110dd20944e1e24f554bc1eba3927ad5bf4
