### ISSUE TITLE
If a font is loaded after rendering a TextBlock, it doesn't refresh

### ISSUE THREAD

**Issue by haroldma** [BabylonJS/Babylon.js#5048]
You just get a permanent box in place of the actual char.

**Comment by deltakosh** [comment]
Well this is expected. You can force the ADT to refresh by calling adt.markAsDirty()

**Comment by haroldma** [comment]
Any recommended way of knowing when a font is loaded to call this?

**Comment by deltakosh** [comment]
Not that I'm aware of:(
