### ISSUE TITLE
Node Graph Recursion, Performance and Improvements 

### ISSUE THREAD

**Issue by Bolloxim** [BabylonJS/Babylon.js#5050]
During my endeavours to improve object rendering performance, we fixed an issue with graphing always having to update parents submission #5040 

over a 10 second window we walked we spent 1362ms walking graphs to validate they are not dirty, basically 13% overhead in graph traversal  this is not insignificant. 

Nodes use code recursive not data recursive methods, mainly because the nodes could evaluate themselves differently.  

In addition to this freezing matrices has to be done per node. This should be per branch or even tree.  If I freeze the root with all children this should explicitly set all children. This could mean we use the a set of root flags to determine frozen states for static geometry once the world matrix is computed it remains static.  Having a root object per node shortcut would then let us just skip to the head of the line to determine node properties for the tree or branch quickly thus removing the necessity to check all parents states. 

Im proposing a couple of changes here. 
1. a method to freeze all matrices in the tree by selecting the root node. Along with a method to detect that changes at the node level rapidly without code recursion.
2. a method to flag the set and test the dirty flag on the trees depth.
3. for animations a fast data recursive method to traverse the nodes rapidly looking for hierarchy changes
4. re-evaluate performance and determine if we need any additional steps.

**Comment by deltakosh** [comment]
This is really great!!

I'm now really curious on how you would like to implement all these great ideas

**Comment by Bolloxim** [comment]
**Node Graph Changes Proposals** 

Some fundamentals

- The node graph is code recursive. 
- Its traverses up when computing transform nodes
- Normally this means checks if cached all the way up. 
- Then a child can get rendered and we do the same thing.
- Its kind of cumbersome and inefficient.

This is due to evaluateActiveMeshes actually walking all meshes and computesWorldMatrix on each mesh.. This means we walk the tree many times.  Yep not good. 

Ideally we would want to do a run over the entire graph once and as quick as possible this means flagging the graph as to what’s changed and where. Simplest is to flag a rootNodeContainer in the scene which all subsequent children can talk to,  should for example a child node get updated it would register itself with the rootnode as being updated. 

So we create a new function ComputeAllWorldTransforms. This will walk through the tree and update all objects however we should clue list tree traversal into being somewhat smart. Why walk the entire tree if branches arent even dirty so we can easily do this just on the parent tree. 

First steps
Node structure adds value and a rootNodeReference : Node 

When we do any processing of transforms, IE change position etc we update the rootNodeReference.DirtyFlag = true;

We process all rootNodes in the scenes. Anything with the dirty flag is evaluated.

We traverse down the graph checking for dirty nodes, once we find a dirty node, from that point on we update the transforms all the way down to the leaves.  

The function ComputeAllWorldTransforms is not code but data recursive it's basically walking the tree looking for transform nodes to transform that are flagged dirty.  

This basically means we change evaluateActiveMeshes so it does not call computeWorldMatrix but just GetWorldMatrix now and this should resolve recursion.

**Comment by Bolloxim** [comment]
I would have no problem coding on this and testing the results difference and obviously making sure it  passes the validation tests :)

**Comment by deltakosh** [comment]
I thought about this long time ago but the main problem with dirty flags was: how can we make sure that mesh.position.x = 1 will trigger the dirty flag? It is not possible to move the vector3 class to use properties as everything else will be dead slow.

But I really like the idea of going down the tree only once while evaluating the active meshes. We would need rootNodes but this should be OK to get and from there we could evaluate the WM more efficiently. The evaluateActiveMeshes function will start from rootNodes and evaluate if their wm needs to be updated if yes then we could flag the node as wasUpdated. Then going down the tree we could just check if a node needs an update (with the cache of its own values or if parent.wasUpdated). If updated then we flag it. And so on. Obviously when arriving on a node we just have to first flag it as wasUpdated = false.

The only overall problem I see with this approach is when you change something related to WM during rendering (like onBeforeDraw). In this case the update will not be visible before next frame (unless the user call getWorldMatrix(true) first)

**Comment by deltakosh** [comment]
Also to keep backward compatibility, the current computrWorldMatrix function should remain unchanged and we can introduce the change by adding an optional parameter (default is false) which will turn on the wasUpdated way

Thoughts?

**Comment by deltakosh** [comment]
The first things to do:
- [ ] add a scene.rootNodes array
- [ ] update node constructor to add all nodes to this array
- [ ] expose the node.children property to get direct access to children 
- [ ] update node.parent property to add/remove mode from/to scene.rootNodes

**Comment by deltakosh** [comment]
_(I'm wondering if we need a rootNodes or only a rootTransformNodes as we do not care about Node from a WM standpoint)_

**Comment by Bolloxim** [comment]
Setters should get around the issue.  Use private on the transforms and only allow access through the const getter/setter method this should ensure the vector is updated only through setter. likewise for rotation and scale.  This gets around a lot of those position/rotation checks.

you dont need to worry about parent is updated because once you find the dirty node and start data recursing down that branch you've just set the update flag in the function for all cwm as they are parented from that point onwards, gets around redundancy testing.  in fact you could call a single function in the branch to computeWorldMatricesInBranch. So that there is an optimal just recompute dont bother testing (except for frozen matrices).

in regards to frozen matrices, you can do frozen including children. vs frozen only.  This difference would then let us freeze trees rather than just freeze a single node.. so freeze + children on the rootnode freezes everything ..

so I think some things are redundant because we are computing all world matrices anyway so having to test if a parent is updated is kind of mute at that point. 

scene.rootNodes makes total sense.  I was thinking of adding an updatedRootsNode so we only have to test those nodes per frame as well.  this is cleared to empty post rendering (or at least double buffered for debugging purposes , ie currentUpdate/previousUpdate and flip each frame) 
this way if you have 4000 scene objects but only 30 moving .. we are just adding and walking those 30 nodes anyway dont even have to test then we know they updated :)

-[ ] add a scene.rootNodes array
-[ ] add a scene.dirtyRootNodes array (possibly double buffered for debug)
-[ ] update node constructor to add all nodes(topmost) to this array
-[ ] expose the node.children property to get direct access to children
-[ ] update node.parent property to add/remove node from/to scene.rootNodes
-[ ] update node.dispose to remove nodes from rootNodes when no parent

-[ ] add setter/getter accessors for position, rotation, scale for each transform.node
-[ ] add frozenChildren flag to transform.node
-[ ] add a scene.computeAllWorldMatrices() function and call it around here. This function will call computeWorldMatrix with the new parameter set to true on the node and then recursively on all children. After having gone through all children of a node wasUpdated is set to false.
-[ ] scene.recomputeAllWorldMatricesInBranch(branchnode :Node) // indicating every after this requires a forced update unless frozen


think this is shaping out well :)

**Comment by Bolloxim** [comment]
oooh i see your problem sublevel properties are not immutable even with const getter only the object itself is unchangeable.  the graph could just private the position/rotation/etc and only allow setters on the transform node.  Then add a get function thats basically a shallow copy.  Ideally you'd want to store locations etc in your own structures and just set them to the scene transformnode.  
Rarely do you want to use that to store your data.

**Comment by deltakosh** [comment]
We cannot add setter to position, rotation or scaling to earn about deprecation as we do not Deprecated because backward compatibility is a top priority

**Comment by deltakosh** [comment]
We can't go down the dirty flag path. If you look in the playground examples, developers are using position.x to animate meshes a lot. 
So I think my initial idea with wasUpdated is the good tradeoff

**Comment by Bolloxim** [comment]
so ok I understand your backward compatibility logic although I thought I had addressed that using deprecated warnings.  modifying transforms without using an interface really is a not a good idea.   Also a programmer shouldnt be creating a new vector each time to modify position. etc they would have a gaming structure with position etc. and then that would set that which would basically do a shallow copy... 

However, all said and done, to keep with this architecture then we can figure this out:

This approach tweek is to keep track of the active transform nodes separately and walk those before computing world matrices.  That way we get the testing out of the way independent of graph traversal. It should be faster still and this is a simple update check. 

- [ ] register all transform nodes not frozen into a list `scene.activeTransformNodes`
- [ ] register all nodes into scene graph as described above
- [ ] add a dirtyCounter to the rootnode
- [ ] nodes frozen and unfrozen are added or removed from the `scene.activeTransformNodes`

- [ ] walk this list testing for changes with position etc.  this function would be `scene.updateActiveTransformNodes`. This would effectively call `node._IsDirty = !node._isSynchronized();` on the transform.node and not check for parents. It will only check active transforms. Dirty flags would then increment a `node.rootNode.DirtyCounter++`.

- [ ] `scene.computeAllWorldMatrices` would walk the the scene root nodes checking for the `rootNode.DirtyCounter` for updating, if so we would walk through as before checking for nodes to update in the graph.  Decrementing the `rootNode.DirtyCounter--` as we find those nodes

`rootNode.DirtyCounter` is useful for traversing just a branch updating.  If we get a single leaf at the end of a branch need updating we know once we hit the dirty counter we are done. Though dirty nodes still have to update their children. This is useful for endpoints in a graph updating.  Its not completely optimal because could be the last leaf ever tested.

**Comment by deltakosh** [comment]
Well I need to see the tests now because it seems overkill to manage this dirty flags where we can just walk the tree once a frame (that you will have to do anyway if I understand correctly). 

When will you update this flag? I guess once per frame by going through the list of active transform (which should be comparable to walking the tree).

I'm still convinced that the dirty Counter is not required but happy to change my mind if numbers prove that it is worth it:)

**Comment by deltakosh** [comment]
I'll implement the rootNodes changes 
THen I'll do a PR for the wasUpdated and we can then compare performance

**Comment by deltakosh** [comment]
rootNodes done..

**Comment by Bolloxim** [comment]
actually anything we can do to avoid doing a computeWorldMatrix is good, we should look at optimizing that code. for example we compute the inverse but dont store the determinate computed in the use of the inverse. then we compute the determinate right after..  where as could store the determinate or just create an inverse using it..  either/or.    
so the entire point of dirty flag is to 

- A) avoid traversal if possible.  
- B) avoid computeWorldMatrix 
- C) avoid calling isSyncronized as much as possible though this is now called per transformnode
- D) using isDirty boolean walking data is way faster than calling isSync function.. overhead is minimal

long term it may open for optimzation pipe where we can avoid updating all transforms and just manually flag dirty for 'advanced' engine users perhaps ?  

checking out the nodes tonight..

**Comment by deltakosh** [comment]
But as we can't use properties the dirtyFlag has to be tested with isSynchronized which can be done while walking the tree so no need for dirtyFlag at all. We just walk the tree, check if the node isSyncrhonized, if not we computeWorldMatrix, set the node.wasUpdated = true, run down the children and reset node.wasUdpated after processing children.

I agree that computeWorldMatrix must be avoided as much as possible and that's what we tend to do already

D) Sorry but I don't see why this is needed as we need to call isSync to get the isDirty

**Comment by deltakosh** [comment]
By the way, do you have a test scene in the PG by any chance?

**Comment by deltakosh** [comment]
Ok I did the PR, you can have a look when you have a chance

**Comment by Bolloxim** [comment]
I checked out the branch I created a test scene thats just spheres but might not be a good example, its spending more time in MeshRender than it is in graphing. 
[node-test.zip](https://github.com/BabylonJS/Babylon.js/files/2355744/node-test.zip)

**Comment by Bolloxim** [comment]
btw, Im on Pacific timezone, but not available till evenings so, sorry about sluggish response times :)
i ran that on the graphImprovements and we are slower walking through all I am rotating just root node though..  in comparision I ran 1000 spheres without parenting @ 60hz.. could be parenting is re-rendering that sphere hierarchy multiple times :)

**Comment by deltakosh** [comment]
I'm on PST as well (seattle :))
So I'm seeing an improvement regarding performance of WM computation.
From:
![image](https://user-images.githubusercontent.com/1306056/45167661-775fe800-b1ae-11e8-96e0-d1108cedd891.png)

To:
![image](https://user-images.githubusercontent.com/1306056/45167636-6ca55300-b1ae-11e8-8f3e-de599a1c34a6.png)

Not a big deal but still improvement and code is cleaner so I'll merge it

**Comment by Bolloxim** [comment]
ok so i thought we could do better here but not certain.  I still think we are overwalking and over transforming.  Question though ? how can I reference a single created sphere and render through references to that sphere rather than running out of memory creating 10,000 of them ?

**Comment by deltakosh** [comment]
You can use clone which will share the geometry but still do a draw call per mesh.
Or you can use createInstance and then it will be only a single draw call
