### ISSUE TITLE
useRightHandedSystem and GizmoManager and ArcRotateCamera causes scene to disappear

### ISSUE THREAD

**Issue by AlexMuir** [BabylonJS/Babylon.js#5055]
Given:
- a scene with useRightHandedSystem
- viewed through an ArcRotateCamera
- and with a gizmo enabled

The scene will disappear whenever the camera is dragged and then the motion finishes.

Playground:  https://www.babylonjs-playground.com/#N0ICEP

**Comment by TrevorDev** [comment]
@AlexMuir I was able to repro this yesterday but can't anymore, I think 
https://github.com/BabylonJS/Babylon.js/pull/5075 
might have fixed it. Let me know if you still are able to repro on the playground.
