### ISSUE TITLE
Gizmos doesn't work using firefox

### ISSUE THREAD

**Issue by ladevieq** [BabylonJS/Babylon.js#5065]
Using firefox gizmos doesn't works and the drag and drop neither.
Object doesn't move, rotate or scale but the gizmos are visibles.

The gizmos works correctly on Edge and Chrome, but with firefox 62 and 63 nothing append.

You can check this behavior using this [playground](http://playground.babylonjs.com/#8MGKWK#25)

**Comment by nathanidp** [comment]
@TrevorDev , also I think pointer events block the camera. Once you click on a gizmo you can't rotate the camera 

Is this linked with the Gizmo ? Because by using sprites and spritePicking, the camera is also blocked.

https://www.babylonjs-playground.com/#31M2AP#6

**Comment by TrevorDev** [comment]
@nathanidp Yep, next nightly with the PR that was merged above should fix this.
