### ISSUE TITLE
Calling `refreshBoundingInfo` on a LinesMesh might prevent picking from working

### ISSUE THREAD

**Issue by barroij** [BabylonJS/Babylon.js#5066]
When a LinesMesh is created, a minimum size in x,y,z is given to the bounding box. This is specially usefull for picking.
When calling `refreshBoundingInfo` on a LinesMesh, this threshold is not applied anymore and the line cannot be picked anymore.

- Bug repro on http://www.babylonjs-playground.com/#1I4F1D#11
- Expected result: Event after a call to `refreshBounding`, I should be able to pick the line.
- Current result: Picking does not work anymore.

**Comment by barroij** [comment]
Additional note ; the code that adds extra extends to the BoundingBox for LinesMesh is :
`
if (mesh.getClassName() === "LinesMesh") {
  this.boundingBias = new BABYLON.Vector2(0, mesh.intersectionThreshold);
  this._updateExtend();
}
`

In the constructor of the `Geometry` class

**Comment by deltakosh** [comment]
Thanks for mentioning that bug! I'll fix it now :)
