### ISSUE TITLE
AdvancedDynamicTexture for mesh doesn't Materials it created when it's disposed

### ISSUE THREAD

**Issue by Exolun** [BabylonJS/Babylon.js#5078]
Bug repro on [Modified GUI Playground](https://www.babylonjs-playground.com/#ZI9AK7#261)

Expected result:
- Cleanup of material created when AdvancedDynamicTexture is disposed

Current result:
- Material count is unchanged after disposal

**Comment by deltakosh** [comment]
excellent repro! I'll fix that asap!

**Comment by deltakosh** [comment]
Actually it is not a bug. The material cannot be dispose implicitly as it is still used by the Plane.
You must force it manually (and the material can also explicitly dispose the texture)

https://www.babylonjs-playground.com/#ZI9AK7#262
