### ISSUE TITLE
ImportMesh has different behavior than in stable

### ISSUE THREAD

**Issue by TrevorDev** [BabylonJS/Babylon.js#5079]
See:
https://www.babylonjs-playground.com/index.html#17MXFZ#33
https://www.babylonjs-playground.com/indexStable.html#17MXFZ#33

Observe that in the stable version the ufo is loaded in front but in most recent it is loaded behind.
Expected it to be loaded in front.

**Comment by deltakosh** [comment]
I think it is expected as gltf spec recently defined the front direction but @bghgary can confirm that

**Comment by TrevorDev** [comment]
Closing, this was caused by camera being at 0,0,0 and calling lookat 0,0,0 which behavior is undefined
