### ISSUE TITLE
GLTFLoader importMeshAsync throws 'Cannot read nodes of undefined' error

### ISSUE THREAD

**Issue by vtange** [BabylonJS/Babylon.js#5080]
I get this with any .gltf or .glb after updating from BabylonJS 3.1 to 3.2 and beyond

1. npm install babylonjs@3.2, babylonjs-loaders@3.2
2. import * as BABYLON from 'babylonjs';  import 'babylonjs-loaders';
3. 			BABYLON.SceneLoader.ImportMesh("a", "assets/", "boxgun.glb", scene, function (meshes) {
				if(!meshes.length)
				{
					console.log("failed to load model: ", mesh[0], mesh[1], mesh[2]);
					fail();
					return;
				}
				console.log(meshes);
				resolve(true);
			});
![untitled](https://user-images.githubusercontent.com/4667949/45198027-23d6b400-b219-11e8-85ac-de09b6f0bb34.png)

[glb.zip](https://github.com/BabylonJS/Babylon.js/files/2359479/glb.zip)

**Comment by bghgary** [comment]
I am pretty sure this is a dupe of #4929 and is already fixed in the 3.3 preview version. @vtange can you try against the preview version?

**Comment by vtange** [comment]
Thank you for the note. I checked babylonjs@3.3.0-beta.3 and babylonjs-loaders@3.3.0-beta.3 and confirmed it is fixed.

Closing this issue. Sorry for the dupe.
