### ISSUE TITLE
Bug on Samsung 5sMini

### ISSUE THREAD

**Issue by PixelsCommander** [BabylonJS/Babylon.js#5082]
The combination of having lights and reflection maps produces this kind of bugs on Samsung 5s Mini and Samsung Tab A.

![screenshot_2018-07-06-16-08-49](https://user-images.githubusercontent.com/810671/45207281-e8bf9980-b287-11e8-82f5-600b6fe46756.png)

**Comment by deltakosh** [comment]
Can you get the content of the console?
This is probably because the webgl implementation of this device does not support enough uniforms so the system tries to reduce shader complexity
It could be worth trying with webgl2 turned off

**Comment by PixelsCommander** [comment]
Did not worked unfortunately. For now we fixed with disabling lights and reflection textures, adding emission to every object on the stage for this device. However if you have any more ideas - would be nice and we can try to fix and make a PR.

**Comment by PixelsCommander** [comment]
engine.getCaps().highPrecisionShaderSupported = false; also do not help =(

**Comment by deltakosh** [comment]
Does it work if you turn webgl2 off?

**Comment by PixelsCommander** [comment]
I`ve already tried that but this time decided to double check and you know it actually did the trick... Thank you!
