### ISSUE TITLE
"Page not found" url

### ISSUE THREAD

**Issue by Vinc3r** [BabylonJS/Babylon.js#5118]
https://github.com/BabylonJS/Babylon.js/blob/f002185bfefc8224e14e3b0c11063ab6b9bfb70f/src/Mesh/Compression/babylon.dracoCompression.ts#L41

The cliquable url `https://preview.babylonjs.com/` in http://doc.babylonjs.com/api/classes/babylon.dracocompression give us a `Page Not found`.

**Comment by sebavan** [comment]
Fixed
