### ISSUE TITLE
OnIntersectionEnterTrigger only triggered multiple times if combined with OnIntersectionExitTrigger

### ISSUE THREAD

**Issue by simplicitylab** [BabylonJS/Babylon.js#513]
Maybe it is no issue but I didn't saw it mentioned in the documentation

http://www.simplicitylab.be/playground/babylonjs/actions/v1/ (open console.log)

Here you will see an entry being logged when the ball intersects with the blue paddle and stops intersecting (which is great and what I want)

This is the code where I setup my actions (beware code quality isn't great as i'm experimenting) 

````
		//
		// setup action for paddle player 1
		//
		this.paddle_p1.actionManager = new BABYLON.ActionManager(this.scene);
		
		// when the paddle intersects with the ball
		this.paddle_p1.actionManager.registerAction(
			new BABYLON.ExecuteCodeAction({ 
					trigger: BABYLON.ActionManager.OnIntersectionEnterTrigger, 
					parameter: this.ball 
				},function(){
					console.log('intersect enter :' + Date.now());
				}));

		this.paddle_p1.actionManager.registerAction(
			new BABYLON.ExecuteCodeAction({ 
					trigger: BABYLON.ActionManager.OnIntersectionExitTrigger, 
					parameter: this.ball 
				},function(){
					console.log('intersect exit :' + Date.now());
				}));
````

http://www.simplicitylab.be/playground/babylonjs/actions/v2/ (open console.log)

Here on the other hand I only get it 1 "intersect enter"message. The only difference is that I removed the OnIntersectionExitTrigger part.

I'm also a bit confused about the "Raised just once" part mentioned in the documentation, so I don't know what the correct behavior is. 

Does this mean that for the whole scene it is only triggered once like in V2 or does it mean that it gets triggered only once (depending on the overlap you could trigger multiple intersections for example) and gets reset from the moment the intersection exits ?

**Comment by RaananW** [comment]
The idea behind triggered once is that it will behave like mouseover and mouseout - it will trigger the first time it happens and again if the other one was triggered as well.

I believe you are right regarding your second demo - the intersect should be triggered every time it happens again. So - a bug :-)
Will look into it!

**Comment by simplicitylab** [comment]
Thx for the explanation now I understand it!
