### ISSUE TITLE
Ambient sounds cannot be heard after launching the MR portal

### ISSUE THREAD

**Issue by nbduke** [BabylonJS/Babylon.js#5142]
# Bugs

Playground: https://www.babylonjs-playground.com/#PCY1J#54

Repro steps:
1. Make sure you have some working headphones connected to the PC. Also make sure the MR portal is not currently running.
2. Go to the playground scene above, then wait until you hear the music playing.
3. Click the VR headset icon. This will launch the Windows MR Portal.

Result: The music ceases to be audible. It no longer plays in your original headphones, and even if your headset has built-in headphones, the music isn't audible there either. Moreover, hitting escape to exit VR mode doesn't bring the music back. The browser thinks the music is playing, though (it shows the speaker icon in the browser tab).

Expected: The music should be audible in either the original headphones or the headset, depending on your MR portal settings.

**Comment by deltakosh** [comment]
Unfortunately this is more an Edge but than a Bjs bug :(

**Comment by nbduke** [comment]
Turns out, I can repro this in Chrome:

1. Go to the playground I linked in Chrome.
2. Open the MR Portal through the start menu in Windows.

This will silence the audio as well. Interestingly, I don't see the same issue with other audio sources, for example, Spotify and YouTube in the browser.

**Comment by deltakosh** [comment]
Interesting. I repro (Actually I'm losing the sound AND my keyboard when I do that :))
They seem to mess with the WebAudio API somehow
I bet Youtube and Spotify should rely on Audio tag and not webaudio

**Comment by deltakosh** [comment]
Even this demo does not work: https://webaudiodemos.appspot.com/midi-synth/index.html

**Comment by nbduke** [comment]
Ok, I figured it had something to do with WebAudio. It's clear that it's not a Babylon-specific issue. Do you have any contacts on the team that maintains the MR Portal? It would be good to raise this issue with them.

**Comment by deltakosh** [comment]
Pinging @davrous  who may know better than me

**Comment by nbduke** [comment]
Ping... @davrous
