### ISSUE TITLE
 If-clause in manifestChecked confusing

### ISSUE THREAD

**Issue by bestog** [BabylonJS/Babylon.js#5147]
https://github.com/BabylonJS/Babylon.js/blob/ce77425ddfaa3ac1bafa9657a7a1f6c4eba99fee/src/Loading/babylon.sceneLoader.ts#L306

Isn't it better to reverse the statement? Since we can assume that the `exception` is not _undefined_ or _null_ and we can access the property `message`? 

```javascript
onError("Failed to load scene." + (exception ? " " + exception.message : ""), exception);
 ```

**Comment by deltakosh** [comment]
Correct!
Will fix that ;)

**Comment by bestog** [comment]
Thank you =)
