### ISSUE TITLE
using BABYLON.GUI.Slider causes the model to get cleared to the background color

### ISSUE THREAD

**Issue by kcoley** [BabylonJS/Babylon.js#5152]
- Bug repro on [Babylon.js skeleton slider demo](http://playground.babylonjs.com/#u9ac0n#1):
- Expected result: The model rotates without being visually erased
- Current result: The model gets erased during each slider update
Before slider update:
![image](https://user-images.githubusercontent.com/3946928/45578114-6fe6b180-b834-11e8-9cc5-967725ba8333.png)

After slider update:
![image](https://user-images.githubusercontent.com/3946928/45578028-fcdd3b00-b833-11e8-8bde-c09bab1f45f5.png)

**Comment by deltakosh** [comment]
Oops ;)
