### ISSUE TITLE
suggestion - remove debug layer in production code

### ISSUE THREAD

**Issue by RaananW** [BabylonJS/Babylon.js#518]
Using gulp and the new configuration file it is easy to "remove" the debug layer when creating the minified version (or better - add it to the max file only). 
I for once would not want people to have such a powerful GUI tool while playing a game created with bjs.
What do you say? Are there any other debug features that can come out in production?

**Comment by deltakosh** [comment]
I have to disagree here. Being able to enable debug functions even on production code is invaluable to fix customer issue.

**Comment by RaananW** [comment]
Dunno, I think the production code should not include such features, but I can understand the point in having it.  Just a suggestion :-) 
I guess it will change the playground as well... Closing.
