### ISSUE TITLE
wrong parameter offset for 32bit indexFormat calling _gl.drawElements

### ISSUE THREAD

**Issue by JPoepsel** [BabylonJS/Babylon.js#519]
When using subMesehs for a mesh, the start index is not correctly multplied by the typesize of the index buffer Format. Instead, alway 2 is used (shoulr be 2 or 4!):

```
===================================================================
--- babylon.2.0.debug.js	
+++ babylon.2.0.debug.js	(working copy)
@@ -4111,11 +4111,12 @@
             this._drawCalls++;
             // Render
             var indexFormat = this._uintIndicesCurrentlySet ? this._gl.UNSIGNED_INT : this._gl.UNSIGNED_SHORT;
+            var mult = this._uintIndicesCurrentlySet ? 4 : 2;
             if (instancesCount) {
-                this._caps.instancedArrays.drawElementsInstancedANGLE(useTriangles ? this._gl.TRIANGLES : this._gl.LINES, indexCount, indexFormat, indexStart * 2, instancesCount);
+                this._caps.instancedArrays.drawElementsInstancedANGLE(useTriangles ? this._gl.TRIANGLES : this._gl.LINES, indexCount, indexFormat, indexStart * mult, instancesCount);
                 return;
             }
-            this._gl.drawElements(useTriangles ? this._gl.TRIANGLES : this._gl.LINES, indexCount, indexFormat, indexStart * 2);
+            this._gl.drawElements(useTriangles ? this._gl.TRIANGLES : this._gl.LINES, indexCount, indexFormat, indexStart * mult);
         };
         Engine.prototype.drawPointClouds = function (verticesStart, verticesCount, instancesCount) {
             // Apply states

```

**Comment by RaananW** [comment]
Would be great to get that as a pull request to be able to correctly test it :-)

**Comment by JPoepsel** [comment]
Hi there!

 

Sorry, I do not have any experiences with Git. But adding one line of code and changing two “2” into two “mult” is not so much work for you… ;-) 

Or use my version appended to this  mail;-)

 

CS

 

Josef

 

 

Von: Raanan Weber [mailto:notifications@github.com] 
Gesendet: Dienstag, 19. Mai 2015 13:28
An: BabylonJS/Babylon.js
Cc: JPoepsel
Betreff: Re: [Babylon.js] wrong parameter offset for 32bit indexFormat calling _gl.drawElements (#519)

 

Would be great to get that as a pull request to be able to correctly test it :-)

**Comment by RaananW** [comment]
yep, you are right, but developers are lazy :-) (here - http://jaxenter.com/results-developers-strategically-lazy-113513.html). apart from that, I thought you would like to be on the contributors list. 

We will look into it and keep this issue updated. Thanks for submitting!!

**Comment by JPoepsel** [comment]
> yep, you are right, but developers are lazy

 

Now you got it ;-) (not you, I’m the developer ;-)))

 

Von: Raanan Weber [mailto:notifications@github.com] 
Gesendet: Dienstag, 19. Mai 2015 15:14
An: BabylonJS/Babylon.js
Cc: JPoepsel
Betreff: Re: [Babylon.js] wrong parameter offset for 32bit indexFormat calling _gl.drawElements (#519)

 

yep, you are right, but developers are lazy :-) (here - http://jaxenter.com/results-developers-strategically-lazy-113513.html). apart from that, I thought you would like to be on the contributors list. 

We will look into it and keep this issue updated. Thanks for submitting!!

**Comment by deltakosh** [comment]
This is a good bug:) I'll fix it:)
