### ISSUE TITLE
Mesh.MergeMeshes does not support merging meshes with multiple different materials

### ISSUE THREAD

**Issue by TrevorDev** [BabylonJS/Babylon.js#5197]
- Link to [forum](http://www.html5gamedevs.com/topic/40036-merge-mesh-and-multimaterial/?tab=comments#comment-228705) discussion about the feature:
- Feature description:
See [MergeMeshes](https://github.com/BabylonJS/Babylon.js/blob/8188fc77fe892d4213763b42945be16fb05e20dd/src/Mesh/babylon.mesh.ts#L3598) Observe that the resulting mesh's material comes from the first mesh and that if the input meshes contain submeshes the resulting mesh does not contain their submeshes.
- Additional links that could help implementing the feature:
https://doc.babylonjs.com/how_to/multi_materials

**Comment by deltakosh** [comment]
You are more than welcome!

**Comment by danjpar** [comment]
I have not yet figured this out, but I think I'm making progress. I have an idea of what should take place to accomplish this. Each submesh and submaterial for each merging mesh should be combined as the new mesh. So 3 mesh cubes subdivided 6 times, each with a different multimaterial and 6 submaterials, should result in a mesh with 18 submeshes and a multimaterial with 18 submaterials in order of materialindex.

I found this [playground ](https://www.babylonjs-playground.com/#1WYYET#7) from this [thread](http://www.html5gamedevs.com/topic/28617-extract-verticedata-from-submesh/). I have been fiddling with parts of this function but cannot get UVs correct. Perhaps it's because I don't fully understand what is going on with the nested for loop and why everything is multiplied by 3.

On a side note, while going through the vertexbuffer, particularly PositionKind, after I round a mesh's scaling and positions to 3 decimals then do bakeCurrentTransformIntoVertices, the vertexbuffer data has 15 decimal places.

**Comment by deltakosh** [comment]
Agree on the overall idea (and we need to turn that option off by default btw)

**Comment by danjpar** [comment]
I have a working javascript function. I will work on the TypeScript tomorrow

`Mesh.MergeMeshes = function (meshes, disposeSource, allow32BitsIndices, meshSubclass, subdivideWithSubMeshes, multiMultiMaterials) {
        if (disposeSource === void 0) { disposeSource = true; }
        var index;
        if (!allow32BitsIndices) {
            var totalVertices = 0;
            // Counting vertices
            for (index = 0; index < meshes.length; index++) {
                if (meshes[index]) {
                    totalVertices += meshes[index].getTotalVertices();
                    if (totalVertices > 65536) {
                        _Misc_logger__WEBPACK_IMPORTED_MODULE_19__["Logger"].Warn("Cannot merge meshes because resulting mesh will have more than 65536 vertices. Please use allow32BitsIndices = true to use 32 bits indices");
                        return null;
                    }
                }
            }
        }
        // Merge
        var vertexData = null;
        var otherVertexData;
        var indiceArray = new Array();
        if (multiMultiMaterials) {
            var subIndex, matIndex;
            var maxValue = 0;
            var materialArray = new Array();
            var materialIndexArray = new Array();
            subdivideWithSubMeshes = false;
        }
        var source = null;
        for (index = 0; index < meshes.length; index++) {
            if (meshes[index]) {
                var wm = meshes[index].computeWorldMatrix(true);
                otherVertexData = BABYLON.VertexData.ExtractFromMesh(meshes[index], true, true);
                otherVertexData.transform(wm);
                if (vertexData) {
                    vertexData.merge(otherVertexData, allow32BitsIndices);
                }
                else {
                    vertexData = otherVertexData;
                    source = meshes[index];
                }
                if (subdivideWithSubMeshes) {
                    indiceArray.push(meshes[index].getTotalIndices());
                }
                if (multiMultiMaterials) {
                    for (matIndex = 0; matIndex < meshes[index].material.subMaterials.length; matIndex++) {
                        materialArray.push(meshes[index].material.subMaterials[matIndex]);
                    }
                    for (subIndex = 0; subIndex < meshes[index].subMeshes.length; subIndex++) {
                        materialIndexArray.push(meshes[index].subMeshes[subIndex].materialIndex + maxValue);
                        indiceArray.push(meshes[index].subMeshes[subIndex].indexCount);
                    }
                    maxValue = materialArray.length;
                }
            }
        }
        source = source;
        if (!meshSubclass) {
            meshSubclass = new Mesh(source.name + "_merged", source.getScene());
        }
        vertexData.applyToMesh(meshSubclass);
        // Setting properties
        meshSubclass.checkCollisions = source.checkCollisions;
        // Cleaning
        if (disposeSource) {
            for (index = 0; index < meshes.length; index++) {
                if (meshes[index]) {
                    meshes[index].dispose();
                }
            }
        }
        // Subdivide
        if (subdivideWithSubMeshes || multiMultiMaterials) {
            //-- removal of global submesh
            meshSubclass.releaseSubMeshes();
            index = 0;
            var offset = 0;
            //-- apply subdivision according to index table
            while (index < indiceArray.length) {
                _subMesh__WEBPACK_IMPORTED_MODULE_11__["SubMesh"].CreateFromIndices(0, offset, indiceArray[index], meshSubclass);
                offset += indiceArray[index];
                index++;
            }
        }
        if (multiMultiMaterials) {
            var multi = new BABYLON.MultiMaterial(source.name + "_merged",scene);
            multi.subMaterials = materialArray;
            for (subIndex = 0; subIndex < meshSubclass.subMeshes.length; subIndex++) {
                meshSubclass.subMeshes[subIndex].materialIndex = materialIndexArray[subIndex];
            }
            meshSubclass.material = multi;
        } else {
            meshSubclass.material = source.material;
        }
        return meshSubclass;
    };`

**Comment by danjpar** [comment]
[Pull Request](https://github.com/BabylonJS/Babylon.js/pull/5789) opened.

**Comment by deltakosh** [comment]
Merged! Thanks a lot
