### ISSUE TITLE
"Defined in" TypeDoc Option

### ISSUE THREAD

**Issue by phuein** [BabylonJS/Babylon.js#5206]
# Feature request

"Defined in [src:line]" enabled option for the doc.

I just noticed a very useful feature that both official TypeDoc and Microsoft Monaco have. I'm not sure if it's a version difference, or theme choice, or a toggle in the config when setting TypeDoc up, but if possible I suggest enabling it. I use API+Docs concurrently all the time. Examples:

http://typedoc.org/api/classes/application.html#constructor
https://microsoft.github.io/monaco-editor/api/modules/monaco.editor.html#colorize

Just under "Overrides", which BJS docs have, it also has "Defined in."

**Comment by deltakosh** [comment]
I see that. Do you know what is the config to apply to Typedoc to generate that?
Our template is here: 
https://github.com/BabylonJS/Documentation/tree/master/typedoc/default

**Comment by phuein** [comment]
For a doc generator, their own docs are extremely lacking in information. After a bunch of trouble, I matched files and found that BJS is either using an _older_ or a _modified_ **Default theme**.

https://github.com/BabylonJS/Documentation/blob/1c1e334b0b5ebf331880ce2c60135769452ff220/typedoc/default/partials/member.sources.hbs
VS
https://github.com/TypeStrong/typedoc-default-themes/blob/master/src/default/partials/member.sources.hbs

To avoid unexpected behavior, I suggest copying the latest Default theme, if not the entire latest TypeDoc project. Otherwise, just copying that extra part will probably do the trick. ;) I'll wait to hear a verdict.

**Comment by deltakosh** [comment]
Well we must have an old one..I'll update that
Thanks a lot
