### ISSUE TITLE
Impossible to update a mesh dynamically

### ISSUE THREAD

**Issue by jroxx911** [BabylonJS/Babylon.js#5220]
Hi, 
I am working with mesh morph dynamically, i am updating a tube in my scene and since this morning it doesn't seem to work anymore, even in your playground. 

# Bugs

- https://www.babylonjs-playground.com/index.html#ACKC2#1 Your playground doesn't work with the latest version but work fine with the stable one. 
- The tube doesn't update itself
- The tube should "dance" just like with the stable version

Cheers

Julien

**Comment by sebavan** [comment]
I am on it, this could be coming from some of our changes yesterday, I might have an idea.
