### ISSUE TITLE
[Regression] babylonjs-gui cannot be used with babylonjs.worker.js anymore

### ISSUE THREAD

**Issue by kkimdev** [BabylonJS/Babylon.js#5235]
There are few different babylonjs versions:
- babylon.js
- babylon.max.js
- babylon.worker.js

But after https://github.com/BabylonJS/Babylon.js/commit/56b22596f0649336fed094df319f9187c244a1f1 , now babylonjs gui files have `import ... from "babylonjs";` hard coded.  For example, https://github.com/BabylonJS/Babylon.js/blob/56b22596f0649336fed094df319f9187c244a1f1/gui/src/2D/style.ts#L1

I have been using babylon.gui.min.js and babylon.worker.js files, not babylon.js, and after the recent update, I get the following error:
```
babylon.gui.min.js?6fcd:1 Uncaught Error: Cannot find module 'babylonjs'
    at webpackMissingModule (babylon.gui.min.js?6fcd:1)
    at eval (babylon.gui.min.js?6fcd:1)
    at eval (babylon.gui.min.js?6fcd:1)
    at Object../node_modules/babylonjs-gui/babylon.gui.min.js (babylon.gui.min.16040689e4924898c7013afa3cc4fd544c69487970337eef8573cff480bc5697.immutable.js:96)
    at __webpack_require__ (babylon.gui.min.16040689e4924898c7013afa3cc4fd544c69487970337eef8573cff480bc5697.immutable.js:20)
    at babylon.gui.min.16040689e4924898c7013afa3cc4fd544c69487970337eef8573cff480bc5697.immutable.js:84
    at babylon.gui.min.16040689e4924898c7013afa3cc4fd544c69487970337eef8573cff480bc5697.immutable.js:87
```

**Comment by kkimdev** [comment]
@RaananW

**Comment by kkimdev** [comment]
I guess this depends on how the worker version is provided with the new es6 refactorings...

**Comment by kkimdev** [comment]
Thanks!! :)

btw, should we keep this issue opened for regular module import usecase without a bundler?

**Comment by deltakosh** [comment]
I will close it because the 3.4 will fix the module issue
