### ISSUE TITLE
[Bug] A couple Highlight layer rendering bugs

### ISSUE THREAD

**Issue by fmmoret** [BabylonJS/Babylon.js#5238]
Not sure when this started happening -- but have seen it in at least a few of the last versions when I've tried to do things with highlight layers.

# Bugs

- Bug repro on [playground](https://www.babylonjs-playground.com/#U1HIF7):
- Expected result:
A red highlight around the sphere and a larger green highlight around the sphere.
Some additive effect: 
![two-highlight-bug-should](https://user-images.githubusercontent.com/5396858/45938442-ded3b100-bf7e-11e8-84d5-b040b146cf34.png)

- Current result:
We see a green highlight and then the whole sphere turns red.
![two-highlight-bug](https://user-images.githubusercontent.com/5396858/45938468-265a3d00-bf7f-11e8-96df-62db043f34d0.png)

- Bug repro on [playground](https://www.babylonjs-playground.com/#0V9H33)
- Expected result:
A red highlight around the sphere. -- should look like (see the advanced texture usage commented out):
![advanced-texture-bug-should](https://user-images.githubusercontent.com/5396858/45938381-40475000-bf7e-11e8-8260-6ac3f7859169.png)

- Current result: 
Whole sphere gets colored the highlight color if I use a BABYLON.GUI.AdvancedTexture.
![advanced-texture-bug](https://user-images.githubusercontent.com/5396858/45938386-4806f480-bf7e-11e8-880f-3455ddf5dd52.png)

**Comment by sebavan** [comment]
The first one is expected and was already existing in stable. The second one has been fixed by the previous commit.

**Comment by fmmoret** [comment]
@sebavan  Ah. The effect I'm trying to achieve is with different inner / outer glow settings and blur values

**Comment by fmmoret** [comment]
I'll try to tackle it some other way

**Comment by sebavan** [comment]
Oh I see, yes in this case, it is not supported by the effect layer.
