### ISSUE TITLE
There is something wrong with how the boundingBias is applied

### ISSUE THREAD

**Issue by barroij** [BabylonJS/Babylon.js#5245]
The `Geometry` class has a Vector2 `boundingBias` member.
If my understanding is correct, this is for enlarging the BoundingBox and BoundingSphere so that the picking can work even if the geometry has actually 0 extend in x or y (this is the case of horizontal lines or verticale lines), and even if it is not the case, it enables the picking when the ray gets close enough.

Although I am 100% ok with that Idea and its usefullness, It seems to me there is something wrong in how it is used to enlarge the BoundingBox :
- this extra "width" is applied to the local boundingBox
- then the local boundingBox is transformed according to the world matrix of the geometry to get the world bounding box
That means the extra width is also transformed, especially, it is SCALED, meaning that, in case of x1000 scaling,  the by default 0.1 bias becomes a bias of 100 .

I might be wrong but is sounds wrong to me. The bias is a value that seems to not be local, but expressed as a world bias. As a consequence, it should be added to the world BoundingBox only or, might better, not added to the bounding box at all, but taken as an extra paremeter to all the calculation done with the BoundingBox.

Everything that relies on the boundingBox ,or the boundingSphere can be missleaded by a scaled bias. In my current experimental development, I have external dirty data that I'm importing with very tiny chunk of geometry that are scaled by a factor 1.000.000 to get the correct size in the scene. So in that case, the bias is bigger than the geometry itself and the extra width after the tranformatoin by the workd matric is 200.000, wich is far bigger than the whole scene itself...

(As a temporay workaround, one can manually set the `intersectionThreshold` of the linesMesh to 0)

**Comment by deltakosh** [comment]
For performance reason I think we need to keep it added to the bounding box. But yeah, I agree this should be added as a world value and not a local value.

We are too close to the release (in a week) to do this change but we can prepare it for next week (after the release)

**Comment by deltakosh** [comment]
Fixed with the new BoundingInfo constructor where you can specify a wolrdMatrix
