### ISSUE TITLE
Create a package.json and update the version on npm

### ISSUE THREAD

**Issue by kevzettler** [BabylonJS/Babylon.js#526]
This is basically the same as #451 

There is currently a `babylonjs` package on npm.org
https://www.npmjs.com/package/babylonjs

Not sure if that is an official module or not. I'm currently using it in node and noticed it was missing some features from the documentation. It looks outdated.
The npm version is listed as `1.13.3` the source code says `"Version",{get:function(){return"1.13.0}"`

**Comment by deltakosh** [comment]
Yes @meulta is working on it:)

**Comment by meulta** [comment]
Yep should be ok this week :)

**Comment by deltakosh** [comment]
This is done!! thanks @meulta
