### ISSUE TITLE
Undo/Redo for Gizmos

### ISSUE THREAD

**Issue by dad72** [BabylonJS/Babylon.js#5260]
# Feature request

@TrevorDev Would it be possible to support in the Gizmos "Undo and Redo" to be able to cancel one or more displacement/rotation/scaling or to restore them.

Thank you in advance.

**Comment by deltakosh** [comment]
This is a complex ask. How would you like it to work?
Something like saveState() and restoreState()?

**Comment by dad72** [comment]
Yes it can be something like that. saveState () et restoreState () is good.

Save in an array (for example) each move / rotation / scaling when releasing the gizmo after the click => drag => drop (10 records can be enough or be able to set the number of save with a public member)

Then when we want to cancel or redo the transformations, retrieve them in the array that serves as a record.

Could this be suitable?

**Comment by TrevorDev** [comment]
You can add customized support for this in your app by using onDragStartObservable/onDragEndObservable exposed through the sub gizmos. See https://doc.babylonjs.com/how_to/gizmo . Every time an action is started, save the current state of the object and when you want to undo just revert back to that state.

**Comment by dad72** [comment]
Yes I know it, but I think it's also something that could be directly supported by Babylon's Gizmo system. (For Babylon 4.0)

But I know that it should not be so complicated to implement on my side, but if it is officially integrate, everyone would benefit.

**Comment by dad72** [comment]
@TrevorDev I found a bug with onDragStartObservable/onDragEndObservable : 

http://www.html5gamedevs.com/topic/40281-gizmo-ondragstartobservable-and-ondragendobservable-always-returns-the-same-values/

**Comment by TrevorDev** [comment]
I have some other tasks I'm working on at the moment but this could be useful. If you manage to get a good implementation that you think others could use feel free to make a PR.

**Comment by dad72** [comment]
I am not very comfortable to make PR so important. I'm not sure that my way of doing it is perfect.

**Comment by TrevorDev** [comment]
I can have this on my backlog but might not get to it for a while. I'm happy to help review any PR you make though.

**Comment by deltakosh** [comment]
Closing for now as this is not high priority and we have ways to do it
