### ISSUE TITLE
Rename npm packages with scoped names

### ISSUE THREAD

**Issue by yvele** [BabylonJS/Babylon.js#5270]
https://docs.npmjs.com/getting-started/scoped-packages

Instead of having https://www.npmjs.com/~babylonjs we can have scoped npm package names:

Examples of the scoped name change:

  - `babylonjs` -> `@babylonjs/core`
  - `babylonjs-inspector` -> `@babylonjs/inspector`
  - `babylonjs-materials` -> `@babylonjs/materials`
  - `babylonjs-loaders` -> `@babylonjs/loaders`

That will prove that all `@babylonjs` packages are official ones 😉 

More informations https://babeljs.io/blog/2017/12/27/nearing-the-7.0-release#renames-scoped-packages-babel-x

**Comment by deltakosh** [comment]
I'm afraid this will break all existing setup right?

**Comment by deltakosh** [comment]
I meant: We have a lot of users referencing the current packages so we are reluctant to change everything :)

**Comment by yvele** [comment]
I don't think so, everything went well for babel.

Nothing will break because existing published packages will not be removed..

The only thing to do for users to update babylons to the next version (scoped package names) is to rename babylonsjs packages in their`package.json`

**Comment by deltakosh** [comment]
This is what I meant. We will force all the users to do that. Not sure it is worth the pain

**Comment by yvele** [comment]
Okay.. I'm just exited about [the new modules feature](https://github.com/BabylonJS/Babylon.js/issues/3314).. and babylonjs looks more and more like a [mono repo](https://www.google.fr/search?q=mono+repo&oq=mono+repo) like many other projects.

I also like scoped package names because they are grouped in `npm_modules`

**Comment by deltakosh** [comment]
But for next release (4.0) we will ship new packages for each project to support ES6
so we could start using that for them

something like @babylonjs/core-es6, @babylonjs/gui-es6, etc...

**Comment by yvele** [comment]
This could represent an opportunity 👍

**Comment by yvele** [comment]
Are you sure to prefix new package names with `-es6`?

New scoped package names can be modules by default.

By the way the term `es6` (`es7`, etc..) is not really appropriate nowadays. I think it's more about modules than esx

**Comment by deltakosh** [comment]
So something like @babylonjs/core-modules ?

**Comment by yvele** [comment]
I don't understand the suffix.. Modules are that new default anyway 🤔 Why not `@babylonjs/core`?

By the way I think the exact term is **module** (or sometimes ES modules)
 - https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import
 - https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/export

**Comment by deltakosh** [comment]
I want to make sure we see a difference with the previous packages (the one that will stay unchanged)

**Comment by deltakosh** [comment]
To be fair, I like the @babylonjs/core, @babylonjs/gui, @babylonjs/materials naming

Simple, easy and we can consider that what is not in the scope is not using modules..

**Comment by yvele** [comment]
The new packages will be scoped `@babylonjs/core` and the old ones unscoped `babylonjs`

I'm not sure adding a specific technical JavaScript feature as a package name suffix is a good idea 🤔 

It's looks to me like people prefixing/suffixing variable names with types `const fooString = "FOO";`

**Comment by deltakosh** [comment]
Well ok I guess you are right :) So new ones will be @babylons/xxxx only

**Comment by yvele** [comment]
Good, I think (JavaScript) module are the new standard anyway 👍

**Comment by yvele** [comment]
Also scoped package names will allow you to more easily manage npm permissions for collaborators 👍

**Comment by tommhuth** [comment]
This is an extremely good idea. 🎉 👍 

It should also make it easy to split out more stuff, so that people don't end up with two physics engines for example, and lots of stuff they aren't using. There's alot of good stuff in Babylon, but i bet most people aren't using everything. This should make the end bundle for people much more focused and smaller. 

I also agree that the ES6 prefix is unnecessary, it is perfectly fine to assume ES6 modules by default for this (also prefixing like that is not commonplace in NPM land as far as I know)

**Comment by sebavan** [comment]
Shipped : https://doc.babylonjs.com/features/npm_support#es6
