### ISSUE TITLE
How to fix bundling with rollup ?

### ISSUE THREAD

**Issue by Tomekmularczyk** [BabylonJS/Babylon.js#5299]
This is related to #4391 - to fix rollup issue when named importing from babylonjs I have to change:
```
import { ArcRotateCamera, Engine, SceneLoader, Vector3 } from "babylonjs";
```
to:
```
import { ArcRotateCamera, Engine, SceneLoader, Vector3 } from "babylonjs/es6";
```

But this is breaking typescript checking. I've asked a very similar question on [StackOverflow](https://stackoverflow.com/questions/52641925/use-types-from-one-module-for-another)

Typings are not the only problem. When I import built package in another project and try to use it I get that CANNON is undefined:

![image](https://user-images.githubusercontent.com/12544704/46469831-daa46080-c7d4-11e8-9ed5-0a43531a624e.png)

Here's the repo I'm working on:
https://github.com/Tomekmularczyk/react-package-rollup/tree/babylon-typescript-example

**Comment by deltakosh** [comment]
We are a few weeks away from shipping the first real es6 port of Babylon.js.
We will have a dedicated package that will fix all these issues
Closing for now. You can track changes on #4892
