### ISSUE TITLE
Compile fails in Angular 6 app

### ISSUE THREAD

**Issue by ganlhi** [BabylonJS/Babylon.js#5308]
When using BabylonJS with an Angular 6 app, generated with the Angular CLI, compile fails with the following error:

```
ERROR in node_modules/babylonjs/babylon.d.ts(6444,5): error TS2717: Subsequent property declarations must have the same type.  Property 'leftBounds' must be of type 'number[]', but here has type 'Float32Array | number[]'.
node_modules/babylonjs/babylon.d.ts(6445,5): error TS2717: Subsequent property declarations must have the same type.  Property 'rightBounds' must be of type 'number[]', but here has type 'Float32Array | number[]'.
```
This occurs with version 3.3.0 and with previews down to beta 1. Alpha 15 works correctly.

**Comment by deltakosh** [comment]
This is because you have to use TypeScript 3.0 instead of 2.x

**Comment by ganlhi** [comment]
Actually I cannot because Angular is still not compatible with it. 
The weird thing is if I downgrade to TypeScript 2.7.2 it works!

**Comment by ganlhi** [comment]
Even without including Angular in the mix, let's say I have the following `index.ts` file:

```typescript
import {Vector3} from 'babylonjs';
console.log(Vector3.Zero);
```

With the following `package.json`:

```json
{
  "name": "test-babylon",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "build": "tsc"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "babylonjs": "3.3.0",
    "typescript": "2.7.2"
  }
}
```
Running `npm install && npm run build` works in this case, doesn't work when setting TypeScript version to 2.9.2 and works again with 3.0.1.

**Comment by deltakosh** [comment]
This is a pity that EACH version of Typescript introduces breaking changes :(
