### ISSUE TITLE
3dsmax export : Uncaught TypeError: Cannot read property 'prepare' of undefined babylon.js:11 

### ISSUE THREAD

**Issue by kevzettler** [BabylonJS/Babylon.js#531]
I have a model that i'm trying to export to babylon. I have 2 machines. one is `Win7+3dsmax2013` and one is `Win8+3dsmax2015`. I can successfully export to babylon on the `Win7+2013` machine. I just started using the `Win8+2015` machine because I was seeing some issues, not related to babylon with the animation rendering on 2013. I can export to babylon on the `Win8+2015` setup It will play a bit of the animation and then crash.

![screenshot 2015-05-26 19 10 09](https://cloud.githubusercontent.com/assets/126209/7827336/e3ff28b6-03da-11e5-8dc4-4010b763beef.png)

you can check out the 3ds source file here:
https://www.dropbox.com/s/vnofp4iip5y1w1t/kz_2011.max?dl=0

The crashing babylon export and assets are here:
https://www.dropbox.com/sh/4lzsfooopy3kx8c/AAB4kdiZJokN5eNgMbMG-22Sa?dl=0

I hope we could at least get some better error handling around the exception.

**Comment by deltakosh** [comment]
Hello using your crashing assets I have no problem with the sandbox (by drag'n dropping all files on it). Do you reproduce on the sandbox?

**Comment by kevzettler** [comment]
@deltakosh 

It does seem to render okay on the sandbox by dragging and dropping but it also throws a differnt error there:

![screenshot 2015-05-29 04 18 59](https://cloud.githubusercontent.com/assets/126209/7881645/f6131f72-05b9-11e5-815a-36fa189ed894.png)

**Comment by deltakosh** [comment]
That's not unexpected as the sandbox may have not found a invalid file
