### ISSUE TITLE
Create a skinnable version of the Slider

### ISSUE THREAD

**Issue by Nodragem** [BabylonJS/Babylon.js#5316]
Once we covered the TextureAtlas #5314  and 9-Patches #5315 issues, we should have all the tools to make BabylonJS customizable with Textures (i.e. skinnable)!

For now, only buttons can have an image/texture.
I will try to detail the TODO list of the controllers that needs a skin if you think this issue is worth investigating.
We may also need the buttons to have a Default/Hovered/Clicked/Deactivated image.

I am a bit afraid that it is a lot of work. Would we keep an unskinnable and skinnable version of each Controller? (is there any benefits performance-wise to do so?)

**Comment by deltakosh** [comment]
The other two are OK to implement. This one needs more thinking
We could for instance expose the render function  so everything could stay and you would just need to implement the render part

**Comment by deltakosh** [comment]
something like control.customDraw = function(){} so each use could provide its own rendering function

**Comment by Nodragem** [comment]
I would like to keep things simple for the user. Implementing a render function sounds complicated to me as a user.

Ideally the user would simply write something like that:

```javascript
BABYLON.GUI.createCustomizedButton("./button_default.png", "./button_hovered.png", 
"./button_clicked.png", "./button_disabled.png").

BABYLON.GUI.createCustomizedSlider("./slider_default.png", "./slider_filling.png", 
"./slider_thumb.png").
```

**Comment by deltakosh** [comment]
So perhaps it could be better to have an ImageBasedSlider for instance
Still unclear how to render the bar then. I can see how to render the background and the thumb from an image but the bar is still unclear

**Comment by Nodragem** [comment]
I was thinking: as a slider is like a progress bar with a thumb; it might be useful to hide the thumb.

I can think of two ways to make the progress/value bar:
- a trick similar to as a ninepatch
- a full bar which you mask with a rectangle or custom shape

**Comment by deltakosh** [comment]
Hiding the thumb could just be a boolean
So here is my take, let me know what you think about:
- Add a new class named ImageBasedSlider inheriting from Slider with
  - backgroundImage
  - thumbImage
  - progressBarImage
- update Slider to add a displayThumb boolean

**Comment by Nodragem** [comment]
Sounds like a good plan!

Should we have a ninepatch that stretches in the dimension of the slider for the backgroundImage/valueBarImage? so that we can make sliders of any size with a minimal use of memory (i.e. image size)?

In term of name, I would rather go for valueBarImage instead of progressBarImage, as it makes sense for both sliders and progress bars.

For the name of the class, I don't know what is best but ImageBasedSlider sounds like a good description of what it is.

**Comment by deltakosh** [comment]
Yes the images could all be NinePatchImage.. That makes sense

**Comment by deltakosh** [comment]
I'll give a try asap

**Comment by deltakosh** [comment]
Ok first version checked in
https://github.com/BabylonJS/Babylon.js/blob/master/gui/src/2D/controls/imageBasedSlider.ts

**Comment by deltakosh** [comment]
Sample: https://www.babylonjs-playground.com/#97I72I (it will be better with NinePatchImages)

**Comment by Nodragem** [comment]
Excellent!

I made this simple slider texture for the demo:
[slider-demo.zip](https://github.com/BabylonJS/Babylon.js/files/2475311/slider-demo.zip)

Should looks like that once put together:
![image](https://user-images.githubusercontent.com/10520249/46904022-b7189e80-ced5-11e8-8e46-843aa42ec20a.png)

That's not super great, but it looks a bit more modern. I can improve it if you are some feedback.

**Comment by deltakosh** [comment]
This is fine. We now need to support NinePatch to improve the demo :)

**Comment by deltakosh** [comment]
Done: https://www.babylonjs-playground.com/#HATGQZ

**Comment by deltakosh** [comment]
Ok cool! I'll update the files

Also I will need the same but with the additional line for ninepatch to do my tests :)
