### ISSUE TITLE
[Feature Request] Cross eye 3d rendering

### ISSUE THREAD

**Issue by kkimdev** [BabylonJS/Babylon.js#5319]
One time I saw a game that supports cross eye 3D rendering option, and was pretty fun! (Though I forgot which game it was)

- https://www.youtube.com/watch?v=zBa-bCxsZDk
- https://www.reddit.com/r/CrossView/

Not an important feature but I just wanted to share an idea.  Please feel free to close.  Thanks!

**Comment by deltakosh** [comment]
Haha fun Ide. I would recommend to share it on the forum.
Closing for now as this is not planned(but can be achieved as an extension definitely)
