### ISSUE TITLE
scene.getWorldExtends() should probably be called scene.getWorldExtents()

### ISSUE THREAD

**Issue by AlexMuir** [BabylonJS/Babylon.js#5320]
I think this is a minor language issue really, and it's not very important.  But correct English would probably be getWorldExtents() as it returns the extents of the world.

**Comment by deltakosh** [comment]
Yeah I know (now) but as we value backward compatibility we cannot rename it or it will break a lot of playgrounds and user code :(

**Comment by AlexMuir** [comment]
I completely understand.  The main thing is that it works perfectly!  BTW I'm deep into a project and BabylonJS is satisfying me on every level!

**Comment by deltakosh** [comment]
Thank you so much for this feedback:)

**Comment by AlexMuir** [comment]
I'll write about this project when I get time.  But I've completely rewritten the same codebase using Blend4Web, Verge3D, ThreeJS and finally (I hope) BabylonJS.  So far I haven't found a feature that is missing, and I have it integrated beautifully with ReactJS.

**Comment by deltakosh** [comment]
I would love to read about that🙏
