### ISSUE TITLE
Forum sign-up process

### ISSUE THREAD

**Issue by n9** [BabylonJS/Babylon.js#5325]
(This issue is about the Babylon.js forum. I have not found its issue tracker. Since it's your official forum, I am posting issue here.)

I was trying to ask a question regarding Babylon.js. I have found that Babylon.js uses its forum for that. In order to ask there, I wanted to register there. I have realized that it is sending password in an unencrypted form. Could you please force Photon Storm (seems like the owner of that forum) to switch at least forum sign-up to https. Add forum host to their certificate or use Let's Encrypt. (Looks like you are the major user.)

**Comment by Vinc3r** [comment]
Agree with that, maybe try to post something here ? http://www.html5gamedevs.com/forum/12-general-talk/

**Comment by deltakosh** [comment]
Good point but not the right place for that:)
I agree with you and with Vinc3r. This is also a flaws for phaser users so the best place is the forum itself

**Comment by Vinc3r** [comment]
FYI, I've made a topic up: http://www.html5gamedevs.com/topic/38433-this-forum-is-not-https/
