### ISSUE TITLE
Terrible mirror performance on 3.3.0

### ISSUE THREAD

**Issue by fsmorygo** [BabylonJS/Babylon.js#5330]
- Bug repro on [playground](http://playground.babylonjs.com/indexStable.html#JWCKRK):
- Expected result: 60 fps
- Current result: fps starts to decrease pretty fast to 0

**Comment by deltakosh** [comment]
I do not repro, it renders at 60fps here

**Comment by deltakosh** [comment]
Ok I can now
Thanks a lot for finding it! I'll fix that ASAP (for 4.0)

**Comment by fsmorygo** [comment]
Yes i guess the renderList leaks, it just behaves so. I wish I reported this on -beta or -rc stage of 3.3.

By the way is it planned to have a predicate in reflection probe? Deferring creation of mirrors/probes until the scene filling is finished does not look comfortable.

**Comment by deltakosh** [comment]
You can also add to the renderList when you want. YOu can start with an empty array and add to it while objects load

**Comment by fsmorygo** [comment]
Ok thanks. I will go along with the workaround. Are there any time estimates on 4.0 release? It looks like a big work is to de done for it.

**Comment by deltakosh** [comment]
Yep:) but you can already grab the preview bits: https://www.npmjs.com/package/babylonjs/v/4.0.0-alpha.2
