### ISSUE TITLE
Textures not showing

### ISSUE THREAD

**Issue by madika** [BabylonJS/Babylon.js#5333]
I'm loading an object with the SceneLoader.ImportMesh, but it does not show the texture.
I see the texture loading in Chrome dev tools but they dont show up in the scene.
![image](https://user-images.githubusercontent.com/16919435/46672171-052c5a00-cbd7-11e8-9176-28ec82e7282d.png)

- Bug repro on playground: http://www.babylonjs-playground.com/#12WBC#257
- Expected result:
A white box with the purple ground inside the box
![image](https://user-images.githubusercontent.com/16919435/46672048-bb437400-cbd6-11e8-8da9-f5e45cb4ab93.png)

- Current result:
Just a white box
![image](https://user-images.githubusercontent.com/16919435/46672078-cf877100-cbd6-11e8-9704-360bc3e7de96.png)

**Comment by deltakosh** [comment]
The texture on your server is almost fully white:
![image](https://user-images.githubusercontent.com/1306056/46680489-1311b900-cb9e-11e8-895c-0a2b1813a0a2.png)

**Comment by deltakosh** [comment]
And it seems to be correctly loaded:
![image](https://user-images.githubusercontent.com/1306056/46680547-32104b00-cb9e-11e8-95c0-21cc920da2a7.png)

**Comment by madika** [comment]
Thank you a lot for your response.

The .mtl consists of 3 materials:
https://raw.githubusercontent.com/madika/babylon-test/2b867c0fd20217c7a907ebffed1e686dc7b97aee/01310-020.obj.mtl

Texture/01310-020-Boden.png, Texture/madika.png and Texture/01310-020-Deckel.png

I just did some testing and replaced another material ([playground](http://www.babylonjs-playground.com/#12WBC#260)) and it seems to load the texture now, but it applies only one material (the last?) to everything. Is there some sort of restriction or some setting I need to set for every texture to be applied (I see all 3 materials loading in Chrome console) ?

**Comment by deltakosh** [comment]
Let me ping @kcoley who will be able to check the problem

**Comment by kcoley** [comment]
Hi @madika I'll take a look

**Comment by kcoley** [comment]
@madika sorry for the delay.  Looking at your obj file, it looks like you are assigning per-face materials in your obj file which Babylon.js does not support.  You can either pack all your textures into one and use texture coordinates to map to your mesh, or you can split your mesh into multiple meshes and assign materials to each mesh.  Let me know if this makes sense.

**Comment by madika** [comment]
> @madika sorry for the delay. Looking at your obj file, it looks like you are assigning per-face materials in your obj file which Babylon.js does not support. You can either pack all your textures into one and use texture coordinates to map to your mesh, or you can split your mesh into multiple meshes and assign materials to each mesh. Let me know if this makes sense.

Thank you, I will give it a try.
