### ISSUE TITLE
add a fixed ratio option to GUI image/buttons

### ISSUE THREAD

**Issue by Nodragem** [BabylonJS/Babylon.js#5336]
# About the issue we want to solve

I would like to never use pixels to size my buttons/images. 
Using proportion sounds much better as everything resizes based on the device screen size. 

However, currently, if the container of a button/image has a width greater than its height, then if you set "button.height=0.2; button.width=0.2", the button will appear elliptic and squashed on Y-axis. Indeed the button will follow the proportion of the container!

# Feature request
My feature request is to add an option "controller.fixedRatio = 1", so that when you set "button.height=0.2", the width is computed automatically so that the button keeps its original ratio.

In practice, control.fixedRatio could be set to any number and is defined as Horizontal/Vertical, e.g. 16/9, 4/3, etc. A control.fixedRatio = 0 would free the ratio. When width and height are both defined by the user, the last to be defined wins.

- Link to [forum](http://www.html5gamedevs.com/topic/40142-can-we-customize-the-look-of-babylonjsgui/?page=2)

**Comment by Nodragem** [comment]
@deltakosh hello, just a quick comment to say that I didn't seem to be able to create an empty PR, so I created this issue to discuss where I should start. I guess I need to add the option to the Image class of BABYLON.GUI?

**Comment by deltakosh** [comment]
This should be a control wide property and we can specialize it for image where the ratio is by default set by the image

**Comment by Nodragem** [comment]
I can have a look.

**Comment by Nodragem** [comment]
Just to let you know that I had some technical issues (I had to re-install windows 10), so I did get to do anything yet. Going to have a look tomorrow :)

**Comment by deltakosh** [comment]
up?

**Comment by Nodragem** [comment]
did not have time since I am still working on a contracted project with babylonjs at the moment :/
