### ISSUE TITLE
Child lights are not removed from scene on `removeMesh(mesh, true)`

### ISSUE THREAD

**Issue by fsmorygo** [BabylonJS/Babylon.js#5339]
- Bug repro on [playground](http://playground.babylonjs.com/#RX7C9C):
- Expected result: Red light is gone with its holder
- Current result: The light stays where it were

**Comment by deltakosh** [comment]
Hello,

This is the expected behavior: http://doc.babylonjs.com/api/classes/babylon.scene#removemesh
The "recursive" parameter indicates that all child meshes should be removed
