### ISSUE TITLE
DynamicTexture having problems in Chrome

### ISSUE THREAD

**Issue by rcz0001** [BabylonJS/Babylon.js#5351]
Large DynamicTexture objects (50 million pixels or greater in size) will not render in the newest version of Google Chrome (69.0), but work fine in Microsoft Edge and Firefox, as well as previous versions of Chrome. 

`

var createScene = function () {

    // This creates a basic Babylon Scene object (non-mesh)
    var scene = new BABYLON.Scene(engine);

    // This creates and positions a free camera (non-mesh)
    var camera = new BABYLON.FreeCamera("camera1", new BABYLON.Vector3(0, 5, -10), scene);

    // This targets the camera to scene origin
    camera.setTarget(BABYLON.Vector3.Zero());

    // This attaches the camera to the canvas
    camera.attachControl(canvas, true);

    // This creates a light, aiming 0,1,0 - to the sky (non-mesh)
    var light = new BABYLON.HemisphericLight("light1", new BABYLON.Vector3(0, 1, 0), scene);

    // Default intensity is 1. Let's dim the light a small amount
    light.intensity = 0.7;

    // Our built-in 'ground' shape. Params: name, width, depth, subdivs, scene
    var ground = BABYLON.Mesh.CreateGround("ground1", 6, 6, 2, scene);
    var groundMat = new BABYLON.StandardMaterial("mat", scene);
    var groundTex = new BABYLON.DynamicTexture("tex", {width: 8000, height: 8000}, scene);
    ground.material = groundMat;
    groundMat.diffuseTexture = groundTex;
    var ctx = groundTex.getContext();
    ctx.fillStyle = "blue";
    ctx.fillRect(0, 0, 8000, 8000);
    groundTex.update();

    return scene;

};

`
When the code above is run in Edge or Firefox, it shows a blue plane, but on Chrome 69.0, the plane is black (meaning that the DynamicTexture object failed to load).

**Comment by aWeirdo** [comment]
Can confirm for Chrome 69.0.3497.100
Same results on both 3.3.0 & 4.0.0

It works on initial load for me,
but > re-run & the texture is black, 
wait a few secs > re-run & it works again..
another re-run and it's black again.

**Comment by deltakosh** [comment]
This is a bug for Chrome db.

**Comment by deltakosh** [comment]
Cannot repro on Version 70.0.3538.54
Cannot repro on Version 71.0.3577.0 (Official Build) canary (64-bit)

PG to test: https://www.babylonjs-playground.com/#Z1YU31

**Comment by deltakosh** [comment]
Clsoing for now as this is a no repro
