### ISSUE TITLE
The onPointerUp event of GUI.Button triggers only while moving the pointer

### ISSUE THREAD

**Issue by AdrianSima** [BabylonJS/Babylon.js#5356]
- **Playground:** https://www.babylonjs-playground.com/#XCPP9Y#653
- **Expected result:** I am expecting the button to change its color every time I click it.
- **Current result:** Currently the pointer up event triggers only if you are moving the cursor when you release the button.

Using **Babylon.js v4.0.0-alpha.2 - WebGL2**

I tested this in **Chrome Version 69.0.3497.100 (Official Build) (64-bit)** and **Microsoft Edge 42.17134.1.0**.
Windows 10 v1803
with mouse

On Android/touch seems to work fine.

**Comment by deltakosh** [comment]
it is actually fixed but not yet deployed...Should be good in a couple of minutes (do not forget to clear your browser cache)
