### ISSUE TITLE
Could we access position, rotation and scale from Node?

### ISSUE THREAD

**Issue by Nodragem** [BabylonJS/Babylon.js#5363]
Hello,

I want to write a Shader helper where the user could give the name of a node (e.g. from a Light, Camera, Mesh, or TransformNode), and I would add a Vector3 for the position of that node in the shader. 

However, when I use the function scene.findNodeByName(), then I couldn't access the position of the Node; I realised that position, rotation and scale are not accessible from Node.

It looks like that Camera, Light, Mesh and TransformNode all have a position, rotation and sometime a scale. Is there a specific reason for not making them accessible from the Node abstraction level?

**Comment by julien-moreau** [comment]
I think because all nodes don’t have these properties. Typically a light doesn’t have a scale, same for camera etc.

**Comment by Nodragem** [comment]
I did say "[They have] sometimes a scale".
But already the ability to access the properties _rotation_ and _position_ from any node would be nice.

Although maybe it's already possible to access them? For instance, I was wondering, how do Animations access the properties of their targets?

**Comment by julien-moreau** [comment]
My bad I missed the « sometimes » ^^
Are you sure that hemispheric light has a rotation ?

**Comment by deltakosh** [comment]
This is a question for the forum. The repo must only be used for bug and features.

If you are in TS, just cast the node: (<TransformNode>node). position 

In js, just call node.position :)

**Comment by Nodragem** [comment]
Thanks for your response :)

Sorry, I thought of it as a feature request as I was requesting the ability to access position and rotation of a Node without knowing what the Node is.

If I need to cast the Node to Camera, that means I need to know that the node is a camera. I just thought that it could be nice to be able to access the position of objects, without knowing too much of what they are.
And I thought Node might be the good level of abstraction for it.

**Comment by Nodragem** [comment]
... yeah; that's a shame. I got that idea because in Blender or Unity, cameras, lights, emptys and meshes all hold a position and a rotation (and even a scale, I think)...

For instance, a directional light does not need a position for its light to be rendered. However, as Blender is a visual editor, directional light still holds a position, because it is important for the user to be able to put the light somewhere that is easy to reach and not in the way.

Now, in the case of BabylonJS, that does not make much sense. So I guess I will just have to test if the object I am given holds a position :D 

Thank you for your feedback anyway @julien-moreau  and @deltakosh
