### ISSUE TITLE
Consider publishing glTF typings on DefinitelyTyped

### ISSUE THREAD

**Issue by donmccurdy** [BabylonJS/Babylon.js#5370]
I noticed that you're publishing types for the glTF schema on npm as "babylonjs-gltf2interface". If that's something you're (1) comfortable maintaining, and (2) planning to keep up-to-date with the glTF official schema, would you consider publishing it on https://github.com/DefinitelyTyped/DefinitelyTyped, without the peer dependency on BabylonJS? Similar to [@types/geojson](https://www.npmjs.com/package/@types/geojson).

Several other TS typings for glTF have also appeared:

- https://www.npmjs.com/package/gltf-typescript-generator
- https://github.com/wnayes/glTF-js-utils/blob/master/src/gltftypes.ts

I'm not entirely happy with either of those, and have considered generating my own... If you're comfortable publishing the BabylonJS glTF typings for broader use, that would probably be better to ensure TS tools are more consistent. :)

**Comment by donmccurdy** [comment]
Not sure about extensions — bundling the KHR_ ones might be nice, but also not necessary if it's more trouble. Separating or omitting glTF-Validator does seem preferable, I agree.

**Comment by bghgary** [comment]
I have a work item to move the extension interfaces to a shared location. I would have put it in this module, but if we want to put it in DefinitelyTyped, then it should probably be split off.

**Comment by donmccurdy** [comment]
I only need the core schema, having that in DefinitelyTyped seems like a great starting point to see how it gets used. Thanks! Let me know if you want help with this.

**Comment by bghgary** [comment]
I've never added anything to DefinitelyTyped. We are also in the middle of moving to modules. If you want, it would be great if you can take the typings from Babylon and submit it. We can switch to the typings and continue maintaining it after we complete the modules move.

**Comment by donmccurdy** [comment]
Sounds good. Opened https://github.com/DefinitelyTyped/DefinitelyTyped/pull/29801.

**Comment by sbtron** [comment]
closing this as a separate one was opened up on.
