### ISSUE TITLE
Ability to Paste into InputText Control

### ISSUE THREAD

**Issue by BabylonJSGuide** [BabylonJS/Babylon.js#5378]
# Feature request

http://www.html5gamedevs.com/topic/40661-gui-input-text-behavior/

Use of CTRL + V to paste into inputText control

Useful Site (?) https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Interact_with_the_clipboard

**Comment by deltakosh** [comment]
THanks sir ;)

**Comment by ssaket** [comment]
Hi @deltakosh and @BabylonJSGuide  
please assign this to me :) 

-Thanks

**Comment by ssaket** [comment]
After spending a productive day, this is the **first prototype** that I have come up with  💯<br/>

![ice_video_20181020235620](https://user-images.githubusercontent.com/27828189/47259290-f8581200-d4c4-11e8-9cb5-9e185e9771bd.gif)

**Comment by ssaket** [comment]
It supports copy, paste, cut events (above)

**Comment by ssaket** [comment]
I have few doubts on system design, as a newbie its hard for me to figure out what's the best place to
define a new function, class etc. This is what I have done -

1. Created a new event class in Events called ClipboardEvents(just like Pointer/Keyboard )
2. Coming to the event listeners, my first thought was to define them in DynamicTexture (because AdvanceDynamicTexture inherits it,
 and has preKeyBoardObservable which basically listens to all events and from which I can later call my corresponding subclass.. blah blah blah.. )
    - Soon after, I realised its not a good idea as DynamicTexture basically deals with texture related things and also it is part of core module (I thought its best not to define clipboard events here and ActionManager's code is really complex! Phew!! ).
    - So, I decided to put them in GUI/controls (only events actions, registration happens in AdvanceDynamicTexture) (please correct me if it shouldn't)

One major impediment- 
  The typescript version which we are using doesn't support navigator.clipboard or 
  creation of custom ClipboardEvent( the constructor doesn't let us use clipboardData while init
  [reference](https://github.com/Microsoft/TypeScript/blob/72244c5b03ec13a77088c4b2f016708007655ce0/lib/lib.dom.d.ts#L3132) ) because of this I had to take the long route (I kinda mutated them; possible area of improvement)
Happy to discuss this further :)

**Comment by deltakosh** [comment]
This is fantastic :)
Can you create a PR so we can discuss over it

**Comment by ssaket** [comment]
Thanks, Sure !

**Comment by ssaket** [comment]
@deltakosh - while working on this I found a cool feature 🏷 
Let's say on a PG, I found a golden sphere, which caught my interest 😍 then I decide to copy(ctr-c) this mesh (sphere) to my clipboard and then place it into some other/different scene using (ctr-v)

In short -
Allow copy-pasting of meshes, or also generate a .babylon file using copy (ctr-c)

I think this will help the users to do fast prototyping by having a databank of files(.babylon) of their favourite meshes. Also, if I an drop (.babylon) files onto scene using (ctr-v) What do you think ? also adding @BabylonJSGuide

**Comment by ssaket** [comment]
Fair enough.. but I still would add them in snippets 😃  after I solve my re-triangulation problem
<br/><br/><br/>



Note* This patch can help only in copy and pasting within the ADT, users won't be able to use navigator's clipboard (); reasons: 
1. https://github.com/Microsoft/TypeScript/issues/26728
2. document.execCommand("paste") is not supported in major browsers including mine.

**Comment by ssaket** [comment]
I have realised how silly my idea was !! :speak_no_evil: This can be done in 5 line outside the framework, using -
```
document.addEventListener("copy", (evt) => {
         let scene = this.scene;
         scene.pick(.....) //get the mesh
         let smesh = BABYLON.SceneSerializer.SerializeMesh(mesh);
          evt.clipboardData.setData("application/json", smesh )
}, false)
```
#feelingEmbarrassed

**Comment by deltakosh** [comment]
No worry:)

**Comment by deltakosh** [comment]
Would be ok to create a doc for it? Thanks a lot (with sanples in the playground)

**Comment by ssaket** [comment]
Yeah ! Already created a PR - https://github.com/BabylonJS/Documentation/pull/1309

**Comment by deltakosh** [comment]
You rock

**Comment by gernot-nu-IT** [comment]
is there a chance to get a method or property to select the text of the inputText if focused by default?

**Comment by ssaket** [comment]
@gernot-nu-IT not as of now, you have to manually add this in onFocusObservable; example- https://www.babylonjs-playground.com/#UWS0TS#22

Now that you have pointed it out, I think it makes sense to have a boolean property like onFocusSelectAll on input text which would allow this.

**Comment by gernot-nu-IT** [comment]
@ssaket yes, I think it would be quite useful. also, if text is highlighted (like in your playground example) and you start typing, the highlighted text should be replaced.

**Comment by deltakosh** [comment]
Agree!

**Comment by deltakosh** [comment]
Done!

**Comment by prithviMP** [comment]
is there an eventlistner for copy paste as i want to control how this are copied in the inputText
