### ISSUE TITLE
Use of Forward Slash / in Firefox for InputText Control Opens FF Quick Find

### ISSUE THREAD

**Issue by BabylonJSGuide** [BabylonJS/Babylon.js#5380]
# Bugs

As can be seen using https://www.babylonjs-playground.com/indexStable.html#UWS0TS

when using Firefox to write / into an inputText control
Instead of the expected result of / being entered;
the current result is that in addition the FF quick find box is opened and this receives focus.

Turns out that same is true for a single quote ' (keycode 222)

Problem is know about for FF https://support.mozilla.org/en-US/questions/1232389#answer-1150671

**Comment by deltakosh** [comment]
Well this seems a Firefox bug more than a Babylon.js one no?

**Comment by BabylonJSGuide** [comment]
Agree, just hoped someone cleverer than me could see a solution other than adding an extension to FF. I think FF users like me are going to have to live with it. Probably if we get the paste into working it will make life easier.

**Comment by deltakosh** [comment]
We will add the ctrlV for sure..
can you try to see if the keyup or keydown events are raised when you hit this key?
And if yes, can you set evt.handled = true?

**Comment by BabylonJSGuide** [comment]
Not sure if this is the way to test but added this code
```
document.addEventListener('keyup', (evt) => {
	evt.handled = true;
        console.log(e.code, e.key);
});
```

to my script, using keyup, keydown and keypress with and without the evt.handeld = true in all cases using FF quick find was opened.

**Comment by deltakosh** [comment]
Apparently, @TrevorDev found that using evt.preventDefault() fixes the problem
See #5382
