### ISSUE TITLE
GodRays from shader material

### ISSUE THREAD

**Issue by PixelsCommander** [BabylonJS/Babylon.js#5384]
We have an animated shader material representing illuminating background. Then this background we d like to apply god rays. Feels like shader material should produce texture at some level so should be possible but not sure how this is better to approach.

Any hints on implementation?

Our animated shader background:
<img width="973" alt="screen shot 2018-10-18 at 2 38 57 pm" src="https://user-images.githubusercontent.com/810671/47154821-a99f5200-d2e3-11e8-94fc-5046f5137791.png">

How we would like it to behave:
<img width="513" alt="screen shot 2018-10-18 at 2 37 21 pm" src="https://user-images.githubusercontent.com/810671/47154844-bae85e80-d2e3-11e8-813d-872611143af9.png">

**Comment by deltakosh** [comment]
Hello! This is a question for the forum ;)

**Comment by PixelsCommander** [comment]
Oh, sorry =)
