### ISSUE TITLE
Picking code broken with Yeti model

### ISSUE THREAD

**Issue by bghgary** [BabylonJS/Babylon.js#5386]
**Bug repro**
https://www.babylonjs-playground.com/index.html#RQ2T0A#8

**Expected result**
Console log reports there are picked results

**Current result**
Console log reports the picked results array is empty

**Comment by Tomekmularczyk** [comment]
I've experienced a very similar issue with this [model](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/Monster/glTF) (haven't tried others). The picking always returns an empty array besides some very specific places on the feet of the Monster.

**Comment by deltakosh** [comment]
It is linked to the model being the wrong one?

**Comment by deltakosh** [comment]
So this is not a bug. The bones are animating the mesh on the GPU but the CPU cannot see that.
So CPU only work on the rest pose of the mesh which looks like that:
![image](https://user-images.githubusercontent.com/1306056/47187416-dace5100-d2e8-11e8-9349-968aa4e779e9.png)
