### ISSUE TITLE
Mesh.convertToFlatShadedMesh() does not work for meshes created with MeshBuilder.CreateGroundFromHeightMap()

### ISSUE THREAD

**Issue by jhadenfeldt** [BabylonJS/Babylon.js#5389]
**What is the issue?**
`Mesh.convertToFlatShadedMesh()` fails for meshes created from a height map. 

**Demo**
https://www.babylonjs-playground.com/#PC6VGP (see line 22)

**Further info**
The error (`Cannot read property 'slice' of undefined`) happens in this line:
https://github.com/BabylonJS/Babylon.js/blob/cf786fdc032aee556e31907bf742572cbd41f8e0/src/Mesh/babylon.mesh.ts#L2215
The problem seems to be that `subMeshes` doesn't exist for ground meshes.

**Comment by deltakosh** [comment]
Not a bug. The CreateGroundFromHeighMap is acyn as it needs to load the image first. You can use the onReady callback for that:
https://www.babylonjs-playground.com/#PC6VGP#1

On a general note, please use the forum as we keep the repo for validated bug only :)

Thanks a lot!
