### ISSUE TITLE
Add onAnimationLoop / onAnimationLoopObservable

### ISSUE THREAD

**Issue by Nodragem** [BabylonJS/Babylon.js#5393]
Hello,

The onAnimationEnd and onAnimationEndObservable are not called at the end of every loop, which is a good thing in order to trigger something at the end of an animation.

However, it might be useful to be able to trigger an event each time a loop ends (e.g. changing the color of an object that moves left and right).

Note that this could also enable the possibility of running a specific number of loops :)

What do you think?

**Comment by deltakosh** [comment]
Great idea!
