### ISSUE TITLE
CSG.toMesh() -> rotationQuaternion.copyFrom (copyFrom of undefined)

### ISSUE THREAD

**Issue by KevinBLT** [BabylonJS/Babylon.js#542]
Hi there,

as we spoke about in Babylon forum four days ago, the rotationQuaternion wasn't copied from
the source mesh to the result mesh of CSG.toMesh.

In my project, I included the actual Babylon Beta from babylonjs.com.
Now, reopening my project, it throws an error: 
"Uncaught TypeError: Cannot read property 'copyFrom' of undefined"
when calling "CSG.toMesh".
It tries to call "n.rotationQuaternion.CopyFrom()" whereas rotationQuaternion is undefined.

The forum post we talked about:
http://www.html5gamedevs.com/topic/14362-illumination-of-merged-and-then-instanced-mesh/

Thanks,

Kevin

**Comment by RaananW** [comment]
Will is be possible to see a demo of the error? Maybe reproduced in the playground?

**Comment by RaananW** [comment]
Sorry, no need :-) Culprit found - https://github.com/BabylonJS/Babylon.js/blob/master/Babylon/Mesh/babylon.csg.ts#L592 , the quaternion doesn't exist at all. fix is coming up.

**Comment by KevinBLT** [comment]
Ok :-)

I've just made it too:
http://www.babylonjs-playground.com/#1JZXI4

Thanks for fast fixing.

Kevin

**Comment by RaananW** [comment]
Thanks for reporting, fix was merged. Don't know exactly when it will be available at the playground thou. Pretty soon, i'm sure.

**Comment by KevinBLT** [comment]
Hey there,

are these errors affected by this change?

Without any rotationQuaternion:
http://www.babylonjs-playground.com/#1JZXI4#1

Here is another thing (PivotPoint was changed!):
http://www.babylonjs-playground.com/#1JZXI4#2

I have many errors in my construction when changing pivotmatrix.
In most cases it is a combination of lookAt, PivotMatrix set and CSG.

Thanks,

Kevin

**Comment by RaananW** [comment]
I fixed the first error as well (the From required quaternion, now no longer needed).
Second one - is the same bug as you originally reported.

**Comment by KevinBLT** [comment]
I didn't change the pivot point in the first example. 
If you look on last one, the new created box (CSG.toMesh) has its pivot 
point back to center, whereas I set it to the bottom center.

But I will wait for the commits to be available in playgound and then test again.
