### ISSUE TITLE
Gizmo with custom mesh don't change on hover

### ISSUE THREAD

**Issue by ladevieq** [BabylonJS/Babylon.js#5421]
When you use a custom mesh on a gizmo, the material doesn't change on hover as it do for default meshes.

http://playground.babylonjs.com/#MT4TYN

If you put your cursor over the arrow you can see that it's material change, but it's not the case for the plane.

**Comment by TrevorDev** [comment]
@ladevieq when a custom mesh is set, it will not be automatically updated. You can update the color of it manually using the gizmo's scene's pointer events. See this playground: http://playground.babylonjs.com/#MT4TYN#1 let me know if you have issues with this.

**Comment by limeiwe** [comment]
> @ladevieq when a custom mesh is set, it will not be automatically updated. You can update the color of it manually using the gizmo's scene's pointer events. See this playground: http://playground.babylonjs.com/#MT4TYN#1 let me know if you have issues with this.

有用，谢了兄弟
