### ISSUE TITLE
GetNodeByName does not find TransformNodes?

### ISSUE THREAD

**Issue by Nodragem** [BabylonJS/Babylon.js#5433]
Hello,

it looks like that I can reach my transform node by name using scene.getTransformNodeByName('node_name'), however I couldn't do it with scene.getNodeByName('node_name').

Here a screenshot:
![image](https://user-images.githubusercontent.com/10520249/47619855-1b914b80-dadb-11e8-8f7e-d04980ed658b.png)

I think that as Node is the parent class of Transform Node, getNodeByName() should be able to return any child classes (i.e. Camera, Light, Mesh, TransformNode).

**Comment by bghgary** [comment]
I just fixed this recently. Can you try the latest preview?

**Comment by deltakosh** [comment]
It is fixed in preview ;)

**Comment by Nodragem** [comment]
oh ok :/ sorry about that!
