### ISSUE TITLE
TextBlock Horizontal Alignment bug

### ISSUE THREAD

**Issue by CorayThan** [BabylonJS/Babylon.js#5436]
# Bugs

- Bug repro on [playground](https://www.babylonjs-playground.com/#1MN4ZZ):
- Expected result: You can set a width and left alignment on text blocks.
- Current result: When you set a width text blocks are always center aligned.

**Comment by deltakosh** [comment]
This is because you are not setting horizontalAlignment:
https://www.babylonjs-playground.com/#1MN4ZZ#2

As you define a width, the width is no longer 100% and thus the text is still aligned on the left but the container is centered.
