### ISSUE TITLE
isVisible not available on TransformNode!

### ISSUE THREAD

**Issue by Nodragem** [BabylonJS/Babylon.js#5453]
Hello,

I group my mesh objects together by making them the children of the same TransformNode.
I would like to easily hide all the meshes of a group by setting TransformNode.isVisible = false. However this property does not exist on TransformNode.

**Comment by bghgary** [comment]
You can disable a transformNode by calling `setEnabled(false)` which will also stop rendering itself and all children. Does that work for your case?

**Comment by Nodragem** [comment]
Yes, I think that in my used case it could be ok.
But `setEnabled(false)` would also prevent the children to update, right? so if they have an animation or behaviour, those would not update?

**Comment by bghgary** [comment]
I believe animations will still update the local transforms of the disabled nodes, but their world transform will not update until the nodes are enabled or the function is explicitly called.

Typically, other behaviors are disabled also. For example, picking is disabled.

**Comment by deltakosh** [comment]
Closing as this is a question for the forum :)

**Comment by Nodragem** [comment]
@bghgary, I believe the real question is whether you agree that transform nodes should have the property isVisible.

I personally think it makes sense, as transform nodes are used to make groups of objects.

@deltakosh, I thought it was a feature request. Would it make sense to have a separate section in the forum for discussing feature request / issue before to bring them here? Cause now the Question section is a mix of everything. Hence, contributors may not see a feature request / issue on the forum because it is mixed with everything else.

**Comment by deltakosh** [comment]
Well not sure to understand the feature request then:)
TransformNode is not renderable so the isVisible would be weird no?

**Comment by deltakosh** [comment]
The new inspector won't as it was a mistake in the previous one. 
Furthermore isVisible is per entity only: setting isVisible to a mesh DOES NOT hide its children. So adding isVisible property to a non renderable entity makes no sense

setEnabled is the one you want to use for that

**Comment by Nodragem** [comment]
ok, sounds good.

**Comment by oliverhruby** [comment]
If this is not supported then what's the purpose of having the "eye" icon on the transform node in the inspector? It's just there not working, not doing anything. I would see it as very useful if that icon would iterate through the children on the transfrom node and toggle the isVisible flag (even it the isVisible wouldn't be directly supported on the transformation object itself).

**Comment by deltakosh** [comment]
There is no eye on transformNode:
![image](https://github.com/BabylonJS/Babylon.js/assets/1306056/044767c8-25db-4474-9679-619aebda71f4)

**Comment by oliverhruby** [comment]
Actually, you're right, it's not there, unfortunately (I don't see how that is a benefit). I have mistaken that for a parent Mesh object which has this "eye" icon which doesn't hide the underlying objects, it's just there doing nothing. It's actually a modified version of your hex tile tutorial:

![image](https://github.com/BabylonJS/Babylon.js/assets/6117436/f311307e-78cb-45c1-869a-f53d7426b5e8)

The parent mesh "eye" doesn't hide anything, it works only on the "leaf" meshes.

**Comment by deltakosh** [comment]
That mesh has no geometry:) hence no impact visually:)
