### ISSUE TITLE
Add "module":<path> to package.json

### ISSUE THREAD

**Issue by backspaces** [BabylonJS/Babylon.js#5455]
Please add the module property to package.json. This will enable unpkg.com, for example, to find the module bundle via the ?module query string. 

It will also help other es6 tools, see https://github.com/rollup/rollup/wiki/pkg.module

It is a Good Thing!  : )

**Comment by deltakosh** [comment]
Sure thing, do you want to do a PR?

**Comment by backspaces** [comment]
No, not really. Just adding a property should do the trick. Not sure where you publish the es6 module.

**Comment by deltakosh** [comment]
It will be a different npm package

**Comment by deltakosh** [comment]
Will be fixed with https://github.com/BabylonJS/Babylon.js/issues/4892
