### ISSUE TITLE
Color Gradient helper

### ISSUE THREAD

**Issue by PatrickRyanMS** [BabylonJS/Babylon.js#5463]
# Tool

- Creating tool to give users a GUI to help design color gradients in particle systems and then provide the needed code.
- Should cut down on the amount of back and forth to other applications to determine color values in gradients and allow decoupling of color gradient with alpha gradient in design, letting the tool write the final gradient code for you.

**Comment by thomlucc** [comment]
Unneeded now that Particle Editor is here.
