### ISSUE TITLE
Input Text GUI element does not highlight all text correctly with click input

### ISSUE THREAD

**Issue by PatrickRyanMS** [BabylonJS/Babylon.js#5471]
# Bugs

- https://playground.babylonjs.com/#42LMAC
- When double-clicking in an input text field, the action does not select all of the text in the box. 
- After double clicking and waiting a beat, part of the line will highlight, but the highlighted text does not seem consistent. Sometimes I get a whole word, sometimes I get a part of a word.
- Click and drag does not select text in the input field.

**Comment by deltakosh** [comment]
Pinging @ssaket

**Comment by ssaket** [comment]
> When double-clicking in an input text field, the action does not select all of the text in the box.

Isn't it right ? I took the idea from the bootstrap's input and this is how it works 2 clicks -> Select Text; 3 clicks-> Select All. Though I skipped the 3 clicks event. For reference - 
![image](https://user-images.githubusercontent.com/27828189/48052949-5ed07600-e1cf-11e8-9e59-8c093c9d14ca.png)
There's also a property of inputText, onFocusSelectAll, which if set true would allow to select complete text on focus.
> After double clicking and waiting a beat, part of the line will highlight, but the highlighted text does not seem consistent. Sometimes I get a whole word, sometimes I get a part of a word.

When you say- you get a part of a word, could you specify how many characters are missing like 1-2 or more ? 

> Click and drag does not select text in the input field.

This is something which we can surely add 👍

**Comment by PatrickRyanMS** [comment]
@ssaket, here are the two things that I am seeing. 

- When double clicking a fresh input text control, double clicking seems to select the whole word, but when you start typing, the new characters are inserted from the position where your mouse was rather than replacing the highlighted text: 

![doubleclickissue](https://user-images.githubusercontent.com/31326855/48084045-93323b00-e1ab-11e8-98cd-638aeb5d80eb.gif)

- The second issue is that once you have edited the string in the input text field, double clicking to select the word seems to highlight fractions of the word around the insertion depending on where your insertion point is when double clicking: 

![selectingwholewordissue](https://user-images.githubusercontent.com/31326855/48084136-c5dc3380-e1ab-11e8-95cd-632f30fa43a2.gif)

- For the two click select word and three click select all, I think that really depends on the use and there likely should be an option to toggle the behavior. I can see a use where an input text field may always want to replace the whole string and a use where you want the user to be able to edit a portion quickly. For strings that you will always want to highlight the whole string for edit, like below, getting only a portion with double click and requiring the third click (which may not be a known interaction) feels broken:

![selectwithperiod](https://user-images.githubusercontent.com/31326855/48084555-e6f15400-e1ac-11e8-9b0f-fe9cecb81198.gif)

You can see that the period in the float value is preventing the selection of the whole string, but I also get some strange partial selections on the long, generated string. 

Thank you for looking into this and I definitely think we need click and drag selection as another action to the system as that is a very well known behavior and would be a likely backup if the multi-click to select all does not behave as the user expects. Please let me know if you have more questions.

**Comment by ssaket** [comment]
Awesome ! That's what I needed. Working on Fix.

**Comment by deltakosh** [comment]
Any update?

**Comment by ssaket** [comment]
Hey! Sorry I was on a vacation. The partial highlight as well as the beat delay after double click is fixed, working on the highlight on drag.

**Comment by mysticfall** [comment]
I tested with a fairly recent version (6.13.0) of Babylon.js, but the double-click text selection doesn't seem to work. I also tried the playground snippet linked above but none of the available versions made any difference.

Am I missing something, or was there a regression since this issue got resolved?
