### ISSUE TITLE
Mesh deformation when rotating around two axes

### ISSUE THREAD

**Issue by pmonnin** [BabylonJS/Babylon.js#548]
Hi!

It's me again :)
I am rotating meshes and I am using the rotate method to do so. I have noticed that my mesh (for example a box) is deformed when I rotate it on two axis with angle values above 1 (I am not sure this is the exact threshold though).
You can find an example of the bug here: http://www.babylonjs-playground.com/#1VFORQ#1

Is this a bug?
Thanks,

Pierre

**Comment by deltakosh** [comment]
Hello Pierre!
the first parameter is an axis so it has to be normalized

**Comment by RaananW** [comment]
The rotate function requires a normalized vector to work properly, otherwise, it seems, it causes nice deformations. 
Here - http://www.babylonjs-playground.com/#1VFORQ#2

**Comment by pmonnin** [comment]
Oh thanks!
Sorry about this issue.

**Comment by deltakosh** [comment]
I fixed Rotate so that axis is always normalized for you
