### ISSUE TITLE
How to load base64 glb string into sceneloader?

### ISSUE THREAD

**Issue by yatao-wf** [BabylonJS/Babylon.js#5480]
https://github.com/BabylonJS/Babylon.js/blob/4a529af0a1821cab91512034dfe00791af49be36/sandbox/index.js#L239

My use case is like this:
1. I've already gotten `base64` string in js code, and it's a glb model.
like 
```javascript
const base64_content = 'xxxxxxx';
```
2. I need to import this model into this `sceneloader`

Is there any easy way I can do that? 
I've seen some code can read directly from string start with `data:`, I tried but didn't work.

**Comment by deltakosh** [comment]
Hello please use the forum for questions :)
http://www.html5gamedevs.com/forum/16-babylonjs/
