### ISSUE TITLE
Babylon's 3DS Max Exporter quadruples vertices on export

### ISSUE THREAD

**Issue by EtagiBI** [BabylonJS/Babylon.js#5482]
Hello,

We're trying to use Babylon's 3DS Max exporter to get glTF files. Unfortunately, the exporter quadruples vertices on export, so output glTF files become very big. 

Our export setting are as follows:
![image](https://user-images.githubusercontent.com/20855725/48179286-49c72480-e340-11e8-81a3-3aa87a5f61ef.png)

Here're our source MAX model and exported glTF model:

[Models.zip](https://github.com/BabylonJS/Babylon.js/files/2560423/Models.zip)

As you can see, BIN file is extremely big (should be around 1 Mb).

**Comment by deltakosh** [comment]
Hello!

Would you mind crating the issue in the exporter repo?
https://github.com/BabylonJS/Exporters

Pinging @kcoley in the meantime:)
