### ISSUE TITLE
Can't transform 3D object into 3D button

### ISSUE THREAD

**Issue by imbirlik** [BabylonJS/Babylon.js#5484]
Hi,
Since the new update to alpha.7 I cannot transform 3D objects into 3D buttons with MeshButton3D(mesh, "name").

Am I doing something wrong?
PG:
https://playground.babylonjs.com/#D7LQDZ
- Expected result: The imported mesh is a button that triggers an alert.
- Current result: The imported mesh doesn't have any event.

**Comment by deltakosh** [comment]
Sorry about the inconvenience. I will fix that asap!

**Comment by deltakosh** [comment]
Here is a workaround in the meantime: https://playground.babylonjs.com/#D7LQDZ#1
 (check line #42)

**Comment by imbirlik** [comment]
Oh thanks. Its working but I don't understand this utilityLayer... Will read some documentation.

**Comment by deltakosh** [comment]
My pleasure !
