### ISSUE TITLE
Babylon.js glyphs font

### ISSUE THREAD

**Issue by PatrickRyanMS** [BabylonJS/Babylon.js#5488]
# Design Solution

- We need to create a font containing the glyphs we will use for GUI icons for both the new inspector and as general glyphs that can be used with Babylon.js
- Design a new family of icons that represent that are representative of actions to increase usibility of UX as well as serve as the basis for an extensible shape language going forward.
- OTF file format using the standard alphanumeric keys at first to help with readable code. Using unicode characters is an extra step of using an app to display the glyph and then copy/pasting it into the code which will look like an empty rectangle. 
- Create a key sheet that can be downloaded for reference.

**Comment by haroldma** [comment]
Have you guys considered relying on a subset of MDL2, like the Fabric [one](https://developer.microsoft.com/en-us/fabric#/styles/icons#icons), instead of creating custom glyphs?

**Comment by PatrickRyanMS** [comment]
We've looked through the MDL2 sets of icons and there are many we will likely use, but there is a whole class of icons that aren't covered by MDL2 which are necessary for our icon sets like mesh, material, bone, light, etc. We will need to add icons to the set as I'm not a fan of repurposing icons that were initially designed for something else but kind of fit for what we need because we may be changing the meaning of the icon which can disrupt continuity. 

I've run into this in the past with 3D creation tools as Microsoft doesn't have a large library of products dealing with 3D creation concepts so many times we are left without iconography solutions for the more technical parts of the field.

**Comment by haroldma** [comment]
That's unfortunate but totally get it. It would be a great chance to try to bring these new glyphs into MDL2 and try to standardized what you guys end up creating 👍

In my team, SharePoint Spaces, we're also are going to try to introduce some custom glyphs for our authoring flow. We should sync on this :)

**Comment by thomlucc** [comment]
Closing as we are cleaning "old" issues. Feel free to re-open if still needed.

**Comment by thomlucc** [comment]
Closing as we are cleaning "old" issues. Feel free to re-open if still needed.
