### ISSUE TITLE
Extend Blender Export by Cycles Render mode

### ISSUE THREAD

**Issue by ohader** [BabylonJS/Babylon.js#549]
Currently the Blender Export script supports the default render mode, but unfortunately not the cycles render mode.

I think it should be doable to extend the Python script for this particular feature. However, I'm not that 3D modelling guy, but more a dev. If somebody could gimme a hint, where to start or what to consider in the "bpy" module, I'd try my best to extend the current exporter. Thanks in advance!

**Comment by deltakosh** [comment]
I would love to :) Please do a post on our forum. There are really great blender experts there
