### ISSUE TITLE
Babylon.gui.js not a source file

### ISSUE THREAD

**Issue by BabylonJSGuide** [BabylonJS/Babylon.js#5491]
# Bugs

In the dist/gui and dist/preview release/gui folders babylon.gui.js is the same as the babylon.gui.min.js file both in the repo and any local build with gulp. This also means that the CDN links both point to a min version

**Comment by deltakosh** [comment]
Yes this is something we will fix with a further update. It is linked to the module work 

Thanks for the heads up (closing as it is already on the work)
