### ISSUE TITLE
Add an option to disable checking manifest but keep IndexedDB offline support 

### ISSUE THREAD

**Issue by yvele** [BabylonJS/Babylon.js#5508]
This is kind of related to #4207 and #3117 but we want to keep IndexedDB offline support

For our IndexedDB offline mode, we don't need `.manifest` files at all because **all our URL are immutable**, they embed a version number and a hash (this is a good practice commonly used in Web industry).

For example all our immutable URLs looks like (the [hash](https://survivejs.com/webpack/optimizing/adding-hashes-to-filenames/) is not required but we still use it)

```
https://domain.com/project/v1.0.0/foo.hash.ext
```

We actually only provide `.manifest` files to make babylonjs happy, but we don't use `.manifest` files, they are all the same and never changes (because our URL are immutable).

Can you please add an option to disable `.manifest` check but keep IndexedDB offline support?

This will remove useless `.manifest` HTTP requests 😉

**Comment by yvele** [comment]
I can provide a PR if needed

**Comment by deltakosh** [comment]
Please :)

**Comment by yuccai** [comment]
Does 
```
Database.IDBStorageEnabled = true;
engine.enableOfflineSupport = true;  //(enable by default)
engine.disableManifestCheck = true;
```
 do the job ?

**Comment by deltakosh** [comment]
you are so right. This is already enough :)
