### ISSUE TITLE
syntax error in babylon.js on homepage with firefox

### ISSUE THREAD

**Issue by SuperUserNameMan** [BabylonJS/Babylon.js#552]
Hi,

When accessing the homepage http://babylonjs.com/ using firefox 38.0.5, clicking on demos have no effect, and the browser console says :

SyntaxError: unterminated string literal, babylon.js:30:4127
ReferenceError: BABYLON is not defined, index.js:413:8

**Comment by Temechon** [comment]
It's working fine for me... Do you have this issue for all demos ? Is it the same for the (playground ?)[http://www.babylonjs-playground.com/]

**Comment by SuperUserNameMan** [comment]
I tried again after several Ctrl+R in the hope of refreshing the cache and I still have the same problem :

None of the demos from the homepage launch.
Clicking on their picture does nothing.

The script babylon.js is simply disabled and ignored on page load after the two mentioned errors are detected by Firefox.


On the other hand, the playground worked.
Also, I tried the homepage with IE11 and it worked.

**Comment by SuperUserNameMan** [comment]
Note : in case that matter, this is Firefox 38.0.5, under Windows 8.1

**Comment by SuperUserNameMan** [comment]
OKAY, I've jsut found what was wrong.

This was just that the babylon.js script in my cache was somehow truncated.

I managed to refresh this file and now it works correctly.

Sorry for the false alarm.

**Comment by Temechon** [comment]
Cool perfect :)
