### ISSUE TITLE
dispose not clear all the node

### ISSUE THREAD

**Issue by MooreSky** [BabylonJS/Babylon.js#5530]
# Bugs

when i dispose one node，the children of the onde still stay in the scene.

- Bug repro on [playground](https://www.babylonjs-playground.com/#068WEJ)
- Expected result: after the dispose, the rootNode's length is 2
- Current result: after the dispose, the rootNode's length is 12

**Comment by deltakosh** [comment]
Thanks a lot for the heads up !
