### ISSUE TITLE
Data URL textures loaded from glTF not working in Edge

### ISSUE THREAD

**Issue by kayahr** [BabylonJS/Babylon.js#5533]
### Versions

* BabylonJS  3.3.0 and 4.0.0-alpha.9
* Windows 10 1809
* Edge 44.17763.1.0

### Repro 

* Open Edge browser on Windows
* Go to [BabylonJS sandbox](https://sandbox.babylonjs.com)
* Upload [this model](https://github.com/BabylonJS/Babylon.js/files/2595472/test.zip)

### Expected result

Should display a cube with a small 16x16 texture on it (Loaded from data URL in the glTF file) as it does in Chrome and Firefox.

### Current result

In Edge the model can't be loaded and console shows error message: 

    BJS - [14:33:59]: Error while trying to load image: data:file:1542634439238/data:image/png;base64,iVBORw0KGgoAAAANSU...eq3FGe/sTFu/7NM3oWN

### Additional information

It's hard to debug in Edge but I digged down to this location in the source of the glTF loader:

https://github.com/BabylonJS/Babylon.js/blob/5fe931ed59ab572bd2f56186f1915bb80cbf35ce/loaders/src/glTF/2.0/babylon.glTFLoader.ts#L1726

In this line the `name` variable is the correct data URL and this line prefixes this data URL with the root URL and another data-URL-prefix which looks wrong to me. This also happens in Chrome and Firefox but for some reason they don't complain about this like Edge.

**Comment by sebavan** [comment]
@bghgary , could you have a look ?

**Comment by bghgary** [comment]
@kayahr Thanks for reporting this. Chrome works, but there is actually an issue with loading base64 images in the loader where it would decode the base64 image twice. I've fixed it in the referenced PR.
