### ISSUE TITLE
AssetManager onTasksDoneObservable has an empty tasks array if tasks where successful

### ISSUE THREAD

**Issue by pascalbayer** [BabylonJS/Babylon.js#5540]
- Bug repro on [playground](https://playground.babylonjs.com): https://www.babylonjs-playground.com/#ZJYNY#104
- Expected result: tasks array length should be the number of tasks also if the tasks were executed successfully
- Current result: task array length is 0 if tasks were executed successfully, only errored tasks are listed

EDIT: same applies for onFinish

**Comment by sebavan** [comment]
This is actually by design, only tasks not done are part of the array to help dealing with unfinished tasks.

May I ask about your use case ? we might find another solution.

**Comment by pascalbayer** [comment]
Understood. Basically what I'm trying to approach is to wrap the AssetManager in a Promise that resolves when all tasks are done or failed and access the tasks object in my integration tests. The logic for actually handling failed and successful tasks happens with the onTaskSuccess/Failed observables and should not have an impact on the wrapping promise.
As a workaround I can store all successful tasks internally and join them with the failed ones and pass that as a promise result, however since the sample code explicitly check on the task state error I thought that the tasks will always be provided and have to be filtered by task state.

**Comment by sebavan** [comment]
no problem, your approach will work perfectly.
