### ISSUE TITLE
Add support for loading glb from a base64-encoded string or arraybuffer

### ISSUE THREAD

**Issue by bghgary** [BabylonJS/Babylon.js#5579]
See www.html5gamedevs.com/topic/41216-load-glb-model-into-scene-directly-from-content-string

**Comment by major-mayer** [comment]
Is it correct, that it is only possible to load GLB files from a Base64 string?
I tried to do this with a base64 encoded stl file (using the FileReader API) and it didn't work...?

**Comment by sebavan** [comment]
Ping @Popov72 which will be the best placed to answer :-)

**Comment by Popov72** [comment]
The PR was only for glb.

You should post to the forum and provide a small PG so that we can have look for stl files.

**Comment by bghgary** [comment]
@Popov72 Just noticed we only added support for base64. Are we adding array buffer support too?

**Comment by sebavan** [comment]
@bghgary do we need array buffers ? Are createObjectURL not enough ? just wondering out loud :-)

**Comment by bghgary** [comment]
I guess so. I can't remember why I put array buffer in the title.

**Comment by sebavan** [comment]
Let s add it if it comes back then

**Comment by keverw** [comment]
I was thinking array buffers would be useful over base64 due to the 33% overhead. I know on browser there is blob but if doing serverside stuff with nullEngine beign able to use array buffers would be better I think. Plus since you need the XHR polyfill in Node, this way could write my own code to read from the file system and load the mesh that way.

**Comment by br-matt** [comment]
Array buffer would be much appreciated. Currently trying to figure how to convert array buffer glb response to base64 and then use `Tools.DecodeBase64` without much luck yet.

**Comment by deltakosh** [comment]
pinging @bghgary

**Comment by bghgary** [comment]
Are `File` objects available in these situations? If so, that's another workaround to be able to load from a buffer.

BABYLON.SceneLoader.LoadAsync("<root url>", new File([glbArrayBuffer], "Box.glb"));

If not, can you file a feature request separate from this one? We can track it and try to figure out a way to do this.

**Comment by br-matt** [comment]
Thanks for the quick response ! It is available and I gave it a shot. 

![Screen Shot 2021-04-05 at 1 40 51 PM](https://user-images.githubusercontent.com/66705855/113605998-6b15c300-9615-11eb-9c2b-9ff0a7b5a493.png)

I got this after. I am not too familiar with glb headers. The file can be loaded normally via .glb and also array buffer -> base64. I will go ahead and open that soon unless you have ideas about the headers here

**Comment by bghgary** [comment]
The magic number is a 4-byte constant at the beginning of the GLB file. It is the ASCII values that represent the letters `g`, `l`, `T`, `F`.

Yours in hex is `0x4F44213C`. The right values are `0x46546C67`.

Can you check your input array buffer to see if these values at at the beginning?

**Comment by br-matt** [comment]
Far as I can tell, yes. This below is the beginning of the input array buffer

![Screen Shot 2021-04-05 at 4 25 14 PM](https://user-images.githubusercontent.com/66705855/113623431-57298b80-962c-11eb-9575-f6c097f1e954.png)

The hex you said is mine is actually `<!DO` backwards.. which leaves me scratching my head. That's the beginning of an html document of course

**Comment by bghgary** [comment]
What environment are you in? Can you create a repro easily?

**Comment by br-matt** [comment]
Using webpack / webpack-dev-server and package version `5.0.0-alpha.16`

https://playground.babylonjs.com/#NUEHWL here is a simple playground example

**Comment by bghgary** [comment]
Hmm, I don't think the PG is having the same issue as your magic number issue.

This works for example, but I don't think you should have to pass "file:" for the first parameter. I'll have to think about that one.
https://playground.babylonjs.com/#NUEHWL#1

**Comment by br-matt** [comment]
`file:` did it for me locally as well ! Thank you !!

I think because webpack-dev-server does a 304 redirect rather than 404, it got a little further

**Comment by bghgary** [comment]
I'm going to fix the passing in `file:` problem. That shouldn't be necessary.

**Comment by bghgary** [comment]
With the latest changes, you shouldn't have to pass `file:` anymore.

**Comment by bghgary** [comment]
Loading directly from an arraybuffer is now supported: https://github.com/BabylonJS/Babylon.js/pull/13946
