### ISSUE TITLE
Inspector : .env texture tool

### ISSUE THREAD

**Issue by Vinc3r** [BabylonJS/Babylon.js#5586]
It seems that we're currently not able to generate [.env textures](https://doc.babylonjs.com/how_to/use_hdr_environment#creating-a-compressed-environment-texture). Is it a bug or a feature not yet re-implemented in the new inspector?

I tried using BJS v3 + inspector from the /dist/ folder, but I don't see the env tool in it.

**Comment by deltakosh** [comment]
It should be in the tools tab when you are in the sandbox for instance
I can see it in my computer

**Comment by Vinc3r** [comment]
yep the button is in place, but clicking on the button do nothing except this console error `The cube texture is invalid (not prefiltered).`... and I don't know where to upload this envTexture.

[img](https://i.imgur.com/O0bzhsu.gif)

**Comment by deltakosh** [comment]
Ok let's ask @sebavan  :)

**Comment by sebavan** [comment]
It is normal it does not export in your page cause the env in your page is already a .env (you can see the error in the console).
To generate the env open the sandbox drag drop a glb file (not from the url shortcut), drag drop a dds preprocess in lys for instance and then use the export button.

I ll add an error message to the inspector.

**Comment by Vinc3r** [comment]
OK so the doc' have to be updated : https://doc.babylonjs.com/how_to/use_hdr_environment#creating-a-compressed-environment-texture

**Comment by deltakosh** [comment]
ok to do a PR?

**Comment by Vinc3r** [comment]
yep I'll do that in the next few days
