### ISSUE TITLE
ScrollViewer Changes

### ISSUE THREAD

**Issue by BabylonJSGuide** [BabylonJS/Babylon.js#5593]
# Bugs ?

https://www.babylonjs-playground.com/#13CF95#3
1. is barBorderColor still necessary?
2. barBackground does not fill all the vertical slider background

# TextBlock adjustment
https://www.babylonjs-playground.com/#3EF49E#3

is there a better way than using setTimeout and adjusting height. Comment out this line (71) and no vertical scroller appears

# Feature request
Would picking up the dragSpace control in the bottom right corner and dragging it to change ScrollViewer size be a feature worth adding? Did try it with the original version but could not do it. Also what happens if the dragSpace control disappears when the viewing window is small enough to fit in the ScrollViewer? How would a user enlarge it again? So not a straight forward feature at all.

**Comment by ssaket** [comment]
Also, Can the bottom right square be removed ? I can't help noticing it every time

**Comment by BabylonJSGuide** [comment]
Not sure what you want instead. The horizontal and vertical scroll bars have to form a square in the bottom right corner

**Comment by ssaket** [comment]
![screenshot 2018-12-04 at 5 33 34 pm](https://user-images.githubusercontent.com/27828189/49440884-e8815c80-f7ea-11e8-9418-b018664d34a8.png)
If the vertical bar is made to reach the bottom/end, this can be avoided.

**Comment by deltakosh** [comment]
I will remove barBorderColor
Checking other issues right now

**Comment by deltakosh** [comment]
Should be good now
Regarding dragging, this is a tough one and I'm not sure I want to go down the dragging path :)

**Comment by BabylonJSGuide** [comment]
> Should be good now brilliant well done
> Regarding dragging, this is a tough one _sure is_ and I'm not sure I want to go down the dragging path :) _Don't blame you I am sure there are many better things on the road map_

**Comment by deltakosh** [comment]
I would love to try it but with a new container then: a resizableContainer that will only provide this feature (I like composable UIs with only minimal feature set per control)
