### ISSUE TITLE
When i load stl file, it shows importScene of undefined from undefined version

### ISSUE THREAD

**Issue by flzyup** [BabylonJS/Babylon.js#5595]
# Bugs

- Bug repro on [playground](https://playground.babylonjs.com):
```
BABYLON.SceneLoader.Append('/assets/stl/', 'arm.stl', scene, function(scene) {

});
```
- Expected result: expect to load stl
- Current result: but it failed with exception as following:
`BJS - [02:26:40]: Unable to load from /assets/stl/arm.stl: importScene of undefined from undefined version: undefined, exporter version: undefinedimportScene has failed JSON parse`
![image](https://user-images.githubusercontent.com/158452/49464385-b9dca380-f835-11e8-827e-a9ca1d8d8028.png)

**Comment by deltakosh** [comment]
Hello did you make sure to reference the stl loader first?
https://doc.babylonjs.com/how_to/stl

**Comment by flzyup** [comment]
@deltakosh yeah, i used angular js, and imported as following:
```
import * as BABYLON from 'babylonjs';
import * as BABYLON_LOADER from 'babylonjs-loaders';

export class TestComponent {
     testMethod() {
      // ... init scene
      BABYLON.SceneLoader.Append('/assets/stl/', 'arm.stl', scene, function(scene) {

    });
     }
}
```

**Comment by flzyup** [comment]
@deltakosh I fixed by modify the import: `import 'babylonjs-loaders';` Thanks

**Comment by relu91** [comment]
> @deltakosh I fixed by modify the import: import 'babylonjs-loaders'; Thanks

I tried with that import but I wasn't still able to load the `.obj`. It seems that `webpack` is doing something fancy behind. I solved with this quick workaround:

```ts
import { Engine, Scene, ArcRotateCamera, HemisphericLight, Vector3, Mesh, MeshBuilder, SceneLoader } from 'babylonjs';
import {OBJFileLoader} from 'babylonjs-loaders';


SceneLoader.RegisterPlugin(new OBJFileLoader())

```

**Comment by cassieview** [comment]
@relu91 This resolved the issue. Thanks!!

**Comment by relu91** [comment]
There you go: https://github.com/vaimee/WoTSimFarm/blob/2468786342b3ab2fe1b933bd6b9c8d2becb6062c/frontend/src/vue/view/SimulationPane.vue . Be aware that the project was a toy example and the code might not be really well documented/designed.
