### ISSUE TITLE
Warnings when compiling with webpack

### ISSUE THREAD

**Issue by kutomer** [BabylonJS/Babylon.js#5606]
Hello :)

Nothing new, but couldn't find any report for this.
When compiling babylon with webpack I encounter the following compilation errors:
1.  `Module not found: Error: Can't resolve 'cannon' in '/.../node_modules/babylonjs'`
2. `Module not found: Error: Can't resolve 'oimo' in '/.../node_modules/babylonjs'`

Tried to change define plugin as:
```
oimo: JSON.stringify(true),
cannon: JSON.stringify(true)
```

Any ideas?

**Comment by deltakosh** [comment]
Here is why: https://doc.babylonjs.com/features/npm_support#external-libraries
