### ISSUE TITLE
tsc error: babylon.d.ts inconsistent with typescript/lib/lib.dom.d.ts

### ISSUE THREAD

**Issue by pineapplemachine** [BabylonJS/Babylon.js#5623]
Two definitions in `babylon.d.ts` of my installed `babylonjs` npm package (@3.3.0) are inconsistent with TypeScript's own DOM type definitions (Tested with @3.1.1 and @3.2.2).

Please see my `tsc` error log ("MODIFIED" comments mine) -

![image](https://user-images.githubusercontent.com/7266412/49800658-baeb6480-fd50-11e8-9186-c0ac6fcf3f9b.png)

I was able to work around this issue by manually making these changes to my installed `babylon.d.ts`:

L252
``` ts
    - fullscreen: boolean;
    + readonly fullscreen: boolean;
```

L303
``` ts
    - readonly orientation: string;
    + readonly orientation: ScreenOrientation;
```

I was also able to resolve this problem by using Babylonjs @4.0.0-alpha.11. Both of these declarations seem to be absent in `dist/preview release/babylon.d.ts`. How stable can I expect the preview release to be? Is there a recommended workaround to get `tsc` working on the latest stable release in the meantime, other than making the aforementioned local changes?

**Comment by deltakosh** [comment]
Yes this is painful. TypeScript introduces breaking changes when updating minor versions.

Anyway:) you found two good ways of fixing it.

V4.0 is already really stable so I would encourage you to switch but other technique is fine as well
