### ISSUE TITLE
Creating a texture for an image that returns a 404 doesn't report using onError callback

### ISSUE THREAD

**Issue by haroldma** [BabylonJS/Babylon.js#5631]
Code: https://github.com/BabylonJS/Babylon.js/blob/master/src/Engine/babylon.engine.ts#L4324-L4332

It goes into the if block for `UseFallbackTexture`, which returns. onError call is after this.

**Comment by haroldma** [comment]
Well, we have a new bug that a texture is failing to load and both `onError` and `onLoad` aren't getting called. There seems to be no way of knowing that the fallback was loaded. Before updating to the latest alpha, this was calling onError.

In the end, should `useFallback` have it called `onLoad`? It definitely feels like valuable information to know that the original texture failed to load.

**Comment by deltakosh** [comment]
I agree. Do you want to do a PR to remove the return?

**Comment by deltakosh** [comment]
(I can do it obviously if you prefer)

**Comment by haroldma** [comment]
I'll go ahead and do a PR :)

**Comment by haroldma** [comment]
PR: #5633
