### ISSUE TITLE
GUI and Fullscreen overlapping when Inspector enabled

### ISSUE THREAD

**Issue by meteorplus** [BabylonJS/Babylon.js#5640]
Hello guys,

# Bug

- GUI and Fullscreen overlapping when Inspector enabled
- Expected result: to be able to go fullscreen when the inspector is enabled and the right/left panels are shown
- Current result: can't go fullscreen since the buttons are hidden with the panels it seems.

#ScreenShots 

Before enabling the inspector:

<img width="1190" alt="screen shot 2018-12-13 at 10 05 57 am" src="https://user-images.githubusercontent.com/12363020/49927660-b93faf00-febe-11e8-8b66-af4cf6917dc0.png">

After enabling it

<img width="1190" alt="screen shot 2018-12-13 at 10 02 33 am" src="https://user-images.githubusercontent.com/12363020/49927619-9f05d100-febe-11e8-97a0-f0b01e764c3d.png">

btw how do you change to full screen if I can add a workaround for now?

`        BABYLON.Tools.RequestFullscreen();`
Doesn't  seems working sadly 

Thanks

**Comment by deltakosh** [comment]
Info not see that as a bug as the inspector had an option to let you decide where you want it to be hosted. You can provide specific HTML elements to host it.
Also not sure why you cannot simply close the inspector and then click on fullscreen button as the inspector won't be visible in fullscreen?

**Comment by deltakosh** [comment]
Or other option: you can open the inspector in popup mode directly

**Comment by deltakosh** [comment]
https://doc.babylonjs.com/how_to/debug_layer

**Comment by meteorplus** [comment]
Can't I use the inspector won't be visible in fullscreen?

**Comment by meteorplus** [comment]
I tried that but it is not defined:

```
Tools.RequestFullscreen(yourDiv)
VM417:1 Uncaught ReferenceError: Tools is not defined
    at <anonymous>:1:1
```

**Comment by deltakosh** [comment]
BABYLON.Tools.RequestFullscreen(yourDiv)

**Comment by meteorplus** [comment]
Thanks, Works very well but how about enabling the tools while the inspector it open?

**Comment by deltakosh** [comment]
As I mentioned this depends upon how you setup your HTML so we cannot fix it :)

**Comment by meteorplus** [comment]
thanks :)
