### ISSUE TITLE
Improve octree update performance

### ISSUE THREAD

**Issue by RyanHow** [BabylonJS/Babylon.js#5641]
- Repro on [playground](https://playground.babylonjs.com): https://playground.babylonjs.com/#AYMY34#1
As the octree updates (once per second on the playground), the frames skip.

- Link to [forum](https://forum.babylonjs.com/) discussion about the feature: https://forum.babylonjs.com/t/how-to-optimise-updating-a-large-octree/87

- Feature description
Ability to add and remove items from the octree (or be able to make a call to update the octree) and have it update smoothly

The ultimate would be to not have to manage the octree at all, just to "enable" it on the scene, and use hints on meshes to optimise.

**Comment by deltakosh** [comment]
Until we have thread the second one will be tricky but I will see what can be done to add or remove quickly.

My idea would be to construct the octree once and then have an option to add and remove without rebalancing it. So the add or remove will just be instant. And you will always have the option  to rebalance at will

Thoughts?

**Comment by RyanHow** [comment]
Does that just mean the tree isn't as efficient the more out of balance it gets? Until at the extreme it would provide no benefit at all, or degrade performance?

I think that sounds ok. As long as it's documented.

There isn't a way to partially rebalance a tree, and call it each frame? I guess it is hard to determine how much time to spend rebalancing without degrading performance?

It would definitely help towards solving the issue though :)

**Comment by deltakosh** [comment]
Exactly. So for a first update let's try to add or remove item quickly and then see if that fits you need and work on it

I'll be able to spend time on it this Monday
