### ISSUE TITLE
Forward and Back shortcuts on the Mac send the camera flying

### ISSUE THREAD

**Issue by mattdmorgan** [BabylonJS/Babylon.js#5646]
1. Launch the default playground on the Mac (https://playground.babylonjs.com).
2. Click the scene to give it keyboard focus.
3. Press (and release) Command-RightArrow, the Go Forward shortcut. (Also reproes with Command-LeftArrow, i.e. Go Back, if you have nothing on your back stack.)

Result: camera goes flying off to the right, as if the arrow key were being held down.
Expect: single motion to the right, as though you had pressed the arrow key once without a modifier. (At least, this is the current Windows behavior.)

Reproes in Safari 12.0.1 and Chrome 71.0.3578.98 on the Mac. Doesn't repro on Windows with the equivalent Alt-Arrow shortcuts.

**Comment by deltakosh** [comment]
@kcoley  do you mind having a look?

**Comment by mattdmorgan** [comment]
It looks like browsers don't send keyup for the arrow key in this case for some reason (as evidenced by doing command-arrow in https://w3c.github.io/uievents/tools/key-event-viewer.html).

**Comment by kcoley** [comment]
@mattdmorgan @deltakosh  I'll take a look
