### ISSUE TITLE
Beta12 > babylon.gui.module.d.ts > error TS2307: Cannot find module '2D'.

### ISSUE THREAD

**Issue by RafaeldelM** [BabylonJS/Babylon.js#5658]
Hello,

I'm updating from 4.0.0-beta10 to beta12, and from beta11 and beta12, I had that problem:

`ERROR in node_modules/babylonjs-gui/babylon.gui.module.d.ts(1610,29): error TS2307: Cannot find module '2D'.
node_modules/babylonjs-gui/babylon.gui.module.d.ts(2182,53): error TS2307: Cannot find module '2D'.`

Do you know what can be the problem? My project doesn't build.

Thanks,

Ralph

**Comment by deltakosh** [comment]
@sebavan do you mind having a look? Thank you so much!

**Comment by sebavan** [comment]
Should be good in the next NPM release
