### ISSUE TITLE
WebVR re-entry on Edge with WMR breaks trigger-based button clicks

### ISSUE THREAD

**Issue by v-keitho** [BabylonJS/Babylon.js#5664]
Needed: Windows Mixed Reality headset

**- Bug repro on [playground](https://www.babylonjs-playground.com/#0Y75BA#35):**
1. Open WebVR with bottom-right button
2. Click on 'close' button in VR (press trigger while pointing at it)
3. Within WMR home, navigate to Edge browser
4. Click the WebVR button again in bottom-right (while still in VR)
5. Press trigger on controller while facing blank space

**- Expected result:** Nothing will happen
**- Current result:** The "close" button will be pressed.

**Comment by TrevorDev** [comment]
Closing this for now as an Edge specific bug as this works as expected in firefox. Recommendation is to work around this is app code until Edge is updated. Feel free to reopen if this is urgent and there is no workaround for your use case.
