### ISSUE TITLE
Turn useInvalidateRectOptimization on by default

### ISSUE THREAD

**Issue by deltakosh** [BabylonJS/Babylon.js#5671]
We cannot still turn the optimization on by default because some issues remain:
- Few clipping issues on https://www.babylonjs-playground.com/#3VMTI9#24
- Rotation issues on this PG: https://www.babylonjs-playground.com/index.html#XCPP9Y#821 (the red rectangle disapears at some angle)

For the second issue I think I know why. We need to change the intersectsRect function to make sure we first transform the currentMeasure using this._transformMatrix (The same way we transform the invalidatedRect), then deduce the AABB and finally compare to invalidated rect. Indeed, we need to make sure they are both using transformed coordinates (and thus I think we could get rid of the clearRect and the invalidatedRect and just keep the clearRect for both clearing and clipping)

**Comment by deltakosh** [comment]
And to be honest I think it is also the same issue for the _clip function: we cannot merge the invalidatedRect with the currentMeasure to determine the clipping rect. This time we need to do the opposite. Getting the invalidatedRect to local coordinates by transforming it with this._invertTransformMatrix and then merging it with currentMeasure

**Comment by deltakosh** [comment]
If that works we will definitely need to validate performance because these operations won't be free

**Comment by TrevorDev** [comment]
@deltakosh did https://github.com/BabylonJS/Babylon.js/commit/63e3b8dd6fac1c29274f28f7ce532f4879020da3 restore the original functionality or do you need me to take a look at that? Also what clipping issues did you see in the first example?

**Comment by deltakosh** [comment]
My commit fixed some points (I sent you an email:)) but some issues remain

On the first one I saw clipping issue on the rotating part of the left and on the dash line in the middle part

**Comment by TrevorDev** [comment]
Adding https://forum.babylonjs.com/t/gui-not-refreshing-properly-pg-attached/541 as an issue I will fix in this

**Comment by TrevorDev** [comment]
Adding this as another issue needed to be fixed here: https://forum.babylonjs.com/t/stackpanel-at-bottom-center/623
