### ISSUE TITLE
Issues with friction and restitution in ammo.js plugin

### ISSUE THREAD

**Issue by BabylonJSGuide** [BabylonJS/Babylon.js#5672]
In process of creating docs looking at differences between Cannonjs, Oimojs and Ammojs and found

# Bugs AmmoJS only

This PG https://www.babylonjs-playground.com/#SFC07U is used to explain bugs.
(1)
Though both `impostor.physicsBody.getFriction();` and `impostor.physicsBody.getRestitution();` are called within AmmonJSPlugin (lines 614 ad 632) neither method exist for physicsBody

Remove comments in turn from lines 45 and 46 in above PG to see issue

(2)
When a physicsImposter is created value for friction is not used. 

In above PG lines 48 and 49 set friction to 0 but lines 42 and 43 do not set friction to 0.
With loaded PG click apply force button once, since friction is 0 box continues to slide.
Comment out both lines 48 and 49 and RUN PG. click apply button once and friction halts the box.

Probably because there is no mention of  `body.setRestitution(impostor.getParam("friction"));` in lines 237 to 271

**Comment by sebavan** [comment]
Ping @TrevorDev .

@BabylonJSGuide you might have some delays on the answer due to the holliday season :-)
