### ISSUE TITLE
GradientMaterial does not work as expected when using disableLighting

### ISSUE THREAD

**Issue by haroldma** [BabylonJS/Babylon.js#5673]
PG: https://www.babylonjs-playground.com/#FQU0WV

I expected the bottom to look fully white but instead, it looks dark.

Seems to be related to there not being a way to set emissiveColor. Is there a way to get it to work like that?

**Comment by sebavan** [comment]
Actually I wonder if for gradients we should not consider disableLighting as emissive ?

@deltakosh  any preferences between me adding emissive or considering disableLighting as emissive ?

**Comment by julien-moreau** [comment]
Fixing ASAP! It looks like the disableLighting property is not used by the material

**Comment by julien-moreau** [comment]
@haroldma pull request merged!
Now disableLighting works as emissive

**Comment by haroldma** [comment]
Nice! Any ideas when there's a new alpha coming out?

**Comment by deltakosh** [comment]
This Monday:)
