### ISSUE TITLE
Touch input – Improve documentation: touch-action="none" needed

### ISSUE THREAD

**Issue by thomasaull** [BabylonJS/Babylon.js#5674]
I just spent an hour trying to figure out why my ArcRotateCamera was not working with touch input on iOS. Even the official playground example: https://www.babylonjs-playground.com/#12WBC#69 did work as long as I used the playground. Downloading the .zip and using the generated `index.html` broke the functionality.

Eventually I figured out the canvas needs to have the attribute `touch-action="none"` to make it work. Since I couldn't find it anywhere in the documentation, please consider adding it to save other users from pulling their hair out and wasting time :) Thanks!

**Comment by sebavan** [comment]
@deltakosh Should I do it in code instead ? it has been several questions and between css and attributes depending on the browser it is always a bit tricky.

Are there any good reason to not do it by code ?

**Comment by sebavan** [comment]
@thomasaull yup you are not the first one with the issue, we ll definitely do smthg about it.

**Comment by sebavan** [comment]
This will now be done automatically
