### ISSUE TITLE
Object stick together when using cannonjs as physic engine 

### ISSUE THREAD

**Issue by kelvinkoko** [BabylonJS/Babylon.js#5678]
For example, when try to switch to use CannonJS in this playground
https://www.babylonjs-playground.com/#8PQK71
e.g. add this line to playground
`scene.enablePhysics(null, new BABYLON.CannonJSPlugin());`

All object sticker together once start

**Comment by TrevorDev** [comment]
@kelvinkoko Thanks for finding this. It looks like cannon was ignoring the connectedPivot parameter you were using.
