### ISSUE TITLE
bakeTransformIntoVertices isn't applied following the children relationship

### ISSUE THREAD

**Issue by pmonnin** [BabylonJS/Babylon.js#568]
Hi!

I am grouping objects to translate/scale/rotate them together. I use bakeTransformIntoVertices on the group mesh to do so but it appears that this function isn't applied to the children of the mesh.

I am not sure it's a bug or a conception choice, so I prefer asking before implementing a workaround in my code :)

Thanks in advance for your answer,

Pierre

**Comment by deltakosh** [comment]
Hey!
This is definitely by design :)

**Comment by jbousquie** [comment]
I guess people committing before 6:00 am local time just had a short 
night due to spacio-temporal baby vortex :-D

**Comment by pmonnin** [comment]
Thanks for your reply!
So, I will implement a workaround in my code :)

**Comment by deltakosh** [comment]
Lol Jerome :)
@pmonnin: Sounds like a good plan
