### ISSUE TITLE
Using SSAO2 pipeline with hasAlpha issue

### ISSUE THREAD

**Issue by azukaar** [BabylonJS/Babylon.js#5690]
When using SSOA2 Pipeline, the SSAO rendering isn't gonna consider objects with hasAlpha as having the right depth in the z-buffer, resulting in annomalies in the rendering.

Here is an example : https://www.babylonjs-playground.com/#LFVESY

![image](https://user-images.githubusercontent.com/7872597/50681863-d884b480-1004-11e9-8bcd-f925ada109f1.png)

**Comment by deltakosh** [comment]
Thanks I will have a look asap

**Comment by deltakosh** [comment]
@CraigFeldspar or @julien-moreau dop you guys want to have a look?

**Comment by CraigFeldspar** [comment]
@deltakosh i'm out of town till tuesday, but i'll definitely have a look next week.
On the top of my head i think it's maybe that the hasAlpha flag is ignored, and not sent to the depth-pass fragment shader.

**Comment by deltakosh** [comment]
I think so! Thanks and no rush. Next week is fine

**Comment by CraigFeldspar** [comment]
sneaky AF, got me 2 hours to figure it out ;)
