### ISSUE TITLE
GUI Image Control detectPickOnOpaqueOnly flag

### ISSUE THREAD

**Issue by WriterZephos** [BabylonJS/Babylon.js#5711]
# Feature request

Here is the discussion about this feature request: https://forum.babylonjs.com/t/how-to-render-2d-polygons-in-billboard-mode-with-constant-size-on-screen/556

Basically it is a flag that when set to true, it only registers pick on the parts of the image that have an alpha > 0. This will allow complicated shapes in image form to be used as clickable icons without having rectangular clicking area, only the actual icon can be clicked on. Examples of the use case for this are in the discussion above.

**Comment by WriterZephos** [comment]
I was looking through the issues and found this one which seems to be related: https://github.com/BabylonJS/Babylon.js/issues/3897

I think they are trying to accomplish the same thing in different ways. Thoughts?

**Comment by deltakosh** [comment]
Well in a sense yes but in this case I will just update the image control..Stay tuned :)
