### ISSUE TITLE
StackPanel at Bottom-Center 

### ISSUE THREAD

**Issue by TrevorDev** [BabylonJS/Babylon.js#5730]
https://www.babylonjs-playground.com/#4P8PJY#9

Creating this so it doesn't get lost as it is separate from:
https://github.com/BabylonJS/Babylon.js/pull/5720

https://forum.babylonjs.com/t/stackpanel-at-bottom-center/623

**Comment by TrevorDev** [comment]
@deltakosh after looking at this, I think this isn't actually a bug and instead the old behavior was broken.

control.verticalAlignment = BABYLON.GUI.Control.VERTICAL_ALIGNMENT_BOTTOM; moves the control to the bottom of the parent, not move it's children to the botton, correct?

**Comment by deltakosh** [comment]
You are right!. The panel is 100% height so it is actually aligned correctly! Please report back to the forum :)
