### ISSUE TITLE
ArcRotateCamera with mousewheel control and attachControl(canvas, false) scrolls page when zooming

### ISSUE THREAD

**Issue by interfect** [BabylonJS/Babylon.js#5734]
I can't reproduce this on Playground, because it provides a canvas that isn't on a scrollable web page.

When you use the ArcRotateCamera in a canvas on a scrollable page, even if you pass `false` as the second parameter to `camera.attachControl()`, scrolling in the canvas still scrolls the page as a whole as well as zooming the camera.

I don't think it used to do this a year or two ago, but it does it now, with Babylon v3.3 on Firefox 64, on a Macbook, scrolling with the touchpad.

When you pass false as that second parameter, scrolling the page when the pointer is over the canvas should zoom the camera but not scroll the page. The page should only be scrolled when the pointer is not over the canvas.

**Comment by deltakosh** [comment]
Please use the forum for question: forum.babylonjd.com

Your issue is probably coming from the fact that you need to add touch-action=none on the canvas element to preventDefault.

Please continue this discussion on the forum as this will be helpful for others as well

**Comment by AmirMehr** [comment]
I write in in jQuery and this solved the problem
                
              ```
  $("body").on("wheel mousewheel", "#renderCanvas, #roomHeight, #roomLong", function () {
                    e.preventDefault();
                });
```
