### ISSUE TITLE
Issues with Physics Engine Plugins Consitency 

### ISSUE THREAD

**Issue by BabylonJSGuide** [BabylonJS/Babylon.js#5736]
Cross reference [documentation PR #1364](https://github.com/BabylonJS/Documentation/pull/1364)

Differences between the behavior of the three plugins are 

1. For Cannon.js for a cylinder imposter you need to swap the y and z values in the mainAxis vector only, for axis of rotation to be consistent with Oimo and Ammo 
* [Playground Example Cannon.js  v4.0.0 now gives error](https://www.babylonjs-playground.com/#F15U0G#35)
* [Playground Example Cannon.js  v3.3.0](https://www.babylonjs-playground.com/indexStable.html#F15U0G#35)
* [Playground Example Oimo.js v4.0.0](https://www.babylonjs-playground.com/#F15U0G#36)
* [Playground Example Ammo.js v 4.0.0](https://www.babylonjs-playground.com/#F15U0G#37)

2. Oimo requires both parameters in setMotor and values must be much larger than in Cannon and Ammo - can be seen in above PGs

3. Compound bodies 

If your replace the plugin with CannonJSPlugin in the method used in the following two PGs the method does not work for Cannon
* [Playground Example - Ammo - Skull as a Compound Body](https://www.babylonjs-playground.com/#492ZK0#1)
* [Playground Example - Oimo - Skull as a Compound Body](https://www.babylonjs-playground.com/#492ZK0#2)

This method does for all three
* [Playground Example - Cannon - Skull as a Compound Body](https://www.babylonjs-playground.com/#492ZK0#3)
* [Playground Example - Ammo - Skull as a Compound Body](https://www.babylonjs-playground.com/#492ZK0#5)
* [Playground Example - Oimo - Skull as a Compound Body](https://www.babylonjs-playground.com/#492ZK0#6)

Creating consistency would require breaking changes.

**Comment by deltakosh** [comment]
For breaking changes, as long as they are documented in the what's new and not to important

**Comment by BabylonJSGuide** [comment]
Expaninding on issue 1 Cannon PG example for V4.0.0

@TrevorDev The issue (I think) with cylinderImpostor not working in 4.0.0 alpha 18 is in  CannonJSPlugin.ts lines 271 to 279

```
//TMP also for cylinder - TODO Cannon supports cylinder natively.
case PhysicsImpostor.CylinderImpostor:
    let nativeParams = impostor.getParam("nativeOptions");
    let radiusTop = nativeParams.radiusTop !== undefined ? nativeParams.radiusTop : this._checkWithEpsilon(extendSize.x) / 2;
    let radiusBottom = nativeParams.radiusBottom !== undefined ? nativeParams.radiusBottom : this._checkWithEpsilon(extendSize.x) / 2;
    let height = nativeParams.height !== undefined ? nativeParams.height : this._checkWithEpsilon(extendSize.y) / 2;
    let numSegments = nativeParams.numSegments !== undefined ? nativeParams.numSegments : 16;
    returnValue = new this.BJSCANNON.Cylinder(radiusTop, radiusBottom, height, numSegments);
    break;
```
Since nativeParams is itself undefined the interpreter find an error before reading the properties such as radiusTop etc. This can be overcome by adding `nativeParams !== undefined && ` to each of these lines

```
//TMP also for cylinder - TODO Cannon supports cylinder natively.
case PhysicsImpostor.CylinderImpostor:
    let nativeParams = impostor.getParam("nativeOptions");
    let radiusTop = nativeParams !== undefined && nativeParams.radiusTop !== undefined ? nativeParams.radiusTop : this._checkWithEpsilon(extendSize.x) / 2;
    let radiusBottom = nativeParams !== undefined && nativeParams.radiusBottom !== undefined ? nativeParams.radiusBottom : this._checkWithEpsilon(extendSize.x) / 2;
    let height = nativeParams !== undefined && nativeParams.height !== undefined ? nativeParams.height : this._checkWithEpsilon(extendSize.y) / 2;
    let numSegments = nativeParams !== undefined && nativeParams.numSegments !== undefined ? nativeParams.numSegments : 16;
    returnValue = new this.BJSCANNON.Cylinder(radiusTop, radiusBottom, height, numSegments);
    break;
```

This might not be the best way.  Interestingly although nativeOptions are part of `export interface PhysicsImpostorParameters` this appears to be the first time they have ever been referenced with a plugin

An alternative could be

```
//TMP also for cylinder - TODO Cannon supports cylinder natively.
case PhysicsImpostor.CylinderImpostor:
    let nativeParams = impostor.getParam("nativeOptions");
    if( nativeParams === undefined) {
        nativeParams = null;
    }
    let radiusTop = nativeParams.radiusTop !== undefined ? nativeParams.radiusTop : this._checkWithEpsilon(extendSize.x) / 2;
    let radiusBottom = nativeParams.radiusBottom !== undefined ? nativeParams.radiusBottom : this._checkWithEpsilon(extendSize.x) / 2;
    let height = nativeParams.height !== undefined ? nativeParams.height : this._checkWithEpsilon(extendSize.y) / 2;
    let numSegments = nativeParams.numSegments !== undefined ? nativeParams.numSegments : 16;
    returnValue = new this.BJSCANNON.Cylinder(radiusTop, radiusBottom, height, numSegments);
    break;
```
 
I will let you consider the range of possibilities.

**Comment by TrevorDev** [comment]
Thx, yea I think we came to similar conclusions for that 👍 . I also found the reason why cylinder's axis is not right because cannons cylinder is default sideways and the way its currently being corrected messes with the axis's, I found an alternative that fixes that aswell.

**Comment by BabylonJSGuide** [comment]
👍

**Comment by TrevorDev** [comment]
With these fixes, the playgrounds linked now seem to behave consistently 🤞. Thanks for all the work you've done. Let me know if these or any other scenario you had looks broken once these changes merge.
