### ISSUE TITLE
Add screen coverage LOD support

### ISSUE THREAD

**Issue by bghgary** [BabylonJS/Babylon.js#5738]
See https://forum.babylonjs.com/t/switch-lod-by-screen-coverage/388.

**Comment by MackeyK24** [comment]
Yo @deltakosh ... Do you think we can get this going... PLEASE :)

**Comment by deltakosh** [comment]
Not for now. We are in code lock for 4.0

**Comment by UXVirtual** [comment]
Has there been any movement on this functionality now that 4.0 has been released? We're looking at using this to help us with optimising larger interior scenes.

**Comment by deltakosh** [comment]
It is not on 4.1 roadmap so far unless someone from the community wants to tackle it

**Comment by UXVirtual** [comment]
No problem - we may do a PR for this functionality at a later date.

**Comment by deltakosh** [comment]
It would be HIGHLY appreciated ;)

**Comment by MackeyK24** [comment]
I’m with @deltakosk ... it would be freaking awesome if you  make PR for screen coverage LOD

**Comment by lguminski** [comment]
As a follow-up to a related [conversation](https://forum.babylonjs.com/t/levels-of-detail-lod-support-for-scaled-meshes/19866/5?u=lguminski), I would like to add that _screen coverage_ does not necessarily need to be the only LoD strategy. One could think of others like:

- distance from the screen center (the closer to screen edges the less detail)
- exposure to light (the darker the less detail)
- and obviously the frame rate (the lower fps the less detail)

I am leaving this here as food for thought. Perhaps one day BabylonJS could offer a selection of strategies to choose from.

**Comment by deltakosh** [comment]
Any news @CraigFeldspar ?

**Comment by CraigFeldspar** [comment]
Ha, it's already done with #10509 😄 @deltakosh

**Comment by deltakosh** [comment]
I wanted to be sure :D
