### ISSUE TITLE
babylon.2.1.d.ts issues

### ISSUE THREAD

**Issue by Palmer-JC** [BabylonJS/Babylon.js#574]
Starting to migrate systems to 2.1.  Replaced babylon.2.0.d.ts with babylon.2.1.d.ts.  Things still compile, but fear it is only because not using something new in 2.1 yet.  FYI, waa.d.ts was and is still also required.

The problem seems to be duplicate camera definitions.  I have commented out lines 1787 - 1806, but not going to PR, unless requested.  This is a generated file, so should also check 2.2 is not generating these as well.

**Comment by deltakosh** [comment]
This is because you are using TS 1.5-beta.

**Comment by deltakosh** [comment]
Or perhaps I have a bug:) I'll check

**Comment by RaananW** [comment]
This file https://github.com/BabylonJS/Babylon.js/blob/master/Babylon/Cameras/babylon.anaglyphCamera.js didn't have his corresponding ts file. Looks like it was removed. Maybe the ts file still exists in the file system where the framework was last compiled?

**Comment by deltakosh** [comment]
Absolutely right..this is fixed now :)
