### ISSUE TITLE
Semantic error TS2322 Type 'GridMaterial' is not assignable to type 'Material'.

### ISSUE THREAD

**Issue by pascalbayer** [BabylonJS/Babylon.js#5748]
Semantic error TS2322 Type 'GridMaterial' is not assignable to type 'Material'. Property 'id' is missing in type 'GridMaterial'.

BabylonJS version: 4.0.0-alpha.18

That's just one of the examples which are caused by the new module.d.ts for `babylonjs-loaders` and `babylonjs-materials` as they cannot resolve the imports.

```
declare module "babylonjs-materials/grid/gridMaterial" {
    import { Color3, Vector3, Matrix } from "babylonjs/Maths/math";
    import { BaseTexture } from "babylonjs/Materials/Textures/baseTexture";
    import { PushMaterial } from "babylonjs/Materials/pushMaterial";
    import { AbstractMesh } from "babylonjs/Meshes/abstractMesh";
    import { SubMesh } from "babylonjs/Meshes/subMesh";
    import { Mesh } from "babylonjs/Meshes/mesh";
    import { Scene } from "babylonjs/scene";
    import "babylonjs-materials/grid/grid.fragment";
    import "babylonjs-materials/grid/grid.vertex";
    ...
```

Changing the imports in the type definitions to the following would resolve these issues:
```
declare module "babylonjs-materials/grid/gridMaterial" {
    import { Color3, Vector3, Matrix, BaseTexture, PushMaterial, AbstractMesh, SubMesh, Mesh, Scene } from "babylonjs";
    import "babylonjs-materials/grid/grid.fragment";
    import "babylonjs-materials/grid/grid.vertex";
    ...
```

I guess that can be solved with an override at build time while generating the typedefs. Let me know if I can support on that issue.

**Comment by sebavan** [comment]
Thanks for reporting, it has been fixed by : https://github.com/BabylonJS/Babylon.js/pull/5746

It will be deployed in alpha 19 today,
