### ISSUE TITLE
MeshBuilder.CreatePolygon and PolygonMeshBuilder API is inconsistent

### ISSUE THREAD

**Issue by kutomer** [BabylonJS/Babylon.js#5749]
Hello,
I'm migrating not from `babylonjs@3.3.0` to `@babylonjs/core@4.0.0-alpha.18` to try out the new and long waited tree shaking! (@sebavan 👑)

And getting the following error: `ReferenceError: earcut is not defined at new PolygonMeshBuilder`.

This is because `MeshBuilder.CreatePolygon` API doesn't support earcut injection:
Babylon.js/src/Meshes/meshBuilder.ts:
![screen shot 2019-01-14 at 16 22 21](https://user-images.githubusercontent.com/3729904/51118365-deef0980-1818-11e9-89ad-3321918829b6.png)

![screen shot 2019-01-14 at 16 24 14](https://user-images.githubusercontent.com/3729904/51118369-e2829080-1818-11e9-87b8-45806e8b07c7.png)

Help will be very much appreciated,
Tomer.

**Comment by kutomer** [comment]
I'm using [next.js](https://nextjs.org) and wouldn't want all my pages to include `earcut` for no reason.

Furthermore, I'm trying to ignore global dependencies as much as possible, I have only one call to `MeshBuilder.CreatePolygon` and if I will ever decide to remove it I think it will be much more obvious that `earcut` is no longer needed compering to global dependency.

Thanks again for your work!

**Comment by sebavan** [comment]
Sweet that is a nice reason for the doc. You ll have it in the next version.

**Comment by kutomer** [comment]
Thanks a lot.

If anyone struggling with the same issue here is a temporary solution you can use:
```
  const earcut = require('earcut');
  (window as any).earcut = earcut;
  const mesh = MeshBuilder.CreatePolygon(...);
```

**Comment by deltakosh** [comment]
Fixed!

**Comment by Fusseldieb** [comment]
> Thanks a lot.
> 
> If anyone struggling with the same issue here is a temporary solution you can use:
> 
> ```
>   const earcut = require('earcut');
>   (window as any).earcut = earcut;
>   const mesh = MeshBuilder.CreatePolygon(...);
> ```

Not a nice solution, but I can say that it works...

Using Electron & Webpack & Vue. I've put it into the `main.js`
Afaik, earcut will be injected globally (into window), which isn't nice considering that the principle of SFC's are broken this way.

**Comment by kutomer** [comment]
> > ```
> >   const earcut = require('earcut');
> >   window.earcut = earcut;
> > ```
> 
> Not a nice solution, but I can say that it works...
> 
> Using Electron & Webpack & Vue. I've put it into `main.js`
> Afaik, earcut will be injected globally (into window), which isn't nice considering that the principle of SFC's are broken this way.
> 
> ... But it works

@Fusseldieb, This was a temporary solution I used until @deltakosh solution, you can inject earcut into CreatePolygon, so there is no real reason to manually referance the global scope:
```
const mesh = MeshBuilder.CreatePolygon("name", { // ... }, scene, require('earcut'));
```

I'm using `@babylonjs/core@4.0.0` and it's working.

**Comment by hiteshsahu** [comment]
Add Earcut as dependency in your index HTML

<script src="https://preview.babylonjs.com/earcut.min.js"></script>

**Comment by kutomer** [comment]
> I'm using [next.js](https://nextjs.org) and wouldn't want all my pages to include `earcut` for no reason.
> 
> Furthermore, I'm trying to ignore global dependencies as much as possible, I have only one call to `MeshBuilder.CreatePolygon` and if I will ever decide to remove it I think it will be much more obvious that `earcut` is no longer needed compering to global dependency.
> 
> Thanks again for your work!

@hiteshsahu see this reply why I think injecting earcut it s better solution than add it as a global dependency. (your solution even bypass webpack which is even worse cause now earcut is not part of the bundle)
But do whatever works for you :)

**Comment by treedbox** [comment]
With Webpack , install earcut via npm:
`npm i --save-dev earcut`

Then in your **.ts** or **.js** file:
```
import earcut from "earcut";

const mesh = MeshBuilder.CreatePolygon(name, options, scene, earcut)
```
In the documentation you can see that after scene, the next optional parameter is **earcutInjection**, _this is the way._
https://doc.babylonjs.com/api/classes/babylon.meshbuilder#createpolygon
