### ISSUE TITLE
Gizmo rendering on the wrong viewport in babylonjs-4.0.0-alpha.13+

### ISSUE THREAD

**Issue by pascalbayer** [BabylonJS/Babylon.js#5750]
I've noticed some broken unit tests on our project this morning regarding the rendering of the gizmo controls and the multi-viewport setup. It seems like the camera selection in which viewport to render the gizmo has changed between babylonjs-4.0.0-alpha.12 to babylonjs-4.0.0-alpha.13 and doesn't work as it did before.

We set the `scene.activeCameras` whenever the cursor enters a new viewport as shown in https://www.babylonjs-playground.com/#E9IRIF#17:
```
scene.onPointerObservable.add((pointerInfo) => {
    const height = scene.getEngine().getRenderHeight();
    const scale = scene.getEngine().getHardwareScalingLevel();

    if (scene.pointerY > height / 2) {
        scene.activeCameras[0] = camera1;
        scene.activeCameras[1] = camera2;
    } else {
        scene.activeCameras[0] = camera2;
        scene.activeCameras[1] = camera1;
    }
});
```

- **Bug repro on [playground](https://playground.babylonjs.com):** https://www.babylonjs-playground.com/#E9IRIF#17
- **Expected result:** The gizmo should be rendered on the currently active viewport/camera as it does with the latest stable version: https://www.babylonjs-playground.com/indexStable.html#E9IRIF#17
- **Current result:** The gizmo is rendered on the inactive viewport/camera: https://www.babylonjs-playground.com/#E9IRIF#17

A different possible solution would be also to render the gizmo in all viewports instead of just the active one or a setting to decide between these two modes.

**Comment by TrevorDev** [comment]
Thanks for reporting the behavior change, when handling multiple activeCameras it was choosing the first instead of the last.

**Comment by pascalbayer** [comment]
Tests are green again and it's all working again, thank you!
