### ISSUE TITLE
GUI ScrollBar not exported properly

### ISSUE THREAD

**Issue by pjoe** [BabylonJS/Babylon.js#5765]
I think ScrollBar is missing here: https://github.com/BabylonJS/Babylon.js/blob/master/gui/src/2D/controls/index.ts#L23

- Bug repro https://playground.babylonjs.com/#KS931X
- Expected result: No errors
- Current result: Line 11:21 - BABYLON.GUI.ScrollBar is not a constructor

**Comment by sebavan** [comment]
Thanks a lot you are totally right Fixed: https://github.com/BabylonJS/Babylon.js/pull/5767/files
