### ISSUE TITLE
Object moves on the wrong plane when using useObjectOrientationForDragging

### ISSUE THREAD

**Issue by haroldma** [BabylonJS/Babylon.js#5783]
## Repro:
[Playground.](https://www.babylonjs-playground.com/#9UFEBE#35)

Drag the object left and right rapidly.

## Cause:
If you update the rotation of the object it will cause the drag plane to be incorrect.

We do want to use the rotation of the object and we want to update the plane on every frame. It works as expected unless you drag left and right rapidly.

**Comment by TrevorDev** [comment]
@haroldma I think this is expected, rotating the object like this will introduce error in your desired drag path as the drag plane is always flat therefore, for large movements between frames, it will be dragged along the flat plane. 

Is your goal to drag the object around a cylinder? If that is the case you could try to snap the object to the closest point on the cylinder when a drag event occurs, or disabled auto dragging and handle drag events yourself to snap the position of the sphere based on your own function.

**Comment by haroldma** [comment]
Here's the [PG](https://www.babylonjs-playground.com/#9UFEBE#36)

Keep dragging left and right and after a while, it starts acting weird.

If you remove this `pointerDragBehavior._targetPosition.addInPlace(snapDiff);` it will just start shaking like crazy after a bit instead.

**Comment by TrevorDev** [comment]
Gotcha, it looks like the drag plane is not properly being updated, looking into it.

**Comment by TrevorDev** [comment]
This playground should work after that gets merged http://playground.babylonjs.com#9UFEBE#37, let me know if you still have issues with your scenario.
