### ISSUE TITLE
Playground search not very discoverable

### ISSUE THREAD

**Issue by kcoley** [BabylonJS/Babylon.js#5793]
The playground search can be found by clicking on the search button on the bottom of a playground:
<img width="966" alt="playground_search_bar" src="https://user-images.githubusercontent.com/3946928/51404195-8913ad80-1b07-11e9-85b9-d9c146443877.png">

Or by navigating to the Babylon.js website, clicking on the "Documentation" Link and then clicking the Playground button on the top menu bar.

However, both methods are not very discoverable.  Is it possible to make this feature easier for users to find?

**Comment by deltakosh** [comment]
Will be in the website rework
