### ISSUE TITLE
GUI Button doesn't notify pointer out observable for texture mode ADT

### ISSUE THREAD

**Issue by nbduke** [BabylonJS/Babylon.js#5806]
# Bugs

Repro playground: https://www.babylonjs-playground.com/#XCPP9Y#868

If you run that playground with the browser debugger console open, you'll see that the pointer in observable is notified but never the pointer out observable. I do not see this issue when I create the AdvancedDynamicTexture in full-screen mode.

**Comment by deltakosh** [comment]
I'm on it :)
