### ISSUE TITLE
Loader loads related files at different top path instead of same path

### ISSUE THREAD

**Issue by GrosSacASac** [BabylonJS/Babylon.js#5820]
# Bug

when using BABYLON.SceneLoader.Load("", "./3d/home.gltf", engine, function (scene) {
the associated files are loaded from ./grid.png and ./home.bin
instead of  ./3d/grid.png and ./3d/home.bin

- Bug repro on

https://gitlab.com/GrosSacASac/home-sweet-home/commit/1ffc0e415d90c44f3c5e51d83d8d0cc0620b7cbf 
(404)
and temporary fix on next commit
https://gitlab.com/GrosSacASac/home-sweet-home/commit/d9b631f0a31d1a393df63498c928dd804f180600

to open in browser npm i
 and npm run serve
then open 
http://localhost:5000/client/test

- Expected result:
loads from same path
- Current result:
loads from different path

From the game jam, so we may give more details later

**Comment by GrosSacASac** [comment]
Not sure if bug but it was unexpected

**Comment by bghgary** [comment]
This is the expected behavior since the first parameter `rootUrl` is empty string. Either pass the full path to the first parameter or split them such that "./3d/" is the first parameter and "home.gltf" is the second parameter.

**Comment by GrosSacASac** [comment]
I see thanks
