### ISSUE TITLE
createDefaultEnvironment skybox top is bottom

### ISSUE THREAD

**Issue by polarber** [BabylonJS/Babylon.js#5824]
The images used for a Skybox are not in the correct order (top is bottom) when used with createDefaultEnvironment: 

https://www.babylonjs-playground.com/#ZTIX9X

scroll out to see the sky as ground.

   var options = {
        skyboxTexture: new BABYLON.CubeTexture("textures/TropicalSunnyDay", scene),
        groundColor: BABYLON.Color3.White()
    };

    let env = scene.createDefaultEnvironment(options);

**Comment by sebavan** [comment]
This is expected as you did not set the correct mode on the texture: skyboxTexture.coordinatesMode = BABYLON.Texture.SKYBOX_MODE;

When you provide the texture, we expect it to be set to your need as we can not infer what type of projection is in.

https://www.babylonjs-playground.com/#ZTIX9X#1

**Comment by polarber** [comment]
TX, this solved the issue. For a newbie like me it would be easier if this could be set as default when I use the option skyboxTexture in createDefaultEnvironment. Or is my assumption wrong that using the skyboxTexture option will have the texture in SKYBOX_MODE in most of the cases.

**Comment by sebavan** [comment]
In case of default, you can simply pass the url: https://www.babylonjs-playground.com/#ZTIX9X#2

If you pass the texture, we expect some custom config hence the need of configuring it yourself.

Hope that makes sense
