### ISSUE TITLE
There's no way to update the bounding gizmo's color after creation

### ISSUE THREAD

**Issue by haroldma** [BabylonJS/Babylon.js#5839]

**Comment by TrevorDev** [comment]
Would adding a setColor function to the BoundingBoxGizmo that works the same way the color paramter in the constructor works solve this? Or are you looking for additional color settings?

**Comment by haroldma** [comment]
A `setColor` will definitely do the trick!

**Comment by TrevorDev** [comment]
This pg should work now: https://playground.babylonjs.com/#N36WU1
Let me know if you have issues.
