### ISSUE TITLE
Blending vertex color & diffuse texture

### ISSUE THREAD

**Issue by jahow** [BabylonJS/Babylon.js#584]
Currently the diffuse texture overrides the vertex color:
https://github.com/BabylonJS/Babylon.js/blob/master/src/Shaders/default.fragment.fx#L507

Would it be possible to change it so that the two blend nicely (multiply) together?

**Comment by RaananW** [comment]
If vertexColor == DiffuseColor, moving lines 502-504 (https://github.com/BabylonJS/Babylon.js/blob/master/src/Shaders/default.fragment.fx#L502) a few lines to 508 will create exactly what you needed. I assume :) But as I am not a shader expert, i'll wait for DK. Needs to also check if DIFFUSE is set when vertexColor exists.

**Comment by jahow** [comment]
Yep, putting the _vertex color_ code after the _diffuse_ code seems like the best way to go.
I'm also submitting this as an issue so that DK can confirm whether this was made like that for design reasons or not!

**Comment by deltakosh** [comment]
This is by design. I need to check if this is not a problem with existing scenes. I keep you posted

**Comment by jahow** [comment]
Great, thanks!

**Comment by jahow** [comment]
You rock.
