### ISSUE TITLE
Unexpected behavior for z-up right-handed coordinate system

### ISSUE THREAD

**Issue by pascalbayer** [BabylonJS/Babylon.js#5843]
I currently try to understand how right-handed z-up works in Babylon as almost all of our 3d-data works in that coordinate system due to the fact that we have to synchronize it between multiple renderers. I noticed a few inconsistencies while playing around but maybe that's just missing understanding of the internals.

**Observations (while using z-up and right-handed):**
- Camera position/target needs to be provided in Y-Up?
- Mesh position coordinates will be handled in Z-Up?
- Mesh.CreateGround works in Y-Up

**Info:**
- Bug repro on: https://playground.babylonjs.com/#YUT9UZ#2
- Expected result: After changing to right-handed and z-up I expect everything to work with the z-up coordinate space
- Current result: it's a mix of both modes

**Comment by deltakosh** [comment]
Please use the forum for questions; forum.babylonjs.com
