### ISSUE TITLE
OBJFileLoader does not exist on babylonjs

### ISSUE THREAD

**Issue by flyfj** [BabylonJS/Babylon.js#5857]
i'm using 4.0.0-alpha.22 for babylonjs and babylonjs-loaders. 

It works for loading obj from a file but when I'm trying to access BABYLON.OBJFileLoader.COMPUTE_NORMALS, i got an error indicating 'OBJFileLoader' does not exist on type 'typeof import('babylonjs)'. Seems like it's not properly exported, been following the instructions and not sure how to fix this. 

Much appreciated for any help.

**Comment by sebavan** [comment]
Hello, are you using namespaces or  modules in your code (it looks like you have a mix) ?

**Comment by flyfj** [comment]
Thanks for your reply. I think i followed the online doc for each sublibrary and this is what i did in my code (angular7 component):
`
import * as BABYLON from 'babylonjs';
import 'babylonjs-loaders';
import 'babylonjs-materials';
`

**Comment by sebavan** [comment]
Let me try locally and I ll come back to you.

**Comment by sebavan** [comment]
So it is normal cause the when you import not using the namespace (which is the good way to go), you can only use the types included in the import. 

The ObjFileLoader is part of loaders and not babylonjs.

You can slighty modify your imports like this:
import * as BABYLON from 'babylonjs'; 
import { OBJFileLoader } from 'babylonjs-loaders';
import 'babylonjs-materials';

OBJFileLoader.COMPUTE_NORMALS;

**Comment by sebavan** [comment]
Let me know if that works :-)

**Comment by flyfj** [comment]
Thank you for the suggestion. Unfortunately, it doesn't seem to work. When I import like you suggested, i got error like 'SyntaxError: Unexpected token v in JSON at position 0' and couldn't load the obj file.

**Comment by sebavan** [comment]
I ll go back over the doc ASAP and it might be a side effect of the es6 works. I will also check why it would work with materials.
