### ISSUE TITLE
PhotoDome confuse InvertY

### ISSUE THREAD

**Issue by mizar** [BabylonJS/Babylon.js#5868]
# Bugs

If that image is already in use, there are cases where `BABYLON.PhotoDome` wrongly turns upside down.

playground: https://www.babylonjs-playground.com/#14KRGG#54

original playground: https://www.babylonjs-playground.com/#14KRGG#3

**Comment by deltakosh** [comment]
Thanks for reporting it!

**Comment by mizar** [comment]
Is this the correct behavior when InvertY is undefined?

**Comment by deltakosh** [comment]
yep this is expected

**Comment by mizar** [comment]
Oh… I'll take care.
