### ISSUE TITLE
Transparent mesh sorting broken if camera is parented

### ISSUE THREAD

**Issue by andyhall** [BabylonJS/Babylon.js#587]
I believe the fix is to change [this line](https://github.com/BabylonJS/Babylon.js/blob/master/src/Rendering/babylon.renderingGroup.ts#L48) from 
`this._scene.activeCamera.position`
 to 
`this._scene.activeCamera.globalPosition`.

**Comment by deltakosh** [comment]
Correct! I'll fix it
