### ISSUE TITLE
Add Support For Compute Shader

### ISSUE THREAD

**Issue by sebavan** [BabylonJS/Babylon.js#5873]
Following the current state of the extension: https://docs.google.com/document/d/1EwhDJO_lBH1mGMMwheQUXGhhFk9yoC98Ant3TPqwmmA/view

https://groups.google.com/a/chromium.org/forum/#!msg/blink-dev/bPD47wqY-r8/5DzgvEwFBAAJ

As it is available in Canary under a flag, It looks like we could start with the implementation :-)

@deltakosh I know you love it so this one is definitely for your coding time :-)

**Comment by deltakosh** [comment]
Closing as WebGPU Compute shader will make more sense
