### ISSUE TITLE
Missing skeletonId

### ISSUE THREAD

**Issue by jackcaron** [BabylonJS/Babylon.js#588]
https://www.dropbox.com/s/fnowo1f22t7hezk/anim.blend?dl=0

In this file, there's a simple bone animation. But in the Cylinder mesh, the skeletonId is missing. Therefore, when loading the mesh with ImportMesh, there's no skeletons.

**Comment by jackcaron** [comment]
Also, once I put the skeletonId in the mesh, in the babylon file itself, the skeleton loads with "ImportMesh", but it's impossible to get the animation to start.

```javascript
    BABYLON.SceneLoader.ImportMesh("", "assets/", "anim.babylon", newScene, function(newMeshes, particleSystems, skeletons) {
      newScene.beginAnimation(newMeshes[0].skeleton, 0, 200, true, 1.0);
      engine.runRenderLoop(function() {
        newScene.render();
      });
    });
```

**Comment by deltakosh** [comment]
Pulling @Palmer-JC in:)

**Comment by Palmer-JC** [comment]
I ran it thru TOB exporter.  Almost the same, except since it generate readable source code, it is much easy to view than a .babylon.

No matricesWeights or matricesIndices are also not in the cylinder object.  This is because the parent of the cylinder is not the armature

**Comment by Palmer-JC** [comment]
Parented, and matricesWeights / matricesIndices both generated.  

- Right click cylinder
- Shift right click skeleton
- <cntrl-p>, then select Object from menu

**Comment by jackcaron** [comment]
@Palmer-JC I put the cylinder as the child of the armature (not very practical if the cylinder was already the child of another node) and it worked for exporting the skeleton. But the animation in Babylon is totally broken. The weights are not properly exported.

**Comment by Palmer-JC** [comment]
This is better on the discussion forum.  Another ID to get yes, but there are also other Blender people with no Github account there.
http://www.html5gamedevs.com/forum/16-babylonjs/
