### ISSUE TITLE
Custom Headers not working for TextureTask and ImageTask

### ISSUE THREAD

**Issue by thomasaull** [BabylonJS/Babylon.js#5888]
Bug repro on: https://www.babylonjs-playground.com/#RI9L29#2

**Expected result:**
The Assets Manager should inject the custom headers for all tasks

**Current result:**
When using `assetsManager.addCubeTextureTask` my custom authorization header is there:
![2019-02-09 at 13 15](https://user-images.githubusercontent.com/227756/52520701-ca156280-2c6c-11e9-956e-c2aa13f1b113.jpg)

With `assetsManager.addTextureTask` or `assetsManager.addImageTask` the custom authorization header is missing:
<img width="625" alt="grafik" src="https://user-images.githubusercontent.com/227756/52520707-e0bbb980-2c6c-11e9-9d62-6313bd3a3c5d.png">

**Comment by deltakosh** [comment]
Ok I'll have a look asap

**Comment by deltakosh** [comment]
Unfortunately this is a limitation of HTML. We cannot change the header of img tag (which are used to load images).
https://stackoverflow.com/questions/27000152/set-custom-header-for-the-request-made-from-img-tag

Based on the answer above, you can load the image uxing a xhr and then set the source URL to a blob in the Assets Manager

**Comment by thomasaull** [comment]
Thanks @deltakosh for the fast help. I got it working using `addBinaryFileTask` like this, which works aswell:
```
let textureTask = assetsManager.addBinaryFileTask(
  'imageTask',
  `my-file.jpg`
)

textureTask.onSuccess = task => {
  const texture = BABYLON.Texture.LoadFromDataString(
    'example',
    task.data,
    scene
  )
}
```
