### ISSUE TITLE
SpotLight shadows not generated when direction.x and direction.z are 0.0

### ISSUE THREAD

**Issue by SuperUserNameMan** [BabylonJS/Babylon.js#589]
Hi, 

If you set the SpotLight direction to (0.0, -1.0, 0.0), shadows are not generated :
http://babylonjs-playground.azurewebsites.net/#1UVX5K#1

With (0.0, -1.0, 0.0000000000001) this works :
http://babylonjs-playground.azurewebsites.net/#1UVX5K#2

**Comment by deltakosh** [comment]
Yep this is a known limitation when light is perfectly perpendicular to the receiving plane

**Comment by SuperUserNameMan** [comment]
From my naive point of view, this limitation seems easy to detect and to overcome by adding a tiny random vector to the direction.
What would prevent such mechanism to be added to the engine to free it from this limitation ?

**Comment by deltakosh** [comment]
Unfortunately what if your random generates a perfect perpendicular? And by the way I do not want to add randomness in the behavior :)

**Comment by deltakosh** [comment]
Reopening in order to find a fix
