### ISSUE TITLE
gltf ziploader, how to add scene using blob

### ISSUE THREAD

**Issue by huxiao5579144** [BabylonJS/Babylon.js#5896]
`  //my code
    //using jszip.min.js
    //using ziploader.js
    //using babylon.max.js

    var url = `"/3dmax/gltf/obj.zip";` //gltf file 180mb after compression 33mb ,i need this

    //xhr zip & progress
    var manager = new LoadingManager();

    new Promise(function (resolve, reject) {
        if (url.match(/\.zip$/)) {
            new ZipLoader().load(url).then(function (zip) {
                manager.setURLModifier(zip.urlResolver);
                resolve(zip.find(/\.(gltf|glb)$/i));
            });
        } else {
            resolve(url);
        }
    }).then(function (files) {
        //zip has been downloaded to the client
        //files[0] blob:/3dmax/gltf/demo1.gltf
        // Now this wrong, how to add scene using blob
        BABYLON.SceneLoader.Load(files[0], ....);
        // im trying to using GLFTLoader but error too. help me
    });`

**Comment by deltakosh** [comment]
Please use our forum for questions 
Https://forum.babylonjs com
