### ISSUE TITLE
glTF: files with no scenes give "/scene: Failed to find index (0)"

### ISSUE THREAD

**Issue by scurest** [BabylonJS/Babylon.js#5900]
In the sandbox, dropping a glTF without a `scenes` property gives "/scene: Failed to find index (0)".

![error](https://user-images.githubusercontent.com/11024420/52590175-4becc380-2e06-11e9-951d-0b7c30b0883f.png)

**Comment by bghgary** [comment]
This currently by design. What behavior do you expect if there is no scene provided? Note that you should be able to use ImportMesh and specify the nodes to load when no `scene` is defined.

https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/README.md#scenes

**Comment by bghgary** [comment]
Sorry for the deleted message. I misread the message. Can I ask what you expect the loader to do if there are no scenes defined?

**Comment by scurest** [comment]
I think the obvious thing to do is to show everything. The spec doesn't require you show anything at all of course.

**Comment by bghgary** [comment]
Is `scene` defined in the glTF? If it is, then the error is correct. If it isn't, I am inclined to load nothing as there is nothing to load.

**Comment by scurest** [comment]
`scene` is not defined in the glTF. The glTF is valid.

**Comment by bghgary** [comment]
Okay, do you have a specific case for this? I think the proper result is for the loader to do nothing.

**Comment by scurest** [comment]
No, I could always view such a model some other way. I don't think there should be an error message for a valid file though.

**Comment by bghgary** [comment]
> I don't think there should be an error message for a valid file though.

Yes, agreed. I will fix it.

**Comment by bghgary** [comment]
I opened a PR with the fix. Note that the default camera will end up with some odd values because there is no meshes in the scene. We possibly should do something about that as well in a separate PR.

Thanks for the report @scurest!
