### ISSUE TITLE
Mesh._GetDefaultSideOrientation overly verbose

### ISSUE THREAD

**Issue by thscott** [BabylonJS/Babylon.js#5902]
I was looking through the mesh builder methods and came across [Mesh._GetDefaultSideOrientation](https://github.com/BabylonJS/Babylon.js/blob/b5d38050a02179b76004387368344ffb9a8469c4/src/Meshes/mesh.ts#L142).
Unless I'm missing something, or there are plans for something more in the future, it could be entirely rewritten as:
```typescript
public static _GetDefaultSideOrientation(orientation?: number): number {
    return orientation || Mesh.FRONTSIDE; // works as Mesh.FRONTSIDE is 0
}
```
or indeed could just be replaced in all the builder methods with just that expression.

This seems to be what the VertexData methods are doing (though they use VertexData.DEFAULTSIDE, after checking for FRONTSIDE). 

This raises another question though, what's the point in the Mesh and VertexData DEFAULTSIDE properties, seeing as they are marked as read only? Even if they weren't read only, I can't really think of a use case for them.

**Comment by deltakosh** [comment]
DEFAULTSIDE is just here to make the code more readable ;)

and you are totally right for the code optimization for GetDefaultSideOrientation. Fancy doing a PR?

**Comment by thscott** [comment]
I can do pr, would you rather just the function changed, or the function be removed entirely and just replaced with the expression?

I'm not sure I understand how DEFAULTSIDE is more readable than just using FRONTSIDE everywhere it occurs though.

**Comment by deltakosh** [comment]
Please just change the function as we do not know how siding can work in the future (real dual side? etc..)

Yes DEFAULTSIDE is not more readable but it comes from a age where FRONTSIDE was not even defined (and thus we keep it for back compat and also because as I mentioned earlier this could evolve in the future as we are adding more support to scene.useRightHanded for instance)
