### ISSUE TITLE
Mac-only: after context menu dismisses, camera keeps panning

### ISSUE THREAD

**Issue by mattdmorgan** [BabylonJS/Babylon.js#5908]
1. Launch the default playground on the Mac (https://playground.babylonjs.com).
2. Right-click in the scene. (Context menu appears, as expected.)
3. Left-click outside the context menu to dismiss it (or hit Esc).
4. Move the mouse.

Result: camera pans as though the mouse button were still down.
Expect: no panning.

This is likely because, on the Mac, context menus display immediately on mousedown, instead of after mouseup. Presumably the context menu then steals the mouseup, and Babylon never sees it.

Reproes in Chrome 71.0.3578.98 and Safari 12.0.3 on the Mac. Doesn't repro on Windows.

**Comment by deltakosh** [comment]
Do you have an idea on how to fix that?

**Comment by FreakTheMighty** [comment]
@mattdmorgan @sebavan I've seen this issue with the arc camera as well.

My first thought was that the control button is a poor choice for panning on control on the mac, though I disabling the context menu is an OK fix as well.
