### ISSUE TITLE
ArcRotateCamer rotataion doesn't work with Babylon v > 2.0.1 and Chrome 45

### ISSUE THREAD

**Issue by KevinBLT** [BabylonJS/Babylon.js#591]
Hello there,

it looks like there is an upcoming issue.
When using Chromebook on Chrome v45 (Dev-Channel) or Chrome v45 (Canary-Channel) on Windows,
the ArcRotateCamera doesn't rotate anymore if Babylon version 2.1 + is used. 
Zooming and rotating with the arrow keys works.
In 2.0.1 everything works again. 
Have there been any changes?

If this is just a temporary chrome issue feel free to close this.
But I just wanted to inform you :-)

**Comment by deltakosh** [comment]
Hey Kevin and thank you for pointing this out. I keep the issue open to track it but so far as long as this is only for canary I won't debug it :)

**Comment by KevinBLT** [comment]
Hey there,

I get some strange results.
I tried another hand version and downloaded hand.1.3.8.js from Github.
It fixes the problem in Chrome Canary, but now nothing happens on the iPad anymore.
It doesn't register any touch events as chrome did before with the other hand version.
Something is going on there :-(
I don't know what to do.
