### ISSUE TITLE
Deserialized cameras don't display info in inspector

### ISSUE THREAD

**Issue by Exolun** [BabylonJS/Babylon.js#5925]
Bug repro on [this Playground](https://www.babylonjs-playground.com/#NMZ0CC):

Repro steps:
- Load the playground linked above
- Expand nodes in the inspector
- Click on 'deserializedCamera'

The info panel on the right is blank, but if you switch to the camera it appears to be functioning fine.

**Comment by deltakosh** [comment]
Will fix that!

Thanks for reporting
