### ISSUE TITLE
Feature Request - make assetsManager await compatible

### ISSUE THREAD

**Issue by Gil-1** [BabylonJS/Babylon.js#5937]
Hello,

as talked on the forum https://forum.babylonjs.com/t/feature-request-could-we-make-the-load-function-from-assetsmanager-compatible-with-await/1452

It would be great to be able to use assetsManager.load() function with async capabilities.

We could have loadAsync()

I'm not sure we would need more.

**Comment by deltakosh** [comment]
I'll start with this one :)
