### ISSUE TITLE
memory leak when dispose mesh with skeleton animation, which use gltf loader

### ISSUE THREAD

**Issue by MooreSky** [BabylonJS/Babylon.js#5940]
when I use scene loaded in GLTF file, I find that dispose function in Mesh class doesn't dispose skeleton, which cause the bone texture can't dispose; and I find that mesh attached the bone can't dispose too. 

I add the code in glTFLoader.ts，show like this, which cause skeleton and bone-attached mesh can dispose when dispose the skeleton-mesh. What things I should care anyway? Thank you.

Note: I think the owner of skeleton ins't the mesh, and I add the code in gltf Loader, not the Mesh class.

```  js

// code in loaders/src/glTF/2.0/glTFLoader.ts

const assignSkeleton = (skeleton: Skeleton) => {
    this._forEachPrimitive(node, (babylonMesh) => {
        babylonMesh.skeleton = skeleton;

        // TODO: dispose skeleton and mesh attatched bone when dispose mesh
        babylonMesh.onDisposeObservable.addOnce(() => {
            for (let bone of skeleton.bones) {
                bone.dispose();
            }
            skeleton.dispose();
        });
    });
};

```

**Comment by MooreSky** [comment]
I think the owner of skeleton ins't the mesh, and I add the code in gltf Loader, not the Mesh class.

**Comment by deltakosh** [comment]
Hello this is because skeletons can be shared by multiple meshes  then we cannot dispose the skeleton when you dispose a mesh as this could break other meshes.

This is why the skeleton has its own dispose than need to be called separately

**Comment by deltakosh** [comment]
Please use the forum.babylonjs.com if you want to discuss that question.

We use the repo for bugs only
