### ISSUE TITLE
Handle CORS credentials in every HTTP requests

### ISSUE THREAD

**Issue by yvele** [BabylonJS/Babylon.js#5941]
Exactly how it has been done in https://github.com/BabylonJS/Babylon.js/pull/792 for [CorsBehavior](https://doc.babylonjs.com/api/classes/babylon.tools#corsbehavior) but for every HTTP requests that BabylonJS make.

Otherwise we get this error:

> Uncaught LoadFileError: Error status: 403  - Unable to load ...

This is needed when HTTP resources are protected with credentials and when the server sets the [Access-Control-Allow-Credentials](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Credentials) header.

BabylonJS is actually using [XMLHttpRequest](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest) (hopefully [fetch](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API) one day?) spread 5 or 6 times in the code base.

Maybe this is time to make a light abstraction layer on how requests are handled.

As a workaround I'm "patching" BabylonJS code base at build time using Webpack [string-replace-loader](https://github.com/Va1/string-replace-loader) plugin like that:

```js
module : {
  rules : [{
    // Patch to make BabylonJS handle credentials in every requests
    test    : /\/babylonjs\/es6\.js$/,
    loader  : "string-replace-loader",
    options : {
      multiple  : [{
        strict  : true, // Throw if nothing found
        flags   : "g",  // All occurences
        search  : "XMLHttpRequest",
        replace : "XMLHttpRequestBabylon"
      }, {
        strict  : true, // Throw if nothing found
        flags   : "i",  // Enable regex search
        search  : ".*", // Complete file
        replace : `
          import { XMLHttpRequestBabylon } from "${require.resolve("./src/babylon/patch")}";
          $&
        `
      }]
    }
  }]
}
```

With an extended class like this one:

```js
import isProtectedUrl from "./isProtectedUrl";


/**
 * Custom XMLHttpRequest that handles credentials.
 * This class is injected into BabylonJS at build time using Webpack.
 */
export default class XMLHttpRequestBabylon extends XMLHttpRequest {

  open(verb, url, ...args) {
    if (isProtectedUrl(url)) {
      this.withCredentials = false;
    }
    return super.open(verb, url, ...args);
  }

}
```

More informations in the [XMLHttpRequest.withCredentials](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/withCredentials) documentation.

It would be nice to have a feature making HTTP requests customizable.

Not only CORS but also follow redirects, etc. See fetch documentation for full options https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/fetch#Parameters

**Comment by deltakosh** [comment]
Fetch is unfortunately not supported on all our targets but perhaps one day:)

In the meantime this is a good idea. Fancy doing a PR?

**Comment by yvele** [comment]
About the PR I'm not sure to have the bandwidth and I'm not really familiar with babylonJS code base.

Maybe an easy way to do that is to extend `XMLHttpRequest` to something like a custom `XMLHttpRequestBabylon`, exactly how I did with my patch.. but even though this is ok for a monkey patch, I'm not sure that's what you want in your code base 🤔  

Off topic: Fetch has a polyfill https://github.com/github/fetch but in the meantime (I'm not sure you are using this feature), progress is unavailable in fetch https://stackoverflow.com/q/35711724/1480391

**Comment by deltakosh** [comment]
We do not use polyfill to not bloat the framework.
Anyway, let me have a look at that centralization for you
