### ISSUE TITLE
Add a function for VideoDome/PhotoDome to rotate to match camera direction

### ISSUE THREAD

**Issue by Exolun** [BabylonJS/Babylon.js#5949]
Currently the VideoDome and PhotoDome works great when instantiated in a new scene with a new camera, but it scenarios where 360 content is invoked from an existing camera, there is a good chance the media will be facing the wrong direction due to existing rotation applied to the camera. 

Check out this [playground](https://www.babylonjs-playground.com/#SQ5UC1#18) for an example

It would be nice if there were a method or flag on VideoDome / PhotoDome to make the dome orientation match the camera's orientation, since many 360 videos/images have a natural forward direction.

**Comment by deltakosh** [comment]
Something like that:
https://www.babylonjs-playground.com/#SQ5UC1#19 ?

**Comment by Exolun** [comment]
Yep pretty much!

**Comment by deltakosh** [comment]
I will add that :D

**Comment by Exolun** [comment]
Awesome.  Thank you!
