### ISSUE TITLE
pointerup not fired in multi-touch when one of the fingers touch outside of canvas

### ISSUE THREAD

**Issue by apptaro** [BabylonJS/Babylon.js#5950]
pointerup not fired in multi-touch when one of the fingers touch outside of canvas.

The issue happens only for multi-touch devices with a browser which supports PointerEvent natively. The issue does not happen for iPhone /iPad because PointerEvent is supported through pep.js which somehow avoids this issue.

# Bugs
- Bug repro on [playground]: https://www.babylonjs-playground.com/#7GSRYH#6
1. The first finger touches on the 3d view (canvas)
2. The second finger touches on the red box (div)
3. Release the second finger
4. Release the first finger

- Expected result:
pointerdown is fired in 1, and pointerup is fired in 4.

- Current result:
pointerdown is fired in 1, and pointerup is fired in 3.

- Cause:
See this._onPointerUp in scene.ts, where this._totalPointersPressed is decreased without checking this._pointerCaptures[evt.pointerId] so the pointerup event in 3 is consumed, while the pointerup event in 4 is ignored.

**Comment by apptaro** [comment]
See here:
https://github.com/BabylonJS/Babylon.js/blob/master/src/scene.ts#L2104

Because pointerup listener is attached to the window, we need to check first if it has been captured by pointerdown. Both 3.3.0 and 4.0.0 have the same issue.

My current workaround is to use CustomScene class in replacement for BABYLON.Scene:

CustomScene.ts:
```
import * as BABYLON from "babylonjs";

export class CustomScene extends BABYLON.Scene {
    private origOnPointerUp!: (evt: PointerEvent) => void;

    public attachControl(attachUp = true, attachDown = true, attachMove = true): void {
        super.attachControl(false, attachDown, attachMove);

        if (attachUp) {
            this.origOnPointerUp = (this as any)._onPointerUp;
            (this as any)._onPointerUp = (evt: PointerEvent) => {
                if (!(this as any)._pointerCaptures[evt.pointerId]) {
                    return;
                }
                this.origOnPointerUp(evt);
            };

            const eventPrefix = BABYLON.Tools.GetPointerPrefix();
            window.addEventListener(eventPrefix + "up", (this as any)._onPointerUp, false);
        }
    }
}
```

**Comment by deltakosh** [comment]
makes completely sense. Do you want to do a PR to fix it?
