### ISSUE TITLE
RenderTargetTexture with blur has interference pattern

### ISSUE THREAD

**Issue by nbduke** [BabylonJS/Babylon.js#5953]
# Bugs

Repro playground: https://playground.babylonjs.com/#X6P873#2

Repro steps:
1. Open up the above playground.
2. Click the "Teleport!" button. This moves the camera, PhotoDome, and acrylic plane 10000 m away on the X axis
3. Note the plane with the "acrylic" style blur.

Expected:
The acrylic plane should look exactly the same.

Result:
The acrylic plane has a distracting pattern of discoloration, resembling interference.

![image](https://user-images.githubusercontent.com/38300641/53201019-cf14d300-35d7-11e9-9a30-32e141b62af3.png)

If you decrease the `teleportDistance` variable, the effect lessens and eventually disappears. If you increase the value, it gets worse.

**Comment by deltakosh** [comment]
Unfortunately this pattern comes a precision issue in the "refract" shader instruction.
The size of the world is too large (10000) and thus refraction computation is less and less precise.

There is not a lot we can do about it. I will instead highly suggest to keep the camera closes to 0 (and then move everything else around)
