### ISSUE TITLE
Custom inspectable fields for inspector

### ISSUE THREAD

**Issue by PixelsCommander** [BabylonJS/Babylon.js#5957]
Discussed with @deltakosh here https://forum.babylonjs.com/t/custom-properties-in-the-inspector/1531/2

We are looking for a way to achieve Unity like functionality in inspector when a game designer could manipulate some custom object properties kinda: timings, model parameters, physics parameters.

Our proposal and preferred way is to have a property which is an array on every game object let`s say `gameObject.inspectable`. And it to be an array of objects like following:

`[
   {
        label: "myProperty",
        type: "checkbox", // or slider or vector3 or color3
        min: 10, // for slider
       max: 100 // for slider
    }, ...
]`

Once the inspector see that `gameObject.inspectables.length` is > 0 it creates `<CustomFieldsPropertyGrid properties={gameObject.inspectables}/>` above standard PropertyGrid for the object. So both - standard properties and custom properties are still editable.

We would be glad to contribute to any part of the implementation.

**Comment by deltakosh** [comment]
BOOM!
https://doc.babylonjs.com/how_to/debug_layer#inspector

**Comment by deltakosh** [comment]
Build in progress. will be ready soon

**Comment by deltakosh** [comment]
Done!

**Comment by PixelsCommander** [comment]
Wow, this was an amazing feature request experience. Thank you a lot.

**Comment by deltakosh** [comment]
My pleasure!
