### ISSUE TITLE
Evaluate WEBGL_multi_draw and  WEBGL_multi_draw_instanced

### ISSUE THREAD

**Issue by deltakosh** [BabylonJS/Babylon.js#5962]
https://www.khronos.org/registry/webgl/extensions/WEBGL_multi_draw/
https://www.khronos.org/registry/webgl/extensions/WEBGL_multi_draw/

https://github.com/kenrussell/webgl-animometer

**Comment by fernandojsg** [comment]
https://www.khronos.org/registry/webgl/extensions/WEBGL_multi_draw_instanced/ ^^

**Comment by deltakosh** [comment]
So far I'm struggling to find a good use case in the context of babylon as this requires to be able to render from the same vertex and index buffers using different offsets and counts which does not happen a lot for us :(

**Comment by deltakosh** [comment]
Closing for now as we are not seeing a direct use in bjs for now

**Comment by FishOrBear** [comment]
I am writing a CAD application on the web. This feature is very useful for me.

E.g:
There may be a lot of lines in the CAD. Generally, each line is controlled by a separate object in the CAD. When drawing the line, if it is not merged into one object to draw, then the number of `drawcall` will be very large. This will increase performance loss.

As mentioned in the proposal:
`
CAD vendors rendering large models compiled of many individual parts face singular issues large numbers of draw calls from WebGL. This extension reduces draw call overhead by standing better batching.
`

If you can support this feature, then it is very cool.

**Comment by deltakosh** [comment]
Why not using instances in that specific case?

**Comment by FishOrBear** [comment]
@deltakosh 
Sometimes you can use an instance, but sometimes it doesn't work.

For example, polygons, each polygon is different.

**Comment by deltakosh** [comment]
I would need to see a live example to better understand :)
if you can create a repro in the playground of what could be accelerated by supporting this extension

**Comment by FishOrBear** [comment]
https://www.babylonjs-playground.com/#7TPP9A

This example may be a bit extreme and the entity is duplicated.

Generally, if you are using duplicate entities, it is no problem to use instantiated geometry.

But in CAD drawings, these graphics may be different.

And the CAD system needs to manage each entity, which means it may be dynamic,
May add points or delete points,
May erase the object and redraw the object.
May draw new objects.
May modify the material (or line type, color)

**Comment by deltakosh** [comment]
Ok understood!

**Comment by FishOrBear** [comment]
I saw the webGPU demo, can webgpu solve similar problems?

**Comment by deltakosh** [comment]
Not really as the idea is technically to merge multiple vertex buffers into one draw call

**Comment by FishOrBear** [comment]
😄  I think this should improve performance.

Is there any plan to support it? Or is there any other solution to solve this problem?

**Comment by deltakosh** [comment]
I will reopen the feature request..Will see ho to add it in our current roadmap :)

**Comment by atg** [comment]
Would this help for submeshes? Say I have a mesh with 20 submeshes, and 10 are active. If I understand correctly this could draw all 10 with 1 draw call.

**Comment by atg** [comment]
Yeah, something like `O(nmaterials)` if submeshes are batched, rather than `O(nactivemeshes)` currently.

It would be useful in my case where I have chunks of voxel terrain sharing the same material, as currently I have to make a trade-off between better culling and fewer draw calls.

**Comment by deltakosh** [comment]
If you want, you can send a PR for that feature (We do not plan to work on it asap but I will gladly review a PR for it)

**Comment by atg** [comment]
Yeah maybe next year, once this ext has shipped in chromium at least. [Chrome tracking](https://bugs.chromium.org/p/chromium/issues/detail?id=890539) : [Firefox tracking](https://bugzilla.mozilla.org/show_bug.cgi?id=1536673).

**Comment by deltakosh** [comment]
Up?

**Comment by Popov72** [comment]
It seems no browsers are currently supporting this extension, at least not Chrome/Firefox in Windows (in their standard mode)...

Maybe we should close the issue until at least one browser supports the extension?

**Comment by sebavan** [comment]
Might be only in Chrome Canary ??? https://twitter.com/Tojiro/status/1099056933783457797 If it is the case it is probably worth adding a not here and reopening once available ?

**Comment by Popov72** [comment]
From what I could gather, it's only available under a switch (which is not "on" by default).

I checked [here](https://webglreport.com/) that's the extension is not available for me in Chrome/Firefox. My GPU is a GTX 1080, so I think it would support it if the browsers would make it available.

**Comment by sebavan** [comment]
Ok do let s close the issue until the extension gets a wider availability. Thanks a ton for checking.

**Comment by bnolan** [comment]
It's in chrome and edge and on android now - but not safari:

https://caniuse.com/mdn-api_webgl_multi_draw

![Screen Shot 2023-04-28 at 6 36 00 AM](https://user-images.githubusercontent.com/17499/234959711-aba1466d-efb2-48ca-b26a-5185c5b9a332.png)

Substrata is using multidraw in their C++ engine, I might try and get it going in babylon.js with our voxel engine geometry.

https://twitter.com/SubstrataVr/status/1651581054153797632

**Comment by sebavan** [comment]
This is great it is widerly available, but I am not sure where you would use it with voxels ???
