### ISSUE TITLE
Back-face rendering shading thresholded in 4.0

### ISSUE THREAD

**Issue by syntheticmagus** [BabylonJS/Babylon.js#5972]
Behavior rendering a glTF asset with back-face culling turned off changed between current stable and Babylon 4.0.  While both renderings appear to be behaving as though double-sided lighting is enabled (even though I don't believe it is), shading appears to be "thresholded" on the 4.0 version of the rendering, whereas smooth gradients appear on the current stable version.

Current stable: https://playground.babylonjs.com/indexStable.html#CS3SME
Babylon.js 4.0: https://playground.babylonjs.com/#CS3SME

**Comment by sebavan** [comment]
I ll take a look ASAP.

**Comment by sebavan** [comment]
It all looks correct to me as NdotV is now always clamped. twoSidedLighting should be enabled for those cases.
