### ISSUE TITLE
normalizeToUnitCube works differently depending on rotation

### ISSUE THREAD

**Issue by haroldma** [BabylonJS/Babylon.js#5983]
If I have the same model in different places (and rotations) I would expect `normalizeToUnitCube` to always produce the same outcome. Instead because of the AABB, rotation impacts it.

A workaround is to reset the rotation and restore after. (This should probably unparent and reparent as well)

Playground: https://www.babylonjs-playground.com/#CLG5B2 (click once to normalize and again to overlap objects)

**Comment by deltakosh** [comment]
Perhaps I can add a parameter to ignore rotation. Would that work for you?

**Comment by haroldma** [comment]
Yeah, that's fine with us (Y)
