### ISSUE TITLE
Create a node based system for material

### ISSUE THREAD

**Issue by sebavan** [BabylonJS/Babylon.js#6012]
One of the struggle with the current default provided materials (and effects at some extend) is their monolithic build making even simple customization hard to do without building a custom version of Babylon.js.

To simplify the customization and creation of derived materials it would be great to rely on a node based system and ensure that our default materials could rely on it internally.

Not only customization would be easy, but the usual tech artist creation workflow relying on node based system should become possible.

This would work to solve issues like :
* https://forum.babylonjs.com/t/pbr-shader-name-property/1731/4
* Most of the customization available in shader builder
* Some of our partners requirements (extending the default material system)

Design will be incoming right after 4.0 to ensure it will have a long run in 4.1 alpha.

Tasks:
- [x] Vec2 transform
- [x] Matrix multiplication
- [x] Vec3 transform
- [x] Vec4 transform
- [x] Vec4 splitter (into r, g, b, a outputs)
- [x] Vec3 splitter (r, g, b)
- [x] Vec4 merger (from r,g,b,a inputs)
- [x] Vec3 merger (from r, g, b)
- [x] Vector multiplication
- [x] Vector addition
- [x] Vector scale (by a float)
- [x] MorphTarget
- [x] Texture read (including uv transform by a matrix)
- [x] Fog
- [x] Instances
- [x] Bones
- [x] Light (can be set to a specific light)
- [x] Light (let the system pick active lights)
- [x] Pixel rejection
- [x] Multiply / Scale and MatrixMultiplication blocks should be the same
- [x] Emit well-known values with same name to reuse them
- [x] Add support for direct connection of attribute to a fragment node
- [x] Dot block
- [x] Cross block
- [x] Add RGB, R, G and B as output on texture block
- [x] Remap (e.g. map values with range [-1, 1] to [0, 1])
- [x] Format serialize JSON
- [x] Shadow
- [x] Reflection
- [x] Trigonometry
- [x] Make sure unconnected output do not generate code
- [x] Add NodeMaterial.CreateDefault(scene)
- [x] Emit comments seems broken
- [x] build API to easily access blocks
- [x] Fresnel
- [x] Lerp
- [x] subtraction node
- [x] exponent or power node
- [x] division node
- [x] Expose vertex color in the vector 3 node
- [x] step node
- [x] Drag out a new node should auto select it
- [x] Converter from color to vector and the opposite
- [x] Search!!!!
- [x] Add Round, Ceiling, and Floor nodes
- [x] Abililty to export shader code for inclusion into project
- [x] Block added to basic math group: one minus (1 - input)
- [x] Auto configure should look for already added blocks before creating new ones
- [x] Block to calculate view angle from camera.position and world matrix
- [x] Block to calculate the light angle for directional light, or a direction from spot/point to pixel to use with dot product for mesh normal
- [x] Add Min and Max blocks
- [x] Add light colors to light info block
- [x] Optimizer to reuse well-known and uniforms
- [x] Pertub normal node
- [x] Add an auto-turn table on the preview
- [x] Block added to range group: invert (color)
- [x] Add rotation support on texture block
- [x] The ability to wire a vector1 to the RGB input of FragmentOutput. This could be wiring direct where the vector1 is wired to R, G, and B under the hood. As a backup, automatically dropping a vector/color merger with the vector1 wired to RGB/XYZ and then to the RGB input is also fine.
- [x] RotationBlock
- [x] Distance block
- [x] Length block
- [x] Create new simple shader ball mesh to be used as a preview primitive.
- [x] Prevent float on cross or dot
- [x] DiscardBlock (https://forum.babylonjs.com/t/pass-value-to-shader-from-gui/5646)
- [x] Random block
- [x] Log Block
- [x] aTan Block
- [x] aCos Block
- [x] aSin
- [x] Fract Block
- [x] Sign Block
- [x] aTan2 Block
- [x] DeltaTime Block
- [x] SmoothStep Block
- [x] Reciprocal Block
- [x] Radian2Degree and Degree2Radian blocks
- [x] Replace Color block
- [x] Posterize Block
- [x] Sawtooth Wave Block
- [x] Square Wave Block
- [x] Triangle Wave Block
- [x] Gradient Block
- [x] WorldPosition Input Block
- [x] WorldNormal Input Block
- [x] Add "hinting" for direction toggle on transform node to activate when connected to vectors that will only be a direction like mesh.normal to save clicks for the user.
- [x] Add toggle for Pre Depth Pass to the Node Material Preview Window.  It can be off by default, but should operate just like the backface culling toggle.
- [x] Add a normal direction node (1 for front face and -1 for back face returning a float)

Designer:
- [x] uploading a texture to the texture node is broken. Try uploading a texture, then deselect the texture node, and then select it again...you'll see that the texture gets set back to "link" mode. It never uses the texture you upload.
- [x] Add extra lights to preview window with toggles to turn each individual light on or off. Playground scene coming from @PatrickRyanMS with all of the settings you will need.
- [x] Add a time stamp to the console window at the bottom for console messages so the user can track that a change has happened. If the same message keeps reporting in the window, it's difficult to know if the console changed or not.
- [x] Provide input for the Reflection texture to allow dds and env
- [x] Pulling out a Fresnel node should include the view direction input node
- [x] Tooltips over output nodes
- [x] Can we add an option so that when a vector block is marked as a constant that we change the background color (css) of the node so that we can easily track from the node graph which are constants and which are uniforms?
- [x] Need to add a scalar on the gloss input for lighting before using that value in Pow so that gloss maps that fall in the 0-1 range actually run the gamut from matte to highly glossy. 
- [x] Add specular (vector3) and gloss (float) inputs to the light node to automate calculations of lighting contribution based on a spec/gloss texture
- [x] Sometimes lose link parameter on an existing texture node when adding another texture node to the scene. This seems to be linked to the bug where UV tiling was being shared between texture nodes due to optimization. This seems to only happen when you have one texture node in the graph that is linked to a texture and you add a new texture node (the previous node will look like the texture was embedded).
- [x] Update rounded cylinder in primitives with new glb
- [x] Add a checkbox in parameters of user defined values (float, vector2, vector3, etc) to define the value as a constant and not a uniform.
- [x] Add a reload button in texture node when texture is not embedded. Changes to the source do not refresh due to the cache. Even switching back to embed and back to link will pull from the cache.  
- [x] save as sur hosted document
- [x] Add an option to not embed images in save and code generation
- [x] Add loaders to nme
- [x] Display message if screen width <768px
- [x] Add range floats to float node. If they are not null, show a slider UI control in inspector
- [x] Reduce speed of turntable on preview primitive to 35% of current speed.
- [x] Cross product node is named "Dot" by default when placed into workspace.
- [x] Change background behind preview primitive to match node tree background color. As a +1, the ability to switch the background color to a user chosen color (even if it's a predefined list) would be awesome. 
- [x] "opposite" node has a name that isn't clear as to what it's doing. Opposite could mean one minus, negate, or invert. Since we are doing a "one minus" operation, I think we should name the node "one minus."
- [x] Add custom input fields in inspector for Matrix node in NME
- [x] In NME, if you drag in a light information node, there is no light to select in the scene and so you cannot develop with that node in NME.
- [x] Copying a sine node, pastes as a cosine node. 
- [x] Changing a cosine node to a sine node and then saving, doesn't save.  The node opens back up as a cosine node.
- [x] Dragging the input of a subtract node out does not create a float, instead it draws a red line to the center of editor.  
- [x] Being able to reload the editor by clicking edit on a different node material in the inspector
- [x] Add User Input Properties to the Clamp node.  Similar to Remap node.  Clamp defaults to 0-1, but should be changeable by the user
- [x] When node is selected and a new node is dragged onto the workspace, both nodes are selected. We should deselect the previous node.
- [x] node groups not in alpha order. If we want to group things like math, we should use Math: Basic, Math: Trig, and Math: Vector. I'm finding it hard to find nodes even when I know what group they are in because input is at the bottom and I have to memorize a random mapping rather than knowing "I" for input should be middle top
- [x] Focus not released from inputtext when clicking inside the editor
- [x] Change FragmentOutput node to only accept RGBA or RGB.  It cannot have both.  Same logic for alpha
- [x] Discrepancy between preview and playground rendering when wiring mesh normal to fragment output
- [x] Cannot render world normal on mesh
- [x] Lerp node has "Fresnel" title.
- [x] Copy/paste for ALL selected nodes (not just the first one)
- [x] In Edge, unable to scroll block list with mouse wheel
- [x] Renaming of inputs do not behave correctly (+ add name (type))
- [x] Node list scrolling does not work on Edgium
- [x] Replace mode in inputBlock with a dropdown
- [x] Inspector will show user defined values (when activated)
- [x] Renaming a node does not work
- [x] Bug with scrolling on node list
- [x] Copy/Paste
- [x] Check why comments are not generated
- [x] more meshes for preview (box and torus)
- [x] Store node position when serializing
- [x] Find a way to preview the canvas in the node editor
- [x] Store texture data when coming from a blob
- [x] Let the user save / load a graph even if it does not compile
- [x] Limit well known and mesh properties per input type
- [x] Display constants on inputs
- [x] General properties for material (like alpha mode)
- [x] Property widget for fragment output
- [x] Block dragging from output ports
- [x] Crash when using RGBAMerger
- [x] Remove zindex use
- [x] Let the user to drag an port and generate an input
- [x] Limit drag and drop to node list only
- [x] Improve warning when dragging incompatible connections
- [x] Save button (use material.serialize into .json file)
- [x] Load button
- [x] Export as shader
- [x] Drag'n'drop for blocks
- [x] Add float input
- [x] Resizable colums
- [x] Do not change type of non connected input
- [x] Reset button (restore to a new simple material)
- [x] Block incompatible connections
- [x] Add support for texture block dropping (So far generates an error)
- [x] Allow drop of inputs directly
- [x] Update UI when texture is changed
- [x] Make sure removing output nodes is supported
- [x] let user change light affected to an input node
- [x] Error messages in red
- [x] New block should be with no input if input set to undefined

UI/UX
- [x] Design explorations for node appearance
- [x] Design exploration for node interface (input/output)
- [x] Rework list of nodes to add icons
- [ ] Add hover tool tip over each node in the node toolbox

**Comment by sebavan** [comment]
Reference to the forum thread: https://forum.babylonjs.com/t/node-based-material/1739

TL/DR: I ll summarize it here.

**Comment by deltakosh** [comment]
List of blocks to work on:
- [ ] Bones
- [ ] Instances
- [ ] Fog
- [ ] MorphTarget
- [ ] Matrix multiplication
- [ ] Vec2 transform
- [ ] Vec3 transform
- [ ] Vec4 transform
- [ ] Vec4 splitter (into r, g, b, a outputs)
- [ ] Vec3 splitter (r, g, b)
- [ ] Vec4 merger (from r,g,b,a inputs)
- [ ] Vec3 merger (from r, g, b)
- [ ] Vector multiplication
- [ ] Vector addition
- [ ] Vector scale (by a float)
- [ ] Light
- [ ] Refraction
- [ ] Reflection

**Comment by sebavan** [comment]
The community feedback and internal partners is a strong GO :-) I can not wait to try it.

**Comment by sebavan** [comment]
The new editor by @deltakosh is pretty cool :-) This is all getting real !!!
