### ISSUE TITLE
SceneLoader.LoadAssetContainer should grab environment texture

### ISSUE THREAD

**Issue by nbduke** [BabylonJS/Babylon.js#6014]
# Feature request
Debatable whether this is a bug or not, so I made it a feature request. If you call `BABYLON.SceneLoader.LoadAssetContainerAsync` with a .babylon file that specifies an environment texture, this texture does not get loaded into the asset container. I'm guessing this is because `AssetContainer` does not share `Scene`'s `environmentTexture` property. 

## Possible solutions
Any of the following solutions would be acceptable. I would probably prefer (1).
1. Move the `environmentTexture` property into `AbstractScene` and make sure `SceneLoader` populates it on the `AssetContainer`.
2. If the .babylon file has an environment texture, load it into either the `textures` array or the `reflectionProbes` array of the `AssetContainer`.

**Comment by nbduke** [comment]
Thinking about it some more, only solution (1) makes it straightforward to implement `addAllToScene`, since if the environment texture is just sitting in the `textures` array, it's not clear how the asset container will know to make it the environment texture of the scene.

**Comment by deltakosh** [comment]
Unfortunately 1 would imply a breaking change so this is not acceptable.

I would prefer having an environment texture property on the asset container that will be used when user call addAll

@trevordev thoughts?

**Comment by nbduke** [comment]
Check out #6019 for a related issue with the `AssetContainer`.

**Comment by TrevorDev** [comment]
Yup, 1 sounds right to me as well

Working on fixes for these issues now
