### ISSUE TITLE
AssetContainer.dispose removes sounds outside of the container

### ISSUE THREAD

**Issue by nbduke** [BabylonJS/Babylon.js#6019]
# Bugs
## Repro steps 
Navigate to [this playground](https://www.babylonjs-playground.com/#VGJIGT). You should immediately hear the music start playing, but after three seconds, we dispose of an asset container containing _only_ the sphere and ground meshes in the scene. Unfortunately, this causes the music to be disposed as well since it's part of the serializable components of the scene.

This feels like a bug: I don't expect objects in the scene outside of the asset container to be removed/disposed when I remove/dispose the asset container.

**Comment by nbduke** [comment]
@TrevorDev I was looking at your commits, and I'm concerned that `AssetContainer.dispose` will dispose the scene's `environmentTexture` even if the container did not possess that texture, which feels like a similar manifestation of the disappearing sound bug.

**Comment by deltakosh** [comment]
Agree I will update that line from:
```
if (this.scene.environmentTexture) {
            this.scene.environmentTexture.dispose();
}
```

to 
```
if (this.environmentTexture) {
            this.environmentTexture.dispose();
        }
```
Thoughts?

**Comment by nbduke** [comment]
That looks correct to me.

**Comment by deltakosh** [comment]
Pushing a fix with the nightly
