### ISSUE TITLE
Highlighter no longer working in 4.0.0.alpha.32

### ISSUE THREAD

**Issue by kevinkaychan** [BabylonJS/Babylon.js#6023]
https://playground.babylonjs.com/index.html#AWGQWM

expected that it should highlight!

:)

**Comment by sebavan** [comment]
cc @TrevorDev cause it is related to the latest multiview changes:

Effect.ts line 654:

// Add multiview setup to top of file when defined
var hasMultiviewExtension = this.defines.indexOf("#define MULTIVIEW\n") !== -1;

**Comment by sebavan** [comment]
We ll fix it ASAP thanks for reporting

**Comment by deltakosh** [comment]
Actually the fixes required are:
- [ ] Fix the bug when there is no multiview ( I will do it as it breaks the highlightlayer)
- [ ] Check if highlightlayer and glowlayer to see if they can work in multiview mode
