### ISSUE TITLE
Inspector "Physics" toggle doesn't render mesh imposters

### ISSUE THREAD

**Issue by PirateJC** [BabylonJS/Babylon.js#6031]
It looks like the inspector doesn't render the physics imposter for when using a MeshImposter, when toggling on the "Physics" helper.

https://playground.babylonjs.com/#B7VGSD#7

It seems like it should :)

**Comment by deltakosh** [comment]
Good point. The question is how to render it? Perhaps like a white mesh ? using wireframe? or solid color?

**Comment by PirateJC** [comment]
White wireframe would make the most sense to me.

**Comment by deltakosh** [comment]
Will do that!

**Comment by TrevorDev** [comment]
David, this is also not expected: 
![image](https://user-images.githubusercontent.com/3753071/53997551-78d48380-40f1-11e9-85bb-7cfc57bcc320.png)

https://playground.babylonjs.com/#B7VGSD#11

any idea why the wireframe would not lineup here?

**Comment by deltakosh** [comment]
Will check that as well
