### ISSUE TITLE
FollowCamera initialized with a position vector

### ISSUE THREAD

**Issue by Bondza** [BabylonJS/Babylon.js#604]
Hey, I am using the ```FollowCamera``` a bit and noticed that it is initialized using a ```Vector3``` as position which is passed on to the super constructor to set the initial camera position. The ```FollowCamera``` constructor then sets some [properties](https://github.com/BabylonJS/Babylon.js/blob/master/src/Cameras/babylon.followCamera.js#L13) which are used to calculate the actual position to follow target from later on. The issue is that unless you have a look at the default values from the constructor and calculate the position these will yeild, you will always experience a transition from your input position to the default position when your game starts.

Would it not be nicer if you could supply those specific parameters to the constructor instead? That way the camera would be stationary when the game starts, which I think would probably look nicer.

Allternatively it could be initialized like the ```ArcRotateCamera``` to set the alpha, beta and radius at which it should follow the target?

**Comment by Bondza** [comment]
Maybe something like https://github.com/Bondza/Babylon.js/commit/a0274e7d3198f36a3a37b739cb3b429d17587961 could work?
I can create a pull request if everything seems fine.

**Comment by deltakosh** [comment]
I do not have access to my computer but this seems fine. Can you provide a testing playground? And please just integrate the new class in followCamera.ts:)

**Comment by Temechon** [comment]
Hey Bondza, 

It's awesome ! Here is a beginning of a [working playground](http://www.babylonjs-playground.com/#XG7ND), but I can't seem to make the camera work correctly...

**Comment by Bondza** [comment]
Alright, maybe I should call it something else then. Because I want the camera to follow the target at an angle relative to target.position, and not care about the rotation of the object..

From what I can se it follows the box the way I wanted it to. But you've specified alpha and beta in radians, and I expect them to be in degrees. I don't know how you feel about that?

Were you expecting something more like [this](http://www.babylonjs-playground.com/#XG7ND#1)?

**Comment by Temechon** [comment]
Exactly :) In Babylon, all parameters are in radians, it would be awesome if you could do the same (for coherence purpose). Otherwise I think it's perfect !

**Comment by Bondza** [comment]
Sure I'll change that and move it into followCamera.ts :)

**Comment by Bondza** [comment]
I submitted a pull request #608 but I made a bit of a mess with the commits. I hope it's okay anyways otherwise I can try to fix it later.

Is [this playground](http://www.babylonjs-playground.com/#C6J9W) okay? :)

**Comment by Temechon** [comment]
Everything is ok :) And your playground is perfect! 
PR merged.

**Comment by Bondza** [comment]
Awesome, thanks! :)
