### ISSUE TITLE
Web Worker with instanced meshes 

### ISSUE THREAD

**Issue by cefleet** [BabylonJS/Babylon.js#605]
It appears as though instances meshes do not have a geometry attribute, so when workerCollisions is set to true on a scene the console fills up with the message "no mesh geometry id" when meshes collide with the instanced mesh.

**Comment by RaananW** [comment]
I'll look into that.

**Comment by cefleet** [comment]
for a little more information this has only been observed on blender exported instanced meshes, not one created using other methods.

**Comment by RaananW** [comment]
The fix will soon be integrated in the built js of 2.2
