### ISSUE TITLE
AssetContainer appears to leak textures and materials

### ISSUE THREAD

**Issue by nbduke** [BabylonJS/Babylon.js#6051]
# Bugs
## Repro steps
1. Navigate to this playground: https://www.babylonjs-playground.com/#FHHM51#4
2. Open the developer console and wait several seconds for the model to load, then two more seconds for it to be disposed.

The model is loaded into an `AssetContainer` using `SceneLoader.LoadAssetContainerAsync`. In the console, you'll see the numbers of meshes, materials, and textures in the scene logged before loading the container, after adding everything to the scene, and after removing/disposing everything in the container.

I would expect the numbers before and after to be exactly the same; i.e., `AssetContainer.addAllToScene()` followed by `AssetContainer.removeAllFromScene()` should leave the scene unchanged in any measurable way. This is not the case, however. Some materials and textures are left in the scene.

**Comment by TrevorDev** [comment]
@nbduke thanks for the good repro. It should not leak anymore after the above PR, however on the first initialization of any pbrMaterial a cached Material will be created so after adding and removing any number of gltfs, it should show 0 materials and 1 texture.
