### ISSUE TITLE
using WebRequest.CustomRequestHeaders results in crash

### ISSUE THREAD

**Issue by susares** [BabylonJS/Babylon.js#6055]
setting WebRequest.CustomRequestHeaders results in a crash for any caller upon WebRequest.open.
This is because the headers must be injected when the request is in state 'open'.

[playground link](https://playground.babylonjs.com/#YQDQZ4#1)
=> uncommenting WebRequest... line will result in an error 
- Expected result: custom headers should be injected
- Current result: custom headrs won't be injected but result in a crash

**Comment by susares** [comment]
There might be also an issue with WebRequest.**CustomRequestModifiers**. 
They are applied before the state is open.
If someone uses a CustomRequestModifier to inject headers it would result in the same crash.

simply moving the 'update' calls to where I moved the _injectCustomHeaders section. might not give expected results due to Modifiers that want to set attributes be used by i.e. 'open'

**Comment by deltakosh** [comment]
Thanks for the fix!
