### ISSUE TITLE
GUI MeshButton3D: parenting doesn't work when set as billboarded

### ISSUE THREAD

**Issue by Vinc3r** [BabylonJS/Babylon.js#6068]
- Bug repro on [playground](https://playground.babylonjs.com/#VC33MZ#4)
- Expected result: both buttons should follow the sphere rotation
- Current result: only the non-billboarded mesh is actually considered as child, the billboarded one is stucked in its initial position

![](https://i.imgur.com/BBpsbX4.gif)

**Comment by deltakosh** [comment]
Hello! this is the expected behavior as billboards do not inherit parent's rotation

You can workaround it by adding a dummy in between:
https://www.babylonjs-playground.com/#TXZNMG

**Comment by Vinc3r** [comment]
oh, OK, thanks!

I tought that was a bug 'cause this worked in alpha22 :)

**Comment by deltakosh** [comment]
I fixed the billboarding which was buggy :)
