### ISSUE TITLE
Mixin Class

### ISSUE THREAD

**Issue by JoJoor** [BabylonJS/Babylon.js#6078]
# Feature request
- Feature description
I want to mixin some babylon.js classes in my project. But some class is created by a factory class (MeshBuilder, AdvancedDynamicTexture...), so that I can't create my mixin class. Is there any other way to reuse babylon.js class?

- my code:
export default function EntityCreator<T extends TypeConstructor<TransformNode>>(target: T) {
       class EntityInterval extends target {
       }
       return EntityInterval
}

- Additional links that could help implementing the feature:
http://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-2.html

**Comment by deltakosh** [comment]
Not sure to get the problem :)
pinging @sebavan to see if it is clearer

**Comment by deltakosh** [comment]
Why do you need mixins as babylon.js provide a complete d.ts file:
https://github.com/BabylonJS/Babylon.js/blob/master/dist/preview%20release/babylon.d.ts

**Comment by sebavan** [comment]
Why not wrapping the statics ? Do you see any back compat changes we could do ?

**Comment by JoJoor** [comment]
@sebavan I want to implement entity-component system just like unity/UE4... Now the solution is  wrapping babylon.js class  as a property in my class (typescript genericity clasa), but it is inconvenient.

I recommend passing in a reference when you create an object using genericity function of factory class, so that I can create it's subclass.

**Comment by deltakosh** [comment]
Can you submit a PR so we can evaluate the impact?

**Comment by deltakosh** [comment]
Clsoing for now..Will reopen in case of a PR
