### ISSUE TITLE
AmmoJSPlugin doesn't set rollingfriction

### ISSUE THREAD

**Issue by mauricedoepke** [BabylonJS/Babylon.js#6086]
AmmoJSPlugin doesn't set the rolling friction, on the physics body. Thus SphereImposters aren't slowed down properly.

I suggest either adding a dedicated rollingFriction option or applying the normal friction as rollingFriction

**Comment by sebavan** [comment]
cc @TrevorDev for the plugin

**Comment by TrevorDev** [comment]
@mauricedoepke I'm not sure if any physics plugins expose this functionality. If you want to use a feature that might be specific to a certain plugin the impostor.physicsBody exposes the library's physics object.

Based on this thread https://pybullet.org/Bullet/phpBB3/viewtopic.php?t=12500 it looks like you should be able to use impostor.physicsBody.setRollingFriction in babylon. Let me know if you have issues.

**Comment by mauricedoepke** [comment]
@TrevorDev  That fixed it for me. But I think that rolling friction is a common enough use case to add it into babylons physics abstraction.

cannon.js can simulate rolling friction via angularDamping
(https://github.com/schteppe/cannon.js/issues/345)

oimo doesn't support it yet, but it was requested multiple times
(https://github.com/lo-th/Oimo.js/issues/47, https://github.com/lo-th/Oimo.js/issues/64, https://github.com/lo-th/Oimo.js/issues/86)

**Comment by TrevorDev** [comment]
I'll take a look to see if there is anything that can be done about oimo, typically the physics impostors only support features that are supported by all engines. Glad the physics body worked for the time being.

**Comment by TrevorDev** [comment]
After investigating, Ill close this for now. Ill reopen if engines have better consistency around this.
