### ISSUE TITLE
Attached sound and camera in the same group: sound is going away when group is moving

### ISSUE THREAD

**Issue by stylefieber** [BabylonJS/Babylon.js#6095]
Create an invisible mesh as group.
Add a box to the group.
Add a sound and attach it to the box (like an engine sound for example).
Create a camera and add it to the group (as a flight sim follow cam with position.z - 3).
Move the group. You would expect, that you can hear the sound, because the camera is still next to the box, but the sound is going away as has the camera never changed its position.

here is the playground example:

you can press w and s to move the box forward and backward.

The first one: https://playground.babylonjs.com/#EDVU95#10 <= camera is not part of the group and box-attached-sound is going away with the box

The second one: https://playground.babylonjs.com/#EDVU95#11 <= camera is part of group and is moving with the whole group, but the sound will go away if you move to far, even if its direct next to the box, which the sound is attached to.

**Comment by deltakosh** [comment]
Hello, not a bug actually. As you are moving the camera you need to turn on custom attenuation:
https://playground.babylonjs.com/#EDVU95#12
