### ISSUE TITLE
MeshImpostor not supported for oimo-plugin

### ISSUE THREAD

**Issue by Bondza** [BabylonJS/Babylon.js#610]
The ```MeshImpostor``` is not supported by the oimo plugin, which results in an error ```Uncaught TypeError: Cannot read property 'body' of null```.

I am trying to set the physics state for a ```GroundMesh``` which is an uneven surface, therefore ```SphereImpostor```,```PlaneImpostor```,```CylinderImpostor```or```BoxImpostor``` does not cut it.

Is there a reason that ```MeshImpostor``` is not supported for the oimo plugin? Or is it just not implemented yet?

**Comment by RaananW** [comment]
Oimo only supports boxes and spheres. The limitation comes from the framework itself and it is therefore impossible to implement.
Try using the Canon JS plugin, it does supper support complex meshes.
