### ISSUE TITLE
Making _pluginData typed

### ISSUE THREAD

**Issue by mauricedoepke** [BabylonJS/Babylon.js#6111]
# Feature request
I suggest making the _pluginData attribute of the Mesh Class typed. Currently it is any.

A solution would be to export a specific type from every physics Plugin and make _pluginData a Unity of that.

I think that could have prevented this bug:https://forum.babylonjs.com/t/v4-creating-a-compound-physics-body-with-a-meshimposter-of-mass-0-in-the-children-throws-error/2087

**Comment by mauricedoepke** [comment]
Are you generally interested in making stronger use of typing? I'm a big proponent of making it as hard as possible to use an api wrong by making wrong usage a type instead of a runtime error. This helps preventing hour long debugging sessions because the intellisense tells you about your mistake while writing the code. This would imho make babylon easier to use for people who haven't read it's source code which could benefit it's poularity.
If you are interested in that I'd be glad to make some contributiins in that area.

**Comment by deltakosh** [comment]
Well this will be a pretty massive work. Would you be ok to start working on it?

And to your second question: OH YEAH :D I'm all in to remove all the any we may need to use so far!

**Comment by mauricedoepke** [comment]
If you have some patience regarding that, then I will do so. I just need another week to better understand babylon, before I feel confident enough to submit code changes.

**Comment by deltakosh** [comment]
We have all the time in the world ;D

**Comment by deltakosh** [comment]
Closing for now as we are doing some grooming. Feel free to reopen at any time :)
