### ISSUE TITLE
In angular app when navigating to a page with a babylonjs canvas it isnt rendered. 

### ISSUE THREAD

**Issue by stevebrunton1** [BabylonJS/Babylon.js#6114]
**Use Github issues ONLY for validated bugs**

We have a really active forum to help answering questions (https://forum.babylonjs.com/)

*If you are convinced that you found a bug, please use the following template for your issue:*

# Bugs

- Bug repro on [playground](https://playground.babylonjs.com):
- Expected result:
- Current result:

# Feature request

- Link to [forum](https://forum.babylonjs.com/) discussion about the feature:
- Feature description
- Additional links that could help implementing the feature:

**Comment by stevebrunton1** [comment]
I am building an app using your babylon js engine.  It renders the webgl correctly if I initiate the application directly on the page that has the canvas on it.  But if I navigate to a different page and then come back to the canvas page, the WebGL isn't rendered.  I get the canvas events (Mouse, Keyboard)  so I know it is there and catching events from the browser.  is there some additional hook or event I need to respond to to get the webGL to redisplay?

**Comment by deltakosh** [comment]
Hello please use our forum (forum.babylonjs.com) for questions
