### ISSUE TITLE
The OBJFileLoader incorrectly displays textures

### ISSUE THREAD

**Issue by shults-s** [BabylonJS/Babylon.js#6123]
On some OBJ-models exported from Blender (or 3ds Max) textures displays wrong.

I tried to use ```BABYLON.OBJFileLoader.OPTIMIZE_WITH_UV = true``` before calling ```BABYLON.SceneLoader.Append(...)```, but this had no effect.
Autodesk FBX Review displays the model correctly.

I attach [link (Yandex.Disk)](https://yadi.sk/d/ilp5PpJ6267tHA) to the model itself and screenshots of how it should be and how it is.

**Comment by deltakosh** [comment]
Pinging @brianzinn to see if he has an idea

**Comment by brianzinn** [comment]
I checked out the shared files - the textures are 60MB of .dds files.  It looks like the normals are displayed wrong (there is an image of actual vs expected).  It would be worthwhile looking at a render without textures loaded.

Unfortunately, I have 2 issues I am looking into in the forum - one with the OBJ exporter and the other with adding smoothing groups feature to OBJ loader.  I don't have any more bandwidth to take this on.  I'm already struggling to find time for these 2.  If this isn't fixed when the other 2 are done then I will definitely start, but cannot make any commitments on time.  Thanks for asking - looks like an interesting one to solve :)

**Comment by deltakosh** [comment]
No worries..@drigax should soon be able to have a look at it

**Comment by Drigax** [comment]
@shults-s I was able to take a look at the model, I noticed that blender and 3ds Max imported your OBJ without issue. The model also loaded your model exported as GLTF without issue as well, but our texture coordinates appear to be inverted when we import OBJ into Babylon. 

I added some OBJ loader settings to give you more control over how your model's texture coordinates are loaded, adding:
```
BABYLON.OBJFileLoader.UV_SCALE = new Vector2(1, -1);
```

into your scene should work as a workaround.

However, I am interested in seeing if there is a pattern to this, whether it is the texture format or the exporting modeling program. Please let me know if you run into any inconsistencies between assets being loaded.

**Comment by shults-s** [comment]
@deltakosh @brianzinn @Drigax
Thank you so much for your help! Apparently, this is a really strange exporter of 3DS Max. It seems that it's time to switch to GLTF, there are no such problems with exporters :)
Babylon.js allowed me to write a bachelor's diploma in a quality and a very short time, when I thought that I was no longer in time. Thank you.

**Comment by deltakosh** [comment]
Lovely feedback thanks a lot!

Pinging @PirateJC  FYI :)

**Comment by PirateJC** [comment]
Amazing @shults-s!  Thanks so much for all of the feedback!  This is incredible to hear!
