### ISSUE TITLE
Stats tab in inspector v2 does not open

### ISSUE THREAD

**Issue by shaileshiyer** [BabylonJS/Babylon.js#6126]
Clicking on stats tab when the inspector is open crashes it. I am using it on a scene with free camera ,two meshes and a ground.
It crashes with the following exception.
`TypeError: Cannot read property 'current' of undefined
    at t.render (babylon.inspector.bundle.js:31)
    at so (babylon.inspector.bundle.js:51)
    at lo (babylon.inspector.bundle.js:51)
    at ho (babylon.inspector.bundle.js:51)
    at Xo (babylon.inspector.bundle.js:51)
    at qo (babylon.inspector.bundle.js:51)
    at Li (babylon.inspector.bundle.js:51)
    at _i (babylon.inspector.bundle.js:51)
    at Di (babylon.inspector.bundle.js:51)
    at Nn (babylon.inspector.bundle.js:51)`

**Comment by deltakosh** [comment]
Hello can you repro on the playground?

**Comment by shaileshiyer** [comment]
Sure can you give me some time to isolate the issue.

**Comment by deltakosh** [comment]
Sure no rush

**Comment by deltakosh** [comment]
up?

**Comment by shaileshiyer** [comment]
It crashes when trying to access the current property in  texturecollisionscounter. I am trying to recreate the issue as im typing. Is this a know issue where it is unable to read textures collisions of an imported gltf model.

**Comment by deltakosh** [comment]
Nope and btw this property was removed from 4.0 recently  :) make sure to use the very latest version from master

**Comment by shaileshiyer** [comment]
So hey I tested and found out that the crash does not happen on the playground. Heres the link 
https://playground.babylonjs.com/#YSYZBX
But when I was looking at the damaged PBR helmet demo provided at the website. I checked the stats tab it also crashed. Could it be that the playground is using a different version of the inspector compared to this demo.
https://www.babylonjs.com/demos/pbrglossy/
Both of them are the exact same scene with the same meshes loaded.

**Comment by shaileshiyer** [comment]
Using the inspector src link from the playground solved the crash in my scene. the unpkg cdn used might be supplying an incorrect version of the inspector bundle. This happened even though I was using the babylon engine from the preview version. preview.babylonjs.com
or is it a case where the bundle available at preview is lagging behind the master.?

> Nope and btw this property was removed from 4.0 recently :) make sure to use the very latest version from master

Sorry just typed without reading your comment. I will do that.

**Comment by deltakosh** [comment]
So we can close the issue?

**Comment by shaileshiyer** [comment]
Yup
