### ISSUE TITLE
weird space between ground meshes

### ISSUE THREAD

**Issue by asif2k** [BabylonJS/Babylon.js#6139]
Weird space between ground meshes when they have large size value for position x,y,z, 
- [playground](https://www.babylonjs-playground.com/#95HXZJ#3):
- They should be rendered at precise location without any random spaces when camera move around

**Comment by deltakosh** [comment]
Hey, this is not bug but more precision related question. I encourage you to use the forum.babylonjs.com

You can try to use log depth perhaps?
https://doc.babylonjs.com/how_to/using_logarithmic_depth_buffer


But most of the time the best option is to not use too large numbers (because of float precision).

**Comment by asif2k** [comment]
i am sorry it is not a bug but maybe limitations of webgl, however number was not large floating points but integer i guess and use of log depth also did not fixed the problem

Thanks

**Comment by deltakosh** [comment]
Yeah unfortunately this is a common problem with webgl rendering. YOu should try to see if other users found creative ideas on the forum regarding this question :)

**Comment by asif2k** [comment]
well i had asked the same question in forum 2 days ago but my question is still hidden by Akismet i dont know why

**Comment by deltakosh** [comment]
Can you try again?

**Comment by asif2k** [comment]
yes i just did and its posted 

thank you

**Comment by asif2k** [comment]
hmm its weird , Akismet has hide it again , i dont know what is the reason and when a staff member will review it

**Comment by deltakosh** [comment]
should be good now

**Comment by asif2k** [comment]
yes thank you again for the prompt support
