### ISSUE TITLE
I download babylon from www.babylonjs.com web site, but it not work

### ISSUE THREAD

**Issue by zfavourite99** [BabylonJS/Babylon.js#6157]
I download babylon from https://www.babylonjs.com/versionbuilder/
![image](https://user-images.githubusercontent.com/2630290/55497340-c2be7400-5673-11e9-95de-4db7b72e7161.png)
if i check any one(or both, or all) checkbox, then i will got the flow error:
![image](https://user-images.githubusercontent.com/2630290/55497459-f9948a00-5673-11e9-86c3-b20d352a357b.png)
when i click the get your version button, i just got one file that named babylon.custom.js. I do not know why require "babylonjs" and there have no the file.
![image](https://user-images.githubusercontent.com/2630290/55497730-90f9dd00-5674-11e9-82c4-7b01b1cb32d4.png)
in addition: if i select v4.0preview and minified, download will fail.

**Comment by deltakosh** [comment]
Hello please use our forum for question: forum.babylonjs.com

(A good read in the meantime:https://doc.babylonjs.com/features/es6_support)
