### ISSUE TITLE
typescript error on BabylonMessage

### ISSUE THREAD

**Issue by unicomp21** [BabylonJS/Babylon.js#616]
payload: InitPayload | CollidePayload | UpdatePayload;

compiler doesn't like the |'s

**Comment by RaananW** [comment]
This is a feature of TypeScript 1.4.  As the entire project was made 1.4 compatible I allowed myself to use it.
Is it possible for you to upgrade?

**Comment by unicomp21** [comment]
Will do, thanks for the help!

**Comment by RaananW** [comment]
great :-)
