### ISSUE TITLE
GUI3d: When using touch and when cliking with 2 fingers, the buttons will scale

### ISSUE THREAD

**Issue by deltakosh** [BabylonJS/Babylon.js#6163]
Repro here on any touch device:
https://www.babylonjs-playground.com/#HB4C01#9

**Comment by mitsufu** [comment]
adding some info: button "up" (and then click) and the associated animation should be raised only when the last manipulator is up.

**Comment by TrevorDev** [comment]
I see, Ill try to see if I can move the logic I added higher up to address the event issue. Thanks for clarifying
