### ISSUE TITLE
new #define for PBRCustomMaterial

### ISSUE THREAD

**Issue by lockphase** [BabylonJS/Babylon.js#6198]
I'm not ts savvy so submitting this as a feature request instead. As per forum post on texture splatting with PBRCustomMaterial, the existing defines don't allow for easy injection of roughness atlas map while it does support albedo and normal atlases. https://forum.babylonjs.com/t/pbr-texture-splatting-up-to-64-textures/1994/6

I'm requesting a new #define in the pbr fragment shader to allow user injection of custom codes for pbr custom material to read a roughness atlas map as a microsurfacetexture. erm, not sure what else is needed as the initial PBRCustomMaterial commits were initiated by @MackeyK24 already. This request is simply an extension of previous work. 

Thanks and hope it helps.

**Comment by MackeyK24** [comment]
Not sure i understand... Do you want another SHADER CHUNK AREA to insert custom shader code because the current SHADER CHUNKS dont give you access to OVERRIDE something.

Or you need an ACTUAL SHADER #DEFINE ???

If so... DEFINE WHAT ???

**Comment by lockphase** [comment]
Yes, as explained in the forum post. There is a whole chunk of shader code between CUSTOM_FRAGMENT_BEFORE_LIGHTS and CUSTOM_FRAGMENT_BEFORE_FOG. I just want to inject a roughness atlas map with my codes for grabbing the right texture2D values based on uv coordinates I supply from decoding the splatmap ids. I could rewrite everything from reflections, fresnel etc and dump to CUSTOM_FRAGMENT_BEFORE_FOG or we could just have a new #define so users can inject their atlases without messing with the light based calculations. 

Specifically, from the pbr.fragment.fx
```
#ifdef MICROSURFACEMAP
vec4 microSurfaceTexel = texture2D(microSurfaceSampler, vMicroSurfaceSamplerUV + uvOffset) * vMicroSurfaceSamplerInfos.y;
metallicRoughness.g *= microSurfaceTexel.r;
#endif
microSurface = 1.0 - metallicRoughness.g;
```
and
```
#ifdef MICROSURFACEMAP
vec4 microSurfaceTexel = texture2D(microSurfaceSampler, vMicroSurfaceSamplerUV + uvOffset) * vMicroSurfaceSamplerInfos.y;
microSurface *= microSurfaceTexel.r;
#endif
```
So #define CUSTOM_FRAGMENT_MICROSURFACE_METALLIC and #define CUSTOM_FRAGMENT_MICROSURFACE_SPECULAR right after those codes should facilitate microsurface atlas maps. I'm open to other suggestions like one #define only to override the reflectivity calculations will work too. Yes, I'm also wary of adding multiple #defines which is why I asked on forum. Ideas? Thoughts?

**Comment by MackeyK24** [comment]
Well i would say go ahead a make a PR with the changes so we can see what you wanna do :)

**Comment by deltakosh** [comment]
Good job! all merged!
