### ISSUE TITLE
requestPointerLog bug (babylon v4)

### ISSUE THREAD

**Issue by rattrap19** [BabylonJS/Babylon.js#6201]
OS: Linux Mint 18.3 (Sylvia)
Browser: Google Chrome 66

Something strange.
I tried babylon (version 4 beta 5) requestPointerLock on firefox, opera and google chrome 73.
Works fine!
Babylon (version 3 and earlier) also works fine with chrome 66.

But requestPointerLock (babylon version 4 beta 5) does not work correctly with chrome 66 on linux mint 18.3.
Maybe this happens only to me. I am confused.

https://www.babylonjs-playground.com/#12WBC#441

**Comment by deltakosh** [comment]
This is something for chrome DB (I remember they had this issue) but I doubt they will fix it :(
