### ISSUE TITLE
StandardMaterialDefines methods slow in V8

### ISSUE THREAD

**Issue by andyhall** [BabylonJS/Babylon.js#621]
Hi,

This is a Chrome/v8-specific issue, but each of the methods in StandardMaterialDefines currently run very slow in v8 due to the `for..in` loops, and the way optimization works in Chrome. (Basically, when v8 sees a `for..in` loop, in most cases it deoptimizes the whole function.)

![perf](https://cloud.githubusercontent.com/assets/352373/8744541/e0789474-2cb2-11e5-9f09-369be5a4ebfb.png)

Could these methods be changed to loop over `Object.keys(this)`, or a predefined array of keys, instead?

(I apologize for not sending a PR, but I don't have typescript compilation set up - sorry!)

**Comment by deltakosh** [comment]
Will do..Chrome is definitely getting better :)
