### ISSUE TITLE
Zoom inertia makes it difficult to zoom out with ArcRotateCamera

### ISSUE THREAD

**Issue by MiiBond** [BabylonJS/Babylon.js#6215]
We’ve been noticing that the `ArcRotateCamera` has an issue where it’s easy to zoom in and hard to zoom out.

Here’s an example:
https://www.babylonjs-playground.com/ts.html#WFAW5A#1

Try zooming in quickly and then try to zoom out at the same speed. Notice that zooming out is much more difficult. The expected behaviour, in my mind, would be for zooming in and out to take the same amount of effort.

The issue appears to be that the inertia of the camera is unaffected by the radius (i.e. `wheelDeltaPercentage`) so your zoom-in speed can easily get you in close to the model but then `wheelDeltaPercentage` prevents you from speeding up again while zooming out.
This is most obvious when the `lowerRadiusLimit` is small.
The solution would, I guess, be to take `wheelDeltaPercentage` and `pinchDeltaPercentage` into account when calculating the distance traveled under inertia.

Note that we still want `wheelDeltaPercentage` to scale the speed that the camera can zoom but it should also scale the speed applied as inertia from the previous frame.

**Comment by TrevorDev** [comment]
@MiiBond after looking at the code
https://github.com/BabylonJS/Babylon.js/blob/master/src/Cameras/Inputs/arcRotateCameraMouseWheelInput.ts#L49
 it looks like the scroll wheel events are always taking the current radius in mind when computing the inertia delta to travel, so if many events are built up while zooming it, it will zoom in too far so I tried computing the target radius and used that instead which hopefully will work in your scenario.
