### ISSUE TITLE
GUI.Image onPointerDown is throttled and onPointerClick doesn't work at all

### ISSUE THREAD

**Issue by kutomer** [BabylonJS/Babylon.js#6223]
Hello,

I've noticed that in the last few versions there has been a change in how pointer events work.
* onPointerDown is throttled (try clicking on the image few times and see that the event only fire once or twice)
* onPointerClick doesn't work at all

see this [playground](https://www.babylonjs-playground.com/#XCPP9Y#1050) for your self.
(open console, press few times on the image and see that click event never fires, and down event fire only once).

reproduced on: Chrome version 73.0.3683.103 running on OSx.

Thanks!

**Comment by deltakosh** [comment]
@TrevorDev  maybe related to your latest change on the pointers

**Comment by aWeirdo** [comment]
Seems to only affect non-button controls

**Comment by deltakosh** [comment]
yep for some reasons the _enterCount seems off

**Comment by deltakosh** [comment]
hahaha I'm just tired :)
As the imge is not a pointer blocker, it does not register to all events:)

Just add `image.isPointerBlocker = true;` and it will work :)
https://www.babylonjs-playground.com/#XCPP9Y#1051

**Comment by aWeirdo** [comment]
I managed to get confused (nothing unusual) since it works in 3.3 without isPointerBlocker
maybe a line should be added to the docs [how_to/gui#events](https://doc.babylonjs.com/how_to/gui#events) section 
"controls must have isPointerBlocker = true" or w/e

**Comment by deltakosh** [comment]
Yeah that changed because 3.3 was a bit messy when dealing with scene interaction.
I will definitely add that info in the doc

**Comment by deltakosh** [comment]
Doc fixed!
