### ISSUE TITLE
scene.activeCamera.onViewMatrixChanged doesn't fire in VR

### ISSUE THREAD

**Issue by Exolun** [BabylonJS/Babylon.js#6228]
Repro steps:

1.) Open [this playground](https://playground.babylonjs.com/#Z570N8#9) in Edge (Windows MR)
2.) Open edge debug tools to view console output
3.) Click the view in headset button
4.) Move head around to look

Notice the camera changed output is logged, but no viewport updates.  Once you exit VR you should see viewport changes logging from the new camera - you just never get them when in VR.

It's also a bit weird that you `isInFrustum` reports incorrect values.  I know the workaround for both of these issues is to use one of the `rigCameras` to detect changes while in VR, but ultimately there are some properties of the active camera that report usable values in VR (such as the forward ray), but a slew of others that don't work - which makes things difficult to predict.

**Comment by TrevorDev** [comment]
Sure, see this PR: https://github.com/BabylonJS/Babylon.js/pull/6230

I made it so child rig cameras will fire the parents camera's view notification

and added another parameter to isInFrustum that you can always set to true to work for vr and non/vr cameras

this pg should work after its merged #Z570N8#11

There is definitely some weird behavior with the webVR camera as it was orignally meant to represent the feet of the user and for back compat reasons a lot of properties of it can't change but a lot of apps use active camera which causes things to break. Hopefully for webXRCamera these issues will be resolved.

**Comment by Exolun** [comment]
That's great - thanks!
