### ISSUE TITLE
Animations associated with Morphed Models don’t play in the Babylon Sandbox.

### ISSUE THREAD

**Issue by Pratyush1184** [BabylonJS/Babylon.js#6259]
I used a model named  Morph Anim.fbx and exported it into .babylon using 3DS Max. The exported model when opened in the BabylonJS Sandbox renders a sphere without the associated animation where the mesh gets morphed into an irregular shape. The fbx model when viewed in Maya, plays the associated animations which involves morphing as can be seen in the video(morph.avi within the Morph Anim.zip file).

I have also uploaded the model Morph Anim.fbx and it’s corresponding babylon model. I have also sent a screenshot of the view obtained in the babylon sandbox(https://sandbox.babylonjs.com/)
Please look into the issue.

[Morph Anim.zip](https://github.com/BabylonJS/Babylon.js/files/3121477/Morph.Anim.zip)
![Screenshot from 2019-04-26 18-57-04](https://user-images.githubusercontent.com/20305094/56810914-1aa46100-6855-11e9-9e8f-26b4bf612cee.png)

**Comment by deltakosh** [comment]
The exported .babylon has no target exported.
Did you make sure to check the export normal and tangents as stated in the doc?
https://doc.babylonjs.com/resources/3dsmax#scene-properties

**Comment by deltakosh** [comment]
As this seems to be an exporter problem do you mind reopening the issue in the Exporters repo?
https://github.com/BabylonJS/Exporters

Thanks a lot

**Comment by Pratyush1184** [comment]
> The exported .babylon has no target exported.
> Did you make sure to check the export normal and tangents as stated in the doc?
> https://doc.babylonjs.com/resources/3dsmax#scene-properties

Yes, I did export normal and tangents as stated in the documentation.
