### ISSUE TITLE
Inspector improvements

### ISSUE THREAD

**Issue by deltakosh** [BabylonJS/Babylon.js#6262]
- [x] See channels with no texture on materials and let the user populate them
- [x] See texture file format
- [x] Add / remove shadowgenerator from light
- [x] Edit shadow generator
- [x] Add option on scene to add all meshes to shadow generators
- [x] Add option on scene to normalize the scene
- [x] Vertex normal meshes should not be visible in the scene explorer

**Comment by echadwick-wayfair** [comment]
It'd also be helpful to see texture file format. While you're in there, ;). I don't think that's exposed anywhere in the Inspector.
