### ISSUE TITLE
'getEngine' of null when CreateFullscreenUI is called on different renderer

### ISSUE THREAD

**Issue by TrySpace** [BabylonJS/Babylon.js#6264]
# Bug
'getEngine' of null when doing `GUI.AdvancedDynamicTexture.CreateFullscreenUI("UI")`, when using multiple canvases/renderers. Assumes last initiated renderer as current.

Say I have the following classes:

```ts
export class RenderCanvas {
  public canvas: HTMLCanvasElement;

  public engine: BABYLON.Engine;

  constructor (canvasElement: string) {
    // Create canvas and engine
    this.canvas = <HTMLCanvasElement>document.getElementById(canvasElement);
    this.engine = new BABYLON.Engine(this.canvas, true);
  }
}
```

```ts
export class Scene {

  public scene: BABYLON.Scene;
  public renderCanvas: RenderCanvas;

  constructor (renderCanvas: RenderCanvas) {
    // create a basic BJS Scene object
    this.renderCanvas = renderCanvas;
    this.scene = new BABYLON.Scene(this.renderCanvas.engine);
  }
}
```
```ts
export class Camera {
  private _camera: BABYLON.ArcRotateCamera;
  public renderCanvas: RenderCanvas;

  constructor(sceneInstance: Scene) {
    // create camera
    this._camera = new BABYLON.ArcRotateCamera(`Camera`, 3 * Math.PI / 2, Math.PI / 2.5, 30, BABYLON.Vector3.Zero(), sceneInstance.scene);
    this._camera.attachControl(sceneInstance.renderCanvas.canvas, true);
  }
}
```

I call in the following order:
```ts
  let renderCanvas1 = new RenderCanvas('renderCanvas1');
  let renderCanvas2 = new RenderCanvas('renderCanvas2');

  let scene1 = new Scene(renderCanvas1);
  let camera1 = new Camera(scene1);
  GUI.AdvancedDynamicTexture.CreateFullscreenUI("UI")
```
It will throw `Cannot read property 'getEngine' of null`.

However, when I do the following: 
```ts
  let renderCanvas1 = new RenderCanvas('renderCanvas1');
  // let renderCanvas2 = new RenderCanvas('renderCanvas2');

  let scene1 = new Scene(renderCanvas1);
  let camera1 = new Camera(scene1);
  GUI.AdvancedDynamicTexture.CreateFullscreenUI("UI")

  // Instead here
  let renderCanvas2 = new RenderCanvas('renderCanvas2');
```
It will be fine.

Now, to avoid this I could pass the scene to `CreateFullscreenUI` like:
```ts
   GUI.AdvancedDynamicTexture.CreateFullscreenUI("UI", true, scene.scene);
```

However I'm not sure if the correct behaviour for the engine is to assume the last initiated Engine instance is the primary. Should the `CreateFullscreenUI` not require the scene instead of being optional?

What's stranger, when I try to do the following:

```ts
  let renderCanvas1 = new RenderCanvas('renderCanvas1');
  let renderCanvas2 = new RenderCanvas('renderCanvas2');

  let scene1 = new Scene(renderCanvas1);
  let scene2 = new Scene(renderCanvas2);

  let camera1 = new Camera(scene1);
  let camera2 = new Camera(scene2);

  GUI.AdvancedDynamicTexture.CreateFullscreenUI("UI")
```
It won't error, but when I uncomment the following:

```ts
  let renderCanvas1 = new RenderCanvas('renderCanvas1');
  let renderCanvas2 = new RenderCanvas('renderCanvas2');

  let scene1 = new Scene(renderCanvas1);
  // let scene2 = new Scene(renderCanvas2);

  let camera1 = new Camera(scene1);
  // let camera2 = new Camera(scene2);

  GUI.AdvancedDynamicTexture.CreateFullscreenUI("UI")
```
It will throw the error `Cannot read property 'getEngine' of null` again...

Which I do not understand.

And it also happens that when I do something more complex with the created `CreateFullscreenUI` like a `CreateSimpleButton` to `.addControl`, while it only renders it in the 2nd canvas, it will also somehow have connected this button to both instances in either renderer. (However this seems to be because there are in fact 2 ui instances which **are rendered twice, but in the same place & canvas**, but still have their own `onPointerUpObservable`. So clicking a button there, will trigger both instances. This took a while to figure out. I assumed the different canvases I used where completely isolated from eachother, but `CreateFullscreenUI` breaks itself out of that assumed isolation)

Not sure how else to explain this. But it seems that the `CreateFullscreenUI` does not work great with multiple canvases.

Another way to 'fix' it, without passing the scene to `CreateFullscreenUI` is to change the excecution order to this:

```ts
  let renderCanvas1 = new RenderCanvas('renderCanvas1');
  let scene1 = new Scene(renderCanvas1);
  let camera1 = new Camera(scene1);
  GUI.AdvancedDynamicTexture.CreateFullscreenUI("UI")

  let renderCanvas2 = new RenderCanvas('renderCanvas2');
  let scene2 = new Scene(renderCanvas2);
  let camera2 = new Camera(scene2);
  GUI.AdvancedDynamicTexture.CreateFullscreenUI("UI")

```
Which all makes sense, but I'm not a fan of a function call to assume a particular context, especially when it relies on excecution sequence.

- I'm unable to repro on playground because it only supports one canvas.

**Comment by aWeirdo** [comment]
Have you tried passing the scene variable to CreateFullscreenUI ?

    BABYLON.GUI.AdvancedDynamicTexture.CreateFullscreenUI(name : 'string', isForeground? : boolean , Scene : BABYLON.Scene);

**Comment by deltakosh** [comment]
or even better on the playground.babylonjs.com ?

**Comment by deltakosh** [comment]
Furthermore as this is not a confirmed bug, I will encourage you to keep this discussion on the forum (as stated in the issue template).

The point is that if you do not provide a scene, the last created one will be used (if there is no then, well, it will crash :))

**Comment by deltakosh** [comment]
Anyway I will fix the Engine.LastCreatedScene to return the last created scene no matter what engine was created last :)
