### ISSUE TITLE
Directional light default angle? 

### ISSUE THREAD

**Issue by echadwick-wayfair** [BabylonJS/Babylon.js#6290]
Right-click on Nodes to add a Directional light. 

The current default angle 1,-1,1 seems to place the lighting behind the model.

Can we change the default rotation to -1, -1, -0.5? 

Moving this from the forum:
https://forum.babylonjs.com/t/sandbox-white-albedo-is-gray/2545/41

**Comment by deltakosh** [comment]
I'll do that as soon as 4.1 is open (in a couple of hours maybe a day max)

**Comment by echadwick-wayfair** [comment]
Thanks David!
