### ISSUE TITLE
Add option for ignoring backfaces on ray cast

### ISSUE THREAD

**Issue by PatrickRyanMS** [BabylonJS/Babylon.js#6319]
# Feature request

- Adding option to ignore backfaces on ray cast. Both as an option on the picking helper as well as in the inspector so that the picking tool can ignore backfaces on models. This is helpful if you have a room and are looking through the backfaces of the walls and want to pick objects in the room.

**Comment by Giv0** [comment]
How about an option for a ray to ignore a specified mesh/mesh group also?

**Comment by deltakosh** [comment]
This is already the case as you can specify a predicate (or just use mesh.isPickable )

**Comment by Giv0** [comment]
I should have read the docs more carefully.  The predicate function would have been nice when making giv0.gitlab.io/doomboom

I have a small sphere invisible and outside of you hitbox that shoots the ray. Itherwise you would hit yourself!

**Comment by deltakosh** [comment]
@PatrickRyanMS do you mind creating or providing a scene that I can use to test the feature?

**Comment by PatrickRyanMS** [comment]
@deltakosh Sure thing, my friend. Here's a model for you to test with:

[https://github.com/PatrickRyanMS/SampleModels/tree/master/meshBackfaces/glb](https://github.com/PatrickRyanMS/SampleModels/tree/master/meshBackfaces/glb)

I set this up so that you need to click through the cube back faces to pick the sphere.
