### ISSUE TITLE
ArcrotateCamera errors with VR 3D rig

### ISSUE THREAD

**Issue by Palmer-JC** [BabylonJS/Babylon.js#632]
I was testing Blender export parameters for camera.  Know that it might not be a real world combination, but it errors on line 521:
     this._rigCameras[0]._cameraRigParams.vrMetrics = metrics;
![selection_110](https://cloud.githubusercontent.com/assets/7916131/8813335/ac79bf9c-2fd0-11e5-8a75-eb1af3cf1dd9.png)
Think the problem is in ArcrotateCamera.createRigCamera().  It should probably have a line like TargetCamera's:
     rigCamera._cameraRigParams = {};

I do not have the hardware to test this, so I am not going to change it.

**Comment by deltakosh** [comment]
Hello I'm not able to repro this bug :(

**Comment by Palmer-JC** [comment]
It might be that I am using 2.1.  I want everything tested against production.  I know interaxialDistance has no meaning for this rig, the arg cannot be null, so always passing it.  Here is function for camera def:

    function defineCameras(scene) {
        if (Number(BABYLON.Engine.Version.substr(0, BABYLON.Engine.Version.lastIndexOf("."))) < 2.1) throw "Babylon version too old";
        BABYLON.Tools.Log('In get_baked.defineCameras');
        var camera;

        camera = new BABYLON.ArcRotateCamera("Camera", 0.8531, 1.1364, 20.1373, scene.getMeshByID("Gus"), scene);
        camera.setCameraRigMode(20,{interaxialDistance: 0.0637});
        camera.rotation = new BABYLON.Vector3(0.4615,-0.8149,0.0981);
        camera.fov = 0.8576;
        camera.minZ = 0.1;
        camera.maxZ = 500;
        camera.speed = 1;
        camera.inertia = 0.9;
        camera.checkCollisions = false;
        camera.applyGravity = false;
        camera.ellipsoid = new BABYLON.Vector3(0.2,0.9,0.2);
        scene.setActiveCameraByID("Camera");
    }
    get_baked.defineCameras = defineCameras;

**Comment by deltakosh** [comment]
Ok so closing this issue for now
