### ISSUE TITLE
Tube Creation Bug for exact 90° angles

### ISSUE THREAD

**Issue by thoebert** [BabylonJS/Babylon.js#6338]
- Bug repro on [playground](https://www.babylonjs-playground.com/#165IV6#797):
- Expected result: Tube with 90° angles
- Current result: tube stops with spike and all following points of the tube are ignored

Changing the last point of the tube to slightly other positions in the end works, for example (0, 10, 0.1), but with exact values it fails. With a slightly changed last position it is weird as well: (0.1, 10, 0)

**Comment by deltakosh** [comment]
Pinging @jbousquie or @BabylonJSGuide

**Comment by jbousquie** [comment]
The tube is built on top the Path3D.
You need to add far more point in your path to get the correct final shape. This is a known (and expected) behavior.
