### ISSUE TITLE
Redundant code in procedural texture rebuild, might be a bug?

### ISSUE THREAD

**Issue by zakhenry** [BabylonJS/Babylon.js#6341]
See https://github.com/BabylonJS/Babylon.js/blob/878c71286e027c2f34a50cd3a6975439134e5406/src/Materials/Textures/Procedurals/proceduralTexture.ts#L193-L195

This block of code appears to achieve nothing. I haven't actually hit a bug with it, but came across it when trying to understand rebuild process on gl context lost and it feels like something has gone wrong in the logic here.

Source commit: https://github.com/BabylonJS/Babylon.js/commit/2cf7717a086ff63c63c803a8d3eda8835293cb8f#diff-f1240db617af98924b84a0b36731c01d

cc @deltakosh

**Comment by deltakosh** [comment]
haha interesting one. This is because the refreshRate is a getter/setter. Setting its value will also reset the refresh counter (But I agree the code looks weird)
