### ISSUE TITLE
Create new HDR environments for playground

### ISSUE THREAD

**Issue by PatrickRyanMS** [BabylonJS/Babylon.js#6348]
# Asset request

Creating some new HDR environments for different lighting qualities in the sandbox and for distribution to anyone using Babylon.js. Scenes include:

- [ ] Exterior shot at noon
- [ ] Exterior shot at mid-morning/mid-afternoon
- [ ] Exterior shot at golden hour
- [ ] Exterior overcast day
- [ ] Interior shot with a mix of natural, incandescent, and/or florescent light. 
- [ ] Environment that matches the Office IBL

**Comment by deltakosh** [comment]
We should also add the same setup as Office

**Comment by Palmer-JC** [comment]
I also had cloudy day from the forum topic.

**Comment by thomlucc** [comment]
Cleaning "old issues" with no new requests. Feel free to re-open,
