### ISSUE TITLE
Color's getHashCode is incorrect

### ISSUE THREAD

**Issue by juchiast** [BabylonJS/Babylon.js#6355]
getHashCode is incorrect for Color3 and Color4.

- Bug repro on [playground](https://playground.babylonjs.com/#R86AWY)
- Current result: Hash code for green and blue is 0

**Comment by takahirox** [comment]
https://github.com/BabylonJS/Babylon.js/blob/master/src/Maths/math.ts#L67-L72

```javascript
public getHashCode(): number {
    let hash = this.r || 0;
    hash = (hash * 397) ^ (this.g || 0);
    hash = (hash * 397) ^ (this.b || 0);
    return hash;
}
```

If I'm right, floating point number is converted to integer before bit operation. Then `hash = (hash * 397) ^ (this.g || 0);` is equal to `hash = (hash * 397) ^ (Math.floor(this.g) || 0);`. So if `.g` or `.b` is smaller than 1, it'll be `hash = (hash * 397) ^ 0;`. Therefore, hash code will be always 0 if `.r` is 0 and `.g` `.b` are smaller than 1.

Probably this `getHashCode()` behavior is away from this function author expects.

**Comment by aWeirdo** [comment]
(0 ^ any number) === 0;

**Comment by deltakosh** [comment]
anyone interested to do the PR?

**Comment by takahirox** [comment]
If you folks don't mind, I'd like to try.

**Comment by deltakosh** [comment]
Please go ahead :D

**Comment by aWeirdo** [comment]
Any updates here?

**Comment by takahirox** [comment]
I'm gonna do in this weekend.

**Comment by aWeirdo** [comment]
Ok, thinking about it, this might need multiplication by 255 to align with RGB values, to avoid any errors with small numbers < 0.1 🙂

**Comment by takahirox** [comment]
Yup, I plan to make that number big enough.
