### ISSUE TITLE
Inspector @types dependencies

### ISSUE THREAD

**Issue by thscott** [BabylonJS/Babylon.js#6357]
Could the inspector @types dependencies (react && react-dom) be put under devDependencies? Including the inspector (es6) is causing conflicts for me due to these types being installed.

**Comment by deltakosh** [comment]
Sure thing I'll update that!

**Comment by alvov** [comment]
hi, sorry for raising an old topic, but it seems to be an issue again for @babylonjs/inspector@4.2.0-alpha.19 -
https://github.com/BabylonJS/Babylon.js/blob/master/dist/preview%20release/inspector/package.json

@deltakosh

**Comment by sebavan** [comment]
It should be ok and we are now moving them as peer dep #8354
