### ISSUE TITLE
Add support for 360 photos in Stereoscopic mode (TopBottom)

### ISSUE THREAD

**Issue by crampof** [BabylonJS/Babylon.js#6360]
Adding support for Stereoscopic mode TopBottom in PhotoDome class (just like in the VideoDome class), do get the 3D depth effect from the panoramas in VR.

Sample image:
![tour_stereo](https://user-images.githubusercontent.com/50719801/57946132-99ffe000-78a9-11e9-95ef-eda300870d47.jpg)

**Comment by deltakosh** [comment]
Do you have a side by side as well? I will add both :)

**Comment by crampof** [comment]
Yes, here you go. Thanks a lot!
![tour_stereo_side](https://user-images.githubusercontent.com/50719801/57947093-f532d200-78ab-11e9-988e-0839b9b37140.jpg)

**Comment by deltakosh** [comment]
Should be enough! Thanks a lot!
Will work on it asap (probably next week)

**Comment by deltakosh** [comment]
https://doc.babylonjs.com/how_to/360photodome#image-types

**Comment by crampof** [comment]
Very nice, thank you a lot!
Sorry for the noob question... should I be able to test it with this link?:
https://preview.babylonjs.com/babylon.js

**Comment by deltakosh** [comment]
yes as soon as the nightly will be compiled (in a hour or so)
