### ISSUE TITLE
[GUI] image with hoverCursor = 'pointer' cause blue overlay on android devices

### ISSUE THREAD

**Issue by kutomer** [BabylonJS/Babylon.js#6369]
Hello,

This is pretty weird but I noticed that when `GUI.Image` have `hoverCursor = 'pointer'` then pressing on them on mobile Android devices cause a blue overlay for a split of a second on the entire scene.

This bug reproduce on the playground with chrome dev tools (try Pixel 2, but also happens on my actual device - Galaxy s10)

https://playground.babylonjs.com/#U5K7QM

 Thanks :)

**Comment by deltakosh** [comment]
Not a bug actually, just set the div that contains the canvas with this css:
```
user-select: none;
```

Related issue: https://stackoverflow.com/questions/21003535/anyway-to-prevent-the-blue-highlighting-of-elements-in-chrome-when-clicking-quic
