### ISSUE TITLE
GroundMesh.optimize issue

### ISSUE THREAD

**Issue by LukasMichna** [BabylonJS/Babylon.js#637]
When I use an "optimize" method on my ground mesh generated from CreateGroundFromHeightmap, the ground becomes no more visible. In my opinion there is a problem in optimize method: var chunksCount is unused  

public optimize(chunksCount: number): void {
            this.subdivide(this._subdivisions);
            this.createOrUpdateSubmeshesOctree(32);
        }

should it be 
public optimize(chunksCount: number): void {
            this.subdivide(chunksCount);
            this.createOrUpdateSubmeshesOctree(chunksCount);
        } ???

**Comment by deltakosh** [comment]
woot! what's that sh... ? You're right! I'll fix it immediately:)
