### ISSUE TITLE
AmmoJS support ellipsoid

### ISSUE THREAD

**Issue by TrevorDev** [BabylonJS/Babylon.js#6376]
https://forum.babylonjs.com/t/rotating-bodies-dont-collide-correctly/3275/12

**Comment by CedricGuillemet** [comment]
First part of the fix is here : https://github.com/kripken/ammo.js/pull/259

**Comment by CedricGuillemet** [comment]
And the PR https://github.com/BabylonJS/Babylon.js/pull/6455
