### ISSUE TITLE
Add support for .basis texture file format

### ISSUE THREAD

**Issue by deltakosh** [BabylonJS/Babylon.js#6382]
https://opensource.googleblog.com/2019/05/google-and-binomial-partner-to-open.html

TODO:
- [x] Initial support
  - [x] cTFETC1
  - [x] cTFBC1
  - [x] cTFBC3
- [x] Fallback to Rgb565
- [x] Support cube data
- [x] Use webworker
- [x] Fallback to loading from CDN
- [ ] Ensure all formats will load
  - [ ] cTFETC1
  - [x] cTFBC1
  - [ ] cTFBC4
  - [ ] cTFPVRTC1_4_OPAQUE_ONLY
  - [ ] cTFBC7_M6_OPAQUE_ONLY
  - [ ] cTFETC2
  - [ ] cTFBC3
  - [ ] cTFBC5
- [x] Docs/examples

**Comment by somerandomguy83** [comment]
Can't wait !

**Comment by deltakosh** [comment]
Thanks a lot @TrevorDev
