### ISSUE TITLE
Sandbox cubemap should not write into depth buffer

### ISSUE THREAD

**Issue by bhouston** [BabylonJS/Babylon.js#639]
I was testing some Clara.io scenes exported to *babylon in the BabylonJS Sandbox here:

http://www.babylonjs.com/sandbox/

Often I notice that I can not see the object in the sandbox that I exported.  Initially I thought it was because the near/far clipping planes are positioned wrong.

But I noticed in this screenshot that the cubemap is actually writing into the depth buffer and thus is clipping objects at relatively near depths:

![image](https://cloud.githubusercontent.com/assets/588541/8967904/1980f974-3608-11e5-9974-147693717da0.png)

My suggestion is that when drawing the cubemap turn off depth writing and you'll get a better result.  The cube map often is considered to be positioned at infinite (although I have seen some recent exceptions.)

**Comment by bhouston** [comment]
To be clear, I know it is the cubemap that is clipping the object because the ground plane here is much larger than the Eiffel tower, but it is clipped at the same location as the Eiffel tower and it is not clipped against a far clipping plane but against planes exactly aligned with the cube map images.

**Comment by deltakosh** [comment]
Hey! you can turn on infinite distance with mesh.infiniteDistance = true but this won't fix directly your issue.
You can also export all mesh but the skydome with renderingGroupId =1. But you need to update the loader to load it (pretty easy:https://github.com/BabylonJS/Babylon.js/blob/master/src/Loading/Plugins/babylon.babylonFileLoader.ts#L677)

**Comment by deltakosh** [comment]
I'm creating an issue to add support for depthWrite disabling as well as this is a good idea
