### ISSUE TITLE
some typo exists for hidden properties

### ISSUE THREAD

**Issue by Vinc3r** [BabylonJS/Babylon.js#6390]
As seen on [this forum topic](https://forum.babylonjs.com/t/add-hidden-camera-property-into-documentation/3482/8?u=vinc3r), it looks like that `/** hidden` stands on code instead of `/** @hidden`.

As I'm not sure if this brake something, I doesn't want to make a PR myself ;)

![img](https://aws1.discourse-cdn.com/standard10/uploads/babylonjs/original/2X/3/3a38ab5c48b7564934e9aa426e29d5cc527863c4.png)

**Comment by deltakosh** [comment]
Thanks! I will fix the missing ones
