### ISSUE TITLE
Max2Babylon - feature request - Clearcoat

### ISSUE THREAD

**Issue by echadwick-wayfair** [BabylonJS/Babylon.js#6398]
- Link to [forum] discussion about the feature:
**https://forum.babylonjs.com/t/max2babylon-feature-request-clearcoat/3498**

- Feature description
I’d like to see support in Max2Babylon for the new Clearcoat PBR features.

Here’s a possible set of correlations between the BabylonJS Clearcoat arguments and the available inputs in 3ds Max.

I prefer it when exporters use setups that try to maintain parity with the built-in offline renderer. This makes it easier to preview the material while authoring, and to re-use the inputs for ground-truth offline rendering. Not all of these are 1:1, but they’re as close as I could get.

Green means the input is accessible in Track View and thus likely also in MAXScript. Beware the incorrect spelling of Roughness in some of 3ds Max’s parameter names!

A couple of the BabylonJS parameters will probably need Custom Attribute support, since there’s no comparable input in the Physical Material. Maybe they could be done similar to how you treat the Unlit material parameter? 

Thank you!
https://doc.babylonjs.com/resources/3dsmax#unlit-material

![2019-05-24 15_51_26-dir - Google Sheets](https://user-images.githubusercontent.com/40177036/58354374-3e040100-7e3f-11e9-90cd-e95f79118c0c.jpg)

**Comment by deltakosh** [comment]
Hello 

We are planning to tackle that soon with @PatrickRyanMS  and @sebavan but we do not have an eta for now

Closing here as this should be in exporters repo
