### ISSUE TITLE
Size Gradients are parsed twice while parsing a particle system

### ISSUE THREAD

**Issue by julien-moreau** [BabylonJS/Babylon.js#6405]
# Bug

- Lines to remove: https://github.com/BabylonJS/Babylon.js/blob/master/src/Particles/particleSystem.ts#L2433
- Expected result: size gradients should be added only one time while parsing a particle system
- Current result: the size gradients are parsed twice

**Comment by deltakosh** [comment]
Ouch:)

will fix that asap!
