### ISSUE TITLE
No ability to scale bump maps

### ISSUE THREAD

**Issue by bhouston** [BabylonJS/Babylon.js#641]
Most other tools allow for the scaling of the bump map affect.  I believe it is as simple as adding a ```bumpScale``` parameter to the ```map``` value here:

https://github.com/BabylonJS/Babylon.js/blob/f0b894768f887da8a563a167cf70b99a45dffe67/src/Shaders/default.fragment.fx#L339

**Comment by jahow** [comment]
All textures in BJS have a `level` property, which in the case of the bump texture is passed as `vBumpInfos.y` in this shader. I believe it fulfills the function you're talking about.

To be more precise, `vBumpInfos.y` is equal to `1.0 / bumpTexture.level`. See here: https://github.com/BabylonJS/Babylon.js/blob/master/src/Materials/babylon.standardMaterial.ts#L696

**Comment by bhouston** [comment]
Sweet.  Thank you!
