### ISSUE TITLE
How to create a mesh without add it to the scene.

### ISSUE THREAD

**Issue by kresli** [BabylonJS/Babylon.js#642]
Currently  when I create an object, it need to be assign to a scene `var sphere = BABYLON.Mesh.CreateSphere("sphere1", 16, 2, scene);`. Thats works great, but unfortunately I need to create object without assign it to any scene. Why? Because of OOP. I like to create an object, and then add it to the scene with some function eg: `scene.addMesh(sphere1)`.Is there any work around to achieve this? Maybe I missing something. Thanks

**Comment by deltakosh** [comment]
Hey,

you can remove your mesh from the scene right after creating it by removing it from scene.meshes[]

**Comment by kresli** [comment]
Hi. Thanks for quick replay. So I need to create temporary scene for storing object and then remove it from it. That makes sense. Thanks :)

**Comment by kresli** [comment]
Hi, 
Removing mesh from scene works great, but add it to the another scene its not working. Is this right way how to do it?
```javascript
var obj = new BABYLON.Mesh.CreateSphere('sphere1', 16, 2, scene1);
scene2.meshes.push(obj);
````

**Comment by deltakosh** [comment]
Yep this should work:) but do not forget to remove obj from scene1 before. Also I suggest to have this conversation on our forum where more people can help you

**Comment by clouds56** [comment]
Why the api designed like this? Why can't I share a mesh between scenes?

**Comment by deltakosh** [comment]
We have assetsCOntainer for that. Scene are the keeper of perf and manage memory for you
