### ISSUE TITLE
d.ts files for Babylonjs

### ISSUE THREAD

**Issue by QuantumInformation** [BabylonJS/Babylon.js#644]
Is there a definition file for babylonjs?

`tsd install babylon-js --save` returns 0 results.

Same with babylonjs

**Comment by deltakosh** [comment]
Here:
https://github.com/BabylonJS/Babylon.js/blob/master/dist/babylon.2.1.d.ts

**Comment by QuantumInformation** [comment]
Cool, thanks. Perhaps we could push a copy over to the https://github.com/borisyankov/DefinitelyTyped repo too as some point so we can manage this dependancy in a tsd.json

**Comment by deltakosh** [comment]
Good idea! thanks!

**Comment by QuantumInformation** [comment]
Cool, I'll raise a pull req with them.

**Comment by deltakosh** [comment]
Thank you for your help :)

**Comment by QuantumInformation** [comment]
Well have to add some tests and fix some things for this to make it to that repo:

https://travis-ci.org/borisyankov/DefinitelyTyped/builds/73700656

**Comment by deltakosh** [comment]
Ok this is because they use TS 1.5. Use this one then:
github.com/BabylonJS/Babylon.js/blob/master/dist/preview%20release%20-%20alpha/babylon.2.2.d.ts

**Comment by QuantumInformation** [comment]
New report

https://travis-ci.org/borisyankov/DefinitelyTyped/builds/73701479

**Comment by deltakosh** [comment]
Sounds like a file encoding issue to me

**Comment by deltakosh** [comment]
Oh no...I think they want a comment at the beginning of the file :)

**Comment by QuantumInformation** [comment]
shall I move the folder to babylon or change the d.ts file name to babylonjs.d.ts?

**Comment by QuantumInformation** [comment]
I created a header:

```
// Type definitions for BabylonJS v2.2
// Project: http://www.babylonjs.com/
// Definitions by: David Catuhe <https://github.com/deltakosh/>
// Definitions: https://github.com/borisyankov/babylonjs
```

**Comment by QuantumInformation** [comment]
My fork is here:
https://github.com/QuantumInformation/DefinitelyTyped

**Comment by QuantumInformation** [comment]
well the checks pass now, waiting for merge

**Comment by deltakosh** [comment]
Excellent thank you!

**Comment by QuantumInformation** [comment]
Just added empty test file, waiting for feedback.
