### ISSUE TITLE
Add a visibility predicate to normalizeToUnitVector

### ISSUE THREAD

**Issue by haroldma** [BabylonJS/Babylon.js#6441]
https://github.com/BabylonJS/Babylon.js/blob/62f0b403319ccb75d92c1762c59695a3ae787934/src/Meshes/abstractMesh.ts#L1000

It currently includes not enabled nodes. Tho it feels like getHierarchyBoundingVectors should ignore disabled meshes?

Also should normalizeToUnitVector live in Node instead of AbstractMesh?

**Comment by deltakosh** [comment]
yes for both!

**Comment by haroldma** [comment]
Thanks @TrevorDev !
