### ISSUE TITLE
StandardMaterial needs to be imported

### ISSUE THREAD

**Issue by bravecow** [BabylonJS/Babylon.js#6447]
Code: https://codesandbox.io/embed/pedantic-fast-xb39p

Preview: https://xb39p.codesandbox.io/

Error: `Uncaught StandardMaterial needs to be imported before as it contains a side-effect required by your code.`

But this example: https://doc.babylonjs.com/babylon101/first#your-own-html doesn't have any Material.

**Comment by bravecow** [comment]
It works with:

`import "@babylonjs/core/Materials/standardMaterial";`

but nothing about materials at https://doc.babylonjs.com/features/es6_support

only `MeshBuilder ` 😐

**Comment by bravecow** [comment]
looks like wrong `CreateSphere`:

works:
https://github.com/BabylonJS/Babylon.js/blob/3cfc6ef9d10e98cba81f3e8550efb6bb9c9311c0/src/Meshes/meshBuilder.ts#L83

doesn't work:
https://github.com/BabylonJS/Babylon.js/blob/94d5555f6657925ca3a9888461736221f16554c9/src/Meshes/mesh.ts#L3329

same method name, different options, `standardMaterial ` dependency. very confusing at the beginning 😏

**Comment by sebavan** [comment]
So about material I will add it to the doc ASAP.

About the CreateSphere, the one on mesh is a back compat method, the meshbuilder or even more sphereBuilder one should be use to reduce the dependencies at their minimum.

BR,
