### ISSUE TITLE
babylon.math.ts

### ISSUE THREAD

**Issue by unicomp21** [BabylonJS/Babylon.js#645]
having a .d.ts for use in workers would be nice

**Comment by RaananW** [comment]
Shouldn't the normal .d.ts be enough? Or am I missing something?

**Comment by unicomp21** [comment]
well, when I try to Vector3 math in the worker, the importScript for babylon.js chokes on refs to the window object.  am I doing something wrong?

**Comment by RaananW** [comment]
This is i believe a different problem - importing the .js file in a worker will not work if you don't define the worker before. 
    var worker = {}
should actually work. Or take a look at the collision worker and how I solved it there - https://github.com/BabylonJS/Babylon.js/blob/master/src/Collisions/babylon.collisionWorker.ts#L243

**Comment by RaananW** [comment]
Sorry, meant don't define the window before :smile:

**Comment by unicomp21** [comment]
tried it, no luck
babylon.2.1.js:4 Uncaught ReferenceError: window is not defined

**Comment by unicomp21** [comment]
/// <reference path="../external/babylon.2.1.d.ts" />

//importScripts("../external/babylon.math.js");
importScripts("../external/babylon.2.1.js");

function worker_proc() { ... }

**Comment by unicomp21** [comment]
I was doing it wrong, good2go, thanks!
