### ISSUE TITLE
WebStorm

### ISSUE THREAD

**Issue by unicomp21** [BabylonJS/Babylon.js#646]
I'm consuming Babylon.js from WebStorm, and loving it!  However, when I go to look at the sources in webstorm ref's aren't resolving.  Looks like what I'm missing is the typescript ref's ie

/// <reference path="xx.ts" />

Any quick easy way to get the ref's generated?

**Comment by RaananW** [comment]
According to the version of Babylon you are using, download the babylon.d.ts file and reference it in each file using Babylon classes. Should work.
