### ISSUE TITLE
Textures should be able to have a static Id

### ISSUE THREAD

**Issue by julien-moreau** [BabylonJS/Babylon.js#6476]
# Feature request
As seen on the forum, here is the issue:
- Link to the forum: https://forum.babylonjs.com/t/babylonjs-editor-default-skybox-environment-dds-inspector-select-boxes-and-ux/3763/3
- As for materials, nodes etc. textures should be able to have a static id, saved when serialized and re-set when parsing.
- Should work like the Node class to keep an homogeneous behavior: https://github.com/BabylonJS/Babylon.js/blob/master/src/node.ts#L72

**Comment by deltakosh** [comment]
Will work on it asap!

**Comment by julien-moreau** [comment]
Thanks you rox!! :)

**Comment by deltakosh** [comment]
Wait..why not using that already:
https://github.com/BabylonJS/Babylon.js/blob/master/src/Materials/Textures/baseTexture.ts#L32 ?

**Comment by julien-moreau** [comment]
Because it is overided in the constructor https://github.com/BabylonJS/Babylon.js/blob/master/src/Materials/Textures/baseTexture.ts#L374

**Comment by deltakosh** [comment]
Well but the serializer will restore it afterwards

**Comment by julien-moreau** [comment]
Yes you are right sorry!
Hum.. is it sure that unique ids will be unique after serializing, parsing, re-serializing etc? In a tool like the editor where you can add new textures, remove etc.

**Comment by deltakosh** [comment]
I think so:)

**Comment by julien-moreau** [comment]
You are right as it is incrementing the id each time before it parses!
So sorry for this useless issue and thanks for the solution!

**Comment by deltakosh** [comment]
My pleasure my friend!
