### ISSUE TITLE
Feature Request - UV morphing

### ISSUE THREAD

**Issue by Mainequin** [BabylonJS/Babylon.js#6480]
Discussed in this [forum post](https://forum.babylonjs.com/t/secondary-uvs-and-uv-morph-targets/3664) with a [playground example](https://playground.babylonjs.com/#H6YPT8#8) for testing purposes

- Morph targets should get an "UVs" attribute to gain the ability to morph an UV set
- Only one of the two possible UV-Layouts should be morphable
- Ideally it can be specified which one will be morphed

**Comment by deltakosh** [comment]
Will work on it as soon as possible (probably next week)
