### ISSUE TITLE
procedural textures

### ISSUE THREAD

**Issue by unicomp21** [BabylonJS/Babylon.js#649]
>Only once to create the texture which is put into cache
http://doc.babylonjs.com/page.php?p=22601

Do the resulting textures get mip-mapped trilinear, ie antialising?

**Comment by deltakosh** [comment]
yes sir!

**Comment by unicomp21** [comment]
Awesome!  If using procedurally generating all my textures and meshes, is
it possible for me to exhaust texture memory?  Or is there a strategy for
chucking textures?

**Comment by deltakosh** [comment]
You can but this is not related to procedural textures but just with textures. You have to deal with the available V-RAM :)

**Comment by deltakosh** [comment]
All textures can be disposed using texture.dispose()

**Comment by unicomp21** [comment]
Thanks!
