### ISSUE TITLE
gLTF loader not setting BoundingInfo

### ISSUE THREAD

**Issue by tibotiber** [BabylonJS/Babylon.js#6496]
Hi, I think I've found a bug with the gLTF loader. I'm using it through the `AssetsManager` and it doesn't seem to set the bounding info object. I thought this might be related to [this issue](http://www.html5gamedevs.com/topic/27575-gltf-loader-not-setting-boundinginfo/?tab=comments#comment-158656) (although I don't think I'm using gLTF 1 here), but setting `IncrementalLoading` to `false` doesn't change anything. I've created a minimal example PG.

- Bug repro on playground: https://www.babylonjs-playground.com/#3QG2DZ
- Expected result: the bounding box should appear and `getBoundingInfo().boundingBox` should be set
- Current result: the bounding box doesn't appear (presumably size is 0), and `getBoundingInfo().boundingBox` doesn't seem to be set

Just in case, I've tried with another model (both exported from Sketchfab) and it's the same.

By the way, just got started with babylonjs and I'm blown away by how well it's built, the ES6 support, tree shaking, the overall state of the docs and example. Kudos! 🚀

**Comment by bghgary** [comment]
This is by design. `getBoundingInfo` returns a shallow bounding of the mesh (i.e. does not include children). Since the code is calling `getBoundingInfo` on the root node with no mesh associated, it just returns all zeros. To get the full bounding of all children, call `getHierarchyBoundingVectors`.

https://www.babylonjs-playground.com/#3QG2DZ#2

**Comment by tibotiber** [comment]
Thanks a lot @bghgary. Is there any place I should have seen this? I've been reading few hours before posting but didn't see any mention of this. Keen to improve the docs if I can.

**Comment by bghgary** [comment]
@deltakosh Are you aware of any documentation for this? Maybe updating the [getBoundingBox](https://doc.babylonjs.com/api/classes/babylon.abstractmesh#getboundinginfo) function comment would help?

**Comment by deltakosh** [comment]
Yeah I think that's the best place

Thanks a lot @tibotiber

**Comment by tibotiber** [comment]
PR opened. Thanks guys :)
