### ISSUE TITLE
Meshes created with MergeMeshesOptimization() are ignored by the Octree

### ISSUE THREAD

**Issue by Gpinchon** [BabylonJS/Babylon.js#650]
When running MergeMeshesOptimization(), the newly created meshes are not added to the current scene's SelectionOctree, thuse making them ignored when rendering the scene.
The only workaround I found is to run createOrUpdateSelectionOctree() while running the SceneOptimizer or before the rendering of each frame (which does not sound right).

**Comment by deltakosh** [comment]
hello this is by design. The octree is not dynamic

**Comment by Gpinchon** [comment]
So I should run the createOrUpdateSelectionOctree() on each frame ?
Also, even without running createOrUpdateSelectionOctree() before running MergeMeshesOptimization(), the newly created meshes become invisible (are ignored).
Is this also by design ?

**Comment by deltakosh** [comment]
If you merge meshes (so creating new mesh) on each frame yes.
But you can also mark your meshes as dynamic (so always visible): scene._selectionOctree.dynamicContent.push(newMesh)

**Comment by Gpinchon** [comment]
And what about the meshes created by a SceneOptimizer using MergeMeshesOptimization(), I don't want them to be always visible (I won't set them as dynamic as it's not counterproductive regarding optimization).
And I am not creating new meshes on each frames, but the SceneOptimizer does create new meshes while the scene is running, which are not taken into account until a new call to createOrUpdateSelectionOctree().
Which means that unless createOrUpdateSelectionOctree() is running in the background while running the SceneOptimizer is running, the new meshes won't be visible.
The best solution performance-wise seems like running createOrUpdateSelectionOctree() on both success and fail of the SceneOptimizer, but the meshes will still be invisible until the SceneOptimizer is done optimizing the scene...

**Comment by deltakosh** [comment]
For the sceneOptimizer, the best way is to call createOrUpdateSelectionOctree on success. Agree for the race condition between two, why not thinking about adding a custom step in the sceneOptimizer to call updateSelectionOctree for you? Or we can even think about adding it natively

**Comment by deltakosh** [comment]
Something like BABYLON.MergeMeshesOptimization.UpdateSelectionTree = true

**Comment by Gpinchon** [comment]
That would be a cool way to do it, setting it to false by default of course, thuse keeping good performances.
I think I'll take an other dive into the BabylonJS source code to take a look at this and try to add it.

**Comment by deltakosh** [comment]
No worry it is almost done
