### ISSUE TITLE
Scaling mesh after assigning physicsImpostor

### ISSUE THREAD

**Issue by tom-berend** [BabylonJS/Babylon.js#6501]
try it here:  https://www.babylonjs-playground.com/#UXGMEC#2

no problem scaling a mesh before adding the impostor.

there is get-set code in AbstractMesh that looks like it tries to force an update to the impostor if the mesh is scaled.  it is called when you use
`mesh.scaling = new BABYLON.Vector3()`
but it fails on all three engines in unpleasant ways.  I believe this is the root problem.

and there is a second problem.  if you just whack in 
`mesh.scaling.x = newValue`
then the mesh is updated in TransformMesh (instead of AbstractMesh).  scaling works, but the impostor doesn't know about the change.  this low-level update should not be allowed.

I would try to fix this myself, but it will take me a while to figure out all the pieces.

**Comment by deltakosh** [comment]
Hello we recommend to use to forum for discussion before opening bugs here as most of the community is on form.babylonjs.com

**Comment by TrevorDev** [comment]
@tom-berend thanks for reporting this, I will try to avoid crashes in the first case and am working on a fix. For the second case I believe this is the expected behavior and I would expect that you will need to recreate the physics impostor or call forceUpdate for the update to take effect.

**Comment by tom-berend** [comment]
the second case LOOKS the same, but gives different results.  I think that case should be captured in AbsrtactMesh with get-set methods and processed consistently.

**Comment by tom-berend** [comment]
... or remove the update in AbsrtactMesh and perform the update explicitly in both cases.  maybe that is the best (works in other cases too).  it is the inconsistency that is a problem.

**Comment by TrevorDev** [comment]
The performance impact of forceUpdate may be large (this recreates the impostor in most cases) so I would prefer to force the developer to explicitly call this. Ideally I would remove calling it in the 1st case but that would break backwards compatibility (@deltakosh do you bless this breaking change?)

**Comment by tom-berend** [comment]
it can't be a breaking change if it never worked.  :) just need to accept a Vector3 in Transform Node for all existing working code.
