### ISSUE TITLE
Make Sound more flexible with URLs

### ISSUE THREAD

**Issue by nbduke** [BabylonJS/Babylon.js#6508]
# Feature request
The Sound object's constructor expects a URL that contains a file extension matching one of the supported codecs, and it must include the period. See [the code](https://github.com/BabylonJS/Babylon.js/blob/a796074061d88e8d5c0b17cead73d266d92298bc/src/Audio/sound.ts#L281).

This is a little restrictive. For example, we use a content conversion service that is able to convert a number of audio formats into mp3, but the URL ends up looking like this:
   https://host/audio_files/fileId/content?format=mp3
Since the URL doesn't contain ".mp3", Sound fails to recognize it and doesn't play anything.

Moreover, it's not even clear why the strict check for codec support is needed. I can work around the issue on my side by sticking "?.wav" onto the end of a URL, and Sound will play the audio just fine even though it's actually an mp3. It seems like there is some underlying mechanism that downloads the file and can check the MIME type to pick the codec; so why check the raw URL itself?

**Comment by deltakosh** [comment]
Good point! I think this could be improved :)
Fancy doing a PR?

**Comment by nbduke** [comment]
Sure, I can do that.
