### ISSUE TITLE
Babylon 101 Video Tutorial Series

### ISSUE THREAD

**Issue by PirateJC** [BabylonJS/Babylon.js#6509]
Create a series of tutorial/walkthrough videos to accompany the Babylon101 documentation. 
 These videos will help walk folks who are new to Babylon, through the beginning basics of how to use it.

- [ ] Intro and About the Course
- [ ] First Steps
- [ ] Discovering the Basics
- [ ] Parametric Shapes
- [ ] Position and Rotation
- [ ] Materials
- [ ] Cameras
- [ ] Lights
- [ ] Animation
- [ ] Cameras, Mesh Collisions and Gravity
- [ ] Intersect Collisions - mesh
- [ ] Picking Collisions
- [ ] Raycasting
- [ ] Sprites
- [ ] Particles
- [ ] Environment
- [ ] Height Map
- [ ] Shadows

**Comment by Yonet** [comment]
@PirateJC I am happy to help with videos if you like.

**Comment by deltakosh** [comment]
Woot that would be so cool @Yonet! Thanks a lot

**Comment by PirateJC** [comment]
Yonet that's awesome!  We'd love to have you contribute to this!  Can you send me a PM on the forum so we can chat more about it?  https://forum.babylonjs.com/u/PirateJC

Thanks!

**Comment by thomlucc** [comment]
Moved this issue to our documentation repo under [#1955](https://github.com/babylonjs/documentation/issues/1955)
