### ISSUE TITLE
AssetContainer.dispose disposes some textures in other AssetContainers

### ISSUE THREAD

**Issue by nbduke** [BabylonJS/Babylon.js#6510]
# Bugs
Repro playground: https://www.babylonjs-playground.com/index.html#FHHM51#17

1. Load the above playground
2. After the assets load, double-click anywhere in the canvas

You'll see the skybox and a portion of the ground disappear.

What's happening is that, when you double-click, the same babylon file is loaded again into a new AssetContainer. Once loaded, the original container is disposed and the new container is added to the scene. Somehow, the textures that you see disappear are disposed even though they're in a new AssetContainer instance (or what I would expect to be a new instance).

I'm not sure why this happens to some textures and not others, though.

**Comment by TrevorDev** [comment]
It looks like there is an issue when loading multimaterials where the second assetcontainer points to the same texture that is stored in the first causing this issue. Still investigating what the best way to fix this is. Thanks for the good repro.
