### ISSUE TITLE
Incorrect camera variable name in docs

### ISSUE THREAD

**Issue by seleb** [BabylonJS/Babylon.js#6512]
Hey there, super minor documentation issue, but tripped me up for a moment so thought I'd point it out: 

https://github.com/BabylonJS/Babylon.js/blob/59c031680502fb12a298f0ade534abb26a738d07/src/Cameras/camera.ts#L180

This line mentions `Camera.PERSPECTIVE_ORTHOGRAPHIC`, but the actual name is `Camera.ORTHOGRAPHIC_CAMERA`.

**Comment by deltakosh** [comment]
Oh yeah! Thanks I will fix that asap
