### ISSUE TITLE
Need to update blender readme.md with new 3.0 feature

### ISSUE THREAD

**Issue by deltakosh** [BabylonJS/Babylon.js#653]
We should create a page and in the doc and link it in the readme

**Comment by Palmer-JC** [comment]
I did agree to do showing doc in multiple places.  No sure when.  Have my main system in the middle of the floor, having a 2nd hard drive installed.  After that Win 10 system & new ubuntu rebuild, which will take a while.

As I said in the forum, after switching to full path image references, this gets easier & more maintainable in multiple spots.  Paths were a problem in dev.

A link sounds good enough for now.

**Comment by Palmer-JC** [comment]
I have updated the TOB read me to use fully qualified names.  The TOB readme could could now be the source for the .babylon one, with all the code examples removed.

Rereading your ask though, please be specific as to which read me gets the link of the other, cause those 15 words too ambiguous

**Comment by deltakosh** [comment]
Mostly my ask is to have a readme.md for the exporter by itself and referencing it from TOB readme.md. Else it could be uneasy for a beginner to understand the difference between TOB and the exporter
