### ISSUE TITLE
IsInFrustum not working for active camera while in VR (Edge/Windows MR)

### ISSUE THREAD

**Issue by Exolun** [BabylonJS/Babylon.js#6533]
Repro steps:

1.) Open this [playground](https://playground.babylonjs.com/#Z570N8#6) in Edge (Windows MR)
3.) Click the view in headset button
4.) Move head around to look

Normally you'd see the spheres in the scene turn red as the frustum moves around, but in this case they mostly stay yellow because the frustum check is failing in VR.

**Comment by TrevorDev** [comment]
Because the camera contains rig cameras they need to be checked as well this is not done by default but can be done by passing true as the second param to isInFrustum. Let me know if this pg doesnt work for you https://playground.babylonjs.com/index.html#Z570N8#15

**Comment by Exolun** [comment]
Ahh I see - the playground works for me.  Will use the flag, thank you!
