### ISSUE TITLE
Instanced meshes with children blow up shadow generator

### ISSUE THREAD

**Issue by nbduke** [BabylonJS/Babylon.js#6545]
# Bug
Repro playground: https://www.babylonjs-playground.com/#593WXW#1

If you have a mesh hierarchy and you create an instance from the root mesh and then add that instance to the shadow casters of a shadow generator, Babylon crashes in the render loop. This happens whether you create the hierarchy manually or it's imported from a file.

Looks like the issue is [here](https://github.com/BabylonJS/Babylon.js/blob/b263278dbdb23248b4e122bc3e118cfe16717c0d/src/Materials/Textures/renderTargetTexture.ts#L688). `RenderTargetTexture` checks if `mesh.subMeshes` is defined, but if the mesh is an instance, it reassigns the mesh to the original mesh, which may not have sub-meshes.

**Comment by sebavan** [comment]
Just noticed in your example that you basically try to create instances of "transform node" (empty meshes)

This is not possible and would result in not rendering any of the children.

You should instead create the instances on the meshes with geometry information.
