### ISSUE TITLE
Package "@babylonjs/..." : some strange issues.

### ISSUE THREAD

**Issue by pierreglibert** [BabylonJS/Babylon.js#6548]
Hi community :)
I have an issue with typescript : Scene.createDefaultSkybox does not exist on type "Scene"
I use es6 npm package : "@babylonjs/core": "^4.0.3". 
Strangely, it work on playground : https://www.babylonjs-playground.com/indexStable.html#WGZLGJ

`
import { Scene } from "@babylonjs/core/scene";
const engine = new Engine(canvas);
var scene = new Scene(engine);
var hdrTexture = CubeTexture.CreateFromPrefilteredData("/src/textures/environment.dds", scene);
scene.createDefaultSkybox(hdrTexture, true);
`

Thanks for your help.

edit : 
1. I test it with : <import * as BABYLON from 'babylonjs';>, It work ...
2. I saw that a lot of things seems strange ... : 
- scene.clearColor not working with "@babylonjs/core" but work with "babylonjs".
- The render of gltf is wrong, it lacks the rendering of several textures but not with "babylonjs" again.

**Comment by sebavan** [comment]
The documentation: https://doc.babylonjs.com/features/es6_support#side-effects explains a lot about your issues.

It all boils down to side effects being in use to handle back compat.

For instance the helper methods like createDefaultSkybox requires the side effect import:
```
import "@babylonjs/core/Helpers/sceneHelpers"
```

Also the use of DDS files would require importing the dds loader for side effects:
```
import "@babylonjs/core/Materials/Textures/Loaders/ddsTextureLoader";
```

We totally understood that it is not ideal and that the discoverability is not great but this was the only way to maintain back compat. We are trying to find a way to enhandce both the doc and discoverability.

**Comment by sebavan** [comment]
Please do not hesitate to reopen if those imports were not sufficient, I am happy to help you find the one you miss.

**Comment by pierreglibert** [comment]
thanks @sebavan :)
