### ISSUE TITLE
Cloth is not simulated when attached to parent TransformNode

### ISSUE THREAD

**Issue by darkowic** [BabylonJS/Babylon.js#6552]
A ground cloth is not simulated when it has a parent TransformNode node. See reproduction case in the playground. You can comment out line 41 to fix the issue.

- Bug repro on [playground](https://playground.babylonjs.com/): https://playground.babylonjs.com/#T74IXV#1
- Expected result: Physics is simulated
- Current result: The cloth is not simulated

**Comment by TrevorDev** [comment]
In Babylon all physics is done in local space so adding a parent will cause unexpected behavior. Would you be able to position it using the cloth object instead or position the object with parents then unparenting before you add the physics impostor? I can add a warning in the console for this to make it more obvious.

**Comment by darkowic** [comment]
Do you have any reference to documentation about it? Warning should enough
for now. I have to say that it is not obvious and unexpected :)

wt., 2 lip 2019, 19:05 użytkownik Trevor Baron <notifications@github.com>
napisał:
