### ISSUE TITLE
Playground sample "Particle Subemitters" is broken

### ISSUE THREAD

**Issue by moderndev** [BabylonJS/Babylon.js#6558]
- Bug repro on [playground](https://playground.babylonjs.com):  https://www.babylonjs-playground.com/index.html#T0L01N#50
- Expected result: render
- Current result: blank scene

I haven't had time to debug this BUT something has broken this sample

**Comment by deltakosh** [comment]
Just hit a to start the system :D

**Comment by moderndev** [comment]
oops ... thanks
