### ISSUE TITLE
Mesh.setParent seems to break if a parent is already present

### ISSUE THREAD

**Issue by nbduke** [BabylonJS/Babylon.js#6571]
# Bugs
[This Playground](https://www.babylonjs-playground.com/#KSAH8T) demonstrates the issue. The cube is parented to the sphere and given a positional offset to make it visible. If you uncomment the `setParent(ground)` line, you'll see the box disappear; it actually moves into the sphere. Based on my understanding of `setParent`, the entire world matrix of a mesh (scaling, rotation, position) should be preserved after calling `setParent`, regardless of what the current or new parent is, so this is unexpected.

Oddly, if you also uncomment the `setParent(null)` line, the box doesn't move.

**Comment by deltakosh** [comment]
Good catch! I'll work on a fix asap!
