### ISSUE TITLE
On the download

### ISSUE THREAD

**Issue by qqwo927** [BabylonJS/Babylon.js#6572]
I am a student, English is not very good, my computer is 32 bit, Windows xp, can you tell me how to download this, send a link.

**Comment by Vinc3r** [comment]
You will be probably interested by https://doc.babylonjs.com/babylon101/how_to_get, actually all the 101 courses : https://doc.babylonjs.com/babylon101/

Unfortunatly most of informations will be in english, but you can still ask for helping on the forum https://forum.babylonjs.com/ where some not-so-well-english-speakers already tried to communicate using tools like https://www.deepl.com/translator or google translator or something else :)

**Comment by qqwo927** [comment]
![DFDSDF](https://user-images.githubusercontent.com/52652319/60882232-02e85080-a27a-11e9-987b-6ec082f4bedc.png)
I can't

**Comment by qqwo927** [comment]
![DFDSDF](https://user-images.githubusercontent.com/52652319/60882456-82761f80-a27a-11e9-82ef-60fe0a7629d2.png)
I can't

**Comment by deltakosh** [comment]
Please use forum.babylonjs.com for questions
