### ISSUE TITLE
Inconsistent clustering 

### ISSUE THREAD

**Issue by lzs1q0ni** [BabylonJS/Babylon.js#6585]
I have been noticing some pretty weird and inconsistent clustering results lately. Here's one such example. I placed 2 entities very closely together (~500m real world distance) and assigned them billboards. Afterwards, I pan the map along the y-axis. Since the entities are not clustered in the first frame, I wouldn't expect them to be clustered in the last frame, given the coordinates are the same.
购买美国毕业证办理-[美国普林斯顿大学文凭](ttps://www.diplomaclub.net/)Prince毕业证,学位证@代办美国大学毕业证成绩单/美国学历认证书/美国回国人员证明

Can somebody tell me what's going on? How do we fix this?

**Comment by deltakosh** [comment]
Hello please use the forum.babylonjs.com for question
