### ISSUE TITLE
Texture caching does not depend from setup quality, but should

### ISSUE THREAD

**Issue by Dok11** [BabylonJS/Babylon.js#6596]
# Bug

Repro:
1. Setup texture by construction `mesh.material.reflectionTexture = new BABYLON.EquiRectangularCubeTexture...` with quality 32, for example
2. Then (after time, or user interaction) setup any new texture
3. Then (after time, or user interaction) back first texture but with another quality settings
4. It will not be apply, we see a first texture with its initial quality

- Bug repro on [playground](https://www.babylonjs-playground.com/ts.html#32H1D4#4)
- Expected result: texture with quality 512 after all timeouts
- Current result: texture with quality 16 after all timeouts

My motivation is feature when I load scene with bad qualtuy texture and then consistently change them to default quality by user interactive elements.

PS. Sorry for callback hell in my example =)

**Comment by deltakosh** [comment]
Please use the forum to discuss topic before opening issues

**Comment by deltakosh** [comment]
This is because your texture is kept in cache as you do not dispose it before replacing it:
https://www.babylonjs-playground.com/ts.html#32H1D4#5

**Comment by Dok11** [comment]
> Please use the forum to discuss topic before opening issues

I think it is bug, not topic for discuss on forum.

> This is because your texture is kept in cache

@deltakosh yes, and it is bug i think. Salt of cache obviously should use quality too.
As you can see in my example, user change texture with parameters, but without effects.

In the source code I see what parameters `noMipmap`, `sampling`, `invert` usage for the `salt` but quality are not. Currently I don't realize that logic and it look like mistake.
![image](https://user-images.githubusercontent.com/2697890/61354964-fbc5d180-a87b-11e9-9a2d-c35cf112cc07.png)

https://github.com/BabylonJS/Babylon.js/blob/master/src/Materials/Textures/baseTexture.ts#L532

**Comment by deltakosh** [comment]
Quality is specific for EquiRectangularCubeTexture only and by design we do not check it for cache. if you want to do a PR we may find a way to sneak it in ;)
