### ISSUE TITLE
Improvements to VR Button

### ISSUE THREAD

**Issue by haroldma** [BabylonJS/Babylon.js#6598]
[The move to bottom right](https://github.com/BabylonJS/Babylon.js/blob/12a5f9b7ce49c8111cd14fea6254f19dffca5bed/src/Cameras/VR/vrExperienceHelper.ts#L925-L926) code doesn't always works. Both `canvas.top` and `offsetTop` don't always return the absolute position. In our canvas they both return zero. Instead you should rely on `getBoundingClientRect()`.

Another improvement is exposing the button itself. This will allow us to hide and show the button at will.

**Comment by deltakosh** [comment]
Definitely good idea. How about a PR?

**Comment by haroldma** [comment]
Sample code:
```
const rect: ClientRect = this._store.canvas.getBoundingClientRect();
vrButton.style.top = rect.top + rect.height - 70 + "px";
vrButton.style.left = rect.left + rect.width - 100 + "px";
```

**Comment by haroldma** [comment]
Will do a PR :+1:

**Comment by deltakosh** [comment]
You rock!
