### ISSUE TITLE
GLTF serializer doesn't resolve the promise in some cases

### ISSUE THREAD

**Issue by julien-moreau** [BabylonJS/Babylon.js#6605]
# Bug

- Bug repro on [playground](https://www.babylonjs-playground.com/#CQNGRK#35): https://www.babylonjs-playground.com/#CQNGRK#35 at line 40
- Expected result: the serializer should export and resolve the promise
- Current result:the serializer seems to never resolve the promise

This is working in most cases except this one mentioned in the above playground.
The start scene of the BabylonJS Editor also has the problem: https://github.com/BabylonJS/Editor/issues/144

**Comment by deltakosh** [comment]
@sebavan do you mind having a look?

**Comment by sebavan** [comment]
You ll have a fix in a couple of hours.

**Comment by julien-moreau** [comment]
You rox! Thanks a lot!
