### ISSUE TITLE
Inspector: Capture screenshot produces transparent image when engine preserveDrawingBuffer is false

### ISSUE THREAD

**Issue by darkowic** [BabylonJS/Babylon.js#6608]
Inspector's capture screenshot (See features https://doc.babylonjs.com/features/playground_debuglayer) produces transparent screenshot when Engine created with option `preserveDrawingBuffer: false` (default). There should be at least warning about it in the console if it is impossible.

# Bugs

- Bug repro on [playground](https://playground.babylonjs.com): Can not reproduce it in the playground - Engine is initiated with `preserveDrawingBuffer: true`. Download any playground, change `preserveDrawingBuffer` to `false` (or remove this option) and try to take a screenshot via the inspector.
- Expected result: Correctly capture scene screenshot.
- Current result: Captured screenshot is transparent.

Bugged screenshot - transparent:
![screenshot_19-7-21_9-59](https://user-images.githubusercontent.com/11510581/61588574-4c03a300-ab9e-11e9-8cff-e52f71a25626.png)

**Comment by deltakosh** [comment]
Hey please use the forum to discuss. This is by default. We mentioned it in the doc: https://doc.babylonjs.com/how_to/render_scene_on_a_png#createscreenshot

**Comment by darkowic** [comment]
I was searching for it through the inspector features - https://doc.babylonjs.com/features/playground_debuglayer. Maybe it is worth to add a note about it there too?

**Comment by deltakosh** [comment]
Sure (or at least point to the screenshot doc :))
Fancy doing a PR?
