### ISSUE TITLE
Can we create a gitter room?

### ISSUE THREAD

**Issue by QuantumInformation** [BabylonJS/Babylon.js#661]
This would be handy way to ask questions with other users of Babylon.js.

see https://gitter.im/

**Comment by deltakosh** [comment]
hey we have a forum for that :)

**Comment by QuantumInformation** [comment]
I know about the forum but a lot of developers prefer things like Slack and glitter. Its a lot faster to bounch ideas about and communicate. It can only help things I feel.

**Comment by RaananW** [comment]
I remember opening the room and waiting there. No one logged in.
I think the majority of the community prefers the forum. There is also an unused chat room on the forum's website. So I guess it's not what people want...

**Comment by QuantumInformation** [comment]
When did you make it? It seems that there are plenty of watchers and users now..

**Comment by RaananW** [comment]
A long long time ago. In this galaxy thou. I think a few months ago. I just checked, there is one single user in :-)
Not all of Babylon's users are Github users as well. Some even report bugs in the forum and not here, which is totally fine.

**Comment by es6Test** [comment]
Whats the url? the way most people find it is from the readme.
