### ISSUE TITLE
Feature Request: Decal Mode For Spotlights

### ISSUE THREAD

**Issue by etienne212** [BabylonJS/Babylon.js#6613]
## Feature Description:
Am attempting to use a spotlight's texture projection as a way to project a video/images synced with both stationary and moving geometry. A big issue is that I am unable to make the texture more opaque/visible especially in higher ambient light levels, and increasing intensity introduces distortion and glare from the lighting. 

## Feature request:
Add in a field that would allow a decal type mode where it adds just the projection texture without introducing any other lighting effects. 

Link To Forum: https://forum.babylonjs.com/t/help-with-projection-textures/4463

**Comment by deltakosh** [comment]
Well unfortunately after doing some experiments it does not work as expected. The light cannot easily (like quite too complex) be removed of the light equation.

I wondering if you can try to use a second uv set that wraps the entire surface and set an emissive texture on that set? Maybe we can try to find a solution on the forum thread :)
