### ISSUE TITLE
Fix Ammo.js CDN link

### ISSUE THREAD

**Issue by CodingMadeEasy** [BabylonJS/Babylon.js#6619]
https://cdn.babylonjs.com/Ammo.js

The following link doesn't work and it's mentioned on the following tutorial page: 
https://doc.babylonjs.com/how_to/using_the_physics_engine

**Comment by deltakosh** [comment]
Fixed ;D

**Comment by CodingMadeEasy** [comment]
I'm still see 404 not found :(

**Comment by deltakosh** [comment]
I fixed the doc to the right link: https://cdn.babylonjs.com/ammo.js
