### ISSUE TITLE
Allow (VR) 180 Videos using the VideoDome

### ISSUE THREAD

**Issue by RaananW** [BabylonJS/Babylon.js#6624]
At the moment, the video dome is a sphere supporting full 360 videos. 180 videos should be projected on half of the dome (from part), and leave the back part texture-less.

Initial conversation and playground can be found here - 

https://forum.babylonjs.com/t/180-degree-3d-video-vr180-support/4681

**Comment by deltakosh** [comment]
Thanks a lot @RaananW !!!
