### ISSUE TITLE
Animations are not exported by GLTF2Export

### ISSUE THREAD

**Issue by fselcukcan** [BabylonJS/Babylon.js#6628]
# Feature request

- Link to [forum]() discussion about the feature:
https://forum.babylonjs.com/t/animations-lost-when-exported-with-gltf2export-glbasync/4460
- Feature description:
1. I get models from BJS github, or oher model archive
2. then import into this [PG](https://www.babylonjs-playground.com/#5A7400#1) and exported it with the code. (Then put it into a public github repository to import below again)
3. Then imported to another [PG](https://playground.babylonjs.com/#SMYK75), or an app with BJS scene which is on my _localhost_, but animations are gone, no _Animation Groups_ section in _Scene Explorer_ or visible animation.
Also when I download and import the original github models to my BSJ scene they also work.
Something happens when I run export methods.

Acording to recent conversation in _forum_ in above link exporting skins is not implemented yet.

- Additional links that could help implementing the feature:

**Comment by deltakosh** [comment]
thanks a lot for this request. @Drigax will look at it (but not now as he already has a lot to deal with exporters :))

Feel free to help if you want

**Comment by fselcukcan** [comment]
thanks. I would love to. What kind of task is at hand? Can I getr some leads while I go into codebase to look around?

**Comment by deltakosh** [comment]
This is the right place

**Comment by deltakosh** [comment]
any news?

**Comment by fselcukcan** [comment]
Unfortunately not any so far. Only if I had the time these recently. :|

**Comment by Drigax** [comment]
I started by creating this test harness so I can quickly evaluate glTF sample models:
https://playground.babylonjs.com/#T087A8#1

Testing this asset import->export->import round trip with AnimatedCube, I can see that our node animation export works fine. That's somewhat of a relief, as I'm not too worried about glTF animation accessor and sampler being properly setup.

Looking back at the forum post, I can see that we're testing against alien from our meshes library, which also includes Morph target and skeletal animation. I'll update my PG to use this asset instead, as its pretty comprehensive as far as export capabilities go.

**Comment by Drigax** [comment]
Alien test bench has been completed. Going to close this issue to roll into #5100
