### ISSUE TITLE
Error handler not invoked when trying to load texture that has already failed to load

### ISSUE THREAD

**Issue by nbduke** [BabylonJS/Babylon.js#6632]
# Bugs
Repro playground: https://www.babylonjs-playground.com/#68BS34

I'm trying to demonstrate a scenario where you try to load a texture and it fails (here, I'm using a file that is *not* a texture, but the issue should be general to any kind of loading failure). As expected, the error handler for that texture is invoked. Later, if you try to load a texture with that same URL, the error handler won't be invoked, leaving you in a state of perpetually waiting for the texture.

It doesn't seem to matter whether the second attempt happens synchronously or after some delay; see https://www.babylonjs-playground.com/#68BS34#1.

**Comment by deltakosh** [comment]
On it

**Comment by deltakosh** [comment]
ok this is expected as the first texture is still in cache.
Just call texture.dispose() and you should be good:
https://www.babylonjs-playground.com/#68BS34#2

**Comment by nbduke** [comment]
Hmm, should Texture auto-dispose in the error case? What can you realistically do with a texture that has errored out?

**Comment by deltakosh** [comment]
You may want to reuse it. Instead of creating a new one (with texture.updateUrl())

**Comment by nbduke** [comment]
Fair enough. Thanks :)
