### ISSUE TITLE
glTF: MIME type based image loading

### ISSUE THREAD

**Issue by zeux** [BabylonJS/Babylon.js#6636]
It looks like glTF loader doesn't support image loading based on MIME type information right now.

For example, Basis and DDS loaders use URI extension to disambiguate file formats. However, this makes it impossible to embed images into GLB buffers and use mimeType (e.g. image/basis) to differentiate the contents.

An upcoming extension, KHR_image_ktx2, will allow using KTX2 textures from GLTF files but it also relies on mimeType (`image/ktx2`) when image is embedded.

**Comment by bghgary** [comment]
Thanks @zeux for the issue. I will take care of this when I complete my implementation of KHR_image_ktx2.

**Comment by zeux** [comment]
Thanks! I was trying to figure out if there's a path to support Basis in glTF that did *not* rely on KHR_image_ktx2 but between https://github.com/BinomialLLC/basis_universal/issues/52 and the upcoming glTF extensions it sounds like the actual .basis format won't have any overlap with glTF long-term, so I'll close this - KHR_image_ktx2 can be tracked separately.
