### ISSUE TITLE
Multiview does not support built-in line shaders

### ISSUE THREAD

**Issue by delaneyj** [BabylonJS/Babylon.js#6665]
Per [discussion on the forum](https://forum.babylonjs.com/t/vr-quest-multiview-missing-content/4920/2), MultiView does not support all built-in shaders.  As a side note; it would be ideal if the needed changes to custom shaders to support Multiview was [part of the documentation on the subject](https://doc.babylonjs.com/how_to/multiview).

# Bugs
- Bug repro on [playground](https://playground.babylonjs.com/#365m82):

- Expected result:
Visible lines in Multiview mode

- Current result:
At least of the Oculus quest it is not visible when VR mode is entered.

**Comment by deltakosh** [comment]
@RaananW: Interested by this one?
