### ISSUE TITLE
Wrong skeletonID in Blender export

### ISSUE THREAD

**Issue by daniel-nth** [BabylonJS/Babylon.js#669]
We have two armatures in a .blend file. When exporting, using exporter 3.0.2, these get exported with the IDs 0 and 1 in the .babylon's *skeletons* array. Strangely, the meshes try to reference them by the *skeletonID*s 0 and 4. 0 works, but 4 obviously doesn't. 
The skeleton with ID 1 is not even loaded by *BABYLON.SceneLoader.ImportMesh*. In the callback function, *Skeleton[]* has a length of 1. When I change the wrong *skeletonID* from 4 to 1 in the .babylon file by hand, everything works as expected.
Is this an error on our part, or does the export mix up the IDs?

The scene in question is available at https://github.com/daniel-nth/babylon-skeletonid-test

Thanks for your awesome work!

**Comment by deltakosh** [comment]
Hello can you please use the forum for questions?

**Comment by daniel-nth** [comment]
Sure, sorry.
