### ISSUE TITLE
Support for WebGPU on Safari tech preview..

### ISSUE THREAD

**Issue by oscarbg** [BabylonJS/Babylon.js#6695]
Hi,
recent Safari tech preview builds runs OK WebGPU demos from:
https://webkit.org/demos/webgpu/
like the compute demo:
https://webkit.org/demos/webgpu/compute-blur.html
so trying Forest WebGPU demo:
https://www.babylonjs.com/demos/webgpu/forestwebgpu
I was expecting to perhaps work much like it worked on Chrome nightly when I tested a month ago or so..

Safari javascript debugger points to "setSubData is not a function":
```
// TODO WEBGPU.
        // Deprecated soon to be removed... replace by mappedBuffers
        buffer.setSubData(dstByteOffset + offset, src, srcByteOffset + offset, byteLength - offset);
```
in simpler Sphere demo:
https://www.babylonjs.com/demos/webgpu/onespherewebgpu

I understand API& spec is not finalised but would be nice to compare perf of Chrome vs Safari WebGPU implementations if possible..

another concern is also you feed WHLSL or SPIR-V code in your demos? as Safari only allows WHLSL I believe:
(https://webkit.org/demos/webgpu/compute-blur.html)
```
[numthreads(${threadsPerThreadgroup}, 1, 1)]
compute void horizontal(constant uint[] source : register(u${sourceBufferBindingNum}),
                        device uint[] output : register(u${outputBufferBindingNum}),
                        constant float[] uniforms : register(b${uniformsBufferBindingNum}),
                        float3 dispatchThreadID : SV_DispatchThreadID)
{
    int radius = int(uniforms[0]);
    int rowStart = ${image.width} * int(dispatchThreadID.y);
    int rowEnd = ${image.width} * (1 + int(dispatchThreadID.y));
    uint globalIndex = uint(rowStart) + uint(dispatchThreadID.x);

    uint[4] channels;

    for (int i = -radius; i <= radius; ++i) {
        uint startColor = source[horizontallyOffsetIndex(globalIndex, i, rowStart, rowEnd)];
        float weight = uniforms[uint(abs(i) + 1)];
        accumulateChannels(@channels, startColor, weight);
    }

    output[globalIndex] = makeRGBA(channels[0], channels[1], channels[2], channels[3]);
}
```

**Comment by sebavan** [comment]
I currently match up everything to Chrome build so I rely on SPRI-V for the shaders. As long a decision is not made by the WebGPU group, I might only support SPIR-V as I can rely with some trickery and shaderc to compile on the client glsl code to SPIR-V.

About setSubData, despite being pulled out from the spec, it is an amazingly simple way to update data to buffer and Chromium is currently keeping it to see if we could add it back but it sounds unlikely. I hope it would stay as this is the kind of convenient APIs that makes it easy to start with implementation.

I will close the issue as a Won't fix... For Now, at least until the shader language for WebGPU has been agreed upon by the WebGPU folks. And I will add a new task to the #6443 issue to ensure we cover it.

**My wish would be to have GLSL compatible with WebGL without any extra tooling but this is even not in consideration unfortunately :-( It would have been amazing to just reuse what we have...

Also, I wish the convenient helpers would stay and be part of the spec to simplify and accelerate all the Webdevs rampup :-)**

On the bright side, we now have a WebpGPU playground: https://playground.babylonjs.com/indexwebgpu.html

**Comment by oscarbg** [comment]
thanks for informative answer.. makes sense..
