### ISSUE TITLE
Feature: A possibility to set any mesh as the global audio listener

### ISSUE THREAD

**Issue by Foxhoundn** [BabylonJS/Babylon.js#6700]
Hey all,

This is my first contribution, so let me start by saying how amazing BabylonJS is, and thanks to all working on this project.

Regarding this feature: currently, the only possible listener for any spatial sounds in the scene is the active camera. This is fine in all cases where the active camera is actually "you".

**The problem:**
In my game, the camera is positioned always at the `Vector3(0, 105, 105)` and follows the player around. If the player encounters door for example, that has sound attached to it with spatial distance of 60, the camera will not be able to hear that sound (simply because it's too far away). Right now I am solving this by creating all sounds in the same distance of it's mesh as the camera is from player (so the sound position is `mesh.position + Vector3(0, 105, 105)`). This works, if the camera is static and is not rotating with the player object.

**The solution:**
Maybe I am naive, but by reverse engineering the audio engine, I realised the solution should be very simple.

In the file [https://github.com/BabylonJS/Babylon.js/blob/d7827d78296faf574984a370dbe25a0a7b93d63f/src/Audio/audioSceneComponent.ts](url) on line 387 we have the `_afterRender` function that determines the camera's global position and set's the listener position.

```
 private _afterRender() {
        const scene = this.scene;
        if (!this._audioEnabled || !scene._mainSoundTrack || !scene.soundTracks || (scene._mainSoundTrack.soundCollection.length === 0 && scene.soundTracks.length === 1)) {
            return;
        }

        var listeningCamera: Nullable<Camera>;
        var audioEngine = Engine.audioEngine;

        if (scene.activeCameras.length > 0) {
            listeningCamera = scene.activeCameras[0];
        } else {
            listeningCamera = scene.activeCamera;
        }

        if (listeningCamera && audioEngine.audioContext) {
            audioEngine.audioContext.listener.setPosition(listeningCamera.globalPosition.x, listeningCamera.globalPosition.y, listeningCamera.globalPosition.z);
        ...
```

My proposal is - Add new method `setListener, that would set an internal property `this.customListener`. Then simply check if customListener is set and use its _absolutePosition_, if it's not set, use the camera.

```
 private _afterRender() {
        const scene = this.scene;
        if (!this._audioEnabled || !scene._mainSoundTrack || !scene.soundTracks || (scene._mainSoundTrack.soundCollection.length === 0 && scene.soundTracks.length === 1)) {
            return;
        }

        var listener: Nullable<Camera | Mesh | AbstractMesh>;
        var listenerPositionKey: 'globalPosition' | 'absolutePosition' = 'globalPosition';
        var audioEngine = Engine.audioEngine;

        if (this.customListener && !this.customListener.isDisposed() && this.customListener.isEnabled()) {
            listener = this.customListener;
            listenerPositionKey = 'absolutePosition'
        }
       else if (scene.activeCameras.length > 0) {
            listener = scene.activeCameras[0];
        } else {
            listener = scene.activeCamera;
        }

        if (listeningCamera && audioEngine.audioContext) {
            audioEngine.audioContext.listener.setPosition(listener[listenerPositionKey].x, listeningCamera[listenerPositionKey].y, listeningCamera[listenerPositionKey].z);
        ...
```

I am very happy to implement this if you decide to move forward. I do not have a VR headset so I will not be able to test the code that follows this regarding cameras in VR, so a help would be needed unfortunately.

Thanks!

**Comment by Foxhoundn** [comment]
Another possibility how to solve this would be to open the `setPosition` method to the public, and if the user decides use their own position, do not set the position automatically within the `_afterRender` method.

**Comment by deltakosh** [comment]
I would prefer option B. If setPosition was called we simply use it. Else we use camera.globalPosition

Thanks a ton for your interest and you can definitely go ahead with a PR

Welcome in the family :D

**Comment by Foxhoundn** [comment]
Update @deltakosh :

It seems that the `_afterRender` function of AudioSceneComponent runs _before_ any custom `onAfterRenderObservable` calls, which makes it impossible to detect if the user has already set the listener position themselves (unless they'd do it in `onBeforeRender...`).

One way this could be done, which would have minimum impact on the Babylon code base would be to introduce a new flag on the scene object called something like `useCustomListenerPosition`, where we would not set the listener position automatically and the user would have to do it themselves (either in the render cycle or statically).

This would have minimal code implications, and there would be no "magic" under the hood.

Although, I am not sure how to handle this part of code
```
            var i: number;
            for (i = 0; i < scene.mainSoundTrack.soundCollection.length; i++) {
                var sound = scene.mainSoundTrack.soundCollection[i];
                if (sound.useCustomAttenuation) {
                    sound.updateDistanceFromListener();
                }
            }
            if (scene.soundTracks) {
                for (i = 0; i < scene.soundTracks.length; i++) {
                    for (var j = 0; j < scene.soundTracks[i].soundCollection.length; j++) {
                        sound = scene.soundTracks[i].soundCollection[j];
                        if (sound.useCustomAttenuation) {
                            sound.updateDistanceFromListener();
                        }
                    }
                }
            }
```

in which all the sounds with custom attenuation are updated to reflect the new listener position.

If we were able to make sure the `_afterRender` function runs _after_ user defined after render calls, we could do this by simply checking if a listener position has been set for this frame.

**Comment by deltakosh** [comment]
Other option: we define scene.getAudioListener position as a () => Vector3. So users can provide it and it will be called automatically when we need it.

Not sure to understand why there is a problem with the code you mentioned. As soon as the audio is set up with the new listener position we are all set and nothing else should change

**Comment by Foxhoundn** [comment]
@deltakosh You mean that the user would define it as 

```
scene.getAudioListenerPosition = () => {
    return myMesh.absolutePosition;
}
```

and then we would call this function in the `_afterRender` function ?

**Comment by deltakosh** [comment]
correct :) this way we have an easy implementation while being really flexible for the user
