### ISSUE TITLE
Feature: Using one scene on multiple canvases

### ISSUE THREAD

**Issue by rocos-yishi** [BabylonJS/Babylon.js#6703]
# Feature request
## Link to [forum](https://forum.babylonjs.com/) discussion about the feature: 
- https://forum.babylonjs.com/t/using-one-scene-on-multiple-canvases/2819

## Feature Description

> I’m trying to use the same scene, but render them on 2 different canvases, and then for each canvas use a different camera angle.
> 
> All I can seem to get working now is have 2 instances of Engine, which is fine, but then to get one scene to render on both Engines/Canvases doesn’t seem to be possible, since the Scene wants an ‘engine’ instance.
> 
> I also want to avoid having 1 canvas with 2 viewports.
> I want to avoid having 2 instances of the same scene, basically doing double the work.
> Is it possible to just have one canvas re-use the scene data that was rendered on another canvas (I guess that means there is always one ‘first’ scene with a parent canvas, and then other canvasses can ‘inherit’ the scene without having to recalculate the scene, but only a different camera angle)

**Comment by deltakosh** [comment]
https://forum.babylonjs.com/t/new-feature-multi-canvases-rendering/6426
