### ISSUE TITLE
Bug: export gltf image paths with spaces

### ISSUE THREAD

**Issue by schiette** [BabylonJS/Babylon.js#6705]
When exporting a gltf (not gltb) that have materials using images with spaces in their name (MOSS TEXTURE.JPG), the exporter uses the wrong path in the images section. The textures section of the gltf works fine. 

Images section: notice the %20 in the name
![image](https://user-images.githubusercontent.com/29231922/62795796-8679a500-baa5-11e9-8a89-b0b74851d4e1.png)

Textures section: correct texture paths
![image](https://user-images.githubusercontent.com/29231922/62795879-bde85180-baa5-11e9-9cd9-5ee46244c605.png)

Other gltf importers are failing because of this issue (for example the gltf importer for blender 2.8).

**Comment by deltakosh** [comment]
@bghgary can you ahve a look at this bug? Thanks a lot!

**Comment by bghgary** [comment]
A URI is not a name. URI are required to be encoded per URI spec. This section describes the requirement for glTF:
https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#uris

**Comment by julienduroure** [comment]
I just pushed a fix on blender glTF importer to decode URI escaped chars

**Comment by bghgary** [comment]
For more context, here is the link to the issue discussing this on the glTF spec: https://github.com/KhronosGroup/glTF/issues/1449

**Comment by schiette** [comment]
@julienduroure  Thanks so much for fixing this on blender!
