### ISSUE TITLE
HTMLCanvasElement.toDataURL()

### ISSUE THREAD

**Issue by unicomp21** [BabylonJS/Babylon.js#671]
This is a problem when generating textures using 2D canvas.

    material.diffuseTexture = new BABYLON.Texture(canvas.toDataURL(), scene);

BJS - [04:24:11]: Babylon.js engine (v2.1.0) launched
Uncaught TypeError: Cannot read property 'replace' of null
  r.CleanUrl	
  r.LoadImage	
  a.createTexture	
  i	
  createScene	
  (anonymous function)

**Comment by Palmer-JC** [comment]
static Texture.createFromBase64String() works for me.
https://github.com/BabylonJS/Babylon.js/blob/master/src/Materials/Textures/babylon.texture.ts#L245

My textures are generated from either of the 2 Blender exporters though.  Not sure what toDataURL() generates.

**Comment by Palmer-JC** [comment]
do a forum search on '.toDataURL()'

**Comment by haykam821** [comment]
Fixed @Palmer-JC's dead link: https://github.com/BabylonJS/Babylon.js/blob/fb7843589dd581284295b50e21ae91bba97cd723/src/Materials/Textures/texture.ts#L702
