### ISSUE TITLE
Feature: A-Frame but based on Babylon.JS

### ISSUE THREAD

**Issue by karanganesan** [BabylonJS/Babylon.js#6710]
Does anyone know something like this been built / is someone working on something like this ?

Just wondering. Composing 3D/VR experience with HTML and a powerful ECS would be great to see :)

**Comment by deltakosh** [comment]
Hey! please use our forum for questions: forum.babylonjs.com

some links in the meantime: 
- https://doc.babylonjs.com/how_to/webxr
- https://doc.babylonjs.com/how_to/webvr_camera
- Viewer (which is comparable to aframe): https://doc.babylonjs.com/extensions/the_babylon_viewer
