### ISSUE TITLE
HTC Vive throwing error when entering VR (Vive/Firefox Nightly)

### ISSUE THREAD

**Issue by Exolun** [BabylonJS/Babylon.js#6711]
Currently seeing an error right after entering VR on the HTC vive that reads 'e.orientation is null' via a call chain ending with checkInputs > updateFromDevice.  I'm guessing the error originates from webVRCamera.ts - but I was running on the minified version of BabylonJS so I can't be much more specific!

Seems to happen on any playground - here is a link to one of the WebVR playgrounds:
[https://www.babylonjs-playground.com/#B4C2AH](https://www.babylonjs-playground.com/#B4C2AH)

**Comment by deltakosh** [comment]
Pinging the almighty @RaananW  ;D

**Comment by deltakosh** [comment]
Ok i tried something :) But as I cannot repro @Exolun do you mind testing with the latest preview? Can you also let me know where the error is precisely using this url: https://www.babylonjs-playground.com/debug.html#B4C2AH

**Comment by RaananW** [comment]
I cannot reproduce this as well. @deltakosh , did you add this - https://github.com/BabylonJS/Babylon.js/blob/master/src/Cameras/VR/webVRCamera.ts#L466 ? 

poseData.orientation is part of the API specifications. If this solves the problem there is a problem with firefox nightly and WebVR. They either moved to a different spec version (which i doubt) or (maybe) they skip a frame and poseData doesn't exist. 

Either way - it seems odd. Is it working in the latest stable firefox? in firefox for developers? 

I dont have a vive, so i can't check this specific device. Was there any driver update that you know of?

**Comment by deltakosh** [comment]
Yes I added that additional check just in case.

**Comment by Exolun** [comment]
Yep it looks like this issue was on my end / Firefox's issue.  It's broken in Nightly, which I was using because the Vive wasn't working for me on Stable either but wasn't producing an error.  As it turns out, the Vive only works on the x64 installation of Firefox.  In my case I hadn't exercised enough discretion selecting an installer and had x86 installed.

Works in stable /x64 Firefox.
