### ISSUE TITLE
VRHelper.onNewMeshSelected cannot determine controller

### ISSUE THREAD

**Issue by millenniummike** [BabylonJS/Babylon.js#6717]
VRHelper.onNewMeshSelected.add(function(mesh) {
    selectedMesh = mesh;
});

There is no way of determing which controller selected a mesh

# Bugs

- Bug repro on 
https://www.babylonjsplayground.com/#B4C2AH

Select mesh with right controller
Pull trigger on left controller

 Expected result:
Mesh will not be attached to right controller

- Current result:
Mesh is attached to right controller

# Feature request

- Link to [forum](https://forum.babylonjs.com/) discussion about the feature:
- Feature description
- Additional links that could help implementing the feature:

**Comment by deltakosh** [comment]
Hello before opening an issue, please discuss the problem on the forum as we may provide solution :)
