### ISSUE TITLE
Right Hand System Bug report

### ISSUE THREAD

**Issue by Zcating** [BabylonJS/Babylon.js#6752]
https://forum.babylonjs.com/t/solved-unexpected-light-gizmo-on-right-hand-system/5043/12

I found a new Question in Right Hand System. The direction's coordinates of the light(directional & spot) will be setted as negative when you use Right Hand System and attach with light gizmo.

**Comment by Zcating** [comment]
I found a solution. Adding this code in 'lightGizmo.ts' .

```
public set light(light: Nullable<Light>) {
// ...
    if ((light as any).direction) {
        const direction = (light as any).direction.clone() as Vector3;
        if (this.light.getScene().useRightHandedSystem) {
            direction.x = -direction.x;
            direction.y = -direction.y;
            direction.z = -direction.z;
        }
        this.attachedMesh!.setDirection(direction);
    }
//...
}
```

**Comment by deltakosh** [comment]
Please keep the discussion on the forum
