### ISSUE TITLE
Existing Typescript Playgrounds Redirected to Javascript or Default

### ISSUE THREAD

**Issue by BabylonJSGuide** [BabylonJS/Babylon.js#6755]
Existing playgrounds that have the form 
`http://www.babylonjs-playground.com/ts.html#ABCDE#xx` redirect to `http://www.babylonjs-playground.com/#ABCDE#xx` which may or may not exist. If they exist they redirect to the Javascript PG  and and if not they redirect to the default.

**Comment by BabylonJSGuide** [comment]
I think I was wrong about the redirect to default. When http://www.babylonjs-playground.com/ts.html#ABCDE#xx redirects to http://www.babylonjs-playground.com/#ABCDE#xx and http://www.babylonjs-playground.com/#ABCDE#xx does not exist then it loads correctly as a typescript file. So the only issue is when it already exists.

**Comment by Jaskar** [comment]
Hi!
Should redirect to http://www.babylonjs-playground.com/index.html#ABCDE#xx
I can't currently work on a computer but told @noalak how to do this. So he should help

**Comment by BabylonJSGuide** [comment]
Turns out that 'http://www.babylonjs-playground.com/index.html#ABCDE#xx` redirects to `http://www.babylonjs-playground.com/#ABCDE#xx` as well.

Is there a way of searching the playground database to check how many urls have both /ts.html#ABCDE#xx and /#ABCDE#xx I suspect there will not be many. It will probably turn out to be only the ones I made for this docs page https://doc.babylonjs.com/features/playground in which case I could produce new typescript examples.

**Comment by BabylonJSGuide** [comment]
Perhaps I overreacted and it would be sufficient for me to do new Typescript examples on the features page for the Intro to PG and wait to see if anyone brings up a problem with this in the future. 

Close the issue if you think this would a solution. Sorry for being a pain.

**Comment by deltakosh** [comment]
Nope I really want to make sure that no breaking changes was introduced :) So no overraction here. Every that worked must keep working

**Comment by Jaskar** [comment]
Hi @BabylonJSGuide ,

As the JS and TS playgrounds share the same database, I'm pretty sur that each playground hash is unique. So, no JS and TS playgrounds should share the same one.

You're saying that 

> It will probably turn out to be only the ones I made for this docs page https://doc.babylonjs.com/features/playground

Can you tell me more about this ? You can't technically choose your hash ?


Concerning the redirection, it's the desired behavior.
As duplicating the code over index.html & ts.html was laborious, we decided to merge everything in the index.html.
So, the ts.html#ABCDE#xx redirect to index.html#ABCDE#xx then load it as it is (JS or TS).

You can check this old TS playground 
https://www.babylonjs-playground.com/ts.html#H3AF26#1

BUT, if you find any thing broken, do not hesitate to prove me that I'm wrong ! We're here to make the playground easy and pleasant to use for anyone.

Do not hesitate to ping @noalak for help, as I'm currently in holidays :)
For any emergency he'll reach me.

Anthony.

**Comment by BabylonJSGuide** [comment]
@noalak 
These are the Typescript PGs that are causing problems 

http://www.babylonjs-playground.com/ts.html#6F0LKI
http://www.babylonjs-playground.com/ts.html#6F0LKI#1
http://www.babylonjs-playground.com/ts.html#6F0LKI#2

because these Javascript PGs already existed

http://www.babylonjs-playground.com/#6F0LKI
http://www.babylonjs-playground.com/#6F0LKI#1
http://www.babylonjs-playground.com/#6F0LKI#2

As I said these are the possibly the only ones because at the time I constructed the docs page since ts.html was a separate url using the same hash codes made some sort of sense.  (I probably just added ts.html to the existing urls and wrote the typescript code, don't remember exactly what I did) If this is the case than I need to provide different examples. The section of the docs needs a re-write now anyway.

**Comment by BabylonJSGuide** [comment]
So, the ts.html#ABCDE#xx redirect to index.html#ABCDE#xx then load it as it is (JS or TS).

This could also be the reason for issue #6760. It may be the intention that if you are on a JS or TS existing page you cannot swap out to the other. If so, for me, this is strange as then the TS JS menu items appear not to work unless you CLEAR or NEW. This could be made clear in the docs but of course not many people would go to the docs to find out how menu buttons work.

On the other hand perhaps I (or my laptop) have a built in fault. :D

**Comment by deltakosh** [comment]
@BabylonJSGuide: Yes this ones are a bit tricky as they were done manually. I would recommend to provide different examples. 

@noalak will update the playground to make sure people understand that clicking on a different language (like TS->JS) will wipe their code and switch to a different PG

**Comment by BabylonJSGuide** [comment]
Yes this ones are a bit tricky as they were done manually. I would recommend to provide different examples. 

Could well be the only examples, I haven't found any others yet. Hence my suggestion I just re-write that section of the docs and in the unlikely event of someone find another deal with it individually.

**Comment by BabylonJSGuide** [comment]
Yes this ones are a bit tricky as they were done manually. I would recommend to provide different examples. 

Could well be the only examples, I haven't found any others yet. Hence my suggestion I just re-write that section of the docs and in the unlikely event of someone find another deal with it individually.

**Comment by deltakosh** [comment]
yep I agree

**Comment by BabylonJSGuide** [comment]
Relevant doc page updated and PR submitted
