### ISSUE TITLE
Purpose of Typescript Javascript Menu Items in Playground

### ISSUE THREAD

**Issue by BabylonJSGuide** [BabylonJS/Babylon.js#6760]
Ref:

> If the current PG is in Javascript and you switch to Typescript the current PG holds, and vice versa

from
https://forum.babylonjs.com/t/please-welcome-the-new-playground/5135/14?u=johnk

May be related to #6755

Maybe its just me, or maybe I am missing something but I find the Typescript Javascript Menu Items in the playground a bit strange. Why?

[In the following argument the words Typescript and JavaScript can be swapped over]

A new Babylon.js user comes across a JavaScript playground (via the forum for example) and sees Typescript on the menu. "Wow" he says "I can use Typescript in the playground and gives it a click. Something appears to be happening, the menu bar takes on an orange appearance, he waits in anticipation and then, "Oh its gone back to JavaScript", he says "Now what".

Luckily he is the persevering type and goes to the docs https://doc.babylonjs.com/features/playground#playground-url-formats and follows the first Typescript link, "Excellent" he thinks "I now can write Typescript code". "Next time" he thinks "I will just type in the URL `https://www.babylonjs-playground.com/#`. When he does this he is pleased to find it does take him to the basic Typescript PG. Looking at the table at https://doc.babylonjs.com/features/playground#playground-url-formats again he does think it a bit strange that the first JavaScript link in the table is also `https://www.babylonjs-playground.com/#` and clicking on it leads to a Javascript PG. "One URL two sites?, A little weird!" he thinks.

Further persevering he finds that if he first clicks on the NEW button or CLEAR (DELETE?)  button and then on the Typescript menu item he will be taken to a Typescript PG. "Why do not NEW and CLEAR lead to a choice of Typescript or Javascript and just use Typescript or Javascript as labels to show which language is used?" he thinks.

Of course the answer to this last question is that having both on the menu makes it clear that both are available. IMHO it would be less confusing and make more sense that clicking on Typescript actually took you to the basic Typescript PG and vice versa.

Thoughts?

**Comment by deltakosh** [comment]
Well when I click on Typescript (even if we agree on the color issue that was flagged for @PatrickRyanMS), you switch to TS in the editor.

We maybe need to mention on the doc that by default the playground is in JS mode unless you open it using ts.html ?

New and clear will behave based on the current mode (TS or JS)

I need to check with @PatrickRyanMS  to see how we can better indicate the current mode and have an option somewhere (but less prominent) that you can change modes

**Comment by BabylonJSGuide** [comment]
Still having the same issue, for example when I go to https://playground.babylonjs.com/#QYFDDP#1 and click on the Orange Typescript on the menu it tries to go to Typescript but then goes back to the same Javascript content. I have tried Firefox, Chrome and Edge and get the same result.

Going to https://www.babylonjs-playground.com/#0X3431#1 which is a Typescript playground and clicking on Javascript just end up back at the Typescript page.

I have tried several different Javascript and Typescript playgrounds and the same happens each time. The only existing playground where I can swap back and forth is https://www.babylonjs-playground.com/#

Do not understand why it works for you and not me :(

**Comment by deltakosh** [comment]
> Still having the same issue, for example when I go to https://playground.babylonjs.com/#QYFDDP#1 and click on the Orange Typescript on the menu it tries to go to Typescript but then goes back to the same Javascript content. I have tried Firefox, Chrome and Edge and get the same result.

I agree this is not good. I'll chat with @noalak to fix that issue

Same for the other way around

**Comment by Jaskar** [comment]
As the second one is a Typescript Playground, isn't it the wanted behavior to stay on the Typescript mode ? Because if it switch to Javascript mode, it will not compile correctly and only display an error message ?

For the other way (JS to TS), can make sense.

**Comment by deltakosh** [comment]
Switching to JS will also wipe the content (as long as we have a warning before)
Same if you switch to TS actually

**Comment by BabylonJSGuide** [comment]
Thank you everybody. I think that the TS JS menu button's purpose is now clear.
