### ISSUE TITLE
GPU Particle System Zero EmitRate Still Emits Particles

### ISSUE THREAD

**Issue by MackeyK24** [BabylonJS/Babylon.js#6863]
The GPU Particle System continues to emit particles **AFTER** setting emitRate = 0.

Please refer to the forums post for details: 

https://forum.babylonjs.com/t/gpuparticlesystem-emitrate-zero-bug/5718

**Comment by MackeyK24** [comment]
Example playground showing problem. It **SHOULD** stop emitting after 5 seconds, but does not:

https://www.babylonjs-playground.com/#NHREL6

**Comment by deltakosh** [comment]
Nope this is expected. Check the doc: https://doc.babylonjs.com/babylon101/particles#gpu-particles
(in the Stopping a GPU Particle System to see h ow to stop emitting particles)

**Comment by MackeyK24** [comment]
Will it always be like that. You have to dispose the whole particle system and re create again when you want to emit 😕

**Comment by deltakosh** [comment]
Correct. It is a technical limitation of how GPU particle works
