### ISSUE TITLE
no click event triggered on textblocks inside a stackpanel inside a scrollviewer.

### ISSUE THREAD

**Issue by dptalks** [BabylonJS/Babylon.js#6865]
i like to add a menu with GUI.TextBlock() entries in a GUI.StackPanel() as child of a GUI.ScrollViewer(). but it makes no sense, because the menu entries aren't clickable. an added onPointerClickObserverable event listener will not get fired. neiter on TextBlock or StackPanel or ScrollViewer().

# Bugs

- Bug repro on [playground](https://playground.babylonjs.com):

https://playground.babylonjs.com/#W622AS

- Expected result:
a fired onPointerClickObservable event

- Current result:
no event

ty.

**Comment by deltakosh** [comment]
Hey please use the forum before posting bugs reports :)

**Comment by dptalks** [comment]
sorry, no time for that.

**Comment by deltakosh** [comment]
cool. Here is your "fix": https://playground.babylonjs.com/#W622AS#1
