### ISSUE TITLE
Add support for TexturePacker class (Texture atlas)

### ISSUE THREAD

**Issue by deltakosh** [BabylonJS/Babylon.js#6877]
The TexturePacker is a tool used to merge textures into a bigger texture atlas.
The idea is to be able to use one big textures when two (or more) where required before.

The tool has to be able to create the next texture, copy the older ones inside and update uvs of all meshes which were relying on the old textures

**Comment by briantbutton** [comment]
Question here about updating the meshes.  _(Thumbs up or correction will be fine.)_

Pre-merge:  A given mesh points at a "merged-in" texture and has certain UV coordinates.

After-merge:  The same mesh should receive pointers to the "merged-out" texture with new UV coordinates.  But we DON'T wanna replace the mesh; just modify all those things.

What I am getting at is that we don't need to get into any internals of the Mesh (code or structure).  We can update all those things by using the same methods that put them there in the first place.

Yeah?

**Comment by Pryme8** [comment]
Aye, something fun ^_^.  Ok, so battle planning.

So I assume we will end up using the Dynamic Texture.  Gonna need to have some parameters like:  cellSize? (size of the packed texture on the Atlas if they are scaled-down),  paddingSize (amount of pixel units the texture is repeated at UV edges),  Layout modes: Strip, PowerTwo, RowCellCount, and target file type (jpg, png etc...)

Now I am thinking it might need a support JSON file (for the UV scalings and frame id).  Unless I am tricky tricky and hide it in a strip of pixel data at the bottom of the image but that might not be the best solution for edibility later.

so like BABYLON.TexturePacker.CreateFromArray(mesh[], options, download)
and
BABYLON.TexturePacker.UpdateMeshes(mesh[] | mesh, json, options)

**Comment by deltakosh** [comment]
> BABYLON.TexturePacker.CreateFromArray(mesh[], options, download)

Like this onebetter (not a big fan of additional files)

**Comment by Pryme8** [comment]
So it's not going to be saved out and used later?
Just kinda created at runtime and then the other assets are dumped?

I kinda figured it was something someone would run it, serialize their data then load it back in later as a single texture. 

We would then need a secondary function to update the meshes UV's accordingly.

**Comment by deltakosh** [comment]
Maybe I'm not completely getting the reason..I trust you to do the right choice
