### ISSUE TITLE
God ray demo is broken

### ISSUE THREAD

**Issue by azukaar** [BabylonJS/Babylon.js#6917]
# Bugs

- Bug repro on [playground](https://www.babylonjs-playground.com/#AU5641):
- Expected result: 

![image](https://user-images.githubusercontent.com/7872597/66033822-f33a7a00-e4ff-11e9-8357-06c1d8d46183.png)

- Current result:

![image](https://user-images.githubusercontent.com/7872597/66033851-fdf50f00-e4ff-11e9-9555-db453f880cc5.png)

**Comment by deltakosh** [comment]
pinging @julien-moreau

**Comment by julien-moreau** [comment]
I’m having a look ASAP!
Thanks for reporting

**Comment by deltakosh** [comment]
any news?

**Comment by julien-moreau** [comment]
Nope, the mesh is rendered but doesn’t appear in the render target used by the post-process. This is weird and I’m investigating

**Comment by deltakosh** [comment]
Fixed!

**Comment by azukaar** [comment]
> Fixed!

Just curious, what was the issue?

**Comment by julien-moreau** [comment]
The vertex shader has been modified and the line computing the final transformation was removed :(
