### ISSUE TITLE
Can not set material to an InstancedMesh even though it is an AbstractMesh

### ISSUE THREAD

**Issue by thebravoman** [BabylonJS/Babylon.js#6942]
# Bugs

Trying to set a material of an InstancedMesh. 
````
const scene = ...
const mesh = scene.getMeshByID("6558.dat.001") 
console.log(mesh.getClassName());
mesh.material = mesh.material.clone();		
````
It outputs
````
InstancedMesh
````
and throws
````
Uncaught (in promise) TypeError: Cannot set property material of [object Object] which has only a getter
````

Importing as
````
<script src="https://preview.babylonjs.com/babylon.js"></script>
<script src="https://preview.babylonjs.com/inspector/babylon.inspector.bundle.js"></script>
<script src="https://preview.babylonjs.com/loaders/babylonjs.loaders.min.js"></script>
<script src="https://preview.babylonjs.com/materialsLibrary/babylonjs.materials.min.js"></script>
<script src="https://preview.babylonjs.com/postProcessesLibrary/babylonjs.postProcess.min.js"></script>
<script src="https://preview.babylonjs.com/gui/babylon.gui.min.js"></script>
<script src="https://preview.babylonjs.com/proceduralTexturesLibrary/babylonjs.proceduralTextures.min.js"></script>
<script src="https://preview.babylonjs.com/serializers/babylonjs.serializers.min.js"></script>
<script src="https://preview.babylonjs.com/nodeEditor/babylon.nodeEditor.js"></script> 
````

- Bug repo on [playground](https://playground.babylonjs.com):
Can not reproduce it on playground currently. Trying. 

- Expected result:
mesh.material = mesh.material.clone()
should change the material
- Current result:

````
TypeError: Cannot set property material of [object Object] which has only a getter
````

Looking at the documentation and InstancedMesh is an AbstractMesh and AbstractMesh has 
property 'material' with description 'Gets or sets current material'
while of InstancedMesh it is 
````
Overrides AbstractMesh.material
The material of the source mesh
````

**Comment by sebavan** [comment]
This is a normal and expected behavior as instanced meshes can not override source mesh material or we could not rely on instanced rendering.

**Comment by thebravoman** [comment]
I understand this now, after a day of looking at the implementation. But what I keep thinking about is that InstancedMesh is not an AbstractMesh and it should not be in the hierarchy of AbstractMesh, because the AbstractMesh and a set/get and InstancedMesh lacks the setter.  

The other thing that was strange for me is that I always though 'geometry instances' share geometry and could have differences in 'postion','rotation','scale' and 'color' and other properties. Like a leaf of three that is slightly on the left and in a different color than the original leaf. Turns out all of the leafs, with the same geometry should also share the same color (at least until i get the instancedbuffers working)

**Comment by deltakosh** [comment]
1: I disagree, the instanceMesh is an AbstractMesh but with a different behavior.
2. Yep this is the goal of instancedBuffers

**Comment by thebravoman** [comment]
The way I wrote the code initially was:
````
node.getChildMeshes().forEach((mesh)=> {
  mesh.material = mesh.material.clone();
})
````
Since getChildMeshes() returns an AbstractMesh[] and we can call a '.material=' setter to AbstractMesh I was surprised that InstancedMesh is not responding to this setter. Since InstancedMesh is not responding to the '.material=' setter it is not an AbstractMesh.

Thinking about it now, to have a different behavior would be to throw an exception, or return a different result and do nothing. The body of the setter, hence its behavior could be different, but the setter should be there. The interface of AbstractMesh should be followed. And the interface is to have a setter method.

**Comment by deltakosh** [comment]
This is what we did initially. But people kept doing it and did not understand why it was not working as the API let them do it so we added a console.error but no one was reading the console...Hence the exception ;)

**Comment by thebravoman** [comment]
I understand. 

Could I suggest something else - since only Mesh and InstancedMesh are extending AbstractMesh can the setter be moved only to Mesh and to have only a getter on AbstractMesh

**Comment by deltakosh** [comment]
lineMeshes are also inheriting from abstractMesh

**Comment by thebravoman** [comment]
Looking at https://doc.babylonjs.com/api/classes/babylon.abstractmesh 
there are only two classes extending AbstractMesh - these are InstancedMesh and Mesh.

The LinesMesh, GroundMesh, TrailMesh are all extending mesh - https://doc.babylonjs.com/api/classes/babylon.mesh

**Comment by deltakosh** [comment]
Yeah right, I'm stupid :) fancy doing the PR?

**Comment by masterweb1125** [comment]
Hi, there are 56 instancedMesh
When I change the material of one of these, all's material is changed together.

How can I do separately?

**Comment by sebavan** [comment]
You can not with instancedMesh. their purpose is too render everything in one draw call so it needs to use only one material, the one of the parent mesh. you will need to use clones in your case.

**Comment by masterweb1125** [comment]
Thanks for your reply.
In the case of clone, can I change the material of each meshes?

**Comment by masterweb1125** [comment]
Let me know the clones in detail

**Comment by masterweb1125** [comment]
Should I build 56 models as each Mesh separately?

**Comment by sebavan** [comment]
You would need as many clones as different materials that you can then instantiate.

https://doc.babylonjs.com/features/featuresDeepDive/mesh/copies

Also consider using the babylon forum for help and discussions.

**Comment by masterweb1125** [comment]
Thanks

**Comment by masterweb1125** [comment]
And can I add glow effect into each instancedMesh separately?

**Comment by sebavan** [comment]
Using clones would be much simpler in this case if you do not want to require a custom shader.

**Comment by sebavan** [comment]
And as stated previously, please use our forum for questions :-) https://forum.babylonjs.com/
