### ISSUE TITLE
Oculus Quest: VR laser pointer not on when entering VR

### ISSUE THREAD

**Issue by Exolun** [BabylonJS/Babylon.js#6967]
This issue occurs intermittently, but it's something we see with a high degree of regularity.

- Load a site with a perf intensive VR scene
- Enter VR
- Controllers will have no laser

If they DO have a laser enabled, exit VR and re-enter VR... And then the laser most likely won't be enabled. (The re-entering VR part repros consistently)

**Comment by deltakosh** [comment]
@RaananW is out for the week but he will look at this issue next week

**Comment by RaananW** [comment]
Looking into it. Just making sure - are you using the latest alpha, or is this an issue with 4.0?

**Comment by RaananW** [comment]
@Exolun , is it still happening? What babylon version are you using? Thanks :-)

**Comment by Exolun** [comment]
@RaananW Yep can still repro in a playground with Latest selected - used the playground below.
https://www.babylonjs-playground.com/#TAFSN0#260

We have a workaround on our side to force-enable the lasers by calling `_activatePointer` after an initial delay on init.  Seems like it may be a timing issue.

**Comment by RaananW** [comment]
we'll take care of this on our side here. should work out of the box :-)

**Comment by RaananW** [comment]
the toggle laser buttons can be used as well (A or X), but  after the PR is merged, it will be on automatically.
The reason (if anyone is interested :-) ) was that the quest fires the gamepad-connected events after entering VR but before being in fullscreen (vr mode). i now check if the VR mode has entered (under the assumption it will not have worked if there was a problem).
