### ISSUE TITLE
Some NodeMaterial blocks should not take care of rootUrl while being deserialized

### ISSUE THREAD

**Issue by julien-moreau** [BabylonJS/Babylon.js#6973]
While loading a scene containing node materials (from a .babylon file for example), the rootUrl (here: https://github.com/BabylonJS/Babylon.js/blob/master/src/Materials/Node/Blocks/Dual/textureBlock.ts#L378) should not be used when the texture is embeded. Else, the URL can look like "http://localhost:1338/scene/data:octet-steam........" and generates an error while loading the textures.

If a playground is necessary, I'll share one :)
Can be easily reproduced in the BabylonJS Editor by clicking on "Play and Debug..."

**Comment by deltakosh** [comment]
Do you want to submit a PR? Thanks a lot :D

**Comment by julien-moreau** [comment]
Ahahah ok will find the time :)

**Comment by deltakosh** [comment]
Truly appreciated!
