### ISSUE TITLE
Antialiasing flag appears to break CreateScreenshotUsingRenderTargetAsync

### ISSUE THREAD

**Issue by nbduke** [BabylonJS/Babylon.js#6981]
# Bugs
Repro playground: https://www.babylonjs-playground.com/#DKE62M

As you can see, after 2 seconds, we take a screenshot of the scene and render it onto one of the planes. If the `antialiasing` variable is set to true, the screenshot always just appears black, but if you switch it to false, it appears how you'd expect.

**Comment by sebavan** [comment]
@nbduke the previous PR is fixing the issue, but I would still recommend on WebGL2 to rely on the samples parameters (the one undefined in your playground example) for quality purpose. On WebGL1 turning anti-aliasing on will be enough as MSAA on Render Target is not available.

**Comment by nbduke** [comment]
@sebavan what do you recommend setting 'samples' to? How does the performance vary as you change that variable?

**Comment by sebavan** [comment]
4 usually gives a pretty good result. If enabled on WebGL2 with antialising set to false (the FXAA post pro will not run) it should be slightly better on most hardware but I do not think it will change the perf by a lot.

**Comment by deltakosh** [comment]
Should not be noticeable

**Comment by nbduke** [comment]
Great, thanks guys!
