### ISSUE TITLE
Add Sensitivity Slider to the NME

### ISSUE THREAD

**Issue by TheoLeeCJ** [BabylonJS/Babylon.js#7017]
# Adding a Sensitivity Slider (for zoom) to the Node Material Editor

**Forum Link:**
https://forum.babylonjs.com/t/node-materials-examples/6048/15

**Feature:**
Currently, I find that scrolling to zoom in / out in the NME is rather slow; on the other hand, other users find it too fast (see https://forum.babylonjs.com/t/node-materials-examples/6048/14).

It would thus be nice to have a sensitivity slider (or otherwise another means) to control the speed at which one can zoom in or out in the NME, and maybe have the setting for the sensitivity be saved to the user's browser so that users need not set the slider every time.

Thanks!

**Comment by deltakosh** [comment]
Do you have an example of specific nme projects were it is slow or is it for all?

**Comment by TheoLeeCJ** [comment]
Every project I have opened in the NME so far has slower-than-desired zooming rate (to me) in Firefox on Windows.

However, after testing in Google Chrome and Edge (Firefox is my default browser) on Windows, it seems that only Firefox has the slower-than-desired scrolling.

**Comment by deltakosh** [comment]
Oh! this is why!!! I will fix that for firefox then :)

**Comment by atg** [comment]
The zooming sensitivity is non-linear for me (chrome, mac), I don't know if that's intentional, but when zoomed in close it is very slow and the further you zoom out the faster the zoom is.

There also seems to be no maximum zoom level, it just gets slower and slower the more you zoom in.

**Comment by deltakosh** [comment]
We are using https://github.com/projectstorm/react-diagrams for the rendering of the controls so not that much control over how it behaves

**Comment by deltakosh** [comment]
Unfortunately no simple way to hack this. I will report it to React diagram repo instead
