### ISSUE TITLE
SSAO2 random issues

### ISSUE THREAD

**Issue by azukaar** [BabylonJS/Babylon.js#7028]
It seems SSAO2 is extremly unstable.
 - The first time you hit a scene with SSAO2, you are very likely to get the "All black monster" (see below) is there any cache anywhere? It would eventually appear once every 100 run afterward

 - Tweaking the settings will most likely end up in a "all black monster" too

Experienced with latest versiomn, on Chrome with NVidia GPU

![Capture](https://user-images.githubusercontent.com/7872597/67150305-c03d0800-f2ad-11e9-834f-acf19d298458.JPG)

![Capture2](https://user-images.githubusercontent.com/7872597/67150306-c206cb80-f2ad-11e9-9a00-330e7d884cb7.JPG)

**Comment by azukaar** [comment]
Just thought of something... Could it be that the computation is first made on unloaded textures ?

**Comment by deltakosh** [comment]
It is definitely bugged! let me ping @CraigFeldspar

**Comment by deltakosh** [comment]
And maybe @julien-moreau if he can have a look

**Comment by CraigFeldspar** [comment]
I'll take a look & will be back to you
