### ISSUE TITLE
updateSamplingMode not working

### ISSUE THREAD

**Issue by azukaar** [BabylonJS/Babylon.js#7029]
This was reported ont the forum but isn't on Github. Setting the sampling mode at creation works, but updating it doesn't seem to.

# Bugs

- Bug repro on https://www.babylonjs-playground.com/#121HCT#0:

![image](https://user-images.githubusercontent.com/7872597/67152117-7dd4f480-f2c8-11e9-815a-ea3d3be0e999.png)

**Comment by deltakosh** [comment]
Not a bug. If you do it afterwards, you have to wait for the texture to be ready before changing the state: https://www.babylonjs-playground.com/#121HCT#5

**Comment by azukaar** [comment]
> Not a bug. If you do it afterwards, you have to wait for the texture to be ready before changing

Thanks! Sorry for false report
