### ISSUE TITLE
Explore multiple light nodes

### ISSUE THREAD

**Issue by PatrickRyanMS** [BabylonJS/Babylon.js#7043]
# Feature request
Explore what should happen if a user puts two light nodes into a graph. Should we allow it? If so, what would that look like? If we disallow two light nodes, how do we message that to the user? When the second node is dropped? When we try to wire up two light nodes? As an error when trying to compile?

As an extension, we should look at our other nodes and see if there are any others which need to be treated in a similar way and how should we handle the UX around this issue.

**Comment by deltakosh** [comment]
Fixed
