### ISSUE TITLE
Exiting VR using button on old Edge prevents mouse from panning camera

### ISSUE THREAD

**Issue by mattdmorgan** [BabylonJS/Babylon.js#7058]
0) Go to https://www.babylonjs-playground.com/#8C89EQ#4 in current Edge.
1) Enter VR by clicking the button.
2) Exit VR by clicking the button again (this playground is tweaked to always show the button).
3) Click and drag in the scene using the mouse.
Result: Camera doesn't pan.
Expect: Camera pans as usual.

Doesn't repro in Chrome/new Edge/etc.
Doesn't repro if you exit VR using the Esc key.

Given that this happens only with old Edge and only with the button, this may not be worth fixing.

**Comment by RaananW** [comment]
Seems like a bug in Edge.

The callback executed when the event `vrdisplaypointerunrestricted` (https://github.com/BabylonJS/Babylon.js/blob/master/src/Engines/Extensions/engine.webVR.ts#L272) is triggered doesn't have the `document` variable (it is undefined).

`this` is the window object, so this would be a solution, the question is (@deltakosh) - do we want this change in the codebase? It is rather straight forward.

**Comment by deltakosh** [comment]
Yeah this will be rad :)
