### ISSUE TITLE
MotionBlur With Environnement, a lot of warning

### ISSUE THREAD

**Issue by stephanedemotte** [BabylonJS/Babylon.js#7060]
Hello

First, when i try to use motion blur, the blur is always on, even if the camera don't move.
Second, we have a lot of `warn` when used with an Environment.

https://playground.babylonjs.com/#LWM8SA

-- EDIT

@julien-moreau 

I've created a skybox with `createDefaultEnvironment`
I have to do it without `createDefaultEnvironment` ?

```
scene.createDefaultEnvironment({
      groundColor: BABYLON.Color3.FromHexString('#4000ff'),
      skyboxColor: BABYLON.Color3.FromHexString('#0e0b5c'),
      skyboxSize: 200
    })
```

**Comment by julien-moreau** [comment]
I’m having a look :)

**Comment by julien-moreau** [comment]
I see now, this is unfortunately a limitation
This is explained here (and the reason why): https://doc.babylonjs.com/how_to/using_motionblurpostprocess#limitations
Please at least a black skybox to avoid clear-color glitches
