### ISSUE TITLE
WebXRDefaultExperience isn't exported in typings (alpha-27)

### ISSUE THREAD

**Issue by nbduke** [BabylonJS/Babylon.js#7069]
# Bugs
More a package issue than a behavioral issue (not sure if that qualifies as a bug). The module "babylonjs/Cameras/XR/webXRDefaultExperience", which includes the classes `WebXRDefaultExperience` and `WebXRDefaultExperienceOptions`, isn't exported in the "babylonjs/Cameras/XR/index" module.

This prevents developers from being able to import these classes normally; you have to use `BABYLON.WebXRDefaultExperience`.

**Comment by RaananW** [comment]
That's odd. the `WebXRDefaultExperienceOptions` is exported in the file babylonjs/Cameras/XR/webXRDefaultExperience , and the file is included in the index. 

What error do you get?
