### ISSUE TITLE
babylon and pixijs（pixijs4.8.2、4.8.8、5.x）

### ISSUE THREAD

**Issue by senray0** [BabylonJS/Babylon.js#7087]
Hello, we met a problem now.In Babylon, combined with Pixijs, there was a problem in rendering 3 d model, model of skeletal animation is also affected by the serious.When include pixijs reference rendering comment out model rendering and animation will return to normal.Could you tell me what is the cause?
![babylon](https://user-images.githubusercontent.com/46912757/68004923-409c3980-fcae-11e9-9155-e458b6690f79.png)
![babylon  and pixi](https://user-images.githubusercontent.com/46912757/68004925-409c3980-fcae-11e9-93e7-7dd5c02bde71.png)

**Comment by deltakosh** [comment]
Please use the forum for question: forum.babylonjs.com
