### ISSUE TITLE
Controller observables incorrectly mapped in WebXR

### ISSUE THREAD

**Issue by nbduke** [BabylonJS/Babylon.js#7091]
# Bugs
Repro playground: https://playground.babylonjs.com/#AM07G2#21

Note: In that playground, the usual "view in headset" button doesn't work for some reason. Click the color picker GUI instead.

I'm using an HP Windows Mixed Reality Headset on Chromium-Edge 79. In XR mode, you can see in the console that the observables hooked up to the gamepad controller don't map sensibly to the observable names. I'm getting this:
  hardware trigger --> pad observable
  hardware grip button --> trigger observable
  hardware touchpad --> main button observable
  hardware thumbstick --> secondary button observable (only on click)

**Comment by RaananW** [comment]
The WebXR API is actually using the gamepad API at the moment. Is it the same in WebVR? or is it just an issue with XR?

**Comment by nbduke** [comment]
I'm only seeing an issue in WebXR.

**Comment by RaananW** [comment]
very interesting :-) 

But I am very happy to read that I can use my mixed reality with edge now. Just downloaded edge canary, I will check and let you know.

**Comment by RaananW** [comment]
I can confirm the mapping is different on my device as well.
I will create different classes for the XR controllers and make the old ones deprecated.

I can't find a reason why anyone will decide to change the mapping, unless it is related to OpenXR (not sure it is) and standardizing the gamepad buttons. I'll give'em the benefit of the doubt :-)

**Comment by RaananW** [comment]
Not yet implemented

**Comment by nbduke** [comment]
@RaananW is there an ETA on when this fix will make it to a release?

**Comment by RaananW** [comment]
Working on that today, will probably be done by the end of the day
