### ISSUE TITLE
PostProcess hard-codes generateMipMaps to false

### ISSUE THREAD

**Issue by MiiBond** [BabylonJS/Babylon.js#7099]
In `postProcess.ts`, the internal RT is created with `generateMipMaps` hard-coded to `false`, regardless of the value of `renderTargetSamplingMode`.
This has caused me issues as I'm trying to sample LOD's from the previous RT in the pipeline.

I'm assuming that `generateMipMaps` is supposed to be configurable.

**Comment by deltakosh** [comment]
good catch! Will fix that
