### ISSUE TITLE
Inspector: a console.log floods browser console

### ISSUE THREAD

**Issue by Vinc3r** [BabylonJS/Babylon.js#7126]
I think this console.log is annoying when debugging our apps.

Example with this playground: https://www.babylonjs-playground.com/#G3GZA1#49

Type "box" in the Filter field of the Inspector, then unfold "Nodes" and "\_\_cornell-root\_\_" : your console is flooded.

![image](https://user-images.githubusercontent.com/3873421/68480054-29bc9080-0234-11ea-8e4c-5987ff6d9ce6.png)

**Comment by deltakosh** [comment]
Ouch! I will fix that
