### ISSUE TITLE
Support for Variants in glTF 

### ISSUE THREAD

**Issue by thomlucc** [BabylonJS/Babylon.js#7131]
To manage the various possible configurations of a product, the Configuration working group of the 3D Commerce is planning to move the "FB_material_variants" to an EXT extension and potentially to a KHR extension.

-> Link to glTF issue to provide feedback if any: https://github.com/KhronosGroup/glTF/pull/1681

**Comment by deltakosh** [comment]
@bghgary Do you recommend implementing it now?

**Comment by bghgary** [comment]
I lean towards no unless we have partners/scenarios that we can support.

**Comment by thomlucc** [comment]
Mike Bond from Adobe is working on it and should submit a PR (discussed in the Metada working group )

**Comment by sebavan** [comment]
PR has been done and merged

**Comment by sebavan** [comment]
#8223

**Comment by thomlucc** [comment]
Re-opening as following our feedback on the implementation, the configuration Working Group simplified the extension to focus on wholesale static variant configuration. @bghgary: see last commit on https://github.com/KhronosGroup/glTF/pull/1681

**Comment by thomlucc** [comment]
Re-opening as some changes (root node) where made to the schema. @bghgary started to work on it per discussion on https://github.com/khronosgroup/gltf/pull/1681.

**Comment by bghgary** [comment]
This is already done.

**Comment by thomlucc** [comment]
ok closing. Thanks for the confirmation!

**Comment by thomlucc** [comment]
Re-opening as I tried the latest models from: https://www.dropbox.com/s/ynity52sut4t6x2/khr_materials_variants_models.zip?dl=0 and got a error in the Sandbox.
Repro:
- Using the variant GLB (Shoes.glb, helmet_combined.glb, chairs.glb)
- ![image](https://user-images.githubusercontent.com/32072891/91450575-4bbde880-e831-11ea-8a7f-b29296807854.png)

**Comment by cx20** [comment]
@thomlucc Probably the sample model here is more up to date.
https://github.com/KhronosGroup/glTF-Sample-Models/pull/271

**Comment by deltakosh** [comment]
@thomlucc did you try with the one from cx20?

**Comment by thomlucc** [comment]
Thanks @cx20 ! @deltakosh: no, I'll try with the latest from cx20 and report back here today.

**Comment by thomlucc** [comment]
@deltakosh - It is working perfectly with the latest models. Thanks again @cx20 !!!
![image](https://user-images.githubusercontent.com/32072891/91481760-c7339000-e859-11ea-88e1-673fae02be3c.png)

**Comment by pragneshmali99** [comment]
Respected Sir,

How can i add "FB_material_variants" in gltf model json using THREE js GLTFLoader ?

Thanks & Regards,
Pragnesh Mali
email: pragneshmali99@gmail.com
