### ISSUE TITLE
Discussion of factors in PBR materials

### ISSUE THREAD

**Issue by PatrickRyanMS** [BabylonJS/Babylon.js#7143]
We need to have a conversation about default color spaces for base color/emissive/specular factors for PBR materials. Right now we default to linear space for the factors, where textures for these inputs are in sRGB, So if I assign (128, 128, 128) in a base color texture for a material that sits next to a material that has its base color factor assigned to (128, 128, 128) in code they will look different unless the base color factor is converted to linear space.

I know this has been around since 3.3, but it seems to me that defaulting color space for base color factor to linear space is not intuitive to an artist creating the materials.

**Comment by sebavan** [comment]
We actually did remove them a while back as it was confusing to have both and we wanted to align with GLTF.

Maybe it should be an inspector option only ?
