### ISSUE TITLE
AssetContainer.instantiateModelsToScene() has a bug

### ISSUE THREAD

**Issue by kekeqy** [BabylonJS/Babylon.js#7144]
If an asset has animation, the entity created by this method has problems and some parts are not visible. See attached pictures and model files.The head of the character is out of sight.
![微信图片_20191112153754](https://user-images.githubusercontent.com/15007739/68651480-7a005f00-0562-11ea-990e-338561452b4d.png)
[anqier.zip](https://github.com/BabylonJS/Babylon.js/files/3834913/anqier.zip)

**Comment by deltakosh** [comment]
Hello please use the forum.babylonjs.com to discuss bugs or questions before opening an issue
