### ISSUE TITLE
Camera isn't in same position after entering XR

### ISSUE THREAD

**Issue by nbduke** [BabylonJS/Babylon.js#7158]
# Bugs
Repro playground: https://www.babylonjs-playground.com/#THMWLW#2

If you enter XR mode, you'll notice that the `WebXRCamera` is not where the previous (non-XR) camera had been, which feels really jarring. You can see their respective positions printed to the console.

Interestingly, this didn't repro in WebVR - flip the `useXR` variable to false and try again in a different browser. The `WebVRCamera` is where you'd expect.

**Comment by deltakosh** [comment]
adding @RaananW

**Comment by nbduke** [comment]
@RaananW I'm not convinced this is fixed (or maybe there's been a regression). In the Playground example, you still see two different positions printed to the console before and after entering XR.

**Comment by RaananW** [comment]
I will look into that and let you know

**Comment by RaananW** [comment]
Implemented with https://github.com/BabylonJS/Babylon.js/issues/7239 , documentation is coming soon
