### ISSUE TITLE
Certain animated models don't seem to be pickable

### ISSUE THREAD

**Issue by Exolun** [BabylonJS/Babylon.js#7168]
We've stumbled upon a 3D model that has an animation that moves it all the way out of its initial bounding area and it seems foil the picking intersect logic.  The geometry is pickable, but the intersection ray doesn't register the hit.

- Bug repro on [this playground](https://www.babylonjs-playground.com/#U5SSCN#84)

**Comment by Vinc3r** [comment]
that's remind me an issue I've spotted, #4651 , probably relative to this

![boundinginfo](https://user-images.githubusercontent.com/3873421/68928696-07be9300-078b-11ea-82c6-4bf44d8a1dd0.gif)

A solution was to scale the bounding box, but I'm not sure it's very intuitive. In your scene, for example, [that's a weird turn-around](https://www.babylonjs-playground.com/#U5SSCN#85)...
Even by forcing bounding refresh on each render, [it seems to fail](https://www.babylonjs-playground.com/#U5SSCN#86).

**Comment by deltakosh** [comment]
Exactly this is because the bones are animating the model on the GPU.
You can manually force the engine to update the geometry locally as well but it will be counter productive for perf

**Comment by deltakosh** [comment]
Here it the right call: https://www.babylonjs-playground.com/#U5SSCN#87 where I refresh the bounding box so the picking will work

**Comment by Exolun** [comment]
Interesting find - thanks for the help!
