### ISSUE TITLE
Small typo in instancedMesh.ts#L80

### ISSUE THREAD

**Issue by Wingnutt** [BabylonJS/Babylon.js#7175]
https://github.com/BabylonJS/Babylon.js/blob/master/src/Meshes/instancedMesh.ts#L80

Missing 't' in '_resyncLighSource'  :)  Not sure if important.

While in there, we/someone COULD adjust line 177 to...

The `data` are either a numeric array **or** a Float32Array.

Nothing overly important... just saw stuff and reported it. (With a git-issue!  Pretty rare for me.)  :)

**Comment by deltakosh** [comment]
Thanks :)
