### ISSUE TITLE
explorerExtensibility is not visible if embedMode flag is set to true

### ISSUE THREAD

**Issue by PUDRESCU** [BabylonJS/Babylon.js#7182]
# Bug

When using the explorerExtensibility API, the extended interface is not shown if the embedMode flag set to true.

```
var extensibility = [
        {
            predicate: (entity) => { return true; },
            entries: [
                {
                    label: "Say hello",
                    action: (entity) => alert("hello " + entity.name)
                }
            ]
        }
    ];
scene.debugLayer.show({ embedMode: true, explorerExtensibility: extensibility });
```

- https://www.babylonjs-playground.com/#F47J2M
- Expected result:
![image](https://user-images.githubusercontent.com/3367536/69092664-bec44400-0a01-11ea-8acf-37a1d4314d8e.png)

- Current result:
![image](https://user-images.githubusercontent.com/3367536/69092698-cedc2380-0a01-11ea-82f4-5af2318ff01d.png)

Resizing the Inspector window or popping it out does not fix.  Only the embedMode flag and I can't seem to find documentation that would indicate this is the expected behavior.

**Comment by deltakosh** [comment]
Thanks!!!
