### ISSUE TITLE
Projection Texture Caching Issue

### ISSUE THREAD

**Issue by PirateJC** [BabylonJS/Babylon.js#7209]
Looks like we've got a very weird caching issue/bug with the Projection Texture.

https://playground.babylonjs.com/#KIMW2P#3

In this playground...we should see the projected texture from the spotlight on the groundplane AND the sphere.

If you open the inspector and hide the sphere...the ground will inherit the projection texture.  Then if you unhide the sphere, now both objects will correctly display the projection texture as expected.

Seems like there's some issue where the sphere rendering is blocking the groundplane from getting the projection texture on the initial load?

**Comment by sebavan** [comment]
indeed, on the ground, the texture being used is the wrong one:
![image](https://user-images.githubusercontent.com/16655165/69638342-c9628700-105a-11ea-8c11-f9ec28bf602e.png)

I ll have a look ASAP.
