### ISSUE TITLE
gltf2interface still on 4.1.0-beta.3, so I can't upgrade loaders to 4.1.0-beta.4

### ISSUE THREAD

**Issue by nbduke** [BabylonJS/Babylon.js#7215]
# Bugs
I tried upgrading to 4.1.0-beta.4, but I depend on the loaders package, which itself depends on gltf2interface, but the latter is still on 4.1.0-beta.3.

**Comment by deltakosh** [comment]
Pinging @sebavan

**Comment by sebavan** [comment]
This is really strange, let me publish it manually... I ll ping you once done

**Comment by sebavan** [comment]
should be good now
