### ISSUE TITLE
Taking a screenshot causes shadows of instanced meshes to disappear

### ISSUE THREAD

**Issue by nbduke** [BabylonJS/Babylon.js#7219]
# Bugs
Repro playground: https://www.babylonjs-playground.com/#IFYDRS#48

In the above playground, I create a box mesh and an instance of that mesh. The instance is added as a shadow caster. A second after scene load, I create a new camera and take a screenshot of the scene using `Tools.CreateScreenshotUsingRenderTargetAsync`. You see a brief blink of the scene and after that, the shadow of the instanced box is gone.

**Comment by sebavan** [comment]
Min repro: https://www.babylonjs-playground.com/#IFYDRS#50

This is not only linked to screenshot but looks like it could impact all RTT. Narrowed down to a caching issue. I am still looking into a fix.
