### ISSUE TITLE
VR / Device Motion not working on iOS 12.2 and higher

### ISSUE THREAD

**Issue by CLB-ZReality** [BabylonJS/Babylon.js#7220]
Please fix the device motion for iOS 12.2 and higher devices by using the new apple API in babylonjs.
Issue request from RanaanW: https://forum.babylonjs.com/t/deviceorientation-in-ios-12-2/1196/4

you can find the api information in the forum post or under this link: https://medium.com/flawless-app-stories/how-to-request-device-motion-and-orientation-permission-in-ios-13-74fc9d6cd140

**Comment by RaananW** [comment]
Seems pretty straightforward, should be fine.

Just wanted to give a heads up - this is for iOS13 and up, 12.2 doesn't have the permisison management system, so it cannot be implemented for it (see the medium post you submitted)
