### ISSUE TITLE
PBR Material with non HDR skybox with Babylonjs 4

### ISSUE THREAD

**Issue by TiagoSilvaPereira** [BabylonJS/Babylon.js#7224]
Hi guys,

As we already discussed this [here](https://forum.babylonjs.com/t/issues-with-pbr-material-on-babylonjs-version-4/6565/18), I'm opening this thread to track the status of this issue :smile:.

# Bugs

- Bug repro on [playground](https://www.babylonjs-playground.com/#B1M547):
- Expected result: The expected result is the same presented using BabylonJS 3, even I'm using a non-HDR skybox
- Current result: But using BabylonJS 4, it is not working more and requires an HDR skybox and a lot of fixes to the mesh and settings to start working. As we discussed, looks like it has some issue with the cloned textures for the environment (I tried not to clone the texture, but it only makes a static texture overlaying the object)

# Feature request

- Link to [forum](https://forum.babylonjs.com/t/issues-with-pbr-material-on-babylonjs-version-4/6565/13) discussion about the feature:

I'm trying to identify the changes that caused this change too. If I can find something, I'll update it here.

Thanks very much

**Comment by sebavan** [comment]
This will be in the next nightly actually found an issue on the harmonics generation.

**Comment by TiagoSilvaPereira** [comment]
Thanks @sebavan
