### ISSUE TITLE
WebXR AR support, including existing features

### ISSUE THREAD

**Issue by RaananW** [BabylonJS/Babylon.js#7226]
Babylon will have an AR module that will support the AR functionality offered in WebXR:

- [x] Enter AR with ease
- [x] Hit-test implementation
- [x] Pointer-Events simulation (as many events as possible, so far only pointermove is working)
- [x] Anchors (using babylon native nodes)
- [x] Plane detection
- [x] Background-removal system

**Comment by bnolan** [comment]
I've been trying to get AR mode running on a pixel 3 with ar-core, and it's not implemented yet? I'm calling `xr.baseExperience.enterXRAsync('immersive-ar')` and it asks to enter AR mode, but doesn't update the camera position, nor does it display the image from the camera in the background.

**Comment by RaananW** [comment]
@bnolan - works correctly on chrome canary and latest stable, but missing features like hit test and plane detection.

**Comment by RaananW** [comment]
For documentation purpose - AR plane detection in chrome stopped working in latest canary with no API changes made. Bug submitted - https://bugs.chromium.org/p/chromium/issues/detail?id=1032070

**Comment by jumpjack** [comment]
Can "double image mode" be implemented? I can't find it in examples.

![image](https://github.com/BabylonJS/Babylon.js/assets/1620953/9adf3c48-5101-4d98-9936-82989413add8)

**Comment by RaananW** [comment]
> Can "double image mode" be implemented? I can't find it in examples.
> 

We do have stereoscopic camera support (StereoscopicFreeCamera for example). WebXR is using the WebXR API and supports whatever WebXR supports.
