### ISSUE TITLE
Pointer direction incorrect when using hands in AR

### ISSUE THREAD

**Issue by RaananW** [BabylonJS/Babylon.js#7236]
When using hands as an input device in WebXR (AR), the pointer direction is incorrect.

Current:
The ray is coming from the thumb and pointing up 

Expected:
The ray is pointing forwards, in the direction of the pointing finger.

**Comment by Manishearth** [comment]
It _seems_ like babylonjs is using the grip space instead of the target ray space, but looking at the code that doesn't seem to be the case.

**Comment by RaananW** [comment]
To me it feels more like a missing 90 degrees on the X axis that is due to the way we are dealing with the cylinder/pointer . I am still checking it, but on different AR issues ATM.

**Comment by Manishearth** [comment]
Ah, could be.

**Comment by RaananW** [comment]
Hi guys, was wondering something. When using the hololens emulator, it seems like the rays from the hands are actually not in the direction of the pointing finger:

![image](https://user-images.githubusercontent.com/1381702/72351542-d574d780-36e0-11ea-9771-ad7044ee265b.png)

It seems like it is the same offset as we are getting (pointing a little higher than expected). Have you tried using a real device, or are you only testing on an emulator?

**Comment by Manishearth** [comment]
No, we were using a real device.

That said we did have a bug in the grip space which we recently fixed!

**Comment by Manishearth** [comment]
Going to see if we can test it again with the fixes and report back

**Comment by RaananW** [comment]
Any update on that? maybe a new version I can test on as well?

**Comment by Manishearth** [comment]
Not at the moment, @jdm has my device

**Comment by jdm** [comment]
Nightly versions are published at http://download.servo.org/nightly/uwp/servo-latest.0.0.0_Test.zip, so you could use those to test.

**Comment by RaananW** [comment]
thanks @jdm ! will test on the emulator

**Comment by Manishearth** [comment]
Yeah, this was our bug, confirmed that the new patch fixed it.

What was happening was that we were lazily setting the grip and target ray spaces on the input source, but babylonjs requests the grip space first and that's what got set, and we had a copy paste error where they both were set to the same field. Three.js didn't have this issue because presumably it accesses the target ray space first, and when testing stuff outside of frameworks I only ever used a single space so I didn't see a space set to the wrong thing

**Comment by RaananW** [comment]
oh, that's great to hear! 

Closing the ticket. Reopen if anything needs a fix on our side

**Comment by Zhernet** [comment]
Hi, I still have the same issue in WebXR (VR) with an Oculus Touch (Oculus Rift v1). With Chrome or Edge, the pointer is upward at 90 degrees angle.
With Firefox (with the flag dom.vr.webxr.enabled) it's pointed at 45 degrees angle.
It works fine with am HTC Vive. 

Any idea for Oculus Rift v1?
