### ISSUE TITLE
v4.1.0 beta 4, safari bug

### ISSUE THREAD

**Issue by stephanedemotte** [BabylonJS/Babylon.js#7237]
Hello

The default playground example don't run on safari : https://playground.babylonjs.com

```
https://playground.babylonjs.com/node_modules/monaco-editor/dev/vs/language/typescript/lib/typescriptServices.js.map
Failed to load resource: the server responded with a status of 404 ()
```

In my project i can load the `js.map` but i have another error
```
WebGL: INVALID_OPERATION: generateMipmap: level 0 not power of 2 or not all the same size
```

Can't load any GLTF in safari, everything work great in Firefox and chrome (MAC)

Thanks !

**Comment by sebavan** [comment]
The playground works for me on Safari for Mac :-(

![image](https://user-images.githubusercontent.com/16655165/69972986-ec8daa80-1522-11ea-9dc0-6e2f4669f896.png)

Could you share what version of Safari and MacOs you are using ?

**Comment by sebavan** [comment]
The .map error can be disregarded and would only be raised when the dev tools are opening. I ll still fix it ASAP

**Comment by sebavan** [comment]
Gltf files are also ok 
![image](https://user-images.githubusercontent.com/16655165/69973256-7e95b300-1523-11ea-83cb-93cc597ea5dd.png)

I ll close the bug for now waiting for more info in order to repro.
