### ISSUE TITLE
WebXR camera positioning API

### ISSUE THREAD

**Issue by RaananW** [BabylonJS/Babylon.js#7239]
It should be possible to position the XR camera in any 3D position in space. 

The current state allows a developer to re-position the webxr container (the parent of the camera and the controllers), but in order to do that correctly the user must also know the height of the user and other factors. There is also an issue when querying the current camera's position and direction, as the camera itself will always return 0,0,0 as its local position due to the way the rig-cameras are working. 

This is a proposed API extension to the WebXR camera that will be able to position the container based on floor meshes, ignoring the user's current height. The camera should be the "single point of truth" when it comes to its own position.

The API will allow:

1) Simple (re)positioning of a user to a point of reference, with an optional floor / height map to use for height:

```javascript
function setPosition(pointInSpace: Vector3, pointOfReference?: Vector3 | Node, options? : {
  space: Space = Space.LOCAL,
  setHeightFromXRFrame: boolean = true,
  // further options TBD
}): void;
```

2) Get the camera's current global and local position using the XFrame information sent by XR (average of both eyes)
3) The ability to query the global position of a single eye
4) The ability to check the camera's current direction 
5) Active position-copy from native (non-XR) to XR cameras and vice versa

**Comment by RaananW** [comment]
@nbduke - please comment if anything is missing here

**Comment by nbduke** [comment]
So if I call `setPosition(point, Vector3.Zero(), { space: Space.LOCAL })`, is that just the same as `setPosition(point, undefined, { space: Space.WORLD })`?

**Comment by RaananW** [comment]
@nbduke - Sorry for a late answer!

Yes, world coordinates will be including the container, local will change the camera alone. Internally, both will change the container but either relative to the current position or not.

**Comment by RaananW** [comment]
Teleporting (position changes of the user) will be done using https://www.w3.org/TR/webxr/#xrreferencespace-interface 
the `setPOsition` function will create a new relative reference space.

**Comment by RaananW** [comment]
merged and tested

**Comment by stefanvanherwijnen** [comment]
@RaananW 
Using `xr.baseExperience.camera.leftCamera` and `xr.baseExperience.camera.rightCamera` does not seem to work anymore. Which is strange, because `xr.baseExperience.camera.rigCameras` returns an Array with two cameras, but `xr.baseExperience.camera.rigCameras.length` returns 1 :confused: .

https://www.babylonjs-playground.com/#LUYXFU

**Comment by RaananW** [comment]
Hi @stefanvanherwijnen , just got back and looking into this.

About the first example, this is what I get:

![image](https://user-images.githubusercontent.com/1381702/71809557-a02d1180-3070-11ea-82c2-ba22f50306d8.png)

Which is what is expected right before the first frame was rendered.

I understand that you want a kind of callback that will be triggered when everything was set, and I agree that it is important. 

This - https://www.babylonjs-playground.com/debug.html#LUYXFU#3 should be working, but due to the fact that I use the first frame to update the camera's position from the old camera, it doesn't . But I believe I have found a way to make it work correctly. Want to create a github issue so we can track it internally?

Thanks!

**Comment by stefanvanherwijnen** [comment]
Thanks, I opened a new issue.
You're right that I'm looking for a callback that is triggered when everything is set, Before the recent changes the IN_XR state was such that everything XR related was ready and working.
