### ISSUE TITLE
v4.1.0 beta 4, IE11 const must be initialized

### ISSUE THREAD

**Issue by stephanedemotte** [BabylonJS/Babylon.js#7240]
Hi

Got this message on IE11

```
Const must be initialized
```

Can't use playground to make a reproductible bug, because playground is stuck in the loading state in IE11

Thanks !

**Comment by deltakosh** [comment]
Hey @stephanedemotte, we do not support IE11 anymore on PG

Can you repro the issue on codepen maybe?

**Comment by stephanedemotte** [comment]
Codepen and Jsfiddle doesn't support IE11 :)

http://babylonv4.demotte.net/

Seem to work here... sorry it's in my project :)

Thanks
