### ISSUE TITLE
v4.1.0 beta 4, safari V13 bug (more infos)

### ISSUE THREAD

**Issue by stephanedemotte** [BabylonJS/Babylon.js#7241]
My project and playground run on Safari v12 but not on v13

<img width="1680" alt="Screen Shot 2019-12-02 at 11 04 50 AM" src="https://user-images.githubusercontent.com/2158130/69975606-84749f80-14f5-11ea-9e13-f36b40132b5a.png">

thanks

**Comment by sebavan** [comment]
Could you send as well the error you are seeing in the console ?

**Comment by sebavan** [comment]
and do you have any experimental features turned on ?

As their name implies they do not work all the time like the WebGL2 ones. It is still not fully compliant.

**Comment by sebavan** [comment]
![image](https://user-images.githubusercontent.com/16655165/69976266-fa462e80-1528-11ea-9a88-695c872db267.png)

I am actually on Safari 13 as well without the issue so I guess you have some special features turned on ?

**Comment by sebavan** [comment]
closing for now as I guess it is related to your env and not a general issue. Tried on 3 different Macs.

Do not hesitate to continue on this thread even closed, I will monitor it to try to unlock you.  I do not want everybody thinking that the full Safari does not work. Or we can continue the discussion on the forum if it is easier.

**Comment by stephanedemotte** [comment]
Ok got it,

If i disable Webgl v2 experimental feature, everything work great.

![Uploading Screen Shot 2019-12-02 at 11.50.47 AM.png…]()

**Comment by sebavan** [comment]
Yup it is still not fully compliant on their side so nothing we can really do at the moment.
