### ISSUE TITLE
Fix how we export KHR_Texture_Transform

### ISSUE THREAD

**Issue by deltakosh** [BabylonJS/Babylon.js#7246]
Flattening the texture is not a good idea
https://forum.babylonjs.com/t/sandbox-glb-export-destroys-khr-texture-transform/7338

**Comment by deltakosh** [comment]
Pinging @Drigax for thoughts

**Comment by atuleccentric** [comment]
Hi I am using this BABYLON.GLTF2Export.GLTFAsync(scene, "object").then((gltf) => {
        gltf.downloadFiles();
    });
for my base I have set texture offset and scale.
output in .gltf is showing like these
  "baseColorTexture": {
          "index": 0,
          "texCoord": 0
        }

 how to enable KHR_texture_transform

**Comment by sebavan** [comment]
I pinged back @Drigax on the forum thread to double check

**Comment by atuleccentric** [comment]
ok thanks @sebavan

**Comment by Drigax** [comment]
I agree, I'm not sure why this was done. I responded back on https://forum.babylonjs.com/t/sandbox-glb-export-destroys-khr-texture-transform/7338/8 with my findings. Basically, our KHR_Texture_Transform implementation bakes the texture if it is translated such that the center of the texture is no longer at (0,0).

My proposed fix removes this check and baking logic.
