### ISSUE TITLE
iOS-focused request for permission causes crash on non-VR-capable Desktop Chrome

### ISSUE THREAD

**Issue by cchengVA** [BabylonJS/Babylon.js#7253]
This is a report written at direction of @RaananW from [this Forum Post](https://forum.babylonjs.com/t/uncaught-referenceerror-for-babylon-scene-createdefaultvrexperience-on-non-vr-machine/7346).

It uses the latest preview of Babylon, and appears to have been introduced in 6c006abc for #7220. The full stacktrace points to [this line](https://github.com/BabylonJS/Babylon.js/commit/6c006abc23c28e07ba93f67f8a48c8e28deee3c9#diff-50de482b218c531bdffc6dc247c14b64R146).  The issue arises in Google Chrome Version 78.0.3904.108 on Windows 10 1903 (build 18362.476).  "About Chrome" reports it as up to date.

I cannot seem to get a repro case in the BJS Playground - perhaps a difference between versions that the Playground uses and elsewhere?  However, I am able to reproduce the issue with the given page:

```<!DOCTYPE html>
<html>

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

    <title>Babylon.js Uncaught</title>

    <!-- Babylon.js -->
    <script src="https://code.jquery.com/pep/0.4.2/pep.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/dat-gui/0.6.2/dat.gui.min.js"></script>
    <script src="https://preview.babylonjs.com/ammo.js"></script>
    <script src="https://preview.babylonjs.com/cannon.js"></script>
    <script src="https://preview.babylonjs.com/recast.js"></script>
    <script src="https://preview.babylonjs.com/Oimo.js"></script>
    <script src="https://preview.babylonjs.com/gltf_validator.js"></script>
    <script src="https://preview.babylonjs.com/earcut.min.js"></script>
    <script src="https://preview.babylonjs.com/babylon.max.js"></script>
    <script src="https://preview.babylonjs.com/inspector/babylon.inspector.bundle.js"></script>
    <script src="https://preview.babylonjs.com/materialsLibrary/babylonjs.materials.min.js"></script>
    <script src="https://preview.babylonjs.com/proceduralTexturesLibrary/babylonjs.proceduralTextures.min.js"></script>
    <script src="https://preview.babylonjs.com/postProcessesLibrary/babylonjs.postProcess.min.js"></script>
    <script src="https://preview.babylonjs.com/loaders/babylonjs.loaders.js"></script>
    <script src="https://preview.babylonjs.com/serializers/babylonjs.serializers.min.js"></script>
    <script src="https://preview.babylonjs.com/gui/babylon.gui.min.js"></script>

    <style>
        html,
        body {
            overflow: hidden;
            width: 100%;
            height: 100%;
            margin: 0;
            padding: 0;
        }

        #renderCanvas {
            width: 100%;
            height: 100%;
            touch-action: none;
        }
    </style>
</head>

<body>
    <canvas id="renderCanvas"></canvas>
    <script>
        var canvas = document.getElementById("renderCanvas");
        var engine = new BABYLON.Engine(canvas, true, { preserveDrawingBuffer: true, stencil: true });
        var scene = new BABYLON.Scene(engine);
        var vrhelper = scene.createDefaultVRExperience();  // BUG STARTS HERE

        engine.runRenderLoop(function () {
            if (scene) {
                scene.render();
            }
        });

        // Resize
        window.addEventListener("resize", function () {
            engine.resize();
        });
    </script>
</body>

</html>
```

- Expected result:
Page loads without issue.

- Current result:
The following stack trace is emitted and the page load breaks, giving only a white screen.

`Uncaught ReferenceError: DeviceOrientationEvent is not defined`
`    at 
FreeCameraDeviceOrientationInput../Cameras/Inputs/freeCameraDeviceOrientationInput.ts.FreeCameraDeviceOrientationInput.attachControl` ([freeCameraDeviceOrientationInput.ts:146](https://github.com/BabylonJS/Babylon.js/blob/5ec117e974e3064ecef4573eb86e87a0d9511d48/src/Cameras/Inputs/freeCameraDeviceOrientationInput.ts#L146))
`    at FreeCameraInputsManager../Cameras/cameraInputsManager.ts.CameraInputsManager.attachElement` ([cameraInputsManager.ts:200](https://github.com/BabylonJS/Babylon.js/blob/5ec117e974e3064ecef4573eb86e87a0d9511d48/src/Cameras/cameraInputsManager.ts#L200))
`    at DeviceOrientationCamera../Cameras/freeCamera.ts.FreeCamera.attachControl` ([freeCamera.ts:191](https://github.com/BabylonJS/Babylon.js/blob/5ec117e974e3064ecef4573eb86e87a0d9511d48/src/Cameras/freeCamera.ts#L191))
`    at new VRExperienceHelper` ([vrExperienceHelper.ts:773](https://github.com/BabylonJS/Babylon.js/blob/5ec117e974e3064ecef4573eb86e87a0d9511d48/src/Cameras/VR/vrExperienceHelper.ts#L773))
`    at Scene../Helpers/sceneHelpers.ts._scene__WEBPACK_IMPORTED_MODULE_1__.Scene.createDefaultVRExperience` ([sceneHelpers.ts:208](https://github.com/BabylonJS/Babylon.js/blob/5ec117e974e3064ecef4573eb86e87a0d9511d48/src/Helpers/sceneHelpers.ts#L208))
`    at (index):51`

**Comment by cchengVA** [comment]
For the purpose of completion, I've attempted to open a similar page (surround in try-catch, show an image if failed) on the Oculus Quest.  In headset, it opens properly if using the Firefox Reality browser, but not the stock browser.

**Comment by cchengVA** [comment]
I have just now found a wrinkle.  Namely, opening the above-mentioned page by way of the `file://` protocol will cause the page to load just fine.  If the page is hosted remotely, then the page breaks.  I'm beginning to wonder if this is a difference in `http` vs `https`.

**Comment by RaananW** [comment]
I can't seem to reproduce this, but a reference error on the line you mentioned can only mean that the Event type is not defined in window. The simplest solution would be to check if the DeviceOrientationEvent exists and only then check if it has the requestPermission function. I will push the change very soon

**Comment by cchengVA** [comment]
I just spent the past while working out getting a self-signed `https` setup.  It turns out DeviceOrientationEvent does not exist in Chrome if you're loading from `http`.  It however does exist when loading from a secure context (such as `file` or `https`).

**Comment by RaananW** [comment]
I actually checked it after you wrote that before, and the standard chrome I have installed does have it (which is odd 🤷‍♂ ). Nonetheless - the PR I submitted will solve this - it checks if the event type exists and only then does the function test.
