### ISSUE TITLE
OBJLoader flips textures along one axis

### ISSUE THREAD

**Issue by MiiBond** [BabylonJS/Babylon.js#7263]
It looks like OBJ files are loaded with textures flipped along the U coord.

Here's an example using this free model (https://free3d.com/3d-model/-oz-beer-bottle-v1--386973.html):

It should look like this:
![Screen Shot 2019-12-04 at 10 32 06 AM](https://user-images.githubusercontent.com/1069125/70170406-79e71100-1681-11ea-8388-bcd5ed4aceb1.png)

But, in Babylon Sandbox, it looks like this:
![Screen Shot 2019-12-04 at 10 32 28 AM](https://user-images.githubusercontent.com/1069125/70170422-823f4c00-1681-11ea-966f-9c5217727311.png)

**Comment by deltakosh** [comment]
Hello we have a parameter for that:
```
BABYLON.OBJFileLoader.INVERT_Y = true;
```

you can also give that parameter to the OBJ loader constructor: https://doc.babylonjs.com/api/classes/babylon.objfileloader#constructor


I would love to be able to detect if the parameter is required from the file but I did not find how unfortunately

**Comment by MiiBond** [comment]
Thanks.
If this is just the issue that WebGL defaults to flipped Y for images (due to the way browsers reference images) then shouldn't `INVERT_Y` be true by default?

**Comment by deltakosh** [comment]
Unfortunately most of the content we dealt with so far required the opposite. This is why I would have loved to find a smart way to deduce it
