### ISSUE TITLE
WebXR: No stereoscopic 3D effect when using MODE_TOPBOTTOM

### ISSUE THREAD

**Issue by mattdmorgan** [BabylonJS/Babylon.js#7264]
0) Open https://www.babylonjs-playground.com/#ZM8UQE#4 in a WebXR-enabled browser (e.g. Chrome Canary).
1) Enter VR.
Result: video plays without a stereoscopic effect -- you see a complete image (not top/bottom stripes), but the same image is shown to each eye.
Expect: stereoscopic 3D effect in video.

Works as expected in WebVR-only browsers (e.g. old Edge).

**Comment by RaananW** [comment]
This happens because the rig camera's isRightCamera is not set to true
