### ISSUE TITLE
Support for 32bit depth buffer

### ISSUE THREAD

**Issue by X-skyer** [BabylonJS/Babylon.js#7289]
As discussed in Feature requests section of the forum:
https://forum.babylonjs.com/t/will-babylon-js-support-32bit-depth-buffer/7496

**Comment by deltakosh** [comment]
Thanks! I will work on it ASAP!

**Comment by deltakosh** [comment]
Btw where did you see that 32bits depth buffer can be turned on on main framebuffer for webgl2?

**Comment by yaserOSource** [comment]
Hi what happened to this?

**Comment by yaserOSource** [comment]
How do you enable this?

**Comment by sebavan** [comment]
This is the default when you create a renderTarget with depth attachment without stencil
