### ISSUE TITLE
Publish this in bower or npm

### ISSUE THREAD

**Issue by NickHeiner** [BabylonJS/Babylon.js#73]
It would be awesome if this project existed in various dependency management tools, like Bower (http://bower.io/) or npm (http://npmjs.org), so it was easier for people to pull into their projects and use.

**Comment by aminroosta** [comment]
+1 for bower package too!

**Comment by matthewharwood** [comment]
+1 for bower package!

**Comment by neutrino84** [comment]
+1 for bower package
