### ISSUE TITLE
glTF loader is slow on assets with lots of nodes

### ISSUE THREAD

**Issue by bghgary** [BabylonJS/Babylon.js#7312]
See twitter thread: https://twitter.com/deltakosh/status/1204891228195545088

Asset is <strike>not shared here as it's not public</strike> here: https://github.com/BabylonJS/Babylon.js/issues/7312#issuecomment-564789519

There are a couple of issues that causes the slowness.

- [x] The glTF validator runs synchronously on the same thread as the main JavaScript thread. The validation of buffer(s) runs on separate tick(s) after the initial synchronous call to validate the JSON payload. The best solution for this is to run glTF validator on a web worker if that's possible.

- [x] <strike>After profiling, it appears calls to Promise functions (e.g. Promise.all, Promise.then) are expensive. If there are only a few, it's not too bad, but because this asset has so many nodes, the problem is multiplied. The glTF loader heavily uses promises and it will be an interesting challenge to stop using them.</strike> Turns out this is a fluke because I profiled with vscode Chrome debugger enabled.

- [ ] `_getGeoemetryByUniqueID` is slow. There is an option on the scene to make it fast. Will figure out what to do here.

**Comment by FreakTheMighty** [comment]
@bghgary the model I emailed can be made public. I'll upload it here to keep it with the issue.
[conference.glb.zip](https://github.com/BabylonJS/Babylon.js/files/3953174/conference.glb.zip)

**Comment by bghgary** [comment]
Turns out the promise issue is a fluke. I was profiling with the vscode Chrome debugger which was causing the slowness.

There is a second issue (unique id map for the add geometries) that is also causing some slowness that I will fix.
