### ISSUE TITLE
Unhelpful error message when using SpritePackedManager (4.1) with an invalid JSON file path

### ISSUE THREAD

**Issue by SacredDuckwhale** [BabylonJS/Babylon.js#7315]
- Link: [Playground](https://www.babylonjs-playground.com/#K5KTWA#30)
- Expected result: Some sort of helpful error message that signals BJS could not find the file requested (like the default JSON parser error) instead of a misleading one
- Current result: BJS gives an entirely puzzling message that I didn't even understand; it sounded like the file was found but somehow malformatted, causing me to go over the formatting with a magnifier, re-export the JSON, etc. Only when I went through the BJS code and disabled the error I got the default JSON parser error, allowing me to find the cause right away. The same wording/message is used three times, by the way, in a slightly different context, which is probably not ideal either. I think the "Spritesheet managed with constant cell size." was not helping, as I had exported a packed spritesheet and it sounded like it was now using a uniform one instead.

---

Not sure if this fits the issue tracker, as it's not really a bug (nor a feature request) and more of a tiny usability concern; feel free to close it if you don't think it's relevant. But I figured since it's a small thing that would help people like myself who are new to using BJS, I might as well post it.

**Comment by deltakosh** [comment]
Pinging @Pryme8

**Comment by deltakosh** [comment]
@SacredDuckwhale  I'm going to close the issue but I pinged Pryne8 and I would recommend to have this discussion on the forum :)

**Comment by Pryme8** [comment]
Got it, yeah I agree.  I will fix that on my next round of sprite updates.   I actually noticed this as well when I was working on some stuff and had to figure out that it was missing the JSON reference through digging around not through the error displayed.  So yes I fully agree.
