### ISSUE TITLE
Use of StackPanel inside ScrollViewer

### ISSUE THREAD

**Issue by BabylonJSGuide** [BabylonJS/Babylon.js#7337]
Unfortunately even though I was the initial author of the ScrollViewer I did have issues getting all the sizings to work together and update and this final part was coded by @deltakosh. Because of the difficulties in updating the sizes it may turn out that there always problems to use a StackPanel with a ScrollViewer. I will have a look but do not think I will be able to solve it for all these cases due to the complex nature of sizing.

#Bugs
noted by 
https://forum.babylonjs.com/t/stackpanel-fill-up-all-remaining-space/7529 - in this PG the issue seems to be making the height of the scroll viewer 100%, though the smaller the browser window the smaller the percentage needed, ie browser 100%, viewer height 92%, browser 50% then viewer height 80%
 
https://forum.babylonjs.com/t/how-to-display-in/7468

https://forum.babylonjs.com/t/scrollviewer-stackpanel-resizing/7621 - in this PG the issue is the use of `this._advancedTexture.idealWidth` without this line it seems OK

**Comment by deltakosh** [comment]
No worries, we will have a look :)

**Comment by Popov72** [comment]
I have answered the different threads in the forum and created a PR for the last one: #7545
