### ISSUE TITLE
Performance improvements for ScrollViewer

### ISSUE THREAD

**Issue by thomlucc** [BabylonJS/Babylon.js#7341]
Need to improve performance of ScrollViewer as it is not usable when there are a high number of elements. Example in https://forum.babylonjs.com/t/fullscreen-ui-with-scrollviewer-performance/7628/7 with 100x50 elements.

**Comment by salamaashoush** [comment]
You can find sample code to test here https://stackblitz.com/edit/typescript-qlkymb

**Comment by Popov72** [comment]
Currently working on this, but is 276000+ controls really sane :) (276041 exactly) ?

**Comment by salamaashoush** [comment]
@Popov72 you can control how many racks created by changing options in `createRooms` function?

**Comment by Popov72** [comment]
I know but I tried with the default settings in the sample, as it is what should be optimized.

**Comment by Popov72** [comment]
See PR #7534
