### ISSUE TITLE
Cloning VideoTexture creates Texture, not VideoTexture

### ISSUE THREAD

**Issue by Armasyll** [BabylonJS/Babylon.js#7383]
I know the docs say VideoTexture is suppose to create a Texture, as it's inherited from Texture, but shouldn't it instead create a VideoTexture?

**Comment by sebavan** [comment]
This is a good question, I guess it defaults to the base class one and does not support cloning actually.

As this is pretty resource intensive (requiring video decoding) as well as error prone (I wonder if the underlying video element should be shared), I guess it is probably why it has not been implemented so far. Also should it share the actual state, playing, pause... etc... or not ?

So I wonder what is your goal when cloning a video texture ? This might help addressing the issue.

@deltakosh any thoughts ?

**Comment by Armasyll** [comment]
I'd assume an instance, rather than a clone, would share states. The clone should be just that, though; a clone, like cloned meshes and instanced meshes.
