### ISSUE TITLE
Undefined left/right camera in WebXR observables

### ISSUE THREAD

**Issue by stefanvanherwijnen** [BabylonJS/Babylon.js#7389]
From: https://github.com/BabylonJS/Babylon.js/issues/7239#issuecomment-571075600

https://www.babylonjs-playground.com/#LUYXFU

I would expect that the state BABYLON.WebXRState.IN_XR is only set after everything WebXR related is set and ready.

**Comment by RaananW** [comment]
Merged, will soon be available in the playground. Please reopen if there is any problem with it
