### ISSUE TITLE
GPUParticleSystem - allow GPU animation from start to end coordinates

### ISSUE THREAD

**Issue by combiz** [BabylonJS/Babylon.js#7392]
Define start and end X,Y,Z coordinates for a GPUParticleSystem and allow GPU tweening / animation of particles between the coordinates.  Essentially a 3D scatter plot allowing smooth transitions of 1,000,000+ data points.  

Ideally a new set of start/end coordinates can be pushed from CPU->GPU at any time (e.g. radio button A,B,C,D,etc on a UI) allowing transition of the same particles between an unlimited number of coordinates.

Happy to provide example coordinate data in CSV format if that helps.  Thank you.

Forum: https://forum.babylonjs.com/t/gpu-particles-start-to-end-animation/7888

**Comment by deltakosh** [comment]
This should work when next nightly will be in:
https://doc.babylonjs.com/babylon101/particles#custom-emitter

**Comment by combiz** [comment]
Amazing turnaround -- thank you.  Very much looking forward to trying this out.  Keep up the great work!
