### ISSUE TITLE
Physics compound body size calculation

### ISSUE THREAD

**Issue by JohanFerret** [BabylonJS/Babylon.js#7407]
Physics compound body not touching the ground.

- Bug repro on [playground](https://playground.babylonjs.com):
https://www.babylonjs-playground.com/#492ZK0#27

- Expected result:
Physics compound body touching the ground.

- Current result:
Physics compound body not touching the ground.

**Comment by RaananW** [comment]
(Documentation only) - Seems like a fundamental issue with compounds:

https://www.babylonjs-playground.com/#492ZK0#28

The transformation calculations of the child-impostors seems to be off. Either that or that the rendering of the object is incorrect.

**Comment by RaananW** [comment]
Reopening - Ammo and Oimo and still acting up:

https://playground.babylonjs.com/#1XWKCR#7

**Comment by RaananW** [comment]
The issue was a missing impostor on the parent:

(cannon) https://playground.babylonjs.com/#1XWKCR#9
(ammo) https://playground.babylonjs.com/#1XWKCR#10
(oimo) https://playground.babylonjs.com/#1XWKCR#11

Closing
