### ISSUE TITLE
Some GLB textures render with artifacts

### ISSUE THREAD

**Issue by nbduke** [BabylonJS/Babylon.js#7418]
# Bugs
Repro playground: https://www.babylonjs-playground.com/#XYZVIV

If you load that playground, you'll see what looks like Moire pattern on the bear model. It didn't use to look this way. If you point the playground at v4.0.3, for example, the pattern disappears.

I can't say for certain when this was introduced, but I know that the model rendered normally as of 4.1.0-alpha.27.

**Comment by deltakosh** [comment]
For some reason the sampling is not linear:
![image](https://user-images.githubusercontent.com/1306056/72176984-94a15980-3394-11ea-8191-2388ec6b3164.png)

Pinging @sebavan  and @bghgary to understand what is the problem

**Comment by sebavan** [comment]
Closing as handled in the previous PR, It will be in our next Nightly
