### ISSUE TITLE
Hover doesn't work on GUIs in XR mode

### ISSUE THREAD

**Issue by nbduke** [BabylonJS/Babylon.js#7420]
# Bugs
Repro playground: https://playground.babylonjs.com/#AM07G2#49

In the playground, hover over the "Click me" button with a mouse. You'll see that on pointer enter, its colors change, and on pointer out, they change back.

Now do the same thing with a controller in XR mode. Pointer enter/out doesn't seem to register, but if you click the button (by pulling the trigger), it will change colors. This is unexpected.

**Comment by RaananW** [comment]
Yeah, for some reason I decided that pointer move should only trigger between pointer down and up. I will add a constant pointer move event
