### ISSUE TITLE
WebXR - Mirror the input-profiles repository

### ISSUE THREAD

**Issue by RaananW** [BabylonJS/Babylon.js#7438]
The WebXR Input Profile repository (https://github.com/immersive-web/webxr-input-profiles) will eventually include all supported controllers, including assets and profile definitions.

This repository is rapidly changing, and now includes mixed reality, oculus, daydream, and all generic controllers.

They license is W3C Software and Document License, we will need to decide:

* Are we hosting the assets (glb files) ourselves, or waiting for them to offer a public repository
* Are we hosting the JSON files (profiles and assets definitions), or integrate them after they change (as we are doing now)
* Is it a clone of the repository, or are we hosting the files differently

If we decide to fully support this repository, we will need to slightly change the architecture of controller loading, thou it is already partly prepared.

**Comment by RaananW** [comment]
My 2 cents (to the questions I added above :-) ):

We will host all files ourselves - including glb models and JSON files, in the same format as the public repository. Essentially it will be a clone of this repository, that we will deploy only after running our own internal tests to make sure the data submitted is consistent with what we want to deliver. 

We will need to see where we can host it and expect a high bandwidth if we automatically load the models with each webxr scene loaded.

**Comment by deltakosh** [comment]
> including glb models and JSON files, in the same format as the public repository. Essentially it will be a clone of this repository, that we will deploy only after running our own internal tests to make sure the data submitted is consistent with what we want to deliver.

Agree!

We can host them in a folder in /assets (will be in assets.babylonjs.com like controllers models)

**Comment by RaananW** [comment]
Upcoming implementation will initially use the github repository, we will need to see how we build and host the assets

**Comment by RaananW** [comment]
PR merged, currently still using version 1.0.0, hosted by github. 
The npm package - https://www.npmjs.com/package/@webxr-input-profiles/motion-controllers can be deployed by us somewhere. This is the repository structure the new ProfiledMotionController class is expecting.
