### ISSUE TITLE
Snap turning breaks if you try to teleport with no floor mesh (WebXR)

### ISSUE THREAD

**Issue by Exolun** [BabylonJS/Babylon.js#7443]
Bug repro is on this [playground](https://www.babylonjs-playground.com/#75J7LQ#2)

Steps to reproduce:
- Enter VR
- Snap turn a few times
- Try to teleport
- Snap turning no longer works

The issue is that if a floor mesh is not provided, there seems to be an error thrown that blows things up!  On our end we wanted to be able to leverage the snap turning controls while having teleportation as optional.

**Comment by RaananW** [comment]
Thanks!

Would probably make sense to add a flag to prevent teleportation which will set to false when no floor-meshes available.

On it :-)

**Comment by RaananW** [comment]
hi @Exolun ,

I was just trying to reproduce this, but it seems to be working correctly. I can't seem to be able to reproduce. Do you mean to simply not provide floorMeshes, or supply an empty array like you show in the playground?

**Comment by Exolun** [comment]
Hi @RaananW  - I was supplying an empty array since that as what we did for the WebVR implementation, but the flag should work fine.   Thanks!

So snap turning didn't break for you in when trying to repro?  Interesting.  I'm using a Windows MR headset by the way.

**Comment by RaananW** [comment]
There is now a flag to disable rotations. If you provide no array, rotation will still work. so, floorMeshes is now optional. if you dont provide it (or provide and empty array), rotation will work, but teleportation won't . PR is here:

https://github.com/BabylonJS/Babylon.js/pull/7445

**Comment by Exolun** [comment]
Very nice.  Thank you!
