### ISSUE TITLE
NME: no shadows displayed when fragmentOutput.a is set

### ISSUE THREAD

**Issue by Popov72** [BabylonJS/Babylon.js#7456]
* open https://playground.babylonjs.com/#MUCYNZ
  * wait for the scene to be displayed:
![image](https://user-images.githubusercontent.com/4152247/72479144-df3b2f80-37f3-11ea-80e4-fddf564faef0.png)
  * there's no shadows (note the wrong rendering for the sphere because zbuffer is not written)
* Click on the "Node Material Editor" button in the inspector
  * far right in the graph: remove the link between "alpha final" and fragmentOutput.a: shadows appear
* Link "alpha final" to fragmentOutput.a again: you get an error:
![image](https://user-images.githubusercontent.com/4152247/72479267-4c4ec500-37f4-11ea-83f0-f123afbb8ff3.png)

Note that if you link a float=1 block directly to fragmentOutput.a it still does not work, no shadows displayed.

**Comment by Popov72** [comment]
It's linked to #7455 : as something is linked to `fragmentOutput.a`, the material is a transparency material, so one has to set "Ignore alpha" on the material to have it rendered into the shadow map.

I still keep this issue opened for the error we got in step 3 above.

**Comment by deltakosh** [comment]
Yeah I have a nasty bug somewhere with the cache system..Digging into it right now

**Comment by deltakosh** [comment]
Regarding node material becoming transparent you have the option to turn it off:
![image](https://user-images.githubusercontent.com/1306056/72482285-053fe000-37b2-11ea-929c-1f9c914c4c7a.png)

**Comment by Popov72** [comment]
That's what I did first, but I had wrong colors in transparent areas, so "Allow transparent shadow" was better for me.
