### ISSUE TITLE
NME: Uniform size does not match uniform method error

### ISSUE THREAD

**Issue by Popov72** [BabylonJS/Babylon.js#7457]
* Save the json of this material locally https://nme.babylonjs.com/#Z965PA
* Open https://playground.babylonjs.com/#71ZSVK#2
* Click on "Node material editor" and load the json saved in step 1

You will get the error:
![image](https://user-images.githubusercontent.com/4152247/72522048-04b05380-385d-11ea-80c1-3f3618ac6be1.png)

**Comment by deltakosh** [comment]
Yes this is a more complicated issue I faced yesterday..It comes from the shader replacement compatibility when switching from shaders (when you recompile a node material)

**Comment by deltakosh** [comment]
The solution is to disable shader hot swapping: https://playground.babylonjs.com/#71ZSVK#3

(Check line #65)

**Comment by Popov72** [comment]
Ok, point noted!
