### ISSUE TITLE
NME: morphing not updated correctly

### ISSUE THREAD

**Issue by Popov72** [BabylonJS/Babylon.js#7466]
https://playground.babylonjs.com/#M5VQE9#2

Morphing of the sphere is not working.

Now click on "Node material editor". Once the material is loaded in the popup, the sphere is refreshed in the main screen and we can see it is deformed (if not, click another time, you may have had bad timing). So it seems the morphed sphere is updated only when the window with the material is opened.

It does work with a simpler material:

https://playground.babylonjs.com/#M5VQE9

**Comment by Popov72** [comment]
It's quite strange, sometimes it works and sometimes not...

When it works, click on the "Play" button of the PG, chances are that it won't work anymore.

**Comment by Popov72** [comment]
When it works, if you open the node material editor, the morphing will stop.

**Comment by deltakosh** [comment]
On it!
