### ISSUE TITLE
NME: wrong orientation for textures

### ISSUE THREAD

**Issue by Popov72** [BabylonJS/Babylon.js#7467]
https://playground.babylonjs.com/#SCEP3W

The two cubes have not the same texturing orientation (they should be identical):
![image](https://user-images.githubusercontent.com/4152247/72571494-095a2380-38c0-11ea-9ce6-225af9af3766.png)

Edit the node material and change the U / V rotation:
![image](https://user-images.githubusercontent.com/4152247/72571439-e3348380-38bf-11ea-870f-0b16fd954138.png)

It is now ok:
![image](https://user-images.githubusercontent.com/4152247/72571526-255dc500-38c0-11ea-81c3-332e08fbf746.png)

**Comment by deltakosh** [comment]
Ok actually it is not a bug :)
By default standardMaterial (for historical reasons) expect the texture to be loaded with invertY set to true but Node Material is using the regular direction

so here is the fix:
```
stdMaterial.diffuseTexture = new BABYLON.Texture("/playground/textures/rock.png", scene, false, false);
```

(Please wait for the next nightly as I found another related issue but overall this is the reason why :))

**Comment by Popov72** [comment]
Ok thanks.

However, I had to not do this correction for the reflection texture, else it would not match the node material.

**Comment by deltakosh** [comment]
Yes this applies only to 2d textures
