### ISSUE TITLE
SVG image scrollbars in scroll viewer

### ISSUE THREAD

**Issue by lockphase** [BabylonJS/Babylon.js#7470]
- Bug repro on https://www.babylonjs-playground.com/#4ZC0G4#3
- Expected result: Both vertical and horizontal scrollbars thumb and bar images should load the correct images from svg file.
- Current result: Vertical scrollbars thumb and bar image are loading the entire svg texture sheet instead. Horizontal scrollbar loads fine.

**Comment by deltakosh** [comment]
Do you mind having a look?

**Comment by deltakosh** [comment]
So far this is not supported because of the way we do the rotation for the vertical bar: we are not considering that the image can contain sprites so instead we rotate the image from the image center to make it vertical (whereas we should rotate the image from the sprite center and then extract the sprite)

I flag this one as enhancement as this is not yet supported

**Comment by lockphase** [comment]
Actually, for images in gui dev, the horizontal and vertical thumb and bar images are not automatically rotated versions of each other. This is due to fake lighting/shadows when creating the visuals. I'm not sure if fixing this is the correct way forward. I would prefer separate images loaded for each item. What do you think ?

ps: not exactly related but is there a way to block scroll events in the scrollviewer similar to isPointerBlocker ?

**Comment by deltakosh** [comment]
> I would prefer separate images loaded for each item

Agree

We cannot block scroll events but it could be a nice addition if you feel fancy to d o a PR :)

**Comment by lockphase** [comment]
> We cannot block scroll events but it could be a nice addition if you feel fancy to d o a PR :)

Maybe somewhere in Feb.

**Comment by Popov72** [comment]
See PR #7561 for the SVG rotation bug.

The separate properties for horizontal/vertical bar images has been handled in PR #7551.
