### ISSUE TITLE
[Discussion] Move WebXR source code out of ./Cameras/

### ISSUE THREAD

**Issue by RaananW** [BabylonJS/Babylon.js#7475]
Historically, we started the VR directory in cameras, as the first class that was created was the VR Free Camera. Since then we continued adding VR classes there, and this is why the XR directory is located in `Cameras` .

I think that before releasing 4.1 we should decide if this is the right place for the files, and where to put them if it isn't 

There are two variants (three, if we include leaving the situation as it is):

1. Move the XR camera to a main directory in `/src/`
2. Distribute the classes in the corresponding directories - Camera in `Cameras`, Input Sources in `Input`, Experience helpers in Tools (or `Helpers`) etc'. 

I am for option 1, would be great to hear your opinion on that

**Comment by deltakosh** [comment]
Well I feel like the current situation is ok. Why do you think it is not the case?

**Comment by RaananW** [comment]
Mainly because it is not really related to a Camera anymore. I wouldn't look for XR-related classes in the Cameras directory. I might look for the WebXR Camera in Cameras, but not the motion controllers, which are technically not related to cameras.

It will also be easier to bundle XR related package without exporting all of the cameras along with it.

**Comment by deltakosh** [comment]
Will it breaks anything besides the folder?

**Comment by RaananW** [comment]
I don't see any technical issue with moving it, but I can do it and test thoroughly before considering our further steps

**Comment by deltakosh** [comment]
![image](https://user-images.githubusercontent.com/1306056/72644927-2b3ac100-3927-11ea-95e9-b68ec929d835.png)
