### ISSUE TITLE
WebXR state remains "Entering" after declining VR permission

### ISSUE THREAD

**Issue by mattdmorgan** [BabylonJS/Babylon.js#7494]
0) Open https://playground.babylonjs.com/#WQCID5#2 in a WebXR browser (any recent Chrome or Edge-Chromium).
1) Click the VR button.
[Result: WebXR state goes to ENTERING_XR, as expected.]
2) In the VR-permission popup, disallow.
Result: WebXR state remains as ENTERING_XR.
Expect: WebXR state to go back to NOT_IN_XR.

**Comment by RaananW** [comment]
Fix was pushed in the referenced PR. Will soon be available in the playground
