### ISSUE TITLE
WebXRSessionManager ignores result of xr.isSessionSupported

### ISSUE THREAD

**Issue by mattdmorgan** [BabylonJS/Babylon.js#7501]
[WebXRSessionManager.IsSessionSupportedAsync](https://github.com/BabylonJS/Babylon.js/blob/a95cb629225a7f487ecd5f3834e9f42613715dff/src/Cameras/XR/webXRSessionManager.ts#L347) is assuming that any non-exception result means the session is supported. This was true for `xr.supportsSession`, but `xr.isSessionSupported` succeeds with a result of false instead. In practice this means that, for instance, 'immersive-vr' is erroneously reported as available even when there's no headset attached.

**Comment by RaananW** [comment]
PR merged, will soon go live.

Thanks a lot for reporting!!
