### ISSUE TITLE
Can't expose gradient node in inspector

### ISSUE THREAD

**Issue by PatrickRyanMS** [BabylonJS/Babylon.js#7525]
# Feature request

- The gradient node, from a UX standpoint, can be classified like the color3/color4 nodes in the user's mind. To that end it stands to reason that the user may want to expose the gradient node values in the inspector in the same way we can with a color3/color4.
- if we can expose the gradient colors, I would expect the UI to be largely the same as it is in NME

**Comment by thomlucc** [comment]
Added as a task to global Inspector vNext #7827
