### ISSUE TITLE
NME: two bugs with the new property page

### ISSUE THREAD

**Issue by Popov72** [BabylonJS/Babylon.js#7528]
* we can't change the boolean float values, clicking on them don't change the value
* https://nme.babylonjs.com/?#AT7YY5#3. At start, there are two "White" variables that don't exist in the material, and each time I click left in the editor area, a new "White" variable is added.

**Comment by deltakosh** [comment]
there are two Whites in the material:
![image](https://user-images.githubusercontent.com/1306056/73123917-027b8280-3f4a-11ea-8056-32ba0e17f6dc.png)

![image](https://user-images.githubusercontent.com/1306056/73123920-0d361780-3f4a-11ea-9436-e04768e882da.png)

**Comment by Popov72** [comment]
Ah yes, I didn't see them (I should have ctrl+f)!
