### ISSUE TITLE
How do I control the zoom speed on GLB viewer

### ISSUE THREAD

**Issue by bart3r** [BabylonJS/Babylon.js#7548]
I have setup babylon.js to view GLB files, but cannot see a configuration setting to control the zoom speed, as I feel the default speed is very fast. 

How would I make the zoom in/out a bit slower?

**Comment by sebavan** [comment]
Github should be used for validated bugs, for questions, please use our forum : https://forum.babylonjs.com/

About your question it depends on your camera type but on ArcRotateCamera you can rely on wheelPrecision or wheelDeltaPercentage and the corresponding pinch properties for touch.
