### ISSUE TITLE
NME: discard node not the same color as other output nodes

### ISSUE THREAD

**Issue by PatrickRyanMS** [BabylonJS/Babylon.js#7558]
# Bugs

- The color of the Discard node is grey like other normal nodes, yet it is categorized with the other output nodes and has no output from the node, only input
- Since this is a terminal node we should treat it like the other terminal nodes in terms of coloring for the purpose of easily finding it in a complex node tree. 

![image](https://user-images.githubusercontent.com/31326855/73412271-f9c5dc00-42bc-11ea-80ab-c98da6182534.png)

**Comment by deltakosh** [comment]
Well it is not an output..Maybe it should have its own color then?

**Comment by PatrickRyanMS** [comment]
If it's not an output, what is it? We have it grouped with outputs and the tool tip says "A final node that will not output a pixel below the cutoff value". The other two nodes have tool tips that list them as "mandatory final nodes" so we either have an issue of grouping and tool tips being wrong or node color being wrong. 

If it is not an output, what should this node type be? Should discard be an integrated part of the fragment output? Something that is only invoked in the code if something is wired to the discard value and cutoff?

**Comment by deltakosh** [comment]
This is the problem, it is a non output :) because it will discard the pixel. I think the tooltip is right and it is in the right group by my guts tell me it should be red or something as it is a discard

**Comment by PatrickRyanMS** [comment]
Deal... let's use color #540b0b on the discard node then. Also we should lowercase the "d" in "discard" to match the other output node patterns and change the header on the group to "Output Nodes" instead of "Output Blocks" for consistency in the tool tips and I think we can close this one out. Not too painful.
