### ISSUE TITLE
Ability to extend inspector with custom tools

### ISSUE THREAD

**Issue by Jaliborc** [BabylonJS/Babylon.js#7559]
- Link to [forum](https://forum.babylonjs.com/t/ability-to-extend-inspector-with-custom-tools/8312) discussion about the feature.
- Would be great to have the ability, with the official API, to add our own custom “tool sections" to the “tools” tab in the inspector. When creating a “custom tool section”, we should be able to specify buttons we can click to run our tools, maybe a couple of checkboxes/sliders/colorpickers for configuring them.

![c1f98951ab8ba1c94b99a7ce98d367050ad75eb2](https://user-images.githubusercontent.com/442637/73413709-d165ce00-430c-11ea-9f1c-9a94c34cd213.png)

**Comment by thomlucc** [comment]
Thanks @Jaliborc , it is added to the issue consolidating requests for Inspector - vNext #7827
