### ISSUE TITLE
New glTF clearcoat sample model crashes Sandbox

### ISSUE THREAD

**Issue by emackey** [BabylonJS/Babylon.js#7568]
I'm developing a new glTF test model for the draft `KHR_materials_clearcoat` extension, in https://github.com/KhronosGroup/glTF-Sample-Models/pull/251.

When I drop the GLB on https://sandbox.babylonjs.com/, I get an unhandled exception in the console:

```
babylon.js:16 BJS - [10:16:38]: Error: FRAGMENT SHADER ERROR: 0:632: 'TBN' : undeclared identifier
ERROR: 0:632: 'perturbNormal' : no matching overloaded function found
ERROR: 0:632: '=' : dimension mismatch
ERROR: 0:632: 'assign' : cannot convert from 'const mediump float' to 'highp 3-component vector of float'
```

/cc @bghgary @sebavan

**Comment by sebavan** [comment]
@emackey  could you share the gltf or glb ???

This looks like a bug I would like to address ASAP.

**Comment by emackey** [comment]
Here's a direct link:  [ClearCoatTest.glb](https://github.com/KhronosGroup/glTF-Sample-Models/blob/4062d54d711a06ef48a05c5d38fc8c61b2e60bf1/2.0/ClearCoatTest/glTF-Binary/ClearCoatTest.glb).

The linked PR also has the [separated glTF version](https://github.com/KhronosGroup/glTF-Sample-Models/tree/4062d54d711a06ef48a05c5d38fc8c61b2e60bf1/2.0/ClearCoatTest/glTF).

**Comment by sebavan** [comment]
Perfect fix will be in in less than 1 hour ;-)

**Comment by sebavan** [comment]
Actually might be a bit longer, just figured I did not manage clear coat bump without bump at all. I am on it thanks a lot for the repro :-)

**Comment by sebavan** [comment]
Yes I am in less than 1 hour, was scared to have lied ;-)
