### ISSUE TITLE
User quotes page for Website

### ISSUE THREAD

**Issue by PatrickRyanMS** [BabylonJS/Babylon.js#7584]
# Add user quotes page to highlight testimonials by users

- [ ] Style exploration for template
- [ ] Add collected feedback
- [ ] Update menu system to include links to page

Pushing full quotes page to 4.2 so that we can get partner testimonials. For now we will include some quotes on the landing page as a rolling content block and implement the full page once we have more content approved for use.

**Comment by thomlucc** [comment]
Moved issue to Website repo.
