### ISSUE TITLE
Unnecessary calculations in vertex shader

### ISSUE THREAD

**Issue by avin** [BabylonJS/Babylon.js#7585]
Hey guys! Found this two lines in shaders, and seems like they do the same things, making unnecessary calculations
https://github.com/BabylonJS/Babylon.js/blob/master/materialsLibrary/src/simple/simple.vertex.fx#L57

line 57 and 59

Maybe this option is better?

```
	vec4 worldPos = finalWorld * vec4(position, 1.0);
	gl_Position = viewProjection * worldPos;
```

thank you!

**Comment by deltakosh** [comment]
this is correct :D

Fancy doing a PR?

**Comment by avin** [comment]
already doing)
