### ISSUE TITLE
Using renderingGroupId breaks PCF shadows

### ISSUE THREAD

**Issue by Exolun** [BabylonJS/Babylon.js#7596]
Repro steps:

1. Create a shadow generator with PCF shadows
2. Add a few meshes to the scene
3. Add them to the shadow map
4. Set a renderingGroupId on any mesh

Result - the meshes aside from the one assigned a renderingGroupId lose their shadows.  If you remove the renderingGroupId from the given mesh all shadows go away.

Playground link:
[https://playground.babylonjs.com/#B48X7G#30](https://playground.babylonjs.com/#B48X7G#30)

**Comment by sebavan** [comment]
Fixed by previous PR, thanks for reporting

**Comment by Exolun** [comment]
Oh good.  Very nice!
