### ISSUE TITLE
Playground Typescript / Javascript switch confusing interface

### ISSUE THREAD

**Issue by codediver1210** [BabylonJS/Babylon.js#7601]
# Bugs
It's confusing.
The yellow box area shouldn't be clickable and display other tool-tip.
For example, "using javascript now". something like this.

<img width="1121" alt="babylonpg" src="https://user-images.githubusercontent.com/49501049/73900200-55522400-48d2-11ea-8ad9-46d60f3263d9.png">

**Comment by PatrickRyanMS** [comment]
Design complete. Passing to @deltakosh for implementation.

**Comment by deltakosh** [comment]
Actually on kyle ;)

**Comment by RaananW** [comment]
@PatrickRyanMS , please check if it's fine the way it is
