### ISSUE TITLE
NME - Bug in camera distance in preview on load

### ISSUE THREAD

**Issue by PatrickRyanMS** [BabylonJS/Babylon.js#7608]
# Bug
- With the new mesh drop down, when NME is loaded, the distance of camera from mesh is not the same as when you change to another mesh.

### Repro
- Load NME fresh. Note the distance the camera is from the mesh in the preview window. 
- Don't interact with the preview window, leave the camera where it is.
- Change drop down to any other mesh and note the distance of camera from mesh
- Chage drop down back to cube and note that the camera is much closer than when the page was loaded. 

### Expected
- When loading the page, the distance of the camera from mesh should be consistent when changing to any other mesh and back to the default mesh.

**Comment by deltakosh** [comment]
I do not repro :(

**Comment by deltakosh** [comment]
[Babylon.js Node Material Editor 2020-02-06 14-48-00.mp4.zip](https://github.com/BabylonJS/Babylon.js/files/4168118/Babylon.js.Node.Material.Editor.2020-02-06.14-48-00.mp4.zip)

**Comment by PatrickRyanMS** [comment]
This is what I am seeing:

[BabylonNME_preview.zip](https://github.com/BabylonJS/Babylon.js/files/4168133/BabylonNME_preview.zip)

**Comment by deltakosh** [comment]
OK I repro if the cube is the initial mesh
