### ISSUE TITLE
Member filtering is broken in the playground

### ISSUE THREAD

**Issue by sailro** [BabylonJS/Babylon.js#7612]
@RaananW it seems you are working on optimizing the workload around the playground, this is great but please be extra careful as this part is highly technical:

For instance, you recently changed the monaco version used:
https://github.com/BabylonJS/Babylon.js/commit/a5d9190a885ac35b4837c10e865f84ecade15667#diff-68a866b97c7bf8685f1e78573f06eb21

And you removed the hook we made on purpose to filter members, see this PR:
https://github.com/BabylonJS/Babylon.js/pull/7169

We were using the 'dev' version purposely to do something that is not yet possible with the current Monaco API (using monkey patching).

You should review the repo history/PR to make sure you are not breaking something going forward.

I fully agree that this one is a bit tricky and we should add comments to properly explain what we do.

cc @deltakosh 

Thanks!
Seb

**Comment by RaananW** [comment]
I am reverting this right now, not a problem at all.

**Comment by sailro** [comment]
Thanks, I will submit a PR to add better comments for this tricky part.

**Comment by RaananW** [comment]
let me first clean this up.

I did that for two reasons:

1) loading from node_modules is not the cleanest way of loading assets
2) cloudflare's cdn is fast and reliable.

But I understand there is a reason for that.
