### ISSUE TITLE
Update KTX2 support to use JS instead of WASM for parsing the KTX2 container

### ISSUE THREAD

**Issue by bghgary** [BabylonJS/Babylon.js#7644]
PR #7640 adds support for KTX2, but all the decoding is happening on the main thread. The code is using libktx.js/wasm to do the decoding. This lib expects a webgl context to be passed in. This prevents the code from being called from a web worker and is a bit bigger than it needs to be. PR https://github.com/KhronosGroup/KTX-Software/pull/172 adds some JS code to parse the KTX2 container and only use WASM to decode the data into the appropriate GPU format. This should hopefully allow the decoding to happen in a web worker. The resulting decoded data can then be transferred to the main thread to upload to the GPU.

**Comment by thomlucc** [comment]
Done
