### ISSUE TITLE
Add links to node API within docs

### ISSUE THREAD

**Issue by PatrickRyanMS** [BabylonJS/Babylon.js#7650]
## Documentation
The connection between the docs for nodeMaterial blocks and the API needs to be tighter. Can we add the link to the API doc page https://doc.babylonjs.com/api/classes/babylon.nodematerial to the node material doc page https://doc.babylonjs.com/how_to/node_material at the start of the list of available blocks?

We should also add language around the setting the value of a block:

> Or you can also use this API to get an InputNode and use it to setup its value if the node is set manual value:
> 
> let block = nodeMaterial.getInputBlockByPredicate((b) => b.name === "foo");
> block.value = 10;

This implies that any block can have a value set with block.value, which isn't accurate. For example a texture block needs block.texture to set the texture on the block. Broadening the language to say something like "you can set the value like this example with a float block using block.value = 10" implies that value applies to the float block. Adding another link to the API here saying to search the api for the block you need will let people know how to find what they need to use.

**Comment by deltakosh** [comment]
> This implies that any block can have a value set with block.value

Well it is not what I'm reading. It is stated that you can get an InputBlock. So maybe we should be crisper on that point ?

**Comment by deltakosh** [comment]
What I mean is that getInputBLock will return an InputBLock (float, olor3, color4, etc..) and you can then set its value

For other blocks, you have to use getBlockByName()

**Comment by PirateJC** [comment]
https://github.com/BabylonJS/Documentation/pull/1914
