### ISSUE TITLE
Feature Request:  Inverted camera/natural panning controls for TargetCamera

### ISSUE THREAD

**Issue by Exolun** [BabylonJS/Babylon.js#7663]
Currently the default camera controls for the FPS style cameras feature a direct mapping style of turning - such that dragging the mouse left results in the camera turning left.

We've gotten some customer asks to support inverting this behavior to match flight simulator style controls or perhaps the Google Maps type of panning.

Something as simple as a `invertRotation` flag would do the trick for now.

**Comment by Drigax** [comment]
+1 
This sounds like a natural addition to any all i  one camera controlling solution

**Comment by deltakosh** [comment]
Fancy doing a PR?

**Comment by Exolun** [comment]
@deltakosh  Sure - I can do a PR for this for 4.2!

**Comment by thomlucc** [comment]
@Exolun, we are on for 4.2!

**Comment by syntheticmagus** [comment]
@Exolun Out of curiosity, is the desired behavior for this something close to [spherical panning](https://doc.babylonjs.com/snippets/sphericalpanning)?

**Comment by deltakosh** [comment]
Ping @Exolun

**Comment by deltakosh** [comment]
Closing for now. Please reopen if required
