### ISSUE TITLE
NME - Color changed in inspector does not reflect on node preview

### ISSUE THREAD

**Issue by PatrickRyanMS** [BabylonJS/Babylon.js#7665]
## Bug

I have a Color3 node in the graph that is exposed to the inspector and have the node material editor open while working on the scene. I make a change to the exposed color in the inspector with the editor still open. The value in the node material editor updates to reflect the change in the inspector, but the node preview does not update to the latest color.

You can see in the image that the Color3 node has a white preview but it's value in the parameters panel is dark grey from the change in the inspector. I often work on a scene with both the inspector and the node material editor open and it is useful to be able to tweak values in either inspector or NME and have the changes propagate to the other.

![image](https://user-images.githubusercontent.com/31326855/74559299-e5b6e700-4f18-11ea-8b99-b8b99b53620f.png)

**Comment by deltakosh** [comment]
Not a supported feature..Will redefine as evolution for 4.2

**Comment by deltakosh** [comment]
Well actually the code to add is small so it should not break my tests
