### ISSUE TITLE
Cascaded Shadow Generator shadows have artifacts in right handed scenes

### ISSUE THREAD

**Issue by Drigax** [BabylonJS/Babylon.js#7666]
Continuing discussion from: https://github.com/BabylonJS/Babylon.js/pull/7610#issuecomment-584410757

Cascaded shadows in a right handed scene appear to have artifacts pop in and out depending on shadow direction:

Left handed scene:
![image](https://user-images.githubusercontent.com/3952729/74560273-1435c180-4f1b-11ea-9038-7985560f0e2f.png)

Right handed scene:
![image](https://user-images.githubusercontent.com/3952729/74565315-d7bb9300-4f25-11ea-9a5f-95fa312cd5f1.png)

Reproduces consistently via:
https://www.babylonjs-playground.com/#IIZ9UU#42

**Comment by Drigax** [comment]
pinging @Popov72 and @sebavan

**Comment by Popov72** [comment]
I'm going to have a look.

**Comment by Popov72** [comment]
Fixed in #7668
