### ISSUE TITLE
NME - Remap does not display evaluated value if input node is not a float

### ISSUE THREAD

**Issue by PatrickRyanMS** [BabylonJS/Babylon.js#7671]
## Bug

When connecting an input to the Remap node that is not a float, the value from the connected node is not evaluated when displaying the range on the node. Any type of math node that computes a value will display a "?" instead of a value.

![image](https://user-images.githubusercontent.com/31326855/74601317-a4762280-5051-11ea-941a-62f0fd60ba40.png)

**Comment by deltakosh** [comment]
We do not preview values. We must wait for the 4.2 preview mode
