### ISSUE TITLE
NME - Resize frame bottom at times will not work for any frame in the graph

### ISSUE THREAD

**Issue by PatrickRyanMS** [BabylonJS/Babylon.js#7672]
## Bug
I am not sure what the root cause of this is because I can not reliably repro the issue, but I have a node material json where the frames will not resize from the bottom and have attached it. All frames act the same in that none will resize from the bottom but sides and top still work. 

I have noticed this happen a few times, but do not see a trend as to when to expect it in a graph.

[brokenBottomResize.zip](https://github.com/BabylonJS/Babylon.js/files/4209517/brokenBottomResize.zip)

**Comment by deltakosh** [comment]
I let @belfortk have a look first. Please tell me if you need help :)
