### ISSUE TITLE
GUI.Checkbox doesn't show value when checked and disabled

### ISSUE THREAD

**Issue by Armasyll** [BabylonJS/Babylon.js#7676]
As the title says; GUI.Checkbox doesn't show its check when disabled, but immediately does when enabled. Maybe have disabledColor also color the check?

**Comment by deltakosh** [comment]
Can you repro in the Playground?

**Comment by deltakosh** [comment]
Adding @CedricGuillemet if he has some free cycles

**Comment by Armasyll** [comment]
My apologies, mates;
https://www.babylonjs-playground.com/#U9AC0N#118

**Comment by CedricGuillemet** [comment]
I'm on it!
