### ISSUE TITLE
Using the inspector to change colors for PBR materials: convert to linear colors?

### ISSUE THREAD

**Issue by Popov72** [BabylonJS/Babylon.js#7678]
As the internal workflow for PBR materials is linear, I think the colors chosen from a color picker should be transformed to linear before updating the material property: what do you think?

That would mean updating the `color3LineComponent` / `color4LineComponent` so that they are able to convert to gamma before showing the color picker with the current color, and to convert to linear before updating the property.

**Comment by deltakosh** [comment]
Agree, we should have an optional props for that

**Comment by Popov72** [comment]
PR done: https://github.com/BabylonJS/Babylon.js/pull/7768
