### ISSUE TITLE
Add support for local space for GPU particles

### ISSUE THREAD

**Issue by deltakosh** [BabylonJS/Babylon.js#7693]
Local space is for now only supported by CPU particles (as of 4.1)

**Comment by deltakosh** [comment]
This: https://doc.babylonjs.com/babylon101/particles#local-space is only supported by cpu particles

**Comment by CraigFeldspar** [comment]
@deltakosh I'm on it

**Comment by thomlucc** [comment]
Closing as it has been done with PR: https://github.com/BabylonJS/Babylon.js/pull/8013. Thanks @CraigFeldspar!
