### ISSUE TITLE
DeviceOrientationCamera properties not displayed in inspector

### ISSUE THREAD

**Issue by brian-hay** [BabylonJS/Babylon.js#7697]
### Bug repro
https://www.babylonjs-playground.com/#SRZRWV#3
(activate Inspector then select camera)

### Expected result
DeviceOrientationCamera properties display in inspector like other camera types e.g. ArcRotateCamera.

### Current result
DeviceOrientationCamera properties not displayed in inspector

**Comment by RaananW** [comment]
will soon be deployed
