### ISSUE TITLE
bug fix for chrome wheel scroll in isPointerBlocker

### ISSUE THREAD

**Issue by lockphase** [BabylonJS/Babylon.js#7702]
In reference to https://forum.babylonjs.com/t/mousewheel-zoom-and-scroll-in-scrollviewer-not-working/8711, I've found the bug to be in advancedDynamicTexture.ts from 

```
this._doPicking(x, y, pi.type, (pi.event as PointerEvent).pointerId || 0, pi.event.button, (<MouseWheelEvent>pi.event).deltaX, (<MouseWheelEvent>pi.event).deltaY);
```

The fix is exceedingly simple but potentially breaking ```(pi.event as PointerEvent).pointerId || 0``` to ```(pi.event as PointerEvent).pointerId || 1```. ffox and chrome return different pointerId values for pointerMove (ffox: 0, chrome: 1) so my big question was 'why was it set to 0 in the first place?' Is there a reason for it and will the fix break other browsers? If not, I'm happy to submit the PR.

**Comment by deltakosh** [comment]
Rats... Browsers are painful... I'll check ;)

**Comment by deltakosh** [comment]
> (pi.event as PointerEvent).pointerId || 1

Doing this breaks Chrome but works on FF
