### ISSUE TITLE
enableEdgesRendering crash on scene dispose in 4.0.3

### ISSUE THREAD

**Issue by Gpinchon** [BabylonJS/Babylon.js#7719]
scene dispose crashes when using Edgesrenderer in 4.0.3 release (commit 9deb1df98eed29fe2b503c1201f2150dba3ebcb5) because of missing modification made here : 2e96c10092abc1705cbc4c98ee94d4b36ddc4140

It would be nice to add this modification to 4.0 and make a new release.

**Comment by deltakosh** [comment]
We do not port fix back (4.1 will be out this Thursday)
