### ISSUE TITLE
Tools.CorsBehavior doesn't have any effect anymore

### ISSUE THREAD

**Issue by yvele** [BabylonJS/Babylon.js#7736]
## Bug

[`Tools.CorsBehavior`](https://doc.babylonjs.com/api/classes/babylon.tools#corsbehavior) isn't working anymore.

You can set it either with a string or a function but it has no effect at all on how Babylon handle CORS in HTML elements.

Looks like this has been broken while refactoring some parts of `Tools` to `FileTools` https://github.com/BabylonJS/Babylon.js/commit/f2dff3b2f2a35165577f5814dc19c2fe547a2522

The condition is checking for `FileTools.CorsBehavior` instad of `Tools.CorsBehavior`.

This is the original commit that was handling this feature: https://github.com/BabylonJS/Babylon.js/pull/792

Is it possible to add a unit test not to face this again (regression bug) in the future?

-------

PS: Also in my opinion the default CORS behaviour should be `undefined` instead of `anonymous` (exactly how Webpack is doing). Note that both `undefined` and `anonymous` does the same thing, but having `undefined` by default is more "clean".

**Comment by deltakosh** [comment]
Yep I forgot a redirection from Tools to FIleTools

I will add it. In the meantime just use FileTools.CorsBehavior as it is the normal way to go
