### ISSUE TITLE
Allow alpha testing + alpha blending at the same time

### ISSUE THREAD

**Issue by Popov72** [BabylonJS/Babylon.js#7758]
See this post in the forum for context: https://forum.babylonjs.com/t/meshes-transparency/8965/9

Currently you can't have alpha testing and alpha blending at the same time for the standard material  (when alpha values come from the diffuse texture) => it is possible with the PBR material.

See this PG: https://playground.babylonjs.com/#68RZKR#3

You have alpha blending on both spheres (left: std material, right: pbr) and not alpha testing. Both are enabled, meaning `mat.needAlphaBlending()` / `mat.needAlphaBlendingForMesh()` and `mat.needAlphaTesting()` both return `true`, but only alpha blending is enabled for the rendering because of this function (defined on `Material`):

```typescript
protected _shouldTurnAlphaTestOn(mesh: AbstractMesh): boolean {
    return (!this.needAlphaBlendingForMesh(mesh) && this.needAlphaTesting());
}
```
Because of this function, when you have both effects on, alpha blending takes precedence and alpha testing is disabled.

We could change this function to:
```typescript
protected _shouldTurnAlphaTestOn(mesh: AbstractMesh): boolean {
    return this.needAlphaTesting();
}
```
to have both effects at the same time: try to uncomment line 38 in the PG and you will see it does work.

HOWEVER, how to have alpha blending without alpha testing with this change? I think it is not possible (at least when we want the alpha values to come from the diffuse texture)...

Maybe I missed something and it is possible to have alpha blending without alpha testing with this change, in which case I can make the PR right away.

But if it's not possible, how to handle that? Should we add a property like `enableBothAlphaBlendingAndTesting` to the material and implement `_shouldTurnAlphaTestOn` as:

```typescript
protected _shouldTurnAlphaTestOn(mesh: AbstractMesh): boolean {
    return (!this.needAlphaBlendingForMesh(mesh) && this.needAlphaTesting() && !this.enableBothAlphaBlendingAndTesting)
            ||
        (this.needAlphaTesting() && this.enableBothAlphaBlendingAndTesting);
}
```
? Bonus: it is not a breaking change.

Or something else?

Note that for PBR it is possible to do whatever we want regarding alpha blending / alpha testing mixing thanks to the `transparencyMode` property (uncomment line 57 in the PG). So whatever we decide for the standard material, I think the PBR material shouldn't be impacted.

**Comment by sebavan** [comment]
Maybe we could include the same than PBR in standard and set it up with a default to not break back compat ? so we gain in consistency without potentially breaking things ?

Liks a transparencyMode being null would mean use the current behavior else use the transparency mode ?

Just a big maybe :-) adding @bghgary as well as we had those kind of discussions in the past.

**Comment by bghgary** [comment]
> a transparencyMode being null would mean use the current behavior else use the transparency mode ?

This is exactly what happens in the PBR material. Search for `_transparencyMode` in https://github.com/BabylonJS/Babylon.js/blob/master/src/Materials/PBR/pbrBaseMaterial.ts.

**Comment by Popov72** [comment]
Going to make a PR so that we will be able to discuss about the implementation.

**Comment by Popov72** [comment]
See #7775
