### ISSUE TITLE
Cannot move camera if mouse button down while pointer locked in Firefox

### ISSUE THREAD

**Issue by jeffhube** [BabylonJS/Babylon.js#7797]
If you acquire pointer lock, you are unable to move a UniversalCamera or FreeCamera while holding down a mouse button. This only seems to affect Firefox (I am using 74.0 on Windows 10 x64).

It looks like this used to work in version 3.1.0-alpha3.5 and prior, but it broke in 3.1.0-alpha3.6. Unfortunately I don't see any tags for these versions to help identify the relevant commits.

I've attached a repro where you can compare the behavior across 3.1.0-alpha3.5 (works), 3.1.0-alpha3.6 (doesn't work), and 4.1.0 (still doesn't work). Open index.html in Firefox. Click each canvas to acquire pointer lock, wiggle the mouse while holding down the left mouse button, press escape to release pointer lock.

[repro.zip](https://github.com/BabylonJS/Babylon.js/files/4316122/repro.zip)

- Bug repro on https://playground.babylonjs.com/#E1CIQM

- Expected result: After clicking the canvas to acquire pointer lock, if you hold down the left mouse button while wiggling the mouse, the camera should move.

- Current result: After clicking the canvas to acquire pointer lock, if you hold down the left mouse button while wiggling the mouse, the camera does not move.

**Comment by RaananW** [comment]
As per this discussion: https://forum.babylonjs.com/t/firefox-pointerlock-mousemove-mousedown-behavior/960/6 , this is an issue with firefox.

When in pointer lock, the mousemove event is not triggered when pointerdown was triggered. This [tip](https://forum.babylonjs.com/t/firefox-pointerlock-mousemove-mousedown-behavior/960/7?u=raananw) seems to fix the issue on firefox.

**Comment by RaananW** [comment]
Closing for now

**Comment by jeffhube** [comment]
I'll just leave some notes here in case anyone decides to revisit this in the future.

`scene.preventDefaultOnPointerDown = false;` seems to fix the issue like so: https://playground.babylonjs.com/#RQYBQG

In 3.1.0-alpha3.6, babylon.js started calling `preventDefault()` on `pointerdown`.

Firefox does not currently emit `mousemove` events during pointer lock if a mouse button is down and you call `preventDefault()` on the `pointerdown` event. It will only emit `pointermove` events.

```
<html>
    <body>
        <canvas id="canvas" width="400" height="400" style="background-color: gray;"></canvas>
        <script>
            const canvas = document.getElementById('canvas');
            canvas.addEventListener('click', () => { canvas.requestPointerLock() });
            canvas.addEventListener('pointerdown', (evt) => { evt.preventDefault(); });
            canvas.addEventListener('pointermove', (evt) => { console.log('pointermove'); });
            canvas.addEventListener('mousemove', (evt) => { console.log('mousemove'); });
        </script>
    </body>
</html>
```
