### ISSUE TITLE
How to add drag behaviors for imported OBJ file model ?

### ISSUE THREAD

**Issue by krishnauppili** [BabylonJS/Babylon.js#7809]
Hi all,
This is my example code for applying PointerDragBehavior for the meshes obtained from imported OBJ file. The object file is getting loaded but I'm unable to drag the meshes obtained from the file. I'm currently using BabylonJs with React.

componentDidMount = () => {
    this.engine = new BABYLON.Engine(this.canvas, true);
    scene = new BABYLON.Scene(this.engine);

    let camera = new BABYLON.FreeCamera("camera1", new BABYLON.Vector3(1, 5, -550), scene);
    camera.setTarget(BABYLON.Vector3.Zero());
    let light = new BABYLON.HemisphericLight("light1", new BABYLON.Vector3(0, 1, 0), scene);
    light.intensity = 0.7;

    let pointerDragBehavior = new BABYLON.PointerDragBehavior({dragAxis: new BABYLON.Vector3(1,0,0)});
    pointerDragBehavior.useObjectOrientationForDragging = false;

    pointerDragBehavior.onDragStartObservable.add((event)=>{
      console.log("dragStart");
      console.log(event);
    })
    pointerDragBehavior.onDragObservable.add((event)=>{
      console.log("drag");
      console.log(event);
    })
    pointerDragBehavior.onDragEndObservable.add((event)=>{
      console.log("dragEnd");
      console.log(event);
    })

    let assetsManager = new BABYLON.AssetsManager(scene);
    let meshTask = assetsManager.addMeshTask("Teeth task", "", "/", "IronMan.obj");
    meshTask.onSuccess = (task) => {
      task.loadedMeshes[0].position = BABYLON.Vector3.Zero();
    };

    assetsManager.onFinish =  (tasks) =>  {
      tasks[0].loadedMeshes.map((mesh) => {
        mesh.addBehavior(pointerDragBehavior);
        return mesh;
      });
      this.engine.runRenderLoop(function () {
        scene.render();
      });
    };
    assetsManager.load();
  };

Any support would help. Thanks in advance !!

**Comment by sebavan** [comment]
Github should only be used for bugs and issues, as for questions we are using the forum https://forum.babylonjs.com/

I created your question there to follow up on this thread: https://forum.babylonjs.com/t/how-to-add-drag-behaviors-for-imported-obj-file-model/9154

**Comment by sebavan** [comment]
Answered there : https://forum.babylonjs.com/t/how-to-add-drag-behaviors-for-imported-obj-file-model/9154/3

The code actually works great in the playground so it is probably related to the setup. Please, continue the discussion on the forum thread.
