### ISSUE TITLE
How to add a custom object on top of all imported meshes?

### ISSUE THREAD

**Issue by krishnauppili** [BabylonJS/Babylon.js#7833]
I have imported a teeth object which has around 64 meshes. I want to create a cube object on front face of all the meshes. I'm able to do this with scene.pick when clicking on the scene. But I want to do this on loading all the meshes without binding any actions to it. I have tried mesh.getBoundingInfo but it adds the cube in the spherical centre of the object. Any thoughts would greatly help. Thanks in advance!

**Comment by deltakosh** [comment]
Please use the forum for question: forum.babylonjs.com
