### ISSUE TITLE
Can't assign CubeTexture to ShaderMaterial in TS

### ISSUE THREAD

**Issue by epascal** [BabylonJS/Babylon.js#7852]
When I try to assign a CubeTexture via setTexture to a ShaderMaterial I got a compilation error in TypeScript :

 **this.material.setTexture('cubeMap', new CubeTexture('assets/envmap/desk', this.scene));**

the workaround is to force typing: 

 **this.material.setTexture('cubeMap', new CubeTexture('assets/envmap/desk', this.scene) as unknown as Texture);**

after that it works, but it's disturbing, could you fix the TypeScript interfaces to allow this ?

Best Regards,

**Comment by sebavan** [comment]
Closed by #7855
