### ISSUE TITLE
Playground Based Tutorials No Longer Works

### ISSUE THREAD

**Issue by BabylonJSGuide** [BabylonJS/Babylon.js#7853]
# Bugs
Even using BJS v3.3
https://www.babylonjs-playground.com/#KNSQD7#, for example logs this error

```javascript
TypeError: "jsEditor.updateOptions is not a function"
    editOff https://www.babylonjs-playground.com/js/pbt.js:1
    createScene https://www.babylonjs-playground.com/#KNSQD7# line 1 > scriptElement:1006
    <anonymous> https://www.babylonjs-playground.com/#KNSQD7# line 1 > scriptElement:1016
    fastEval https://www.babylonjs-playground.com/js/main.js:1
    compileAndRun https://www.babylonjs-playground.com/js/main.js:1
main.js:1:127
    handleException https://www.babylonjs-playground.com/js/main.js:1
    <anonymous> https://www.babylonjs-playground.com/#KNSQD7# line 1 > scriptElement:1018
    fastEval https://www.babylonjs-playground.com/js/main.js:1
    compileAndRun https://www.babylonjs-playground.com/js/main.js:1
```
It appears some changes to the way the Monaco Editor works in the playground  have stopped pbt.js functioning. 

If the fix is NOT straight forward then as, other than the example playgrounds I wrote when developing pbt, it is never used we can remove pbt.js from the Playground

**Comment by deltakosh** [comment]
Good luck!

**Comment by BabylonJSGuide** [comment]
Having looked at what will be involved in re-writing pbt.js and considering its lack of use I will remove it and also any references to it in the docs shortly.

**Comment by deltakosh** [comment]
Totally agree!
