### ISSUE TITLE
Support RealTime filtering of cube maps for PBR

### ISSUE THREAD

**Issue by sebavan** [BabylonJS/Babylon.js#7867]
This could help with real time probes, support for unprefiltered environments. We could inspire ourself from :

https://developer.nvidia.com/gpugems/gpugems3/part-iii-rendering/chapter-20-gpu-based-importance-sampling

Or newer techniques.

**Comment by Vinc3r** [comment]
> This could help with real time probes

'love this part :-p

**Comment by CraigFeldspar** [comment]
@sebavan On it !
