### ISSUE TITLE
AssetsManager / TextureAssetTask should not flip textures vertically by default

### ISSUE THREAD

**Issue by broederj** [BabylonJS/Babylon.js#7879]
Hi guys,

I've noticed that, when loading a texture using the AssetManager's TextureAssetTask, the resulting texture is being flipped vertically - even if the (optional) argument "invertY" is omitted. In the [code comments](https://github.com/BabylonJS/Babylon.js/blob/master/src/Misc/assetsManager.ts#L509-L512) it says that the default is false, but that doesn't seem to be the case.

- Bug repro on [playground](https://playground.babylonjs.com/#USVG25)
- Expected result: The texture is only inverted when invertY is explicitly set to true, or otherwise the documentation should say so.
- Current result: The texture is inverted by default.

I've narrowed it down to the Texture class, which looks to have some inconsistent/confusing defaults. For example, see [here](https://github.com/BabylonJS/Babylon.js/blob/master/src/Materials/Textures/texture.ts#L199), [here](https://github.com/BabylonJS/Babylon.js/blob/master/src/Materials/Textures/texture.ts#L280), [here](https://github.com/BabylonJS/Babylon.js/blob/master/src/Materials/Textures/texture.ts#L759) and [here](https://github.com/BabylonJS/Babylon.js/blob/master/src/Materials/Textures/texture.ts#L779). What do you think?

Thanks!

**Comment by deltakosh** [comment]
Texture has a lot of history hence the inconsistency :)

But I agree that the textureAssets must be fixed..Fancy doing a PR?

**Comment by broederj** [comment]
Sure! https://github.com/BabylonJS/Babylon.js/pull/7883
