### ISSUE TITLE
Geometry missing from Draco-compressed glTF

### ISSUE THREAD

**Issue by MiiBond** [BabylonJS/Babylon.js#7922]
The attached GLB loads fine in Three.js, Cesium and Adobe Dimension but is missing half the geometry when rendered in Babylon. When exported without Draco, it works fine, so I assume that this is an issue with how Draco meshes are loaded.

[draco_test.zip](https://github.com/BabylonJS/Babylon.js/files/4389414/draco_test.zip)

**Comment by bghgary** [comment]
@deltakosh @sebavan Looks like instancing is broken. It has nothing to do with Draco. If I turn off instancing in glTF loader, the model renders correctly.

**Comment by bghgary** [comment]
Min repro: https://playground.babylonjs.com/#SPYB5B

**Comment by bghgary** [comment]
@deltakosh Is what I'm doing even allowed?

**Comment by deltakosh** [comment]
it is not common but it shou;d work
I'll check what is wrong

**Comment by deltakosh** [comment]
Wait no this is not possible (You cannot instanciate a shared geometry:
https://doc.babylonjs.com/how_to/how_to_use_instances#limitations

There is an easy fix: Just call `mesh.makeGeometryUnique()` before calling createInstance:

https://playground.babylonjs.com/#SPYB5B#2

**Comment by bghgary** [comment]
Unfortunately, fix didn't work. glTF loader doesn't assign geometry until after the instances are created.

**Comment by bghgary** [comment]
New min repro: https://playground.babylonjs.com/#SPYB5B#3
