### ISSUE TITLE
Mesh destruction tool

### ISSUE THREAD

**Issue by thomlucc** [BabylonJS/Babylon.js#7924]
@CedricGuillemet: you will create a Mesh destruction tool as one of you demo, that's correct?

**Comment by CedricGuillemet** [comment]
I didn't get a lot of traction on this feature. Making a tool for that is overkill considering the benefits IMHO.
But I think the same technic (with baked animation in textures) can be applied to export particles/destruction/physics from tools like Houdini. What do you think @PatrickRyanMS ?

**Comment by deltakosh** [comment]
I agree we should not invest on it as we see no traction. I vote to close this issue

**Comment by thomlucc** [comment]
OK, closing as no traction (this was from our 4.2 Brainstorm session). Re-open if needed.

**Comment by PatrickRyanMS** [comment]
I agree with you, @CedricGuillemet, there are DCC solutions that can use this technique so building a tool for it here would probably not be the best return on investment.
