### ISSUE TITLE
SceneLoader.ImportAnimations doesn't work in all cases

### ISSUE THREAD

**Issue by phenry20** [BabylonJS/Babylon.js#7931]
In the following PG: https://www.babylonjs-playground.com/#KM2N07#15
You will see that the imported animation only moves part of the arm when it should be moving the entire body. This is due to the fact that the default targetConverter targets the wrong Nodes when multiple types of nodes have the same name. 

I've written some code to get it working on my side (https://www.babylonjs-playground.com/#KM2N07#17)

Essentially the targetConverter needs a way to know what type the target is so that it can make the correct mapping instead of guessing by name. I've made an attempt to do that, but I don't know if this is the correct way to fix this issue that's why I haven't created a ~MR~ PR for it yet.

Please let me know if I'm on the right track and whether I should create a ~MR~ PR or not. If I'm not on the right track can you please steer me in the right direction so that a proper fix can be implemented?

Thanks.

**Comment by deltakosh** [comment]
I like your fix! definitely the right track!

Please send a PR when you want and thanks a ton for your help!

**Comment by phenry20** [comment]
Great! I hope to have a PR by end of day or early tomorrow

**Comment by phenry20** [comment]
#7936 https://github.com/BabylonJS/Babylon.js/pull/7936
