### ISSUE TITLE
NME - custom mesh does not appear in primitive drop down

### ISSUE THREAD

**Issue by PatrickRyanMS** [BabylonJS/Babylon.js#7943]
## Bug
When loading a custom mesh in the NME preview window, it does not appear as an option in the drop down list of primitives. If I then select a different primitive, I have no way to get back to the mesh I loaded. And if I try to load a custom mesh again and choose the last one I loaded, nothing happens and I remain on whatever primitive had been selected before choosing load mesh.

If I load a different custom mesh, and then load the one I first loaded, I am able to see my original mesh again. This UX should be avoided because it's not intuitive. Best case solution would be to add an option in the drop down that points to the loaded mesh if we retain the mesh in memory. If not, the option to load mesh should work on subsequent loads of the same mesh, though this UX is sub-optimal because it requires more input steps to retrieve your custom mesh.

**Comment by belfortk** [comment]
@PatrickRyanMS , yep there is a small bug that is preventing you from reloading. I have a quick fix for that on [branch](https://github.com/belfortk/Babylon.js/commit/6264f11975bec835378bb4f939940d99bf6acf7d) I can PR. This would implement the sub-optimal solution

@deltakosh , I think previewMeshControlComponent and the GlobalState class are set up to support just one custom mesh at a time. My (hazy) understanding is that it would take some non-trivial work to add support for multiple custom meshes in memory. I am happy to try and tackle this but I wanted to check to see if this is a higher priority than my Frame Port work. And if my understanding is incorrect, please let me know!

**Comment by PatrickRyanMS** [comment]
@belfortk, thanks for jumping on this. I don't think it's necessary to enable multiple custom meshes, but if we could add the custom mesh loaded to the drop down list so that I could switch from the custom mesh to the cube and back to the custom mesh would be super helpful. If I loaded another mesh, replacing the one in memory should be fine so we don't have to get into naming meshes in case someone decides to add multiples and want to know which they are choosing.

**Comment by deltakosh** [comment]
Agree with @PatrickRyanMS, only one custom mesh is fine but we need to be able to switch it :)

AS this is a bug, it is high pri

**Comment by belfortk** [comment]
Ah ok, that seems simpler than what I was imagining. Thanks for clearing up my confusion! I'll get right on it.
