### ISSUE TITLE
scrollviewer and grid size interaction

### ISSUE THREAD

**Issue by lockphase** [BabylonJS/Babylon.js#7951]
From https://forum.babylonjs.com/t/scrollviewer-and-grid-size-interaction/9534

- Bug repro on PG: https://www.babylonjs-playground.com/#4ZC0G4#8

Steps:

1. Click on blue ‘click me’ button once. You should see some numbers on each row that is not 50.
2. Click on blue ‘click me’ button again. You should see some numbers on each row that is 50.
3. scroll to the very bottom. Click on blue ‘click me’ button again. The scroll viewer window goes grey.
4. Now you can click on blue ‘click me’ button again and again, the scroll viewer window remains grey and the grid does not show until you scroll up a little.

Expected result: At step 3, the sv window should resize to new grid height.

Pls note, I have not tested the horizontal adjustable columns in grid vs horizontal scroll bar in sv. Thanks!

**Comment by deltakosh** [comment]
Fancy doing a PR? or maybe @BabylonJSGuide  ?

**Comment by lockphase** [comment]
Thank you very much, Tested, fix works!
