### ISSUE TITLE
"unbounded" space should be recommended for "immersive-ar" sessions

### ISSUE THREAD

**Issue by thetuvix** [BabylonJS/Babylon.js#7959]
Right now, Babylon.js is discouraging use of the `"unbounded"` reference space in `"immersive-ar"` sessions.  While the unbounded space will be most useful across AR phones/tablets and AR headsets once the anchors module has shipped, it is already useful on devices like HoloLens 2, as it's the only space that enables tagalong content to continue rendering when the user walks through an untracked hallway into a new room.

https://github.com/BabylonJS/Babylon.js/blob/cab0386275b2de037e192f715489cd3f2654e35e/src/XR/webXRExperienceHelper.ts#L105

**Comment by RaananW** [comment]
Thanks! Will change that very soon
