### ISSUE TITLE
NME: textures inverted in PG when live editing

### ISSUE THREAD

**Issue by Popov72** [BabylonJS/Babylon.js#8021]
When updating a texture in a texture block in the NME, the corresponding texture in the PG linked to the node material is inverted.

It happens only when live editing: if the node material is saved with the update texture and reloaded in the PG, the texture is ok.

**Comment by Popov72** [comment]
https://playground.babylonjs.com/#5UWULF#1

Given my testing, there's a timing/race condition problem somewhere, so you don't always have the same result...

To be clear, here's the right setup:
![image](https://user-images.githubusercontent.com/4152247/79276038-930d9300-7ea7-11ea-8651-9dd8cc194441.png)

And the bad one:
![image](https://user-images.githubusercontent.com/4152247/79276087-a9b3ea00-7ea7-11ea-8d78-7c5819675f6e.png)

* when launching the PG, you may see the right sphere (the one with the node material) with y-inverted texture compared to the left sphere (reference) or not. If you click several times/quickly on the "play" button, you should succeed to see inverted texture at some time => it always happens for me when I make a double click on the play button (meaning 2 quick clicks)
* Assuming the textures are not inverted:
  * edit the material in the node editor
  * remove the texture and reload it (rock.png)
  * the texture is now inverted in the PG for the right sphere
*  Comment line 9 `//new BABYLON.CubeTexture("textures/country.env", scene0);`
  * Assuming you start the PG with non inverted texture (you still can get inverted texture in this setup), even by doing the steps explained above (edit material, remove/upload texture), the texture will remain ok in the PG
* you can try to set `fromSnippet=false`
  * instead of loading the material from the snippet server, it will parse a jsonized material embedded  in the PG
  * in this setup it is much more difficult to get inverted texture at start (but still possible)
  * assuming you start the PG with non inverted texture, when doing the steps explained above (edit material, remove/upload texture), the texture will be inverted in the PG EXCEPT if you comment line 9 (so same thing as above)

Note: my PG uses two cameras in a single scene, one to show the first sphere and the other to show the second one (it may or may not be important, but as it is not usual I prefer making it clear in case it plays a part in the problem).

Late note: One time I had been able to see this:
![image](https://user-images.githubusercontent.com/4152247/79276356-221aab00-7ea8-11ea-97a4-0b2f38a9ce7b.png)
!

**Comment by Popov72** [comment]
Ah, I forgot to say, to add to the confusion:
* if the texture is `country.dds` instead of `country.env`, if you start with the right configuration, even if editing the material, removing/reuploading the texture you will get the right non-inverted texture in the PG (contrary to what happens when the texture is `country.env`)...

**Comment by deltakosh** [comment]
Well in my case in the local index test file, it is ALWAYS inverted which is expected has NME is setting invertY to false by default

So your good one is actually the expected one

You need to load the texture with invertY set to false for your albedo to mimick what NME is doing

**Comment by deltakosh** [comment]
https://playground.babylonjs.com/#5UWULF#2

So the question is more: why sometimes do you see the NME texture inverted. I'm trying to repro but with no success so far

**Comment by deltakosh** [comment]
On your repro, the main texture is not attach to the scene0 but to the scene object hence the problem :)

Fixed here: https://playground.babylonjs.com/#5UWULF#4

**Comment by Popov72** [comment]
Ah, stupid me, thanks!

Note however I have been able to see this configuration even with the change:
![image](https://user-images.githubusercontent.com/4152247/79281410-f224d500-7eb2-11ea-989c-741738419601.png)

which should not have happened (I must say it happened only a single time during my multiple refreshes, so maybe it is due to PG crazy refreshing instead).

**Comment by deltakosh** [comment]
Let's wait if we can get a more stable repo and we will reopen this issue then ;)
