### ISSUE TITLE
Inspector: Add detail window for texture preview

### ISSUE THREAD

**Issue by PatrickRyanMS** [BabylonJS/Babylon.js#8022]
## Feature Request
When debugging textures, it's hard to discern what is in each channel from only the small texture preview in the inspector. It would be very helpful to be able to "zoom in" to the texture by either clicking on the texture preview or adding a "full size" button to the UI which opens a child window of the image at full resolution or at 100% of the monitor (whichever is smaller). The child window should still have the R G B A ALL buttons at the top, but I think we can leave the other functionality to load a texture to the inspector as this is solely to debug what the texture looks like or if there are problems with any of the channels.

**Comment by deltakosh** [comment]
Done!
