### ISSUE TITLE
Implement Draco-compressed GLB export option in Sandbox' Inspector

### ISSUE THREAD

**Issue by vortice3D** [BabylonJS/Babylon.js#8046]
Hi everybody:
 
As stated in [this forum discussion](https://forum.babylonjs.com/t/sandbox-glb-exporter-question/9856/9), I think that being able to export from BJS Sandbox to a Draco compressed GLB would be a nice feature to have.

Best regards.

**Comment by bghgary** [comment]
@pandaGaume This is a serializer feature request that you might be able to tackle.

**Comment by saidmoya12** [comment]
You can compress after export with gltf-pipeline

`
gltf-pipeline -i model.glb -o model.glb -d
`

[https://github.com/CesiumGS/gltf-pipeline](https://github.com/CesiumGS/gltf-pipeline)

**Comment by mathus1** [comment]
Do you have an estimate of when this feature will be implemented?

**Comment by sebavan** [comment]
cc @bghgary

**Comment by bghgary** [comment]
Once https://github.com/BabylonJS/Babylon.js/issues/12600 is implemented, this should be easy.

**Comment by deltakosh** [comment]
https://forum.babylonjs.com/t/implement-draco-compressed-glb-export-option-in-sandbox-inspector/52129
