### ISSUE TITLE
Bug/inconsistency in constructor and updateOptions method of Sound

### ISSUE THREAD

**Issue by randle-mcmurphy** [BabylonJS/Babylon.js#8058]
The `offset` and `length` properties of `ISoundOptions` are handled differently in `constructor` and `updateOptions` method of `Sound`.

**In constructor:**
> this._length = options.length;
> this._offset = options.offset;

**In updateOptions method:**
> this._length = options.length ? options.length / 1000 : undefined;
> this._offset = options.offset ? options.offset / 1000 : undefined;

So we need to multiply offset and length values by 1000 when using `updateOptions`, to make sure we get the expected result.

**Playground:**
https://www.babylonjs-playground.com/#6LXPBX#8

**Comment by deltakosh** [comment]
Do you want to submit a PR?

**Comment by deltakosh** [comment]
Also clsoing as discussion must happen on the forum
