### ISSUE TITLE
Sandbox exporter to support preserving embed jpg format of a loaded .glb

### ISSUE THREAD

**Issue by shaderbytes** [BabylonJS/Babylon.js#8090]
# Feature request

https://forum.babylonjs.com/t/sandbox-only-export-the-imported-object/10423

While wanting to add a texture to an imported model in the sandbox , on export I found the original glb which is ~600k became ~4mb.

In the forum discussion it was established this is probably due to babylon only exporting .png files within the .glb but the source .glb had .jpg images in it. 

Here is the original .glb used to test :

https://www.shaderbytes.co.za/clients/five_star_bath_solutions/assets/glb/basket.glb

Suggestions were to possibly preserve this on export or add options to export JPEGs when possible.

**Comment by deltakosh** [comment]
Hey I've got a 404 on the glb. Can you share it again?

**Comment by shaderbytes** [comment]
sorry about that .. I deleted it when making space on my rented shared host space .. i have put it back now again. Although I think I might have added an AO texture via blender nodes ( which was the goal I wanted to achieve with the sandbox when I discovered the issue ) but the textures are all .jpg so it should still be fine to test your export adjustments

**Comment by deltakosh** [comment]
Ok thanks. please keep it alive a bit while we work on it ;D
