### ISSUE TITLE
[Improve] Bloom bright extraction

### ISSUE THREAD

**Issue by jcyuan** [BabylonJS/Babylon.js#8098]
from the source code in `extractHighlights.fx`:

https://github.com/BabylonJS/Babylon.js/blob/ae19ec8facd1ceec0b449a31fd1f8d2415d757ce/src/Shaders/extractHighlights.fragment.fx#L12-L13

`step` only returns 0 / 1, so the result you will get is kind of toon rendering:
![GIF1](https://user-images.githubusercontent.com/850854/80853969-27794300-8c67-11ea-98a1-a747c1761b42.gif)

test code for this image result (BBL version):

    const float uThreshold = 1.;
    const float uExposure = 1.;
    const vec3 LuminanceEncodeApprox = vec3(0.2126, 0.7152, 0.0722);
    vec3 extractBright1(const in vec3 color) {
        float lum = clamp(dot(color * uExposure, LuminanceEncodeApprox), 0., 1.);
        return step(uThreshold, lum) * color;
    }

and actually this result can be improved like this:
![GIF2](https://user-images.githubusercontent.com/850854/80854008-6e673880-8c67-11ea-8406-c2033368744a.gif)

test code for this new result:

    const float uThreshold = 1.;
    const float uExposure = 1.;
    const vec3 LuminanceEncodeApprox = vec3(0.2126, 0.7152, 0.0722);
    vec3 extractBright2(const in vec3 color) {
        float lum = dot(color * uExposure, LuminanceEncodeApprox);
        return clamp(color * clamp(lum - uThreshold, 0.0, 1.0), 0.0, 1.0);
    }

i set the `uThreshold` as `1.` because normally only the color which exceeds from `1.` will glow, especially for HDR. (in BBL default 0.9)

**Comment by sebavan** [comment]
I guess it is normally not a big issue as it goes through several passes of blur after extraction but would you be willing to create a PR and add a special mode for it ?

So the bloom could have a "softer" flag for this one preventing any back coompat issues ?

**Comment by deltakosh** [comment]
Closing as we want tech discussion to happen on the forum (for discoverability reasons)
