### ISSUE TITLE
Particle Editor - Emission rate velocity gradiant not working with snippet server

### ISSUE THREAD

**Issue by thomlucc** [BabylonJS/Babylon.js#8107]
- Bug repro on [playground](https://playground.babylonjs.com/#CHTCF7#2):
- Expected result: should display particles
![image.png](https://images.zenhubusercontent.com/5dae4b4d14fb1000015c0e1e/812d0486-78e0-492a-b467-21cb3ef8f569)
- Current result: Nothing (Particle System isn't starting)
- Repro:
1. From [basic particle playground loading from snippet server](https://playground.babylonjs.com/#CHTCF7#1)
2. add a Velocity Gradiant for the rate:
![image.png](https://images.zenhubusercontent.com/5dae4b4d14fb1000015c0e1e/75f1a942-4d76-4857-9b60-898e516bbfed)
![image.png](https://images.zenhubusercontent.com/5dae4b4d14fb1000015c0e1e/faf04e15-e226-4855-b879-fb8eb597aec7)
3. Save to snippet server
4. Save updated playground with new snippet ID
5. The new [playground ](https://playground.babylonjs.com/#CHTCF7#2) doesn't display anything (the particle system cannot start)
6. If I remove the velocity gradiant, then it works again (I can start the Particle system and save to snippet works).

**Comment by deltakosh** [comment]
not a bug :) The EmitRate gradients require a targetStopDuration:
https://doc.babylonjs.com/babylon101/particles#emit-rate-over-time
