### ISSUE TITLE
Particle Editor - Transparency cursor not moving and displayed value not changing

### ISSUE THREAD

**Issue by thomlucc** [BabylonJS/Babylon.js#8108]
# Bugs

- Bug repro on [Playground](https://playground.babylonjs.com/#A42FPU#2)
- Expected result:
Transparency value and Cursor should be at 10% 
- Current result: 
Transparency displayed value remains displayed at 100% and cursor doesn't move 

- Repro
1. On [Playground](https://playground.babylonjs.com/#A42FPU#2)
2. Click on the turquoise color of the color gradiant of the Smoke Particle System
![image.png](https://images.zenhubusercontent.com/5dae4b4d14fb1000015c0e1e/381eff1f-56bc-4bce-8032-8af2601b462b)
3. Enter "10" for A
![image.png](https://images.zenhubusercontent.com/5dae4b4d14fb1000015c0e1e/67038eab-2b8f-40d6-b792-86295aaeb62d)
4. The color transparency changes effectively (see rendering and color)
![image.png](https://images.zenhubusercontent.com/5dae4b4d14fb1000015c0e1e/d0065f54-9f1c-45bd-bbfa-cc3b13766210)
5. But the cursor is still at 100% and A displayed value is = "100%"
![image.png](https://images.zenhubusercontent.com/5dae4b4d14fb1000015c0e1e/efc71366-4f4a-4405-b7d0-0fc84d6263dc)

**Comment by deltakosh** [comment]
On it

**Comment by thomlucc** [comment]
Rested and Confirmed that it is now fixed! Thanks.
![image](https://user-images.githubusercontent.com/32072891/81228725-6c70e280-8fa3-11ea-8476-516e08947013.png)
