### ISSUE TITLE
Iphone VR and Oculus Quest VR doesn't work when exported with Unity3D exporter

### ISSUE THREAD

**Issue by EngKareemHesham** [BabylonJS/Babylon.js#8127]
Good morning everyone,
I tried building the unity exporter demo ( https://github.com/BabylonJS/UnityExporter/tree/master/Redist ).
Just added a camera rig to a new empty unity project, enabled experience helper and built it.

# Screen shots of the process
![Screenshot (12)](https://user-images.githubusercontent.com/34426650/81397847-69532f00-9128-11ea-973d-cd730890ad80.png)
![Screenshot (16)](https://user-images.githubusercontent.com/34426650/81397942-943d8300-9128-11ea-9a51-ed9c7b89f223.png)

# Bugs

- Bug repro on [github page]( https://engkareemhesham.github.io/webvr13/ )
- Expected result: VR opens and it rotates when you rotate your head
- Current result: VR opens but doesn't rotate with your head
-reproduced on : Iphone and Oculus quest
-VR works with no issues on : Pc(using a mouse) ,Android and Gear VR

**Comment by deltakosh** [comment]
Hello this is not the right repo :)
Can you please post it here: https://github.com/BabylonJS/UnityExporter
