### ISSUE TITLE
Input System - Next steps

### ISSUE THREAD

**Issue by PolygonalSun** [BabylonJS/Babylon.js#8147]
- [x] Wire up to existing Input Manager
- [ ] ~~Wire up to existing Gamepad Manager~~

Note: Gamepad Manager will be pulled out into different issue.

**Comment by thomlucc** [comment]
Separated Input Profile System in #8912 for Future Release

**Comment by PolygonalSun** [comment]
InputManager wired up with PR https://github.com/BabylonJS/Babylon.js/pull/9789

**Comment by PolygonalSun** [comment]
GamepadManager Issue: https://github.com/BabylonJS/Babylon.js/issues/9795
