### ISSUE TITLE
Incorrect rendering using EXT_mesh_gpu_instancing

### ISSUE THREAD

**Issue by zeux** [BabylonJS/Babylon.js#8149]
The attached scene has a variant of SimpleMeshes from glTF-Sample-Models converted with instancing support using gltfpack.

Bear in mind that support for instancing in gltfpack is experimental, but it seems like this is hitting some bugs in Babylon.JS loader.

The two variants of the model are:
- simplemeshes_noq.glb - encoded using raw floating point attributes
- simplemeshes.glb - encoded using KHR_mesh_quantization (each instance embeds a dequant matrix with the scale 1/16383)

When I open these files in the sanbox, they both look incorrect:

- `simplemeshes_noq.glb` shows three triangles, rendering the base mesh in addition to instanced data. My understanding is that the middle triangle should not be rendered here.

![image](https://user-images.githubusercontent.com/1106629/81652098-0c859c00-93e8-11ea-9d61-02132d0f27b5.png)

- `simplemeshes.glb` shows just one triangle - it looks like it's the triangle for the base mesh. I'm not quite sure what happened to the instanced triangles here.

![image](https://user-images.githubusercontent.com/1106629/81651663-b0227c80-93e7-11ea-8dff-6af25caa13ba.png)

[instancing.zip](https://github.com/BabylonJS/Babylon.js/files/4614025/instancing.zip)

**Comment by bghgary** [comment]
> simplemeshes_noq.glb shows three triangles, rendering the base mesh in addition to instanced data. My understanding is that the middle triangle should not be rendered here.

This isn't super clear in the extension spec, but I agree the source mesh shouldn't show. I've fixed this in #8156.

> simplemeshes.glb shows just one triangle - it looks like it's the triangle for the base mesh. I'm not quite sure what happened to the instanced triangles here.

I don't see anything wrong with the code here. It looks like the data in the glb may be wrong? The scale is super tiny 0.00006 and the positions are suspicious. Are the positions supposed to be normalized perhaps?

**Comment by bghgary** [comment]
The PR fixes both problems now. Thanks for the report!

**Comment by zeux** [comment]
> EDIT2: Never mind. This is because the camera is taking the source mesh into account. I'll see if I can fix it.

Ah, right, and there's no dequant matrix in the node so it's super big. Makes sense, thanks for the fixes!
