### ISSUE TITLE
Suboptimal performance with EXT_mesh_gpu_instancing

### ISSUE THREAD

**Issue by zeux** [BabylonJS/Babylon.js#8164]
I've been testing instancing using models provided in https://github.com/KhronosGroup/glTF/issues/1699; attached is the ice stadium model encoded using EXT_mesh_gpu_instancing.

[stadium.glb.zip](https://github.com/BabylonJS/Babylon.js/files/4619618/stadium.glb.zip)

After conversion this scene has 583 nodes with a total of 610 mesh primitives, but many of these are instanced; the cumulative instance count is around 27K.

three.js has an open PR for support of this extension; using that, it takes ~140ms to fully deserialize the file including mesh parsing etc., and ~3ms each frame to submit draw commands to the GPU, with scene looking a bit like this

![image](https://user-images.githubusercontent.com/1106629/81767262-cd5d5680-948c-11ea-94ab-e17188a383a6.png)

In comparison, Babylon.JS takes ~16 seconds (~114x longer) to deserialize the file, and ~55ms (~18x longer) to render each frame on the CPU. The GPU cost looks comparable, maybe better on Babylon side.

Here's a breakdown of loading process, with a separate section for createDefaultCamera (it seems to run into some sort of N^2 behavior?), and a few other expensive bits:

![image](https://user-images.githubusercontent.com/1106629/81767861-4e691d80-948e-11ea-866a-4a4b0461f057.png)

![image](https://user-images.githubusercontent.com/1106629/81767948-8708f700-948e-11ea-8d9a-3c827eb31829.png)

Here's a breakdown of a single render frame:

![image](https://user-images.githubusercontent.com/1106629/81767734-01854700-948e-11ea-911b-d7ba4c28fa9c.png)

The most severe issues here are the problem with `createDefaultCamera` and the render frame performance. I'm wondering if Babylon.JS provides a more efficient way to represent instanced draws? Right now it looks like the loader just creates a node per mesh, and presumably then relies on auto-instancing functionality to dispatch draw calls more efficiently, but it looks like the scene graph checks are not very fast here.

**Comment by deltakosh** [comment]
Thanks a lot! We are currently working on improving (drastically) the situation. We will report here asap

**Comment by Popov72** [comment]
Fixed by #8208 and #8209.
