### ISSUE TITLE
mesh.position not available in particle fragment shaders

### ISSUE THREAD

**Issue by cpaul747** [BabylonJS/Babylon.js#8186]
# Feature request

- Forum Link: https://forum.babylonjs.com/t/particle-vertex-shader-screen-or-view-position/10860
- NME particle shaders allow you to select mesh.position as an input Vector, but it is assigned no value so it can not be used.  Additionally, documentation suggests you can only override the fragment shader for a particle, making it impossible to pass it in yourself.
- Additional links that could help implementing the feature: NME particle shader example - https://nme.babylonjs.com/#E33CC8

**Comment by deltakosh** [comment]
Thanks!!

**Comment by sebavan** [comment]
@Popov72 same here, I do not remember if you added this one already ?

**Comment by Popov72** [comment]
No, currently working on it.

**Comment by sebavan** [comment]
thanks :-)
