### ISSUE TITLE
Add a LoadFromFileAsync to Sprite

### ISSUE THREAD

**Issue by deltakosh** [BabylonJS/Babylon.js#8190]

**Comment by sebavan** [comment]
Are sure we need LoadFfomFileAsync ? I think you meant LoadFoamFileAsync  :-)  

![image](https://user-images.githubusercontent.com/16655165/81993158-68992c00-9645-11ea-964a-88d5fa84cf77.png)

**Comment by deltakosh** [comment]
LOOOL
