### ISSUE TITLE
NME: Long comments on collapsed frames breaks port alignment

### ISSUE THREAD

**Issue by PatrickRyanMS** [BabylonJS/Babylon.js#8193]
## Bug

If we ad a comment to a frame that is longer than the collapsed frame width allows, the wrapping of the comment will shift the port label and icon down so that it no longer aligns with wires coming from the frame. 

There are two obvious solutions here and one that is more complicated and may not be desirable due to the complexity. 

- Solution 1: When frames are collapsed we hide the comment due to the limited space within the collapsed frame for comments.
- Solution 2: We prevent comments in a collapsed frame from wrapping and hide overflow text. This does preserve the fact that there is a comment, but the minimal usable space on the collapsed frame will likely make the comment unusable if much of it is hidden.
- Solution 3 (the more complex solution): When a frame is open, we keep the comments in the frame so the comment is obviously part of the frame. However when we collapse the frame we shift the comment to the outside of the frame so that it mirrors how other comments appear on the standard nodes. 

Obviously the third option preserves the utility of the comment feature, but the complexity of the solve may make this undesirable to maintain. In that case, I would likely choose the first option of only showing the comment when the frame is expanded because hiding overflow text will likely make the comment unusable if the length is more than a few words. 

![image](https://user-images.githubusercontent.com/31326855/82030093-d09f4080-964c-11ea-8a05-fe94adb4b8f9.png)

**Comment by deltakosh** [comment]
I vote for solution 2: adding the ellipsis like in other portion of NME or the inspector.

User can still read the comment by clicking the frame and looking at the property grid
