### ISSUE TITLE
OBJ file importer problems

### ISSUE THREAD

**Issue by JohnGrime** [BabylonJS/Babylon.js#8196]
I think there's a problem with the .obj file importer.

If I drag'n'drop an example ".obj" file (in zipfile, attached) into the sandbox I get the wrong result (see "obj.png"), but if I try the same data in ".stl" format (in attached zipfile) I get the right result (see "stl.png").

The zipfile also contains the Blender file I used to export the .obj and .stl files, in case anyone is interested.

I tested the .obj and .stl files in MeshLab, and Meshlab imports both correctly.

[obj_test.zip](https://github.com/BabylonJS/Babylon.js/files/4635788/obj_test.zip)

<img width="494" alt="stl" src="https://user-images.githubusercontent.com/4098291/82075484-ef7bf200-96a1-11ea-896a-db5189534d2a.png">
<img width="491" alt="obj" src="https://user-images.githubusercontent.com/4098291/82075485-f0ad1f00-96a1-11ea-8bfd-d655f320e3a0.png">

**Comment by deltakosh** [comment]
Hello as stated in the template please first discuss the problem on our Forum :)
