### ISSUE TITLE
textWrapping not working on Asian languages (Japanese & Chinese)

### ISSUE THREAD

**Issue by thomlucc** [BabylonJS/Babylon.js#8211]
From [Forum post](https://forum.babylonjs.com/t/textwrapping-not-working-on-asian-languages-japanese-chinese/10902)

GUI TextBlock textWrapping is not working on Asian languages. I’ve tried Japanese and Chinese.

The PG I saved is all ? marks.
https://www.babylonjs-playground.com/#XCPP9Y#2555 7

But you can simply copy+paste the text below and replace line 33.
var text = “<copy+paste here>”

Japanese text:
バビロンは、紀元前18～6世紀の古代メソポタミア地域における主要な王国だった。その名をとどろかせる首都が、ユーフラテス川沿いに建設された。都市は、川をまたいでその両岸に、ほぼ同じ面積で建設され、時に襲う季節的な洪水を防ぐため、川沿いには険しい堤防が築かれた。元々は、バビロンはアッカドの小さな町で、その起源は紀元前2300年頃のアッカド帝国にまでさかのぼる。

Chinese text:
巴比伦城市遗址在今天伊拉克巴比伦省的希拉被发现，位于巴格达以南约八十五公里处。这个举世闻名城市的遗址地处底格里斯河和幼发拉底河之间肥沃的美索不达米亚平原上，现在仅留存着由破损的土砖建筑物构成的大型土墩和碎片。城市沿着幼发拉底河建造，被左、右河岸平分成两部分，配有陡峭的河堤来抵御季节性的洪水。

**Comment by sebavan** [comment]
@Popov72 I guess this one can be closed now ?

**Comment by sebavan** [comment]
https://jsfiddle.net/3ph9m0cx/
