### ISSUE TITLE
Asian characters not handled in PG

### ISSUE THREAD

**Issue by Popov72** [BabylonJS/Babylon.js#8221]
Create a PG with only:
```
var joshi = "でなければ|";
```
Then save the PG (I have done this in: https://playground.babylonjs.com/#MEH9C5)

You will get an error (expected because it's not a valid PG), and the japanese characters will be lost, all replaced by "?".

It must be a problem on server side, because I checked that the string built on client side and send to the snippet server is ok.

So, either it's a problem at the receiving / saving stage, or when retrieving the snippet.

**Comment by deltakosh** [comment]
let me check that

**Comment by deltakosh** [comment]
Ok this is because the SQL Server database we used has the payload field set to text (instead of ntext) but I cannot change the type as the column is enabled forfull text search so closing as "won't fix"

Maybe we can use a jsfiddle here instead of the PG?

**Comment by Popov72** [comment]
Ok, going to do that.
