### ISSUE TITLE
OnObserverAdded observable in the observable class

### ISSUE THREAD

**Issue by RaananW** [BabylonJS/Babylon.js#8229]
I suggest adding an "onObserverAddedObservable" observable to the observable class, that will allow us to call the added callback immediately if the right conditions are met. 

For example - 

The onMotionControllerInitObservable of the xr input source is triggered when the motion controller was initialized. But any callback added afterwards will never be triggered.

My suggestion is this - allow the creator of every observable to trigger added callbacks if conditions are met. In this case, I would expect the onMotionControllerInitObservable to also have this:

```
onMotionControllerInitObservable.onObserverAddedObservable.add((observer) => {
    if(motionController) { 
        onMotionControllerInitObservable.notifyObserver(observer, motionController); 
    }
});
```
This way we are sure the function will be executed.

Alternatively we could have added this to the `add` function with a `conditions met` predicate, but that would take the responsibility away from the obersvable. Something like this:

```
onMotionControllerInitObservable.add(() => { myWonderfulCallback(); }, whateverVariables, () => controller.motionController);
```

The last function is a predicate that we can call `executeIfMet`. If this function returns true, the observer should be notified right after being registered. This is a simple change to the observable add function. but it makes the function bigger than it already is and changes the public signature.

**Comment by deltakosh** [comment]
Like it!

**Comment by deltakosh** [comment]
Well actually you don';t need that :)
you can add a callback to the constructor:https://github.com/BabylonJS/Babylon.js/blob/master/src/Misc/observable.ts#L184

**Comment by RaananW** [comment]
hmm.. how did I miss that :-)
