### ISSUE TITLE
Camera's view isn't persisted if rotationQuaternion is animated

### ISSUE THREAD

**Issue by nbduke** [BabylonJS/Babylon.js#8250]
# Bugs
Repro playground: https://www.babylonjs-playground.com/#CGUX9W

Once you load the above playground, the camera will animate to look at a cube in the scene. After the animation finishes, try to pan the camera. It will snap back to its initial view instead of smoothly panning near where you just animated it.

This feels like a bug. I'd expect animations to correctly persist the camera's view.

**Comment by sebavan** [comment]
Definitely a bug !!! good catch, I ll have a look shortly, worst case you ll have it by end of day monday.
