### ISSUE TITLE
NME - copy/paste action on frame creates many duplicates of internal nodes

### ISSUE THREAD

**Issue by PatrickRyanMS** [BabylonJS/Babylon.js#8286]
## Bug
When a selected frame is copied and pasted, rather than copying and pasting the frame and contents, many duplicates of the contents of the frame are pasted into the graph. These are pasted right on top of the original frame nodes which is another problem as it is hard to untangle the mess that is created since we have no undo stack. 

Ideally, we would be able to copy and paste a frame as we would any other node. If that isn't possible, we should just paste one copy of the contents of the frame, but we should not paste them down within the bounds of the original frame. it appears a frame is pasted down with the new nodes in the example below, but I didn't witness this consistently happening. 

original frame
![image](https://user-images.githubusercontent.com/31326855/83344410-798ba380-a2bb-11ea-939f-64432150a1d5.png)

frame selected, copied, and pasted
![image](https://user-images.githubusercontent.com/31326855/83344416-8d370a00-a2bb-11ea-81cf-ac448d848373.png)

**Comment by deltakosh** [comment]
cc @sebavan fyi. We need to tackle this one asap. Please let me know if you want me to tackle it

**Comment by sebavan** [comment]
@PatrickRyanMS I unfortunately can not seem to be able to repro:

![image](https://user-images.githubusercontent.com/16655165/83360284-6e4e7b80-a380-11ea-80f7-f19b414be254.png)

Would you have detailed steps for the repro ?

**Comment by sebavan** [comment]
Ok figured it out fixed by #8289
