### ISSUE TITLE
NME - copy/paste action does not select newly pasted node

### ISSUE THREAD

**Issue by PatrickRyanMS** [BabylonJS/Babylon.js#8287]
##Bug
When a selected node is copied, the resulting pasted node is not selected, but rather the original node that was copied remains selected. This becomes problematic when you copy several nodes at once. We paste the chain down sometimes over other nodes that are already in the graph that were not part of the originally selected nodes. In this case it is important that we keep the newly pasted nodes selected so we can easily move those nodes to a free space in the graph.

original nodes selected to be copied:
![image](https://user-images.githubusercontent.com/31326855/83344562-4e09b880-a2bd-11ea-8bec-5dd2a5a1895c.png)

pasted nodes:
![image](https://user-images.githubusercontent.com/31326855/83344534-e2bfe680-a2bc-11ea-8f3d-b51e82564ca7.png)

**Comment by deltakosh** [comment]
I'll take care of it
