### ISSUE TITLE
NME - preview mesh flashes visibility when changing values in graph

### ISSUE THREAD

**Issue by PatrickRyanMS** [BabylonJS/Babylon.js#8290]
## Bug
This is a behavior I have not noticed before but can't pinpoint when it may have started but it is very obvious right now. When changing the value of a node in the shader using a slider or code, the sample mesh in the preview window of the NME graph flashes visibility with each change. This obviously isn't normal behavior and makes the experience feel buggy, even if it's not effecting the outcome of the rendered material. The mesh disappearing for a moment like that can cause an apprehension about the underlying shader code in the user and make them question if the tool works correctly.

The preview window in NME is the only place the flashing happens as any mesh using the material in your scene does not suffer from the same issue so this is tied to the preview window. I have attached a sample video showing the behavior and the shader used to repro this issue. Note that this isn't the shader I was working on when I noticed the issue, but is a much simpler shader in general that I have used in one of our recent videos so I know it was working at least at that point. But I can repro it across several shaders after a cache dump and restart of Edge.

[nmeFlashBug.zip](https://github.com/BabylonJS/Babylon.js/files/4708578/nmeFlashBug.zip)

**Comment by Popov72** [comment]
I think:
```typescript
if (this._storeEffectOnSubMeshes) {
    if (tempSubMesh._materialDefines) {
        tempSubMesh._materialDefines._renderId = -1;
    }
    if (!this.isReadyForSubMesh(mesh, tempSubMesh, localOptions.useInstances)) {
        if (tempSubMesh.effect && tempSubMesh.effect.getCompilationError() && tempSubMesh.effect.allFallbacksProcessed()) {
            lastError = tempSubMesh.effect.getCompilationError();
        } else {
            allDone = false;
            setTimeout(checkReady, 16);
        }
    }
} else {
    tempSubMesh._renderId = -1;
    if (!this.isReady(mesh, localOptions.useInstances)) {
        if (this.getEffect() && this.getEffect()!.getCompilationError() && this.getEffect()!.allFallbacksProcessed()) {
            lastError = this.getEffect()!.getCompilationError();
        } else {
            allDone = false;
            setTimeout(checkReady, 16);
        }
    }
}
```
can be reduced to:
```typescript
if (!this.isReadyForSubMesh(mesh, tempSubMesh, localOptions.useInstances)) {
    if (tempSubMesh.effect && tempSubMesh.effect.getCompilationError() && tempSubMesh.effect.allFallbacksProcessed()) {
        lastError = tempSubMesh.effect.getCompilationError();
    } else {
        allDone = false;
        setTimeout(checkReady, 16);
    }
}
```
as there's already a `if (this._storeEffectOnSubMeshes) {` up in the hierarchy, and `tempSubMesh` being just created, `tempSubMesh._materialDefines = null`.

I think it would make the code clearer.

**Comment by deltakosh** [comment]
oh right that's code I missed! thanks!
