### ISSUE TITLE
Vector3 accessors is a breaking change for serialization

### ISSUE THREAD

**Issue by nbduke** [BabylonJS/Babylon.js#8363]
# Bugs
[This PR](https://github.com/BabylonJS/Babylon.js/pull/8314) has broken several scenarios for my team, specifically in places where we serialize a `Vector3` as a struct like `{x, y, z}`. The problem is TypeScript's implicit unpacking/stringifying of objects; it only grabs the data members, not accessors/methods.

We can of course fix our code by either changing the serialized data representation to `{_x, _y, _z}` or explicitly (rather than implicitly) stringifying a `Vector3`. However, as this constitutes a breaking change, we wonder if it's something that could wait until the next major version.

**Comment by deltakosh** [comment]
Well we do not consider it a breaking change as the class features and public accessors are not changed.
Furthermore this brings a really important speed optimization for complex scenes as we can improve the caching mechanism

I would recommend using vector3.asArray and FromArray for serialization purpose

**Comment by nbduke** [comment]
That's fair. We will fix it on our end.
