### ISSUE TITLE
Sandbox: toggle footer removes footer buttons

### ISSUE THREAD

**Issue by LenaTevar** [BabylonJS/Babylon.js#8366]
# Bugs

- Bug repro on [sandbox](https://sandbox.babylonjs.com/):
index.js line 345
```
   window.addEventListener("keydown", function(event) {
        // Press space to toggle footer
        if (event.keyCode === 32 && event.target.nodeName !== "INPUT") {
            if (footer.style.display === "none") {
                footer.style.display = "block"; // <---- HERE should be "grid"
                canvasZone.style.height = "calc(100% - 56px)";
                if (debugLayerEnabled) {
                    currentScene.debugLayer.show();
                }
                engine.resize();
            }
            else {
                footer.style.display = "none";
                canvasZone.style.height = "100%";
                errorZone.style.display = "none";
                engine.resize();
                if (currentScene.debugLayer.isVisible()) {
                    currentScene.debugLayer.hide();
                }
            }
        }
    });
```
- Expected result: Space key toggle the sandbox footer.
- Current result: When showing the footer, buttons are not available. The event changes the style to block instead of grid.

**Comment by LenaTevar** [comment]
Addition: 
The canvasZone div does not go back to their previous height after toggling back the footer.
index.js line 350

Expected result: div class canvasZone back to  height: calc(100% - var(--footer-height))
Current result:  div class canvasZone height is not setted back to original value

**Comment by deltakosh** [comment]
hello do you want to submit a PR to fix it?

**Comment by deltakosh** [comment]
Actually it was easy to do it as I was working on the sandbox

Thanks a ton for the feedback!
