### ISSUE TITLE
Instances shadows are not visible with refresh rate 0

### ISSUE THREAD

**Issue by sebavan** [BabylonJS/Babylon.js#8369]
https://www.babylonjs-playground.com/#YB006J#75

**Comment by Popov72** [comment]
Note that it has some thing to do with timing, as when refreshing the PG several times it does sometimes work.

Also, adding: 
```
            engine.stopRenderLoop();
            window.setTimeout(() => {
                engine.runRenderLoop(() => {
                    scene.render();
                });
            }, 1000);
```
in the `ImportMesh` callback make it always work.
