### ISSUE TITLE
Browser window hangs when disposing scene containing a particular GLB

### ISSUE THREAD

**Issue by nbduke** [BabylonJS/Babylon.js#8449]
# Bugs
Repro playground: https://www.babylonjs-playground.com/#LZWXKM#3
In the playground, wait for the model to load, then click the 'D' key.

For some reason, this model causes `scene.dispose()` to hit an infinite loop, hanging the browser window. In a different context (not the Playground), I debugged into things and discovered this loop to be the culprit:
```
while (this.textures.length) {
   this.textures[0].dispose();
}
```

**Comment by sebavan** [comment]
Thanks for the great repro will fix it ASAP. I ll recreate a new NPM today.

**Comment by sebavan** [comment]
Ok so this happens only with msft_lod extension + assetContainer cause the textures of first lods got disposed without belonging to the scene so they are not removed from it but nor from the container. 

I ll figure the best way to address it in the next couple hours.

**Comment by sebavan** [comment]
@bghgary FYI

**Comment by sebavan** [comment]
4.2.0-alpha.22 is up :-)
