### ISSUE TITLE
WebXR Camera is rotating inversely in Firefox Reality

### ISSUE THREAD

**Issue by fernandojsg** [BabylonJS/Babylon.js#8469]
When loading any WebXR demo on Firefox Reality on the Oculus Quest the camera control is rotating inversely.

- Bug repro on [playground](https://playground.babylonjs.com): https://playground.babylonjs.com/pg/9K3MRA
- Expected result: Moving the view according the headset orientation
- Current result: It seems like the rotation is inverted in all the angles

**Comment by RaananW** [comment]
Hi @fernandojsg , I did some tests comparing both implementation of WebXR browsers on the quest, and one in the emulator.

What I did was enter this scene - https://playground.babylonjs.com/debug.html#9K3MRA, rotate the device 45 degrees up in the X axis (technically - look straight and up) and made a snapshot of the first view (left eye). I took a screenshot of the values from all, showing the pos, quat, projection matrix and view matrix of the view.

I would expect the orientation to be both positive on the x axis and the w, something like:

```javascript
{
x: 0.38,
y:0,
z:0,
w: 0.92
}
```

The results from the emulator look like this:

![2020-07-03 17_33_23-DevTools - playground babylonjs com_debug html](https://user-images.githubusercontent.com/1381702/86483204-d4e60100-bd53-11ea-9bbd-ef1864501304.png)

Which is roughly correct.

These are the results from the oculus browser:

![2020-07-03 17_26_14-DevTools - playground babylonjs com_debug html#9k3mra](https://user-images.githubusercontent.com/1381702/86483227-e4fde080-bd53-11ea-8e11-9f37cdad17a2.png)

And this is from firefox reality:

![2020-07-03 17_19_22-Toolbox (USB) - Tab _ Babylon js Playground](https://user-images.githubusercontent.com/1381702/86483239-ecbd8500-bd53-11ea-80d0-b031210a88bc.png)

It seems to me like th rotation is inverted (x is negative). I made sure to check the X axis, as we are not flipping it to convert from right-handed to left handed. This is also the raw transformation from the device, without any manipulation on our side. 

Can that help you debug further?

**Comment by fernandojsg** [comment]
Thanks for looking into that @RaananW!
Ok, so it seems you are creating your transform using directly orientation and position instead of using the transform's matrix, that's why the difference between iwwg webxr samples or three.js.
I tested using the transform's matrix to decompose the rotation and I got 
```
{
_w: 0.8918419325535785,
_x: 0.45146151204582224,
_y: 0.011221145853035148, 
_z: -0.02524179787041015,
}
```
Where the `X` is positive so maybe is something our end on how we compute the rotation from the view matrix or is missing some transform I'm missing.
@MortimerGoro @bluemarvin any idea what can be happening here?

**Comment by RaananW** [comment]
Up until alpha 21 we used the view matrix directly, but since we support both right handed and left handed systems i had a problem supporting the conversion correctly. 
I'm working on moving us to use the view matrix directly (probably only in 4.3), but until then we will continue calculating it on our own using the transformation provided. I have no problem decomposing the view matrix, but i would expect the rotation that is already provided to be aligned with the matrix you provide 😁.

**Comment by fernandojsg** [comment]
@RaananW this is already fixed in Firefox Reality and it will be landed on the next release :) thanks for the help!
