### ISSUE TITLE
Animation Curve Editor List of Bugs/Features

### ISSUE THREAD

**Issue by toledoal** [BabylonJS/Babylon.js#8478]
Hello everybody! 😃 

#This is the current list of bugs/features that will be addressing for the Animation Curve Editor

- [x]  ~Bug (Flickering Scrollbar on resize)~
- [x] ~fps input doesn't update the frames per second property in animation~
- [x] ~when open animation to edit, the scale of animation is compressed~
- [x] ~when opening an animation the animation is not stopped~
- [x]  ~The Playhead is not draggable~
- [x]  ~The Playhead behavior is strange, the draggable area appears to be small~
- [x] ~Dragging keyframes should have limits to left/right.~
- [x] ~Dragging keyframes not working as expected~
- [x] ~Adding/Deleting keyframes produces bug on curve's path~
- [x] ~Stop animation after clicking Playhead.~
- [x] ~Stop animation on Loop button click~
- [x] ~Remove Size animation type on create~
- [x] ~Graph action controls hide sometimes. Should be visible all times~
- [x] ~Value box should be empty and disabled if no key frames are selected~
- [x] ~Frame Input should not reposition Playhead.~
- [x] ~Value box is not working (see https://github.com/BabylonJS/Babylon.js/pull/8515#issuecomment-656225459).~
- [x] ~Connect value and frame boxes to Keyframe dragging.~
- [x] ~Value scale is wrong and cannot change scale for types (int, float, color)~
- [x] ~Test font loading in Edge doesn't load sometimes~
- [x] ~Play animation in editor behaves strangely (probably fps related)~
- [x] ~Key frame should be able to be dragged back to 0 if it is the first one~
- [x] ~When adding a new keyframe, add value between two points in a curve~
- [x] ~You cannot delete a key with the 'delete' key, only the 'backspace' key. It should probably be both?~
- [x] ~When moving the tangent handles, they seem to be limited and cannot be raised or lowered past a certain point? I expected to be able to move a tangent to any height and it not be limited.~
- [x]  ~Broke Mode on/off. When moving control point the other distorts~

**Items left for initial Scope**
- [x] ~Dragging the playhead appears to have no connection to the scene? If I scrub the playhead in the curve editor, shouldn't the object being animated update in the playground?~
- [x]  ~Dragging the canvas around feels sluggish and stuttery~
- [x]  ~When dragging the playhead, the playhead seems to release from the mouse selection when the cursor falls outside of the playhead area. It should be sticky. I expected that once I had selected the playhead I could scroll left and right anywhere and it would move back and forth, not releasing playhead selection until the mouse button is released.~
   - [x]  ~Vertical scroll at the bottom is lost outside the slider. ~
- [x]  ~Moving the play to next/previous keyframes with the UI does not reposition the canvas~
- [x]  ~Animation Begin/End buttons do not go to the first/last frame. They are currently advancing the frame by one, which is incorrect behavior. ~
- [x]  ~The play control buttons do not reposition canvas~
- [x]  ~Flat tangents (only for selected keyframes)~
- [x]  ~When changing animation frame size, change the length of available frames~
- [ ] Dragging the canvas does not follow mouse (mouse looks faster than canvas)
- [ ] When canvas moves on selected frames, it does not reposition vertically at frame value
- [ ] Repair zoom/frame button
   - [ ]  Frame selected button should only work when we have selected keyframes
- [ ] Resize window doesn't resize the editor
- [ ]  Save animations should save tangents
- [ ]  On edit animation, animation should update to have tangents...
- [ ] Value box sometimes gets floats beyond three decimals
- [ ] Linear interpolation control not working,  Lerp only to next keyframe
- [ ] Scale of moving tangent points is not correct
- [ ] Deselect single key (if control points enabled) cannot be done
- [ ] When dragging a control point on a tangent, the control point cannot be lowered any further down than past the bottom of the frame. Please see reference video in the Teams Channel.
- [ ] Adjusting control points of a tangent appears to improperly affect the animation values. Please see reference video in the Teams Channel.
- [ ] If I play the animation inside the editor and my keyframes go minus 0 (-1.... -100) I can't play animations and I get and extra frame zero on my selected animation keys 

**Items for future scope**
- [ ] Test Load from a snippet
- [ ] Test save to a snippet
- [ ] Add proper support for animation groups. 
   - [ ] Removed target path for now (this is aimed at animation groups)
- [ ] Vector2/3 Support
   - [ ]  Select Vector3 Animation, shows its animations
   - [ ] Adding keyframes to Vector3 animations not working
- [ ] I could not figure out how to expand the viewable frame range. Is this related to the zoom buttons being missing/broken?
- [ ] Fix Old Edge
- [ ] When breaking tangents on a key and dragging the handles, the movement of the handles seems to be limited to vertical movement only? I expected it to allow me to drag the tangent handles horizontally as well. 
- [ ]  Select Coordinate Animation, shows selected list background, and displays the correct curve
- [ ]  Select Vector3 animation, shows selected list background
- [ ]  selected keyframe in coordinate animation, shows yellow diamond on animation list
- [ ]  When dragging keyframes, coordinate animations, should update its frame, but not its values

**Comment by sebavan** [comment]
@PirateJC, you should be able to start playing back with the curve editor in the limits of the bugs defined upper. Please let @toledoal know of any other issues.

@toledoal would be great to have to 2 next one on the list by end of week to start fully playing with the curves. Do you think it is achievable ?

**Comment by toledoal** [comment]
Yes, I'll be working those couple bugs today. I started reviewing last night the one for Play animation (fps) but I need to investigate further. 👍

**Comment by sebavan** [comment]
I also added to the list the fact that the former Edge just crashes on open
![image](https://user-images.githubusercontent.com/16655165/88341169-633f1880-cd3d-11ea-90c5-2792f420a3bc.png)

**Comment by PirateJC** [comment]
Hey Guys,
Playing around with the curve editor this morning...I've tried to cross-reference the things I've found with the known bugs, forgive me if I comment on something you already know about. Here's a few things I've found:

- [ ] When breaking tangents on a key and dragging the handles, the movement of the handles seems to be limited to vertical movement only? I expected it to allow me to drag the tangent handles horizontally as well. 
- [ ] Dragging the canvas around feels sluggish and stuttery
- [ ] Dragging the playhead appears to have no connection to the scene? If I scrub the playhead in the curve editor, shouldn't the object being animated update in the playground?
- [ ] I could not figure out how to expand the viewable frame range. Is this related to the zoom buttons being missing/broken?
- [ ] When dragging the playhead, the playhead seems to release from the mouse selection when the cursor falls outside of the playhead area. It should be sticky. I expected that once I had selected the playhead I could scroll left and right anywhere and it would move back and forth, not releasing playhead selection until the mouse button is released.
- [ ] When moving the tangent handles, they seem to be limited and cannot be raised or lowered past a certain point? I expected to be able to move a tangent to any height and it not be limited.
- [ ] You cannot delete a key with the 'delete' key, only the 'backspace' key. It should probably be both?

**Comment by toledoal** [comment]
I did another pass on things we are missing on the editor and added several checkboxes for those.

**Comment by PirateJC** [comment]
I just updated the main list to reflect the latest conversation and reflect the scoping discussion we've recently had.

**Comment by PirateJC** [comment]
Just added 2 new bugs per the email conversation. From here on out, will move bugs to the Teams thread. Please see video reference for the bugs found today.

**Comment by sebavan** [comment]
Following Today s tests, I added:
- [ ] Dragging the canvas does not follow mouse (mouse looks faster than canvas) (discussed together)
- [ ] When canvas moves on selected frames, it does not reposition vertically at frame value (the horizontal position is now ok but not the vertical one)

**Comment by deltakosh** [comment]
Closing as we are rewriting the control
