### ISSUE TITLE
libktx needs to be updated to follow latest spec changes

### ISSUE THREAD

**Issue by zeux** [BabylonJS/Babylon.js#8483]
KTX specification rc1 (https://github.khronos.org/KTX-Specification/, 2020-05-26) removed globalFlags from supercompression global data for BasisU.

This makes all existing KTX2 files incompatible, and accordingly requires an update to libktx to load them; currently valid (as per new spec) files fail to load with:

> ERROR: Failed to transcode: File data is inconsistent with KTX spec.

Attaching a sample file which loads correctly in three.js after https://github.com/mrdoob/three.js/pull/19791

[rubyrose.glb.zip](https://github.com/BabylonJS/Babylon.js/files/4873328/rubyrose.glb.zip)

**Comment by sebavan** [comment]
Adding @bghgary to upgrade

**Comment by bghgary** [comment]
I've been looking at this for a bit. There are issues with the latest version of libktx.js/wasm where the GL object not exposed for some reason. Still investigating with Mark, but this might take a bit of time.

**Comment by bghgary** [comment]
Turns out the new build in KTX-Software is causing an issue. The old build is still there, so I was able to create a build using that with Mark's help.
