### ISSUE TITLE
Large Scene Size Not Rendering with ArcRotateCamera

### ISSUE THREAD

**Issue by ecoinomist** [BabylonJS/Babylon.js#8486]
# Bugs

- Bug repro on [playground](https://playground.babylonjs.com/#91IBLI):
- Expected result: render meshes with any number of unit scale, useful for architecture to set 1 unit = 1 millimetre to avoid js floating point calculation issues
- Current result: when the number used for Vector3 and mesh sizes exceed about 1000, scene with ArcRotateCamera stops rendering them either partially, or completely, beginning from the top part of the canvas.

**Comment by Hersir88** [comment]
@ecoinomist `camera.maxZ = 100000;`

it could be because max camera depth need to be set higher

**Comment by ecoinomist** [comment]
@Hersir88 `camera.maxZ = 100000` fixed it, but shouldn't this be set automatically, relative to `camera.radius`?
The bug does not appear with UniversalCamera.

**Comment by sebavan** [comment]
Clipping maxZ and minZ is something free for the user to set on the camera as on one side it will limit zFighting to increase precision and on the other limit what you render in the far distance. The current behavior is the expected one.
