### ISSUE TITLE
Certain 3D models capture input regardless of occlusion

### ISSUE THREAD

**Issue by nbduke** [BabylonJS/Babylon.js#8519]
# Bugs
Repro playground: https://www.babylonjs-playground.com/#4ULPY6

In the playground, I've loaded a 3D model that always gets picked by the scene, even when the pointer is over an occluding mesh (the "can't click me" square). You can, however, click on something that doesn't have the model behind it.

**Comment by deltakosh** [comment]
@CedricGuillemet do you mind having a look?

**Comment by CedricGuillemet** [comment]
I'm on vacation until 7/15. I can take a look when I come back.

**Comment by deltakosh** [comment]
Will it work @nbduke ?

**Comment by nbduke** [comment]
@deltakosh yeah that should be fine. I think I have a workaround anyway, which is to make the problematic meshes unpickable.

**Comment by deltakosh** [comment]
Let me just try to see if @RaananW has a few cycles to check?

**Comment by Popov72** [comment]
If it can help, the problem does not show up if the scaling of the parent transform node is set to 1/1/1 instead of being 0.01/0.01/0.01 as it is after loading.

After loading:
![image](https://user-images.githubusercontent.com/4152247/87092046-0b7fb800-c23b-11ea-85d0-954986526bd3.png)

Setting the scaling to 1/1/1:
![image](https://user-images.githubusercontent.com/4152247/87092108-294d1d00-c23b-11ea-951a-844a11524c8f.png)

The **Can't click me!** button can now be clicked.

**Comment by CedricGuillemet** [comment]
Yes, it looks like the scale interferes with the world position and the distance at some point.

**Comment by CedricGuillemet** [comment]
There is a skeleton associated with the mesh and the skeleton world transform is identity. It's used to compute the ray (origin, direction) https://github.com/BabylonJS/Babylon.js/blob/2e51756b494b3c8f655c818e0fd443832d35981f/src/Culling/ray.ts#L680
But when the local hit position/origin is converted back to world coordinates, the mesh world matrix is used https://github.com/BabylonJS/Babylon.js/blob/2e51756b494b3c8f655c818e0fd443832d35981f/src/Meshes/abstractMesh.ts#L1541
I have 2 questions:
- @nbduke do you know why you have a mesh with a skeleton ? 
- @deltakosh shall I use the same matrix (with the override skeleton matrix) for computing back the local position to the world coordinates?

**Comment by nbduke** [comment]
I don't know why. This model came from the Hubble service of stock 3D models. I've found several of them that repro this bug, so I'm guessing that means a lot of them use skeletons for whatever reason.

**Comment by deltakosh** [comment]
Yes I think this is the problem! Good catch!
