### ISSUE TITLE
Soft Body broken when source model is glTF

### ISSUE THREAD

**Issue by Kagetsuki** [BabylonJS/Babylon.js#8520]
When using glTF files as soft bodies they end up having very strange behavior. More specifically, despite how the soft body properties are set, they crumple like paper and their collision detection breaks and they fall through other objects. Multiple soft bodies inserted into the scene this way also don't interact with each-other in any logical fashion. 

**Repro**
Because this bug requires an external glTF model, I'm not able to easily reproduce it in the sandbox. Instead, allow me to provide sample files and code here:
```js
import * as BABYLON from 'babylonjs'
import 'babylonjs-loaders'

function init() {
  var canvas = document.getElementById('renderCanvas')
  var engine = new BABYLON.Engine(canvas, true, { preserveDrawingBuffer: true, stencil: true })
  var scene = new BABYLON.Scene(engine)
  scene.enablePhysics(new BABYLON.Vector3(0,-9.81, 0), new BABYLON.AmmoJSPlugin())
  scene.debugLayer.show()
  var camera = new BABYLON.ArcRotateCamera("Camera", 3 * Math.PI / 2, Math.PI / 2.5, 15, BABYLON.Vector3.Zero(), scene);
  camera.setTarget(BABYLON.Vector3.Zero())
  camera.attachControl(canvas, false)
  var light = new BABYLON.HemisphericLight('light1', new BABYLON.Vector3(0, 1, 0), scene)

  var options = {
    mass: 1,
    friction: 0.1,
    restitution: 0.3,
    pressure: 2000,
    velocityIterations: 40,
    positionIterations: 40,
    stiffness: 0.9,
    damping: 0.01
  }

  var ground = BABYLON.MeshBuilder.CreateBox('ground', {width: 5, height:0.2, depth: 5}, scene)
  ground.physicsImpostor = new BABYLON.PhysicsImpostor(ground, BABYLON.PhysicsImpostor.BoxImpostor, { mass: 0, friction: 0.5, restitution: 0 }, scene)

  BABYLON.SceneLoader.ImportMeshAsync('', 'assets/glb/box.glb', '', scene).then(model => {
    var targetMesh = model.meshes[1]
    targetMesh.parent = null
    targetMesh.forceSharedVertices()
    targetMesh.physicsImpostor = new BABYLON.PhysicsImpostor(targetMesh, BABYLON.PhysicsImpostor.BoxImpostor, { mass: 10 }, scene)
  })

  BABYLON.SceneLoader.ImportMeshAsync('', 'assets/glb/soft.glb', '', scene).then(model => {
    var targetMesh = model.meshes[1]
    targetMesh.parent = null
    targetMesh.forceSharedVertices()
    targetMesh.position.y = 3
    targetMesh.physicsImpostor = new BABYLON.PhysicsImpostor(targetMesh, BABYLON.PhysicsImpostor.SoftbodyImpostor, options, scene)
  })

  window.addEventListener('resize', () => {
    engine.resize()
  })

  engine.runRenderLoop(() => {
    scene.render()
  })
}

init()
```
[soft-body-glb-samples.zip](https://github.com/BabylonJS/Babylon.js/files/4900488/soft-body-glb-samples.zip)

**Screenshots**
![image](https://user-images.githubusercontent.com/864634/87110093-2e44b780-c2a1-11ea-9e8d-707e6beb1efe.png)

**Desktop (please complete the following information):**
 - OS: Tested on both OSX and Linux
 - Browser Tested on both Chrome and FireFox

**Additional context**
I'm not the developer who discovered this bug, I just translated the information, so my description may not be accurate. If you are unable to replicate the issue or find my description to be inaccurate or lacking please let me know and I will try to get a better description or have the developer make a sample that can be viewed easily in the sandbox.

**Comment by BabylonJSGuide** [comment]
Here is a playground https://www.babylonjs-playground.com/#XY6QF0#3. It is worth playing with the options values, the ones from above are commented out.

You can replace box.glb with soft.glb.

You might be better placing the issue on the forum as more people follow that.

**Comment by deltakosh** [comment]
"You might be better placing the issue on the forum as more people follow that."

It is mentioned in the issue template as well

**Comment by Kagetsuki** [comment]
@deltakosh I'm not asking for help though, I'm trying to report what appears to be a bug/issue.

To clarify, what we are experiencing here does not occur with meshes/objects created within Babylon or from other imported formats that we have checked. This appears to be exclusive to glTF. Once you make the glTF objects into soft bodies they become unstable, quickly collapse in on themselves/crumple, and appear to have some sort of hit detection inside of themselves as they never stop pulsing/twitching. This, again, does not occur with say a cube created within Babylon, but what is essentially the same cube created in Blender and exported as glTF will not act the same even with the same parameters.

@BabylonJSGuide Thanks for putting together the playground scene. I've edited it a bit to display what I'm talking about: https://www.babylonjs-playground.com/#XY6QF0#4

![image](https://user-images.githubusercontent.com/864634/87213001-a7edab80-c35c-11ea-8d29-89cfbd254ad6.png)

![image](https://user-images.githubusercontent.com/864634/87213101-63164480-c35d-11ea-9411-ab5af6828f99.png)

**Comment by Popov72** [comment]
What @deltakosh  is saying is that you should create a post in the forum (https://forum.babylonjs.com/) about this.

More people will be able to have a look at it.

**Comment by deltakosh** [comment]
Don￼'t get me wrong, I certainly don't want to shut the discussion down

On the contrary, I want to make sure this problem get exposed to a maximum number of people

**Comment by Kagetsuki** [comment]
I understand, but I'm probably not the best person to present the issue on the forum. It's on one of our developers who found the issue while we were evaluating different engines, and she asked me to report it for her as she doesn't speak English. To be perfectly honest I don't completely understand how to describe the issue any more accurately than I have above, so if just copying the above and pasting it on the forum would be sufficient I'll do so, but I don't know how much more I can do than that.

**Comment by deltakosh** [comment]
" so if just copying the above and pasting it on the forum would be sufficient I'll do so"
That would be perfect!

**Comment by Kagetsuki** [comment]
I have posted on the forums: https://forum.babylonjs.com/t/soft-body-issues-when-importing-a-gltf-model/12501
