### ISSUE TITLE
Allow functions to take parameters object

### ISSUE THREAD

**Issue by Yonet** [BabylonJS/Babylon.js#8521]
**Issue:**

The current way of using comma-separated parameters for functions is error-prone and harder to use:

- The user has to remember the order of the parameters. This problem might be solved for TypeScript users by the editor but it is still a problem for JS developers. 

- When not using all of the parameters, still needs to enter a value, which makes it harder to read the code. 

```ts       
 const importResult = await SceneLoader.ImportMeshAsync(
            "",
            "",
            controllerModel,
            scene,
            undefined,
            ".glb"
        );
```

- If the developer wants to use a configuration object the implementation would be harder.

**Solution:**

If as an option, we can give an object as a parameter with named values, no one needs to remember the order of parameters and would be easier to read code examples.

```ts       

 const config = {
            sceneFilename: controllerModel, 
            scene: scene, 
            pluginExtension: ".glb"
 }
 const importResult = await SceneLoader.ImportMeshAsync(config);
```

I am happy to help to refactor. 

Thanks!

**Comment by Hersir88** [comment]
Small note on this, its ok for functions that are not called often but could be an issue for these that are called in loops or even worse on game loop as can lead to bigger garbage collections, but that's depends on platform
 and browser version

**Comment by deltakosh** [comment]
Yep totally aligned with @Hersir88 
Also we protect the backward compatibility so if this happens it would be on a second function (which is totally ok)

That being said we recommend opening the discussion on our forum first

Do you mind opening a thread there? I'm totally ok to add a function that takes a config parameter

**Comment by Yonet** [comment]
I am not saying it has to be a named object, garbage collection is irrelevant. Passing in an object directly is still more readable, less error-prone. 

> Also we protect the backward compatibility so if this happens it would be on a second function (which is totally ok)

You can check if the argument is an object in the same function, no?

> That being said we recommend opening the discussion on our forum first

I have copy-pasted into the forum. I am not clear when to open an issue vs using the forum since there is a feature request template for the issues.
