### ISSUE TITLE
Multi View - Input & Action Manager doesn't work properly

### ISSUE THREAD

**Issue by rwedoff** [BabylonJS/Babylon.js#8537]
**Repro**
- Bug repro on [CodePen](https://codepen.io/rywedoff/pen/BajOpQx?editors=1010):
- Expected result: When having using a multi view/canvas setup, the input system should work on the Canvas that is currently in focus.
- Current result: Having to set the engine.inputElement on click/focus the camera events based on the mouse are messed up, i.e. the camera starts zooming instead of rotating around the model.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Edge Chromium Beta
 - Version:  84.0.522.35 (Official build) beta (64-bit)

**Additional context**
Previous correspondence: 
I am working with a multi canvas setup from useEngine() setup. I am attempting to add a an ActionManager to a mesh to execute a code action OnPickDownTrigger. I am having some strange input behaviors though, compared to a playground test environment. 

In the multi canvas React version [here]( https://github.com/rwedoff/BabylonReact/blob/u/rywedoff/executeCodeAction/testapp/src/App.tsx), I have added 2 spheres to the scenes. One on the top, and one on the bottom. The top sphere works okay (it doesn't work if we are zoomed out far from the mesh, it doesn't change the cursor)
The bottom canvas, clicking it doesn't work at all.

The challenge is setting the engine input element setup that we have here:
```
let inputElement = engine.inputElement;
scene1.detachControl();
engine.inputElement = canvas1;
scene1.attachControl();
engine.inputElement = inputElement;
```

A work around is to add set the input element based on a canvas click/mouseenter event (which can be found in the CodePen above), but then that's where there are strange behaviors with the zooming and rotating.

**Comment by deltakosh** [comment]
Pinging @Popov72 to see if he has a few cycle to check

**Comment by deltakosh** [comment]
@CedricGuillemet do you mind having a look?

**Comment by CedricGuillemet** [comment]
@deltakosh Sure! I add this issue to my todo list.

**Comment by Popov72** [comment]
Sorry, I missed the ping!

**Comment by deltakosh** [comment]
lol no worries you already have a lot on your plate buddy!

**Comment by CedricGuillemet** [comment]
@rwedoff I've found that the pinch/zoom issue happens when clicking in the canvas that has already the focus.
So, I've tweaked your js to detach both scene controls in the addEventListener and it worked properly.
```
canvas1.addEventListener("click", () => {
  scene2.detachControl();
  scene1.detachControl();
  engine.inputElement = canvas1;
  scene1.attachControl();
});

canvas2.addEventListener("click", () => {
  scene2.detachControl();
  scene1.detachControl();
  engine.inputElement = canvas2;
  scene2.attachControl();
});

```
I don't know yet why it happens. @PolygonalSun any idea why it happens?

**Comment by CedricGuillemet** [comment]
When the controls are attached to a scene twice, the arcRotateCameraPointer input receive 2 pointerDown events and assumes it's multitouch and then treat pointerMove as pinch.
A quick fix is to detach controls for both scenes like I did in my previous comment.
Another fix is to check if the registration already exists here
https://github.com/BabylonJS/Babylon.js/blob/0a6e9368c61090cb3be822efaca6f16eab37efed/src/Inputs/scene.inputManager.ts#L460
and unregister before re-registering. I don't know if this solution has some draw backs or if it's a good practice in the engine.
Do you see another better solution ? @RaananW @sebavan

**Comment by RaananW** [comment]
This is technically detaching before re-attaching, right? Would that still allow multi-touch on both canvases?

The issue here (application-level) is that a click is allowed on the canvas that is already focused. We can be defensive and make sure that the scene (or better yet - the input manager) is not already attached to this specific canvas - which will be a cleaner solution, but on an application level, I would not register a global click, or make sure in the callback that either the scene is not already attached or that the last attached scene is detached. something like this:

```javascript
let attachedScene; 
canvas1.addEventListener("click", () => {
  attachedScene.detachControl();
  engine.inputElement = canvas1;
  scene1.attachControl();
  attachedScene = scene1;
});

canvas2.addEventListener("click", () => {
  attachedScene .detachControl();
  engine.inputElement = canvas2;
  scene2.attachControl();
  attachedScene = scene2;
});
```
