### ISSUE TITLE
Display of 180 mono videos on the the VideoDome does not display as expected

### ISSUE THREAD

**Issue by jocravio** [BabylonJS/Babylon.js#8575]
On the video dome props, you can both specify the videoMode (mono, stereo LR, TB) and the halfDomeMode (true/false). I was kind of expecting that if you set the videoMode to mono and the halfDomeMode: true, you would be able to correctly display a 180 mono video on half of the dome.

What I am getting instead is that half the dome is covered (expected) but only half of the 180 video is being displayed, and it is stretched as if the whole video was extended through the 360 surface and then half was covered.

From the documentation (How to do 360 Video - Babylon.js Documentation 1), it doesn’t specify anything about 180 mono videos not being supported.

I opened a topic on April around this as I was implementing the VR 180 stereo (How to properly display 180 videos on the VideoDome), but thought that a new topic was worth to point this out.
@RaananW

**Screenshots**
Actual 180 video
![actual video](https://user-images.githubusercontent.com/63118979/88090371-56a2a080-cb42-11ea-97d4-53616083d2e8.png)

Video displayed on the dome with halfDome: true, videoMode: mono
![display when 180 option - monoscopic dome](https://user-images.githubusercontent.com/63118979/88090447-78038c80-cb42-11ea-969a-590a893d6991.png)

Video displayed on the dome with halfDome: true, videoMode: stereo side by side
![display when 180 option - stereoscopic side by side](https://user-images.githubusercontent.com/63118979/88090486-8487e500-cb42-11ea-9422-548c2ef643fc.png)

Expected result:
Half of the video dome should be covered, but the entire video should show on the other half without being stretched.

@RaananW 

Here is the link to the forum where this was discussed:
https://forum.babylonjs.com/t/display-of-180-mono-videos-on-the-the-videodome-does-not-display-as-expected/12458

Here is a link to a 180 mono video, in case you need one for testing.
https://microsoft-my.sharepoint-df.com/:v:/p/jocravio/ETaiETsPxKZCgHmp4deWHdcBW8Od2P5A7MFXWZxG5ZnUmA?e=Vb9Aav

**Comment by RaananW** [comment]
Merged, should be working correctly now. @jocravio - please reopen if there is any issue :-)

**Comment by jocravio** [comment]
Thanks!
