### ISSUE TITLE
Texture no-v-flip option

### ISSUE THREAD

**Issue by velbi** [BabylonJS/Babylon.js#8581]
UV is wrong, When dynamic material change with texture by code(three.js, playcanvas.js..),  
 like this picture (https://forum.babylonjs.com/t/3dsmax-exporter-plugin-gltf-glb/6492)
 Probably This problem is because of ao texture.

The reason is model UV,. 

So I think we need no-v-flip feature or without uv feature thru checkbox option.
like --no-flip-v (Don't flip V texture coordinates) in https://github.com/facebookincubator/FBX2glTF#cli-switches  
or glTF export  without uv in blender 

Thanks.

**Comment by deltakosh** [comment]
Hello please use forum.babylonjs.com for questions
