### ISSUE TITLE
BoundingBox.vectorsWorld resolves to local vectors when being accessed

### ISSUE THREAD

**Issue by ecoinomist** [BabylonJS/Babylon.js#8591]
**Repro**
- Bug repro on [playground](https://playground.babylonjs.com/#RC7EHK):

- Expected result: mesh.getBoundingInfo().boundingBox.vectorsWorld should return vectors that can be accessed as world space vectors

- Current result: any form of accessing .vectorsWorld will resolve to local space vectors
- Example: 
```js
var world = sphere.getBoundingInfo().boundingBox.vectorsWorld;
console.log('world', world); // => shows world space vectors correctly
console.log('world.accessed', world[0]); // => bug - it will resolve as local space vector
console.log('world.cloned', world.map(v => v.clone())); // => bug
console.log('world.mapped', world.map(({x, y, z}) => ({x, y, z}))); // => bug
```

**Screenshots**
attached
<img width="469" alt="Screenshot 2020-07-23 at 12 53 49" src="https://user-images.githubusercontent.com/13236298/88273945-9f458f80-cce3-11ea-94d6-8e777c5e3952.png">
.

**Desktop (please complete the following information):**
 - OS: [macOS Catalina]
 - Browser [chrome]
 - Version [84]

**Comment by Popov72** [comment]
The world matrix must be up to date when you get the `vectorsWorld` property.

So, you should call `sphere.computeWorldMatrix()` yourself: it is done automatically by the engine in the render loop, but in your sample the render loop is not enterered yet when you display the values.

https://playground.babylonjs.com/#RC7EHK#1
