### ISSUE TITLE
Implementing EXT_texture_webp to gltf loader

### ISSUE THREAD

**Issue by samevision** [BabylonJS/Babylon.js#8614]
Since we are using 3D in web, the smaller the file size the better. Unfortunately 2k, 4k, 8k textures are very big using png or jpg.

I would love to use [EXT_texture_webp](https://github.com/KhronosGroup/glTF/tree/master/extensions/2.0/Vendor/EXT_texture_webp) with babylon js because webp is able to compress the file size of textures massively.

Forum: https://forum.babylonjs.com/t/using-webp-with-gltf/12732

**Comment by deltakosh** [comment]
Will do! Thanks a lot!

**Comment by deltakosh** [comment]
Do you have a sample gltf and glb we can use to test it?

**Comment by samevision** [comment]
I uploaded a gltf with seperated textures here: https://gofile.io/d/PpzOjP

I wasn’t able to test it because I can’t find a gltf viewer that supports this extension.

I hope this helps.

**Comment by deltakosh** [comment]
Thanks a lot! That's perfect
