### ISSUE TITLE
event has no pointerId in 4.2.0-alpha.27

### ISSUE THREAD

**Issue by kutomer** [BabylonJS/Babylon.js#8633]
Hello guys,

I'm testing the new version (upgrading from `"@babylonjs/core": "4.1.0"`to `4.2.0-alpha.27`, and noticed an API change that I wasn't expecting.

When using: `scene.onPrePointerObservable.add` the `event.event.pointerId` is undefined on safari desktop (I guess that it might be undefined on different browsers as well) the pointerId is used to identify the "finger" in multi-touch screens.
The only change I made was upgrading babylon version and then I noticed the bug.

I would very much appreciate your help in this matter.

**Comment by deltakosh** [comment]
Hello please use the forum as mentioned in the issue template :)

Cc @CedricGuillemet to check that issue in the meantime
