### ISSUE TITLE
WebGL context lost - new safari 14 context lost with cubeTexture

### ISSUE THREAD

**Issue by kutomer** [BabylonJS/Babylon.js#8634]
Hi, 
I found a bug related to the new safari 14 and of course the new iOS 14.
When creating a dynamic `ReflectionProbe` with cubeTextue and than resizing the canvas WebGL context is lost and meshes from the screen disappear (I couldn't find any way of recovering from this state)
![1](https://user-images.githubusercontent.com/3729904/88802797-40d15300-d1b4-11ea-8468-22ea0263d65e.gif)

steps to reproduce: 

1. [made a simple playground containing both a mesh with PbrTexture and a ReflectionProbe with cube texture](https://playground.babylonjs.com/#DUXI7P#2)
2. Open [safari beta desktop](https://developer.apple.com/safari/download/) or safari mobile on iOS 14
3. let the model load for a second
4. resize the window and see that context is lost

As always, will very much appreciate your help!
Tomer.

**Comment by deltakosh** [comment]
Please use the forum to discuss issues. Furthermore this is a safari  beta related bug so I encourage you to report it to safari
