### ISSUE TITLE
Optimizing glTF reading like in blender .

### ISSUE THREAD

**Issue by tawfik741** [BabylonJS/Babylon.js#8635]
I tessellated a step file and exported it to glb . I then opened glb the file with blender . The file works really fine . I then uploaded the file to babylon's sandbox and found out that since i exported just after tessellation , all the primitives are meshes and babylon draws every primitive everytime i move the camera resulting to a really big number of draw calls . I found out that blender welds the node's primitives to one mesh by itself after uploading the glb file . I exported the blender render to glb and uploaded it to babylon's platform and found out that all the primitives are merged . Is there a way to merge all the primitives to one mesh when reading the glb file with babylon like blender does ?

**Comment by deltakosh** [comment]
Please use the forum as stated in the issue template
