### ISSUE TITLE
Implementing thin instance picking support

### ISSUE THREAD

**Issue by Popov72** [BabylonJS/Babylon.js#8638]
See https://forum.babylonjs.com/t/picking-instances-using-ext-mesh-gpu-instancing/12399/7

**Comment by deltakosh** [comment]
what is missing?

**Comment by Popov72** [comment]
Only that I do the code :)

But I think I didn't fully understand your question (?)

**Comment by deltakosh** [comment]
For some reasons I thought thin instances were already added to the gltf extension..Isn't it?

**Comment by deltakosh** [comment]
OR..I do not understand what this task is about ;D

**Comment by deltakosh** [comment]
OH I know: it is about PICKING!!

**Comment by deltakosh** [comment]
I can do it by the way as you have a lot on your plate already

**Comment by Popov72** [comment]
Yes, but the core of it is to implement intersection between thin instances and box / ray, that's why I had added "intersection" in the title.

**Comment by Popov72** [comment]
> I can do it by the way as you have a lot on your plate already

That's fine to me, I will switch to something else then.

**Comment by deltakosh** [comment]
Deal!
