### ISSUE TITLE
IWebXRHitTestOptions should expose options to hit test against XRHitTestTrackableType instead of assume a default implementation

### ISSUE THREAD

**Issue by hendryems** [BabylonJS/Babylon.js#8687]
**Is your feature request related to a problem? Please describe.**
When hit testing against real world geometry (e.g. through ARKit/ARCore), the hit test seems to be very specific to a particular implementation.

E.g. On the ARCore implementation [Source [link](https://github.com/BabylonJS/BabylonNative/blob/master/Dependencies/xr/Source/ARCore/XR.cpp)], this is XRHitTestTrackableType.mesh which seems to be the most restrictive.

```
            // Iterate over the results and pull out only those that match the desired TrackableType.  For now we are limiting results to
            // just hits against the Plane, and further scoping that to Poses that are contained in the polygon of the detected mesh.
            // This is equivalent to XRHitTestTrackableType.mesh (https://immersive-web.github.io/hit-test/#hit-test-trackable-type-enum).
```

For apps looking to build an app using BabylonJS as its XR abstraction, it is desirable to be able to configure the specifics of what hit testing would be against.

**Describe the solution you'd like**
When configurating a WebXRHitTest, a XRHitTestTrackableType option (through IWebXRHitTestOptions ?) should be exposed.

**Discussion**
https://github.com/BabylonJS/BabylonReactNative/issues/53

**Comment by RaananW** [comment]
Sure! makes sense. I have already added entityType to the webxr.d.ts file, it is a matter of exposing it in the configuration. Also noticed the `mesh` type is missing, will add that as well
