### ISSUE TITLE
Make geometry renderer works with webgl1 + extension

### ISSUE THREAD

**Issue by deltakosh** [BabylonJS/Babylon.js#8701]
So far GeometryRenderer requires webgl2 but could work with 1+extension

**Comment by julien-moreau** [comment]
Isn't the case using the "draw buffers" extension with WebGL1 ?

**Comment by deltakosh** [comment]
Actually it works :) I'm dumb :D

**Comment by deltakosh** [comment]
The problem is elsewhere. We introduced the PrePass renderer and I think this should be removed and merged into the geometry buffer

@julien-moreau: Do VLS, MotionBlur or SSR works with webgl1?

**Comment by julien-moreau** [comment]
Yep they work, if the draw buffers extension is available which is not available on iOS :(

VLS are still using a custom render target (like the depth renderer does) to render their custom pass. Maybe it can be moved to geometry buffer renderer but will not work on iOS anymore :( except if both modes are supported

**Comment by deltakosh** [comment]
I think we should as ios14 will support webgl2
Or we add a mode for it so we keep both paths
