### ISSUE TITLE
GUI Sliders become permanently active if window loses focus while sliding

### ISSUE THREAD

**Issue by DarraghBurkeMS** [BabylonJS/Babylon.js#8719]
**Repro**
- Bug repro on [playground](https://www.babylonjs-playground.com/#U9AC0N#1)
- Expected result: If you begin dragging the slider, and the canvas loses focus (for example, if the user changes tabs), the slider should also lose focus and stop sliding.
- Current result: The slider becomes permanently "active", so it will continue to slide with the mouse even after the mouse button has been released. There doesn't seem to be a way to get it to stop sliding.

Note: this behavior also happens if you trigger a context menu by right clicking, although this is disabled in the playground.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 83.0.4103.116

**Comment by DarraghBurkeMS** [comment]
I would be happy to look into resolving this issue if need be :)

**Comment by Popov72** [comment]
Let @deltakosh decide if that needs to be investigated.

If that does, maybe while you are debugging the slider component you can have a look at https://forum.babylonjs.com/t/when-the-slider-is-scaled-down-in-a-container-the-thumb-doesnt-follow-the-pointers-position-accuratelly/13203 (if that needs to be investigated too)?

**Comment by deltakosh** [comment]
@DarraghBurkeMS please do :)
