### ISSUE TITLE
Highlight Layer is breaking webxr

### ISSUE THREAD

**Issue by Renji3** [BabylonJS/Babylon.js#8720]
**Repro**
- Bug repro on [playground](https://playground.babylonjs.com/pg/9K3MRA/revision/133):
- Expected result: When opening XR the model should be rendered just like outside of xr
- Current result: Only the highlight layer is visible

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Oculus Quest
 - Browser: Oculus Browser
 - Version: 11.0.0.1.20.2325867404

**Comment by deltakosh** [comment]
Did you chat on the forum first before posting as mentioned in the template?

**Comment by Popov72** [comment]
Yes he did, @RaananW asked him to create the issue.

**Comment by deltakosh** [comment]
Ok it would have been perfect to follow the template then :)

**Comment by RaananW** [comment]
I can reproduce this, it seems like when in XR (not emulated) the highlight layer is the only thing rendered.

**Comment by RaananW** [comment]
The issue was that stencil was set to false per default on the xr context. a new PR will take the value from the engine instead of setting defaults
