### ISSUE TITLE
The skybox makes the second view of the camera disappear

### ISSUE THREAD

**Issue by dad72** [BabylonJS/Babylon.js#8732]
Link to this subject: 
https://forum.babylonjs.com/t/gizmo-multiview-and-skybox/13329/2?u=dad72

**Repro**
- Bug repro on [playground](https://www.babylonjs-playground.com/#Z4ZGAY#21):
- Expected: Display of both views
- Current result: The skybox makes the second view of the camera disappear

**Comment by deltakosh** [comment]
Well this is expected as the viewport of the camera1 is overlapping. The solution is to add camera1 first but I guess this introduces another issue right?

**Comment by dad72** [comment]
Yes exactly 

The second problem that this produces is on this PG : 
https://www.babylonjs-playground.com/#Z4ZGAY#18

**Comment by dad72** [comment]
For more information, the Gizmo should be on camera1
But the cameraGIzmo disappears and the GizmoManager is found on Camera2

**Comment by deltakosh** [comment]
Here is your fix:

You need to tell the gizmo layers to pick the camera1:
https://www.babylonjs-playground.com/#Z4ZGAY#22

Line 43 / 44
