### ISSUE TITLE
Open Url on button click

### ISSUE THREAD

**Issue by parthgundi** [BabylonJS/Babylon.js#8741]
Hi,

Is it possible to open a URL after clicking a Holographic Button?

Thanks,

**Comment by dad72** [comment]
Yes, Just use **location.href = URL** inside an observable

**Comment by parthgundi** [comment]
Hi, 
i'm unsure where to put the link: https://www.babylonjs-playground.com/#HB4C01#300
also how do you add images to a holographic button?

**Comment by deltakosh** [comment]
Please use the forum for question: forum.babylonjs.com
