### ISSUE TITLE
Using Gizmos With Instanced Mesh

### ISSUE THREAD

**Issue by julien-moreau** [BabylonJS/Babylon.js#8784]
I'm sure it's a bug, so I'll not use the forum first :)

Using gizmos with InstancedMesh class has some problems: the world matrix of the instance is well updated according to the gizmo's manipulation but its transformation properties (position, rotation / rotation quaternion and scaling) are not updated.

Using the given playground: move using plane gizmos. Then, use one of the axis gizmos. You'll see that the sphere has its transformation reset to the original one.

According to this line, the "_matrixChanged" method doesn't take care of InstancedMesh class: https://github.com/BabylonJS/Babylon.js/blob/master/src/Gizmos/gizmo.ts#L197

- Bug repro on [playground](https://www.babylonjs-playground.com/#31M2AP#119): https://www.babylonjs-playground.com/#31M2AP#119
- Expected result: The instanced mesh has its transformation properties updated.
- Current result: The instanced mesh has its position reset before it is moved again and transformation properties are not updated.

**Comment by CedricGuillemet** [comment]
Hi @julien-moreau ,
the PR is here : https://github.com/BabylonJS/Babylon.js/pull/8844
I also did some change to do a better support for right handed coordinates. If you could do some quick tests on that, it would be awesome!

**Comment by julien-moreau** [comment]
Merged ahah,
I’m testing ASAP thanks a lot !!!!!!
