### ISSUE TITLE
Inspector - Ability to extend with custom tools.

### ISSUE THREAD

**Issue by thomlucc** [BabylonJS/Babylon.js#8788]
Would be great to have the ability, with the official API, to add our own custom “tool sections" to the “tools” tab in the inspector. When creating a “custom tool section”, we should be able to specify buttons we can click to run our tools, maybe a couple of checkboxes/sliders/colorpickers for configuring them.
![image.png](https://images.zenhubusercontent.com/5dae4b4d14fb1000015c0e1e/4a77442d-faee-40e9-979a-177871f6cf9f)

**Comment by deltakosh** [comment]
Closing for now as we see no traction. Will reopen if required
