### ISSUE TITLE
BoundingBoxGizmo scaling is sometimes unexpected

### ISSUE THREAD

**Issue by nbduke** [BabylonJS/Babylon.js#8791]
Repro playground: https://www.babylonjs-playground.com/#VKJLY3

If you grab one of the corner scaling cubes closest to the camera and drag, the corner follows your mouse and the model scales up or down as expected. However, if you grab one of the corner scaling cubes furthest from the camera and drag, the corner moves the opposite direction from your mouse, so scaling goes the opposite way as well.

It must have something to do with your pointer going through the gizmo, since if you adjust the camera such that you can grab one of the back corners without clicking through the gizmo, everything works as expected.

**Comment by deltakosh** [comment]
Sorry @Popov72 :) Since @CedricGuillemet is on vacation I had to call you for help :D

**Comment by Popov72** [comment]
Np, having a look now that the bug on glb export is fixed!

**Comment by Popov72** [comment]
Fixed by #8829
