### ISSUE TITLE
NME - Expose to frame option appears after node removed from frame

### ISSUE THREAD

**Issue by PatrickRyanMS** [BabylonJS/Babylon.js#8794]
## Enhancement

- A node that has an exposable port (like the scale node) that is dragged to the canvas will not show an option to expose port to frame if it is not in a frame. 
- If the node is then placed within a frame, the node will now display an option to expose the port to the frame when the port is selected
- Moving that node outside the frame again should remove the option to expose the port to the frame since the node is no longer in a frame, but the port options still contain "expose port to frame"

We should check the state of a node (within a frame or not) when we populate the options when selected a port so that we aren't allowing the user to assign a port to a frame when there is no parent frame.

![image.png](https://images.zenhubusercontent.com/5dc2034af3f3b50001abf7aa/dc885e04-6e18-4423-83b5-e1bf08b9808d)

**Comment by sebavan** [comment]
Will be in the next nightly tomorrow :-) as fixed by PR above thanks @msDestiny14
