### ISSUE TITLE
load gltf error: loadAssets of unknown 	Materials

### ISSUE THREAD

**Issue by aboutqx** [BabylonJS/Babylon.js#8800]
Error `loadAssets of unknown 	Materials Name: Material__9`
Actually that's a anoymous material with no link to texture but some properties.

I'm using `BABYLON.SceneLoader.Append`

**Comment by aboutqx** [comment]
When add `babylon-loaders`, the normal babylon.js works fine, but the `babylon.max.js` still report succh errors.

**Comment by deltakosh** [comment]
Please use the forum for questions: forum.babylonjs.com
