### ISSUE TITLE
Sandbox - Incorrect texture colorspace with KTX 2 textures?

### ISSUE THREAD

**Issue by donmccurdy** [BabylonJS/Babylon.js#8808]
Testing the following model on https://sandbox.babylonjs.com/:

[CorsetKTX.glb.zip](https://github.com/BabylonJS/Babylon.js/files/5127404/CorsetKTX.glb.zip)

The model was created from the official corset sample, using the command:

```
gltf-transform etc1s Corset.gltf CorsetKTX.glb
```

That command is internally using `toktx` with mostly default settings:

```
toktx --genmipmap --bcmp tmp1.ktx2 tmp2.png
```

The result is washed out, which leads me to think the colorspace is wrong. The original file looks fine in the sandbox, so it seems to be just related to KTX. The KTX version looks correct in my viewer, https://gltf-viewer-experimental.donmccurdy.com/. Note that only the "-experimental" version of my viewer has KTX support so far.

- Expected result:
![Screen Shot 2020-08-25 at 8 18 36 PM](https://user-images.githubusercontent.com/1848368/91251382-2d140080-e710-11ea-84ab-8a907e5c221a.png)

- Current result:
![Screen Shot 2020-08-25 at 8 18 57 PM](https://user-images.githubusercontent.com/1848368/91251396-3735ff00-e710-11ea-8276-a72c19a699b4.png)

/cc @bghgary

**Comment by Popov72** [comment]
Thanks for the report!

We are currently rewriting the KTX2 loader (#8775), the fix will be in that PR.

**Comment by thomlucc** [comment]
Fixed
