### ISSUE TITLE
GLTF Serializer - add a filter to remove unused dynamic textures

### ISSUE THREAD

**Issue by jblazier** [BabylonJS/Babylon.js#8809]
When we export a scene via GLTF2Export.GLTFAsync, dynamic textures that are not in use by any exported nodes show up in the exported files (referenced in the GLTF and listed as png's). There does not appear to be a way to filter those out.

It would be nice to have a filter, similar to the node filter, that allows us to prevent textures from exporting (or some other solution that prevents our unneeded textures from exporting)

**Comment by deltakosh** [comment]
Please use the forum for discussion first as it is stated in the issue template
