### ISSUE TITLE
Spotlights and spot light shadows incorrect when useRightHandedSystem = true

### ISSUE THREAD

**Issue by kevinsbennett** [BabylonJS/Babylon.js#8813]
**Repro**
- https://playground.babylonjs.com/#B48X7G#32
this is existing shadow test provided by the docs with the only change being useRightHandedSystem is set to true.  

- Expected result:  The spotlights should be illuminating the boxes.
- Current result:  The spotlight is pointing in the wrong direction.  Note that if you flip the direction of the spot lights (which you shouldn't have to do), it will illuminate the boxes, but with no shadows.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser:  Chrome
 - Version: 84

**Additional context**
Point lights also appear to have a bug with useRightHandedSystem = true

**Comment by deltakosh** [comment]
I'm having a look right now
