### ISSUE TITLE
[WebXR] Adding the possibility to list objects that cannot be crossed by the ray

### ISSUE THREAD

**Issue by cstfan** [BabylonJS/Babylon.js#8831]
Adding the possibility to list objects that cannot be crossed by the ray

**Discussion**
https://forum.babylonjs.com/t/webxr-prohibit-teleportation-through-the-wall/13745/2

**Comment by RaananW** [comment]
Partly implemented in #8855 , to be tested and improved. leaving the ticket open.

**Comment by thomlucc** [comment]
Done and merged :-)
