### ISSUE TITLE
pirates game demo on babylonjs website doesn't work on MacOs Catalina

### ISSUE THREAD

**Issue by macakmujo** [BabylonJS/Babylon.js#8840]
**Use Github issues ONLY for validated bugs. PLEASE DISCUSS THEM ON THE FORUM FIRST!**

We have a really active forum to help answering questions (https://forum.babylonjs.com/)

*If you are convinced that you found a bug, please use the following template for your issue:*

**Repro**
- Bug repro on http://race.assassinscreedpirates.com/
- Expected result: game loaded
- Current result: not loaded

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOs Catalina
 - Browser any browser.  - Chrome Version 84.0.4147.135 (Official Build) (64-bit)

**Smartphone (please complete the following information):**

**Additional context**

**Comment by deltakosh** [comment]
This is a link to an external site unfortunately that we do not own

**Comment by macakmujo** [comment]
ok thx

looks like it is not compatible with new version of babylon,

bunch of errors in console


Babylon is very cool, I am new to 3d and like it very much Thanks
