### ISSUE TITLE
Safari: programmatic call to PointerDragBehavior.startDrag() doesn't work

### ISSUE THREAD

**Issue by mattdmorgan** [BabylonJS/Babylon.js#8850]
0) Open https://www.babylonjs-playground.com/#9UFEBE#108 on Safari. (It attaches a PointerDragBehavior to the sphere and calls startDrag on it.)
1) Mouse over the rendered area.
Result: Nothing happens.
Expect: Sphere to follow the mouse.

Works as expected in Chrome.

From debugging, it looks like it gets hung up in the POINTERMOVE handler of PointerDragBehavior, in the condition for updating the default _AnyMouseID value of currentDraggingPointerId to the next-moved pointerId (https://github.com/BabylonJS/Babylon.js/blob/7049f6d78ac9093985c38ee6204f8cc2a0b85de5/src/Behaviors/Meshes/pointerDragBehavior.ts#L206). Specifically, the pointer event has no pointerType. Thus currentDraggingPointerId is never updated and the later condition for calling _onMoveDrag is never satisfied.

**Comment by sebavan** [comment]
ohhh I ll have a look today @mattdmorgan is the issue on IOS or Mac or both ??? just to better target the fix.

**Comment by sebavan** [comment]
ok it repoes on desktop as well, I hope to have a fix shortly
