### ISSUE TITLE
TextBlock truncation puts commas between characters

### ISSUE THREAD

**Issue by mattdmorgan** [BabylonJS/Babylon.js#8862]
Title says it all. Playground example: https://www.babylonjs-playground.com/#M0EBV0#27 .

The culprit is this line: https://github.com/BabylonJS/Babylon.js/blob/5202b12514ac13d535e83be365ec7abd3e30df53/gui/src/2D/controls/textBlock.ts#L433
Calling `join` without an argument joins with commas.

**Comment by sebavan** [comment]
@Popov72, would be amazing if you could have a look ?
