### ISSUE TITLE
Cant interact with GUI.Button.CreateSimpleButton in WebXr immersive-ar mode.

### ISSUE THREAD

**Issue by ankitcsr** [BabylonJS/Babylon.js#8879]
Cant click on GUI button created using BABYLON.GUI.Button.CreateSimpleButton in WebXr ‘immersive-ar’ sessionMode mode .
Check out the playground (link below), its working fine in normal mode but in AR isn't working.

https://www.babylonjs-playground.com/#XCPP9Y#3651.

**Comment by sebavan** [comment]
@RaananW will have a look shortly after the week end as he is our own V/A/X R hero
