### ISSUE TITLE
[XR] onHitTestResultObservable always gives non zero results.length 

### ISSUE THREAD

**Issue by ankitcsr** [BabylonJS/Babylon.js#8887]
hitTest.onHitTestResultObservable.add((results) => {
if (results.length) {
dot.isVisible = true;
results[0].transformationMatrix.decompose(
dot.scaling,
dot.rotationQuaternion,
dot.position
);
} else {
dot.isVisible = false;
}
});

In above code (taken from  [ hit-test example](https://doc.babylonjs.com/how_to/webxr_augmented_reality#hit-test) ) its never going in else part .

In WebXRHitTest.ts.
Its notifying when results.length is non zero.
if (results.length) {
this.onHitTestResultObservable.notifyObservers(results);
}

**Comment by sebavan** [comment]
Refering to https://forum.babylonjs.com/t/webxr-onhittestresultobservable-always-gives-non-zero-results-length/13945/4

**Comment by RaananW** [comment]
Just wanted to add that this is not bug, it's by design.
