### ISSUE TITLE
Second example of "Create Compound Bodies" is broken

### ISSUE THREAD

**Issue by fabienrohrer** [BabylonJS/Babylon.js#8888]
From the page ["Create Compound Bodies"](https://doc.babylonjs.com/how_to/compounds), open [the second playground example](https://www.babylonjs-playground.com/#492ZK0#12). The skull is not affected by physics and remains still in the air much above the ground.

**Comment by CedricGuillemet** [comment]
I'm on it!

**Comment by CedricGuillemet** [comment]
Reassigning to @RaananW as it's related to previous changes.
