### ISSUE TITLE
API missing to get joint feedback

### ISSUE THREAD

**Issue by fabienrohrer** [BabylonJS/Babylon.js#8890]
If I'm not wrong, it's currently not possible to get an hinge joint angle/a slider joint distance without computing it manually. This is annoying. Having a set of functions, such as `HingeJoint.getAngle()` or `PrismaticJoint.getDistance()` would be welcome.

**Comment by sebavan** [comment]
Please use the forum first for questions, we keep Github only for validate issues or feature requests.

**Comment by sebavan** [comment]
Ping @RaananW  and @CedricGuillemet  FYI

**Comment by fabienrohrer** [comment]
👍 My apologies, I will use the forum..

**Comment by sebavan** [comment]
no problem, it is just to help the community :-)

**Comment by sebavan** [comment]
I kept the one which were pretty fishy open, so the other ones could be discussed there first.
