### ISSUE TITLE
Compound impostors does not support hierarchy

### ISSUE THREAD

**Issue by fabienrohrer** [BabylonJS/Babylon.js#8891]
When creating a compound impostor, it may be interesting to support a "transformNode" / "transformed empty mesh" hierarchy. To illustrate this, I expect that this modification of the [third playground example](https://www.babylonjs-playground.com/#492ZK0#8) of the [compound body page] should work:

```js
// Create a compoundBody and add all children
var compoundBody = new BABYLON.Mesh("", scene);
skull.parent = compoundBody;
var intermediateNode = new BABYLON.Mesh("", scene); // This has been added.
intermediateNode.rotation.x = Math.PI/5; // This rotation is problematic!!
box.parent = intermediateNode;
intermediateNode.parent = compoundBody;
sphere.parent = compoundBody;
compoundBody.position.y+=3;
compoundBody.rotation.x = Math.PI/5;
compoundBody.rotation.z = Math.PI/6;
```

**Comment by sebavan** [comment]
Please use the forum first for questions, we keep Github only for validate issues or feature requests.

Ping @CedricGuillemet  and @RaananW  FYI
