### ISSUE TITLE
[XR] Lighting Estimation Feature

### ISSUE THREAD

**Issue by ankitcsr** [BabylonJS/Babylon.js#8904]
https://immersive-web.github.io/lighting-estimation/

**Comment by brianzinn** [comment]
I've started a branch:
https://github.com/brianzinn/Babylon.js/commit/ebd1f40ac64f4acbd924b9d3486c4c181bd0a3e6

I'll work to get the `getReflectionCubeMap` and `LightingEstimate` (`primaryLightDirection`/`primaryLightIntensity` and `sphericalHarmonicsCoefficients`).

I will get the XR feature to the point of making the data available.  One thing to note is that I think the babylon SphericalHarmonics is to order^2 and I think it would need to support order ^3 with the 27 element array, but I haven't checked thoroughly.
