### ISSUE TITLE
Turning off glTF validation doesn't work in the the playground inspector

### ISSUE THREAD

**Issue by bghgary** [BabylonJS/Babylon.js#8925]
See https://forum.babylonjs.com/t/gltf-loader-binary-file-is-loaded-twice/14069/4

**Repro**
- Bug repro on [playground](https://playground.babylonjs.com): https://www.babylonjs-playground.com/#JA1ND3#48
- Open the inspector to the glTF Loader
- Deselect Validate
- Click Run to refresh

Expected result: glTF validation is turned off
Current result: glTF validation is still on

**Comment by deltakosh** [comment]
you are looking at it?

**Comment by bghgary** [comment]
Not yet. If someone has time, feel free to take it.

**Comment by deltakosh** [comment]
ok let's see who will have time first

**Comment by bghgary** [comment]
Lol, this line: https://github.com/BabylonJS/Babylon.js/blob/master/inspector/src/components/actionTabs/tabs/tools/gltfComponent.tsx#L63
