### ISSUE TITLE
NME: Mode switching UX broken when node material attached to a scene

### ISSUE THREAD

**Issue by PatrickRyanMS** [BabylonJS/Babylon.js#8937]
**Bug**
When changing the mode of a node material in nme.babylonjs.com from a material to any other mode like procedural, you get a warning saying that changing modes will reset your shader and you will lose changes with a confirmation to continue with reset.

![image](https://user-images.githubusercontent.com/31326855/92963474-5da1ad00-f427-11ea-97d0-b4fa41798613.png)

When you open a node material in the editor from a PG or in the sandbox, if you try to change mode you do not get a warning about resetting your shader, and your shader does not reset. The mode remains on whatever you started with, material for example. 

**Repro**
- https://www.babylonjs-playground.com/#7QCYPB
- Open the node material editor from the selected node material
- Attempt to change the mode of the shader
- Expected result: We should get a warning about resetting the shader and then once confirming, actually reset and switch modes
- Current result: Nothing happens when you try to change modes and the mode remains on whatever it started with.

Changing the mode of a shader in a PG will be destructive if the node material is not called the right way in code (like parsing a texture from a procedural texture node material) so it may be problematic to change the modes in a playground and may introduce instability into the PG. If this is the case, we should remove the ability to change modes in nme when the shader is attached to a scene, and instead just list what mode the shader is in when attached to a scene.

**Comment by deltakosh** [comment]
So you have the warning but it is displayed on the wrong window :)

**Comment by deltakosh** [comment]
It is on the PG window. I will fix that
