### ISSUE TITLE
Inspector/Animation Curve Editoy CSS rule being applied to document body

### ISSUE THREAD

**Issue by richardsdev** [BabylonJS/Babylon.js#8946]
As discussed on the forum: https://forum.babylonjs.com/t/latest-es6-versions-of-babylon-and-inspector-css-rule-being-injected-into-body-by-inspector/

The inspector in v 4.2 alpha is injecting a CSS rule into the document body instead of being applied to a specific class or element ID used by the inspector. The rule appears to be set in this SCSS file: inspector/src/components/actionTabs/tabs/propertyGrids/animations/curveEditor.scss on lines 1 to 3.

**Comment by deltakosh** [comment]
Yep. this is taking FOREVER to get fixed so I'll do it :)

Thanks @richardsdev

**Comment by deltakosh** [comment]
Will be live in a hour or so
