### ISSUE TITLE
Baked animation support

### ISSUE THREAD

**Issue by NonLinearGuy** [BabylonJS/Babylon.js#8966]
Hey, It turns out skeletal animation takes big chunk of time from every frame since all transformations for each bone has to be calculated. The idea of baked animation is simple, let's say you have an Idle animation of 30 FPS and for each frame you will calculate and save all the transformations for bones in either a JSON/RAM and use those to play animation. This will cut down the overhead of computing those for every frame.

Many modern engines support it.  here's a unity thread... https://answers.unity.com/questions/1353202/baked-animations-what-does-it-mean-for-unity.html

Thanks.

**Comment by Popov72** [comment]
Thread in the forum: https://forum.babylonjs.com/t/baked-animation-support/14161/20

**Comment by thomlucc** [comment]
Done and documented: https://doc.babylonjs.com/divingDeeper/animation/baked_texture_animations
