### ISSUE TITLE
Add serializer support for KHR_Materials_Specular

### ISSUE THREAD

**Issue by Drigax** [BabylonJS/Babylon.js#8968]
See forum post: https://forum.babylonjs.com/t/babylon-editor-export-texture-scaling/12723/26

Reproducible via playground: https://playground.babylonjs.com/#DHZKGW#7

Currently when we export specularGlossiness PBRMaterials via `_GLTFMaterialExporter._convertSpecularGlossinessTexturesToMetallicRoughnessAsync`

We combine albedo + glossiness textures into Base64 texture string, stripping all extension information.

~~This should probably be changed to bake transform information before combining the textures.~~

**Comment by Drigax** [comment]
Currently we convert spec gloss to metal rough, however we probably should export glossiness factors/textures as part of our support for [KHR_materials_specular](https://github.com/KhronosGroup/glTF/pull/1719/files?short_path=1131ec6#diff-1131ec600160968ecced71a9ae53cd5f)

**Comment by Drigax** [comment]
Changing the title to represent this, I'd rather do this right, and have a more futureproof solution than making a half measure to fix a specific issue. Recategorizing as our support for KHR_materials_specular in our serializers.

**Comment by supk1a1** [comment]
I can take a try at this

**Comment by sebavan** [comment]
Nice !!!! thanks a lot !!!
