### ISSUE TITLE
Light position changed when exporting to glb in sandbox

### ISSUE THREAD

**Issue by AhdaiDawn** [BabylonJS/Babylon.js#8976]
I imported a glb file with a light in the sandbox, then exported it to a new glb file(**no modification**). When I imported the new file again, I found that the light position changed.

**Screenshots**
1.  
![image](https://user-images.githubusercontent.com/26542474/93304986-73044600-f830-11ea-9997-7aad640515d7.png)
2.
![image](https://user-images.githubusercontent.com/26542474/93305010-7dbedb00-f830-11ea-8cd2-3c9bb2003cb8.png)

**Desktop:**
 - OS: windows 10 professional 1909
 - Browser [chrome]

I suppose the question located at here:
https://github.com/BabylonJS/Babylon.js/blob/15804eb5e9c5d5562fad3c5a8167ddc22ddd8431/serializers/src/glTF/2.0/Extensions/KHR_lights_punctual.ts#L148
When I commented out the lines related to the transformations , it seemed to work fine.

**Comment by deltakosh** [comment]
Please start a discussion on the forum first:) Unless you want to send a PR to fix it?
