### ISSUE TITLE
Expose "major performance caveat" for WebGL context

### ISSUE THREAD

**Issue by MiiBond** [BabylonJS/Babylon.js#9019]
When a device falls back to a software implementation (like Swift Shader), there is a flag that you can specify when creating a context to determine if this has happened (or if there is going to be a major performance issue for another reason).

It would be nice if Babylon could query this at startup so that the app can have this info and disable features as appropriate.

I do this right now with:
```
    var canvas: HTMLCanvasElement = document.createElement("CANVAS") as HTMLCanvasElement;
    canvas.width = 1;
    canvas.height = 1;
    document.body.appendChild(canvas);
    var gl = canvas.getContext('webgl', { failIfMajorPerformanceCaveat : true });
    canvas.remove();

    if (!gl) {
        this.hasMajorPerformanceCaveat = true;
    }
```

**Comment by deltakosh** [comment]
That is an option we can expose on the engine options. I will add it asap!

**Comment by deltakosh** [comment]
Quick question though: How do you detect a software implementation?

**Comment by deltakosh** [comment]
I will add a new Engine.IsHardwareSupported that will do the check
So software rendering will be Engine.IsSupported  && !Engine.IsHardwareSupported

**Comment by MiiBond** [comment]
This major performance caveat test isn't specifically for software rendering. From the spec:
`Context creation will fail if the implementation determines that the performance of the created WebGL context would be dramatically lower than that of a native application making equivalent OpenGL calls.`

This can be due to falling back to a software renderer or any other reason for potential slow performance. The spec gives the following other example:
`An implementation might require reading back the framebuffer from GPU memory to system memory before compositing it with the rest of the page, significantly reducing performance.`

**Comment by deltakosh** [comment]
Would you prefer to rename IsHardwareSupported to IsPerformant? Betternaming idea?

**Comment by deltakosh** [comment]
Or simply HasMajorPerformanceCaveat  :) yeah will do that !

**Comment by MiiBond** [comment]
Yeah, that sounds perfect! Thanks!
