### ISSUE TITLE
[XR]Ray's angle is not correct.

### ISSUE THREAD

**Issue by VTFLAB** [BabylonJS/Babylon.js#9022]
![screenshot_0_20200923-183212](https://user-images.githubusercontent.com/10072114/93998202-30fa7780-fdcf-11ea-9f30-32814ce58d16.png)

Controller angle is correct but Ray's angle is wrong.
Do you plan to fix this, or is there a way to specify the property?
I looked at the documentation for a few hours and I didn't discover it.

**Comment by deltakosh** [comment]
Please open a thread on the forum first :)
