### ISSUE TITLE
depth-of-field glitch

### ISSUE THREAD

**Issue by stephanedemotte** [BabylonJS/Babylon.js#9032]
Hello

We can see a 1 pixel circle when we play with `aperture` and `distorsion`

Can we do something to avoid it ?

[Playground](https://www.babylonjs-playground.com/#DX6AV#4) founded in the [doc](https://doc.babylonjs.com/how_to/using_depth-of-field_and_other_lens_effects) 

<img width="908" alt="Screen Shot 2020-09-24 at 7 08 10 PM" src="https://user-images.githubusercontent.com/2158130/94209074-6370a700-fe99-11ea-827b-6be656a04cbf.png">

Thank you !

**Comment by deltakosh** [comment]
Please use forum for question as stated in the issue template
