### ISSUE TITLE
Babylon.js does not work on iOS 14.2 Safari browser

### ISSUE THREAD

**Issue by StephenWeiXu** [BabylonJS/Babylon.js#9037]
**Use Github issues ONLY for validated bugs. PLEASE DISCUSS THEM ON THE FORUM FIRST!**

We have a really active forum to help answering questions (https://forum.babylonjs.com/)

*If you are convinced that you found a bug, please use the following template for your issue:*

# Bugs

- Bug repro on [playground](https://playground.babylonjs.com): 
    * Upgrade iOS to 14.2 via Apple beta program
    * Open Safari browser on iPhone with iOS 14.2, and go to https://playground.babylonjs.com
- Expected result: page loads
- Current result: page doesn't load with Error `A problem repeatedly occurred on https://playground.babylonjs.com/`

**Note**:
* I am on iOS 14.2 (iOS beta version). Need to enroll Apple beta program to upgrade iOS to 14.2 as of now
* This is affecting our product which uses Babylon as well. But since Babylon playground also doesn't work on iOS 14.2, getting the site work should probably help with external usage of Babylon.js as well

![Screen Shot 2020-09-25 at 3 20 22 PM](https://user-images.githubusercontent.com/8272863/94309625-5d84cf80-ff46-11ea-93c7-9dc9b51c94d7.png)

**Comment by deltakosh** [comment]
I wonder what is unclear in that sentence: "**Use Github issues ONLY for validated bugs. PLEASE DISCUSS THEM ON THE FORUM FIRST!**"
