### ISSUE TITLE
Universal Scalar UpdateGizmoRotationToAttachedMesh resulting in reverse behavior

### ISSUE THREAD

**Issue by davesauce14** [BabylonJS/Babylon.js#9053]
When setting the below property to true. The Uniform scalar behaves in the opposite manner after rotating 90 degrees.

`gizmoManager.gizmos.scaleGizmo.uniformScaleGizmo.updateGizmoRotationToMatchAttachedMesh = true;`

Steps to recreate:

[Uniform scalar bug repro](https://www.babylonjs-playground.com/#8MGKWK#338)

- load scene, 
- rotate any mesh 90 degrees,
- press "r" to load the scaling tool,
- drag the uniform scalar up to increase the scale of the object.
- You will notice that the scale decreases instead of increases.

Expectation:
Regardless of the rotation of the universal scalar, dragging "up" will increase the scale, dragging "absolute down" will decrease the scale of the mesh.

Babylon Version 4.1

**Comment by deltakosh** [comment]
As mentioned in the template, please use the forum first...

**Comment by davesauce14** [comment]
Hi @deltakosh, here is the topic:

[Babylon Forum Topic](https://forum.babylonjs.com/t/universal-scalar-update-rotation-flag-resulting-reverse-behavior/14529)

**Comment by deltakosh** [comment]
Sure but there was no discussion :)
