### ISSUE TITLE
Support for info/event data on GUI control events (passing pointerType)

### ISSUE THREAD

**Issue by Exolun** [BabylonJS/Babylon.js#9067]
Lately we've been working on some feature areas to support Touch interaction, but the events on the Babylon GUI `Control` classes such as `onPointerEnterObservable` and `onPointerClickObservable` we don't have a `PointerEvent` passed through, so there doesn't seem to be a way to identify whether a given pointer event originated from a touch device or not.

Is there a workaround for this?  Either way it would be nice if the pointer events in the base `Control` class shared a base class that propagated the `PointerEvent` or perhaps a full `PointerInfo` object much like the `scene.onPointerObservable` event does. 

Thanks!

**Comment by deltakosh** [comment]
OK I will push an update that will store the pointerinfo in the observable state:
```
button.onPointerClickObservable.add((evt, state) => {
        console.log(state)
    })
```

Which will output:
![image](https://user-images.githubusercontent.com/1306056/94870155-b26b8e80-03fb-11eb-9f92-8c66aa284ad6.png)

**Comment by Exolun** [comment]
Very nice!  Thank you
