### ISSUE TITLE
Array.from errors when running in IE11

### ISSUE THREAD

**Issue by bghgary** [BabylonJS/Babylon.js#9122]
Array.from is not supported in IE11. There are a bunch of usages in the code that should be replaced. Some of them can be replaced with Tools.Slice, but some of them cannot.

This [PR](#9119) was an attempt at fixing using Tools.Slice, but it doesn't compile for some cases since it was converting a typed array to a regular array.

**Comment by syntheticmagus** [comment]
#9123 addresses this for at least the one easy case.
