### ISSUE TITLE
[SAFARI] MP3 not played with latest Safari

### ISSUE THREAD

**Issue by CedricGuillemet** [BabylonJS/Babylon.js#9125]
Forum thread : https://forum.babylonjs.com/t/new-audio-problem-after-os-update-on-safari-browser-desktop/14714
mp3 not played in bjs with Safari Version 14.0 (15610.1.28.1.9, 15610)

PG https://playground.babylonjs.com/#EAC5RK

**Comment by sebavan** [comment]
@CedricGuillemet the samples in the playground of the sound category are exhibiting the same behavior

**Comment by lucastwong** [comment]
@CedricGuillemet @sebavan Update to the new iOS 14.0.1, and mp3 sounds in any BabylonJS program no longer works in any browser. This is a serious issue!

**Comment by sebavan** [comment]
@CedricGuillemet let me know if you found a workaround that we could add in for the release ?
