### ISSUE TITLE
Add camera serialization to GLTF serializer

### ISSUE THREAD

**Issue by Drigax** [BabylonJS/Babylon.js#9146]
See:
https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#cameras

**Comment by daoshengmu** [comment]
I am working on this now. The new spec of Camera, https://www.khronos.org/registry/glTF/specs/2.0/glTF-2.0.html#cameras

**Comment by sebavan** [comment]
@daoshengmu you rock !!!

**Comment by feuersteiner** [comment]
Docs on this are out of date. I personally have been using the camera exported for a while.
link to docs: https://doc.babylonjs.com/features/featuresDeepDive/Exporters/glTFExporter

**Comment by sebavan** [comment]
Thanks a lot for the report, @feuersteiner do you want to submit a PR there or do you prefer me to update ?
