### ISSUE TITLE
Dragging from the Reflection input port of the PBR node creates a non-usable Reflection node

### ISSUE THREAD

**Issue by PirateJC** [BabylonJS/Babylon.js#9166]
Inside NME, starting with the PBR Node, if you drag out from the reflection input port, a reflection node is added to the graph, however the reflection node that is added seems to be broken. You cannot hook up any values to it's input ports. 

A reflection node that is brought in from the node list on the left does not have this problem. It comes in just fine. So the issue seems to exist when a reflection node is added while dragging out from the input port of the PBR node.

**Comment by Popov72** [comment]
Fixed by #9179
