### ISSUE TITLE
Update PBR NME Design

### ISSUE THREAD

**Issue by sebavan** [BabylonJS/Babylon.js#9177]
As discussed with @PirateJC and @PatrickRyanMS here is the list of functional changes to bring into the PBR nodes:
- [ ] Remove the reflectivity node and inject metallic, roughness as first class citizen of the main node
- [ ] Remove the AO node and inject the AO into the main node
- [ ] Always reuse view from the main node so we can remove it from all "satellite nodes"
- [ ] Remove all textures from "satellite nodes" but the bump ones
- [ ] Move view up near the other positions info
- [ ] Group the new metallic roughness AO parameters with the base color

The visual  changes will come in a separate issue to refine UX.

**Comment by deltakosh** [comment]
this will break all samples and PG

**Comment by deltakosh** [comment]
(I mean: we will need to update doc, tests and samples)
