### ISSUE TITLE
Custom Frames Load In Broken

### ISSUE THREAD

**Issue by PirateJC** [BabylonJS/Babylon.js#9181]
Custom Frames are loading broken. After exporting a frame, and reimporting it in collapsed mode it's showing broken ports:

![image.png](https://images.zenhubusercontent.com/5dcb34efa1442a0001945170/cc014f5e-bcf5-40de-998f-fd17538ca1bc)

In expanded mode it looks like this:

![image.png](https://images.zenhubusercontent.com/5dcb34efa1442a0001945170/07fd15b6-54ec-48b8-b446-e310f8108ab9)

You can repro this with the following NME Session:
https://nme.babylonjs.com/#HVMGZ9#1

Draw a frame around these nodes:
![image.png](https://images.zenhubusercontent.com/5dcb34efa1442a0001945170/1ad6b5da-57de-490c-9988-3e023b2df11b)

Collapse the frame:
![image.png](https://images.zenhubusercontent.com/5dcb34efa1442a0001945170/42438031-c472-471a-a9ff-6e1664c41ed5)

Export the frame and reimport and it will look like this:
![image.png](https://images.zenhubusercontent.com/5dcb34efa1442a0001945170/2047c3a8-8a44-4696-bb82-dd1af23f8c78)

**Comment by msDestiny14** [comment]
After discussing. Only work that needs to have is the reupdate once the node is reconnected.
