### ISSUE TITLE
Issue when taking a screenshot with multi-cameras

### ISSUE THREAD

**Issue by gabrielheming** [BabylonJS/Babylon.js#9201]
The method [BABYLON.ScreenshotTools.CreateScreenshotUsingRenderTarget](https://doc.babylonjs.com/api/classes/babylon.screenshottools#createscreenshotusingrendertarget) is not respecting the selected render target when the scene has multiple cameras.

[Playground demo](https://www.babylonjs-playground.com/pg/E9IRIF/revision/266).

Line 82-89 has the following method:

```
BABYLON.ScreenshotTools.CreateScreenshotUsingRenderTarget(
    engine,
    camera1,
    { width: engine.getRenderWidth(), height: engine.getRenderHeight() },
    (data) => {
        console.log(data);
    }
);
```

The `camera1` variable has the view from the upper box (big box). However, the result, is a screenshot using the last camera from the list of active cameras (`scene.activeCameras`).

Expected output:

![expected-output](https://user-images.githubusercontent.com/1536369/96351920-52453f80-10bf-11eb-8ef3-c278fc70c7e0.png)

Actual output:

![actual-output](https://user-images.githubusercontent.com/1536369/96351922-52ddd600-10bf-11eb-85a9-55ae7aa89294.png)

[BabylonJS Forum thread discussion](https://forum.babylonjs.com/t/issue-when-taking-a-screenshot-with-multi-cameras/14964)

**Comment by gabrielheming** [comment]
Seems that a new commit undone this fix. I'm reopening this issue.

**Comment by sebavan** [comment]
Fix by the latest PRs :-) will be in the next nightly thanks for reporting it
