### ISSUE TITLE
Need to expose blend mode on NME preview window when in Particle Mode.

### ISSUE THREAD

**Issue by PirateJC** [BabylonJS/Babylon.js#9218]
We need to have an option to change the blend mode of the particles in the preview window of NME, when NME is set to particle mode. This will allow the user to see proper representation of their particle effect.

@PatrickRyanMS - for the design
@msDestiny14 - for the implementation

**Comment by deltakosh** [comment]
I can do the implementation as soon as we have a design

**Comment by deltakosh** [comment]
Here we are
![image](https://user-images.githubusercontent.com/1306056/107078393-24395780-67a3-11eb-9245-d4e2fe3100cd.png)

**Comment by PirateJC** [comment]
Awesome!!!!
