### ISSUE TITLE
NME Not updating preview window

### ISSUE THREAD

**Issue by msDestiny14** [BabylonJS/Babylon.js#9220]
Under certain circumstances, the NME preview window shows "Please wait loading..." This is then fixed as soon as any property of a node or the node material is updated. 

Confirmed circumstances: 
 -when something is loaded into NME: a new NME file, frame etc.

Unconfirmed circumstances:
-Loading into NME?

**Comment by sebavan** [comment]
@msDestiny14 can we close this one now the PR has been merged ?
