### ISSUE TITLE
 A question about blendMode of particle effects

### ISSUE THREAD

**Issue by catdoc** [BabylonJS/Babylon.js#9254]
![babylon_particlesystem](https://user-images.githubusercontent.com/4272019/96952155-fdc90800-14a2-11eb-9aa2-bf8a5ccd5859.png)

The code screenshot above is quoted from [here](https://github.com/BabylonJS/Babylon.js/blob/master/src/Particles/particleSystem.ts)

When the blendmode of the particle is BLENDMODE_MULTIPLYADD, is the code in the red box correct?

Is an else missing after the If statement ？

**Comment by sebavan** [comment]
Yup it definitely looks like a bug, I ll fix it asap, there should be a else statement here.

@deltakosh  FYI, so if I actually should not fix it, please ping me and I ll revert the change.
