### ISSUE TITLE
Collision detection doesn't support meshes without index array

### ISSUE THREAD

**Issue by RaananW** [BabylonJS/Babylon.js#9267]
See - https://forum.babylonjs.com/t/collision-problem-bug-with-gltf-mesh-without-indexes/14914

Playground to reproduce:

https://www.babylonjs-playground.com/#SYQW69#505

**Comment by sebavan** [comment]
@Popov72 would you have a bit of bandwith to look into this one ? or should we move it to after 4.2 ?

**Comment by Popov72** [comment]
Trying to finish some things for WebGPU first.

As it's not a bug, I think we are not so much in a hurry(?)

**Comment by sebavan** [comment]
Yup definitely, no rush, let s do before the next bash of webgpu things but after this one :-)

**Comment by epajarre** [comment]
I sort of disagree with the "not a bug". As I see it it is: collision testing works, until it does not.....

I will be doing a workaround to my toolchain for creating the index buffers, this might be a little bit messy as am working with .glb to .glb translation.  

With a fast search I did not find a convertToIndexedMesh call in Babylonjs. (please correct me if I just missed it).

**Comment by deltakosh** [comment]
Yes I confirm the bug status. Please make sure to consider it as soon as possible
