### ISSUE TITLE
Add glow layer to right-click context menu for render pipeline. 

### ISSUE THREAD

**Issue by PatrickRyanMS** [BabylonJS/Babylon.js#9278]
**Enable the glow layer to be added/viewed without the need for a render pipeline**
We have the ability to create and use a glow layer in code without declaring a render pipeline. However, if a glow layer is declared without a render pipeline, there is no way to debug the glow layer in the inspector. It would be great to be able to see the glow layer much like we do with the render pipeline, and add a new one with the right-click context menu like we can with the full render pipeline. 

I am not sure what the exact implementation should be, but using our existing behavior as the basis to design this interaction would be the best. Here is a sample playground that enables the glow layer without a render pipeline for testing:

https://playground.babylonjs.com/#7QCYPB

**Comment by deltakosh** [comment]
Glow layer takes a list of meshes. How do you want to enable it with the inspector?

I think we can add a way to see the glow layer maybe but beside the glow layer intensity what do you want to debug?

**Comment by PatrickRyanMS** [comment]
Maybe to start, we just expose the glow layer with the intensity and blurKernelSize controls when there is already a glow layer in the scene that wasn't attached to a render pipeline. This PG is an example of that:

https://playground.babylonjs.com/#UUXABN#6

You can see the glow layer and change the parameters in code, but you cannot test anything live in the inspector. I would have assumed I would find it under the material image processing header in scene, but I can't find it anywhere in the inspector. 

Maybe we fall back on the fact that you can add a render pipeline to the scene in the inspector to get access to the glow layer for emission and close to 1 values, and that is how you add a glow layer in the inspector. But it would be good to be able to debug a glow layer created in code using only the inspector.

**Comment by deltakosh** [comment]
> Maybe to start, we just expose the glow layer with the intensity and blurKernelSize controls when there is already a glow layer in the scene that wasn't attached to a render pipeline. 

Deal!
