### ISSUE TITLE
Implement Quaternion.LookRotation

### ISSUE THREAD

**Issue by Alex-MSFT** [BabylonJS/Babylon.js#9293]
Unity provides a nice helper function [Quaternion.LookRotation](https://docs.unity3d.com/ScriptReference/Quaternion.LookRotation.html) to help create a look rotation quaternion vector for a given direction and normal.  This helps with operations such as orienting objects to face a specific direction along a fixed plane.

Babylon.js has a similar mesh.lookAt function but this has two limitations:
1. You can't lock the normal for the look direction
2. You can't perform this operation with just two vectors, as it requires operating against a mesh.

In the past I have implemented it using this algorithm: https://www.euclideanspace.com/maths/geometry/rotations/conversions/matrixToQuaternion/

**Comment by deltakosh** [comment]
Hello any news?

**Comment by Alex-MSFT** [comment]
Thanks for reminding me I have this issue assigned to me!  It got a bit lost on my personal backlog as I have been working on some other priorities.  I will try to prepare a PR for this soon.

**Comment by deltakosh** [comment]
Thanks a lot!
