### ISSUE TITLE
Gizmo Rotation demo broken, ribbon creation in 4.2.0 beta.19

### ISSUE THREAD

**Issue by muusssari** [BabylonJS/Babylon.js#9295]
**Repro**
https://playground.babylonjs.com/#7KX2R8#133
Rotating gizmo should rotate and move the object where gizmo is set

Right now there is bunch of ribbon creating errors when touching rotating gizmo. but other gizmos looks working fine.

**Desktop:**
 - OS: Windows 10
 - Browser Chrome Version 86.0.4240.111, Firefox 82.0.1

**Additional context**
Problem looks to be in new custom mesh, when setting it to be as gizmo.

**Comment by CedricGuillemet** [comment]
I'm on it ...
