### ISSUE TITLE
How to step up any distance

### ISSUE THREAD

**Issue by BoldBigflank** [BabylonJS/Babylon.js#9321]
**Repro**
- Related [playground](https://www.babylonjs-playground.com/#QAN9X5):
- Expected result: You should be able to move on top of the low cube
- Current result: Instead of stepping onto the low cube, you are thrown back from the low cube

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Firefox
 - Version Babylon 4.2.0-beta.21

**Additional context**
Discussed on the [forum](https://forum.babylonjs.com/t/how-to-step-up-any-distance/14253)

**Comment by deltakosh** [comment]
Answered on the forum
