### ISSUE TITLE
Can't render PCF shadows on iOS Safari with WebGL 2.0 enabled

### ISSUE THREAD

**Issue by nbduke** [BabylonJS/Babylon.js#9329]
I can repro this on iPad Pro running iOS 14.1, Safari version 14.0, *with the WebGL 2.0 experimental flag turned on*.

When I load [this Playground](https://playground.babylonjs.com/#1Z89KY#37), the planes that receive shadows fail to render. I haven't been able to get console logs on my device, but one of my colleagues tried a similar scenario on a different iPad and saw this in the logs:

"[Error] WebGL: ERROR: 0:90: 'sampler2DShadow' : declaration must include a precision qualifier for type\
compileShader\
[Error] WebGL: ERROR: 0:140: Invalid call of undeclared identifier '_ucomputeShadowWithPCF5'\
compileShader\
[Error] BJS - [15:51:33]: Unable to compile effect:\"

If you don't turn on that WebGL 2.0 flag, the Playground renders as expected. Alternatively, if you modify that Playground to remove the `usePercentageCloserFiltering` flag on the shadow generators, it renders as expected (see [this version](https://playground.babylonjs.com/#1Z89KY#39)).

The issue seems specific to the iPad Pro GPU because it doesn't repro on Mac Safari with WebGL 2.0 turned on.

**Comment by deltakosh** [comment]
yes and unfortunately this is not on us but due to incomplete webgl2 support on iOS. we cannot fix it on our side. We need to wait for apple to finish the work :(
