### ISSUE TITLE
ArcRotateCamera fails after setting the upVector

### ISSUE THREAD

**Issue by Bikeman868** [BabylonJS/Babylon.js#9352]
**Repro**
```
const camera = new BABYLON.ArcRotateCamera(
   "orbitalCamera",  0, 0, 0, new BABYLON.Vector3(0, 0, 0),
   scene, true);
camera.upVector = new BABYLON.Vector3(0, 0, 1);
camera.setPosition(0, 200, 0);
```
Set a breakpoint and inspect the camera. The `alpha`, `beta` and `radius` are all `NaN` and `position` is `undefined`.

- Expected result:
alpha = -pi/2
beta = pi/2
radius = 200

- Current result:
alpha = NaN
beta = NaN
radius = NaN

**Comment by Bikeman868** [comment]
See https://www.babylonjs-playground.com/#1A3M5C#158 for an example

**Comment by Popov72** [comment]
Not a bug, see answer in forum https://forum.babylonjs.com/t/arc-rotate-camera-relationship-to-axes/15393/11

**Comment by Bikeman868** [comment]
So, the problem is that `setPosition` takes a `Vector3` as input, so this was my error.
