### ISSUE TITLE
GUI Buttons and IFocusableControl

### ISSUE THREAD

**Issue by Flux159** [BabylonJS/Babylon.js#9378]
**Is your feature request related to a problem? Please describe.**
I'm trying to create a simple menu system (ported from code I wrote in Unity) with Babylon.js's GUI and while mouse events (& touch events with pep.js) are fairly well supported for buttons, making a GUI with keyboard navigation seems fairly complicated at the moment.

**Describe the solution you'd like**
Buttons that implement IFocusableControl would make it significantly easier to make keyboard navigation for menu systems (up/down, "focused cursor", enter). It seems like the current interface should be good enough to handle events with `processKeyboard`, `onFocus`, and `onBlur`. 

Independently, for usability it might be nice to also have a `focus()` & `blur()` functions that could handle `adt.focusedControl = this`, but that might require some additional changes to get a reference to the texture a button/control is rendered on (reference: https://forum.babylonjs.com/t/babylon-gui-focus/4526).

**Discussion**
https://forum.babylonjs.com/t/focusable-gui-buttons/1891

**Comment by deltakosh** [comment]
Hey this seems super fine to me

wanna do a PR?

**Comment by Flux159** [comment]
Started on this here: https://github.com/BabylonJS/Babylon.js/compare/master...Flux159:master - still testing out some basics right now, but have some usability questions before I cleanup the code and submit the pull request (these are also todos in my diff right now as well):

* Should there be a focus highlight color property? (would need to be optional to keep current API)
* Should there be a `isFocusable` property for a button? (Control already has `isFocusInvisible`, but not entirely clear what that does for buttons right now)
* Or should button be subclassed to a `FocusableButton` if this is going to change the logistics of using buttons?

Unrelated to these changes, just an overall question:
* When the HTML canvas is focused, should the adt/._host automatically focus the previously focused control?

Put up a video showing some debugging logging after adding the code here - https://imgur.com/a/wm91Xzw , was wondering if I should add a playground example or additional docs as part of this as well? Don't know if those have different contribution guidelines.

**Comment by deltakosh** [comment]
> Should there be a focus highlight color property? (would need to be optional to keep current API)

Yes I like it and yes please make if off by default

> Should there be a isFocusable property for a button? (Control already has isFocusInvisible, but not entirely clear what that does for buttons right now)

Actually isFocusInvisible == !isFocusable

> Similar to above question, but slightly different - should clicking (pointer down/up) the button focus the button? Or should that also be optional based on a boolean property?

I think so. It should focus it

> I was able to add a focus() and blur() function to button, should I do the same for inputText & add it as part of the IFocusableControl interface? Seems like every control has a ._host property that should make this easy.

Totally

> Should button be subclassed to a FocusableButton if all of this is going to change the logistics of using buttons?

Probably but I need to see the code implementation to be sure

> When the HTML canvas is focused, should the adt/._host automatically focus the previously focused control?

Yes!

And as you mentioned, we will need documentation updates as as much examples as you can provide 👍 
Thanks a ton!
