### ISSUE TITLE
How to submit my page to the "made with" section?

### ISSUE THREAD

**Issue by EdnaldoNeimeg** [BabylonJS/Babylon.js#9398]
I built a product customizer using FabricJS + BabylonJS and i'd like to show it in the "made with" section.
You can see the page [HERE](https://camisadimona.com.br/produto/caneca-acessorios-caneca?studio=true)

![screenshot-localhost_8080-2020 11 12-16_07_47](https://user-images.githubusercontent.com/6233059/98984788-6edb6880-2501-11eb-93ee-85eff315cd1b.png)

**Comment by deltakosh** [comment]
please open a thread on our forum @PirateJC  will help you from there ;D
