### ISSUE TITLE
ScreenSpaceReflections acting weird

### ISSUE THREAD

**Issue by praptoumache** [BabylonJS/Babylon.js#9399]
# Bugs

- Expected result: clean reflections
- Current result:
![image](https://user-images.githubusercontent.com/57391596/98990663-0b663080-252b-11eb-97b4-e8a74e5df245.png)

i am trying to achieve some realtime reflections on a room i am working on.
basically i used the commands provided by the examples in the docs.
as you can see - the reflections are shown numerous times.

can you guys provide some help ?

**Comment by deltakosh** [comment]
Please use our forum as stated in the issue template
