### ISSUE TITLE
Update playground to pull examples directly from search index

### ISSUE THREAD

**Issue by deltakosh** [BabylonJS/Babylon.js#9400]
https://babylonjs-newdocs.search.windows.net/indexes/playgrounds/docs?api-version=2020-06-30&$top=1000&api-key=820DCA4087091C0386B0F0A266710390&search=
 

Adding a search query will filter the data:
 
https://babylonjs-newdocs.search.windows.net/indexes/playgrounds/docs?api-version=2020-06-30&$top=1000&api-key=820DCA4087091C0386B0F0A266710390&search=collision

**Comment by RaananW** [comment]
Update this this - the current number of playgrounds in this search index is ca. 1400. We will mark 50-100 of them as "main", and you will be able to fetch them automatically. Search in the rest is always possible. 

Ticket for updating the `isMain` flag is here - https://github.com/BabylonJS/Documentation/issues/71

**Comment by deltakosh** [comment]
ok that sounds great!
I'll probably work on it after thanksgiving

**Comment by deltakosh** [comment]
Pinging @PirateJC to see if we can get a first list soon (ish) ?

**Comment by PirateJC** [comment]
Yes! Sorry for the delay! Planning on doing this tomorrow!

**Comment by RaananW** [comment]
The following query will provide the playgrounds marked as "main":

https://babylonjs-newdocs.search.windows.net/indexes/playgrounds/docs?api-version=2020-06-30&$top=1000&api-key=820DCA4087091C0386B0F0A266710390&$filter=isMain%20eq%20true

It will provide max 1000, but i doubt we will ever have more than that.

The results also have a category which can be used to group them and can be displayed (like "GUI", "Shadows", "VR/AR" and so on)
