### ISSUE TITLE
Error in Promise polyfill

### ISSUE THREAD

**Issue by Dimous** [BabylonJS/Babylon.js#9403]
Hello!
I noticed an incorrect code.
https://github.com/BabylonJS/Babylon.js/blob/70b81037140736c8dd3c53ed5ce35b4e78ffa69d/src/Misc/promise.ts#L74
`_resolve` method is void so the code in the if statement body would never be executed.

_I just wanted to port this polyfill to another language where there is no such concept as promise/future, if you are interested in how I ended up here :p_

**Comment by deltakosh** [comment]
Good catch! I'm gonna fix it asap
