### ISSUE TITLE
TypeScript: types incompatibilities

### ISSUE THREAD

**Issue by StanislavChankov** [BabylonJS/Babylon.js#9407]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
I want type unification.

**Discussion**
Currently there are many different cases that the same types are shown as differnt from `TypeScript`. Of course the issue is not in TypeScript, but instead how the classes are defined. Some examples:
Same `Scene` type <-> `BABYLON.Scene`. 
![image](https://user-images.githubusercontent.com/35253870/99188858-d9411280-2766-11eb-93e7-04bf54058d83.png)

This error is completly unacceptable for me. This makes the code not `TypeScript` ready.
![image](https://user-images.githubusercontent.com/35253870/99188897-0d1c3800-2767-11eb-9eb5-92af0365b71a.png)

`Material` <-> `StandardMaterial` issue:
![image](https://user-images.githubusercontent.com/35253870/99188963-78fea080-2767-11eb-964e-a6bd947e4b93.png)

`BaseTexture` <-> `BABYLON.Texture`
![image](https://user-images.githubusercontent.com/35253870/99189032-c5e27700-2767-11eb-89bb-852f292722b9.png)

And many more...

**Comment by deltakosh** [comment]
Well first you should have started the discussion on the forum as mentioned in the GitHub template.
So please go to forum.babylonjs.com

Also babylon.js is developed WITH typescript so it cannot be incompatible :)

So there must be something wrong with your setup and we will help you on the forum to fix it :D

**Comment by StanislavChankov** [comment]
I already created one, but the provided solution is not the expected one.
https://forum.babylonjs.com/t/how-to-manage-with-static-vs-non-static-members/15470/2

**Comment by deltakosh** [comment]
And so instead of replying on the thread you decided to create an issue on the repo?
