### ISSUE TITLE
Babylon 4.2: can Cardboard VR be supported without Google VR Services?

### ISSUE THREAD

**Issue by procedural** [BabylonJS/Babylon.js#9422]
Hi! Great 4.2 release, guys!

I have a question / feature request: can Babylon.js support Cardboard VR without Google VR Services?

Here's how it looks when I try the first VR example from Getting Started:

https://doc.babylonjs.com/start/chap8/vr

![Screenshot_20201117-220019](https://user-images.githubusercontent.com/28234322/99435504-413b5880-2921-11eb-89e9-b9b8e8e90331.png)

When I click that goggles button, it redirects me to Google VR Services app that is not supported on my device:

![Screenshot_20201117-220024](https://user-images.githubusercontent.com/28234322/99435663-7e9fe600-2921-11eb-9190-41f750e2349f.png)

![Screenshot_20201117-220040](https://user-images.githubusercontent.com/28234322/99435696-89f31180-2921-11eb-98fe-fe76fc2b85b3.png)

But the problem is: I can run Cardboard VR just fine without Google VR Services installed:

![Screenshot_20201117-215912](https://user-images.githubusercontent.com/28234322/99435780-aa22d080-2921-11eb-8156-cb65d29b8b7d.png)

Is it possible to enable Cardboard VR mode without Google VR Services?

The google code for their Cardboard VR app that works without Google VR Services is open source, by the way: https://github.com/googlevr/cardboard

Thanks!

**Comment by deltakosh** [comment]
Hello! do you mind asking the question on the forum?

Thanks a lot

@RaananW  FYI

**Comment by procedural** [comment]
@deltakosh sure! Though it's sort of a feature request, if Cardboard VR can't be activated without the Google VR Services app.

**Comment by deltakosh** [comment]
anyway. we recommend forum discussion for everything (as stated in the github issue template)
