### ISSUE TITLE
PBRSpecularGlossiness materials are excluded from export

### ISSUE THREAD

**Issue by Drigax** [BabylonJS/Babylon.js#9423]
See:
https://forum.babylonjs.com/t/spec-gloss-material-to-gltf-glb/15652/3

Currently we only export PBRMaterial, PBRMetallicRoughnessMaterial, and StandardMaterial.

We should either A) create some material conversion functionality to export PBRSpecularGlossinessMaterial as PBRMaterial, or reimplement the PBRSpecularGlossiness export codepath.

**Comment by bghgary** [comment]
Both PBRMaterial, PBRMetallicRoughnessMaterial, and PBRSpecularGlossinessMaterial derives from PBRBaseMaterial. I wonder if you can just export PBRBaseMaterial?
