### ISSUE TITLE
Create Legacy Material Converters

### ISSUE THREAD

**Issue by Drigax** [BabylonJS/Babylon.js#9424]
This was inspired by #9423

Currently we don't have any explicit codepaths to convert PBRMetallicRoughnessMaterail or PBRSpecularGlossinessMaterial to PBRMaterial. This might be worth looking into to remove pain points for those using the legacy materials in their serialized scenes, when trying to take advantage of future functionality.

**Comment by deltakosh** [comment]
cc @sebavan  for info

**Comment by bghgary** [comment]
Closing since we don't actually need this and it is covered by PBRBaseMaterial.
