### ISSUE TITLE
Enable IME in inputtext

### ISSUE THREAD

**Issue by shota-inoue** [BabylonJS/Babylon.js#9428]
**Is your feature request related to a problem? Please describe.**

I would like to use inputtext, but my expected native language is Japanese.
Japanese is already supported by Babylon.js,
IME cannot be used in inputtext because IME is not working.

**Describe the solution you'd like**

In the discussion, RaananA was able to input Japanese in a pseudo manner by using the native input field as one of the solutions.
However, I want to input Japanese using IME with inputtext without displaying the native input field.

**Discussion**

https://forum.babylonjs.com/t/i-want-to-input-japanese-with-input-text/15796

**Comment by RaananW** [comment]
For future reference - IME (Input method editors) - https://docs.microsoft.com/en-us/windows/uwp/design/input/input-method-editors are a standard way to input many different languages while still using an english-layout keyboard. The input to the text field is still english (and is being converted while typing). Language like Japanese and Chinese are using it, and they are supported in a native input field.

**Comment by n9512378** [comment]
Perhaps an HTML element input, is a better general solution.

Reference Layaair engine
https://layaair2.ldc2.layabox.com/demo2/?language=zh&category=2d&group=Text&name=InputMultiline

**Comment by RaananW** [comment]
we cannot use solely an HTML element, as Babylon native doesn't support HTML elements. We will need to consider a more abstract solution, though it seems like we will eventually be forced to use an HTML element, at least for the web version

**Comment by thomlucc** [comment]
No traction. Might be re-open if IME is supported in the Canvas API
