### ISSUE TITLE
Can't generate bounding info for int8 meshes

### ISSUE THREAD

**Issue by stojg** [BabylonJS/Babylon.js#9429]
Hi!

It's possibly to use GL_BYTE (int8) arrays for vertex data according to https://forum.babylonjs.com/t/using-gl-byte-for-vertex-arrays/15349 but a hardcoded float size of 4 doesn't allow bounding info to be generated for GL_BYTE vertex meshes, see https://github.com/BabylonJS/Babylon.js/blob/f64b0af5d1e97597f76b7dfe5d25bd122d478628/src/Meshes/geometry.ts#L277

How to reproduce:
See the example at https://playground.babylonjs.com/#U1CZV3 and click the rectangle and observe the error in the console

**Comment by deltakosh** [comment]
I'll take care of it :)
