### ISSUE TITLE
RecastJSPlugin Choppy Movement since 4.2.0 RC6

### ISSUE THREAD

**Issue by MackeyK24** [BabylonJS/Babylon.js#9468]
The RecastJSPlugin now has choppy movement that used to smooth as a baby's but. But Since the 4.2.0-RC6 update now the movement is **CHOPPY**

Here is an example playground... Click around as see how choppy the box move around:

https://playground.babylonjs.com/#X5XCVT#261

**Comment by sebavan** [comment]
Looks like it might come from https://github.com/MackeyK24/Babylon.js/commit/5ed4724f80c7b03573148986a7fb12abc124e91e
