### ISSUE TITLE
Black surfaces for some KHR_texture_basisu textures.

### ISSUE THREAD

**Issue by donmccurdy** [BabylonJS/Babylon.js#9503]
For the attached file using `KHR_texture_basisu`, textures 1-3 are already power-of-two dimensions. Textures 4-6 are NPOT, and are resized by `toktx`. The dimensions of the mipmaps generated by `toktx` are below:

![Screen Shot 2020-11-28 at 8 41 28 PM](https://user-images.githubusercontent.com/1848368/100533513-30f56a00-31ba-11eb-91de-4cae6c39f7ed.png)

For some reason, this model is rendering correctly in three.js, but displays black surfaces for textures 4-6 in babylon.js. Because all final textures have power-of-two dimensions, I don't think this is a WebGL compatibility issue. It may be related to textures 4-6 having non-square dimensions? Or something unexpected in the generated KTX2 file?

Further context in https://github.com/donmccurdy/glTF-Transform/issues/144 and https://github.com/KhronosGroup/KTX-Software/issues/345.

**Repro**
- Bug repro on [playground](https://playground.babylonjs.com):

[Archive.zip](https://github.com/BabylonJS/Babylon.js/files/5611653/Archive.zip)

- Expected result:

![Screen Shot 2020-11-28 at 8 38 29 PM](https://user-images.githubusercontent.com/1848368/100533472-b0366e00-31b9-11eb-9b0f-0a331e554e4c.png)

- Current result:

![Screen Shot 2020-11-28 at 8 38 24 PM](https://user-images.githubusercontent.com/1848368/100533474-b2003180-31b9-11eb-997d-fcecec868d6f.png)

**Screenshots**

See above.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Firefox
 - Version: 82

**Comment by sebavan** [comment]
Thanks a lot for your report @donmccurdy :-)

Adding @Popov72 our KTX2 master

**Comment by Popov72** [comment]
Thanks for the report, fixed by #9507

**Comment by donmccurdy** [comment]
Awesome, thank you! :)
