### ISSUE TITLE
Add option to use keyboard rotate with Universal Camera

### ISSUE THREAD

**Issue by PolygonalSun** [BabylonJS/Babylon.js#9521]
Users have suggested that they'd like a built-in solution for being able to rotate a camera in-scene, using the keyboard.

Potential Solution:
Create a toggle/flag to allow this functionality to be enabled.

**Discussion**
https://forum.babylonjs.com/t/is-there-an-option-to-rotate-a-universalcamera-with-left-right-arrows/16133

**Comment by deltakosh** [comment]
I don't even think we need a flag as it is new

**Comment by deltakosh** [comment]
I would simply add a new camera.rotateLeftKeys and camera.rotateRightKeys

**Comment by sebavan** [comment]
Fixed by the previous PR
