### ISSUE TITLE
Add in a canvas resize to fit size of CreateScreenshot()

### ISSUE THREAD

**Issue by PatrickRyanMS** [BabylonJS/Babylon.js#9556]
Due to the limitations of CreateScreenshotUsingRenderTarget when it comes to the render target used in glTF transmission or post effects like the glow layer, CreateScreenshot seems like the easiest solve to those issues. However we need to be able to control the size of the canvas when creating screenshots like we do with CreateScreenshotUsingRenderTarget so that if I pass a square format render on a canvas that is rectangular, we resize the canvas to a square before rendering out the screenshot without distortion. 

https://playground.babylonjs.com/#ZB3SRQ#6 can be used as a test PG for this feature.

**Comment by deltakosh** [comment]
Fixed by https://github.com/BabylonJS/Babylon.js/commit/9a709bef52c5fbef78356736f28de4c2eb62dfa4

**Comment by deltakosh** [comment]
Solution with new code;
```
                var currentCanvasSizeWidth = activeCanvas.style.width;
                var currentCanvasSizeHeight = activeCanvas.style.height;
                activeCanvas.style.width = renderWidth + "px";
                activeCanvas.style.height = renderHeight + "px";
                engine.resize(true);
                BABYLON.ScreenshotTools.CreateScreenshotWithResizeAsync(engine, scene.activeCamera, renderWidth, renderHeight).then(() => {
                    activeCanvas.style.width = currentCanvasSizeWidth;
                    activeCanvas.style.height = currentCanvasSizeHeight;
                    engine.resize(true);                        
                })
```
