### ISSUE TITLE
Add support for data texture for morph target

### ISSUE THREAD

**Issue by deltakosh** [BabylonJS/Babylon.js#9560]
Store morph target data into texture to get more targets supported
(like what was done for bones)

Make sure to test with:
- [x] Effect layer
- [x] Shadows
- [x] OutlineRenderer
- [x] Depth Renderer
- [x] Geometry buffer
- [x] Node Material

**Comment by EricEisaman** [comment]
I would like to contribute to this if possible.  

How can I currently intercept and add to the vertex and fragment shader sources of a PBR material loaded with a GLTF asset prior to the compilation of the shader program?

**Comment by deltakosh** [comment]
Wrong fix id

**Comment by EricEisaman** [comment]
@deltakosh Would you consider the following API?

API :
instance.instancedBuffers.morphTargets.targetName.influence

**Comment by deltakosh** [comment]
It will not use instance buffer but a texture array actually :)

**Comment by EricEisaman** [comment]
So something like?:

API :
instance.textureArrays.morphTargets.targetName.influence

**Comment by deltakosh** [comment]
Actually there will be no API change. Instead of storing the targets into attributes, we will store them into texture arrays (same was as what we did for bones)

Influence values are stored into uniforms so what you are suggesting will not work unfortunately

**Comment by EricEisaman** [comment]
@Influence values are stored into uniforms so what you are suggesting will not work unfortunately

Are these influence value uniforms going to be data textures in order to accommodate for the per instance customized influence values?

**Comment by deltakosh** [comment]
Not for first version. I mean, it is a different issue. Having influences as an attribute can be a different issue
