### ISSUE TITLE
Improved mouse wheel zooming...

### ISSUE THREAD

**Issue by lovettchris** [BabylonJS/Babylon.js#9566]
**Is your feature request related to a problem? Please describe.**
ArcRotateCamera mouse wheel zooming is unnatural, it should zoom into the mouse location like just about every game out there now.

**Describe the solution you'd like**
Zoom to mouse location (see Supreme Commander).

**Discussion**
I've implemented a prototype here: https://playground.babylonjs.com/#0Y0ALJ#14

It would be nice if this was integrated into ArcRotateCamera  or if a new built in camera was designed with this behavior in mind so folks don't have to cut & paste all this code.  A built in version could also be done without the need for window.setTimeout to track camera animations.  (could also give cameras a callback to tell client when they have stopped moving).

**Comment by deltakosh** [comment]
Hey please first discuss about it on the forum 👍 (I like the idea anyway)

**Comment by lovettchris** [comment]
There is a forum thread but there is not much activity:
https://forum.babylonjs.com/t/arcrotatecamera-with-rotation-and-zoom-center-about-cursor/7543/6

**Comment by deltakosh** [comment]
Pinging @PolygonalSun

**Comment by lovettchris** [comment]
And there is another thread here where someone else likes my proposal:
https://forum.babylonjs.com/t/how-to-set-zooming-based-on-the-position-of-cursor-in-mouse-wheel/13652/7

**Comment by lovettchris** [comment]
I saved a new version #14 that makes the debug stuff optional, just pass "false" to addControls and the camera target and hit plane debug visualizations will disappear.  [Mouse wheel zoom to mouse position | Babylon.js Playground](https://playground.babylonjs.com/#0Y0ALJ#14)

**Comment by deltakosh** [comment]
Do you mind trying to start a PR? We can use it as a support to discuss

**Comment by lovettchris** [comment]
Sure what do you recommend though?  A new type of camera? settings on ArcRotateCamera, or modify some other camera, like the UniversalCamera ?

**Comment by deltakosh** [comment]
Ideally I would recommend a new camera input maybe? How do you feel regarding this idea?

**Comment by PolygonalSun** [comment]
@lovettchris this is a great idea.  Personally, I agree with @deltakosh on this.  It should be a type of camera input that can be added to the attached inputs, kinda like BaseCameraMouseWheelInput or something that could be used by all cameras that have access to the mouse wheel.  If you wanna give this a shot, please make sure to keep me in the loop and I'll help in any way that I can.

**Comment by lovettchris** [comment]
@PolygonalSun , I'm not too familiar with the attachable camera input idea, could you send me a coded stub to point me in the right direction and I will fill in the details... ?

**Comment by lovettchris** [comment]
Something changed in BablyonJS?  I just had to adjust the mouse wheel amount so it doesn't zoom too much.  See https://playground.babylonjs.com/#0Y0ALJ#91

**Comment by lovettchris** [comment]
See my new PR: https://github.com/BabylonJS/Babylon.js/pull/10069

**Comment by sebavan** [comment]
Closed by the previous PR
