### ISSUE TITLE
AdvancedDynamicTexture errors

### ISSUE THREAD

**Issue by javismiles** [BabylonJS/Babylon.js#9592]
I have a model loaded in babylon successfully, with a texture applied

I want to add floating labels in the 3d space,
so I try to use

var advancedTexture = GUI.AdvancedDynamicTexture.CreateFullscreenUI("UI");

but every time I use that line, I get errors
either getcomponent null error or onsuccess callback error from append mesh
babylon.js:16 Uncaught TypeError: Cannot read property '_getComponent' of null

what is the best way to add floating labels in 3d space without errors?
thank you very much

**Comment by javismiles** [comment]
this is somebody elses example but they get similar error
https://playground.babylonjs.com/#YWDWH9

**Comment by deltakosh** [comment]
Please read issue templates
Use the forum for questions
