### ISSUE TITLE
issues lighting a blender exported model with baked texture

### ISSUE THREAD

**Issue by javismiles** [BabylonJS/Babylon.js#9593]
I export a blender model with a shader that gets baked to a texture,
and I load it successfully in babylon.js

issue is the lighting.

if I use
var environment = scene.createDefaultEnvironment({
createGround: false,
enableGroundShadow: false,
groundYBias: 1,
groundOpacity: 0.5,
});

then I can see the texture applied to the model, great. But I want to light it better. So I add lights like:

var light = new PointLight("pointLight", new Vector3(50, 333, 1), scene);
light.diffuse = new Color3(1, 1, 1);
light.specular = new Color3(0, 0, 0);
light.intensity = 10000000;

but the light behaves very strangely and only if I put a super high intensity I can see something.
Also If I give it a neutral color, it colors the entire object so I don't see its texture properly anymore.

If instead I don't use the createdefaultenvironment line, then similar thing happens.

the question is, how can I bring more neutral light/brightness to different parts of my model without changing
the colors that the applied texture is giving it?

If I choose a light with neutral color it just gets rid of the color in the texture

thank you

(issues lighting a blender exported model with baked texture)

**Comment by deltakosh** [comment]
Please read issue templates
Use the forum for questions
