### ISSUE TITLE
Issue creating floating label in 3d space

### ISSUE THREAD

**Issue by javismiles** [BabylonJS/Babylon.js#9595]
Im trying to create simple floating text labels around the 3dspace,
I didn't find the way to do them by themselves, so I am trying this:

// Create the 3D UI manager

    var manager = new GUI.GUI3DManager(scene);

    // Create a horizontal stack panel

    var panel = new GUI.StackPanel3D();

    panel.margin = 0.02;

    manager.addControl(panel);

    panel.position = new Vector3(0, 300, -50);

    panel.scaling = new Vector3(100, 100, 100);

    var button = new GUI.Button3D("orientation");

    panel.addControl(button);

    var text1 = new GUI.TextBlock();

    text1.text = "Trying to create text label";

    text1.color = "white";

    text1.fontSize = 24333;

    text1.fontFamily = "Arial";

    button.content = text1;

and I can see the panel, the rectangular panel appears well,
and the text as well

but how can I make text labels appear without the panel, just by themselves?
and that I can position anywhere I want in the 3d space

thank you

**Comment by deltakosh** [comment]
Please read issue templates
Use the forum for questions
