### ISSUE TITLE
model looks well on desktop and laptop, but not on android mobile phone 

### ISSUE THREAD

**Issue by javismiles** [BabylonJS/Babylon.js#9597]
I have a model loaded with a texture applied,
it can be seen here
https://festive-jennings-45c799.netlify.app/

if I load it on a desktop or laptop it looks all good

but If i load it in an android xiaomi mi a2 mobile phone with chrome browser,
the texture does not appear, its black, I see the texts and the rims of the texture,
something seems to be off maybe with the lights, but its very strange that all looks fine in desktop and laptop

thank you for your help

**Comment by deltakosh** [comment]
Please read issue templates
Use the forum for questions
