### ISSUE TITLE
Cannot disable WebXR in VRExperienceHelper

### ISSUE THREAD

**Issue by chuen1118** [BabylonJS/Babylon.js#9604]
I would like to disable WebXR when using VRExperienceHelper, so I set the `useXR` in options to false when creating VRExperienceHelper, but the value was ignored.

https://github.com/BabylonJS/Babylon.js/blob/c8e5f6bae8f842bb3b4b934a49c7c94e5c95cb12/src/Cameras/VR/vrExperienceHelper.ts#L726-L728

The value would be forced back to true.

**Comment by RaananW** [comment]
WebXR will be forced when WebVR is not available or the flag is set to true. I would anyhow recommend not to use WebVR, as it is not available in any modern browser.
