### ISSUE TITLE
Example of Viewer configuration doesn't work properly

### ISSUE THREAD

**Issue by eldinor** [BabylonJS/Babylon.js#9608]
The example of full configuration in the Babylon Viewer docs 4 doesn’t work properly.
[https://doc.babylonjs.com/extensions/babylonViewer/defaultViewerConfig#the-full-example](url)

The loading screen and model is OK, but navigation bar buttons don’t work.
The example code from Docs is here - https://codepen.io/BabylonJS/pen/KBXVdw 

... it used to work correctly, so it might have been a small architectural change that we made and we simply didn’t check it.
[https://forum.babylonjs.com/t/documentation-example-doesnt-work-properly/16604/6](url)

This the **only example with the full recreating of Viewer configuration**.

**Comment by sebavan** [comment]
Adding @RaananW for the viewer and cc @thomlucc FYI

**Comment by RaananW** [comment]
This was crazy to debug for some reason, but I found the issue eventually. It happened due to wrong function binding (a one-line fix...)

This codepen - https://codepen.io/raananw/pen/gOPZJVY  will work after this is merged

**Comment by RaananW** [comment]
Next nightly will have the fix.
