### ISSUE TITLE
Bitmap Fonts

### ISSUE THREAD

**Issue by abhishekrathore03** [BabylonJS/Babylon.js#9634]
**Allow Support to Bitmap Fonts**
Bitmap fonts are combination of an image (containing required characters) & and data file explaining everyframe of the image

As bitmap fonts are quite important to game development, requesting you to please add support at the erliest.
This was discussed here as well - https://forum.babylonjs.com/t/rendering-bmfonts/14698

**Comment by sebavan** [comment]
We are not considering to add the support at the moment but are totally fine with external contributions, so please, do not hesitate to create a PR for it.

At the moment we are relying on canvas 2d for text on the web and have an embedded text support planned in Native.

**Comment by deltakosh** [comment]
@abhishekrathore03 interested into doing a PR ?

**Comment by abhishekrathore03** [comment]
> @abhishekrathore03 interested into doing a PR ?

Yes, but not now as occupied in some other projects.
May work on it after couple of Months.

**Comment by daoshengmu** [comment]
> We are not considering to add the support at the moment but are totally fine with external contributions, so please, do not hesitate to create a PR for it.
> 
> At the moment we are relying on canvas 2d for text on the web and have an embedded text support planned in Native.

I haven't taken a look at how Babylon.js uses canvas 2d to render texts in WebGL. I would guess for a text gui, Babylon.js will create a 2d canvas to draw texts and output the result into an `ImageData`. Then, using WebGL `texImage2D()` to draw this `ImageData`. (https://forum.babylonjs.com/t/how-to-put-2d-text-in-3d-world/2584)

If it is like what I said, it would cause performance bottlenecks from `ctx.getImageData()` and when uploading this imageData into a WebGL texture. More worse, if we are considering tens of GUI in a scene need to draw text, that would be complexity N x the time spent of the operations above.

**Comment by thomlucc** [comment]
You can add it as an [extension](https://doc.babylonjs.com/guidedLearning/devStories/showroomCamera), but we don't think it should be part of the core engine.
