### ISSUE TITLE
Defining input sensibility

### ISSUE THREAD

**Issue by jasonsturges** [BabylonJS/Babylon.js#9697]
My interpretation is probably off in the Americas, but I'm not sure I understand the term sensibility in Babylon:

```js
/**
 * Defines the panning sensibility of the inputs.
 * (How fast is the camera panning)
 */
@serialize()
public panningSensibility: number = 50.0;
...
public rotationSensibility: number = 1;
public radiusSensibility: number = 1;
public zoomingSensibility: number = 25.0;
public gamepadRotationSensibility = 80;
public gamepadMoveSensibility = 40;
public angularSensibilityX = 1000.0;
public heightSensibility: number = 1;
...
```

While I would normally think of this as "sensitivity", I can see "sensibility" as "a perception or responsiveness towards something", or "ability to receive (tactile) sansations" as relating to sensitiveness.

Just curious if this was intended.  Probably have a major implication to the API if changed.

**Comment by sebavan** [comment]
Yup it should have been sensitivity but french ppl coding in english :-) and now we ca not update it due to our back compat policy and the e xtent of the change.
