### ISSUE TITLE
Having influences as an attribute (per vertex)

### ISSUE THREAD

**Issue by EricEisaman** [BabylonJS/Babylon.js#9733]
Not for first version. I mean, it is a different issue. Having influences as an attribute can be a different issue

_Originally posted by @deltakosh in https://github.com/BabylonJS/Babylon.js/issues/9560#issuecomment-754031765_

**Comment by EricEisaman** [comment]
Having morph target influences as instance attributes will be a very powerful addition.

**Comment by deltakosh** [comment]
But it will be a different one as well: so far influences are PER mesh and if it becomes an attribute it will be PER vertex

**Comment by EricEisaman** [comment]
@deltakosh  RE: ```But it will be a different one as well```
Should I open a new issue and close this one or rename this one?

**Comment by deltakosh** [comment]
Well I'm not sure we want that feature yet :) It should only be implemented at instances level and not for a regular mesh. That seems quite a lot.

My only question would be: do you want to try to develop it?

**Comment by FrameBuffer4096** [comment]
Once the morph targets for a particular model are exposed via a single uniform data texture, I can study the layout used to build the texture and create a new instance buffer holding a morph target influences object which in turn provides getters and setters for each morph target.  Are you close to landing the data texture layout of morph targets?

**Comment by deltakosh** [comment]
Probably before mid feb to give you a fair estimate

**Comment by deltakosh** [comment]
Closing for now as we do not plan to add the feature.

Please reopen if someone is willing to do a PR for it

**Comment by EricEisaman** [comment]
Sorry.  I am currently in crunch mode.
