### ISSUE TITLE
[XR] Move to the new hand tracking API

### ISSUE THREAD

**Issue by RaananW** [BabylonJS/Babylon.js#9751]
As part of the changes there is now a way to get all poses for all 25 joints in one go (instead of querying per joint):

https://immersive-web.github.io/webxr-hand-input/#xrframe-interface

**Comment by cabanier** [comment]
Also, the WebXR Hands API was updated so you need to update your library.

**Comment by RaananW** [comment]
Yep, working on that 😊
Thanks!

**Comment by RaananW** [comment]
This was implemented already
