### ISSUE TITLE
More text formatting options

### ISSUE THREAD

**Issue by Modcat** [BabylonJS/Babylon.js#9778]
I love that Babylon is using text wrapping, but there is no clear demonstration on how to apply it https://doc.babylonjs.com/typedoc/enums/babylon.gui.textwrapping

So maybe some docs there and also things like, columns, and even path wrapping that is now being supported in Firefox
https://blog.logrocket.com/creative-text-flows-using-css-shapes/

I was thinking more along the lines of allowing any 3D object to have boundaries and where applicable to the wrapper text it would move the text onto new lines and automatically allow wrapping when the external object was overlapping the text wrapping area.

**Comment by deltakosh** [comment]
Hello please use forum.babylonjs.com for discussion
