### ISSUE TITLE
[Playground] Tabbed edits and Build feature

### ISSUE THREAD

**Issue by CedricGuillemet** [BabylonJS/Babylon.js#9781]
I love the PG and I'd like to see 2 features that would allowing use it not only for prototyping.

1) Tabbed edit
tabs for switching between multiple scripts and not only one. Tabbed scripts are concatenated when running.

2) Build option
I'd like to get a self contained package (.zip) with the selected babylonjs version and all needed dependencies. I could then unzip it my CDN with no configuration. No editor in the package, just the full screen experience.
other build destinations possible with just 1 click:
- azure web hosting
- github repo folder (for github.io)
- ...

**Comment by deltakosh** [comment]
Hello, good ideas!

Wanna take a stab at it?

For 2, we already have the zip download that is doing almost the same thing (we are simply keeping the dependencies as links)

**Comment by CedricGuillemet** [comment]
Closing. Duplicate with https://github.com/BabylonJS/Babylon.js/issues/10361
