### ISSUE TITLE
Too much wheel sensitivity on Chromium / WebKit-based browsers (plus likely upcoming Firefox) in some examples.

### ISSUE THREAD

**Issue by emilio** [BabylonJS/Babylon.js#9799]
# Bugs

- Bug repro on [playground](https://playground.babylonjs.com): https://playground.babylonjs.com/#ARN6TJ#5
- Expected result: Moving the wheel reacts somewhat sensibly
- Current result: Even a single wheel tick causes massive amounts of zoom.

This was originally reported in https://bugzilla.mozilla.org/show_bug.cgi?id=1686655. Looking a bit into it, it seems like `Cameras/Inputs/arcRotateCameraMouseWheelInput.ts` uses the event's `deltaY` without looking at `deltaMode` first.

On the current release version of Firefox, that yields a `DOM_DELTA_LINES` delta, so the number of lines is relatively small and the camera zooms smoothly.

On Firefox Nightly or Chromium / WebKit-based browsers, the delta without checking for `deltaMode` first gets returned as `DOM_DELTA_PIXELS` (see [this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1392460) for the Firefox change)), and thus the delta is much larger, causing excessive zooming.

`Cameras/Inputs/BaseCameraMouseWheelInput.ts` does deal with this correctly (see `_ffMultiplier` in that file). In order to preserve behavior exactly, on Firefox you can just read out `deltaMode` before the actual deltas to get the lines-based delta. But on Chromium you probably want to divide by `_ffMultiplier` to make the wheel more sensible.

Feel free to close if this is working as intended, though I'd be somewhat surprised if that was the case.

**Comment by deltakosh** [comment]
Thanks a ton. This is super useful

**Comment by PolygonalSun** [comment]
This should be fixed by this PR: https://github.com/BabylonJS/Babylon.js/pull/9814

**Comment by sebavan** [comment]
Reopen as the fix is reverting **https://github.com/BabylonJS/Babylon.js/pull/10034**

**Comment by sebavan** [comment]
@PolygonalSun FYI

**Comment by sebavan** [comment]
I am looking into it, and if anybody wants to repro, they should use https://playground.babylonjs.com/#ARN6TJ#38 on FF :-)

**Comment by sebavan** [comment]
Should be fixed back by #10101
