### ISSUE TITLE
Runtime decorations

### ISSUE THREAD

**Issue by adamshaylor** [BabylonJS/Babylon.js#9828]
## Is your feature request related to a problem? Please describe.

I work at [Spectrum](https://spectrumcustomizer.com/), a 3D product customization platform. We’re currently evaluating Babylon and glTF for the next generation of our rendering architecture. One feature we will need to port over from our current architecture applies decorations and personalizations to models. The way we do this in our current rendering architecture is to copy a target mesh, give it its own material, apply a base texture to it, and change the render order so the decoration is rendered last and therefore appears on top. This is a lot like how [Babylon decals](https://github.com/BabylonJS/Babylon.js/blob/master/src/Meshes/Builders/decalBuilder.ts) work, but decals have some limitations.

![A jacket customizer we built for Levi’s with an embroidered decoration feature](https://www.spectrumcustomizer.com/wp-content/uploads/2018/10/client-screenshot-levis3.jpg)

1. **UVs do not appear to be preserved.** Instead, they’re [based on the x/y coordinates of the vertices](https://github.com/BabylonJS/Babylon.js/blob/4.2.0/src/Meshes/Builders/decalBuilder.ts#L237-L238). This leads to distortions which, in the context of a product customizer, do not yield accurate representations of the final product.
2. **Decals are defined in world coordinates.** 3D modelers need to be able to carefully place decorations using the local coordinate system of the target model. We’ve tried creating a UI tool that uses picking to place decals, but it would be better to use local coordinates so we can follow our clients’ placement specifications exactly. We’ve also encountered complications when we transform the model instead of the camera (which is what our clients prefer) in spite of using a [`TransformNode`](https://doc.babylonjs.com/typedoc/classes/babylon.transformnode). I assume the use of world coordinates will also lead to problems when assigning material properties such as the occlusions of the underlying model (e.g. [printing onto a speaker mesh](https://www.spectrumcustomizer.com/casestudy/jbl-customizer/)).
3. **Preservation of underlying normals is unclear.** It’s sometimes necessary to model product details with normal maps. [The `normal` option](https://github.com/BabylonJS/Babylon.js/blob/4.2.0/src/Meshes/Builders/decalBuilder.ts#L39) defaults to world up and [transforms the vertex normals of the decal](https://github.com/BabylonJS/Babylon.js/blob/4.2.0/src/Meshes/Builders/decalBuilder.ts#L57-L65). I’m not clear on why that is necessary or if it’s possible to leave the decal’s normals un-transformed.

## Describe the solution you'd like

We would like a feature that would:

* Apply decorations to a model at runtime.
* Define the position and transformations of the decoration relative to the target model.
* Carry the target model’s UVs and normals over to the decoration.
* Mix and match the target model’s material properties with independent decoration materials to support use cases like printing, embroidery, etching, and engraving on both soft and hard goods
* Material properties like occlusions that are selectively applied to the decoration also line up exactly with the target model (again, thinking of the example of printing onto a speaker mesh with occlusions).

In our email conversation, you’d suggested modifying decals to preserve UVs and normals as the best approach. Another option we were exploring prior to our exchange was compositing a model’s material with a decoration material without creating any new models. The benefit is that all the coordinate system problems go away. The drawback, we’ve found, is that doing this compositing is quite complicated. We defer to you as to how best to approach this problem.

## Discussion

The initial discussion for this feature occurred by email. We appreciate you all taking a look and letting us know what you think. If you‘d like to see the source code from our experiments, let us know and we can make it available to you.

**Comment by deltakosh** [comment]
Hey @adamshaylor and thanks for this descriptive issue!

So in a nutshell, we want to offer the option for people to create decals with:
- uvs capture
- normals capture

Defining the decal relatively to the parent can be done with:
```
decal.setParent(sourceMesh)
```

This should move it as a child of the parent mesh and thus all its position/rotation/scaling will be local to parent mesh

**Comment by deltakosh** [comment]
@adamshaylor do you mind sharing a simple playground with an example where we can see the current issue?

For instance I just realized that normals are already captured. I will add uvs though

**Comment by adamshaylor** [comment]
@deltakosh, I interpreted this code to mean that the normals are transformed based on the normal option, which defaults to world up:

https://github.com/BabylonJS/Babylon.js/blob/4.2.0/src/Meshes/Builders/decalBuilder.ts#L57-L65

I’m honestly not clear what that transformation does or what it’s for. Would it make sense to give us the option to leave the original normals un-transformed?

**Comment by deltakosh** [comment]
I published that update now:
https://github.com/BabylonJS/Babylon.js/blob/master/src/Meshes/Builders/decalBuilder.ts#L40

You can provide a new option to let the system capture the untransformed normals
