### ISSUE TITLE
[GE] - Lines get left on the canvas when dragging a GUI button

### ISSUE THREAD

**Issue by PirateJC** [BabylonJS/Babylon.js#9840]
When dragging a GUI button on the canvas, lines are being left behind and stick to the canvas.

![image.png](https://images.zenhubusercontent.com/5dcb34efa1442a0001945170/247f02fe-c053-4afe-98dc-b883048a3977)

**Comment by msDestiny14** [comment]
Status update: Think I got this one, coming in the next PR.
