### ISSUE TITLE
Add optional Mesh parameter to TextureDome?

### ISSUE THREAD

**Issue by Exolun** [BabylonJS/Babylon.js#9846]
Recently I've been working on some optimizations to utilize cloning and instancing in situations where identical meshes are being used.  

I was wondering if it would help to pass in a cloned sphere for the `textureDome` in cases where there are scenes with many 360 content objects of the exact same size? (Wasn't sure how much of a benefit you see from cloning versus instantiating new objects)

If it is potentially beneficial for perf, could you add an optional `mesh` parameter to the `textureDome` options? 

Thanks!

**Comment by deltakosh** [comment]
That sounds a good idea..let me ask @RaananW for his thoughts

**Comment by RaananW** [comment]
Of course! Makes sense for this use case. 
Want to submit a PR? Perfectly fine if not, I'll assign it to me and work on that this or next week.

**Comment by Exolun** [comment]
@RaananW It'll be a little while before I can tackle this one, so if you have time to squeeze it in I'd appreciate it!
