### ISSUE TITLE
Help!why switching models causes memory growth

### ISSUE THREAD

**Issue by Niwei** [BabylonJS/Babylon.js#9854]
When I use scene loaded in OBJ file or GLTF file,and switching tab0 and tab1 many times，which cause the memory growth！
I've done some optimization but without effect。
The  memory  screenshot，I find `574564564.mtl`  in the memory and not deallocate
### obj memory screenshot
![image](https://raw.githubusercontent.com/Niwei/niwei.github.io/main/images/obj_memory.png)
![image](https://raw.githubusercontent.com/Niwei/niwei.github.io/main/images/obj_memory2.png)
### gltf memory screenshot
![image](https://raw.githubusercontent.com/Niwei/niwei.github.io/main/images/gltf_memory.png)
### The test link
[obj test](https://niwei.github.io/)
[gltf test](https://niwei.github.io/?type=gltf)
### The test code
[test code](https://github.com/Niwei/niwei.github.io/blob/main/index.html)

**Comment by deltakosh** [comment]
Please use the forum for question as stated in the template
