### ISSUE TITLE
Enable refraction to use local cube maps

### ISSUE THREAD

**Issue by PatrickRyanMS** [BabylonJS/Babylon.js#9862]
Right now refraction in SSS does not use local cube maps which means we have no control over scaling or boundingbox size when using reflection probes. The idea would be to have some control over the size of the refracted cube texture so that the scale of the refracted image is realistic. Right now probes used for refraction are creating refractions of the environment that are far too large to be believable.

Test scene: https://playground.babylonjs.com/#RJN64I

**Comment by Popov72** [comment]
Fixed by #10042 

PG: https://playground.babylonjs.com/#RJN64I#5
