### ISSUE TITLE
BUG with Control._GetFontOffset when using font size as !important 

### ISSUE THREAD

**Issue by gabrielheming** [BabylonJS/Babylon.js#9863]
Two threads have been created around this issue:

https://forum.babylonjs.com/t/bug-with-control-getfontoffset-when-using-font-size-as-important/17981
https://forum.babylonjs.com/t/textblock-line-spacing/17963

I will create a PR with the solution

**Comment by deltakosh** [comment]
Thanks!

**Comment by kadinuguru** [comment]
Hi, Fix for this bug is throwing CSP errors. Reverting to the original fixes CSP
