### ISSUE TITLE
File picking is broken in sandbox

### ISSUE THREAD

**Issue by zeux** [BabylonJS/Babylon.js#9879]
The sandbox available at https://www.babylonjs.com/sandbox doesn't work with GLB files correctly anymore:

- Dragging a file onto the window now results in a download prompt for that file, instead of the file being loaded in the viewer
- Pressing the "Open scene" button in the bottom right and selecting a file results in the following JS error:

```
Uncaught TypeError: Cannot read property 'loadFiles' of undefined
    at Object.onFilesPicked (babylon.sandbox.js:16)
    at t.onFilePicked (babylon.sandbox.js:16)
    at onChange (babylon.sandbox.js:16)
    at Object.l (babylon.sandbox.js:37)
    at p (babylon.sandbox.js:37)
    at babylon.sandbox.js:37
    at v (babylon.sandbox.js:37)
    at at (babylon.sandbox.js:37)
    at ot (babylon.sandbox.js:37)
    at lt (babylon.sandbox.js:37)
```

This happens on stable Chrome on Windows 10.

**Comment by zeux** [comment]
P.S. This works correctly in MS Edge for some reason.

Version of Chrome (that doesn't work): Version 88.0.4324.104 (Official Build) (64-bit)
Version of Edge (that does work): Version 88.0.705.56 (Official build) (64-bit)

**Comment by Popov72** [comment]
It does work for me in Chrome 88.0.4324.104 (Official Build) (64-bit).

Have you tried to clean the cache of the browser?

**Comment by zeux** [comment]
Yeah this persists after clearing the cache and in incognito mode. I should mention that this definitely used to work, I often use sandbox as a glTF viewer.

**Comment by deltakosh** [comment]
I cannot repro either

Which OS are you on?

**Comment by zeux** [comment]
After restarting Chrome, clearing the cache, restarting Chrome again, the bug doesn't reproduce anymore in Chrome either... ¯\_(ツ)_/¯

**Comment by deltakosh** [comment]
lol no worries! Web :D
