### ISSUE TITLE
Handle LinesMesh when saving/loading .babylon files

### ISSUE THREAD

**Issue by Popov72** [BabylonJS/Babylon.js#9888]
Currently, `LinesMesh` are not handled correctly when saving/loading a .babylon file, see https://forum.babylonjs.com/t/lines-are-not-visible-after-export-babylon/18150

**Comment by deltakosh** [comment]
Wanna check it?

**Comment by Popov72** [comment]
I will do the PR but wanted to finish what I'm doing first, so I have created the issue to track it.
