### ISSUE TITLE
Split RegisterTopRootEvents from the rest of the tools collection

### ISSUE THREAD

**Issue by major-mayer** [BabylonJS/Babylon.js#9898]
**Is your feature request related to a problem? Please describe.**
I am building a custom input and need the static method `RegisterTopRootEvents`for that.
Currently i have to import the whole Tools class to use this method, something like this:
```
import { Tools } from "@babylonjs/core/Misc/tools";
```
This contains a lot of code which i don't need for my purpose and blows up the final budle size.

**Describe the solution you'd like**
I would like to be able to only import the RegistrationTools (?) part of the Tools class that would allow me to use tree shaking and reduce the bundle size.
Maybe it can be done just like with the screenshot tools, that can be imported like i stated above or with the following statement: 
```
 import { ScreenshotTools } from "@babylonjs/core/Misc/screenshotTools";
```
I haven't found something like that for my use case yet.

**Discussion**
You must provide a link to the forum post where the initial discussion happened

**Comment by deltakosh** [comment]
> Discussion
You must provide a link to the forum post where the initial discussion happened

Please discuss on the forum first
