### ISSUE TITLE
GUI: Drop shadow blur does not refresh when blur amount reduced

### ISSUE THREAD

**Issue by PatrickRyanMS** [BabylonJS/Babylon.js#9906]
**Repro**
- https://playground.babylonjs.com/#XCPP9Y#8
- Roll down the GUI hierarchy in the inspector and select No name [Rectangle]
- Change drop shadow blur amount to 60 and hit enter
- Note the gradient blur from the drop shadow surrounding the button
- Change the drop shadow blur amount back to 0 and hit enter
- Expected result: The drop shadow should no longer render since the blur is now 0
- Current result: The outsides of the drop shadow still render, but there are some clear spots at the corners of the button that are no longer rendering the dropshadow.

**Screenshots**
The image below shows the original blurred drop shadow on a rectangle on the top and the result after changing the drop shadow blur back to 0.

![image](https://user-images.githubusercontent.com/31326855/107446693-cc2c8900-6af3-11eb-9a14-29d0486e6a4e.png)

**Comment by deltakosh** [comment]
I'll check:)
