### ISSUE TITLE
GLTF Import and the Right Handed System - issues with WebXR Plane Detection

### ISSUE THREAD

**Issue by VGuerreiro** [BabylonJS/Babylon.js#9935]
Importing GTLF files to a BabylonJS project that uses an Immersive-AR scene requires the use of the Right Handed System, in order to properly import the models with the correct orientation. 
Setting the Right Handed System to true seems to cause issues within the Plane Detection. This causes the Materials to react weirdly and the Shadow Cast not to work properly in the tracked/triangulated planes.

Here's the forum thread with further details regarding the issue (including reproduction in plyaground):
https://forum.babylonjs.com/t/issues-importing-gltf-models-in-a-webxr-ar-immersive-scene/18398

**Comment by VGuerreiro** [comment]
Just to tag @RaananW :)

**Comment by RaananW** [comment]
> Importing GTLF files to a BabylonJS project that uses an Immersive-AR scene requires the use of the Right Handed System

This is the part the bothers me in this ticket - I am not sure this is 100% accurate. Would you be able to reproduce this? Maybe share the model that you find problematic?

The issue with plane detection is actually in the playground and not in plane detection. This playground works correctly - https://playground.babylonjs.com/#98TM63#57 (notice the z-inversion when creating the polygon).

**Comment by VGuerreiro** [comment]
The Import happens, and the GLTF mesh loads. 
It's the orientation that the mesh comes in with that is rotated in the Z-Axis when not using Right Handed System. I tried to rotate it in babylon.js and it quickly rotates back in the wrong direction.
You can see it even in this Playground (https://playground.babylonjs.com/#KDWCZY) from the docs, that the character model is not placed facing the camera, it's facing the wrong way. When turning the Right Handed System on, it's placed as it should.

I think this has to do with the transforms applied when using GLTF as this issue isn't present when using an OBJ file.

In this regard (GLTF facing the wrong way), the main issue is a workflow one - in order to have it placed properly in my scene, I have to either turn Right Handed on or make the asset with the back facing the camera and export it that way from the 3D package.

Here is a link with the model - from OneDrive: https://1drv.ms/u/s!AjstMy_m0nNsjIkqVeTb80zHqE0ejQ?e=cqiKi1

Here are a couple of screenshots: 
- In the 3D package (I use Blender):
![blender_A7nT0FpuRz](https://user-images.githubusercontent.com/10901289/108238053-746bce80-7140-11eb-8328-2759cf59fbff.png)
- The settings I'm using on the exporter: 
![blender_pLXiSqJqBq](https://user-images.githubusercontent.com/10901289/108238112-83528100-7140-11eb-8b91-ba48ffe34d16.png)
- The way it gets placed in the scene when not using the Right Handed System:
![signal-2021-02-17-164550](https://user-images.githubusercontent.com/10901289/108238195-982f1480-7140-11eb-85f4-e0bfde30c669.jpeg)

In regards to the Plane Detection issue, while using the Right Handed System, I still get the same problem with the playrgound you've just linked.
Here a screenshot from my phone (android):
- In this session, the purple material is barely visible on the side edges of the tracked/triangulated planes:
![signal-2021-02-17-165933](https://user-images.githubusercontent.com/10901289/108239496-e264c580-7141-11eb-94cf-3a220d39a2bd.jpeg)

This is exactly what was happening in the other Playground and in my own setup when turning the RightHanded System On.
It looks like the geometry/normals/or something of that sort is inverted and the material is showing weirdly. I think this is why it doesn't render any cast shadows either (from the previously linked playground - if turning right handed on, and in my own setup).

**Comment by thomlucc** [comment]
Cannot reproduce. Please re-open if needed.
