### ISSUE TITLE
PEP.js is now deprecated

### ISSUE THREAD

**Issue by sep2** [BabylonJS/Babylon.js#9950]
**Is your feature request related to a problem? Please describe.**
Related announcement: https://openjsf.org/blog/2021/02/10/pointer-events-polyfill-pep-enters-emeritus-status-at-the-openjs-foundation/

**Describe the solution you'd like**
Remove dependence on PEP.js and use native API instead.

**Comment by deltakosh** [comment]
What about following the issue template? We ask specifically for people to discuss the issue on the forum before coming here so everyone in the community can participate

btw from where precisely do you want to remove pep? playground? sandbox? other places?

**Comment by deltakosh** [comment]
I removed it from all our pages :)
