### ISSUE TITLE
DeviceSourceManager.onDeviceConnectedObservable notifies an observer with undefined event data

### ISSUE THREAD

**Issue by CoPrez** [BabylonJS/Babylon.js#9959]
**Repro**
- [Bug repro on playground](https://www.babylonjs-playground.com/#6S4YDA#6)
  - The bug only repro's with touch events and not pointer events. You can still repro on a desktop browser in device emulator mode ([more info](more info)).
- Expected result: Registering for onDeviceConnectedObservable should only send event data for a valid device.
- Current result: If you register for onDeviceConnectedObservable after a touch event has occurred you will get an immediate callback with undefined event data.

**Desktop (please complete the following information):**
 - OS: MacOS 11.2.1
 - Browser Edge
 - Version 89.0.774.27

**Smartphone (please complete the following information):**
 - Device: Note 10+
 - OS: Android 10
 - Browser: Babylon React Native

**Additional context**
From debugging it looks like the issue is that after a touch event has ended DeviceSourceManager [deletes the entry](https://github.com/BabylonJS/Babylon.js/blob/4a9da4143b9ab67f2f8594fb200e8292b241a47f/src/DeviceInput/InputDevices/deviceSourceManager.ts#L174) into the _devices[DeviceType.Touch][index] array. That means that the _devices[DeviceType.Touch] entry still has a value defined (albeit an Array with no values). Then when you register for the observable event it iterates over _devices and finds the non-undefined _devices[DeviceType.Touch] entry and fires the event with it's value (which is undefined at that point).

**Comment by PolygonalSun** [comment]
I'll take a look and see what's going on.

**Comment by PolygonalSun** [comment]
Fix for this is in PR: https://github.com/BabylonJS/Babylon.js/pull/9991

**Comment by PolygonalSun** [comment]
Closed as fixed
