### ISSUE TITLE
@babylonjs\core in nightly build?

### ISSUE THREAD

**Issue by benaadams** [BabylonJS/Babylon.js#9961]
Haven't worked out where the `@babylonjs\core` files are generated; doesn't seem to be in `dist\preview release` ?

**Comment by benaadams** [comment]
Looks like its generated to `.temp\distES6\core` which isn't included anywhere? 🤔

**Comment by sebavan** [comment]
actually there is a gulp task to generate the es6 packages and npm link them locally for debug purpose: gulp npmPackages-es6

It will generate all of it in .temp/packageES6Dev

**Comment by sebavan** [comment]
The default one used during dev locally are in .temp\localDevES6

**Comment by benaadams** [comment]
Wondering if it should be in a more obvious place and part of the "nightly" builds; so if you are using it it will match what is offically pushed to npm?

**Comment by deltakosh** [comment]
I would recommend moving the discussion to the forum so other people can chime in ;)
