### ISSUE TITLE
Add a flag for influence optimization on the Morph Target Manager

### ISSUE THREAD

**Issue by PirateJC** [BabylonJS/Babylon.js#9970]
Can we add a flag to the morph target manager that allows a user to specify if they want the manager to optimize the shader based on whether the influence of a target is set to zero or not. 

The behavior would likely be that the manager defaults to optimizing (for performance reasons), but the user could turn off the optimization if they want all morph targets evaluated in the shader at once.

**Comment by thomlucc** [comment]
Done
