### ISSUE TITLE
GUI adaptXXXChildren does not take padding into consideration

### ISSUE THREAD

**Issue by LukeTOBrien** [BabylonJS/Babylon.js#9987]
Hello there,

This is not really a bug but it is somthing that I think may have been overlooked.  

I have been playing about with your wonderful GUI controls and on your [position and size documentation](https://doc.babylonjs.com/divingDeeper/gui/gui#position-and-size) it says:

> This means that the usableWidth = width - paddingLeft - paddingRight. Same for usableHeight = height - paddingTop - paddingBottom.

But [when I add padding to the bottom of the text block](https://playground.babylonjs.com/#GL5SIM#38) the container rect does not addapt to the size.  
So in the above, the height is `40px` and paddingBottom is `40px` so the container should be `80px` in height I would say.

What do you think, should the padding be taken into consideration?

---

To put this in context, I am thinking about creating educational scenes to teach children, so I would load a model and next to it display an info box, the text for the info box will be loaded from an external file (JSON or something) so the scene does not know the needed diementions.

**Comment by deltakosh** [comment]
Hello please our forum for discussion (as stated in the issue template)
